### ISSUE TITLE
brute library does not support prefix-less script arguments

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1003]
Library `brute.lua` is using `stdnse.get_script_args("brute.foo")` to retrieve Boolean arguments but `nmap.registry.args["brute.foo"]` for numerical arguments. The reason behind this is not obvious.

One undesirable side effect is that the Boolean arguments can be specified with a short-hand, `--script-args foo=true`, but the numerical ones need to be spelled out, `--script-args brute.foo=2`.

I am proposing the following patch to retrieve the arguments consistently with `stdnse.get_script_args`:

```diff
--- a/nselib/brute.lua
+++ b/nselib/brute.lua
@@ -340,9 +340,9 @@
     o.firstonly = self.checkBoolArg("brute.firstonly", false)
     o.passonly = self.checkBoolArg("brute.passonly", false)
     o.killstagnated = self.checkBoolArg("brute.killstagnated", false)
-    o.max_retries = tonumber(nmap.registry.args["brute.retries"]) or 3
-    o.delay = tonumber(nmap.registry.args["brute.delay"]) or 0
-    o.max_guesses = tonumber(nmap.registry.args["brute.guesses"]) or 0
+    o.max_retries = tonumber(stdnse.get_script_args("brute.retries")) or 3
+    o.delay = tonumber(stdnse.get_script_args("brute.delay")) or 0
+    o.max_guesses = tonumber(stdnse.get_script_args("brute.guesses")) or 0
 
     return o
   end,
```

Please leave a note if you have an explanation for the original inconsistency or have any questions or concerns with the proposed patch. Otherwise I will apply it in a few weeks.

**Comment by dmiller-nmap** [comment]
This looks fine to me. The `stdnse.get_script_args` call in `checkBoolArg` was added in r27081, but the commit message doesn't mention it, so it was probably just a simplification of convenience. I'd say go for it right away.

**Comment by nnposter** [comment]
Committed in r37012 (00c95dda320893d960feb0a3e717d510e169f378)
