### ISSUE TITLE
Possibility of integer overflows in timer code

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1006]
The code related to timers seem to contain quite a few situations where values are being assigned to `int` or `long` variables without reliably avoiding the possibility of overflowing.

A few examples:
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/timing.cc#L177
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/timing.cc#L192
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/timing.cc#L222
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/FPEngine.cc#L1500
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/FPEngine.cc#L2414
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/nmap.cc#L860
https://github.com/nmap/nmap/blob/cb237c4468170fc5c35ca376523b08c2e3804513/nmap.cc#L871

The chance of overflow is quite small in practical terms so I am not sure how much desire there is to clean it up. @dmiller-nmap did opine that it might be worth doing so at least in some cases in his comment on #995:

> For RTT calculations, 2^31 microseconds is 35 minutes. Very unlikely we'd ever hit something like that, but it is currently possible. In timing.cc, we ensure the timeout is never greater than o.maxRttTimeout(), but in FPEngine.cc we do not. This probably should be corrected.

I have put together a rudimentary patch for Ncat, which does not contain nearly as many timing intricacies, but I am leaving it to the community to decide what to do about Nmap, if anything.

```diff
--- a/ncat/ncat_main.c
+++ b/ncat/ncat_main.c
@@ -138,6 +138,7 @@
 #ifndef WIN32
 #include <unistd.h>
 #endif
+#include <limits.h>
 #include <stdlib.h>
 #include <string.h>
 #include <stdio.h>
@@ -185,6 +186,19 @@
     return *sslen;
 }
 
+static int parse_timespec (const char *const tspec, const char *const optname)
+{
+    const long l = tval2msecs(tspec);
+    if (l <= 0 || l > INT_MAX)
+        bye("Invalid %s \"%s\" (must be greater than 0 and less than %ds).",
+            optname, tspec, INT_MAX / 1000);
+    if (l >= 100 * 1000 && tval_unit(tspec) == NULL)
+        bye("Since April 2010, the default unit for %s is seconds, so your "
+            "time of \"%s\" is %.1f minutes. Use \"%sms\" for %s milliseconds.",
+            optname, optarg, l / 1000.0 / 60, optarg, optarg);
+    return (int)l;
+}
+
 /* These functions implement a simple linked list to hold allow/deny
    specifications until the end of option parsing. */
 struct host_list_node {
@@ -414,11 +428,7 @@
             o.conn_limit = atoi(optarg);
             break;
         case 'd':
-            o.linedelay = tval2msecs(optarg);
-            if (o.linedelay <= 0)
-                bye("Invalid -d delay \"%s\" (must be greater than 0).", optarg);
-            if (o.linedelay >= 100 * 1000 && tval_unit(optarg) == NULL)
-                bye("Since April 2010, the default unit for -d is seconds, so your time of \"%s\" is %.1f minutes. Use \"%sms\" for %g milliseconds.", optarg, o.linedelay / 1000.0 / 60, optarg, o.linedelay / 1000.0);
+            o.linedelay = parse_timespec(optarg, "-d delay");
             break;
         case 'o':
             o.normlog = optarg;
@@ -432,11 +442,7 @@
                 bye("Invalid source port %d.", srcport);
             break;
         case 'i':
-            o.idletimeout = tval2msecs(optarg);
-            if (o.idletimeout <= 0)
-                bye("Invalid -i timeout (must be greater than 0).");
-            if (o.idletimeout >= 100 * 1000 && tval_unit(optarg) == NULL)
-                bye("Since April 2010, the default unit for -i is seconds, so your time of \"%s\" is %.1f minutes. Use \"%sms\" for %g milliseconds.", optarg, o.idletimeout / 1000.0 / 60, optarg, o.idletimeout / 1000.0);
+            o.idletimeout = parse_timespec(optarg, "-i timeout");
             break;
         case 's':
             source = optarg;
@@ -458,11 +464,7 @@
             o.nodns = 1;
             break;
         case 'w':
-            o.conntimeout = tval2msecs(optarg);
-            if (o.conntimeout <= 0)
-                bye("Invalid -w timeout (must be greater than 0).");
-            if (o.conntimeout >= 100 * 1000 && tval_unit(optarg) == NULL)
-                bye("Since April 2010, the default unit for -w is seconds, so your time of \"%s\" is %.1f minutes. Use \"%sms\" for %g milliseconds.", optarg, o.conntimeout / 1000.0 / 60, optarg, o.conntimeout / 1000.0);
+            o.conntimeout = parse_timespec(optarg, "-w timeout");
             break;
         case 't':
             o.telnet = 1;
```
I will commit this patch in a few weeks unless anybody voices concerns.

**Comment by dmiller-nmap** [comment]
There is a suggested enhancement at #180 that would change a lot of this code, probably in ways that would obviate a lot of these concerns. It's a bigger undertaking, though, so maybe it's worth fixing some of the more critical of these.

Regarding the Ncat fix, I do like pulling out the `parse_timespec` function; maybe this could even be put into `nbase`. But couldn't we fix some of it by making the `idletimeout`, `linedelay`, and `conntimeout` into `long`s? Not to mention, we have the possibility of overflowing double in `tval2secs` and `tval2msecs`, but we don't bother much with that so far. My point is just that we are currently very lazy about this, and your patch is a step in the right direction.

Possibly also related: #863

**Comment by nnposter** [comment]
> But couldn't we fix some of it by making the `idletimeout`, `linedelay`, and `conntimeout` into longs?

Not trivially. The problem would just shift deeper into the code because Nsock routines, such as `nsock_connect_unixsock_stream` or `event_new`, expect an `int`. As a quick fix I would rather stabilize the type early on, than to dive into full-blown refactoring of the timer code that spans both nmap and ncat.
