### ISSUE TITLE
[Feature Request] CSV output

### ISSUE THREAD

**Issue by AresS31** [nmap/nmap#1017]
Hi, 

I would like to see a new feature to output NMAP results to a CSV file. This could for example be `-oC`, I am aware of the plethor of third party scripts (python, perl, powershell, etc.) that exist to achieve this, however, natively supporting this feature would be nice.

Indeed, for security assessements very often, reports include Excel spreadsheet containing a list of all the detected host and services so being able to generate them directly via NMAP would be welcome.

Thanks,
Alex

**Comment by dmiller-nmap** [comment]
Alex,

There are significant costs to adding new output formats: development, maintenance, and performance. The stance of Nmap's developers is that the two existing machine-readable (predictable) output formats are sufficient and can be converted into other formats using simple existing scripts and libraries. The formats are [grepable](https://nmap.org/book/output-formats-grepable-output.html) and [XML](https://nmap.org/book/output-formats-xml-output.html).

Thanks for the suggestion! Input from real users of Nmap is very important in guiding development, and we hope you will continue to provide feedback.
