### ISSUE TITLE
default_channel.h version number has not been updated

### ISSUE THREAD

**Issue by MythHack** [nmap/nmap#102]
Nmap-update Version definition error in default_channel.h

#define DEFAULT_CHANNEL "6.00"

to
#define DEFAULT_CHANNEL "6.47"

**Comment by dmiller-nmap** [comment]
Thanks for the bug report!

The nmap-update channel number is supposed to reflect the earliest version of Nmap that is compatible with the updates in that channel. This is something we will need to keep abreast of when nmap-update channels are being maintained. However, we do not currently push any updates to any channels, so this does not affect any users.
