### ISSUE TITLE
Exclusion File Switch Should Behave Similarly to Input List Switch

### ISSUE THREAD

**Issue by caesarcipher-r7** [nmap/nmap#1039]
The input list (-iL) switch is aware of files on path and allows tab completion of filenames, but the --exclusionfile switch is dumb and can't do the same thing.

Please enhance --exclusionfile to behave more similarly to the input list feature.

**Comment by dmiller-nmap** [comment]
Tab completion is not implemented by Nmap. It is usually implemented by a script or plugin provided by your system distribution or package maintainer. Please file the bug report there.
