### ISSUE TITLE
dnet: Failed to open device wlan0

### ISSUE THREAD

**Issue by Deathlive** [nmap/nmap#1047]
I install nmap in Debian `apt install nmap`  at start `dnet: Failed to open device wlan0`
can what some packages are not considered ?
How to fix this ?

**Comment by dmiller-nmap** [comment]
I've never seen this happen on Linux. Please provide this diagnostic information:

1. output of `nmap --version`
2. output of `nmap -d --iflist`
3. Any information about your system that may be relevant: what kind of interface is "wlan0"? Are you using a VPN? etc.

**Comment by Deathlive** [comment]
@dmiller-nmap I not quite have Debian, I use Termux(Android terminal emulator), with proot Debian installed.
https://imgur.com/a/Gyd7R
