### ISSUE TITLE
Scanning only 128 hosts on /24

### ISSUE THREAD

**Issue by Yannis100** [nmap/nmap#1052]
I'm running the following scan comand
nmap -sC -sS -sU -sV -T4 -O -v -v -F -Pn --version-light 192.168.1.0/24
to force full scan even on "down" hosts (-Pn)

But today I see the following result 

Starting Nmap 7.60 ( https://nmap.org ) at 2017-10-30 11:43 W. Europe Standard Time
NSE: Loaded 146 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 2) scan.
Initiating NSE at 11:44
Completed NSE at 11:44, 0.00s elapsed
NSE: Starting runlevel 2 (of 2) scan.
Initiating NSE at 11:44
Completed NSE at 11:44, 0.00s elapsed
Initiating Parallel DNS resolution of 256 hosts. at 11:44
Completed Parallel DNS resolution of 256 hosts. at 11:44, 0.07s elapsed
Initiating SYN Stealth Scan at 11:44
**Scanning 128 hosts [100 ports/host]**

It is only scanning the first 128 hosts instead of the full 255 range.
Is it something related with the command I used or a bug ?

**Comment by dmiller-nmap** [comment]
This is the intended  scan group size for UDP scanning. The function that determines this is [`determineScanGroupSize`](https://github.com/nmap/nmap/blob/master/scan_engine.cc#L1284-L1323), which takes things like number of ports, number of hosts scanned so far, and timing level. But for UDP scans, it is capped at 128 hosts at a time.

Scan group size is a potential area to study for improving scan times. I made a note on our GSoC Community Ideas list to investigate this: https://secwiki.org/w/GSoC_community_ideas/Performance/Optimization_specialist
