### ISSUE TITLE
nmap ignore "--with-openssl=" during building

### ISSUE THREAD

**Issue by iz8mbw** [nmap/nmap#1053]
Hi.
On my Linux system I have OpenSSL version 1.1.0f (already built) in `/opt/ssl` and I have OpenSSL version 1.1.1 devel (already built) in `/opt/ssldevel`.
OpenSSL version 1.1.0f is my system OpenSSL default library (`/opt/ssl/lib`) is in my `/etc/ld.so.conf` file.

I want to build nmap and link to OpenSSL version 1.1.1 devel in `/opt/ssldevel`.
This is my `configure`: `./configure  --with-openssl="/opt/ssldevel" --with-libpcap=included --with-libpcre=included --with-libdnet=included --with-liblua=included --with-liblinear=included`

After `make` and `make install` if I execute `ldd /usr/local/bin/nmap` I see that nmap use my system OpenSSL library (OpenSSL version 1.1.0f) and not the specified one (during `configure`) version 1.1.1 devel available in `/opt/ssldevel`.

See `ldd`:

```# ldd /usr/local/bin/nmap
        linux-vdso.so.1 =>  (0x7ed30000)
        /usr/lib/arm-linux-gnueabihf/libcofi_rpi.so (0x76f20000)
        libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x76ee2000)
        libssl.so.1.1 => /opt/ssl/lib/libssl.so.1.1 (0x76e87000)
        libcrypto.so.1.1 => /opt/ssl/lib/libcrypto.so.1.1 (0x76ca4000)
        libz.so.1 => /usr/local/lib/libz.so.1 (0x76c84000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76c79000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76ba7000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76b36000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76b0e000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x769da000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x769bb000)
        /lib/ld-linux-armhf.so.3 (0x76f2a000)
```
`ls -la` of  `/opt/ssldevel`:

```root@system:/opt/ssldevel# ls -la
total 72
drwxr-xr-x 10 root root  4096 Oct 30 11:40 .
drwxr-xr-x 26 root root  4096 Oct  1 05:00 ..
drwxr-xr-x  2 root root  4096 Jul 12 11:54 bin
drwxr-xr-x  2 root root  4096 Jul 12 11:54 certs
-rw-r--r--  1 root root   414 Jul 12 11:54 ct_log_list.cnf
-rw-r--r--  1 root root   414 Jul 12 11:54 ct_log_list.cnf.dist
drwxr-xr-x  3 root root  4096 Jul 12 11:54 include
drwxr-xr-x  4 root root  4096 Jul 12 11:54 lib
drwxr-xr-x  2 root root  4096 Jul 12 11:54 misc
-rw-r--r--  1 root root 10771 Jul 12 11:54 openssl.cnf
-rw-r--r--  1 root root 10771 Jul 12 11:54 openssl.cnf.dist
drwxr-xr-x  2 root root  4096 Jul 12 11:54 private
drwxr-xr-x  4 root root  4096 Jul 12 11:58 share
```

Where I wrong? How Can I specify to `configure` to use `/opt/ssldevel`?

**Comment by dmiller-nmap** [comment]
The configure script looks for an OpenSSL **installation** in the directory provided, not a source tree. That is, it will look for `/opt/ssldevel/include/` and `/opt/ssldevel/lib/` and try to include the openssl headers from there and link to the library there as well. You will have to have configured OpenSSL source with the `/opt/ssldevel` prefix and run `make install_sw` to install it there before configuring Nmap.

If you *do* have an OpenSSL installation at `/opt/ssldevel`, then please provide the `config.log` file from your Nmap source tree so we can see what it is doing. We rely on and test this specific feature regularly, so I am fairly confident that it is still working.

**Comment by iz8mbw** [comment]
Hi. OpenSSL was previously built with that "config" options: `config enable-tls1_3 --prefix=/opt/ssldevel --openssldir=/opt/ssldevel -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'`
These are the `ls -la` of the OpenSSL directories:
```
root@server:/opt/ssldevel/lib# ls -la
total 6600
drwxr-xr-x 4 root root    4096 Nov  3 10:12 .
drwxr-xr-x 9 root root    4096 Nov  3 10:13 ..
drwxr-xr-x 2 root root    4096 Nov  3 10:12 engines-1.1
-rw-r--r-- 1 root root 3363402 Nov  3 10:12 libcrypto.a
lrwxrwxrwx 1 root root      16 Nov  3 10:12 libcrypto.so -> libcrypto.so.1.1
-rwxr-xr-x 1 root root 2305732 Nov  3 10:12 libcrypto.so.1.1
-rw-r--r-- 1 root root  592572 Nov  3 10:12 libssl.a
lrwxrwxrwx 1 root root      13 Nov  3 10:12 libssl.so -> libssl.so.1.1
-rwxr-xr-x 1 root root  472878 Nov  3 10:12 libssl.so.1.1
drwxr-xr-x 2 root root    4096 Nov  3 10:12 pkgconfig

root@server:/opt/ssldevel/include# ls -la
total 12
drwxr-xr-x 3 root root 4096 Nov  3 10:12 .
drwxr-xr-x 9 root root 4096 Nov  3 10:13 ..
drwxr-xr-x 2 root root 4096 Nov  3 10:12 openssl
```

And, for your info, I use that same OpenSSL library for `nginx` and `curl` without problems.

In attach, as requested, the `config.log` of nmap taken after the command `
[config.log.txt](https://github.com/nmap/nmap/files/1453632/config.log.txt)
./configure --with-openssl="/opt/ssldevel" --with-libpcap=included --with-libpcre=included --with-libdnet=included --with-liblua=included --with-liblinear=included`.

**Comment by dmiller-nmap** [comment]
I think this is a problem with libssh2, which did not have complete compatibility with OpenSSL 1.1. I am guessing that the OpenSSL in `/opt/ssldevel` was built without the backwards-compatible deprecations for some things, so the linker can't find the functions (`OpenSSL_add_all_ciphers`) that it is looking for, and so it falls back to the other version in your system's linker path. I backported the fix from libssh2/libssh2#176 and it seems to work here. Please try again with r37078 when it syncs to Github.

**Comment by dmiller-nmap** [comment]
The commit in question is 03f6c2f0160d

**Comment by iz8mbw** [comment]
I have built downloading the latest source from https://github.com/nmap/nmap/archive/master.zip but it still link to `/opt/ssl` and not to `/opt/ssldevel`.

Just for your info I workarounded the problem with that:
```
export CPPFLAGS="-I/opt/ssldevel/include"
export LDFLAGS="-L/opt/ssldevel/lib -Xlinker -rpath=/opt/ssldevel/lib"

./configure --with-ld-opt="-L/opt/ssldevel/lib -ldl -Wl,-rpath,/opt/ssldevel/lib" --with-libpcap=included --with-libpcre=included --with-libdnet=included --with-liblua=included --with-liblinear=included
```

But anyway if I build with `--with-openssl="/opt/ssldevel"` it still does not work.

**Comment by dmiller-nmap** [comment]
We have been successfully using the `--with-openssl=` configure option to test various OpenSSL versions for the latest release (Nmap 7.93) and it works fine. If you have issues with this in the future, please open a new issue.
