### ISSUE TITLE
npcap 0.95 - duplicate sent-out packets seen on local Interface

### ISSUE THREAD

**Issue by mapl** [nmap/nmap#1055]
Hello,

when I start Wireshark I am encountering duplicate TCP/UDP packets sent from my machine . After toggling the NPcap driver in the TCP/IP Settings of my Ethernet Interface and restarting Wireshark, the behavior is not seen anymore until I restart the System.

Is this behavior already known or limited to my machine?

OS: Windows 10 Build 1706
Wireshark 2.4.2

**Comment by dmiller-nmap** [comment]
Are these packets sent with or injected by Npcap (like those sent by Nmap) or are they regular TCP/IP traffic from regular Windows applications? Do you know if they are actually duplicated on the network, or if they are only showing double in Wireshark?

**Comment by mapl** [comment]
I just did a traffic capture on my wan interface while sending data to a specific IP and didn't see any duplicate packets.
It seems that only TCP Packets are actually affected with a very short delay of 0.00000X secs

- OS: Windows 10 Build 1703
- Wireshark 2.4.2 or Tshark
- NPcap 0.96 (just updated from NPcap 0.95)

**Comment by mapl** [comment]
after restarting the npcap windows kernel driver, no more fake duplicate packets are seen in wireshark/tshark

After a windows reboot, fake duplicate packets reoccur

**Comment by dmiller-nmap** [comment]
@mapl Is this still happening with Npcap 0.99-r6? If so, can you determine if they are showing up twice in Wireshark only, or are they actually being transmitted twice (i.e. they show up twice in a packet capture at the router or destination)? Thanks

**Comment by mapl** [comment]
We can close this issue. I have not encountered the behavior for a long time. thank you for the reminder

**Comment by yuanjianpeng** [comment]
I have the same problem On windows 10.  When I uninstall my antivirus program. the problem solved.
A another Windows 10 has the same problem. but i don't know which program cause it.
