### ISSUE TITLE
Having an hotkey to skip lagging targets

### ISSUE THREAD

**Issue by maaaaz** [nmap/nmap#1057]
Hello there,

While scanning large IP spaces you can often stumble upon a target that, for known or unknown reasons/protections, slows down nmap drastically (like 1 hour for 1 target): it happens a lot while scanning OVH-hosted targets.

In that case while we frantically press "space" or "enter" hotkey wondering if the scan will ever finish, 
it would be a good idea to have **a specific hotkey for skipping such target**.

Cheers.

**Comment by dmiller-nmap** [comment]
Interactions with a running scan are complicated and probably not a good way to proceed. The existing hotkeys only turn on or off different output options; altering a running scan is more complex. However, there are ways to accomplish this easily:

* Use the `--script-timeout` option to set a limit on how long any NSE script can spend on a single host. If the script exceeds this time, the script stops and does not record results. All other results are preserved for the host.
* Use the `--host-timeout` option to set a limit on how long Nmap can spend on a single host, combined between all scan phases. If the timer runs out during any scan phase, the host is dropped from scanning, and no results will be reported.

The `-T5` option includes (among other settings) the equivalent of `--script-timeout 10m --host-timeout 15m`.

Of course, if you have specific examples of target behaviors that slow Nmap down too much, we can try to come up with countermeasures to ensure a quick scan.

**Comment by maaaaz** [comment]
Thanks @dmiller-nmap, I wasn't aware of the `--host-timeout` option, it should be a good workaround.

For slow targets, I could give you any OVH IP, I don't know how exactly their **VAC** protection works but it really slows nmap...

**Comment by cldrn** [comment]
I will close this for now as we have already options to limit the scan time.
