### ISSUE TITLE
Check if array is NULL is reduntant

### ISSUE THREAD

**Issue by landgraf** [nmap/nmap#1061]
Minor issue but makes static analyzer angry... 
pkt is array so pkt == NULL doesn't make sense and always false.
  u8 pkt[MAX_IP_PACKET_LEN];       /**< Holds packets returned by fillpacket */
 https://github.com/nmap/nmap/blob/d52df89026ca13a94717b056e39432eba9b2ead8/nping/ProbeMode.cc#L431
Same in https://github.com/nmap/nmap/blob/d52df89026ca13a94717b056e39432eba9b2ead8/nping/ProbeMode.cc#L482

**Comment by nnposter** [comment]
In agreement. The code looks like a copy/paste job from another area where the variable is indeed a pointer.
