### ISSUE TITLE
is ARP ping of nmap AVL now? win10 and centos, v7.40 v7.60

### ISSUE THREAD

**Issue by Justsoos** [nmap/nmap#1065]
I find there is no -PR option in command help page, but still in nmap Guild:
https://nmap.org/book/man-host-discovery.html

and I tested the NIC which blocked icmp ping with nmap -PR, or combination with -sn, all failed to discover it.

is ARP ping of nmap AVL? or, what is the right way to run ARP ping with nmap?

**Comment by dmiller-nmap** [comment]
ARP host discovery is the default when Nmap has sufficient privileges (sudo/root) for addresses on the same link. For this reason, `-PR` doesn't actually accomplish much of anything useful. What it currently does is force any addresses which are *not* directly connected to be reported as `down`. I think we will change this to produce an error if you do not have necessary privileges and a more useful message if the address is not on the same link segment.

If you want to test discovery on the local LAN *without* using ARP, you have to use `--disable-arp-ping`.

**Comment by Justsoos** [comment]
@dmiller-nmap  thx for your reply. But my doubt is like if I do want to No ping or No port scan to discover all computers on my LAN, just the way of ARP discover left, how can I do?
with `nmap -Pn -sn 192.168.0.1/24`
is wrong obviously. surely I have sudo / root privileges first.
as I consider, nmap is the one and only one tools, so be it.

**Comment by Justsoos** [comment]
@dmiller-nmap thx for your reply, but first I have to say, the nmap man page made me confused badly:
https://nmap.org/book/man-host-discovery.html
it says (in -sn section):
> The default host discovery done with -sn consists of an ICMP echo request, TCP SYN to port 443, TCP > ACK to port 80, and an ICMP timestamp request by default.
but I tried `nmap -sn -n LOCALNETWORK` and capture it with wiresharks, there are only ARP packages! No TCP ACK or ICMP, not like the description on man page, so, the simple ARP-only scan achieved by just nmap -sn option, is that right ? the man page mistook of out of date?
