### ISSUE TITLE
NMAP crash with ssh-auth-methods.nse (patch included)

### ISSUE THREAD

**Issue by sethrandall** [nmap/nmap#1077]
When testing ssh-auth-methods.nse against non-standard ports, I forgot to specify ports and NMAP crashed. I have narrowed it down to running the script against port 139. I ran a debug and found the crash appears to be caused by a double free of session data. This appears to be due to a session pointer not being NULLed after the session is freed. Attached is a patch that appears to fix the issue.
[nse_libssh2-session-null.txt](https://github.com/nmap/nmap/files/1528645/nse_libssh2-session-null.txt)

**Comment by landgraf** [comment]
This was fixed in 350bbe0597d37ad67abe5fef8fba984707b4e9ad

**Comment by landgraf** [comment]
@dmiller-nmap can you close the issue since you've commited the fix? :)

**Comment by dmiller-nmap** [comment]
Thanks!
