### ISSUE TITLE
Nping loss rate can go negative and cause weird values

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#108]
Nping can sometimes receive more packets back than it sends, leading to a negative "loss rate" and a bogus loss percentage value.  We should handle it more gracefully when we legitimately receive more responses than we sent, and we should probably also be more strict about what packets are considering a true "response".  We should try to exclude packets which are unrelated to our probe packets, to the extent we can.  For more, see:

http://seclists.org/nmap-dev/2015/q2/64

![nping](https://cloud.githubusercontent.com/assets/2155933/7439879/29737f8e-f047-11e4-9e6c-aeea579e3eb8.jpg)

**Comment by dmiller-nmap** [comment]
Good discussion over at #691, so closing this as a duplicate.
