### ISSUE TITLE
No output from ssl-poodle

### ISSUE THREAD

**Issue by bfearer** [nmap/nmap#1086]
I have tried as many different options with ssl-poodle as I can think of but I get no output.
I tried all version of nmap from 6.49 to current, both linux and windows. Google returns the same links no matter how I search for information.

I have attached two snips, one with regular options and one with the debug switch.
![nmap output with debug](https://user-images.githubusercontent.com/34627706/34081708-8b9e3546-e31f-11e7-9558-43ccc19c845c.PNG)
![nmap output](https://user-images.githubusercontent.com/34627706/34081709-8baa4854-e31f-11e7-91fe-c0663e3ca795.PNG)

**Comment by bfearer** [comment]
Apparently I was looking at things wrong. Now I know if there are no vulnerable ports, it returns no information.

**Comment by dmiller-nmap** [comment]
@bfearer If you want to see "not vulnerable" information, use the [`vulns.showall` script argument](https://nmap.org/nsedoc/lib/vulns.html#script-args).
