### ISSUE TITLE
Blue screen with Npcap 0.97

### ISSUE THREAD

**Issue by UltramarineBlue0** [nmap/nmap#1087]
My PC crashed when I started a software that used Npcap. I'm using Windows 10 Version 1709 and Npcap 0.97. Npcap is installed in the WinPcap compatible mode. The event viewer tells me that the bluescreen stop code were `0x000000d1 (0x000000000000005f, 0x0000000000000002, 0x0000000000000001, 0xfffff809849011a7)`.

[Here's a dropbox link to the memory dump](https://www.dropbox.com/s/bj3prwppwwd2wij/MEMORY.7z?dl=0). Unfortunately, the dump is too big to upload directly to GitHub.

Not sure if it's important: the software that I tried to use is a [utility](http://uk.tp-link.com/download/TL-PA9020P-KIT_V1.html#Utility) for a powerlan adapter. Apparently, it uses WinPcap to communicate with the adapters and I've installed Npcap as a replacement for WinPcap.

**Comment by dmiller-nmap** [comment]
Thanks for the report! We'll look into it.

**Comment by dmiller-nmap** [comment]
@UltramarineBlue0 can you please provide the output of [DiagReport](https://nmap.org/npcap/guide/npcap-issues.html) so that we can better debug this memory dump? Thanks.

**Comment by UltramarineBlue0** [comment]
@dmiller-nmap I tried to execute DiagReport.bat by double-clicking it in the file explorer and starting it in an admin Powershell. Both times, it exited without showing any output and didn't create a DiagReport.txt. Do you know how I could get that to work?

**Comment by dmiller-nmap** [comment]
@UltramarineBlue0 Does this issue still affect you with Npcap 0.99-r6?

**Comment by UltramarineBlue0** [comment]
@dmiller-nmap With Npcap 0.99-r7 and a newer version of the utility, I no longer get bluescreens. However I've not tested Npcap 0.99-r7 with the older version of the utility, so I don't know what exactly fixed the bluescreen
