### ISSUE TITLE
Why proxychains works but --proxies didnt?

### ISSUE THREAD

**Issue by intrd** [nmap/nmap#1098]
I have a reverse ssh socks4 pointing to my port 443, scanning is working w/ proxychains works:

```
proxychains nmap -sT -Pn -n 10.1.1.X -p80 --open

Results:
PORT   STATE SERVICE
80/tcp open  http
```

But when I try to do this directly from nmap using --proxies..

```
nmap -sT -Pn -n --proxies socks4://127.0.0.1:443 10.1.1.X -p80 --open

No results, nmap can't detect the open port.
```

**Comment by dmiller-nmap** [comment]
From [the relevant section of the man page](https://nmap.org/book/man-bypass-firewalls-ids.html):

>Warning: this feature is still under development and has limitations. It is implemented within the nsock library and thus has no effect on the ping, port scanning and OS discovery phases of a scan. Only NSE and version scan benefit from this option so far—other features may disclose your true address. SSL connections are not yet supported, nor is proxy-side DNS resolution (hostnames are always resolved by Nmap).

In short, the `--proxies` option does not currently work for TCP port scanning. There is an experimental branch by @d33tah that may allow it to work: http://seclists.org/nmap-dev/2015/q3/13

**Comment by ocervell** [comment]
Any updates here since 4 years ?
