### ISSUE TITLE
Make http-fetch prepend host:port directory to destination

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#1099]
[`http-fetch`](https://nmap.org/nsedoc/scripts/http-fetch.html) downloads files like `wget`, but although it takes a destination directory script-arg, it doesn't keep separate subdirectories for separate targets. We should automatically create a `host:port` directory below the destination and keep the files in there.

**Comment by aniketp41** [comment]
@dmiller-nmap I'll work on it.

**Comment by aniketp41** [comment]
@dmiller-nmap Fixed in #1100 . Please have a look.

**Comment by NK-Nikunj** [comment]
Hello @dmiller-nmap 

I have been using nmap for quite some time(off-course for white hat purpose). I am new to open source community and would like to contribute.
