### ISSUE TITLE
Script http-fetch broken on Windows

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1102]
Commit r37113, related to #1099 and #1100, broke script `http-fetch` because it is trying to use colon in a directory name, which is an illegal character on Windows. Here is the culprit:
```diff
--- scripts/http-fetch.nse	(revision 37112)
+++ scripts/http-fetch.nse	(revision 37113)
@@ -211,10 +211,12 @@
     return output, output.ERROR
   end
 
+  local sub_directory = tostring(host.ip) .. ":" ..  tostring(port.number) .. SEPARATOR
+
   if destination:sub(-1) == '\\' or destination:sub(-1) == '/' then
```
One possible fix is to use the port number as a separate level in the `destination` hierarchy.

**Comment by aniketp41** [comment]
Fixed it. Thanks for pointing out the issue @nnposter
