### ISSUE TITLE
Out-of-date documentation in script http-fetch

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1104]
The embedded documentation in script `http-fetch` is out of date, not reflecting the recently implemented origin directory structure. See #1099, #1100, #1102.

There is a separate issue that the XML section is missing `@xmloutput` tag and `result` element.

**Comment by aniketp41** [comment]
@nnposter please have a look at the PR #1105 . Thanks!

**Comment by nnposter** [comment]
I have committed the PR. Thank you for the fast turnaround.
