### ISSUE TITLE
ssl-poodle.nse:181: variable 'DEFAULT_ELLIPTIC_CURVES' is not declared

### ISSUE THREAD

**Issue by mgoins01** [nmap/nmap#1106]
Am attempting to run ssl-poodle.nse from a kali box with nmap 7.60 loaded on it to check an IP address, and am receiving the following error.  Have pulled copies of the ssl-poodle.nse script from both the nmap site & github, and both show the same symptoms.  If interested I can provide complete debug output.  
Command as executed:
nmap -sV -d --version-light --script ssl-poodle -p 443 [redacted]

Starting Nmap 7.60 ( https://nmap.org ) at 2018-01-14 14:07 UTC
... <skipping to ssl-poodle debug output>
NSE: Starting ssl-poodle against [redacted]:443.
NSE: ssl-poodle against [redacted]:443 threw an error!
/usr/bin/../share/nmap/scripts/ssl-poodle.nse:181: variable 'DEFAULT_ELLIPTIC_CURVES' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
        /usr/bin/../share/nmap/scripts/ssl-poodle.nse:181: in upvalue 'base_extensions'
        /usr/bin/../share/nmap/scripts/ssl-poodle.nse:207: in upvalue 'find_ciphers_group'
        /usr/bin/../share/nmap/scripts/ssl-poodle.nse:289: in upvalue 'find_ciphers'
        /usr/bin/../share/nmap/scripts/ssl-poodle.nse:364: in function </usr/bin/../share/nmap/scripts/ssl-poodle.nse:336>
        (...tail calls...)

Completed NSE at 14:07, 0.00s elapsed

**Comment by aniketp41** [comment]
@mgoins01 As it is stated in the debug message, the variable `DEFAULT_ELLIPTIC_CURVES` is not declared in the file `usr/share/nmap/nselib/tls.lua`. So the issue is that you're running mismatched versions of nmap script and the nse library. 
Try replacing `usr/share/nmap/nselib/tls.lua` with [this file](../nselib/tls.lua) and see if it works.

**Comment by dmiller-nmap** [comment]
@aniketp41 is correct. Use the copy of `ssl-poodle` that came with Nmap 7.60 and you won't have any problems. It has not been substantially improved since the 7.60 release.
