### ISSUE TITLE
UDP communication issue

### ISSUE THREAD

**Issue by Eugeny1** [nmap/nmap#111]
I try performing easy task - on windows PC send UDP packet from one CMD window to another.
One:
ncat -l -4u -p67 -verbose
Another
ncat -4u [IP-address-of-this-PC] 67
If I type anything on "another" machine finished by enter, first exits with message:
NCAT DEBUG: Error in CreateProcess: 2

**Comment by dmiller-nmap** [comment]
There is no `-verbose` option. This gets parsed as `-v -e rbose`, and the error is because "rbose" is not a valid command. However, we should clean up this error message on Windows, since the error message on Linux is much clearer in this case:

```
exec: No such file or directory
```

**Comment by RajithaRama** [comment]
I will look into this.

**Comment by RajithaRama** [comment]
I'm using ncat version 7.12 and still can recreate the problem.

**Comment by e12283** [comment]
https://github.com/nmap/nmap/pull/527 clean fix here.
