### ISSUE TITLE
Add support for netmask notation

### ISSUE THREAD

**Issue by AresS31** [nmap/nmap#1110]
So far only the `CIDR` notation is supported by `nmap`; would it be possible to also implement support for classical `netmask` notation as well such as /255.255.255.0?

**Comment by dmiller-nmap** [comment]
This is not a priority for the project; netmask notation can be trivially converted to CIDR notation, and we also offer octet range notation, e.g. `192.0.2.1-254`. If you want to submit a patch to support this, we will consider it, though.
