### ISSUE TITLE
Nmap 7.30 installs but does not function

### ISSUE THREAD

**Issue by kabeerk** [nmap/nmap#1113]
Hello,

I tried installing nmap version 7.30 and the installer confirms that the installation is finished. However no shortcuts or anything appears and when I run ncat in Bash I get a:

bash: ncat: command not found

I tried version 7.60 as well and had the same issue. 

Attaching the install.log and NPFInstall.log for the 7.30 install.

I'm on a Windows 7 machine.

[install.log](https://github.com/nmap/nmap/files/1655868/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/1655869/NPFInstall.log)

**Comment by dmiller-nmap** [comment]
Did you try restarting your command shell? On Windows, running ncat or nmap from a shell requires the Nmap installation directory to be added to the `PATH` environment variable (there is an option in the installer to do this). Already-running processes like your shell have their own copy of the `PATH`. New processes started as children of `explorer.exe` (like opening a new shell by double-clicking the EXE) will get the new `PATH`.

**Comment by kabeerk** [comment]
Where in the installation is the option for the installer? I can't seem to find it

**Comment by dmiller-nmap** [comment]
The installer automatically adds Nmap installation directory to PATH unless instructed otherwise. If you have problems with running Nmap 7.93 or newer, please open a new issue.
