### ISSUE TITLE
Deprecated netstat modules in default.lua and network.lua

### ISSUE THREAD

**Issue by kstreitova** [nmap/nmap#1117]
As netstat networking command (part of the net-tools package) is considered deprecated, I would suggest replacing netstat modules in "nselib/data/psexec/default.lua" and "nselib/data/psexec/network.lua" with a convenient alternative (probably "ss -an").

**Comment by dmiller-nmap** [comment]
These modules are for executing commands on Windows systems. `netstat` is not deprecated on Windows, as it is a different program than the NET-3 tool distribution for Linux. Windows systems do not have a `ss` command.
