### ISSUE TITLE
An operation was attempted on something that is not a socket.

### ISSUE THREAD

**Issue by steinm07** [nmap/nmap#1118]
I installed nmap and when i tried to connect with ncat to anything it results in either doing nothing or:
libnsock select_loop(): nsock_loop error 10038: Došlo k pokusu o operaci s něčím, co není soket. (Translated form Czech: An operation was attempted on something that is not a socket.)

Wierd, because nmap works fine.

**Comment by nnposter** [comment]
If this issue is experienced with stock 7.60 on Windows then it is likely #978, which is already fixed in the code base. Please report back if the issue persists with the current trunk code.

**Comment by myxal** [comment]
Any idea when we can expect a new build, since the affected 7.60 is still provided on nmap.org as the latest?

**Comment by dmiller-nmap** [comment]
We are working on the next release, but don't have a solid release date
yet. Ncat 7.50 is unaffected and suitable for most things; the only big
feature change was the addition of DTLS and ALPN support.

**Comment by benlavender** [comment]
Looking forward to the next release for Windows as mine on 7.60 does exactly as https://github.com/nmap/nmap/issues/978

**Comment by nnposter** [comment]
Nmap 7.70, which includes the fix, has been released in March 2018
