### ISSUE TITLE
NPcap fails for PacketRequest(OID_GEN_MEDIA_CONNECT_STATUS)

### ISSUE THREAD

**Issue by pstavirs** [nmap/nmap#1127]
For the following application code -
```
    memset(linkStateOid_, 0, sizeof(PACKET_OID_DATA) + sizeof(uint));
    linkStateOid_->Oid = OID_GEN_MEDIA_CONNECT_STATUS;
    linkStateOid_->Length = sizeof(uint);
    if (PacketRequest(adapter_, 0, linkStateOid_))
        . . . 
```
the `PacketRequest` call works with WinPcap, but returns false with NPcap

Full application code - https://github.com/pstavirs/ostinato/blob/master/server/winpcapport.cpp#L66

MSFT OID Ref: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-media-connect-status

The above MSFT ref says -
> NDIS handles this OID for NDIS 6.0 and later miniport drivers.

So, my guess is it is expected to automatically work with NPcap - but it doesn't

**Comment by dmiller-nmap** [comment]
Npcap is not a miniport driver, but a Lightweight Filter Driver. Jeffrey Tippet of Microsoft [noted on ntdev](https://www.osronline.com/ShowThread.cfm?link=235910):

>LWFs are not allowed to query certain deprecated OIDs, including OID_GEN_LINK_SPEED, OID_GEN_MEDIA_CONNECT_STATUS, and OID_GEN_MAXIMUM_FRAME_SIZE. These queries will always fail. Instead, query OID_GEN_LINK_STATE.

**Comment by dmiller-nmap** [comment]
Sorry, that was a little abrupt. Thanks for reporting this! I learned something valuable. Is there somewhere in Npcap's documentation that you would expect to find this information? Maybe we can make it easier to avoid in the future.

**Comment by pstavirs** [comment]
@dmiller-nmap I would suggest adding a _Compatitibility with WinPcap_ section to https://nmap.org/npcap/guide/npcap-devguide.html with these details. This section can be expanded in the future if any other similar incompatibility is found.

Additionally, I would suggest to consider internally mapping the deprecated OIDs to the new OID to address this so that applications can still use NPCAP as a drop-in replacement for WinPCAP without having to change any code - if you don't want to do this after due consideration, that's fine too.

**Comment by pstavirs** [comment]
To close the loop on this, `OID_GEN_MEDIA_CONNECT_STATUS` and `OID_GEN_MEDIA_CONNECT_STATUS_EX` do not work with npcap (v0.9987) and Win10, but `OID_GEN_LINK_STATE` works. 

However, none of the above including `OID_GEN_LINK_STATE` works with the following adaptors -
* Npcap Loopback Adapter
* Adapter for loopback traffic capture

Any ideas why?
