### ISSUE TITLE
Npcap 0.98 - install hangs on creation Npcap Loopback Adaptor

### ISSUE THREAD

**Issue by Zebrafish007** [nmap/nmap#1134]
Hi,

The installation of Npcap 0.98 fails when install option `Support loopback traffic` is checked. The installer halts at the point where it reports "extract: WlanHelper.exe". If this option remains unchecked it installs normal (checked options are:  first) Automatically start...', last) Install Npcap in...').

Win10 x64.

Attached a bunch of log files (normal and halted version). 

Normal:
[install.log](https://github.com/nmap/nmap/files/1713619/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/1713620/NPFInstall.log)
[DiagReport-20180210-183617.txt](https://github.com/nmap/nmap/files/1713621/DiagReport-20180210-183617.txt)

Halted:
[Halt - install.log](https://github.com/nmap/nmap/files/1713625/Halt.-.install.log)
[Halt - NPFInstall.log](https://github.com/nmap/nmap/files/1713626/Halt.-.NPFInstall.log)
[Halt - DiagReport-20180210-183241.txt](https://github.com/nmap/nmap/files/1713627/Halt.-.DiagReport-20180210-183241.txt)

**Comment by dmiller-nmap** [comment]
It looks like the "normal" install also had WinPcap API-compatible mode checked, and the "halted" version was a reinstall. I can't figure out from the logs what was the problem; it seems to stop during installation of the WFP callout driver, but the NPFInstall.log doesn't show that command being run at all.

I do see that the command to install the loopback adapter stopped logging in the middle of execution. This looks like a crash of some sort. Can you run `NPFInstall.exe -il` and report if it succeeds or not?

**Comment by Zebrafish007** [comment]
Hmmm... this is the response: "Npcap Loopback adapter has failed to be installed.".

**Comment by dmiller-nmap** [comment]
@Zebrafish007 Are you still having this problem with Npcap 0.99-r6?

**Comment by Zebrafish007** [comment]
@dmiller-nmap Cheers for the fix. It now works, also NMAP 7.70 installs just fine.

**Comment by dmiller-nmap** [comment]
Glad it's working for you!
