### ISSUE TITLE
What's different about ICMP in NMAP? 

### ISSUE THREAD

**Issue by pmgcrypto** [nmap/nmap#1138]
I found a host that will not respond ping in ubuntu. However, it will respond to ping in NMAP. What is different about the ICMP sweep in NMAP that would cause this?

**Comment by dmiller-nmap** [comment]
Nmap does host discovery in several different ways, and it is not limited
to ICMP echo request. You can read more about this in the Nmap man page:
https://nmap.org/book/man-host-discovery.html
