### ISSUE TITLE
Spoofing TCP ISN sequence predictability index

### ISSUE THREAD

**Issue by cstayyab** [nmap/nmap#1143]
Hi!
I am working on OS and TCP/IP Fingerprint Spoofing. I have achieved almost everything except that I want to generate ISNs such that they give a specific value of TCP ISN sequence predictability index (SP). 
I have read https://nmap.org/book/osdetect-methods.html#osdetect-sp but it was not much helpful.

Kindly help.
Thanks

**Comment by fyodor** [comment]
Thanks for the note, but this isn't really an Nmap software bug or problem, and the issues tracker isn't really meant for general discussion.
