### ISSUE TITLE
smb-enum-users not returning user info

### ISSUE THREAD

**Issue by Katorias** [nmap/nmap#1153]
I'm attempting to run the smb-enum-users script targeted at a windows 7 pc using the following command:

nmap -p445 --script=smb-enum-users <host>

but I'm not getting back any information relating to the users of that system, I've tried targeting other machines with little success also. 

I've also tried running the command using the debug and verbose parameters but nothing out of the ordinary shows up, i.e. no warnings/errors. 

Any ideas?

**Comment by cldrn** [comment]
Hey,

Can you try with -d2 and share the output? This could happen because a few different reasons including IPC isn't accesible anonymously.
