### ISSUE TITLE
nmap-7.70/libdnet-stripped/src/arp-ioctl.c:221: off by one error ?

### ISSUE THREAD

**Issue by dcb314** [nmap/nmap#1156]
nmap-7.70/libdnet-stripped/src/arp-ioctl.c:221]: (error) Width 100 given in format string (no. 4) is larger than destination buffer 'macbuf[100]', use %99s to prevent overflowing it.

Source code is

       i = sscanf(buf, "%s 0x%x 0x%x %100s %100s %100s\n",
            ipbuf, &type, &flags, macbuf, maskbuf, devbuf);

**Comment by dmiller-nmap** [comment]
Thanks for spotting this! I did an audit for other uses of `scanf`-type functions, and all other uses correctly allow 1 extra byte for null.
