### ISSUE TITLE
dnet: Failed to open device eth0 - error with nmap 7.70 on Windows 10

### ISSUE THREAD

**Issue by marce1000** [nmap/nmap#1167]
dnet: **Failed to open device eth0** - error with nmap 7.70 on Windows 10 ; I started a CMD (run as **administrator**) ,  but the problem persists. Already rebooted once, but the problem remains.
M.

**Comment by fishouttah20** [comment]
Any fix? getting this on Win7 too

**Comment by do-you-even-curl** [comment]
Having the same error on win10.

Had nmap 7.40 installed previously which gave the same exact error. So I upgraded to 7.70 hoping it would be fixed.

**Comment by gvanem** [comment]
What does `nmap --iflist` print? And do you have a working Windump/tcpdump or WireShark? If not, it's not Nmap's fault.

**Comment by guyharris** [comment]
It's the fault of whatever code is under the delusion that "eth0" is an appropriate device to open on Windows.

(It's also not an appropriate device to open on: macOS, FreeBSD, NetBSD, OpenBSD, DragonFly BSD, Solaris, HP-UX, AIX, etc..

It's not even guaranteed to be an appropriate device to open on ***Linux***!)

**Comment by do-you-even-curl** [comment]
First of all: It's working now for me.

I got the error when doing an Intense scan on 192.168.2.*; Then I did a Ping scan which did work. Then I closed nmap. When I read your comment I ran `nmap --iflist` (see output below). It listed eth0. Then I started nmap again, ran an Intense scan and now it worked. Not sure what exactly fixed it.

Output of `nmap --iflist` (censored some stuff):
```
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-14 21:05 Mitteleuropõische Sommerzeit
************************INTERFACES************************
DEV  (SHORT) IP/MASK                               TYPE        UP   MTU  MAC
eth0 (eth0)  fe80::a1e9:5523:a1f3:bdff/64          ethernet    up   1492 XX:XX:XX:XX:XX:XX
eth0 (eth0)  192.168.2.102/24                      ethernet    up   1492 XX:XX:XX:XX:XX:XX
eth1 (eth1)  fe80::bd91:5ca4:4697:115e/64          ethernet    up   1500 XX:XX:XX:XX:XX:XX
eth1 (eth1)  192.168.56.1/24                       ethernet    up   1500 XX:XX:XX:XX:XX:XX
eth2 (eth2)  fe80::e533:5ef0:c8bb:68b3/64          ethernet    down 1500 XX:XX:XX:XX:XX:XX
eth2 (eth2)  169.254.104.179/16                    ethernet    down 1500 XX:XX:XX:XX:XX:XX
eth3 (eth3)  fe80::102f:34a7:4efd:bd89/64          ethernet    down 1500 XX:XX:XX:XX:XX:XX
eth3 (eth3)  169.254.189.137/16                    ethernet    down 1500 XX:XX:XX:XX:XX:XX
lo0  (lo0)   ::1/128                               loopback    up   -1
lo0  (lo0)   127.0.0.1/8                           loopback    up   -1
tun0 (tun0)  2001:0:9d38:78cf:45e:b6a:a8b1:fb17/64 point2point up   1280
tun0 (tun0)  fe80::45e:b6a:a8b1:fb17/64            point2point up   1280

DEV    WINDEVICE
eth0   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth0   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth1   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth1   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth2   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth2   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth3   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
eth3   \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
lo0    <none>
lo0    <none>
tun0   <none>
tun0   <none>
<none> \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
<none> \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
<none> \Device\NPF_{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}

**************************ROUTES**************************
DST/MASK                               DEV  METRIC GATEWAY
192.168.56.255/32                      eth1 281
255.255.255.255/32                     eth0 281
192.168.2.255/32                       eth0 281
192.168.56.1/32                        eth1 281
255.255.255.255/32                     eth1 281
192.168.2.102/32                       eth0 281
255.255.255.255/32                     eth2 311
255.255.255.255/32                     eth3 321
127.255.255.255/32                     lo0  331
127.0.0.1/32                           lo0  331
255.255.255.255/32                     lo0  331
192.168.56.0/24                        eth1 281
192.168.2.0/24                         eth0 281
127.0.0.0/8                            lo0  331
224.0.0.0/4                            eth1 281
224.0.0.0/4                            eth0 281
224.0.0.0/4                            eth2 311
224.0.0.0/4                            eth3 321
224.0.0.0/4                            lo0  331
0.0.0.0/0                              eth0 25     192.168.2.1
fe80::bd91:5ca4:4697:115e/128          eth1 281
fe80::a1e9:5523:a1f3:bdff/128          eth0 281
fe80::e533:5ef0:c8bb:68b3/128          eth2 311
fe80::102f:34a7:4efd:bd89/128          eth3 321
::1/128                                lo0  331
2001:0:9d38:78cf:45e:b6a:a8b1:fb17/128 tun0 331
fe80::45e:b6a:a8b1:fb17/128            tun0 331
fe80::/64                              eth0 281
fe80::/64                              eth1 281
fe80::/64                              eth2 311
fe80::/64                              eth3 321
fe80::/64                              tun0 331
2001::/32                              tun0 331
ff00::/8                               eth0 281
ff00::/8                               eth1 281
ff00::/8                               eth2 311
ff00::/8                               eth3 321
ff00::/8                               tun0 331
ff00::/8                               lo0  331
::/0                                   tun0 331
```

**Comment by gvanem** [comment]
>  ... the delusion that "eth0" ..

It's not a *delusion*. It's an adaption to make Nmap more Posix-like. Have you actually used Nmap on Windows? Press the **CLICK ME** above and see what device-names are behind those `ethX` names.

**Comment by bortiz557** [comment]
I was able to get this to work by installing nmap 7.70 without selecting npcap 0.99-r2.

**Comment by codebeat-nl** [comment]
Got the same error win7 ultimate. Upgrade software, reboot several times, no effect. No solution to this?

**Comment by bortiz557** [comment]
Codebeat-nl 
I was able to get this to work by installing nmap 7.70 without selecting npcap 0.99-r2.

**Comment by lugerf** [comment]
Had the same issue. For me it was solved by replacing the installation of npcap 0.99-r9 (was installed with wireshark) with version 0.99-r2.  The latter one is working well now.

**Comment by lorrangarcia** [comment]
I remove the npcap  0.99-r9 and install the last version of npcap Npcap 0.992 and the problem was solved. > https://nmap.org/npcap/

**Comment by apacoco9861** [comment]
I found the problem happen on Ubuntu 18.10 when install by snap install nmap which is 7.7
when apt install nmap to install 7.6, problem gone

**Comment by sarah-rose** [comment]
Reinstalled Npcap on Win 10, works now.

**Comment by dmiller-nmap** [comment]
This problem should be solved with Npcap 0.995. If you are having this problem with Nmap 7.70, first upgrade Npcap to the latest version from https://npcap.org/#download and try again. If you still have a problem, please open a new bug report. Thanks!

**Comment by trich101** [comment]
So I am on Nmap 7.60 but same error. Read this thread and went to add remove and uninstalled the copy of npcap that came with Nmap, 9.3. I did not touch Nmap itself. I then installed the most recent copy of Npcap 0.9983, as of 10/9/19.  Closed Nmap and opened it again, performed same scan and works perfect now. Thanks everyone..

**Comment by Dave4626** [comment]
> 
> 
> So I am on Nmap 7.60 in Win10 but same error. Read this thread and went to add remove and uninstalled the copy of npcap that came with Nmap, 9.3. I did not touch Nmap itself. I then installed the most recent copy of Npcap 0.9983, as of 10/9/19. Closed Nmap and opened it again, performed same scan and works perfect now. Thanks everyone..

I had same issue and this approach works for me as well. Thanks.

**Comment by azri7744** [comment]
removing npcap and installing the latest version solved it for me... thank you

**Comment by d1w0u** [comment]
I used "sudo apt install --reinstall nmap"

**Comment by eliehaykal** [comment]
> I remove the npcap 0.99-r9 and install the last version of npcap Npcap 0.992 and the problem was solved. > https://nmap.org/npcap/

Solved on Win 10 -- thanks

**Comment by mayankjain1609** [comment]
uninstalled version 0.9989 which was installed with nmap , and installed latest version 0.9990 worked
perfectly!

**Comment by dmiller-nmap** [comment]
This issue is closed. The issue description is a very general error message indicating a failure to enumerate or open network interfaces, and can happen on any operating system. If you experience this error, please follow these steps to diagnose and resolve:

1. If on Windows, update Npcap to the latest release from https://npcap.org/#download
2. Update Nmap to the latest version from https://nmap.org/download.html
3. If you still have a problem, file a bug report including the output of `nmap --version`, `nmap --iflist`, and either `uname -a` for Linux/macOS/UNIX or [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues) for Windows.
