### ISSUE TITLE
tftp-enum checks for Cisco configs even when `tftp-enum.filelist` specifies just a few files.

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#117]
tftp-enum should be able to be used to check for just a few files without trying all 256 address-based filenames for Cisco devices. One way to accomplish this would be to support a range operator in filenames. We already substitute MAC address for "{MAC}", so something like "{IP}" or "{0-255}" could be used, or simply use "{cisco}" to mean "use the existing function to generate all cisco config names." That way a custom filelist can avoid including all of them.

**Comment by sriram0706** [comment]
Fixed

**Comment by sriram0706** [comment]
fixed
