### ISSUE TITLE
Cannot get raw wireless packets in wireshark

### ISSUE THREAD

**Issue by schmug** [nmap/nmap#1180]
I'm attempting to use a Macbook 9,2 running Windows 10, pncap 0.99r3, the built-in wireless adapter, and Wireshark to capture raw 802.11 packets. 

The best I can get at the moment is I can manually set the adapter into monitor mode using wlanhelper.exe. Using wireshark I never see any raw packets whether I manually set monitor mode or attempt to click the monitor mode checkbox in wireshark (it just unselects).

I also believe there is conflicting information on this page [Npcap guide]:(https://nmap.org/npcap/guide/npcap-devguide.html). 

> You need to use WlanHelper.exe tool to switch on the “Monitor Mode” in order to see 802.11 control and management packets in Wireshark

> If you want to use Wireshark to capture raw 802.11 traffic in “Monitor Mode”, you need to switch on the monitor mode inside the Wireshark UI instead of using WlanHelper.exe

I am running Windows 10 Pro 16299. I've got wireless driver version  7.35.118.73 from 7/12/2017. I have tried both methods of changing to monitor mode.

[DiagReport-20180409-155625.txt](https://github.com/nmap/nmap/files/1891610/DiagReport-20180409-155625.txt)
[NPFInstall.log](https://github.com/nmap/nmap/files/1891611/NPFInstall.log)

**Comment by dmiller-nmap** [comment]
We are now tracking compatibility with various WiFi adapters on SecWiki at the Npcap/WiFi adapters page. Please ensure you are using the latest Npcap and follow the directions there for determining level of WiFi capture support. You may update this issue, edit the SecWiki page, or email us directly at dev@nmap.org with adapter info.
