### ISSUE TITLE
Npcap OEM Silent Uninstaller should Silently Uninstall WinPcap

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#1195]
Npcap OEM (https://nmap.org/npcap/oem/) includes a silent installer.  But if Winpcap-Compatible mode is chosen, and the original WinPcap installer is already on the machine, it needs to be uninstalled.  And that is currently done by running the WinPcap uninstaller, which opens dialogues for user input.  So this defeats the point of Npcap OEM silent install and can be particularly problematic if silent install was used because it is a headless PC and/or mass install and/or there are other reasons that users can't be there to help the uninstall along.

We already have original-winpcap uninstall code in our old nmap-winpcap installer, so we should port that to our Npcap installer.  For now it should just go in Npcap OEM since that is the only one which has silent install feature anyway.  But we could consider using it for non-silent install in the future for both Npcap and Npcap OEM.  The main advantage of this is that it avoids WinPcap uninstaller prompting for reboot (which will abort Npcap install if the user chooses yes to reboot).  We already have a popup panel asking users not to choose reboot, but they might do so anyway.  The disadvantage of using our uninstaller in non-silent mode is that the official uninstaller seems like a cleaner way to do it.

**Comment by dmiller-nmap** [comment]
Added in Npcap 0.99-r5
