### ISSUE TITLE
bittorrent.lua parse_buffer: "A dict key has to be a string or escape."

### ISSUE THREAD

**Issue by fslove** [nmap/nmap#1203]
> if tonumber( string.char( buf:byte(pos) ) ) then

> char = "l"
> hex:6c

[test.zip](https://github.com/nmap/nmap/files/1957447/test.zip)

**Comment by fslove** [comment]
>        elseif cur.type == "dict" then
>         local item = {} -- {key = <string>, value = <.*>}
>         -- key
>         if tonumber( string.char( buf:byte(pos) ) ) then
>           local str
>           local tmp_pos = pos
>           str, pos = bdec_string(buf, pos)
>           if not str then return nil, "Error parsing string.", pos end
>           item.key = str
>           -- fill the info_pos_start
>           if item.key == "info" and not info_pos_start then info_pos_start = pos end
> 
>         elseif "e" == string.char(buf:byte(pos)) then
>           if info_buf_count == 0 then
>             info_pos_end = pos-1
>           end
>           if info_pos_start and (not info_pos_end) then
>             info_buf_count = info_buf_count -1
>           end
> 
>           table.remove(stack, #stack)
>           cur = stack[#stack]
>           if not cur then return nil, "Problem with list closure:", pos end
>           pos = pos+1
> 
>         else
>           return nil, "A dict key has to be a string or escape.", pos
>         end

we need add elseif "i" == string.char(buf:byte(pos)) then ?

**Comment by dmiller-nmap** [comment]
Thanks for the report! We had 2 separate functions doing the same parsing, and the one in use here (`parse_buffer`) was doing some things wrong. I changed it so that it calls `bdecode` for the actual parsing, and it works now. Also I found several other bugs and fixed them.
