### ISSUE TITLE
pause and continue

### ISSUE THREAD

**Issue by MrCPF** [nmap/nmap#1206]
Can I control nmap scanning process, such as pause and continue？thanks

**Comment by dmiller-nmap** [comment]
Nmap has some [scan interaction](https://nmap.org/book/man-runtime-interaction.html#man-runtime-interaction), mostly limited to changing the information that is shown during scanning. A scan that is interrupted (such as with Ctrl+C) can be [resumed from the output file](https://nmap.org/book/man-output.html#idm46159112898960); any targets that haven't finished being scanned and output will be re-scanned.
