### ISSUE TITLE
bencode and parse_buffer "Problem with list closure"

### ISSUE THREAD

**Issue by fslove** [nmap/nmap#1221]
[
[sample_nmap.zip](https://github.com/nmap/nmap/files/2020136/sample_nmap.zip)

**Comment by fslove** [comment]
About 1 million samples, only this one is wrong

**Comment by fslove** [comment]
waiting...

**Comment by b4ldr** [comment]
This issues should probably be closed, zip contains a torrent file to something call hd_ Pacopacomama

i am curious what is Pacopacomama? google only came up with asian fetish porn and im not curious enough to continue searching
