### ISSUE TITLE
nmap port scan fd number up to 1024

### ISSUE THREAD

**Issue by XiaobingQi** [nmap/nmap#1222]
when the target open too many ports,then some times nmap return an error:
Attempt to FD_ISSET fd 1024 ,which is not less than FD_SETSIZE(1024). Try using a lower parallelism....

this is because of the FD_SET check for select progress.when fd > 1024,then nmap report error.

so my question is:why do not use epoll to finish port scan?

**Comment by gvanem** [comment]
On what OS?
Have you tried `nmap --nsock-engine=epoll ...`? If your system makes ` HAVE_EPOLL` possible.

**Comment by dmiller-nmap** [comment]
Nmap's code uses `select()` for TCP Connect scan (`-sT`), and we make every effort to keep socket use below the `FD_SETSIZE` limit. If you use `--max-parallelism` with a value near 1000, it is likely you will go over this limit and the error will stop your scan. The solution is to either use TCP SYN scan (`-sS`) or set a lower `--max-parallelism` value.

Regarding the use of `epoll()`, we have existing efforts to port TCP Connect scan to Nsock, which uses `epoll()`, `poll()`, `kqueue()`, or IO Completion Ports (Windows) to do efficient management of large numbers of asynchronous socket operations. See #215 for some related info.
