### ISSUE TITLE
ncat cannot listen to multiple UDP clients

### ISSUE THREAD

**Issue by pronebird** [nmap/nmap#1223]
Hi,

I have a simple program that sends a message to UDP port. I'd like to use ncat to monitor it. The program itself opens a new UDP connection each time it sends a new message, so it seems that ncat is not able to handle multiple clients at the same time since I only see the message received from the very first client and only once.

```
ncat -ul 1234
```

After showing the first message, ncat hangs. If I hit enter it prints out:

>Ncat: An existing connection was forcibly closed by the remote host

In case of macOS and netcat everything works fine with a very small timeout, i.e: `nc -ul 1234 -w 1`, same trick doesn't work with ncat though.

**Comment by si74** [comment]
I'm experiencing the same issue on Ubuntu 20.04

**Comment by dmiller-nmap** [comment]
This has been expected behavior. Traditional and OpenBSD netcats also have this limitation. However, I have updated Ncat to be able to support multiple UDP clients with the `--keep-open` or `-k` option. The commit message will close this issue when it is synced.
