### ISSUE TITLE
ncat no resolves the desired endpoint in PROXY connections

### ISSUE THREAD

**Issue by jaymzh** [nmap/nmap#1230]
I spent a while git-bisecting this and it comes down to this commit:

https://github.com/nmap/nmap/commit/21b7e3818dab6edad641111a3be12e61ac36f32a

Before this commit, if you did:
```
./ncat/ncat --proxy-type http --proxy MYPROXY:8080 ENDPOINT
```
Then what was sent to MYPROXY was:
```
CONNECT [2611:1a:e10::4]:22 HTTP/1.0\r\n
```

Where `2611:1a:e10::4` is the IPv6 address of ENDPOINT.

After this commit, this is sent:
```
CONNECT ENDPOINT:22 HTTP/1.0\r\n
```

Which the proxy may not be able to resolve which causes a failed to resolve error, which then breaks being able to proxy.

**Comment by landgraf** [comment]
Can you verify please? 
https://github.com/nmap/nmap/pull/1214

**Comment by jaymzh** [comment]
I'll give that a shot today, but I'm referring to HTTP proxy, not socks4 proxy, and that commit looks specific to socks4.

**Comment by jaymzh** [comment]
Thanks. Ping me again when the PR is updated, and I'll happily test.

**Comment by nnposter** [comment]
Could you please take a look at #1439 and let me know if it would meet your needs?

**Comment by jaymzh** [comment]
commented on the PR, thanks!

**Comment by landgraf** [comment]
Hi @nnposter ,
#1439  looks good. Thanks!

**Comment by nnposter** [comment]
Ability to control DNS resolution implemented in r37586. Thank you for raising up the issue.
