### ISSUE TITLE
Npcap Loopback Adapter does not appear in ipconfig

### ISSUE THREAD

**Issue by Deuce1058** [nmap/nmap#1241]
I have upgraded to npcap 0.99 r6 from npcap 0.94 on Win7 x64. After restarting windows, Wireshark 2.4.7 x64 sees Npcap Loopback Adapter but ipconfig does not report the npcap adapter. It was previously visible under npcap 0.94. 

npcap was installed with these options:
Automatically start Npcap driver at boot time 
Support loopback traffic ("Npcap Loopback Adapter" will be created)

I have verified that Base Filtering Engine and npcap are started.

In Network Connections I can see the Npcap Loopback Adapter status is Not Connected.

Wireshark doesnt see any traffic on the Npcap Loopback Adapter. I expected to see lots of traffic between the database, the server and the application which are all running locally.

**Comment by dmiller-nmap** [comment]
Do you have WinPcap, Win10Pcap, or Npcap in WinPcap API-compatible mode installed? Wireshark currently prefers the old WinPcap DLLs, which do not support loopback capture, so removing those and installing Npcap **without** WinPcap mode will usually fix this.

**Comment by Deuce1058** [comment]
@dmiller-nmap Somewhere along the way I installed WinPcap. I uninstalled WinPcap and Npcap. Reinstalled Npcap with these options only: 
Automatically start Npcap driver at boot time
Support loopback traffic ("Npcap Loopback Adapter" will be created)

Now Wireshark sees traffic on the Npcap Loopback Adapter. 
Thanks for the reply!

**Comment by dmiller-nmap** [comment]
Glad it's working for you now.
