### ISSUE TITLE
nmap OS Fingerprinting

### ISSUE THREAD

**Issue by ahmedkhiar** [nmap/nmap#1246]
Hello all,

I want to evade nmap's TCP/IP fingerprinting, which it is used to detect the OS on a machine. Is there a way to manipulate the TCP/IP implementation in the kernel to evade this detection or highliting another operating system ? 

Thank you.

**Comment by fyodor** [comment]
Hi.  Many people have done research on that, and even produced some tools to attempt to confuse active OS detection.  But this isn't really appropriate for the Nmap bug/issue tracker. Cheers!
