### ISSUE TITLE
smb-brute/msrpc script bug

### ISSUE THREAD

**Issue by DuoMorph** [nmap/nmap#1255]
Nmap latest stable version (7.70) not may found password from correct users in smb server. **But nmap version 7.31 is worked fine with this nmap command.**

cmd: nmap -T5 --script smb-brute.nse -p445 --open --script-args userdb=u.txt,passdb=p.txt,smbtype=v2 192.168.0.32-33 -d
....
> NSE: smb-brute against 192.168.0.32 threw an error!
C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4424: bad argument #2 to 'date' (number has no integer representation)
stack traceback:
        [C]: in function 'os.date'
        C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4424: in upvalue 'get_domain_info'
        C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4529: in function 'msrpc.get_domains'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:516: in upvalue 'bad_lockout_policy'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:918: in global 'found_account'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1050: in upvalue 'go'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1079: in function <C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1067>
        (...tail calls...)

> NSE: smb-brute against 192.168.0.33 threw an error!
C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4424: bad argument #2 to 'date' (number has no integer representation)
stack traceback:
        [C]: in function 'os.date'
        C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4424: in upvalue 'get_domain_info'
        C:\Program Files (x86)\Nmap/nselib/msrpc.lua:4529: in function 'msrpc.get_domains'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:516: in upvalue 'bad_lockout_policy'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:918: in global 'found_account'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1050: in upvalue 'go'
        C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1079: in function <C:\Program Files (x86)\Nmap/scripts\smb-brute.nse:1067>
        (...tail calls...)
...

$ nmap --version
Nmap version 7.70 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.3 openssl-1.0.2n nmap-libssh2-1.8.0 nmap-libz-1.2.8 nmap-libpcre-7.6 Npcap-0.99-r2 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Comment by DuoMorph** [comment]
Need to round querydomaininfo2_result_8['info']['domain_create_time'] to int value in msrpc.lua:4424?
Insert "querydomaininfo2_result_8['info']['domain_create_time'] = math.floor(querydomaininfo2_result_8['info']['domain_create_time'])" before "if..." in msrpc workaround problem.
`  if(querydomaininfo2_result_8['info']['domain_create_time'] ~= 0) then
    querydomaininfo2_result_8['info']['domain_create_time'] = math.floor(querydomaininfo2_result_8['info']['domain_create_time'])
    response['created'] = os.date("%Y-%m-%d %H:%M:%S", querydomaininfo2_result_8['info']['domain_create_time'])
  else
    response['created'] = "unknown"
  end`

**Comment by dmiller-nmap** [comment]
Thanks for the report! I think I've addressed this in an upcoming commit. Please let us know if it is not solved after this issue is closed.

**Comment by recoverycount** [comment]
error still happening any solution?

**Comment by mechs85** [comment]
Hi, this is still occurring for me in smb-enum-sessions

Is there any fix?

**Comment by dmiller-nmap** [comment]
@recoverycount @mechs85 Is it exactly this same issue (same line number and error)? We just fixed a similar issue #1303 that affected Nmap on Windows only that might have been related. Otherwise, please make a new Issue with a copy of the error you are receiving.
