### ISSUE TITLE
nmap update !

### ISSUE THREAD

**Issue by talal2** [nmap/nmap#1257]
Hi !

Is the nmap get updated automatically when i ---> apt-get update && apt-get upgrade && apt-get dist-upgrade in kali, or i need to re-compile it again ?

                          Much appreciated ;) :)

**Comment by nnposter** [comment]
Nmap is provided by Kali but they do not push the new version immediately. Last time the delay was about a month if I recall correctly.

If you set up Nmap on your own by hand then it is not seen as an installed deb package so you are equally on your own to keep it current as you see fit.

**Comment by dmiller-nmap** [comment]
This is a question to ask the people who do package management for Kali Linux. Nmap's installation options are listed here: https://nmap.org/book/install.html
