### ISSUE TITLE
[Ncat]SSL Error When Connect From Linux To Windows

### ISSUE THREAD

**Issue by hex4d0r** [nmap/nmap#1266]
On Windows,

NCAT 5.59BETA1

On Linux,

NCAT 7.6

Windows Output,
`C:\Users\Administrator>ncat -nvlp 5555 --ssl`
`Ncat: Version 5.59BETA1 ( http://nmap.org/ncat )`
`Ncat: Generating a temporary 1024-bit RSA key. Use --ssl-key and --ssl-cert to use a permanent one.`
`Ncat: SHA-1 fingerprint: D077 FD80 9474 E845 C429 6068 CE83 A110 03CA 35D7`
`Ncat: Listening on 0.0.0.0:5555`
`Ncat: Connection from [client]:56592.`
`Ncat: Failed SSL connection from [client]: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number`

Linux Output,
`ncat -nv [host] --ssl`
`Ncat: Version 7.60 ( https://nmap.org/ncat )`
`Ncat: Connection timed out.`

It also happens opposite connection.

**Comment by dmiller-nmap** [comment]
Thanks for the bug report! Unfortunately, Ncat 5.59BETA1 is 7 years old by now, and we've made significant changes and fixes to it. Specifically for your issue, #773 was fixed in Ncat 7.50 and #1049 was fixed in Ncat 7.70. If this issue still happens with Ncat 7.70, please reopen or open a new issue. Thanks!

**Comment by slw07g** [comment]
Unfortunately, Nmap (for windows) only ships with Ncat 5.59BETA1. I can't find 7.70 ncat.exe anywhere.

**Comment by slw07g** [comment]
This might help others encountering the same issue:
I was able to install 6.49 beta 1 on my Kali endpoint. I downloaded it from https://nmap.org/dist/.

I used alien to [extract its contents](https://askubuntu.com/a/52234/335404) and ran the extracted ncat from `./usr/bin/`
