### ISSUE TITLE
ncrack error 

### ISSUE THREAD

**Issue by MrCrypt99** [nmap/nmap#1270]
HI dear,
when I start a brute force operation with this command: ncrack -U user.txt -P pass.txt 127.0.0.1:22 I receive the error message: failed to open input file users.txt for reading!
Quitting! if instead I write on the terminal in this way:
ncrack -U user -P pass 127.0.0.1:22
I get the problem: segmentation error how can I solve the problem?

**Comment by lewisstennis** [comment]
I am getting the same error. But don't know why and I don't see anything only saying why?
