### ISSUE TITLE
libpcap issues with tip

### ISSUE THREAD

**Issue by sfx2000** [nmap/nmap#1275]
Building off both svn and git tip - looks like the libpcap update to 1.8.1 might have broken things - see this on both debian stretch and ubuntu bionic.

Confirmed that host as a recent libpcap-dev...

apt list libpcap-dev
Listing... Done
libpcap-dev/bionic 1.8.1-6ubuntu1 amd64

=======
Build failure...

gcc -fvisibility=hidden -fpic -I.  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -g -O2    -c ./fad-helpers.c
make[2]: Entering directory '/home/sfx/builds/nmap/libpcap'
make[2]: *** No rule to make target 'w'.  Stop.
make[2]: Leaving directory '/home/sfx/builds/nmap/libpcap'
Makefile:459: recipe for target 'grammar.h' failed
make[1]: *** [grammar.h] Error 2
make[1]: Leaving directory '/home/sfx/builds/nmap/libpcap'
Makefile:145: recipe for target 'build-pcap' failed
make: *** [build-pcap] Error 2

=======
Did a make clean/make distclean - resyncing back up to things - svn presents this, restoring things below.

~/builds/nmap $ svn up
Updating '.':
Restored 'libpcap/grammar.c'
At revision 37293.

Also did a full rm -rf and pull and still seeing same issue.

Thoughts here?

**Comment by sfx2000** [comment]
Nevermind - solved my own issue with the libpcap-dev dependency...

Was in the repo's, but not installed.

**Comment by dmiller-nmap** [comment]
I found the same problem happened because I did not commit the generated `grammar.h` file. This didn't produce a problem before, but I'll be putting in a change to fix it momentarily.

**Comment by sfx2000** [comment]
Saw the commit on SVN - thx!

Works on arm and x86-64 now
