### ISSUE TITLE
Npcap Loopback Adapter does not show in ipconfig but works with Wireshark

### ISSUE THREAD

**Issue by BLTSIZE** [nmap/nmap#1284]
The problem occurs on a laptop with WiFi card only, running on Windows 7 latest updates. Winpcap was never installed on this laptop.  

After installing Npcap version 0.99r7 with the default options ("Automaticaly start the Npcap driver...", "Support loopback traffic (...)" and "Use DLT_NULL as the loopback..."), the loopback adapter shows in the Control Panel, along with the WiFi card ("Npcap Loopback Adapter").  Wireshark detects the loopback adapter and is able to sniff a classic ICMP traffic (from the DOS prompt : "ping 127.0.0.1").

The problem occurs with ipconfig, because "ipconfig /all" does not reports the Npcap Loopback Adapter. It reports nothing more than when Npcap is not installed (capture follows). Any idea ? 

I had a look at : 

https://github.com/nmap/nmap/issues/592
https://github.com/nmap/nmap/issues/1241

No success.

If this may help, I'm using Scapy. When I list the interfaces, I only get one entry : the "Intel(R) Centrino(R) Advanced-N 6235". And if I call the Scapy function route_add_loopback(), I get a new entry : the "Npcap Loopback Adapter".

**Comment by gpotter2** [comment]
Random comment: please note that `route_add_loopback()` says when launched
> WARNING: This will completely mess up the routes. Testing purpose only !

**Comment by dmiller-nmap** [comment]
Thanks for the report! The Npcap Loopback Adapter was known to cause problems with some software, so we removed the need for it in Npcap 0.9983, released today. Be sure to deselect (un-check) the "Legacy loopback support" to get the new loopback capture support without cluttering up the list of real network adapters. Let us know how it works for you.
