### ISSUE TITLE
ipOps.get_ips_from_range() does not return true first address

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1285]
Function `ipOps.get_ips_from_range` is described as follows:

> Returns the first and last IP addresses in the supplied range of IPv4 or IPv6 addresses in either CIDR or first-last notation.

The returned last address is calculated as expected but the first address is merely copied from the supplied "range" even if the range is a CIDR block. As an example:

```lua
ipOps.get_ips_from_range("192.168.73.128/24")
```

returns `192.168.73.128`, `192.168.73.255`, instead of the more logical result of `192.168.73.0`, `192.168.73.255`. (If doubting how realistic this example is, look no further than iproute2, which is a Linux core utility.)

Function `ipOps.ip_in_range` is similarly impacted (because of its dependency on `ipOps.get_ips_from_range`):

```lua
ipOps.ip_in_range("192.168.73.5", "192.168.73.128/24")
```

returns `false`.

I am planning to change the code to return true first address in the supplied CIDR block. I have reviewed all current scripts and libraries that consume `ipOps.get_ips_from_range` or `ipOps.ip_in_range` and I believe that there should be no impact. That said, I will let this issue sit here for a while so that other people can raise concerns.

**Comment by djcater** [comment]
This seems like a sensible change. The current behaviour is unexpected, at least to me.
