### ISSUE TITLE
Implement RFC 4419 DH group exchange for ssh2.lua

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#129]
Right now, ssh-hostkey can only get hostkeys for hosts that support the `diffie-hellman-group1-*` or `diffie-hellman-group14-` key exchange (KEX) methods. With the recent concern over weak DH groups (see https://weakdh.org/), more and more SSH servers will be incompatible with our simple implementation. [RFC 4419](https://tools.ietf.org/html/rfc4419) is the spec for `diffie-hellman-group-exchange-*` KEX methods, which are one of the alternatives that are being put forward (the other is Elliptic Curve DH).

Before beginning this work, it would be worthwhile to check whether we can shortcut the process, since we do not intend to actually exchange keys with the server. All we need is to get far enough to gather the server's own key. Maybe we can just send some random number (not even a prime?!) to advance the handshake to the next step of receiving the server's hostkey. But be careful! This might be implementation-specific.

**Comment by sergeykhegay** [comment]
Hello! 

My name is Sergey. 
I am a first year MS Computer Science student at NYU Tandon School of Engineering.
I'm interested to apply to nmap project for the GSoC.

I've read through the RFC and it seems pretty easy to implement. Actually, I have already written a draft code. I have stumbled upon how can I test my implementation? Where can I find servers that specifically  use diffie-hellman-group-exchange-* KEX? Or should I try to configure one myself?

Also, could you explain your idea of a shortcut in more detail?
Are you talking about sending a random exponent value? Actually, I think it can work, but once again how can I test?
