### ISSUE TITLE
nmap -p [port] also scans 443 

### ISSUE THREAD

**Issue by mhale1982** [nmap/nmap#1292]
Hi guys!

Using Nmap 7.70 on Windows. 
C:\Users\mike>nmap -V
Nmap version 7.70 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.3 openssl-1.0.2n nmap-libssh2-1.8.0 nmap-libz-1.2.8 nmap-libpcre-7.6 Npcap-0.99-r2 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

If I run:
nmap -p 4072 [Target_IP]

I see the following:
ICMP (host discovery, cool)
TCP 443 (Erm, what?)
TCP 4072 (What I was looking for)

Is that expected behavior?

**Comment by djcater** [comment]
Yes. You've not specified any particular host discovery method, so the default method is used, which is described here: https://nmap.org/book/man-host-discovery.html

(Many hosts are configured not to respond to ICMP packets).

**Comment by Rourke101** [comment]
This is normal. It will check if the host is alive. Use -Pn if you want to get rid of the extra packet

**Comment by mhale1982** [comment]
OOOOH.  So the default host discovery part is ICMP echo, ICMP timestamp and 443?

**Comment by dmiller-nmap** [comment]
@mhale1982 The default host discovery is described [in the Nmap man page](https://nmap.org/book/man-host-discovery.html):

> If no host discovery options are given, Nmap sends an ICMP echo request, a TCP SYN packet to port 443, a TCP ACK packet to port 80, and an ICMP timestamp request. (For IPv6, the ICMP timestamp request is omitted because it is not part of ICMPv6.) These defaults are equivalent to the -PE -PS443 -PA80 -PP options. The exceptions to this are the ARP (for IPv4) and Neighbor Discovery (for IPv6) scans which are used for any targets on a local ethernet network. For unprivileged Unix shell users, the default probes are a SYN packet to ports 80 and 443 using the connect system call. This host discovery is often sufficient when scanning local networks, but a more comprehensive set of discovery probes is recommended for security auditing.

**Comment by mhale1982** [comment]
Derp. 

Thanks for that!  Much appreciated.
