### ISSUE TITLE
Directory listing in https://nmap.org

### ISSUE THREAD

**Issue by prasadlingamaiah** [nmap/nmap#1294]
**Discription:**
Web servers can be configured to automatically list the contents of directories that do not have an index page present. This can aid an attacker by enabling them to quickly identify the resources at a given path, and proceed directly to analyzing and attacking those resources. It particularly increases the exposure of sensitive files within the directory that are not intended to be accessible to users, such as temporary files and crash dumps.
Directory listings themselves do not necessarily constitute a security vulnerability. Any sensitive resources within the web root should in any case be properly access-controlled, and should not be accessible by an unauthorized party who happens to know or guess the URL. Even when directory listings are disabled, an attacker may guess the location of sensitive files using automated tools.

**Effected URL:**
https://nmap.org/images/flags/32/
https://nmap.org/movies/oceans8/

**Mitigation:**
We should make sure the directory does not contain sensitive information or you may want to restrict directory listings from the web server configuration.
There is not usually any good reason to provide directory listings, and disabling them may place additional hurdles in the path of an attacker. This can normally be achieved in two ways:
Configure your web server to prevent directory listings for all paths beneath the web root;
Place into each directory a default file (such as index.htm) that the web server will display instead of returning a directory listing.

![1](https://user-images.githubusercontent.com/24879082/43678234-39c300da-982d-11e8-8262-0cee74727da1.PNG)
![2](https://user-images.githubusercontent.com/24879082/43678235-3a02f866-982d-11e8-8361-61c0652371c9.PNG)
![4](https://user-images.githubusercontent.com/24879082/43678236-3a52e902-982d-11e8-875d-b86ecd3ac5c2.PNG)
![5](https://user-images.githubusercontent.com/24879082/43678237-3a8de4ee-982d-11e8-8d59-1a24b24b1176.PNG)

**Comment by dmiller-nmap** [comment]
Thanks for letting us know your concern. These are all known and specifically-allowed directory listings. If you have specific concerns about the security of data on nmap.org, please send that to fyodor via email and reserve this issue tracker for problems with Nmap software only. Thank you.
