### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [nmap/nmap#1295]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion. Nmap is distributed through nmap.org and via package maintainers for free OS distributions that perform the work of packaging and supporting it on those platforms. If a package maintainer has a concern or an enhancement request, they can open a detailed Issue for that and we will evaluate it.

**Comment by fyodor** [comment]
Thanks for your suggestion.  I've consolidated several similar issues into a new #2275 for discussing the benefits of supplying Nmap as an AppImage, Snap, or Flatpak.
