### ISSUE TITLE
nmap not reporting what it sees

### ISSUE THREAD

**Issue by Rourke101** [nmap/nmap#1298]
I am experiencing something strange. My network is like this:

VM guest with nmap <--[NAT]--> VM host <---[5Ghz]---> Router

The network link is very good, the host is also 2m from the router. I am nmaping the router at 10.10.1.1. Specifically, I do know port 80, 443 and others are open. I run the following command:

```
# nmap -n -sS -p- 10.10.1.1 -T5 -r --max-retries 0`

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 05:59 EDT
Warning: 10.10.1.1 giving up on port because retransmission cap hit (0).
Stats: 0:00:09 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
...
SYN Stealth Scan Timing: About 97.88% done; ETC: 06:07 (0:00:11 remaining)
Nmap scan report for 10.10.1.1
Host is up (0.32s latency).
Not shown: 65534 filtered ports
PORT   STATE SERVICE
23/tcp open  telnet

Nmap done: 1 IP address (1 host up) scanned in 504.51 seconds
```
It takes a very long time (even times out if I do not use the maxretries), and no port 80 appears. However, in my wireshark capture, I can see that the router has sent the SYN-ACK correctly. Then nmap and the router stayed sending RST and SYN+ACK for some time. So nmap does know the port is open. Another strange thing is that nmap reports "65534 filtered ports" when I can see in the capture that the router sent RST packages for all of them.

![image](https://user-images.githubusercontent.com/20154036/43830512-b6149a78-9b01-11e8-8f60-5ccb7247597f.png)

I have done different tests with similar strange behaviour. For example:
```
# nmap -n -sS -F 10.10.1.1 -T5 -r --max-retries 0

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 06:17 EDT
Warning: 10.10.1.1 giving up on port because retransmission cap hit (0).
Nmap scan report for 10.10.1.1
Host is up (0.020s latency).
Not shown: 98 filtered ports
PORT   STATE SERVICE
23/tcp open  telnet
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 0.84 seconds
```

Again showing filtered ports when I see the RST responses, and also I see the SYN+ACK answer from 443, responded by nmap with RST but not reported here. I have been trying different things and found different behaviour depending on speed (-Tx), which could perhaps explain some things (see logs below).

Independently, my questions are:

-  Why nmap is not reporting what it is actually seeing in the network? (and I know it sees it because I see nmap responding to some SYN+ACK but not reporting them). Is it a bug or something logical for my environment?

- Why do I get so different results even running the same command after a few seconds? Is it something related to timing (Tx)?

## Some logs:

You can see I get very different results from one to another, even repeating the same command a few seconds later.

```
# nmap -n -sS -F 10.10.1.1 -T5 -r --max-retries 0 --reason -vv

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:07 EDT
Initiating Ping Scan at 07:07
Scanning 10.10.1.1 [4 ports]
Completed Ping Scan at 07:07, 0.06s elapsed (1 total hosts)
Initiating SYN Stealth Scan at 07:07
Scanning 10.10.1.1 [100 ports]
Discovered open port 23/tcp on 10.10.1.1
Warning: 10.10.1.1 giving up on port because retransmission cap hit (0).
Discovered open port 80/tcp on 10.10.1.1
Completed SYN Stealth Scan at 07:07, 0.64s elapsed (100 total ports)
Nmap scan report for 10.10.1.1
Host is up, received echo-reply ttl 128 (0.022s latency).
Scanned at 2018-07-23 07:07:38 EDT for 1s
Not shown: 98 filtered ports
Reason: 98 no-responses
PORT   STATE SERVICE REASON
23/tcp open  telnet  syn-ack ttl 128
80/tcp open  http    syn-ack ttl 128

Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 0.87 seconds
           Raw packets sent: 104 (4.552KB) | Rcvd: 9 (401B)

# nmap -n -sS -F 10.10.1.1 -T4 -r

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:09 EDT
Nmap scan report for 10.10.1.1
Host is up (1.2s latency).
Not shown: 94 closed ports
PORT     STATE    SERVICE
23/tcp   open     telnet
53/tcp   open     domain
80/tcp   open     http
443/tcp  open     https
514/tcp  filtered shell
8080/tcp filtered http-proxy

Nmap done: 1 IP address (1 host up) scanned in 7.93 seconds

# nmap -n -sS -F 10.10.1.1 -T5 -r

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:09 EDT
Nmap scan report for 10.10.1.1
Host is up (0.57s latency).
Not shown: 88 filtered ports
PORT    STATE  SERVICE
7/tcp   closed echo
9/tcp   closed discard
13/tcp  closed daytime
21/tcp  closed ftp
22/tcp  closed ssh
23/tcp  open   telnet
25/tcp  closed smtp
26/tcp  closed rsftp
37/tcp  closed time
53/tcp  open   domain
80/tcp  open   http
443/tcp open   https

Nmap done: 1 IP address (1 host up) scanned in 2.55 seconds

# nmap -n -sS -F 10.10.1.1 -T3 -r

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:09 EDT
Nmap scan report for 10.10.1.1
Host is up (1.7s latency).
Not shown: 94 closed ports
PORT     STATE    SERVICE
23/tcp   open     telnet
53/tcp   open     domain
80/tcp   open     http
443/tcp  open     https
514/tcp  filtered shell
8080/tcp filtered http-proxy

Nmap done: 1 IP address (1 host up) scanned in 10.69 seconds

# nmap -n -sS -F 10.10.1.1 -T4 -r

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:10 EDT
Nmap scan report for 10.10.1.1
Host is up (1.5s latency).
Not shown: 94 closed ports
PORT     STATE    SERVICE
23/tcp   open     telnet
53/tcp   open     domain
80/tcp   open     http
443/tcp  open     https
514/tcp  filtered shell
8080/tcp filtered http-proxy

Nmap done: 1 IP address (1 host up) scanned in 7.98 seconds

# nmap -n -sS -F 10.10.1.1 -T5 -r

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-23 07:10 EDT
Nmap scan report for 10.10.1.1
Host is up (2.3s latency).
Not shown: 54 closed ports, 42 filtered ports
PORT    STATE SERVICE
23/tcp  open  telnet
53/tcp  open  domain
80/tcp  open  http
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 4.47 seconds

```

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Virtual NAT is usually incapable of handling the number of attempted connections that Nmap makes, especially with higher-speed timing profiles like `-T5`. If you do a network capture on the virtual machine where Nmap is running, you will see that the response traffic just doesn't reach Nmap. There's not much else we can do besides recommending that you use bridged networking instead.

**Comment by Rourke101** [comment]
Thanks for your answer, however I am capturing the traffic from the actual VM (so running nmap and wshark in parallel) and as you can see in the image, nmap did receive the SYN+ACK, and moreover, it actually replied it!  However this is not shown in the report. That is my question.
