### ISSUE TITLE
snmp-brute script doesn't work with IPv6

### ISSUE THREAD

**Issue by G10h4ck** [nmap/nmap#130]
snmp-brute NSE script doesn't work with IPv6, from a brief investigation it seems that the code inside sniff_snmp_responses isn't IPversion agnostic, and that may me the cause of the problem

**Comment by G10h4ck** [comment]
This commit should make snmp-brute ipversion agnostic
https://gitlab.com/g10h4ck/nmap-gsoc2015/commit/238d0d82bbfeafaa2395124b116565bdd7ae31f7

I have done lots of tests, IPv4 keep working while, the problem with IPv6 now seem that Nmap NSE libpcap doesn't get incoming IPv6 packets while tcpdump do...

From the tests I have done IPv4 work both outbound and inbound direction while IPv6 get just outbound packets

I do tests on 
Linux 3.18.7-gentoo x86_64

More tests and feedback are welcome

**Comment by dmiller-nmap** [comment]
@G10h4ck Your patch works well for me here. Please commit it, being sure to include "Fixes #130" in the commit message. We can talk about your libpcap problems in our next meeting.

**Comment by G10h4ck** [comment]
Fix commited in r34542 = 1799428a3530f125cedfc85c9da1dd91a28d3580
