### ISSUE TITLE
NSE script hanging 

### ISSUE THREAD

**Issue by aidylewis** [nmap/nmap#1304]
I am running the NSE **vuln** category of scripts

```
$ nmap --script vuln -p <port> <ip>
```

But I am getting a script hang
```
NSE Timing: About 91.89% done; ETC: **12:45** (0:00:04 remaining)
NSE Timing: About 91.89% done; ETC: **12:55** (0:00:04 remaining)

```
I am trying to find out what script is hanging. I tried **--script-trace**, but it's too low level. 

Thanks
@aidylewis

**Comment by aidylewis** [comment]
Sorry, it is still hanging on the *vuln* class of scripts (even after upgrading v7). It seems to be only on port 443.

**Comment by paolo-tanium** [comment]
This has been par for the course in my experience. The remaining time hasn't been indicative of what is really left.

**Comment by aidylewis** [comment]
Thanks @paolo-tanium. Is there any way of printing the current running script to stdout?

**Comment by tremblerz** [comment]
You can use `--script-timeout` flag.
