### ISSUE TITLE
http-form-brute always end at 900s

### ISSUE THREAD

**Issue by tomta555** [nmap/nmap#1305]
I am running NSE http-form-brute on Kali linux on my lab to brute force password that need more than 900s to crack.
so I add `--host-timeout 400m --script-timeout 400m` and nothing change.
It not working and always end at 900s

this is timing report
```
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 24000000
  min-rate: 0, max-rate: 0
---------------------------------------------
```

and this is the result
```
PORT   STATE SERVICE REASON
80/tcp open  http    syn-ack ttl 64
| http-form-brute: 
|   Accounts: No valid accounts found
|_  Statistics: Performed 14051 guesses in 899 seconds, average tps: 15.6
Final times for host: srtt: 1160 rttvar: 4999  to: 100000
```
EDIT

When I test by add `--host-timeout 10s --script-timeout 10s `
the script work perfectly and stop at 10s 
but when I enter 180m, 300m, 600m it not working and still stop at 900s

Thank

**Comment by dmiller-nmap** [comment]
I think we could improve the documentation for this, but this is intended behavior. The [`unpwdb` library](https://nmap.org/nsedoc/lib/unpwdb.html) sets the time limit; after a certain amount of time, it stops yielding new credentials, and the scan ends. You can control this using the `unpwdb.timelimit` script argument. For instance, to run without a time limit:

    nmap --script-args unpwdb.timelimit=0 --script http-form-brute

**Comment by tomta555** [comment]
Oh! I see and that solve the problem. So it is my misunderstanding Haha!

Thanks for the suggestion.
