### ISSUE TITLE
NCAP 0.99-r7 failed to setup on Windows 10 Edu

### ISSUE THREAD

**Issue by manfisto** [nmap/nmap#1308]
[DiagReport-20180824-085015.txt](https://github.com/nmap/nmap/files/2316659/DiagReport-20180824-085015.txt)
[install.log](https://github.com/nmap/nmap/files/2316660/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/2316661/NPFInstall.log)

Attached are the logs after failed installation.
error message: Failed to create npcap services ........

**Comment by dmiller-nmap** [comment]
Closing due to no followup. If this issue persists in the latest Npcap version, please open a new issue. Thanks!
