### ISSUE TITLE
nmap csv output format

### ISSUE THREAD

**Issue by dsolstad** [nmap/nmap#1319]
Why hasn't this been implemented yet? Is there any plans for it?

**Comment by dmiller-nmap** [comment]
There are no plans for it. CSV is not extensible enough to handle all the possible Nmap output fields, and we already have a simple text format for legacy output, [Grepable output](https://nmap.org/book/output-formats-grepable-output.html). To answer why this has not been implemented, see #635. In short, Nmap's output processing is tightly coupled to its procedure and adding new formats is not trivial. Parsers for Nmap's XML output exist in nearly every programming language which make it fairly simple to generate any other format as needed.
