### ISSUE TITLE
Magnet link not working in bittorrent-discovery

### ISSUE THREAD

**Issue by abreksa4** [nmap/nmap#132]
Command:
nmap --script bittorrent-discovery --script-args newtargets,bittorrent-discovery.magnet=magnet:?xt=urn:btih:b415c913643e5ff49fe37d304bbb5e6e11ad5101&dn=Ubuntu+14.10+desktop++x64&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

Output: 
[1] 10484
[2] 10485
[3] 10486
[4] 10487
[5] 10488
abreksa@ubuntu:~/Desktop$ 
Starting Nmap 6.40 ( http://nmap.org ) at 2015-05-22 14:34 PDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:1173: Value around '=urn:btih:b' is invalid or is unterminated by a valid seperator
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nse_main.lua:1173: in function 'parse_string'
	/usr/bin/../share/nmap/nse_main.lua:1196: in function 'parse_table'
	/usr/bin/../share/nmap/nse_main.lua:1214: in main chunk
	[C]: in ?

QUITTING!
^C
[1]   Exit 1                  nmap --script bittorrent-discovery --script-args newtargets,bittorrent-discovery.magnet=magnet:?xt=urn:btih:b415c913643e5ff49fe37d304bbb5e6e11ad5101
[2]   Done                    dn=Ubuntu+14.10+desktop++x64
[3]   Done                    tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80
[4]-  Done                    tr=udp%3A%2F%2Fopen.demonii.com%3A1337
[5]+  Done                    tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969

**Comment by dmiller-nmap** [comment]
Script arguments must be escaped or quoted properly. This command should do what you want:

    nmap --script bittorrent-discovery --script-args 'newtargets,bittorrent-discovery.magnet="magnet:?xt=urn:btih:b415c913643e5ff49fe37d304bbb5e6e11ad5101&dn=Ubuntu+14.10+desktop++x64&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969"'
