### ISSUE TITLE
Blank "WINDEVICE" with nmap --iflist

### ISSUE THREAD

**Issue by brittadams** [nmap/nmap#1323]
DEV  WINDEVICE
eth0 <none>
eth0 <none>
eth1 <none>
eth1 <none>
lo0  <none>

*************************************************
DiagReport for Npcap ( http://npcap.org )
*************************************************
Script Architecture:		64-bit
Script Path:			C:\Program Files\Npcap\DiagReport.ps1
Current Time:			09/12/2018 10:52:06
Npcap install path:		C:\Program Files\Npcap
Npcap Version:			0.99-r7
PowerShell Version:		5.1.17746.1000

*************************************************
OS Info:
*************************************************

Caption                 : Microsoft Windows 10 Enterprise
BuildNumber             : 17746
Locale                  : 0409
MUILanguages            : {en-US}
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SystemDirectory         : C:\WINDOWS\system32
Version                 : 10.0.17746

*************************************************
CPU Info:
*************************************************

Name                      : Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Manufacturer              : GenuineIntel
DeviceID                  : CPU0
NumberOfCores             : 2
NumberOfEnabledCore       : 2
NumberOfLogicalProcessors : 4
Addresswidth              : 64

*************************************************
Memory Info:
*************************************************
Size:				16250 MB (17039765504 Bytes)

*************************************************
Network Adapter(s) Info:
*************************************************

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet 4                Fortinet SSL VPN Virtual Ethernet Ad...      30 Disabled     00-09-0F-AA-00-01       100 Gbps
Ethernet 10               Npcap Loopback Adapter                       59 Up           02-00-4C-4F-4F-50       1.2 Gbps
vEthernet (NATSwitch)     Hyper-V Virtual Ethernet Adapter #3          29 Up           00-15-5D-1E-6F-02        10 Gbps
Local Area Connection     PPPoP WAN Adapter                            22 Disconnected 00-00-00-00-00-00          0 bps
Ethernet 3                Fortinet Virtual Ethernet Adapter (N...      21 Disconnected 00-09-0F-FE-00-01       100 Mbps
vEthernet (Wireless Ex... Hyper-V Virtual Ethernet Adapter #2          15 Disconnected 3C-95-09-54-45-FB        10 Gbps
vEthernet (Default Swi... Hyper-V Virtual Ethernet Adapter             36 Up           92-15-F1-33-3F-D5        10 Gbps
Bluetooth Network Con...2 Bluetooth Device (Personal Area Ne...#2      10 Disconnected 3C-95-09-54-45-FC         3 Mbps
Wi-Fi                     Qualcomm Atheros QCA61x4A Wireless N...       2 Up           3C-95-09-54-45-FB       400 Mbps

Caption         : [00000001] Fortinet Virtual Ethernet Adapter (NDIS 6.30)
GUID            : {6F6C27CE-295C-49E1-ABFE-8C8AB2BFDBF5}
Index           : 1
InterfaceIndex  : 21
Manufacturer    : Fortinet
NetConnectionID : Ethernet 3
PNPDeviceID     : ROOT\NET\0000

Caption         : [00000005] Fortinet SSL VPN Virtual Ethernet Adapter
GUID            : {D7A6F03D-C11B-4056-9E22-821D1712B766}
Index           : 5
InterfaceIndex  : 30
Manufacturer    : Fortinet Inc.
NetConnectionID : Ethernet 4
PNPDeviceID     : ROOT\NET\0001

Caption         : [00000006] PPPoP WAN Adapter
GUID            : {77A2E5E7-1DCB-4A48-97E1-48BD5FFAD226}
Index           : 6
InterfaceIndex  : 22
Manufacturer    : Fortinet Inc.
NetConnectionID : Local Area Connection
PNPDeviceID     : ROOT\NET\0002

Caption         : [00000007] Hyper-V Virtual Ethernet Adapter
GUID            : {44B5EFA1-E10A-41F0-92E5-22F07E73D858}
Index           : 7
InterfaceIndex  : 36
Manufacturer    : Microsoft
NetConnectionID : vEthernet (Default Switch)
PNPDeviceID     : ROOT\VMS_MP\0000

Caption         : [00000008] Hyper-V Virtual Ethernet Adapter
GUID            : {577A73F4-F357-4C4C-BB03-120D3E38C7FA}
Index           : 8
InterfaceIndex  : 15
Manufacturer    : Microsoft
NetConnectionID : vEthernet (Wireless External)
PNPDeviceID     : ROOT\VMS_MP\0001

Caption         : [00000009] Hyper-V Virtual Ethernet Adapter
GUID            : {BD8BA3C3-F62A-40FC-8ACA-E177293826A8}
Index           : 9
InterfaceIndex  : 29
Manufacturer    : Microsoft
NetConnectionID : vEthernet (NATSwitch)
PNPDeviceID     : ROOT\VMS_MP\0002

Caption         : [00000010] Qualcomm Atheros QCA61x4A Wireless Network Adapter
GUID            : {00DEC2FE-D055-4013-972C-69A8372D1261}
Index           : 10
InterfaceIndex  : 2
Manufacturer    : Qualcomm Atheros Communications Inc.
NetConnectionID : Wi-Fi
PNPDeviceID     : PCI\VEN_168C&DEV_003E&SUBSYS_082717AA&REV_32\4&3103CBFB&0&00E5

Caption         : [00000012] Bluetooth Device (Personal Area Network)
GUID            : {29330F3C-A34A-429B-87C1-5CD021A91A75}
Index           : 12
InterfaceIndex  : 10
Manufacturer    : Microsoft
NetConnectionID : Bluetooth Network Connection 2
PNPDeviceID     : BTH\MS_BTHPAN\6&3A081F93&0&2

Caption         : [00000022] Microsoft KM-TEST Loopback Adapter
GUID            : {C4AE6762-21C8-47F5-87B6-F0EA4A250A17}
Index           : 22
InterfaceIndex  : 59
Manufacturer    : Microsoft
NetConnectionID : Ethernet 10
PNPDeviceID     : ROOT\NET\0003

*************************************************
NDIS Light-Weight Filter (LWF) Info:
*************************************************

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_bridge
Description      : @%SystemRoot%\system32\bridgeres.dll,-2
InfPath          : netbrdg.inf
InfSection       : Install
LocDescription   : @%SystemRoot%\system32\bridgeres.dll,-2
                   6e974-e325-11ce-bfc1-08002be10318}\{171C5016-3D19-4CB2-9556-63E586EE5010}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_wfplwf_lower
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6006
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_Lower_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6006
                   6e974-e325-11ce-bfc1-08002be10318}\{3BFD7820-D65C-4C1B-9FEA-983A019639EA}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 40
ComponentId      : ms_netbios
Description      : @%windir%\system32\drivers\netbios.sys,-501
InfPath          : netnb.inf
InfSection       : NetBIOS.ndi
LocDescription   : @%windir%\system32\drivers\netbios.sys,-501
                   6e974-e325-11ce-bfc1-08002be10318}\{42494F53-4554-004E-6E89-7EF9DE2570E3}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
ComponentId      : ms_server
Description      : @%systemroot%\system32\srvsvc.dll,-109
InfPath          : Netserv.inf
InfSection       : Install.ndi
LocDescription   : @%systemroot%\system32\srvsvc.dll,-109
                   6e974-e325-11ce-bfc1-08002be10318}\{52564552-5345-414E-2DD4-CF8F7555A888}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : vms_vsf
Description      : @%windir%\System32\drivers\vmswitch.sys,-60005
InfPath          : wvms_vsft.inf
InfSection       : VMSVSF.ndi
LocDescription   : @%windir%\System32\drivers\vmswitch.sys,-60005
                   6e974-e325-11ce-bfc1-08002be10318}\{529B8983-9625-49A5-8284-CE944FD8E242}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_vwifi
Description      : @%windir%\System32\drivers\vwififlt.sys,-105
InfPath          : netvwififlt.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\vwififlt.sys,-105
                   6e974-e325-11ce-bfc1-08002be10318}\{5CBF81BF-5055-47CD-9055-A76B2B4E3698}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {226, 7, 9, 0...}
Characteristics  : 262144
ComponentId      : INSECURE_NPCAP
Description      : @oem19.inf,%npf_desc_standard%;Npcap Packet Driver (NPCAP)
InfPath          : oem19.inf
InfSection       : FilterStandard
LocDescription   : @oem19.inf,%npf_desc_standard%;Npcap Packet Driver (NPCAP)
                   6e974-e325-11ce-bfc1-08002be10318}\{7DAF2AC8-E9F6-4765-A842-F1F5D2501341}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {226, 7, 9, 0...}
Characteristics  : 262144
ComponentId      : INSECURE_NPCAP_WIFI
Description      : @oem19.inf,%npf_desc_wifi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
InfPath          : oem19.inf
InfSection       : FilterWiFi
LocDescription   : @oem19.inf,%npf_desc_wifi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
                   6e974-e325-11ce-bfc1-08002be10318}\{7DAF2AC8-E9F6-4765-A842-F1F5D2501351}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_pacer
Description      : @%windir%\System32\drivers\pacer.sys,-101
InfPath          : netpacer.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\pacer.sys,-101
                   6e974-e325-11ce-bfc1-08002be10318}\{B5F4D659-7DAA-4565-8E41-BE220ED60542}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_wfplwf_upper
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6005
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_Upper_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6005
                   6e974-e325-11ce-bfc1-08002be10318}\{B70D6460-3635-4D42-B866-B8AB1A24454C}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {226, 7, 9, 0...}
Characteristics  : 262144
ComponentId      : ft_fortifilter
Description      : @oem70.inf,%ftndislwf_desc%;FortiClient NDIS 6.3 Packet Filter Driver
InfPath          : oem70.inf
InfSection       : Install
LocDescription   : @oem70.inf,%ftndislwf_desc%;FortiClient NDIS 6.3 Packet Filter Driver
                   6e974-e325-11ce-bfc1-08002be10318}\{E3D370D9-A102-49F6-AE59-6A5A71073632}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_nativewifip
Description      : @%windir%\System32\drivers\nwifi.sys,-101
InfPath          : netnwifi.inf
InfSection       : MS_NWIFI.Install
LocDescription   : @%windir%\System32\drivers\nwifi.sys,-101
                   6e974-e325-11ce-bfc1-08002be10318}\{E475CF9A-60CD-4439-A75F-0079CE0E18A1}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_wfplwf_vswitch
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6004
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_vSwitch_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6004
                   6e974-e325-11ce-bfc1-08002be10318}\{E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_vfpext
Description      : Microsoft Azure VFP Switch Extension
InfPath          : vfpext.inf
InfSection       : Install
LocDescription   : Microsoft Azure VFP Switch Extension
                   6e974-e325-11ce-bfc1-08002be10318}\{E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262200
ComponentId      : ms_ndiscap
Description      : @%windir%\System32\drivers\ndiscap.sys,-5000
InfPath          : ndiscap.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\ndiscap.sys,-5000
                   6e974-e325-11ce-bfc1-08002be10318}\{EA24CD6C-D17A-4348-9190-09F0D5BE83DD}
                   6e974-e325-11ce-bfc1-08002be10318}

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_l2bridge
Description      : @%SystemRoot%\System32\drivers\l2bridge.sys,-5000
InfPath          : l2bridge.inf
InfSection       : Install
LocDescription   : @%SystemRoot%\System32\drivers\l2bridge.sys,-5000
                   6e974-e325-11ce-bfc1-08002be10318}\{F15DC512-1E94-4CDB-9B42-27A953C64E67}
                   6e974-e325-11ce-bfc1-08002be10318}

*************************************************
File Info:
*************************************************

    Directory: C:\Program Files\Npcap

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        9/12/2018  10:52 AM           1904 DiagReport-20180912-105205.txt                                        
-a----       11/29/2016   3:43 PM           1034 DiagReport.bat                                                        
-a----        2/22/2018   9:25 PM           8908 DiagReport.ps1                                                        
-a----         7/5/2018   9:25 AM           2957 FixInstall.bat                                                        
-a----        9/12/2018  10:48 AM          67114 install.log                                                           
-a----        6/18/2018   9:31 AM           9919 LICENSE                                                               
-a----        9/12/2018  10:48 AM              1 loopback.ini                                                          
-a----         7/5/2018   8:42 PM          10846 npcap.cat                                                             
-a----         7/5/2018   8:42 PM           8657 npcap.inf                                                             
-a----         7/5/2018   8:42 PM          82824 npcap.sys                                                             
-a----         7/5/2018   3:11 PM           2404 npcap_wfp.inf                                                         
-a----         7/5/2018   3:13 PM         271160 NPFInstall.exe                                                        
-a----        9/12/2018  10:48 AM         246464 NPFInstall.log                                                        
-a----         7/5/2018   8:42 PM         176776 Uninstall.exe                                                         

    Directory: C:\WINDOWS\System32

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        2/28/2013   6:49 PM         107768 Packet.dll                                                            
-a----        2/28/2013   6:49 PM         370424 wpcap.dll                                                             

    Directory: C:\WINDOWS\System32\Npcap

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----         7/5/2018   3:13 PM         116536 NpcapHelper.exe                                                       
-a----         7/5/2018   3:13 PM         190776 Packet.dll                                                            
-a----         7/5/2018   3:13 PM          74552 WlanHelper.exe                                                        
-a----         7/5/2018   3:13 PM         376120 wpcap.dll                                                             

    Directory: C:\WINDOWS\SysWOW64\Npcap

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----         7/5/2018   3:13 PM         102712 NpcapHelper.exe                                                       
-a----         7/5/2018   3:13 PM         165176 Packet.dll                                                            
-a----         7/5/2018   3:13 PM          64312 WlanHelper.exe                                                        
-a----         7/5/2018   3:13 PM         331064 wpcap.dll                                                             

*************************************************
WinPcap Info:
*************************************************
HKLM:\SOFTWARE\WOW6432Node\WinPcap:
Get-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\WOW6432Node\WinPcap' because it does not exist.
At C:\Program Files\Npcap\DiagReport.ps1:170 char:6
+     (Get-ItemProperty HKLM:\SOFTWARE\WOW6432Node\WinPcap | out-string ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\WOW6432Node\WinPcap:String) [Get-ItemProperty], ItemNotF 
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 

*************************************************
Registry Info:
*************************************************
HKLM:\SOFTWARE\WOW6432Node\Npcap:

AdminOnly         : 0
WinPcapCompatible : 0
(default)         : C:\Program Files\Npcap
LoopbackAdapter   : \Device\{C4AE6762-21C8-47F5-87B6-F0EA4A250A17}

HKLM:\SYSTEM\CurrentControlSet\Services\npcap:

Type         : 1
Start        : 2
ErrorControl : 1
Tag          : 76
ImagePath    : \SystemRoot\system32\DRIVERS\npcap.sys
DisplayName  : @oem19.inf,%NPF_Desc_Standard%;Npcap Packet Driver (NPCAP)
Group        : NDIS
Description  : @oem19.inf,%NPF_Desc_Standard%;Npcap Packet Driver (NPCAP)

HKLM:\SYSTEM\CurrentControlSet\Services\npcap\Parameters:

NdisImPlatformBindingOptions : 0
LoopbackSupport              : 1
DltNull                      : 1
AdminOnly                    : 0
Dot11Support                 : 1
VlanSupport                  : 1
WinPcapCompatible            : 0
Dot11Adapters                : \Device\{00dec2fe-d055-4013-972c-69a8372d1261}
LoopbackAdapter              : \Device\{C4AE6762-21C8-47F5-87B6-F0EA4A250A17}
                               \npcap\Parameters
                               \npcap

HKLM:\SYSTEM\CurrentControlSet\Services\npcap_wifi:

Type         : 1
Start        : 4
ErrorControl : 1
Tag          : 77
ImagePath    : \SystemRoot\system32\DRIVERS\npcap.sys
DisplayName  : @oem19.inf,%NPF_Desc_WiFi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
Group        : NDIS
Description  : @oem19.inf,%NPF_Desc_WiFi%;Npcap Packet Driver (NPCAP) (Wi-Fi)

HKLM:\SYSTEM\CurrentControlSet\Services\npcap_wifi\Parameters:

NdisImPlatformBindingOptions : 0
                               \npcap_wifi\Parameters
                               \npcap_wifi

HKLM:\SYSTEM\CurrentControlSet\Services\npf:
Get-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Services\npf' because it does not exist.
At C:\Program Files\Npcap\DiagReport.ps1:201 char:2
+ (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf | out-s ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...et\Services\npf:String) [Get-ItemProperty], ItemNotFo 
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
HKLM:\SYSTEM\CurrentControlSet\Services\npf\Parameters:
Get-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Services\npf\Parameters' because it does not exist.
At C:\Program Files\Npcap\DiagReport.ps1:203 char:2
+ (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf\Paramet ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...\npf\Parameters:String) [Get-ItemProperty], ItemNotFo 
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi:
Get-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi' because it does not exist.
At C:\Program Files\Npcap\DiagReport.ps1:205 char:2
+ (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi |  ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...rvices\npf_wifi:String) [Get-ItemProperty], ItemNotFo 
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi\Parameters:
Get-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi\Parameters' because it does not 
exist.
At C:\Program Files\Npcap\DiagReport.ps1:207 char:2
+ (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi\Pa ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...wifi\Parameters:String) [Get-ItemProperty], ItemNotFo 
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 

*************************************************
Service Info:
*************************************************

Status      : Stopped
Name        : npcap
DisplayName : Npcap Packet Driver (NPCAP)

Get-Service : Cannot find any service with service name 'npf'.
At C:\Program Files\Npcap\DiagReport.ps1:217 char:1
+ Get-Service npf
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npf:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 

*************************************************
Install Info:
*************************************************
Please refer to: C:\Program Files\Npcap\install.log

**Comment by dmiller-nmap** [comment]
Your output indicates that the `npcap` service is stopped. In an administrator command prompt, run `net start npcap` and let us know any output or if this fixes the problem. Nmap is supposed to try to do this itself, but it may fail if Nmap is not run by a user with Administrator rights.

**Comment by dmiller-nmap** [comment]
Closing due to no further updates.
