### ISSUE TITLE
(npcap) > compatibility issue

### ISSUE THREAD

**Issue by Yuri-01** [nmap/nmap#1337]
Npcap is not compatible with "WinDump.exe".

After run "windump" i get window with the following message: "Entry point in procedure getservenv not found in wpcap.dll".

Detailed info:
OS:
1. w2k8r2 / 64 bit / RU_ru
2. Windows 7 Prof with SP1 / 64 bit / RU_ru

Rights/perms.:
Run "windump.exe" with elevation rights

Ver.:
Npcap: Latest
WinDump: Latest

Install_mode:
With and without compatible with winpcap.

**Comment by fyodor** [comment]
Just as a quick data point, I downloaded WinDump.exe from https://www.winpcap.org/windump/install/default.htm.  It worked with WinPcap 4.1.3 and then I uninstalled that and tried with Npcap 0.99-r7 with WinPcap mode enabled of course and got the error message about getservent not located.  Note that it is getservent rather than getservenv (that was probably a typo).

**Comment by fyodor** [comment]
Here's the error screenshot:
![windump](https://user-images.githubusercontent.com/2155933/46306440-2652d200-c569-11e8-801b-bdddf130f885.png)

**Comment by Yuri-01** [comment]
Hi, Fyodor.
Yes, i am wrong. True - getservent

**Comment by dmiller-nmap** [comment]
This is an incompatibility between WinPcap and Npcap. Thank you for pointing it out! I will be adding documentation of this and a few other missing functions to the Npcap Developer's Guide.

As a separate effort, I am working on submitting some changes to [tcpdump](https://github.com/the-tcpdump-group/tcpdump/) to allow it to work natively with Npcap. As it currently stands, it can be built using CMake (set the environment variable `CMAKE_PREFIX_PATH=".\path\to\npcap-sdk"`) and will work with Npcap in WinPcap API-compatible mode.

**Comment by Yuri-01** [comment]
Hi, Daniel and thank you for your work.

**Comment by kasumiru** [comment]
same issue. last version pcap - "npcap-0.9987.exe" from nmap is NOT compatibility with WinDump.exe and crushed, same error. Use only "WinPcap release was 4.1.3"
