### ISSUE TITLE
Confusion between java-rmi and rmiregistry

### ISSUE THREAD

**Issue by BastienFaure** [nmap/nmap#1342]
I think there is a confusion about RMI services naming. Let's take an example (I used a freshly cloned and compiled version of nmap (`Nmap 7.70SVN ( https://nmap.org ) at 2018-10-05 11:41 CEST`):

```
./nmap -p9000-9001 -sC -sV vulns.local
[...]
PORT     STATE SERVICE     VERSION
9000/tcp open  rmiregistry Java RMI
9001/tcp open  java-rmi    Java RMI Registry
| rmi-dumpregistry:
|   jmxrmi
|     javax.management.remote.rmi.RMIServerImpl_Stub
|     @172.16.1.103:9000
|     extends
|       java.rmi.server.RemoteStub
|       extends
|_        java.rmi.server.RemoteObject
```
Port 9001 is a port that I configured as the registry, which is the place where remote users can find stubs to retrieve. Here my registry only contains one stub at port 9000.

So basically, may the service names be reversed ? For me the `rmiregistry` should be at port 9001, not the opposite. Also, the `rmi-dumpregistry` script was run on `java-rmi`, which comfort my position :D

Do you agree with that ?

Thanks !

PS: Also sent an email to dev@nmap.org, dunno which way is preferred for reporting bugs.

**Comment by BastienFaure** [comment]
Hi, attached is the nmap output as XML. Strange, this time both were detected as rmiregistry...

**Comment by BastienFaure** [comment]
Strange, this time both services are detected as rmiregistry...
[rmi.zip](https://github.com/nmap/nmap/files/2459541/rmi.zip)

**Comment by dmiller-nmap** [comment]
Aha! It seems `rmi-dumpregistry.nse` is forcing the `java-rmi` service name if it succeeds. That's where one of the errors is. The other error, if there is one, may be in labeling the `java-rmi` service as `rmiregistry`. Unfortunately, I was wrong in saying that the XML would have the line number of the match; we do that for `<osmatch>` elements, not for services. I will need the regular screen (or `-oN`) output with `--version-trace` to get that info. At minimum, I need the lines that start with "Service scan".

**Comment by BastienFaure** [comment]
Hi @dmiller-nmap, no worries, please find attached the `-oN` output.

[rmi.zip](https://github.com/nmap/nmap/files/2461958/rmi.zip)

**Comment by BastienFaure** [comment]
Hmm I don't fully agree with you. If the NSE script rmi-dumpregistry succeeds, you should definitely let set the service name to `rmiregistry`, since it is exposing a registry through the RMI endpoint.
But I agree with you that both ports, exposing either a registry of an object stub are relying on the same protocol, which is called JRMP for me (https://en.wikipedia.org/wiki/Java_Remote_Method_Protocol)

What do you think ?

**Comment by BastienFaure** [comment]
Ok I think I understood how nmap translates information to users. With latest version I got this:
```
PORT     STATE SERVICE  VERSION
9000/tcp open  java-rmi Java RMI
9001/tcp open  java-rmi Java RMI
| rmi-dumpregistry: 
|   jmxrmi
|     javax.management.remote.rmi.RMIServerImpl_Stub
|     @172.16.1.103:9000
|     extends
|       java.rmi.server.RemoteStub
|       extends
|_        java.rmi.server.RemoteObject
```

But I am expecting (don't know if my opinion is shared, but anyway):
```
PORT     STATE SERVICE  VERSION
9000/tcp open  jrmp     Java RMI
9001/tcp open  jrmp     RMI Registry
| rmi-dumpregistry: 
|   jmxrmi
|     javax.management.remote.rmi.RMIServerImpl_Stub
|     @172.16.1.103:9000
|     extends
|       java.rmi.server.RemoteStub
|       extends
|_        java.rmi.server.RemoteObject
```
Also, I think I can work on a pull request to detect that port 9000 is actually a JMX stub (probably with adding a specific match line).
