### ISSUE TITLE
Nmap telnet brute force error

### ISSUE THREAD

**Issue by hkaraoglu** [nmap/nmap#1345]
**Input:**
`nmap -p23 -script telnet-brute.nse -script-args userdb=user.txt,passdb=password.txt {{MY_IP_ADDRESS}}`

**Output:**
`Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-08 09:54 `
`Assertion failed: lua_status(L) == LUA_YIELD, file ..\nse_nsock.cc, line 612`

**Comment by nnposter** [comment]
There has been a recent bug fix related to concurrency and Nmap sockets (#1233). Can you try to reproduce the issue by swapping library `nselib/brute.lua`with [the current version](https://github.com/nmap/nmap/blob/master/nselib/brute.lua)?

In the meantime you might be able to work around it by dropping the thread count to 1:
```
nmap ... --script-args brute.threads=1,brute.start=1 ...
```

**Comment by safebaseline** [comment]
done

**Comment by nnposter** [comment]
No follow-up activity. Issue presumably resolved
