### ISSUE TITLE
Nmap exclude 

### ISSUE THREAD

**Issue by 97zgxgw** [nmap/nmap#1347]
Hello,
nmap -sL -n 85.140.96.0/20 --exclude 85.140.104.0/21,85.140.96.0/21 
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-09 15:31 
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.00 seconds

Why this warning ?

**Comment by 97zgxgw** [comment]
Resolved with IP calc

**Comment by dmiller-nmap** [comment]
`85.140.104.0/21` is the range from `85.140.104.0` to `85.140.111.255`

`85.140.96.0/21` is the range from `85.140.96.0` to `85.140.103.255`

Together, they represent the contiguous range `85.140.96.0` to `85.140.111.255`, which is equivalent to the range `85.140.96.0/20`, which is your input range. Another way to look at it is that every network with a netmask length *N* contains exactly 2 non-overlapping networks with netmask length *N+1*. If you have specified 2 exclusions with netmask length 21 that do not overlap each other but that each overlap the target network with netmask 20, then there are no addresses in the 20 network that are not part of the two 21 networks.
