### ISSUE TITLE
Update Npcap so that it can be installed alongside Winpcap and applications can be made to choose which one they use

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#135]
Right now, our npcap installer basically thinks it is the Nmap Winpcap installer and so it will uninstall an existing winpcap if encountered.  I think in normal (non-silent mode) it asks the user first. We should instead update npcap so that it can install alongside an existing Winpcap.  This means we need to use a different driver name than npf.exe, for example, and do the install in a different directory path.  We need to have a good way in mind for applications to be able to select which they use, if desired.  Because for Nmap we would desire this.

**Comment by hsluoyz** [comment]
https://github.com/nmap/npcap/commit/836fa81a88b78f4495b45c17acdb81ce164b855d
https://github.com/nmap/npcap/commit/c67abf6f8b62bda89cd98c5ecc582566323f4c91
Above two commits solve the issue to have NPcap installed alongside WinPcap.

**Comment by hsluoyz** [comment]
I figured out a way for Nmap to choose between WinPcap and NPcap, at the same time we don't need to rename wpcap.dll to npcap.dll.

That is: 
Nmap call SetDllDirectory("C:\\Windows\\system32\\NPcap") before DLL loading (nmap uses DLL delay loading, so we have much time to make the call). Then path "C:\\Windows\\system32\\NPcap" will be searched earlier by Windows than system32 path, according to https://msdn.microsoft.com/en-us/library/ms686203.aspx

**Comment by hsluoyz** [comment]
Nmap code is modified to use NPcap first, details as below:
http://seclists.org/nmap-dev/2015/q2/258

**Comment by hsluoyz** [comment]
Finished using macros to define driver type. See below:
https://svn.nmap.org/nmap-exp/yang/nmap-npcap/mswin32/winfix.cc

**Comment by grossmj** [comment]
The NPCAP installer still asks for Winpcap to be uninstalled. Is this correct?

**Comment by hsluoyz** [comment]
@grossmj , 

Not true. If you have already installed WinPcap, Npcap installer will still allow you to install it in ``Non-WinPcap Compatible Mode`` in the Options page. Only after uninstalling WinPcap, you can choose to install Npcap in ``WinPcap Compatible Mode`` or ``Non-WinPcap Compatible Mode``.

**Comment by grossmj** [comment]
@hsluoyz 

Got it, I previously misread the message.
