### ISSUE TITLE
Java RMI service not detected on IPv6 addresses

### ISSUE THREAD

**Issue by bonewolves** [nmap/nmap#1352]
The current regex in nmap-service-probes for rmiregistry/Java RMI does not consider IPv6 addresses in the response and thus does not recognize the service on IPv6 addresses.

The fix is to change regex to match both IPv4 and IPv6 addresses in the response:

match rmiregistry m|^\x4e..[0-9a\:A-Fa-f.]+\0\0..$|s p/Java RMI/

**Comment by bonewolves** [comment]
Before the change:
PORT      STATE SERVICE   VERSION
10023/tcp open  cefd-vmp?
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port<redacted>-TCP:V=7.70%I=7%D=10/11%Time=5BBF891F%P=x86_64-apple-darwin17.
SF:3.0%r(JavaRMI,2D,"N\0&<redacted>\0\0\xee\x9
SF:5");

After the change:
PORT      STATE SERVICE     VERSION
<redacted>/tcp open  rmiregistry Java RMI

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! The change was already made in the development branch a few days ago: 53f5f5652e755d99aa5ee64a7e80b2045c528b2c
