### ISSUE TITLE
PPCLE64 Architecture Support

### ISSUE THREAD

**Issue by cwillhelm** [nmap/nmap#1357]
I was just curious if there are plans to support the ppcle64 architecture? With the advancement of OpenPOWER as well as the falling cost of Power9, I think everyone's favourite scanning tool should be available on all "major" platforms. Many Linux distributions support this platform, and it would be nice to see more software adopt a multi-architecture support model.

**Comment by dmiller-nmap** [comment]
Thanks for your interest! We don't have any plans regarding any specific architectures. Have you tried to build for ppcle64? What issues do you encounter? We are willing to address specific issues to improve support, but there's not a lot we can do based on the information here.

**Comment by dmiller-nmap** [comment]
I feel that I must point out: there is no "x86 version" of Nmap. The source builds successfully on many different architectures, as evidenced by the long list of arch-specific packages of Nmap from Debian: https://packages.debian.org/sid/nmap#pdownload

If you do get Nmap to build, be sure to run `make check` to do some basic testing for runtime bugs.

**Comment by dmiller-nmap** [comment]
We do not have plans for additional architecture support at the moment. Future versions of Nmap on Windows may target x64 or ARM64 separately, but we will continue publishing Nmap as x86 code at least until Microsoft no longer supports any 32-bit version of Windows.
