### ISSUE TITLE
Feature Request: Reverse Portscan

### ISSUE THREAD

**Issue by Script-Nomad** [nmap/nmap#1360]
I ran into a scenario where I was being severely throttled by an IPS during a penetration test and needed a way to spread my nmap scans over a series of hosts, scanning one port at a time before cycling the hosts again and iterating to the next port.

Ordinarily, I would have suspected this to be implemented already but was surprised it wasn't there. I ended up making a wrapper script to execute nmap from bash and stepped over the port numbers as I scanned a list of IP addresses.

```
#!/bin/bash

hostlist=$1
portbegin=$2
portend=$3

for ((i=${2}; i<=${3}; i++))
do
   nmap -iL $1 -p$i -sS -sV -v -F -oA port-results-p$i
done
```

What would be extremely awesome is if we could utilize a flag to enforce this behavior natively. Something like calling `--spray` or `--reverse-portscan` or `--cycle-hosts`. Whatever you guys think would be fitting. 

This technique is extremely useful for dodging an IPS without being throttled, but also without sacrificing scan speed using the `-T#` timing flags.

**Comment by True-Demon** [comment]
Sorry for being late responding to this. I didn't realize nmap had this behavior under the hood, so thanks for the insight. I admit I'm not nearly comfortable enough with C to dig into it on that level, so I shouldn't be surprised there were hidden gems like that already built in. Thanks for the extra resources as well. 

The -F may have been a typo on my part. I think I was using -f to make use of fragmentation at the time, but I can't remember anymore. ¯\_(ツ)_/¯  

Thanks for being so helpful and taking the time to educate me. :+1:
