### ISSUE TITLE
Remove Nmap Concurrency Mutexes Put in to Prevent WinPcap Bug

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#137]
Rapid7 identified an problem a few months ago which related to running numerous instances of Nmap concurrently.  We weren't able to reproduce it, but with debugging info from R7, we were able to create a workaround patch which involved using mutexes to ensure that certain calls such as PacketOpenAdapter and PacketCloseAdapter don't happen concurrently even if multiple Nmaps are running.  We should ask R7 if they can test whether they can reproduce the problem with Npcap and--if so--we should try to find a better solution which fixes the underlying problem instead of the mutex workaround.

**Comment by fyodor** [comment]
It has been more than five years and I don't think many people use WinPcap with new versions of Nmap any more.  So I think we can take out these concurrency controls if we haven't done so yet.  And if we already have, we can just close this issue :)

**Comment by dmiller-nmap** [comment]
This was removed in 30db7097555ca383ce496f0808a071bf0cd9ce70 (r37445, Oct 2018, released as part of Nmap 7.80).
