### ISSUE TITLE
Segmentation fault on Fedora 28

### ISSUE THREAD

**Issue by ionreflex** [nmap/nmap#1370]
Hi all,
Repeating myself, don't know much about programming but been using nmap freshly compiled from source; was working fine but lately I get SEGFAULT on Fedora 28 :

```
20181025@1101:~$ uname -a
Linux antares 4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
20181025@1101:~$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
20181025@1102:~$
```

Ncat and Nping are working just fine.

See attached files for relevant info, lemme know if I forget to include anything or how I can help!

TY,

Ion

[compile.log](https://github.com/nmap/nmap/files/2515530/compile.log)
[dnflist.txt](https://github.com/nmap/nmap/files/2515537/dnflist.txt)
[strace.log](https://github.com/nmap/nmap/files/2515538/strace.log)

**Comment by dmiller-nmap** [comment]
Thanks for this report. Does this issue still happen for you with the current version of Nmap? If so, please provide a backtrace of the crash by running `LD_PRELOAD=/usr/lib/libSegFault.so nmap --version` so we can determine what is going wrong.

**Comment by fyodor** [comment]
Closing since it's more than 4 years old and the reporter isn't responsive any more.
