### ISSUE TITLE
Release Nmap as a 64-bit build on macOS

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#1371]
https://developer.apple.com/news/?id=04112018a

Nmap macOS installer is currently 32-bit.

**Comment by rhymeswithmogul** [comment]
It's not just the installer. I ran nmap 7.70 from the command-line, and I received a warning saying nmap needed to be updated.

`$ file `which nmap`
/usr/local/bin/nmap: Mach-O executable i386`

**Comment by ipv6freely** [comment]
Just to add to this - nmap won't run at all in macOS 10.15. 
`-bash: /usr/local/bin/nmap: Bad CPU type in executable`

**Comment by codyc1515** [comment]
Can confirm this is an issue with the build in macOS 10.15.

**Comment by Tukan3** [comment]
Please update the binary to 64 bits.

**Comment by dmiller-nmap** [comment]
I forgot to put it in the changelog, but I believe Nmap 7.80 was built for x86_64. Can someone on this thread confirm whether the new installer works? https://nmap.org/download.html#macosx

**Comment by vdeniet** [comment]
Hi, it doesn't work for macOS 10.15. New installs should be Notarised (verified/ signed) by Apple:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/41434158/63427471-781c7900-c415-11e9-9c7a-5a87aa58a70a.png">

**Comment by dmiller-nmap** [comment]
@vdeniet Thanks for checking. We are looking into Apple developer verification and tracking that as #94. If you are willing or able to change your preferences to allow installing unsigned packages, we would still like confirmation that this build executes on x64 macOS.

**Comment by ipv6freely** [comment]
Hi, just confirmed it works fine on macOS 10.15. Thank you for updating it!

**Comment by newacct** [comment]
I can verify that nmap 7.80 shows as a 64-bit app on my macOS 10.14.

To install it on my macOS 10.14, after the alert that says it can't be opened, I had to go to System Preferences -> Security & Privacy -> General, and click the "Open Anyway" button, to be given the choice to open it. I am not sure if it is similar on macOS 10.15.

**Comment by vdeniet** [comment]
> Hi, just confirmed it installs and executes fine on macOS 10.15. Thank you for updating it!

For me it also works now on 10.15

**Comment by dmiller-nmap** [comment]
Great, thanks! I agree that code signing is an important step in macOS support, so we will definitely try to get that going. In the meantime, I'm closing this issue as resolved. Thanks!
