### ISSUE TITLE
stderr not piped in netcat

### ISSUE THREAD

**Issue by illera88** [nmap/nmap#1373]
Testing:
Listen with:
ncat.exe -lvp 4444 --ssl

Connect with:
ncat.exe 127.0.0.1 4444 -e cmd.exe --ssl -v.

when you get a shell run some non existent command (i.e. nonononono) and you won't get the typical:
```
'nonononono' is not recognized as an internal or external command,
operable program or batch file.
```
Actually you will see that in the client console.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is a common behavior of netcat implementations on all platforms; TCP only provides for a single output stream, so only standard output is directed to the network socket. If the user wants to combine multiple output streams (Powershell has 5 streams, for instance), it is up to them to use `--sh-exec` and shell redirection or other means to get all output into a single stream for Ncat to handle.
