### ISSUE TITLE
Npcap windows is always Blue Screen of Death

### ISSUE THREAD

**Issue by BeiJingHaiDian12** [nmap/nmap#1375]
Hello,
I install npcap-0.81, To capture database flows，but my computer always happen Blue Screen Death.
Doctor, if this problem is solved, can you tell me which version I solved, because I'm going to write a report to the client and update it?
my Installation configuration is as follows(3 configurations were selected) :
1、Automatically start the driver at boot time
2、support loopback traffic("npcap loopback adapter" will be created)

Windows server Error Message ：
probably caused by：npcap.sys(npcap+76ab)

phone：13323815576
weixin：13323815576
QQ:457893370

**Comment by BeiJingHaiDian12** [comment]
Sorry, I'm wrong. I've chosen two configurations, not three. Would you please tell me the **Specific version** to solve this problem?    Specific version，It's hard for you！

**Comment by BeiJingHaiDian12** [comment]
1、if I Select three configurations , A blue screen happened in 2~4 hours，configuration is as follows：
     (1) Automatically start the driver at boot time
     (2) support loopback traffic("npcap loopback adapter" will be created)
     (3) Install Npcap in WinPcap API-compatible Mode
2、if I Select two configurations , A blue screen happened in 20~30 hours，configuration is as follows：
     (1) Automatically start the driver at boot time
     (2) support loopback traffic("npcap loopback adapter" will be created)

**Comment by BeiJingHaiDian12** [comment]
1、if I Select three configurations , A blue screen happened in 2-4 hours，configuration is as follows：
(1) Automatically start the driver at boot time
(2) support loopback traffic("npcap loopback adapter" will be created)
(3) Install Npcap in WinPcap API-compatible Mode
2、if I Select two configurations , A blue screen happened in 20-30 hours，configuration is as follows：
(1) Automatically start the driver at boot time
(2) support loopback traffic("npcap loopback adapter" will be created)

**Comment by gvanem** [comment]
Have you tried [WinPcap](https://www.winpcap.org/install/)? Rock solid. Simply forget about the half-finished NPcap software.

**Comment by dmiller-nmap** [comment]
@BeiJingHaiDian12 There have been many crashes fixed since Npcap 0.81. The only way we can know which one of these you are experiencing is to get the crash dump from `C:\Windows\Minidump\` and compare crash location to known fixes. Since every release fixes issues found in preceding releases, I cannot recommend any version other than the latest, which at the time of this writing is Npcap 0.99-r7.

@gvanem Npcap is far from half-finished. We have had no user-reported blue screen crashes since Npcap 0.90 in May 2017, but we have been active in fixing all crashes reported via Microsoft driver analytics (crash telemetry). There are many additional reasons besides stability that users prefer Npcap: updated libpcap API, loopback traffic capture and injection, commercial support, etc.

**Comment by BeiJingHaiDian12** [comment]
[102518-45006-01.zip](https://github.com/nmap/nmap/files/2528413/102518-45006-01.zip)
[103018-18171-01.zip](https://github.com/nmap/nmap/files/2528414/103018-18171-01.zip)

Hello Doctor @dmiller-nmap
The above two compressed packages are blue screen crash dump files. Would you please tell me the  Specific version to solve this problem? 

if I Select three configurations , crate crash dump files 102518-45006-01.zip，configuration is as follows：
(1) Automatically start the driver at boot time
(2) support loopback traffic("npcap loopback adapter" will be created)
(3) Install Npcap in WinPcap API-compatible Mode 

if I Select two configurations , crate crash dump files 103018-18171-01.zip，configuration is as follows：
(1) Automatically start the driver at boot time
(2) support loopback traffic("npcap loopback adapter" will be created)

I hope you will inform us of the version number of these two questions separately.  
Thank you very much

**Comment by BeiJingHaiDian12** [comment]
Can you briefly describe the reasons for the above two blue screens, because we need to write problem reports to our customers.

**Comment by BeiJingHaiDian12** [comment]
@dmiller-nmap  
Would you please give me some time to reply  
                                                     Thank you

**Comment by BeiJingHaiDian12** [comment]
how much

**Comment by BeiJingHaiDian12** [comment]
@fyodor  how much one month
