### ISSUE TITLE
[Npcap] SetInterface error 50

### ISSUE THREAD

**Issue by Vastrix** [nmap/nmap#1382]
Greetings

    | Version
------------ | -------------
OS | Windows 10 x64
Npcap | 0.99-r7
Adapter | Killer Wireless-n/a/ac 1535 Wireless Network Adapter

I'm trying to set my adapter in monitor mode, wireshark isn't showing the checkbox so I tried `Wlanhelper.exe` which gives `Error: SetWlanOperationMode::SetInterface error, error code = 50 (The request is not supported)`, Using the *interactive* mode I got a similar result..

I checked the [supported adapters](https://secwiki.org/w/Npcap/WiFi_adapters) list but I'm guessing it's outdated..? :s  
  

[**Diagreport**](https://puu.sh/BWJ3E/0761d86f75.txt)

**Comment by dmiller-nmap** [comment]
Thanks for the report. The Killer 1535 uses a Qualcomm Atheros QCNFA364AH chipset, which we do not have listed in our supported adapters page. This does not mean it is not supported, only that we have not received any information from users with this card. We can update the page with your findings if you are able to provide some information:

1. Ensure you have the latest driver version: https://www.killernetworking.com/killersupport/driver-downloads/category/other-downloads
2. Perform [the tests on the supported adapters page](https://secwiki.org/w/Npcap/WiFi_adapters#How_to_help) and report here.

Thanks!

**Comment by Vastrix** [comment]
I updated and No monitor mode checkbox, also, I'm positive Winpcap was uninstalled and npcap installed  (as I believe the diagreport points out)  
  
**I also reached out to Killer and they had this to say on the matter..**  
![Solid Nope](https://puu.sh/C5z5O/d8aafefb21.png)  
  
I don't really feel like creating a secwiki account just for this though.. so if someone else could.. You have my blessing :)

**Comment by fyodor** [comment]
Thanks @Vastrix.  I added the card to https://secwiki.org/w/Npcap/WiFi_adapters, but I'm not sure about the following:

* Firmware/Driver version
* Capture Works
* FCS
* Channel/Frequency
* RSSI

If you know the answers to any of these (there is a glossary on the page), let me know and I'll further update the Killer Wireless entry.  It's a bummer that they apparently have no interest in supporting Monitor Mode!

**Comment by Vastrix** [comment]
@fyodor 
**Driver version**: 12.0.0.448  
**Notes**: No killer adapter is or will ever support monitor mode
All the other information has Monitor mode as a dependency it seems (according to previous entry and the help section)  
  
And yeah indeed, major bummer :/

**Comment by fyodor** [comment]
Thanks @Vastrix , I've updated the page.  Hopefully it will help people buy good adapters.

**Comment by Vastrix** [comment]
Indeed!
Thanks! :)

**Comment by vcidst** [comment]
Hello,
I had got the same error and checked for my hardware adapter. Turns out it does not support monitor mode either. I don't have an account on your wiki so pasting the information here,

Adaptor: Intel Dual Band Wireless-AC 7265
Driver Version: 19.51.14.1
Monitor Mode: No

Source: [intel forums](https://forums.intel.com/s/question/0D50P0000490RQySAM/intel-dual-band-wirelessac-7265?language=en_US)

**Comment by fyodor** [comment]
Thanks @vcidst .  I've added the entry to https://secwiki.org/w/Npcap/WiFi_adapters, but can you tell me what Windows version and Npcap version you tested with?  Then I'll add that information as well.

**Comment by vcidst** [comment]
> 
> 
> Thanks @vcidst . I've added the entry to https://secwiki.org/w/Npcap/WiFi_adapters, but can you tell me what Windows version and Npcap version you tested with? Then I'll add that information as well.

Npcap Version: 0.99-r9
Microsoft Windows 10 Pro - Version 1803 (OS Build 17134.523)

**Comment by fyodor** [comment]
Thanks @vcidst  - added.

**Comment by felipepintomoraes** [comment]
Hi, 
 
I faced the same issue as @vcidst and my adaptor is not supported. I used: 
Intel Dual Band Wireless-AC 8265
Driver Version: 20.50.1.1
Monitor Mode: no
Npcap Version: 0.99-r9
Microsoft Windows 10 Pro - Version 1803 (OS Build 17134.523)

**Comment by fyodor** [comment]
Thanks @felipepintomoraes - I added that to the page.

**Comment by CRTX** [comment]
Just tried with an Intel 9260, no monitoring mode either :'(

**Comment by phelipebf** [comment]
Same issue here:

Killer Wi-Fi 6 AX1650i (201NGW)
Driver Version: 21.70.0.6
Monitor Mode: no
Npcap Version: 1.60
Microsoft Windows 11 Home - Version 21H2 (OS Build 22000.978)

**Comment by deividnn** [comment]
sme issue here:

Killer(R) Wireless-AC 1550i Wireless Network Adapter (9560NGW) 160MHz
Driver Version: 22.40.0.7
Monitor Mode: no
Npcap Version: 1.72
Microsoft Windows 10 Home - Version 10.0.19045
