### ISSUE TITLE
[Npcap]  Replace the original npcap.sys with my own compile npcap.sys, driver is  registered  failed 

### ISSUE THREAD

**Issue by BeiJingHaiDian12** [nmap/nmap#1384]
Now I can compile it correctly from npcap code，I can get npcap.sys，First I install Npcap use the binaries you provide，then I replace the c:/windows/system32/driver/npcap.sys and reboot computer，but npcap driver can not be registered，It`s will ok if I use your npcap.sys of package to replace again and reboot computer.
The computer that I installed npcap is windows 7 X64. The Platform I compiled is Window 10 vs2015 in Release、X64 options. I don't know why I failed. Is it related to my compilation options.? It is necessary to compile on windows7 to install on windows7 platform? I didn't change anything. I used the default.
can you give me some suggestion. Thank you very much.

**Comment by fyodor** [comment]
Closed because this sort of discussion/support request isn't really what we use the issue tracker for.  Please stop opening so many issues.
