### ISSUE TITLE
Npcap Loopback adapter didn't show

### ISSUE THREAD

**Issue by Claiyre** [nmap/nmap#1387]
- Winpcap has been uninstalled totally
- not check winpcap api-compat mode(Checking doesn't help)
- OS: win7 64
- installer: npcap-0.99-r7.exe
- wireshark version 2.6.4

Tried several times, still can't find Npcap Loopback adapter in wireshark interfaces or ipconfig list

By the way, Basic Filtering Engine (BFE) service is running.

**Comment by dmiller-nmap** [comment]
Can you please provide output of [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues)?

Does running 'C:\Program Files\Npcap\FixInstall.bat` fix the problem?

**Comment by tankilo** [comment]
Same on win10 1803   
![image](https://user-images.githubusercontent.com/10413284/49213693-cd37db00-f3ff-11e8-9ae8-ff1cadf304d1.png)
![image](https://user-images.githubusercontent.com/10413284/49213720-dd4fba80-f3ff-11e8-91c3-d6d7f78bb8e8.png)

**Comment by BobVul** [comment]
On 0.992 it works if I either select `Automatically start the Npcap driver at boot time` or manually `sc stop npcap` and then `sc start npcap` before launching Wireshark. Perhaps a race condition when Wireshark (?) starts it?

**Comment by dmiller-nmap** [comment]
The Npcap Loopback Adapter was known to cause problems with some software, so we removed the need for it in Npcap 0.9983, released today. Be sure to deselect (un-check) the "Legacy loopback support" to get the new loopback capture support. Let us know how it works for you.
