### ISSUE TITLE
PATH variable in User variables section was replaced by 'C:\Windows\Program Files (x86)\Nmap'

### ISSUE THREAD

**Issue by fungiboletus** [nmap/nmap#1396]
It's probably similar or related to the issue #404.

Using Nmap 7.70 [2018-03-19] on Windows 10.

**Comment by dmiller-nmap** [comment]
I'm sorry to hear that you had this problem with our installer. It does indeed sound similar to #404, so I'll check our version of NSIS. We're doing some investigation of alternative installers for Npcap, so we may end up using something different prior to the next Nmap release, but at minimum we will fix this for the next release.

**Comment by dmiller-nmap** [comment]
Thanks again for the report! This fix will ensure our installer cannot be built without using the Large Strings build of NSIS.

**Comment by pkExec** [comment]
Same thing happened to me today, fresh install nmap-7.70-setup.exe.

**Comment by dmiller-nmap** [comment]
@pkExec Yes, unfortunately we have not yet issued an Nmap release with the fix included. To avoid this issue with the Nmap 7.70 installer, you can run it from a CMD.EXE window with the `/REGISTERPATH=NO` option, or uncheck the "Register Nmap path" checkbox in the graphical installer.

**Comment by regs01** [comment]
Another happy user. Lost all my path. As a workaround i suggest to completely remove this from installation until fixed.
