### ISSUE TITLE
nmap dns-fuzzer - threw an error - dns-fuzz.nse:155: attempt to concatenate a table value

### ISSUE THREAD

**Issue by phil-c123** [nmap/nmap#1403]
Anyone have experience with nmap dns-fuzzer when extending the time and it complains about concatenating a table value?

issued 
nmap -d -p53 --script dns-fuzz --script-args timelimit=2s <a.b.c.d>

NSE: dns-fuzz against 10.6.1.99:53 threw an error!
/usr/bin/../share/nmap/scripts/dns-fuzz.nse:155: attempt to concatenate a table value
stack traceback:
/usr/bin/../share/nmap/scripts/dns-fuzz.nse:155: in function 'makePacket'
/usr/bin/../share/nmap/scripts/dns-fuzz.nse:328: in function </usr/bin/../share/nmap/scripts/dns-fuzz.nse:287>
(...tail calls...)

**Comment by nnposter** [comment]
Could you please confirm that you are using the latest version of the script, available [here](https://raw.githubusercontent.com/nmap/nmap/master/scripts/dns-fuzz.nse)?

**Comment by phil-c123** [comment]
Thanks for the reply and link.  Yes, have confirmed using same script version...

Running what I believe is latest nmap version "Nmap 7.01 ( https://nmap.org )"  on system running Ubuntu 16.04.2 LTS

**Comment by nnposter** [comment]
Actually the latest Nmap version is 7.70. Version 7.01 is three years old.
The reason I am inquiring about the script version is that the trace line numbers do not line up.

Please try to reproduce the issue in Nmap 7.70 and use the latest version of script from SVN/Github. (There were changes to the script since the 7.70 release.)

**Comment by phil-c123** [comment]
Creatred new VM with Ubuntu 16.0.4.2 LTS and re-installed nmap,  but its stating 7.01 is latest:

root@ubuntu16-10-64-3-196:~# apt-get upgrade nmap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nmap is already the newest version (7.01-2ubuntu2).
Calculating upgrade... Done

**Comment by nnposter** [comment]
Unfortunately this is not something that the Nmap community can control. Ubuntu generally assembles all their application packages when they put together a new release but only a selected subset of them is receiving feature updates throughout the release lifespan. In onther words, most of the applications get stuck on the original version.

If you have ability to spin up new VMs then the easiest way might be to grab a current Kali image and then update the script by hand.

**Comment by dmiller-nmap** [comment]
This was fixed in b5656da, and is available in Nmap 7.30 or later.

**Comment by phil-c123** [comment]
Thanks everyone,  

Yes,  had to get nmap-7.70-1.x86_64.rpm and install from there.  The dns-fuzz.nse does not look to be the latest up-to date from this,  so can obtain that from location that nnposter has pointed out.

/usr# nmap -version
Nmap version 7.70 ( https://nmap.org )

Looks to be working now....

/usr# nmap -d -sU -p 53 --script ./dns-fuzz --script-args timelimit=10s <host>
...
PORT   STATE SERVICE REASON
53/udp open  domain  script-set
|_dns-fuzz: The server seems impervious to our assault.
Final times for host: srtt: 317 rttvar: 5000  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 14:34
Completed NSE at 14:34, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 10.91 seconds
           Raw packets sent: 6 (232B) | Rcvd: 1 (28B)
