### ISSUE TITLE
Logic mistake in SMB.lua

### ISSUE THREAD

**Issue by bpdevries1** [nmap/nmap#1405]
It always picks the netbios domain and not the domain in  --script-args=smbdomain=<domain>

at line 1404 in smb.lua
if ( smb['domain'] or smb['server'] and ( not(domain) or #domain == 0 ) ) then

Should prolly be:

if ( (smb['domain'] or smb['server']) and ( not(domain) or #domain == 0 ) ) then

**Comment by nnposter** [comment]
This appears to be a duplicate of #1544. Fixed in 0855eb4c0c38b6e9a455a005faad7bf197315362.
