### ISSUE TITLE
http-useragent-tester should check for 403 Forbidden, not just redirects

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#141]
http-useragent-tester is supposed to check for allowed and forbidden user agents, but it only handles sites that redirect forbidden agents elsewhere. The site could just as easily return a 403 Forbidden status code. Maybe the script should report any differences in HTTP status code, only using the redirect check when the normal response is also a redirect.

**Comment by h4ck3rk3y** [comment]
Checks for redirection different from a browser user-agent, followed by a check for difference in response code. Shows the response code of browser user agent and all the ones where there was a change.
Also added XML output.
https://github.com/h4ck3rk3y/nmap-exp-gyani/blob/master/scripts/http-useragent-tester.nse
