### ISSUE TITLE
NSE SQL script ms-sql-info not reporting SP# correctly

### ISSUE THREAD

**Issue by NicholasLeader** [nmap/nmap#1411]
nmap x.x.x.x -p 1433 --script ms-sql-info  is returning the correct release 'number' but not the correct 'Service Pack level'. e.g. 'number: 11.00.7001.00' should correspond to 'Service pack level: SP4' (not SP3).

Reference:
https://www.microsoft.com/en-us/download/details.aspx?id=56040
https://sqlserverbuilds.blogspot.com/
https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20SQL%20Server%202012%20Service%20Pack

**Comment by nnposter** [comment]
Fixed in r37538. Thank you for contributing
