### ISSUE TITLE
Segmentation fault (core dumped) when creating xml output

### ISSUE THREAD

**Issue by cpandya2909** [nmap/nmap#1412]
Hi

When I scan an ip, I can see the output on terminal, but when I give -oX option to save it as xml, the nmap crashes.

**Comment by cpandya2909** [comment]
How can I share core dump file? 

My nmap command is  nmap -sV -Pn --version-all -T4 --open -sC 103.251.109.88 -p 80,443 -oX -

here is head of core dump file

ProblemType: Crash
Architecture: amd64
Date: Wed Dec 12 11:51:43 2018
DistroRelease: Ubuntu 16.04
ExecutablePath: /usr/bin/nmap
ExecutableTimestamp: 1459434173
ProcCmdline: nmap -sV -Pn --version-all -T4 --open -sC 103.251.109.88 -p 80,443 -oX -
ProcEnviron:
 SHELL=/bin/bash
 TERM=screen.xterm-256color
 PATH=(custom, no user)
 LANG=en_US.UTF-8

**Comment by gvanem** [comment]
Version **7.01** must be 3 years old. Time to upgrade.

**Comment by cpandya2909** [comment]
~$ sudo apt install nmap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nmap is already the newest version (7.01-2ubuntu2).

**Comment by nnposter** [comment]
Please see https://github.com/nmap/nmap/issues/1403#issuecomment-444672027 for an explanation what "newest" really means in Ubuntu.

**Comment by nnposter** [comment]
No follow-up activity. Issue presumably resolved
