### ISSUE TITLE
nmap: nsock_pool.c:227: nsp_delete: Assertion `nse->iod->events_pending >= 0' failed.

### ISSUE THREAD

**Issue by chpagy** [nmap/nmap#1414]
# nmap -sP 172.22.85.45

Starting Nmap 6.40 ( http://nmap.org ) at 2018-12-14 18:41 HKT
nmap: nsock_pool.c:227: nsp_delete: Assertion `nse->iod->events_pending >= 0' failed.
Aborted (core dumped)
You have new mail in /var/spool/mail/root

**Comment by dmiller-nmap** [comment]
Thanks for the bug report. Unfortunately, Nmap 6.40 is over 5 years old, and there have been 14 releases and many code changes since it was released. This bug has not been reported in any recent version, so we suggest you upgrade to [the latest version from nmap.org](https://nmap.org/download.html).

**Comment by landgraf** [comment]
@dmiller-nmap nmap-6.40 is still part of Centos/RHEL 7.X I think bug reporter uses one. 

@chpagy  please see downstream bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1577589

I'll fix in once prioritization allows....

**Comment by thorleifjaocbsen** [comment]
This is still a issue. Can reproduce. Removing ipv6 nameservers from /etc/resolv.conf fixes it. Centos7

**Comment by shuidaan** [comment]
This is still a issue. Can reproduce. Removing ipv6 nameservers from /etc/resolv.conf fixes it. Centos7

**Comment by shuidaan** [comment]
> This is still a issue. Can reproduce. Removing ipv6 nameservers from /etc/resolv.conf fixes it. Centos7

this is right

**Comment by landgraf** [comment]
> This is still a issue. Can reproduce. Removing ipv6 nameservers from /etc/resolv.conf fixes it. Centos7

time to use Centos8. This bug is not gonna be fixed in Centos7. See https://bugzilla.redhat.com/show_bug.cgi?id=1577589

**Comment by BenAveling** [comment]
For me, I can reproduce the problem by removing my default route, and 'fix' the problem by restoring a default route.
```
# nmap 192.168.0.204 -Pn

Starting Nmap 6.40 ( http://nmap.org ) at 2023-11-14 20:43 UTC
Nmap scan report for 192.168.0.204
Host is up (0.0013s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
22/tcp open  ssh
MAC Address: 08:00:27:51:68:E7 (Cadmus Computer Systems)

Nmap done: 1 IP address (1 host up) scanned in 21.54 seconds

# ip r del 0.0.0.0/0 dev enp0s8

# nmap 192.168.0.204 -Pn

Starting Nmap 6.40 ( http://nmap.org ) at 2023-11-14 20:44 UTC
nmap: nsock_pool.c:227: nsp_delete: Assertion `nse->iod->events_pending >= 0' failed.
Aborted

# ip r add 0.0.0.0/0 dev enp0s8

# nmap 192.168.0.204 -Pn

Starting Nmap 6.40 ( http://nmap.org ) at 2023-11-14 20:45 UTC
Nmap scan report for 192.168.0.204
Host is up (0.0012s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
22/tcp open  ssh
MAC Address: 08:00:27:51:68:E7 (Cadmus Computer Systems)

Nmap done: 1 IP address (1 host up) scanned in 18.33 seconds

# nmap --version

Nmap version 6.40 ( http://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.2.2 openssl-1.0.2k libpcre-8.32 libpcap-1.5.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
