### ISSUE TITLE
[Req MAC vendor update] Is it possible to update the MAC vendor list?

### ISSUE THREAD

**Issue by hjcoumans** [nmap/nmap#1427]
Dear developers,

Using Nmap 7.70 (with the Kali distro) I found MAC addresses that resolved to (Unknown) vendor, while Googling gave me a resolution.
Is it possible to have the list of MAC vendor's updated to the latest known?

To help you with a few that I got from my Nmap scan (the line is copied from hwaddress.com and (disclaimer) I'm not a stakeholder of this website):

54-BF-64 | 54-BF-64-00-00-00 - 54-BF-64-FF-FF-FF | Dell Inc.
94-B8-6D | 94-B8-6D-00-00-00 - 94-B8-6D-FF-FF-FF | Intel Corporate
74-9E-AF | 74-9E-AF-00-00-00 - 74-9E-AF-FF-FF-FF | Apple, Inc.

Maybe other users can submit missing MAC vendor parts too, to save the devs time and effort.

Thanks in advance.

Keep up the great work and best regards,
Han Coumans

**Comment by fyodor** [comment]
Hi Han.  Thanks for your report.  I've just updated the nmap-mac-prefixes in our svn repo to the latest IEEE data, which includes all of those you mention.  It will be in the next Nmap release, and you can also get just the updated mac prefixes file at https://svn.nmap.org/nmap/nmap-mac-prefixes.
