### ISSUE TITLE
How to fix it？

### ISSUE THREAD

**Issue by safebaseline** [nmap/nmap#1434]
C:\WINDOWS\system32>nmap -sS --script=brute 192.168.80.129
Starting Nmap 7.70 ( https://nmap.org ) at 2019-01-16 09:20 ?D1ú±ê×?ê±??
Assertion failed: lua_status(L) == LUA_YIELD, file ..\nse_nsock.cc, line 612

**Comment by nnposter** [comment]
Please try the workaround from #1345

**Comment by 2254865925** [comment]
test

**Comment by nnposter** [comment]
No further activity; presumably resolved
