### ISSUE TITLE
Included libpcap make does not fully clean up

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1435]
When building the included `libpcap`, files `pcap_version.h` and `version.c` are left behind, which complicates automated building of Nmap packages. The following patch remediates the issue:
```diff
--- a/libpcap/Makefile.in
+++ b/libpcap/Makefile.in
@@ -154,6 +154,7 @@
 
 CLEANFILES = $(OBJ) libpcap.* $(TESTS) \
 	$(PROG)-`cat $(srcdir)/VERSION`.tar.gz \
+	pcap_version.h version.c \
 	lex.yy.c pcap-config
 
 MAN1 = pcap-config.1
```
There seems no reason proposing this patch upstream because their makefile has changed in the meantime.

**Comment by djcater** [comment]
I've also noticed a few leftover files after `make clean` as well. E.g. after the following steps (using the GitHub mirror of Nmap):
```
git clone https://github.com/nmap/nmap.git
cd nmap
./configure --prefix=/usr/local
make
sudo make install
make clean
```
Then the output from `git status` is non-empty. Next time I build I'll copy the leftover file list here.

**Comment by nnposter** [comment]
@djcater There is also #967
