### ISSUE TITLE
nmap-service-probes

### ISSUE THREAD

**Issue by g0dA** [nmap/nmap#1442]
Hi
The cpe of openssh in [nmap-service-probes](https://github.com/nmap/nmap/blob/master/nmap-service-probes) may be a little missing。

My ideal situation is that:
OpenSSH 7.2 (protocol 2.0)  ==> cpe:/a:openbsd:openssh:7.2:p2

But the real situation is:
OpenSSH 7.2 (protocol 2.0)  ==> cpe:/a:openbsd:openssh:7.2

This has led to a huge gap in the number of vulnerabilities.

**Comment by dmiller-nmap** [comment]
Thanks for your comments. The 5th field in the [CPE format](https://nmap.org/book/output-formats-cpe.html) is the "update" field, and should not be used to reflect a configuration like protocol version. We have tried to be consistent in our fingerprint output by putting the protocol version in the [`info` field](https://nmap.org/book/vscan-fileformat.html#vscan-tbl-versioninfo) of the fingerprint, which is displayed in (parentheses) in the normal output and in the [`extrainfo` field in the XML output](https://nmap.org/book/output-formats-xml-output.html#output-formats-xml-port-elements).
