### ISSUE TITLE
compile error on Arch Linux

### ISSUE THREAD

**Issue by thesle3p** [nmap/nmap#145]
I can confirm this issue is only present on Arch Linux not debian but none the less I am curious as to what is wrong here: This issue is present on version 6.47 and both the  git and svn versions. My lua version is 5.3.0-2

When I try and compile nmap normally (./configure && make) I get the following error message:
collect2: error: ld returned 1 exit status
Makefile:120: recipe for target 'ncat' failed
make[1]: *** [ncat] Error 1
make[1]: Leaving directory '/home/bob/Toolz/nmap/ncat'
Makefile:149: recipe for target 'ncat_build' failed
make: *** [ncat_build] Error 2

So naturally seeing that ncat won't build I try ./configure --without-ncat  but then I get this compiler error when it tries to build the NSE main:
nse_main.cc: In function ‘int script_set_output(lua_State*)’:
nse_main.cc:122:65: error: ‘luaL_checkint’ was not declared in this scope
     sr.set_output_str(luaL_checkstring(L, 3), luaL_checkint(L,-1));
                                                                 ^
nse_main.cc: In function ‘int host_set_output(lua_State*)’:
nse_main.cc:136:65: error: ‘luaL_checkint’ was not declared in this scope
     sr.set_output_str(luaL_checkstring(L, 4), luaL_checkint(L,-1));
                                                                 ^
nse_main.cc: In function ‘int port_set_output(lua_State*)’:
nse_main.cc:153:65: error: ‘luaL_checkint’ was not declared in this scope
     sr.set_output_str(luaL_checkstring(L, 5), luaL_checkint(L,-1));
                                                                 ^
nse_main.cc: In function ‘std::string format_obj(lua_State*, int)’:
nse_main.cc:442:64: error: ‘luaL_checkint’ was not declared in this scope
   output = std::string(lua_tostring(L, -2), luaL_checkint(L, -1));
                                                                ^
nse_main.cc: In function ‘int nse_yield(lua_State*, int, lua_CFunction)’:
nse_main.cc:664:33: error: invalid conversion from ‘lua_CFunction {aka int (*)(lua_State*)}’ to ‘lua_KFunction {aka int (*)(lua_State*, int, long int)}’ [-fpermissive]
   return lua_yieldk(L, 1, ctx, k); /* yield with NSE_YIELD_VALUE */
                                 ^
In file included from nse_main.h:11:0,
                 from portlist.h:131,
                 from nse_main.cc:4:
/usr/include/lua.h:287:15: note:   initializing argument 4 of ‘int lua_yieldk(lua_State*, int, lua_KContext, lua_KFunction)’
 LUA_API int  (lua_yieldk)     (lua_State *L, int nresults, lua_KContext ctx,
               ^
Makefile:107: recipe for target 'nse_main.o' failed
make[1]: *** [nse_main.o] Error 1
make[1]: Leaving directory '/home/bob/Toolz/nmap-6.47'
Makefile:115: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dmiller-nmap** [comment]
Nmap and Ncat use Lua 5.2. We distribute this with our source, so you can use the `--with-liblua=included` configure option to use it.
