### ISSUE TITLE
http-internal-ip-disclosure fails

### ISSUE THREAD

**Issue by ogerasymenko** [nmap/nmap#1470]
Hello.
I'm try to run nmap --script http-internal-ip-disclosure example.com and got output:

http-internal-ip-disclosure: ERROR: Script execution failed (use -d to debug)

Then launch same with -d option:

Initiating NSE at 17:30
NSE: http-internal-ip-disclosure against example.com (some_ip:80) threw an error!
...in/../share/nmap/scripts/http-internal-ip-disclosure.nse:59: variable 'debug1' is not declared
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nselib/strict.lua:80: in function '__index'
	...in/../share/nmap/scripts/http-internal-ip-disclosure.nse:59: in function 'generateHttpV1_0Req'
	...in/../share/nmap/scripts/http-internal-ip-disclosure.nse:75: in function <...in/../share/nmap/scripts/http-internal-ip-disclosure.nse:72>
	(...tail calls...)

Why can be this output?

**Comment by nnposter** [comment]
One possible explanation is that your environment has commingled versions of Nmap. Can you reproduce the issue with Nmap 7.70, while making sure that no other version of Nmap is present on the host?

**Comment by ogerasymenko** [comment]
Yesterday I'm install quite old version of nmap by command "apt-get install nmap" on Ubuntu 14.04 and it installs 6.40 version. Today I'm build latest version from source code and it works as it should.
Problem was in old version of application.
