### ISSUE TITLE
Overlapped I/O engine for Nsock on Windows

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#148]
Nsock on Windows is still stuck using `select()`, which has performance limitations. [Overlapped I/O](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365603%28v=vs.85%29.aspx) is one option for handling many thousands of concurrent connections efficiently.

References:
- http://www.winsocketdotnetworkprogramming.com/winsock2programming/winsock2advancediomethod5e.html
- http://tangentsoft.net/wskfaq/articles/io-strategies.html

**Comment by hdoreau** [comment]
Here is another useful link on the subject: http://tinyclouds.org/iocp-links.html
I think the difficulty will be to make it fit within nsock reactor model...

Poll() is available on windows and can handle many FDs, though not as efficiently as the advanced APIs mentioned here.

**Comment by dmiller-nmap** [comment]
IOCP Nsock engine was added as part of GSOC 2016 by @Tudor-Coman
