### ISSUE TITLE
Most likely there is a specific script that is stuck. Can you try to identify it by hitting a space while it is looping (and everything else has already stopped)?

### ISSUE THREAD

**Issue by Stivovo** [nmap/nmap#1486]
Most likely there is a specific script that is stuck. Can you try to identify it by hitting a space while it is looping (and everything else has already stopped)?

You should get output similar to the following:
```
Stats: 0:00:05 elapsed; 0 hosts completed (1 up), 1 undergoing Script Scan
NSE: Active NSE Script Threads: 1 (1 waiting)
NSE Timing: About 0.00% done
NSE: Script some-buggy-script: 0 threads running, 1 threads waiting
```

_Originally posted by @nnposter in https://github.com/nmap/nmap/issues/1478#issuecomment-464372532_

**Comment by nnposter** [comment]
No actual issue or question posted. Please feel free to create a new issue.
