### ISSUE TITLE
Script ssl-cert cannot get server certificate when a client certificate is required

### ISSUE THREAD

**Issue by cnotin** [nmap/nmap#1490]
Even after fixing #1488, I've observed that the `ssl-cert` script fails to fetch the server certificate when a SSL client certificate is required.

Without the client certificate, of course we cannot fully connect but we still receive the Server Hello with the server certificate that could be parsed.

Here is the debug output:
```
NSOCK INFO [0.2920s] nsock_iod_new2(): nsock_iod_new (IOD #1)
NSOCK INFO [0.3630s] nsock_connect_ssl(): SSL connection requested to a.b.c.d:8090/tcp (IOD #1) EID 9
NSOCK INFO [0.3860s] handle_connect_result(): EID 9 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
NSOCK INFO [0.3860s] nsock_trace_handler_callback(): Callback: SSL-CONNECT ERROR [Input/output error (5)] for EID 9 [a.b.c.d:8090]
NSE: [ssl-cert M:560520e6e748 a.b.c.d:8090] getCertificate error: Failed to connect to server
NSE: Finished ssl-cert M:560520e6e748 against a.b.c.d:8090.
```

![image](https://user-images.githubusercontent.com/550823/53098179-61a76a80-3523-11e9-8a9e-907e0aac98d2.png)

**Comment by cnotin** [comment]
It works fine if I disable the status check after `socket:connect` in sslcert.lua.
Is this check necessary?
There's already a check below after `cert = socket:get_ssl_certificate()`

**Comment by cnotin** [comment]
To test this issue, here is how to quickly create a TLS server that requests a client certificate:
`socat -v OPENSSL-LISTEN:443,reuseaddr,fork,verify=1,cert=site.pem -`

**Comment by aph3rson** [comment]
+1. still seeing this issue in 7.70. Trying on 7.80.

**Comment by nnposter** [comment]
What a timing. If you grab today's SVN, you will benefit from @dmiller-nmap 's commit 81ceee49c525302d8ff85d159f4d4b7d18486d68. Apply PR #1873 on top of it and you might find the script working as expected.

**Comment by cnotin** [comment]
Confirmed! Thanks @dmiller-nmap and @nnposter

**Comment by vigneshkaladharan** [comment]
Hi @cnotin  I am facing the same issue with nmap 6.40 not able to retrieve the certificate since client certification is required.could you please help me on this.

**Comment by vigneshkaladharan** [comment]
command what i have used nmap -p- --script +ssl-cert --version-intensity 1 -v --packet-trace -oN output.txt <ip>

**Comment by cnotin** [comment]
Nmap 6.40 is very old. Just upgrade and it should work!
You'll benefit from many other improvements and fixes too.
