### ISSUE TITLE
SVN not synchronizing with GitHub

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1495]
Last successful synchronization was on 2/18 (but there were no SVN commits until earlier today).

**Comment by nnposter** [comment]
Looks like the commits are flowing in again

**Comment by nnposter** [comment]
Synchronization is not happening again

**Comment by dmiller-nmap** [comment]
We have moved the synchronization scripts to different infrastructure that ought to be more reliable and give us better indication when there are problems.
