### ISSUE TITLE
Sierra Wireless PIN2 Conflict

### ISSUE THREAD

**Issue by PeteSL** [nmap/nmap#1497]
There is a conflict between the NPCAP drivers and the Sierra Wireless drivers in Windows 10 that causes the cell adapter to connect but not pass data.  When running Windows 10 trouble shooter, it says SIM is locked and need to enter PIN2.  Uninstalling NPCAP resolved issue.  Resolution was gleaned from public posts referencing npcap removal as a potential resolution to the problem.  Card is a DW5811e from Dell which is a Sierra Wireless Snapdragon X7 LTE card.

**Comment by dmiller-nmap** [comment]
Thanks for the bug report. While we investigate, you may be able to work around the problem by unbinding Npcap from the LTE network adapter, which would allow you to continue using Npcap on other adapters. In Control Panel > Network and Internet > Network Connections, right-click the adapter and choose Properties. In the window labeled "This connection uses the following items:" uncheck the box next to "Npcap Packet Driver (NPCAP)" and choose OK.

To help us diagnose better, please provide the output of Npcap's [DiagReport tool](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport). Thanks!

**Comment by dmiller-nmap** [comment]
This should be fixed in Npcap 0.9983 if you avoid installing "Legacy loopback support." The issue was a conflict with the Npcap Loopback Adapter, which is no longer required.

**Comment by alexhalbi** [comment]
I just experienced this issue and it would be great if the "Legacy loopback support." is not a default enabled option in the setup, since it is not really required unless some legacy application is installed.

**Comment by dmiller-nmap** [comment]
@alexhalbi The "Legacy loopback support" option is not enabled by default. For reinstallations and upgrades, the installer records the currently-installed options and supplies them as defaults. You can still un-check the option when running the installer, or supply the "/loopback_support=no" command-line option.
