### ISSUE TITLE
npcap should use libpcap 1.9.0

### ISSUE THREAD

**Issue by guyharris** [nmap/nmap#1506]
The current Npcap 1) appears to build remote capture support but 2) that support doesn't work - see, for example, [this ask.wireshark.org question](https://ask.wireshark.org/question/7772/not-able-to-capture-packets-on-remote-interface/), [this Wireshark bug](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15547), and the-tcpdump-group/libpcap#795.

Libpcap 1.8.x's remote-capture support had a number of bugs; 1.9.0 was the first release where it was reasonably usable (even on Windows, much less on UN\*Xes).

Please upgrade to libpcap 1.9.0 (and let us know what changes you need to apply, and why).

**Comment by dmiller-nmap** [comment]
Looks like we'll get this included in the next release. Had some difficulty due to this libpcap issue: the-tcpdump-group/libpcap#810

**Comment by guyharris** [comment]
So shall we close this?

**Comment by dmiller-nmap** [comment]
Yeah, should be fine. We often keep issues open until release when we need confirmation from the original reporter, but this is straightforward.

**Comment by guyharris** [comment]
[Wireshark bug 15547](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15547), which reported that remote capture wasn't working with Npcap, now has a user who said "I have the same problem" saying that remote capture is working with npcap v0.992.
