### ISSUE TITLE
npcapwatchdog task has bad path to checkstatus.bat

### ISSUE THREAD

**Issue by chrullrich** [nmap/nmap#1513]
After installing npcap 0.99-r9 (via Wireshark) on Windows 10, there is a scheduled task named "npcapwatchdog". This task's only action is this:

![image](https://user-images.githubusercontent.com/4695907/54281044-33083700-4599-11e9-8a94-5ab846ba3583.png)

Whatever creates this task should make sure that spaces in it are not misinterpreted as above.

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! Properly quoting strings so that they are correctly interpreted by NSIS, cmd.exe, and schtasks.exe is difficult, but we believe the problem is solved in Npcap 0.991, released yesterday.
