### ISSUE TITLE
Capture regression with Npcap 0.991

### ISSUE THREAD

**Issue by hdm** [nmap/nmap#1525]
After upgrading to npcap 0.991 on Windows 10,  captures for my application's filters no longer return packets. An example filter that is no longer working is `(udp and dst port 53) or (tcp and tcp[13] = 18)`

Stopping the npcap service, uninstalling npcap 0.991, and reinstalling 0.99-r9 did not resolve the issue either, nor did a full reboot. Removing npcap 0.991 and then manually deleting npcap.sys and related files, then reinstalling npcap 0.99-r9 fixed this, but this wasn't the expected outcome.

This almost seems like two issues (regression on filters and failure to cleanly uninstall). Anything I can provide to help diagnose the issue?

**Comment by hdm** [comment]
For the udp filter above, this is trying to match an *outbound* packet, if that helps (based on #1438 it seems like that might be related)

**Comment by dmiller-nmap** [comment]
Thanks for the report. We did make some substantial changes to how capture filters are applied to address the report in #1406, so it's likely we introduced the bug there.

Can you try to see if this only affects the filters involving byte offsets, e.g. `tcp[13] = 18`, or if filters that do not involve byte offsets are also affected, e.g. `udp and dst port 53`?

**Comment by hdm** [comment]
I retried with a few variants and had the same result with each:
* (udp and dst port 53) or (tcp and tcp[13] = 18)
* (udp and dst port 53) or (tcp)
* (udp) or (tcp)

Skipping the filter entirely seems to work, but isn't a usable option for my case.

This system is x86_64 Windows 10 build 1803

**Comment by dmiller-nmap** [comment]
Npcap 0.992 should resolve this issue. Thanks!

**Comment by hdm** [comment]
Npcap 0.992 solves this issue here, thanks!
