### ISSUE TITLE
Windows Service not visible

### ISSUE THREAD

**Issue by Mitschmaster** [nmap/nmap#1530]
Service is not visible in taskmanager or services.msc. I would want to start it when i need it and disabled the autostart. i can start it with command line though.

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion. This is a fundamental difference between the way that WinPcap worked versus how Npcap works; Npcap is a NDIS 6 filter driver, not a Windows Service. Disabling the service will cause delays in network connectivity at boot time, so we will be removing the installer option that affects driver start type and only supporting Npcap in a boot-start configuration. There is more discussion about this at #1502.
