### ISSUE TITLE
Readme for Npcap contains misleading information

### ISSUE THREAD

**Issue by Vort** [nmap/nmap#1535]
[README.md](https://github.com/nmap/npcap/blob/master/README.md) for Npcap contains **Packaging** section, which points to non-existent file: `installer\Deploy.bat`.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Since we began maintaining the [Npcap Guide](https://nmap.org/npcap/guide/), we've neglected the README. I'll get some changes pushed soon.
