### ISSUE TITLE
nmap -sn 192.168.1.1 unexpected results

### ISSUE THREAD

**Issue by cawfehman** [nmap/nmap#1537]
running this command while doing a packet capture seems to indicate the -sn option doesn't disable port scan, but limits it to 80/443.  

nmap -sn 192.168.1.1 seems to also send a single SYN packet to port 443 and an ACK to port 80 on 192.168.1.1

Is this expected behavior? 

running zenmap on Windows 7.70 also tried from command line.

**Comment by nnposter** [comment]
What you are seeing is not a port scan but part of host discovery. Please review section *Host Discovery* in the nmap man page. Use `-Pn` to disable the discovery altogether or `-PE` to rely solely on ICMP ping.

**Comment by cawfehman** [comment]
Thank you for clarifying, thought it was something I missed.  -PE provided the results I was looking for.  Thank you for your time.
