### ISSUE TITLE
Add an option to probe for service/version info from an IP:port combination

### ISSUE THREAD

**Issue by Qazeer** [nmap/nmap#1540]
Adding an option to conduct scans using an input file of targets in the format IP:PORT (or any other type of delimiter, with one IP / port combination per line) would be a cool enhancement to nmap.

It would allow for services scans only, the initial ports enumeration step could be done using an asynchronous and stateless ports scanner (masscan, zmap, etc.). The needs arising whenever scanning larger IP ranges.

**Comment by dmiller-nmap** [comment]
Thanks for requesting this option. We have an open discussion of the challenges surrounding this change over at #1217.
