### ISSUE TITLE
Unable to compile : libpcap/bpf_filter issue

### ISSUE THREAD

**Issue by ionreflex** [nmap/nmap#1545]
This looks a lot like https://github.com/nmap/nmap/issues/1379 (so I tried `make distclean` but to no avail...)

Trying to compile from current pull, I have the same result at `make` (following a `./configure --without-zenmap`) on up-to-date [CentOS Linux 7 (Core)] and [Ubuntu 18.10] :

```
make[1]: *** No rule to make target 'bpf_filter.c', needed by 'bpf_filter.o'.  Stop.
make[1]: Leaving directory '/home/nulinflux/gitstuff/nmap/libpcap'
make: *** [Makefile:144: build-pcap] Error 2
(╯°□°）╯︵ ┻━┻
```

Am I missing something?

-|-

**Comment by dean1510** [comment]
Source file is missing. Just add it manually from libpcap repo.

**Comment by tsellers-r7** [comment]
@bonsaiviking - FYI, I just ran into this as well on Ubuntu 18.04 with  a completely fresh checkout from SVN. Perhaps related to the end of March changes to libpcap?

**Comment by dean1510** [comment]
/nmap/.gitignore contains line: "libpcap/bpf_filter.c". I don't know the reason.

**Comment by ionreflex** [comment]
Thanks to @bonsaiviking I confirm the issue is fixed
