### ISSUE TITLE
Zenmap 6.49b1 gui won't launch on Yosemite 10.10.3

### ISSUE THREAD

**Issue by tsimmons** [nmap/nmap#155]
When you launch the gui, you are forced to authenticate (normal.) After authentication, the app immediately quits; XQuartz does not get launched.

The following appears in Console:

`6/5/15 3:30:57.381 PM authexec[2067]: executing /Applications/Zenmap.app/Contents/MacOS/zenmap_wrapper.py`
`6/5/15 3:30:57.422 PM com.apple.xpc.launchd[1]: (org.insecure.Zenmap.210476[2057]) FairPlay decryption failed on binary.
`

I have tried launching XQuartz first and it doesn't change the behavior.

BTW, I launch the Zenmap gui from 6.47 and it runs just fine (actually invoking the nmap 6.49BETA!)

**Edit: I also have macports installed, if that makes a difference.

Is it just me?

**Comment by dmiller-nmap** [comment]
See also http://seclists.org/nmap-dev/2015/q4/101

**Comment by dmiller-nmap** [comment]
@tsimmons Do you still have this problem with 6.49BETA6? Can you confirm that the nmap-6.49BETA6-1.dmg file is not corrupted by checking [the GPG signature](https://nmap.org/dist/sigs/nmap-6.49BETA6-1.dmg.asc) or [checksums](https://nmap.org/dist/sigs/nmap-6.49BETA6-1.dmg.digest.txt)?

**Comment by tsimmons** [comment]
The latest dmg appears to run fine under Yosemite 10.10.5.

<img width="307" alt="screen shot 2015-11-05 at 7 18 53 am" src="https://cloud.githubusercontent.com/assets/366120/10969390/aa8b95be-838d-11e5-9d8e-c3857cc415ff.png">
