### ISSUE TITLE
npcap loopback adapter - no internet with Win10

### ISSUE THREAD

**Issue by mazarick** [nmap/nmap#1553]
Npcap Loopback Adapter
No Internet

I have the following:

npcap ver # .98
IPv6 DNS servers:	fec0:0:0:ffff::1%1
fec0:0:0:ffff::2%1
fec0:0:0:ffff::3%1
Manufacturer:	Microsoft
Description:	Npcap Loopback Adapter
Driver version:	10.0.17134.1
Physical address (MAC):	02-00-4C-4F-4F-50

When I look at the Win10 ipconfig info, I get:
 ipconfig /all

Ethernet adapter Npcap Loopback Adapter:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Npcap Loopback Adapter
   Physical Address. . . . . . . . . : 02-00-4C-4F-4F-50
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::29d9:34bc:ebde:65ae%7(Prefe
   Autoconfiguration IPv4 Address. . : 169.254.101.174(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 620888140
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-24-2D-E0-B3-46-2C-3A-
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

I normally use the RealTek driver (the default Ethernet) via IPv4.  

I have Wireshark and NMAP installed (very recent versions)

**Comment by JaapKeuter** [comment]
Latest Wireshark (3.0.1) should come with npcap 0.99r2, not the version 0.98 you stated. Retry with that one first to see if the problem persists.

**Comment by mazarick** [comment]
I downloaded the latest npcap version.   The results are:

**Comment by mazarick** [comment]
My “next to latest” settings were:

 

Link-local IPv6 address:   fe80::5086:aa1d:77b0:e480%27

IPv6 DNS servers:    fec0:0:0:ffff::1%1

fec0:0:0:ffff::2%1

fec0:0:0:ffff::3%1

Manufacturer:   Microsoft

Description:    Npcap Loopback Adapter

Driver version: 10.0.17763.1

Physical address (MAC):    02-00-4C-4F-4F-50

 

I changed it to use Google’s Public DNS Servers (2001:4860:4860::8888 and 2001:4860:4860:0:0:0:0:8844)

 

The configuration still fails with a message that “Npcap does not have a valid IP configuration     Not Fixed”

**Comment by dmiller-nmap** [comment]
Thanks for the report! The Npcap Loopback Adapter was known to cause problems with some software, so we removed the need for it in Npcap 0.9983, released today. Be sure to deselect (un-check) the "Legacy loopback support" to get the new loopback capture support without cluttering up the list of real network adapters. Let us know how it works for you.
