### ISSUE TITLE
Using custom CSV database.

### ISSUE THREAD

**Issue by Davetheraveuk** [nmap/nmap#1561]
I would like to use a custom CSV database.
The database is called **_allitems.csv_** and the fields I would like outputted in the terminal are **_Name, Description, Severity, Published, Added, Modified_** and **_Solution_**.

How would I do this?
Any help would be great.

**Comment by dmiller-nmap** [comment]
I'm not sure what you're asking here. Nmap does not produce CSV output, and its output does not have fields that match those descriptions. You can read about Nmap's output formats [in the online documentation](https://nmap.org/book/output.html). The best way to convert Nmap output to a different format is usually to parse the [XML output](https://nmap.org/book/output-formats-xml-output.html) with the tool or language of your choice.
