### ISSUE TITLE
Npcap 0.992 regression: pcap_lib_version 

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#1566]
Hi !

We use `pcap_lib_version` to detect which version the user is running (basically we used to parse for `Npcap` instead of `Winpcap`), as advised by the [doc](https://nmap.org/npcap/guide/npcap-devguide.html):

https://github.com/nmap/npcap/blob/a8982716bd2d7a080b43aeb97507a681f48dacee/docs/npcap-devguide.xml#L129-L145

However this behavior has changed:
- **with 0.992**
```
>>> pcap_lib_version()
b'libpcap version 1.9.0 (packet.dll version 0.992)'
```
- **with 0.991**
```
>>> pcap_lib_version()
b'Npcap version 0.991, based on libpcap version 1.8.1'
```
This breaks the detection. If this is expected, please update the doc accordingly :-)

**Comment by fyodor** [comment]
Thanks for the report, @gpotter2.  A build system change caused this, but @bonsaiviking fixed it for the next version, which we hope to release this week.

**Comment by gpotter2** [comment]
Thanks for the info !
