### ISSUE TITLE
IPv4 fallback support is missing from ncat

### ISSUE THREAD

**Issue by quanah** [nmap/nmap#157]
As discussed in this thread from 2 years ago:
http://seclists.org/nmap-dev/2013/q4/269

ncat does not have IPv4 fallback.  This is a serious deficiency and lack of feature parity with the other nc implementation.  It makes ncat essentially unusable on systems that have both ipv4 and ipv6 localhost defined, but only have services listening on the ipv4 localhost.

With only ipv4 localhost defined:

[root@zqa-226 ncat]# echo STATUS | ./ncat -w 15 localhost 7171
SUCCESS ACTIVE[root@zqa-226 ncat]#

After defining ::1 to localhost:

[root@zqa-226 ncat]# echo STATUS | ./ncat -w 15 localhost 7171
Ncat: Connection refused

**Comment by robert-scheck** [comment]
+1 for getting this deficit fixed

**Comment by mhlavink** [comment]
see this email for updated patch with addressed comments http://seclists.org/nmap-dev/2015/q2/92

**Comment by quanah** [comment]
I disagree that this is an "enhancement".  This is a serious bug and lack of feature parity that causes *serious* issues when trying to use ncat as a replacement for nc.

**Comment by d33tah** [comment]
I second @quanah.

**Comment by tremblerz** [comment]
Hello folks,
I have a small report regarding this please tell me if I am missing something and whether patch works fine or not.
[REPORT](https://docs.google.com/document/d/1CONA1kdttPsjy-qwNtvkFb_z8LSiBQ3Q7YTkBdtSh04/edit?usp=sharing)

**Comment by dmiller-nmap** [comment]
Fixed in 4629f6d8 with patch via http://seclists.org/nmap-dev/2015/q2/92
