### ISSUE TITLE
npcap adapter is missing in Wireshark after reboot Windows

### ISSUE THREAD

**Issue by ddayzzz** [nmap/nmap#1570]
Hello. I installed lastest version(0.992) of npcap. As soon as the installation completed, I could find the npcap lookback adapter in Wireshark. However, after I reboot, I couldn't find the same item in Wireshark. *Base Filtering Engine service* is enable by default and starts automatically. The *Npcap lookback Adapter* installed by npcap still exist, but the I can't see the network name of this adapter in my system.

**OS**: Windows 10 1903(18362.53), zh_CN, x86_x64
**Wireshark**: v3.0.1-0-gea351cd8, zh_CN
[install.log](https://github.com/nmap/nmap/files/3111386/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/3111387/NPFInstall.log)
[DiagReport-20190424-164315.txt](https://github.com/nmap/nmap/files/3111388/DiagReport-20190424-164315.txt)

**Comment by FlorianReimold** [comment]
I can confirm the missing Npcap Loopback Adapter with a fresh installation. My own software depends on the loopback adapter and thus stops working when installing Npcap 0.922. Although Windows shows the loopback adapter in the Network manager, neither Wireshark nor my own software can find it. I installed Npcap 0.992 with default options. I am using SDK 1.01, which appears to still be the most recent one.

My current solution is to downgrade to Npcap 0.99r9 where everything works just fine. When upgrading to Npcap 0.992 again, everything still works until I reboot Windows.

![wireshark](https://user-images.githubusercontent.com/11774314/56716574-f9e7e880-673a-11e9-9721-bb6d2cec1f91.png)
[install.log](https://github.com/nmap/nmap/files/3115624/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/3115625/NPFInstall.log)
[DiagReport-20190425-090722.txt](https://github.com/nmap/nmap/files/3115626/DiagReport-20190425-090722.txt)

**Comment by FlorianReimold** [comment]
I played around a little and discovered that when I run
```bat
sc stop npcap
sc start npcap
```
the Loopback adapter shows up again. I also discovered that Npcap 0.99r9 did not actually fix the problem, even with that version the adapter disappears when restarting Windows and re-appears when stopping and starting the npcap service again.

**Comment by ddayzzz** [comment]
> I played around a little and discovered that when I run
> 
> ```batchfile
> sc stop npcap
> sc start npcap
> ```
> 
> the Loopback adapter shows up again. I also discovered that Npcap 0.99r9 did not actually fix the problem, even with that version the adapter disappears when restarting Windows and re-appears when stopping and starting the npcap service again.

Thank you😊! I managed to find the npcap lookback adapter with your instructions. In addition, I found that both npcap lookback adapter and other virtual adapters(e.g. Hyper-V Virtual Ethernet Adapter) disappear at the same time. I think there might be some problem between npcap and MS KM-Test driver. 
Thanks a lot. :)

**Comment by dmiller-nmap** [comment]
Confirmed this here on Npcap 0.992. The fix for this ought to be in the next release. Thanks!

@FlorianReimold Windows often does not let you downgrade a driver, so installing Npcap 0.99-r9 may not actually install the older working driver, which is why you still experience the problem.

**Comment by dmiller-nmap** [comment]
This was fixed earlier in Npcap 0.993, but Npcap 0.9983 released today removes the need for the Npcap Loopback Adapter entirely. Be sure to deselect (un-check) the "Legacy loopback support" to get the new loopback capture support. Let us know how it works for you.
