### ISSUE TITLE
npcap 0.993 uninstall not possible (results in blue screen)

### ISSUE THREAD

**Issue by libertyx82** [nmap/nmap#1577]
After i have installed npcap 0.993 on my windows (10 Build 17763.rs5 64bit) i can not uninstall npcap, the uninstall will result in an windows blue screen)

`IRQL NOT LESS OR EQUAL`

![IMAG1330](https://user-images.githubusercontent.com/22996350/56861946-32d7c580-69a6-11e9-9ae1-555c415c411e.jpg)

**Comment by dmiller-nmap** [comment]
Thanks for reporting this! We did not encounter this problem in testing. Can you please provide the [crash dump](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues-bsod) that can be found in `C:\Windows\Minidump\` or `C:\Windows\MEMORY.DMP` so that we can diagnose the bug? Thank you.

**Comment by dmiller-nmap** [comment]
As a workaround, you can disable the Npcap driver service and then uninstall, which should prevent the blue screen:

1. In an Administrator command window, run the command: `sc.exe config npcap start= disabled`
2. Reboot the system.
3. Uninstall Npcap.

**Comment by dmiller-nmap** [comment]
I'm sorry, I incorrectly used the wrong issue number in that commit message. It is not related to this one.

**Comment by libertyx82** [comment]
Hi,
this Problem was caused by the AV Software i use (Avast), after i removed Avast the Problem no longer occurs.

So this is not an bug of npcap.

**Comment by sbaxevanis** [comment]
Looks like Avast is the culprit - my experiences were identical and when I disabled the file and behavior options of Avast I was able to uninstall pcap.

**Comment by M1n1-Z** [comment]
Avast was not the cause in my case. I was able to uninstall by executing uninstaller in silent mode: 
`C:\Program Files\NPcap\Uninstall.exe /S`

**Comment by zdunning13** [comment]
I have tried uninstalling silently, disabling the service from starting, and disabled Avast and I keep getting a blue screen when attempting to uninstall Npcap 0.955. I'm also getting a blue screen when rebooting my computer, an unplugging from my StarTech USB Dock.

**Comment by libertyx82** [comment]
avast is only the Cause then the firewall module is installed, due to the reason that the firewall is causing this.
it is not sufficient to disable avast, avast or the firewall modul must be uninstalled to solve the Problem

**Comment by zdunning13** [comment]
Uninstalling Avast and then uninstalling Npcap worked for my system. Thanks!

**Comment by M1n1-Z** [comment]
I tried many things before. Maybe I did it from failsafe boot, and thus avast might not be running...

**Comment by Youda008** [comment]
In fact, the error was on Npcap side in the end, it unloaded its driver module while Avast was still holding handle to it. https://github.com/nmap/nmap/issues/1642
Easier than uninstalling Avast is to disable the npcap service and after reboot upgrade it to 0.996 or newer, as described here https://github.com/nmap/nmap/issues/1626#issuecomment-502393376
