### ISSUE TITLE
npcap 0.993 installer bad checkbox handling

### ISSUE THREAD

**Issue by yoctozepto** [nmap/nmap#1579]
I discovered an issue with the installer: if one tries to deselect the loopback interface, the installer goes straight to installation phase as if the "install" button was pressed right after that (the loopback is righteously not installed). The other checkboxes seem to work just fine.

**Comment by dmiller-nmap** [comment]
Thanks for this bug report. I have confirmed the issue and hope to have a bugfix release available soon. If you want to install without loopback support in the meantime, try running the installer from the command line with the option: `/loopback_support=no`

**Comment by dmiller-nmap** [comment]
I fixed this in fyodor/npcap-build@72c01c7, but used the wrong issue number in the commit message. Sorry!
