### ISSUE TITLE
6.49BETA1 configure failure

### ISSUE THREAD

**Issue by ohauer** [nmap/nmap#158]
I tested a nmap-6.49BETA1 build in an isolated build jail (FreeBSD pouderie).

The following configure arg will fail 
--with-openssl=/usr --without-localdirs --without-zenmap --without-ndiff --with-libpcre=/usr/local --with-liblua=included --without-nmap-update --prefix=/usr/local
...
checking if AF_INET6 IPPROTO_RAW sockets include the packet header... no
checking for a Python interpreter with version >= 2.4... none
configure: error: in `/wrkdirs/usr/ports/security/nmap/work/nmap-6.49BETA1':
configure: error: --with-ndiff requires Python 2.x with x>=4
See `config.log' for more details
===>  Script "configure" failed unexpectedly.

6.47 builds fine, it seems the culprit comes from the changes in configure.ac to test if python is available and if not ignore --without-ndiff.

**Comment by G10h4ck** [comment]
Pushed a quick fix here please test and review it ;)
https://gitlab.com/g10h4ck/nmap-gsoc2015/commits/hotfix/158

**Comment by dmiller-nmap** [comment]
@G10h4ck Looks like a good approach. Change the condition to `elif ... fi` instead of `else if ... fi fi` and commit it. Thanks!

**Comment by ohauer** [comment]
Thanks, changing s/else/elif/ fixed fixed the the issue fir me.
Will push BETA1 on the weekend into the FreeBSD ports tree so it gets wider testing
