### ISSUE TITLE
[NPcap]The name of default item returned by `reg` can be affacted by system locale and may not be used by `CheckStatus.bat` and `FixInstall.bat`

### ISSUE THREAD

**Issue by yyjdelete** [nmap/nmap#1582]
Replace all `(Default)` to `REG_SZ` in `CheckStatus.bat` and `FixInstall.bat` seems work for me.

```
>reg query "HKLM\Software\WOW6432Node\Npcap" /ve

HKEY_LOCAL_MACHINE\Software\WOW6432Node\Npcap
    (默认)    REG_SZ    C:\Program Files\Npcap
```

zh_CN:
![image](https://user-images.githubusercontent.com/1819074/56950819-f0aab180-6b68-11e9-9285-00dcac095730.png)

After `chcp 65001`
![image](https://user-images.githubusercontent.com/1819074/56951452-78dd8680-6b6a-11e9-889d-2d5905281e87.png)

**Comment by dmiller-nmap** [comment]
Thanks for this bug report! Your suggestion of using `REG_SZ` will work perfectly.

**Comment by yyjdelete** [comment]
Forget to close this, the new version works for me.
