### ISSUE TITLE
The Npcap SDK needs to be updated to libpcap 1.9.0

### ISSUE THREAD

**Issue by guyharris** [nmap/nmap#1584]
Currently, the 1.01 Npcap SDK provides headers from libpcap 1.8.x, but current versions of Npcap are based on libpcap 1.9.0; if a version of Npcap comes out that's based on a newer version of libpcap than the previous version, the SDK should be updated to include the new headers - and, presumably, a new load library for the DLL, as there may be new APIs added.

**Comment by dmiller-nmap** [comment]
Thanks for the reminder. We are currently working on this as part of a general effort to create a standardized test suite. We need to ensure our SDK build scripts work with the new libpcap version, and will probably need to upstream some documentation formatting changes, so this is pretty high priority.

**Comment by dmiller-nmap** [comment]
@guyharris Is there a canonical location to find API changes between versions of libpcap? The CHANGES file has some interesting things, but I would love to see something like Lua does with [changes from previous version](https://www.lua.org/manual/5.3/readme.html#changes) or [incompatibilities with previous version](https://www.lua.org/manual/5.3/manual.html#8).

**Comment by dmiller-nmap** [comment]
Npcap SDK 1.02 includes libpcap 1.9.0 headers and docs. Thanks!

**Comment by guyharris** [comment]
> @guyharris Is there a canonical location to find API changes between versions of libpcap? The CHANGES file has some interesting things, but I would love to see something like Lua does with [changes from previous version](https://www.lua.org/manual/5.3/readme.html#changes) or [incompatibilities with previous version](https://www.lua.org/manual/5.3/manual.html#8).

We should probably consider doing release notes for both libpcap and tcpdump; you might want to add them as libpcap and tcpdump issues.  I'll try to do at least some documentation of API changes; I'll try as hard as I can not to do anything to the APIs to make it necessary to *have* an "incompatibilities with previous version" section (complete source *and* binary compatibility with earlier versions is a strong goal of mine for libpcap - some OSes that ship with libpcap as an API have a significant number of binary-only applications that the vendor expects to run on multiple OS versions).

**Comment by dmiller-nmap** [comment]
Probably related issue: #1761
