### ISSUE TITLE
Npcap: Add "read only" option to disable packet sending

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#1593]
We have received several requests from people for an option to disable all packet sending functionality from Npcap, so users can sniff the network but not inject raw frames.  At least three companies requesting this are coming from WinPcap, where they had modified that driver to include this read-only functionality.

One important note is that Npcap does offer an "admin-only" security mode which WinPcap lacks.  If you enable admin-only mode at install time, packet reading and writing can only be done with Administrator privileges.  This prevents normal unprivileged users or malware that gets in on a browser or similar from accessing any of the functionality.  If someone does have Admin rights on Windows, it will be very hard to keep them from writing to the network (using Npcap or otherwise).  But maybe people who want this feature can lock the systems down sufficiently so that even admins can't install other packet writing drivers, etc.

Or maybe it is important to some companies that normal unprivileged users be allowed to sniff the network (using Wireshark, etc.) but they just don't want those users sending any packets.  In this case, the read-only mode would be more easily effective.

We haven't decided whether to add this feature yet, so we're interested in feedback from folks who want it.  Is admin-only mode enough?  If not, would you be trying to lock down normal users (e.g. not using admin-only mode) or are you interested in having admin-only mode AND preventing those admins from writing packets?

If we added this feature and we wanted it to improve the chances of it actually protecting against admin users, we would probably have to compile special versions of the drivers with #ifdef guards on the ioctl processing part that handles write requests.  Because if we just check a registry key or file for whether this options was specified at install time, admin users could usually change those.

**Comment by tinti** [comment]
Would be very useful to have read-only too.

**Comment by fyodor** [comment]
Hi @tinti and other folks interested in this feature.  We ended up adding this to [Npcap OEM](https://nmap.org/npcap/#oem).  This is the commercial version of Npcap for companies to deploy internally and/or redistribute with products (depending on which Npcap OEM license they buy).  Adding it to the free version of Npcap would be problematic because it could conflict with other software using Npcap on the machine when used in general purpose computers.  Like if Npcap read-only is installed to prevent capture software like Wireshark from sending packets, that would be fine until/unless other software like Nmap is installed later and now can't send probes.  Even for Npcap OEM, customers have to request the feature (which is free for them) so they don't use it without being fully aware of the consequences.  It can be useful for embedded devices and extraordinarily locked down systems where the users/vendors know that raw packet sending won't ever be necessary, and they use Npcap OEM read-only to enforce that.

Since this feature does exist now in Npcap OEM, I am closing this ticket.  Any existing or potential customers interested in Npcap OEM read-only can write to us at sales@nmap.com.  Cheers!
