### ISSUE TITLE
issue with Nmap 7.70 (Windows 7)

### ISSUE THREAD

**Issue by choywungit** [nmap/nmap#1594]
i've install the latest version of Nnmap as per the site in https://nmap.org/download.html

Latest stable release self-installer: nmap-7.70-setup.exe 
Latest Npcap release self-installer: npcap-0.995.exe

Issue 1 : When i run the Nmap on windows it will return me as follow. Is there anything else that might be missing?

Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-12 19:21 Malay Peninsula Standard Time
WARNING: Could not import all necessary Npcap functions. You may need to upgrade to the latest version from http://www.npcap.org. Resorting to connect() mode -- Nmap may not function completely

Issue 2 : When running the nmap on windows, will need to indicate it with --unprivileged. is this expected?
e.g nmap --unprivileged scanme.nmap.org

**Comment by dmiller-nmap** [comment]
It sounds like Npcap was not installed correctly. Can you please provide the output from [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues-diagreport) for your system so that we can better diagnose the problem? Your `install.log` file may also be useful.

**Comment by dmiller-nmap** [comment]
Closing due to no followup. If the problem persists in the latest version, please open a new issue.
