### ISSUE TITLE
LIB files missing from NPCAP SDK 1.02 zip file?

### ISSUE THREAD

**Issue by dhopf** [nmap/nmap#1597]
When I download the zip file of the SDK for version 1.01 ([Npcap SDK 1.01](https://nmap.org/npcap/dist/npcap-sdk-1.01.zip)), the downloaded zip file contains the following structure and files under the folder **Lib**:

- x64
  - Packet.lib
  - wpcap.lib
- Packet.lib
- wpcap.lib

With version 1.02 of the SDK ([Npcap SDK 1.02](https://nmap.org/npcap/dist/npcap-sdk-1.02.zip)) the structure is still there, but no .lib files.
Is this an intended change? Do I need to compile NPCAP by myself on Windows now to obtain the Libs?

Regards
Daniel

**Comment by fyodor** [comment]
Thanks for the note.  We have now released Npcap SDK 1.03 to fix this issue and made changes to hopefully prevent it from happening again.
