### ISSUE TITLE
npcap fails to install properly in windows 10 Enterprise 

### ISSUE THREAD

**Issue by n2cbo** [nmap/nmap#1606]
Here are the details of the install:
Stopping the npf driver
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

Stopping the npcap driver
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

Output folder: C:\Program Files\Npcap
Extract: LICENSE
Extract: DiagReport.bat
Extract: DiagReport.ps1
Extract: FixInstall.bat
Extract: NPFInstall2.exe
Extract: NPFInstall.exe
Output folder: C:\Program Files\Npcap
Extract: npf.sys
Extract: npf.cat
Extract: npf.inf
Extract: npf_wfp.inf
Extract: npcap.sys
Extract: npcap.cat
Extract: npcap.inf
Extract: npcap_wfp.inf
Output folder: C:\Program Files\Npcap
Extract: Uninstall.exe
Installing NDIS6.x x64 driver for Win7, Win8 and Win10
Output folder: C:\WINDOWS\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\WINDOWS\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Users\mae\AppData\Local\Temp\nsi890E.tmp
Extract: Insecure-SHA1.cer
TrustedPublisher "Trusted Publishers"
Related Certificates:

Exact match:
Element 2:
Serial Number: 09a62d3bec2c603652d5cb46a1a1ebab
Issuer: CN=DigiCert EV Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
 NotBefore: 4/10/2018 8:00 PM
 NotAfter: 11/7/2019 8:00 AM
Subject: CN=Insecure.Com LLC, O=Insecure.Com LLC, L=Seattle, S=Washington, C=US, SERIALNUMBER=200010310013, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=California, OID.1.3.6.1.4.1.311.60.2.1.3=US
Non-root Certificate
Cert Hash(sha1): 83b2ddfef9f7004438d7aa66c524344f71a70b48

Certificate "Insecure.Com LLC" already in store.
CertUtil: -addstore command completed successfully.
Delete file: C:\Users\mae\AppData\Local\Temp\nsi890E.tmp\Insecure-SHA1.cer
Extract: Insecure-EV.cer
TrustedPublisher "Trusted Publishers"
Related Certificates:

Exact match:
Element 0:
Serial Number: 033b0a4dc1797373e6efec07fc63ba34
Issuer: CN=DigiCert EV Code Signing CA (SHA2), OU=www.digicert.com, O=DigiCert Inc, C=US
 NotBefore: 11/2/2016 8:00 PM
 NotAfter: 11/7/2019 8:00 AM
Subject: CN=Insecure.Com LLC, O=Insecure.Com LLC, L=Seattle, S=Washington, C=US, PostalCode=98104, STREET=113 Cherry St #1337, SERIALNUMBER=200010310013, OID.1.3.6.1.4.1.311.60.2.1.2=California, OID.1.3.6.1.4.1.311.60.2.1.3=US, OID.2.5.4.15=Private Organization
Non-root Certificate
Cert Hash(sha1): ec2ae51775f3252541b266c40528daa77baa072f

Certificate "Insecure.Com LLC" already in store.
CertUtil: -addstore command completed successfully.
Delete file: C:\Users\mae\AppData\Local\Temp\nsi890E.tmp\Insecure-EV.cer
Npcap driver cache in Driver Store has been successfully cleaned up!
The cache in driver store was cleared
Npcap WFP callout driver has been successfully installed!
Npcap LWF driver (with Wi-Fi support) has been successfully installed!
The npcap service for Win7, Win8 and Win10 was successfully created
Npcap WFP callout driver has been successfully installed!
Npcap LWF driver (with Wi-Fi support) has been successfully installed!
The npf service for Win7, Win8 and Win10 was successfully created
Writing service options to registry
Identify the wireless adapters and write them into the registry
Wlan adapters have been successfully written to registry!
Installing Npcap Loopback Adapter
Npcap Loopback adapter has been successfully installed!
Starting the npf driver
The requested service has already been started.

More help is available by typing NET HELPMSG 2182.

The Npcap Packet Driver (NPF) service was stopped successfully.

The Npcap Packet Driver (NPF) service was started successfully.

Starting the npcap driver
System error 2 has occurred.

The system cannot find the file specified.

The Npcap Packet Driver (NPCAP) service is not started.

More help is available by typing NET HELPMSG 3521.

System error 2 has occurred.

The system cannot find the file specified.

Output folder: C:\Program Files\Npcap
Extract: CheckStatus.bat
SUCCESS: The scheduled task "npcapwatchdog" has successfully been created.
Completed

**Comment by dmiller-nmap** [comment]
Thanks for the bug report. We're tracking "System error 2" problems at #1944.
