### ISSUE TITLE
Npcap Bug Report : Poor reception performance

### ISSUE THREAD

**Issue by Vincent1962** [nmap/nmap#1610]
Hi
I am trying to use npcap to send orders to a card and receive its answers. I work in raw. No IP protocol. My own protocol.
The response to a command takes 0.2ms, but the minimum 1ms timeout of pcap_open_live slows me down to 1000 Hz.
But sometimes the reception time lengthens to some ms.
For example:
Visual Studio 2017 is open. I recompile my projects dll and exe in release win32. I go to my output directory. I run my test programs and the results are good: 1000 Hz.
I'm closing Visual Studio 2017 now. I'm doing a test again and the result is bad 15 Hz.
I do not see any explanation.

Otherwise I would like a pcap_open_live opening with a timeout of 0 ms.
I hope to hear from you.
cordially
Vincent1962

**Comment by dmiller-nmap** [comment]
The pcap API lets you set "immediate mode" which causes any packets to be delivered as soon as they arrive, with no buffering. To accomplish this, replace `pcap_open_live()` with a call to [`pcap_create()`](https://nmap.org/npcap/guide/wpcap/pcap_create.html). Set immediate mode with [`pcap_set_immediate_mode()`](https://nmap.org/npcap/guide/wpcap/pcap_set_immediate_mode.html), and then activate the handle with [`pcap_activate()`](https://nmap.org/npcap/guide/wpcap/pcap_activate.html).

Please let us know if this addresses your concern.

**Comment by Vincent1962** [comment]
Perfect !
Thanks very much
