### ISSUE TITLE
npcap bluescreens the pc when trying to uninstall it or interact with it at all

### ISSUE THREAD

**Issue by flamedbaby** [nmap/nmap#1613]
Version is 0.995

Cannot uninstall it as doing so immediately causes a BSOD.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is a known issue with the previously-installed version of Npcap, which needs to be disabled before attempting the upgrade. A simple procedure for doing this can be found [in this comment on #1598](https://github.com/nmap/nmap/issues/1598#issuecomment-493827123).

Duplicate of #1598.
