### ISSUE TITLE
mass/async reverse DNS resolution is not case-insensitive

### ISSUE THREAD

**Issue by richardschuetz** [nmap/nmap#1622]
Reverse DNS resolution in nmap fails if the PTR name in the DNS response's answer section is not all lower case (e.g. `52.0.2.10.IN-ADDR.ARPA` instead of `52.0.2.10.in-addr.arpa`). DNS labels should be treated case-insensitive.

**Comment by dmiller-nmap** [comment]
I'm sorry I did not remember this issue and PR. We had the issue re-reported in #2068, and I took action on that. I will add your name to the credit in the changelog since you reported this earlier.
