### ISSUE TITLE
RHEL's versioning and backporting

### ISSUE THREAD

**Issue by aidylewis** [nmap/nmap#1623]
I believe RedHat provides versions when the RPM came out. So even though Apache httpd 2.4.6 is riddled with CVES and is installed on CentOS 7, security patches may have been backported from the last stable version of 2.4.39. Nmap is providing the version 2.4.6 as RedHat have not updated a minor version number and I am likely giving a number of false positives. Is there any alternative than a user of the box to login and examine change logs (which is not going to happen right)?

**Comment by nnposter** [comment]
You are correct. Most security scanners have solved this problem by implementing so-called "authenticated scans", where they are not just scraping port banners but also establishing shell access and inspecting installed packages. Short of implementing the same functionality, nmap cannot really provide reliable results.

**Comment by aidylewis** [comment]
Does anyone think backporting and not incrementing a minor version number to be an acceptable practice?

**Comment by aidylewis** [comment]
The above comment seems a little angry, it didn't mean to be. There is some information about backporting here: https://access.redhat.com/security/updates/backporting/, and I wonder if we could make nmap OVAL-compatible through the NSE?

**Comment by nnposter** [comment]
It depends what you mean by "compatible". It certainly appears feasible to use its SSH capability to run `oscap`, collect the XML output, and produce a distilled output. One minor nuisance is that NSE currently has no XML parser but it is not a showstopper.

**Comment by aidylewis** [comment]
Closing this as we have oscap as @nnposter suggested. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sect-using_oscap. I will speak to the RHEL Techical Account Manager. My opinion would be a backport offering a minor version incrment upon port grabbing.  But this is *not* an nmap issue.

**Comment by dmiller-nmap** [comment]
@nnposter NSE has an XML parser in the [`slaxml` library](https://nmap.org/nsedoc/lib/slaxml.html). But OVAL compatibility is a separate issue, so we'll keep this one closed and let anyone who wants that feature open a new issue.

**Comment by aidylewis** [comment]
I think I will have a go at this and pretty print to the console. Is there someone who specifically reviews and accepts NSE scripts?

**Comment by aidylewis** [comment]
Closing for new issue
