### ISSUE TITLE
tls-alpn nse script loop bug

### ISSUE THREAD

**Issue by fordpref** [nmap/nmap#1625]
similar to this bug: https://github.com/nmap/nmap/issues/1330

I'm running nmap 7.7 on Kali, updated yesterday (2019.06.06).

I have two systems I am scanning with -d1 that are stuck in this loop with no way to break out of the loop without killing the scan.

Per the previous report, there was a fix in May of 2018:  https://github.com/nmap/nmap/commit/3b8b6516a7697d8b6d4cd87e253daa369fcdbf2a#diff-ba642420e50ee44c73b3d13d5ea29cc9

so just curious if this got reverted in some way or if it is a new bug.

**Comment by cnotin** [comment]
Kali ships with the latest Nmap release, which is 7.70. It was released in March 2018 and therefore do not contain the fix you mentioned...
If you really need the fix and do not want to wait, I suggest you to compile Nmap yourself or to replace the NSE file with the latest version (hoping that it does not rely on an update in another file) :)

**Comment by dmiller-nmap** [comment]
Fix released in Nmap 7.80
