### ISSUE TITLE
check showing OPTIONS allowed when blocked

### ISSUE THREAD

**Issue by marckranat** [nmap/nmap#1627]
check showing HTTP OPTIONS allowed when really blocked (7.7 on MAC OSX)

<code>$ nmap -v --open -p 80 --script=http-methods 300m.com</code>
shows
<code>PORT   STATE SERVICE
80/tcp open  http
| http-methods: 
|_  Supported Methods: GET HEAD POST OPTIONS</code>

<code>$ curl -i -X OPTIONS https://300m.com </code>
shows <code>HTTP/2 403 </code>

**Comment by nnposter** [comment]
You do realize that in your example nmap is used against port 80, while curl is accessing 443, right?
```
root@kali:~# curl -i -X OPTIONS http://300m.com
HTTP/1.1 301 Moved Permanently
Server: Sucuri/Cloudproxy
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
X-Sucuri-ID: 20003
Location: https://300m.com/
```
```
root@kali:~# curl -i -X OPTIONS https://300m.com
HTTP/2 403 
server: nginx
content-type: text/html
x-sucuri-id: 20003
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
strict-transport-security: max-age=31536000
content-security-policy: upgrade-insecure-requests;
referrer-policy: no-referrer-when-downgrade
x-sucuri-block: MET043
```

**Comment by marckranat** [comment]
yes, it was intentional, not to mislead,
<code>$ nmap -v --open -p 443 --script=http-methods 300m.com</code>
returns no method, just
<code>PORT    STATE SERVICE
443/tcp open  https</code>
a curl to http gives the expected 301 as there is a redirect for the entire site.

**Comment by nnposter** [comment]
Your original concern was that that nmap is reporting supported methods on port 80 while curl has shown `OPTIONS` being blocked on port 443.  When correcting the port, nmap is not reporting the same methods so it is consistent with curl. I guess I am then missing your point.

**Comment by marckranat** [comment]
but the NMap scan of port 443 shows no methods, but GET HEAD POST are allowed. If you consider this a non issue, please close.

**Comment by nnposter** [comment]
Your server seems to reject requests that do not include HTTP header `Accept-Encoding` (which nmap does not provide).

**Comment by marckranat** [comment]
thank you, that explains it

**Comment by nnposter** [comment]
On top of it, the server does not like nmap `User-Agent` string.

I have modified the script (`http-methods`) to use Firefox-like `User-Agent` and to add `Accpet-Encoding`:
```
PORT   STATE SERVICE REASON
443/tcp open  http    syn-ack ttl 64
| http-methods:
|_  Supported Methods: GET HEAD POST
```
