### ISSUE TITLE
VS2019编译问题

### ISSUE THREAD

**Issue by kouzhudong** [nmap/nmap#1629]
1>------ 已启动生成: 项目: nbase, 配置: Debug Win32 ------
2>------ 已启动生成: 项目: zlibvc, 配置: Debug Win32 ------
3>------ 已启动生成: 项目: libpcre, 配置: Debug Win32 ------
4>------ 已启动生成: 项目: libdnet-stripped, 配置: Debug Win32 ------
5>------ 已启动生成: 项目: liblua, 配置: Debug Win32 ------
6>------ 已启动生成: 项目: libnetutil, 配置: Debug Win32 ------
7>------ 已启动生成: 项目: liblinear, 配置: Debug Win32 ------
8>------ 已启动生成: 项目: zlibstat, 配置: Debug Win32 ------
1>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
2>Microsoft (R) Macro Assembler Version 14.21.27702.2
2>Copyright (C) Microsoft Corporation.  All rights reserved.
2>
2> Assembling: match686.asm
2>Microsoft (R) Macro Assembler Version 14.21.27702.2
2>Copyright (C) Microsoft Corporation.  All rights reserved.
2>
2> Assembling: inffas32.asm
2>adler32.c
1>strcasecmp.c
3>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
3>pcreposix.c
6>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
6>UDPHeader.cc
8>adler32.c
3>pcre_xclass.c
1>snprintf.c
3>pcre_version.c
3>pcre_valid_utf8.c
7>daxpy.c
7>ddot.c
7>dnrm2.c
7>dscal.c
3>pcre_ucp_searchfuncs.c
2>compress.c
3>pcre_try_flipped.c
7>正在生成代码...
1>nbase_winunix.c
3>pcre_tables.c
3>pcre_study.c
8>compress.c
3>pcre_refcount.c
3>pcre_ord2utf8.c
3>pcre_newline.c
7>linear.cpp
2>crc32.c
1>nbase_time.c
3>pcre_maketables.c
3>pcre_info.c
6>TransportLayerElement.cc
7>tron.cpp
3>pcre_globals.c
7>正在生成代码...
7>liblinear.vcxproj -> E:\git\nmap\liblinear\.\liblinear.lib
8>crc32.c
8>deflate.c
8>gzclose.c
8>gzlib.c
3>pcre_get.c
3>pcre_fullinfo.c
3>pcre_exec.c
3>pcre_dfa_exec.c
3>pcre_config.c
3>pcre_compile.c
3>正在生成代码...
3>正在编译...
3>pcre_chartables.c
1>nbase_str.c
1>nbase_rnd.c
1>nbase_misc.c
1>nbase_memalloc.c
5>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
5>lzio.c
5>lvm.c
5>lutf8lib.c
5>lundump.c
5>ltm.c
5>ltablib.c
5>ltable.c
5>lstrlib.c
5>lstring.c
5>lstate.c
5>lparser.c
5>loslib.c
5>lopcodes.c
5>lobject.c
5>loadlib.c
5>lmem.c
5>lmathlib.c
5>llex.c
5>liolib.c
5>linit.c
5>正在生成代码...
4>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
4>strsep.c
4>strlcpy.c
4>strlcat.c
4>route-win32.c
4>ip6.c
4>ip-win32.c
4>ip-util.c
4>intf-win32.c
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1933,1): warning C4005:  “snprintf”: 宏重定义
4>E:\git\nmap\libdnet-stripped\include\dnet_winconfig.h(280): message :  参见“snprintf”的前一个定义
4>eth-win32.c
2>deflate.c
2>Assembler code may have bugs -- use at your own risk
2>gzclose.c
2>gzlib.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>TCPHeader.cc
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>RoutingHeader.cc
1>nbase_addrset.c
3>正在生成代码...
5>正在编译...
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1935,1): error C1189:  #error:  Macro definition of snprintf conflicts with Standard Library function declaration
4>err.c
5>lgc.c
5>lfunc.c
5>ldump.c
5>ldo.c
5>ldebug.c
2>gzread.c
5>ldblib.c
1>inet_pton.c
5>lctype.c
3>libpcre.vcxproj -> E:\git\nmap\libpcre\.\libpcre.lib
5>lcorolib.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
5>lcode.c
5>lbitlib.c
6>RawData.cc
8>gzread.c
5>lbaselib.c
5>lauxlib.c
4>arp-win32.c
5>lapi.c
1>inet_ntop.c
5>正在生成代码...
2>gzwrite.c
5>E:\git\nmap\liblua\lapi.c(398,49): warning C4244:  “return”: 从“lua_Unsigned”转换到“size_t”，可能丢失数据
4>addr.c
8>gzwrite.c
1>getopt.c
1>正在生成代码...
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>PacketParser.cc
4>E:\git\nmap\libdnet-stripped\src\eth-win32.c(24,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1933,1): warning C4005:  “snprintf”: 宏重定义
4>E:\git\nmap\libdnet-stripped\include\dnet_winconfig.h(280): message :  参见“snprintf”的前一个定义
4>addr-util.c
5>liblua.vcxproj -> E:\git\nmap\liblua\.\liblua.lib
5>已完成生成项目“liblua.vcxproj”的操作。
2>infback.c
8>infback.c
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1935,1): error C1189:  #error:  Macro definition of snprintf conflicts with Standard Library function declaration
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1933,1): warning C4005:  “snprintf”: 宏重定义
4>E:\git\nmap\libdnet-stripped\include\dnet_winconfig.h(280): message :  参见“snprintf”的前一个定义
4>正在生成代码...
1>nbase.vcxproj -> E:\git\nmap\nbase\.\nbase.lib
9>------ 已启动生成: 项目: nsock, 配置: Debug Win32 ------
10>------ 已启动生成: 项目: nmap-update, 配置: Debug Win32 ------
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h(1935,1): error C1189:  #error:  Macro definition of snprintf conflicts with Standard Library function declaration
2>inffast.c
4>已完成生成项目“libdnet-stripped.vcxproj”的操作 - 失败。
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
10>nmap-update.c
6>PacketElement.cc
9>proxy_socks4.c
8>inffast.c
2>Assembler code may have bugs -- use at your own risk
2>inflate.c
8>inflate.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>proxy_http.c
6>NetworkLayerElement.cc
10>svn_auth.c
10>E:\git\nmap\nmap-update\nmap-update.c(33,10): error C1083:  无法打开包括文件: “svn_client.h”: No such file or directory
10>正在生成代码...
10>E:\git\nmap\nmap-update\svn_auth.c(46,10): error C1083:  无法打开包括文件: “svn_client.h”: No such file or directory
10>已完成生成项目“nmap-update.vcxproj”的操作 - 失败。
2>inftrees.c
8>inftrees.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
6>netutil.cc
2>ioapi.c
9>nsock_write.c
8>ioapi.c
2>iowin32.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
8>trees.c
6>IPv6Header.cc
9>nsock_timers.c
2>trees.c
8>uncompr.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
6>IPv4Header.cc
9>nsock_ssl.c
2>uncompr.c
8>unzip.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
2>unzip.c
6>ICMPv6RRBody.cc
9>nsock_read.c
8>zip.c
2>zip.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
8>zutil.c
6>ICMPv6Option.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>nsock_proxy.c
2>zutil.c
8>正在生成代码...
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>ICMPv6Header.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>nsock_pool.c
2>正在生成代码...
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>ICMPv4Header.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
2>E:\git\nmap\libz\contrib\minizip\iowin32.c(31,32): warning C4067:  预处理器指令后有意外标记 - 应输入换行符
9>nsock_pcap.c
8>zlibstat.vcxproj -> E:\git\nmap\libz\contrib\vstudio\vc12\x86\ZlibStatDebug\zlibstat.lib
2>match686.obj : error LNK2026: 模块对于 SAFESEH 映像是不安全的。
2>inffas32.obj : error LNK2026: 模块对于 SAFESEH 映像是不安全的。
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
2>  正在创建库 x86\ZlibDllDebug\zlibwapi.lib 和对象 x86\ZlibDllDebug\zlibwapi.exp
6>HopByHopHeader.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
2>x86\ZlibDllDebug\zlibwapi.dll : fatal error LNK1281: 无法生成 SAFESEH 映像。
2>已完成生成项目“zlibvc.vcxproj”的操作 - 失败。
11>------ 已启动生成: 项目: libssh2, 配置: Debug Win32 ------
9>nsock_log.c
11>cl: 命令行 warning D9035 :“Gm”选项已否决，并将在将来的版本中移除
11>cl: 命令行 error D8016 :“/ZI”和“/Gy-”命令行选项不兼容
11>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: “CL.exe”已退出，代码为 2。
11>已完成生成项目“libssh2.vcxproj”的操作 - 失败。
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>FragmentHeader.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>nsock_iod.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>EthernetHeader.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>nsock_event.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
6>DestOptsHeader.cc
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>nsock_engines.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
6>ARPHeader.cc
9>nsock_core.c
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
6>正在生成代码...
6>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
9>nsock_connect.c
6>已完成生成项目“libnetutil.vcxproj”的操作 - 失败。
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>netutils.c
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>gh_heap.c
9>filespace.c
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>error.c
9>engine_select.c
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>正在生成代码...
9>正在编译...
9>engine_poll.c
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>engine_kqueue.c
9>engine_iocp.c
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>engine_epoll.c
9>正在生成代码...
9>E:\git\nmap\nsock\src\nsock_ssl.h(69,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
9>已完成生成项目“nsock.vcxproj”的操作 - 失败。
12>------ 已启动生成: 项目: nmap, 配置: Debug Win32 ------
13>------ 已启动生成: 项目: ncat, 配置: Debug Win32 ------
14>------ 已启动生成: 项目: nping, 配置: Debug Win32 ------
13>Copying ca-bundle.crt to output directory...
12>Copying nmap-mac-prefixes to output directory...
14>ArgParser.cc
13>base64.c
12>Copying nmap-os-db to output directory...
12>Copying nmap-payloads to output directory...
12>Copying nmap-protocols to output directory...
12>Copying nmap-rpc to output directory...
12>Copying nmap-service-probes to output directory...
12>Copying nmap-services to output directory...
12>Copying nmap.xsl to output directory...
12>charpool.cc
14>common.cc
13>http.c
12>FingerPrintResults.cc
13>http_digest.c
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>common_modified.cc
12>FPEngine.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>Crypto.cc
13>ncat_connect.c
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>FPmodel.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>ncat_core.c
14>EchoClient.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>idle_scan.cc
13>ncat_exec_win.c
14>EchoHeader.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
12>MACLookup.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>ncat_listen.c
14>EchoServer.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
14>NEPContext.cc
13>ncat_lua.c
12>main.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
13>ncat_main.c
14>nping.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>ncat_proxy.c
12>NewTargets.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>NpingOps.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>ncat_ssl.c
13>E:\git\nmap\ncat\util.h(146,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>ncat_win.c
12>nmap.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>NpingTarget.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>sys_wrap.c
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>NpingTargets.cc
13>E:\git\nmap\ncat\ncat.h(138,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>util.c
13>E:\git\nmap\ncat\util.h(146,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>正在生成代码...
13>E:\git\nmap\ncat\util.h(146,10): error C1083:  无法打开包括文件: “openssl/ssl.h”: No such file or directory
13>已完成生成项目“ncat.vcxproj”的操作 - 失败。
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>output.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>ProbeMode.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>stats.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nmap_dns.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nmap_error.cc
12>nmap_ftp.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>utils.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nmap_tty.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>utils_net.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>winfix.cc
12>NmapOps.cc
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>正在生成代码...
14>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
14>已完成生成项目“nping.vcxproj”的操作 - 失败。
12>NmapOutputTable.cc
12>nse_debug.cc
12>nse_fs.cc
12>nse_libssh2.cc
12>nse_lpeg.cc
12>nse_main.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>正在生成代码...
12>正在编译...
12>nse_utility.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nse_nmaplib.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nse_nsock.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nse_dnet.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nse_openssl.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>nse_pcrelib.cc
12>nse_ssl_cert.cc
12>E:\git\nmap\nse_openssl.cc(9,10): error C1083:  无法打开包括文件: “openssl/bn.h”: No such file or directory
12>nse_zlib.cc
12>osscan.cc
12>E:\git\nmap\nse_ssl_cert.cc(142,10): error C1083:  无法打开包括文件: “openssl/bn.h”: No such file or directory
12>osscan2.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>output.cc
12>E:\git\nmap\osscan2.h(137,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>payload.cc
12>portlist.cc
12>E:\git\nmap\osscan2.h(137,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>portreasons.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>protocols.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>scan_engine.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>scan_engine_connect.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>scan_engine_raw.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>scan_lists.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>service_scan.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>正在生成代码...
12>正在编译...
12>services.cc
12>Target.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>TargetGroup.cc
12>E:\git\nmap\libnetutil\netutil.h(142,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>targets.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>tcpip.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>timing.cc
12>traceroute.cc
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>utils.cc
12>xml.cc
12>winfix.cc
12>E:\git\nmap\osscan2.h(137,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>正在生成代码...
12>E:\git\nmap\tcpip.h(140,10): error C1083:  无法打开包括文件: “pcap.h”: No such file or directory
12>已完成生成项目“nmap.vcxproj”的操作 - 失败。
========== 生成: 成功 5 个，失败 9 个，最新 0 个，跳过 0 个 ==========

**Comment by dmiller-nmap** [comment]
谢谢! Thanks for trying out Nmap. When building Nmap on Windows, please refer to [the online documentation for building Nmap from source on Windows](https://nmap.org/book/inst-windows.html#inst-win-source). The required headers are available in the `nmap-mswin32-aux` repository on `svn.nmap.org`.
