### ISSUE TITLE
Npcap 802.1x authentication - causes wireless disconnect

### ISSUE THREAD

**Issue by catchonsuccess** [nmap/nmap#1631]
Hello,

Our software uses npcap, and we have tied it into our installation. We have found that if a windows machines uses 802.1x authentication, then the installation of npcap disconnects and causes the user to need to manually reconnect. Is this a known issue or something that can be reviewed? Thank you.

**Comment by dmiller-nmap** [comment]
Thanks for the report. We are tracking progress on this issue at #1658. Closing this one as a duplicate for now.
