### ISSUE TITLE
replacement of md5 on SHA256

### ISSUE THREAD

**Issue by kraczynski** [nmap/nmap#1644]
I noticed that in the command results

**`# nmap -A -T4 192.168.1.1-255`**

I get as a result:

```
map scan report for 192.168.1.23
Host is up (0.022s latency).
Not shown: 999 closed ports
PORT STATE SERVICE VERSION
22 / tcp open ssh (protocol 2.0)
| Fingerprint-strings:
| NULL:
| _ SSH-2.0-OpenSSH_7.4p1 Raspbian-10 + deb9u6
| ssh-hostkey:
| _ 256 3a: 48: 2f: 01: 22: 17: 9b: c5: 03: e2: a7: ab: 04: 62: 23: f4 (ED25519)
1 service unrecognized despite returning data. If you know the service / version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service:
SF-Port22-TCP: V = 7.70% I = 7% D = 6/10% Time = 5CFE0B0D% P = x86_64-pc-Gnu-Linux% r (NULL
SF: 29 "SSH-2 \ .0-OpenSSH_7 \ .4p1 \ x20Raspbian-10 \ + deb9u6 \ n");
```

I have a question for ssh-hostkey because it is given in 
**md5 256 3a: 48: 2f: 01: 22: 17: 9b: c5: 03: e2: a7: ab: 04: 62: 23: f4 (ED25519)**
more and more often, however, another representation 
of **256 SHA256 is used: / Ez9WX5xyX8QAwx1GTyJ0QZbq7Q2O0DWl6YPbe5vWU8**
Maybe it's worth changing in program?

**Comment by nnposter** [comment]
Please give [this patch](https://gist.github.com/nnposter/dd35b0b86c02fdecf8af19e3735e2784) a spin and report back.
```
$ nmap -p22 --script ssh-hostkey 192.168.1.1
Starting Nmap 7.70SVN ( https://nmap.org ) at 2019-06-25 17:54 MDT
Nmap scan report for 192.168.1.1
Host is up (0.0023s latency).

PORT   STATE SERVICE
22/tcp open  ssh
| ssh-hostkey: 
|   2048 a9:c0:de:b2:c0:18:22:ab:8d:29:32:61:94:33:0b:8b (RSA)
|   256 0a:66:67:d0:b7:66:e6:91:4a:d7:de:b1:2a:b4:a7:2a (ECDSA)
|_  256 2e:ab:83:47:5a:3d:f2:79:67:3a:db:d4:6c:90:dd:d7 (ED25519)

Nmap done: 1 IP address (1 host up) scanned in 0.62 seconds

$ nmap -p22 --script ssh-hostkey --script-args ssh_hostkey=sha256 192.168.1.1
Starting Nmap 7.70SVN ( https://nmap.org ) at 2019-06-25 17:54 MDT
Nmap scan report for 192.168.1.1
Host is up (0.0024s latency).

PORT   STATE SERVICE
22/tcp open  ssh
| ssh-hostkey: 
|   2048 SHA256:FJvJJOc7obQZM8rNY/mCu469CzH08BPEL+2jmN3BFgM (RSA)
|   256 SHA256:Bvt/7CzrQGAQel3G6Ovz8BhgFPVuHE9f2vqCQBax7Bw (ECDSA)
|_  256 SHA256:EJl3s9xdBCuzJy03Dkbqa5HeZBR9D2x7nZwRn/BImZ0 (ED25519)

Nmap done: 1 IP address (1 host up) scanned in 0.63 seconds
```

**Comment by dmiller-nmap** [comment]
I agree this format should be supported. I will add it as an additional fingerprint format, controlled by the [`ssh_hostkey` script arg](https://nmap.org/nsedoc/scripts/ssh-hostkey.html). I think in the future we may make this the default format instead of MD5, but I'd rather not make that change right away.

**Comment by nnposter** [comment]
@dmiller-nmap Have you looked at the patch above?

**Comment by dmiller-nmap** [comment]
@nnposter Haha, we stumbled over each other to get this one done! It's amazing how closely your code resembles mine, though I did make a few more changes to the script as a whole in subsequent commits.
