### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by JMRexach** [nmap/nmap#1645]
Npcap 0.996 fails with Intel N7260: Neither waiting 90 seconds neither disabling and enabling the adaptor works. Win 10 pro 64 bit version 1903. It's a refurbished pc, so I don't have any previous experience on it. Intel controller version 18.13.17.1.
Any suggestion?

Thks,

JMa

**Comment by JMRexach** [comment]
SOLVED,
The trouble was in driver installation. The device mgr reported version 18.33.17.1 of the Intel driver but the file was v. 18.33.14.3. Reinstalling driver solved it.
Now it seems to work fine also in monitor mode.
Thks at all.
JMa

**Comment by dmiller-nmap** [comment]
@JMRexach I'm glad you found a solution. Since you say Npcap now works in monitor mode, could you help us out with a little information? Many drivers are not compatible with Npcap's raw 802.11 frame capture, so we are trying to document which ones may be over at https://secwiki.org/w/Npcap/WiFi_adapters . Could you provide answers to the questions in the "How to help" section as a comment here so we can update our documentation? Thanks!

**Comment by JMRexach** [comment]
Hi,

I were too optimistic!

Really the Npcap allows monitor mode and Wireshark shows the checkbox in the interfaces list for enable it but no traffic is captured. Versions list:

 

Wireshark 3.0.2

Npcap 0.96

Adapter Intel N7260 dual band

Driver Intel version 18.33.17.1

Win10 pro 64 bit.

 

Windows takes some time (30 sec aprox)  starting wifi adapter after a reboot.

 

I hope that this help you.

 

BR.

 

@JMRexach

 

 

De: Daniel Miller [mailto:notifications@github.com] 
Enviado el: lunes, 24 de junio de 2019 18:12
Para: nmap/nmap <nmap@noreply.github.com>
CC: JMRexach <jmrexach@telefonica.net>; Mention <mention@noreply.github.com>
Asunto: Re: [nmap/nmap] Npcap Bug Report (#1645)

 

@JMRexach <https://github.com/JMRexach>  I'm glad you found a solution. Since you say Npcap now works in monitor mode, could you help us out with a little information? Many drivers are not compatible with Npcap's raw 802.11 frame capture, so we are trying to document which ones may be over at https://secwiki.org/w/Npcap/WiFi_adapters . Could you provide answers to the questions in the "How to help" section as a comment here so we can update our documentation? Thanks!
