### ISSUE TITLE
ssl-cert not working on port different than 443

### ISSUE THREAD

**Issue by adon90** [nmap/nmap#1653]
It seems ssl-cert doesn't work fine when port is not 443 or SERVICE is not https, in these cases, I cannot get the certificate even though it works with openssl s_client.
I can't do `nmap -sS -p443,6001,7001,7002,8001,8080,9090,9001,9002,8443,4443,8002 -Pn --script ssl-cert <ip>` and expect obtaining the CommonName in any of these ports, unless it has ssl on 443. 
It seems it works if I use -sV though
` nmap -sS --open -p443,6001,7001,7002,8001,8080,9090,9001,9002,8443,4443,8002 -Pn -sV --script ssl-cert <ip>`
How to work it out? Thanks

**Comment by nnposter** [comment]
Nmap runs a given script against a given port only if it believes that a corresponding protocol is likely on it. As an example, TLS/SSL scripts will be run against port 443, 993, 995, etc., but not 80 or 22.

You have two options to make the script run against the other ports: Either run Nmap with `-sV`, which will cause it to detect TLS on the other ports, in turn knowing that `ssl-cert` should be run. Alternatively, if you do not want to go through the rather heavy version detection, you can force a script to run against *any* port by prefixing the script with a plus sign:
```
nmap -sS --open -p443,6001,7001,7002,8001,8080,9090,9001,9002,8443,4443,8002 -Pn -sV --script +ssl-cert <ip>
```

**Comment by adon90** [comment]
The "+" option is very nice, thank you very much!!

**Comment by vmukhachev** [comment]
it is still does not work at least for --script +http-security-headers
