### ISSUE TITLE
[npcap] Issue with reboot/hibernate/uninstall/taskmanager in npcap 0.996

### ISSUE THREAD

**Issue by samcook** [nmap/nmap#1664]
Hi,

I recently installed Wireshark 3.0.2 (including npcap 0.995) and began having the following issues:
- reboot/hibernate would hang and eventually fail
- task manager would hang after one "refresh" (no network details visible on the "Performance" tab either)
- unable to uninstall npcap (stuck on stopping the service)

It seems that some or all of these are known issues in 0.995, and I was eventually able to remove npcap by first disabling the `npcap` service as noted in #1626 and #1598.

Without npcap installed the issues above are resolved, however on installing 0.996 the problems have returned.

[DiagReport-20190723-125212.txt](https://github.com/nmap/nmap/files/3421972/DiagReport-20190723-125212.txt)
[install.log](https://github.com/nmap/nmap/files/3421974/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/3421976/NPFInstall.log)

**Comment by fyodor** [comment]
It looks like nobody was able to specifically address your issue in the last 9 months, but we have made many improvements in Npcap since then and I hope they have fixed your problem.  If you still experience the issue with Npcap version 0.9991 or newer, please refile.  Thanks!
