### ISSUE TITLE
npcap 09981 install problem

### ISSUE THREAD

**Issue by Patsjemoe** [nmap/nmap#1667]
Hi,
when trying to install, I get following error : 
Cannot get access to give device, path or file. Possibly you do not have the right authority for the item.
I tried to install with administrator, also no succes.
Avast virusscanner regards it as dangerous.
How to solve ?
Note : using0995 and  0996 in wireshark does not work, no interfaces found.
Regards
Ludo

**Comment by dmiller-nmap** [comment]
Thanks for the report. Can you provide the `install.log` and `NPFInstall.log` files from the Npcap installation directory (usually `C:\Program Files\Npcap\`)? Thanks.

**Comment by Patsjemoe** [comment]
Hi Daniel,
thanks for your quick feedback.

attached the files.

Luckaly, these 2 files were still there, as I uninstalled it, and
re-installed WinPcap....this works.

I tried several times with 0.995, 0.996, 09981

regards
Ludo

**Comment by dmiller-nmap** [comment]
@Patsjemoe The email interface to Github Issues doesn't allow attaching files. You have to log in to the web interface and attach them in the comment box. Alternatively, you could send them directly to dmiller@nmap.com.

**Comment by Patsjemoe** [comment]
Have sent the files.
Any news ?

**Comment by mesteele101** [comment]
This same issue is happening with Snort. Reported with 0.9981 and 0.9982 was released with no fix...

**Comment by Patsjemoe** [comment]
Hi Daniel,
I sent you the files,
any news to solve the issue ?

**Comment by Patsjemoe** [comment]
I just wonder why someone asks to send files, and then drops to complete silence...

**Comment by fyodor** [comment]
Hi @Patsjemoe.  We are working on dozens of issues at any given time.  We need the files in order for the report to be complete enough that we can try to find time to work on it, but that doesn't mean we will drop everything else and work on it immediately.  We prioritize reports based on severity, how many people are reporting the issue, whether we have any leads on what might be the problem, etc.

**Comment by Patsjemoe** [comment]
Hi,
For me no more needs on this subject anymore  ....

Op do 5 sep. 2019 02:20 schreef Fyodor <notifications@github.com>:

**Comment by Patsjemoe** [comment]
Hi Daniel,
What I ment was that I actually use the solution that I have, and will see
when the  npcap issue will be solved. Just let me know when it is ok.....

Op do 5 sep. 2019 06:15 schreef Ludo Kustermans <ludo.kustermans@gmail.com>:
