### ISSUE TITLE
Npcap 0.9982 Failing!

### ISSUE THREAD

**Issue by mesteele101** [nmap/nmap#1677]
Npcap for Windows is not working with Snort. The last version that worked correctly with Snort was 0.996...

Problem was previously reported. To test just install Npcap and Snort, then try and list available adaptors using **snort -W**. The list is empty :(

**Comment by dmiller-nmap** [comment]
Can you please point us to the code within snort that uses Npcap to list adapters? We changed some internal APIs after 0.996, but they were not published APIs and are not guaranteed to be stable.

**Comment by mesteele101** [comment]
In the past I used WinPcap for at least 10+ years. I didn’t know there was an alternative to WinPcap until a few months back when I started using Npcap 0.996

 

As far as I know Snort does not directly summon Npcap. They may be summoning something to do with WinPcap?

**Comment by yyjdelete** [comment]
@mesteele101 
Maybe you can replace `Packet.dll` and `wpcap.dll` in `Snort\bin` with the ones from `C:\Windows\SysWOW64\Npcap`?

**Comment by mesteele101** [comment]
Those files come with the Snort install, and WinPcap is also a required install, but we were installing Npcap instead.

 

There was a programming change from Npcap 0.996 that caused Npcap to not work with Snort just by installing it. The programmers need to figure out what they did to break Npcap instead of hacking it to work with Snort.

 

I have no idea if swapping those files will fix it, but you can easily try it out. Install Snort, install Npcap, move the files mentioned, and then from a command prompt type c:\snort\bin\snort –W

 

If you get a list of interfaces it does work, but I highly doubt it?

 

Michael…

**Comment by yyjdelete** [comment]
@mesteele101 
It works (`WanPacket.dll` and `npptools.dll` is no longer needed)
![image](https://user-images.githubusercontent.com/1819074/62706044-42dd5780-ba21-11e9-9883-6237d9216c49.png)

I think it's described in https://github.com/nmap/npcap/releases/tag/v0.9981 . 
```
Redefine the I/O control codes used by Npcap using the CTL_CODE macro to
ensure proper access control and consistent parameter passing. This is not a
published API, but the change will require that Packet.DLL and the npcap
driver are the same version.
```


BTW: 
@dmiller-nmap
Seems there is another version of `Packet.dll`/`wpcap.dll` from `mingw32/64-wpcap`, which may be used to compile cross platform apps, which may also not works.
https://www.google.com/search?q=mingw64-wpcap
https://github.com/search?q=mingw64-wpcap&type=Code

**Comment by mesteele101** [comment]
Ok, so what exactly do I need to do to make Npcap 0.9981 work with Snort?

 

Thanks…

**Comment by mesteele101** [comment]
I’m not sure and it is confusing as to what works and what doesn’t. I don’t know how reliable Npcap is at this point working with Snort with anything past 0.996.

 

WanPacket is required to be present in the snort/bin folder or Snort won’t start.

 

I can work with Sourcefire on getting this all straightened out to reliably use Npcap but I need direction to a final solution.

 

Winpcap is not being maintained any longer and Sourcefire could be persuaded to opt-in to using Npcap instead for Windows.

 

I never removed the files from the snort/bin folder. I deleted the snort/bin/packet.dll file and Snort now lists the interfaces and shows traffic using the –V switch.

 

Is it a reliable solution to just delete the packet.dll file from the snort\bin folder if NpCap is going to be used instead of WinPcap?

**Comment by dmiller-nmap** [comment]
Yes, if Npcap is installed, it will have its own DLLs installed. However, in order to avoid conflicting with WinPcap, which uses the same DLL names, we elected to install its DLLs in a subdirectory of System32. Therefore, software that wishes to use Npcap should delay-load the DLL and add that subdirectory to the DLL search path before loading. This is the preferred method to avoid DLL-hell that comes with shipping your own copies of the DLL, which is what caused the breakage when the version became unsynchronized with the version of the Npcap driver installed.

If Npcap is installed in WinPcap API-compatible mode, software can just load wpcap.dll or packet.dll directly without modifying the search path, since they will be overwritten with the Npcap versions. This is probably how Snort is written already. Note that not all the new features of Npcap are supported in WinPcap API-compatible mode, even if they may work in current versions.

**Comment by dmiller-nmap** [comment]
@yyjdelete Thanks for the analysis. I'm not familiar with the mingw build, but we've known for a while that statically-built stuff or things shipping their own DLLs might be broken by some of the changes we're making. This is partly why we keep putting off the Npcap 1.0 release: we want to have a stable API that won't break things like this, but there are just too many great changes we want to make before then.

**Comment by mesteele101** [comment]
I think that in order for Snort to be reliable with Npcap yopu might need to consult with Sourcefire and see exactly what they are doing.

 

It would be fine with me if they discontinued supporting WinPcap if that is what they are doing, seeing it is a dead project. 

 

Joel Elser [jesler@cisco.com] should be able to direct you as to whom to consult with if interested?

 

Thanks...

 

I ran a list of adaptors with the results below. Not real sure what the output for 0.9982 means?

 

I'm assuming to use any version pre 0.996 taht the packet.dll file needs to be the only thing removed from the snort install?

 

The below is a list of adaptors from WinPcap

--------------------------------------------

 

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

 

C:\Users\Operator>d:\winids\snort\bin\snort -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reser

ved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

    1   00:0C:29:A5:39:2E       0000:0000:fe80:0000:0000:0000:094c:30b5 \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}      Intel(R) PRO/1000 MT Network Connection

 

 

The below is a list of adaptors from Npcap 0.669

------------------------------------------------

 

C:\Users\Operator>

 

Microsoft Windows [Version 6.1.7601]

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

 

C:\Users\Operator>d:\winids\snort\bin\snort -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reser

ved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

    1   00:0C:29:A5:39:2E       0000:0000:fe80:0000:0000:0000:094c:30b5 \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}      Intel(R) PRO/1000 MT Network Connection

 

C:\Users\Operator>

 

 

The below is a list of adaptors from Npcap 0.9982

-------------------------------------------------

 

C:\Users\Operator>d:\winids\snort\bin\snort -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reser

ved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

    1   00:00:00:00:00:00       disabled        \Device\NPF_NdisWanIp   NdisWan Adapter

    2   00:00:00:00:00:00       disabled        \Device\NPF_NdisWanBh   NdisWan Adapter

    3   00:0C:29:A5:39:2E       0000:0000:fe80:0000:0000:0000:094c:30b5 \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}      Intel(R) PRO/1000 MT Network Connection

    4   00:00:00:00:00:00       disabled        \Device\NPF_NdisWanIpv6 NdisWan Adapter

 

C:\Users\Operator>

**Comment by dmiller-nmap** [comment]
In the final analysis, the issue is caused by a version mismatch between the WinPcap version of Packet.DLL that is shipped with Snort and the Npcap driver API that is implemented by Npcap's own Packet.DLL. The solution is to remove wpcap.dll and Packet.dll from the executable path of Snort and either install Npcap in WinPcap API-compatible mode or modify Snort to call `SetDllDirectory` appropriately to find the Npcap DLLs [as described in the Npcap Developers' Guide](https://nmap.org/npcap/guide/npcap-devguide.html#npcap-feature-native).
