### ISSUE TITLE
can not downgrade to earlier version

### ISSUE THREAD

**Issue by cbwang505** [nmap/nmap#1686]
i installed npcap-0.9982 and run sharpcap i caught Exception: SharpPcap.PcapException: 'Unable to activate the adapter (rpcap://\Device\NPF_{DB15D668-E692-46D9-9A6F-FD6747CD11AD}). Return code: -1',when i  then uninstall it and install the npcap-0.991 still call the error,Exception: SharpPcap.PcapException: No interfaces found! Make sure libpcap/WinPcap is properly installed on the local machine.
   在 SharpPcap.WinPcap.WinPcapDeviceList.Devices(String rpcapString, RemoteAuthentication remoteAuthentication)
   在 SharpPcap.WinPcap.WinPcapDeviceList.GetDevices()
   在 SharpPcap.WinPcap.WinPcapDeviceList.Refresh()
   在 SharpPcap.WinPcap.WinPcapDeviceList..ctor()
   在 SharpPcap.WinPcap.WinPcapDeviceList.get_Instance()
   在 SharpPcap.CaptureDeviceList..ctor()
   在 SharpPcap.CaptureDeviceList.get_Instance()
   在 DeviceList.Program.Main(String[] args) 位置 E:\git\PeachProject\PeachAdmin\DeviceList\Program.cs:line 16
now i can not install any earlier version than npcap-0.9982 how to resovle this problem,in addtional i  uninstall  npcap and install winpcap instead of it , it works

**Comment by gsuberland** [comment]
I am also running into this same issue. 0.991 does not show any adapters at all (in SharpPcap or Wireshark), whereas 0.9982 shows adapters in Wireshark but no adapters can be opened in SharpPcap (same exception as OP).

**Comment by melon3r** [comment]
I'm having the same isue with npcap 0.9983. I upgraded from 0.991 to check if it'd work with SharpPcap, and after finding it doesn't, I can't go back.

**Comment by dmiller-nmap** [comment]
Npcap uninstallers prior to Npcap 0.9985 did not properly check for filesystem redirection on 64-bit Windows, so the `npcap.sys` file was not correctly deleted. Windows would therefore not overwrite it with a version that was older than the previously installed version, preventing a clean downgrade.

Npcap 0.9985 (soon to be released) can be safely downgraded to any other version. For downgrading from previous versions, you must manually delete the `%WINDIR%\System32\Drivers\npcap.sys` file after uninstalling and before installing the older version.
