### ISSUE TITLE
Where does gunzipping of man files occur

### ISSUE THREAD

**Issue by visrani** [nmap/nmap#1689]
Am trying to have 2 nmap versions on my system 6.40 and 7.70 for a temperory requirement. At this moment I cannot afford to upgrade entire nmap.

I have modified the part of the man docs that make way into
/usr/share/man/man1/something.1. gz
To
/usr/share/nmap7/man/man1/something.1. gz

The rpm is generated fine but what I get is
/usr/share/nmap7/man/man1/something.1

Somehow nmap is not able to gunzip the file because it has moved to a different location.

I couldn't trace from where exactly the tarball creation was taking place. Spent a lot of time but not able to crack it.

Need help.

**Comment by dmiller-nmap** [comment]
Are you using the RPM packages from https://nmap.org/download.html#linux-rpm ? This is a packaging issue and is very dependent on your OS distribution. Nmap itself does not modify or compress manual pages.

**Comment by visrani** [comment]
No am using  nmap-7.70.tar.bz2 tarball.
Extracting it on a centos6 box and trying to perform a configure and make

**Comment by dmiller-nmap** [comment]
Nmap's Makefile does not gzip the man page. That is being done by the packager for your distribution. You can change the location for installing the man pages by setting the `mandir` variable when invoking `make install`, or by changing the installation prefix when running `configure`. Beyond that, this is not something the Nmap team can help with.
