### ISSUE TITLE
Unable to find nmap-services!

### ISSUE THREAD

**Issue by M0dred** [nmap/nmap#1690]
Unable to find nmap-services!  Resorting to /etc/services

NSE: failed to initialize the script engine:
could not locate nse_main.lua
stack traceback:
	[C]: in ?

**Comment by gvanem** [comment]
The messy function `nmap_fetchfile()` is responsible for these steps. 
Try adding an env-var `NMAPDATADIR` pointing to the directory of `nmap-services` and `scripts/*.nse`.

**Comment by dmiller-nmap** [comment]
@M0dred How did you install Nmap? What is the path to the `nmap` binary and to the `nmap-services` file and `nse_main.lua`?

**Comment by dmiller-nmap** [comment]
Options that enable NSE script scanning will fail if the NSE engine can't be started for any reason. This is expected behavior.
