### ISSUE TITLE
Nmap script "rdp-ntlm-info" - hardcoded port

### ISSUE THREAD

**Issue by pandalatte** [nmap/nmap#1694]
There's a nifty script called "rdp-ntlm-info" which allows to extract Netbios info from RDP.

However, the port value of 3389 is *hardcoded*. Line 46 goes as:

author = "Tom Sellers"
license = "Same as Nmap--See https://nmap.org/book/man-legal.html"
categories = {"default", "discovery", "safe"}
portrule = shortport.port_or_service(3389, "ms-wbt-server")

====
How do I pass a non-standard port as variable? Thanks!

**Comment by cldrn** [comment]
Hi,
The rule will trigger anytime the service 'ms-wbt-server' is detected so it is not really hardcoded only for port 3389. Enable service detection if the service is running on an alternate port (-sV) and you can always force the execution of a script using the character '+' before the script name (--script +rdp-ntlm-info).
Cheers.
