### ISSUE TITLE
Seclists needs bigger list icons

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#170]
Social networks such as Facebook, Reddit, etc. like to have a thumbnail image to associate with posts.  Right now the tags we put in the page ask them to use the logo associated with the individual list.  But most of those logos are too small, at least for some networks.  For example, Facebook wants og:image to be at least 200x200.  The images don't necessarily have to even be shown on the page as long as we link them from og:image.

**Comment by fyodor** [comment]
OK, we made bigger ones but then we discovered that if they are larger than 600x315, Facebook displays them in a huge format which is probably bigger than we need.  So we should probably make a smaller version than that, and Facebook suggests we have an aspect ratio around 1.91:1

**Comment by dmiller-nmap** [comment]
@fyodor I think we took care of this. Can you use the facebook debugger on relevant pages and double-check? https://developers.facebook.com/tools/debug/

**Comment by fyodor** [comment]
Looks good for the dev and announce lists, but for the other lists FB still uses ad banners by default. Can you do this fix for the other lists as well?  We should at least have a good icon for full-disclosure since we run it.  And for the other lists, if it's a pain to make a large enough icon for them, maybe a generic seclists.org icon could be used.

**Comment by dmiller-nmap** [comment]
All remaining lists will now use seclists.org logo as image for sharing while retaining their own logos on the webpages.
