### ISSUE TITLE
rtsp-url-brute script come across error

### ISSUE THREAD

**Issue by smallnuaa** [nmap/nmap#1701]
I run nmap with version 7.80 on Ubuntu 16.04, script rtsp-url-brute failed,  here is the debug info with -d:
nmap --script rtsp-url-brute -p 554 -d 10.43.60.35
Starting Nmap 7.80 ( https://nmap.org ) at 2019-08-19 17:26 CST
Warning: File ./nmap-services exists, but Nmap is using /usr/local/bin/../share/nmap/nmap-services for security and consistency reasons.  set NMAPDIR=. to give priority to files in your local directory (may affect the other data files too).
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000_
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 17:26
Completed NSE at 17:26, 0.00s elapsed
Initiating Ping Scan at 17:26
Scanning 10.43.60.35 [4 ports]
Packet capture filter (device br0): dst host 172.16.1.26 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.43.60.35)))
We got a ping packet back from 10.43.60.35: id = 47945 seq = 0 checksum = 17590
Completed Ping Scan at 17:26, 0.04s elapsed (1 total hosts)
Overall sending rates: 99.62 packets / s, 3785.43 bytes / s.
mass_rdns: Using DNS server 114.114.114.114
Initiating Parallel DNS resolution of 1 host. at 17:26
mass_rdns: 13.00s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 3]
Completed Parallel DNS resolution of 1 host. at 17:26, 13.00s elapsed
DNS resolution of 1 IPs took 13.00s. Mode: Async [#: 1, OK: 0, NX: 0, DR: 1, SF: 0, TR: 3, CN: 0]
Initiating SYN Stealth Scan at 17:26
Scanning 10.43.60.35 [1 port]
Packet capture filter (device br0): dst host 172.16.1.26 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.43.60.35)))
Discovered open port 554/tcp on 10.43.60.35
Completed SYN Stealth Scan at 17:26, 0.05s elapsed (1 total ports)
Overall sending rates: 20.12 packets / s, 885.13 bytes / s.
NSE: Script scanning 10.43.60.35.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 17:26
NSE: Starting rtsp-url-brute against 10.43.60.35:554.
NSE: rtsp-url-brute against 10.43.60.35:554 threw an error!
/usr/local/bin/../share/nmap/nselib/rtsp.lua:87: invalid value (nil) at index 3 in table for 'concat'
stack traceback:
	[C]: in function 'table.concat'
	/usr/local/bin/../share/nmap/nselib/rtsp.lua:87: in function </usr/local/bin/../share/nmap/nselib/rtsp.lua:77>
	[C]: in function 'tostring'
	/usr/local/bin/../share/nmap/nselib/rtsp.lua:208: in function </usr/local/bin/../share/nmap/nselib/rtsp.lua:200>
	(...tail calls...)
	/usr/local/bin/../share/nmap/scripts/rtsp-url-brute.nse:84: in upvalue 'fetch_url'
	/usr/local/bin/../share/nmap/scripts/rtsp-url-brute.nse:142: in function </usr/local/bin/../share/nmap/scripts/rtsp-url-brute.nse:116>
	(...tail calls...)

Completed NSE at 17:26, 0.00s elapsed
Nmap scan report for 10.43.60.35
Host is up, received echo-reply ttl 62 (0.00086s latency).
Scanned at 2019-08-19 17:26:43 CST for 13s

PORT    STATE SERVICE REASON
554/tcp open  rtsp    syn-ack ttl 62
Final times for host: srtt: 858 rttvar: 3776  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 17:26
Completed NSE at 17:26, 0.00s elapsed
Read from /usr/local/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 13.45 seconds
           Raw packets sent: 5 (196B) | Rcvd: 2 (72B)

**Comment by JinxuanCang** [comment]
I encountered this problem on Windows as well. I have the exact same "traceback" output as @smallnuaa does.

**Comment by nnposter** [comment]
The issue has been hopefully rectified in r37751 (08a6d8db4b15599c4ec5f8e49bcfc811decfe161). Please report back if the error persists.
