### ISSUE TITLE
Zenmap crash after click Topology on macOS 10.15 

### ISSUE THREAD

**Issue by Ponny035** [nmap/nmap#1710]
After I finish scan my network and I click show Topology it crash and appears this error
<img width="1680" alt="Screen Shot 2562-08-24 at 15 50 33" src="https://user-images.githubusercontent.com/19405100/63634921-08152980-c687-11e9-9091-5bcd003f53a8.png"> 
and after this I can't click even scroll to read error any button on Zenmap util I user activity monitor to close it

**Comment by schliden** [comment]
This is the same issue as #1705 

https://github.com/nmap/nmap/issues/1705
