### ISSUE TITLE
ssl-enum-ciphers reports dhparam sizes divided by 8

### ISSUE THREAD

**Issue by MichalStaruch** [nmap/nmap#172]
ssl-enum-ciphers script reports dhparam size divided by 8, that is when we generate 4096 dhparam with
`openssl dhparam -out dhparam.pem 4096` ssl-enum-ciphers reports it as `(dh 512)`.

Tested on nmap 6.49SVN (commit df5d9a7).

**Comment by dmiller-nmap** [comment]
Thanks for the report. This was due to some confusion between DH and ECDH strength-vs-length equivalences. I have corrected this in ddc5762, with help from Brandon Paulsen.
