### ISSUE TITLE
nmap detected

### ISSUE THREAD

**Issue by bigboy606** [nmap/nmap#1721]
I am scanned 10 different IP address with bugs. next day was all ports closed, deciosion nmap fired. how to be undetectable?

**Comment by XdaemonX** [comment]
There is no one recipe to be undetectable. You have to tweak a lot your nmap scan in order to be "undetectable", timing options for example.

**Comment by cnotin** [comment]
A few suggestions:
http://blog.bonsaiviking.com/2015/07/they-see-me-scannin-they-hatin.html
http://blog.bonsaiviking.com/2015/07/they-see-me-scannin-part-2.html

**Comment by dmiller-nmap** [comment]
Nmap scan tuning and detection avoidance is a complicated topic, not something we will discuss on this issue tracker. You can read more in the chapter of *Nmap Network Scanning* titled [Detecting and Subverting Firewalls and Intrusion Detection Systems](https://nmap.org/book/firewalls.html).
