### ISSUE TITLE
Can't connect to wireless network [Win10]

### ISSUE THREAD

**Issue by Vegetassg** [nmap/nmap#1729]
Hello,
I do have a very strange and annoying issue. I recently installed Nmap 7.8 along with Ncap ( and the loopback driver..)
Right after installing thoses softwares i had no problem.
After rebooting my laptop, i could not connect to any wireless network except open one ( i also tried with 2 other wifi usb key)
I removed Nmap, Npcap and ensured that the loopback driver was also uninstalled. But i keep getting this problem. I tried reset Win 10 network setting by default but nothing change. I also desactivate my wlan adaptor but nothing changed.

Here are the diag and log wich i kept from after i removed the sofware.
[install.log](https://github.com/nmap/nmap/files/3587026/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/3587027/NPFInstall.log)
[DiagReport-20190907-202831.txt](https://github.com/nmap/nmap/files/3587028/DiagReport-20190907-202831.txt)

**Comment by fyodor** [comment]
Thanks for your report.  Nmap currently still bundles a very old version of Npcap. If you can install Npcap version 0.9991 first and then install Nmap, hopefully everything will work.  If not, please file a new issue with details and we'll investigate further.  Thanks!
