### ISSUE TITLE
improve topology view and vector output

### ISSUE THREAD

**Issue by tjt263** [nmap/nmap#1741]
Hey, where's the code that determines:

- Exactly how the topology view looks and/or 
- How the SVG/PDF/PS/PNG output is rendered? 

I'd like to contribute some improvements; fine-tune it a bit. I have a bit more experience in that area, than I do with programming but I'm quite comfortable with Python. I think I just need to identify/locate the original code.

Thanks.

**Comment by fyodor** [comment]
Thanks for your interest in improving Zenmap!  I am closing this since it isn't really an "issue" that needs to be fixed, but anyone who wants to can still reply to your question here.  You are also welcome to send it to the Nmap dev list at dev@nmap.org.

**Comment by dmiller-nmap** [comment]
Topology view is in `zenmap/zenmapGUI/TopologyPage.py`, with most implementation done in `zenmap/radialnet/`.
