### ISSUE TITLE
zh translate error about parallelism

### ISSUE THREAD

**Issue by gMan1990** [nmap/nmap#1745]
- error: `--min-parallelism <milliseconds>; --max-parallelism <milliseconds> (调整探测报文的并行度)`
https://github.com/nmap/nmap/blob/7d7f0672d2ff4be4bdac233d566b56443f8d815c/docs/man-xlate/nmap-man-zh.xml#L1421

- right: `--min-parallelism <numprobes>; --max-parallelism <numprobes> (Adjust probe parallelization)`

- it's `numprobes` not `milliseconds`

**Comment by dmiller-nmap** [comment]
Thank you for letting us know! This was a problem from years ago in the English documentation, so older translations still use the incorrect words. We've corrected it in several different translations, and will be updating the website soon.
