### ISSUE TITLE
NMAP XML output showing deprecated CPE

### ISSUE THREAD

**Issue by cstayyab** [nmap/nmap#1749]
I scanned one of my systems and saved the XML and found a CPE which is deprecated. Here is the part of the output:

```xml
<port protocol="tcp" portid="443">
    <state state="open" reason="syn-ack" reason_ttl="0"/>
    <service name="http" product="Microsoft IIS httpd" version="7.5" ostype="Windows" tunnel="ssl" method="probed" conf="10">
        <cpe>cpe:/a:microsoft:iis:7.5</cpe>
        <cpe>cpe:/o:microsoft:windows</cpe>
    </service>
<!-- Truncated Data-->
</port>
```

When I searched `cpe:/a:microsoft:iis:7.5` I learnt that this CPE has deprecated and an new CVE is available:

> This CPE has been deprecated to:
> `cpe:2.3:a:microsoft:internet_information_server:7.5:*:*:*:*:*:*:*`

**REFERENCE:** https://nvd.nist.gov/products/cpe/detail/126703?keyword=cpe%3A2.3%3Aa%3Amicrosoft%3Aiis%3A*%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED&orderBy=CPEURI&namingFormat=2.3

**Comment by dmiller-nmap** [comment]
Thanks for the tip! We've updated these references, and the commit should close this issue shortly.
