### ISSUE TITLE
Nmpa script error when scanning SMBv1

### ISSUE THREAD

**Issue by ColeBracew** [nmap/nmap#1758]
I am running the latest version of Kali with Nmap version 7.80.

I have noticed none of the SMB scripts run correctly when targeting SMBv1.  i have attached the debug output from my scan here.
[smberror.txt](https://github.com/nmap/nmap/files/3647098/smberror.txt)

You can test this by your self by scanning lame on hackthebox 'where i found the issue. 

i know this was working on an older version of Kali and Nmap.

**Comment by cldrn** [comment]
Hi, Can you share a pcap? I've noticed a weird behavior recently. Something changed that is making NSE have problems with retransmissions or out of order packets.

**Comment by ColeBracew** [comment]
Here you go. 

[smberror.zip](https://github.com/nmap/nmap/files/3647752/smberror.zip)

**Comment by DroppedSyn** [comment]
Same problem here.

**Comment by nnposter** [comment]
A fix for this known issue has been committed as r37733 (c491143358f3417ed7f6712ae8a9d3e48699463a) back on September 7. Please report back if it does not work for you.
