### ISSUE TITLE
mysql-info: ERROR: Script execution failed (use -d to debug)

### ISSUE THREAD

**Issue by Reelix** [nmap/nmap#1765]
$nmap -p3306 google.com --script=mysql-info -d
Starting Nmap 7.80 ( https://nmap.org ) at 2019-09-28 13:05 UTC
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
\---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI:
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:05
Completed NSE at 13:05, 0.00s elapsed
Initiating Ping Scan at 13:05
Scanning google.com (173.194.217.100) [2 ports]
Completed Ping Scan at 13:05, 0.00s elapsed (1 total hosts)
Overall sending rates: 1410.44 packets / s.
mass_rdns: Using DNS server 127.0.0.53
Initiating Parallel DNS resolution of 1 host. at 13:05
mass_rdns: 0.00s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
Completed Parallel DNS resolution of 1 host. at 13:05, 0.00s elapsed
DNS resolution of 1 IPs took 0.01s. Mode: Async [#: 1, OK: 1, NX: 0, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating Connect Scan at 13:05
Scanning google.com (173.194.217.100) [1 port]
Discovered open port 3306/tcp on 173.194.217.100
Completed Connect Scan at 13:05, 0.00s elapsed (1 total ports)
Overall sending rates: 682.59 packets / s.
NSE: Script scanning 173.194.217.100.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:05
NSE: Starting mysql-info against google.com (173.194.217.100:3306).
NSE: [mysql-info 173.194.217.100:3306] receiveGreeting(): failed
NSE: mysql-info against google.com (173.194.217.100:3306) threw an error!
EOF
stack traceback:
        [C]: in local 'try'
        /usr/bin/../share/nmap/nselib/mysql.lua:111: in function 'mysql.receiveGreeting'
        /usr/bin/../share/nmap/scripts/mysql-info.nse:85: in function </usr/bin/../share/nmap/scripts/mysql-info.nse:74>
        (...tail calls...)

Completed NSE at 13:05, 0.00s elapsed
Nmap scan report for google.com (173.194.217.100)
Host is up, received syn-ack (0.0010s latency).
Other addresses for google.com (not scanned): 173.194.217.139 173.194.217.113 173.194.217.102 173.194.217.138 173.194.217.101 2607:f8b0:400c:c07::64
rDNS record for 173.194.217.100: vw-in-f100.1e100.net
Scanned at 2019-09-28 13:05:35 UTC for 0s

PORT     STATE SERVICE REASON
3306/tcp open  mysql   syn-ack
Final times for host: srtt: 1039 rttvar: 3763  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:05
Completed NSE at 13:05, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 0.31 seconds

**Comment by dmiller-nmap** [comment]
Thanks for the bug report. This is not really a bug for a couple of reasons:

1. The crash came in a `try` function. This indicates that the script author expects that a function may return an error, and is willing to abort completely if that happens. This worked more cleanly in older Lua versions, but now results in a Lua error being thrown. In any case, it means there is not a programming error, but a network error condition. In this case, we were unable to receive a greeting from the server.

2. You have found port 3306 open on google.com, when it is not actually open. This is probably the result of interference by your ISP in order to stop network attacks or force businesses to purchase plans without these restrictions. You may be able to use Nmap's `-sV` feature to determine what kind of service is responding on Google's behalf.

**Comment by Reelix** [comment]
Whilst I'll accept this as closed, I'll just leave some notes.

- This worked more cleanly in older Lua versions, but now results in a Lua error being thrown.
That's what the issues was about - The script crashing. It's inability to return a MySQL-based result was rather irrelevant :)

- This was performed from within Google's own infrastructure VIA a Google Cloud Platform Compute Engine. "nmap -p3306 -sV google.com" reports it as open, service=tcpwrapped, and a blank version.
