### ISSUE TITLE
dnet: Failed to open device eth0 (Windows 10 + nmap 7.80 + npcap 0.9982)

### ISSUE THREAD

**Issue by Youda008** [nmap/nmap#1769]
I just freshly installed nmap 7.80 and its bundled npcap 0.9982 from the Windows installer downloaded on the official page, but whenever i try to run any kind of nmap scan, it ends up with error
```
dnet: Failed to open device eth0
QUITTING!
```
Output of my `nmap -iflist`:
```
************************INTERFACES************************
DEV  (SHORT) IP/MASK                                   TYPE     UP MTU  MAC
lo0  (lo0)   ::1/128                                   loopback up 1500
lo0  (lo0)   127.0.0.1/8                               loopback up 1500
eth0 (eth0)  2a0b:e181:600:900:b105:bf3f:d639:691b/64  ethernet up 1500 B8:85:84:C0:7A:97
eth0 (eth0)  2a0b:e181:600:900:c105:6040:55bc:b6e1/128 ethernet up 1500 B8:85:84:C0:7A:97
eth0 (eth0)  fe80::b105:bf3f:d639:691b/64              ethernet up 1500 B8:85:84:C0:7A:97
eth0 (eth0)  192.168.123.158/24                        ethernet up 1500 B8:85:84:C0:7A:97

DEV  WINDEVICE
lo0  <none>
lo0  <none>
eth0 <none>
eth0 <none>
eth0 <none>
eth0 <none>

**************************ROUTES**************************
DST/MASK                                  DEV  METRIC GATEWAY
255.255.255.255/32                        lo0  281
169.254.207.22/32                         lo0  281
169.254.255.255/32                        lo0  281
192.168.123.158/32                        eth0 291
255.255.255.255/32                        eth0 291
192.168.123.255/32                        eth0 291
127.255.255.255/32                        lo0  331
127.0.0.1/32                              lo0  331
255.255.255.255/32                        eth0 331
192.168.123.0/24                          eth0 291
169.254.0.0/16                            lo0  281
127.0.0.0/8                               lo0  331
224.0.0.0/4                               lo0  281
224.0.0.0/4                               eth0 291
224.0.0.0/4                               eth0 331
0.0.0.0/0                                 eth0 35     192.168.123.1
fe80::2043:6173:1163:cf16/128             lo0  281
2a0b:e181:600:900:c105:6040:55bc:b6e1/128 eth0 291
fe80::b105:bf3f:d639:691b/128             eth0 291
2a0b:e181:600:900:b105:bf3f:d639:691b/128 eth0 291
::1/128                                   lo0  331
fe80::/64                                 lo0  281
fe80::/64                                 eth0 291
2a0b:e181:600:900::/64                    eth0 4131
ff00::/8                                  lo0  281
ff00::/8                                  eth0 291
ff00::/8                                  eth0 331
::/0                                      eth0 4131   fe80::5ee2:8cff:fe9e:fc0c
```
Tried running command prompt in admin mode, tried reinstalling nmap, tried upgrading to npcap 0.9983, tried rebooting.

**Comment by dmiller-nmap** [comment]
Thanks for the report. Can you please provide the output of [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues) so we can better diagnose the problem?

**Comment by dzhenway** [comment]
same with me
i got this error

**Comment by Youda008** [comment]
Here it is
[DiagReport-20191002-094340.txt](https://github.com/nmap/nmap/files/3679975/DiagReport-20191002-094340.txt)

**Comment by dmiller-nmap** [comment]
Ok, it seems the npcap driver service is stopped. Nmap normally attempts to start it, but if you aren't running with an Admin account, it can't do so. What output do you get if you try to start the service manually? Here are the steps:

1. Open an command prompt as Administrator. (Windows+R, then type: `powershell.exe Start-Process cmd.exe -Verb runAs` )
2. In the Administrator command console, type: `net start npcap`

**Comment by dzhenway** [comment]
hi @dmiller-nmap 

C:\Windows\system32>powershell.exe Start-Process cmd.exe -Verb runAs

C:\Windows\system32>net start npcap
System error 2 has occurred.

The system cannot find the file specified.

I tried reinstall NPCAP (0.9983) but still didnt work

OS : Windows 10 Pro 64 bit

**Comment by Youda008** [comment]
Same as dzhenway:
```
C:\WINDOWS\system32>net start npcap
System error 2 has occurred.

The system cannot find the file specified.
```

**Comment by Youda008** [comment]
Additional info. When i uninstall the npcap, i see the following in the uninstall window
```
...
Npcap LWF driver (with Wi-Fi support) has failed to be uninstalled.
Npcap WFP callout driver has been successfully uninstalled!
The npcap service for Win7, Win8 and Win10 was successfully deleted
ROOT\NET\0001                                               : Removed
Npcap Loopback adapter has failed to be uninstalled.
...
```

**Comment by Youda008** [comment]
My issue has been fixed by this
https://forum.avast.com/index.php?topic=229610.0
But i guess that's just a workaround and should be investigated further.

**Comment by dzhenway** [comment]
hi @Youda008 

can you share npcap.reg? because i wanna try it

Thank you

**Comment by Youda008** [comment]
[npcap.reg.txt](https://github.com/nmap/nmap/files/3842009/npcap.reg.txt)
remove the .txt postfix and then double-click

**Comment by dzhenway** [comment]
> [npcap.reg.txt](https://github.com/nmap/nmap/files/3842009/npcap.reg.txt)
> remove the .txt postfix and then double-click

thank you

**Comment by dezza** [comment]
> npcap 0.9982
From [nmap.org/download.html](https://nmap.org/download.html)
> Note: The version of Npcap included in our installers may not always be the latest version.
Latest ([npcap-0.9986.exe](https://nmap.org/npcap/dist/npcap-0.9986.exe))
https://nmap.org/npcap/#download

This is a brand new replacement to WinPcap, so it's subject to lots of change over this time.

I got it to work with this version, but I had trouble using the version included (0.9982 as in original issue description) and with using a "WireGuard tunnel TAP adapter" it refused to give me anything but `Failed to open eth0` even if I restarted `net stop npcap` and `net start npcap`

Good luck guys. And thanks for the hard work towards npcap to author 👍

**Comment by senorblasto** [comment]
> > > npcap 0.9982
> > 
> > You're using the included version in nmap, which is a bit outdated now.
> > 
> > From [nmap.org/download.html](https://nmap.org/download.html)
> 


Was getting:
```
 dnet: Failed to open device eth4

QUITTING!
```
This fixed it for me.

**Comment by dmiller-nmap** [comment]
This issue is the same as #1944, so we will track it there. If you are still having this problem after upgrading to [the latest Npcap](https://npcap.org/#download), please provide diagnostic information on that issue instead.

**Comment by cedricbellec** [comment]
I solved this issue this way: open regedit.exe and go to \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap
Change the key ImagePath with this value: System32\DRIVERS\npcap.sys
Close regedt
Now start service in an admin command console with : sc start npcap
And it should work

**Comment by palaboy** [comment]
any fix for latest npcap-0.9991 ?
i still have error Windows 10 2004:
C:\WINDOWS\system32>net start npcap
System error 2 has occurred.

The system cannot find the file specified.

**Comment by gptshubham595** [comment]
ANy problem Just uninstall and reinstall I don't know but it solves my problem

**Comment by hastalamuerte** [comment]
same problem with norvpn nordlynx tunnel ! Help plz!

**Comment by freeload101** [comment]
Yah I think reinstall fixes it .. I want to say it has to do with interfaces changing or being updated and npcap needing to be hooked into them. I also have had some luck running zenmap for whatever reason even with -iface param nmap.exe won't work then zenmap works fine ... also could be ERD/Endpoint BS ...just some ideas THANKS ALL! -rmccurdyDOTcom

**Comment by eabase** [comment]
This is a classical problem when you have been messing with drivers and/or installed other drivers that *does something* to your native network drivers. Normally re-installing the latest `npcap` instantly fixes these issues.
