### ISSUE TITLE
--script=safe on port 53 displays "too short" 5 times

### ISSUE THREAD

**Issue by Reelix** [nmap/nmap#1774]
> nmap -sC -sV 10.13.37.10 -p53 --script=safe -vvv
> Starting Nmap 7.80 ( https://nmap.org ) at 2019-10-07 02:43 Egypt Standard Time
> NSE: Loaded 362 scripts for scanning.
> NSE: Script Pre-scanning.
> NSE: Starting runlevel 1 (of 3) scan.
> Initiating NSE at 02:43
> NSE: [targets-xml] Need to supply a file name with the targets-xml.iX argument
> NSE: [mrinfo] Nsock connect failed immediately
> NSE: [broadcast-sonicwall-discover] No network interface was supplied, aborting.
> NSE: [mtrace] A source IP must be provided through fromip argument.
> NSE: [url-snarf] no network interface was supplied, aborting ...
> NSE: [shodan-api] Error: Please specify your ShodanAPI key with the shodan-api.apikey argument
> NSE: [broadcast-ataoe-discover] No interface supplied, use -e
> too short
> too short
> too short
> too short
> too short
> Completed NSE at 02:44, 30.46s elapsed
> NSE: Starting runlevel 2 (of 3) scan.
> Initiating NSE at 02:44
> Completed NSE at 02:44, 0.00s elapsed
> NSE: Starting runlevel 3 (of 3) scan.
> Initiating NSE at 02:44
> Completed NSE at 02:44, 0.00s elapsed
> Pre-scan script results:
> | broadcast-dns-service-discovery:
> \*Regular output here\*  
  
The 5 "too short" lines appear in a --script=safe scan even without -v with no description as to where they come from or what they mean. I'm assuming it's from one of the scripts that runs, but am unsure which.

**Comment by dmiller-nmap** [comment]
This was resolved in edb130e9088
