### ISSUE TITLE
shortport.lua : Add globalcatLDAPssl and 3269 as LIKELY_SSL_PORTS

### ISSUE THREAD

**Issue by claykeller** [nmap/nmap#179]
globalcatLDAPssl and port 3269 are already defined in nmap-services as an SSL port. I think it would be reasonable to go ahead and add to shortport.lua as a likely ssl port. I've run into it a bunch lately.

**Comment by cldrn** [comment]
For some reason I've seen it a lot lately too. It makes sense.
