### ISSUE TITLE
Ncat 7.80 server side gets no messages with --chat mode 

### ISSUE THREAD

**Issue by Justsoos** [nmap/nmap#1794]
MacOS 10.13.6
from homebrew
nmap/ncat 7.80

Ubuntu 18.04 LTS
from apt install
nmap/ncat 7.60

server side run:
```
ncat -lp 8888 --chat
```
client side run:
```
ncat -v localhost 8888
```

server side can not show message from client,  client get from `<user0>` 

 ```
ncat -v localhost 8888
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:8888.
<announce> 127.0.0.1 is connected as <user5>.
<announce> already connected: nobody.
<user0> MESSAGES
```

**Comment by Justsoos** [comment]
both macos and ubuntu get the same bug

**Comment by dmiller-nmap** [comment]
Ncat chat mode is a special case of [connection brokering](https://nmap.org/ncat/guide/ncat-broker.html), which is used to transmit messages between multiple connected clients. STDOUT is not considered a connected client, though input is still accepted from STDIN. This is not really a bug; the server is doing a different job than a connected client, so its behavior is different. I'll mark this as an enhancement request in case anyone is interested in implementing it.

**Comment by Justsoos** [comment]
see, the server is a host-role
