### ISSUE TITLE
Abort in stopTimeOutClock again

### ISSUE THREAD

**Issue by severach** [nmap/nmap#1797]
#1361 is back and worse than before. As root nmap 7.80 will run once after boot and no more. All runs after the first report

````
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
Aborted (core dumped)
````
nmap 7.80 runs fine as a user even after a root run has left nmap as root non functional. nmap 7.70 runs fine as root. To run 7.80 again as root I must reboot.

````
pacman -Q nmap-svn
nmap-svn 7.80.r37748-1
````

**Comment by dmiller-nmap** [comment]
Fixed in 33f421f
