### ISSUE TITLE
http-enum.fingerprintfile will not work with a .txt

### ISSUE THREAD

**Issue by Sorsnce** [nmap/nmap#1798]
Per the Network_Exploration_And_Security_Auditing_Cookbook the http-enum NSE script should be able to take a .txt file to enumerate with the http-enum.fingerprintfile flag. This does not work and the NSE script appears to only work with .lua files. See below for sytacts from Network_Exploration_And_Security_Auditing_Cookbook:

```
The fingerprints are stored in the file http-fingerprints.lua in /nselib/data/,
and they are actually LUA tables. An entry looks like something like following:
table.insert(fingerprints, {
category='cms',
probes={
 {path='/changelog.txt'},
 {path='/tinymce/changelog.txt'},
},
matches={
 {match='Version (.-) ', output='Version \\1'},
 {output='Interesting, a changelog.'}
}
})
You may add your own entries to this file or use a different fingerprint file by using the
argument http-enum.fingerprintfile:
$ nmap --script http-enum --script-args http-enum.fingerprintfile=./
myfingerprints.txt -p80 <target>
```

**Comment by cldrn** [comment]
Hi,

I think I did not make myself clear enough there. The file extension should not matter but the content needs to be Lua tables as shown in the example (not lists separated by newlines).

Cheers.

**Comment by Sorsnce** [comment]
Closing this issue and updated documentation.
