### ISSUE TITLE
Nmap Issue - DNet: Failed to open device eth2

### ISSUE THREAD

**Issue by ghost** [nmap/nmap#1801]
Hi, i have installed Nmap and fixed some issues along the way, i have installed all the additional required programs and when i go to scan it provides me with the following error:

Starting Nmap 7.80 ( https://nmap.org ) at 2019-10-31 14:52 AUS Eastern Daylight Time

NSE: Loaded 151 scripts for scanning.

NSE: Script Pre-scanning.

Initiating NSE at 14:52

Completed NSE at 14:52, 0.00s elapsed

Initiating NSE at 14:52

Completed NSE at 14:52, 0.00s elapsed

Initiating NSE at 14:52

Completed NSE at 14:52, 0.00s elapsed

Initiating Parallel DNS resolution of 1 host. at 14:52

Completed Parallel DNS resolution of 1 host. at 14:52, 0.00s elapsed

Initiating SYN Stealth Scan at 14:52

dnet: Failed to open device lo0

QUITTING!

Any help would be greatly appreciated. :)
Thanks Nick

**Comment by samdizzy** [comment]
Same here but it works for ip 192.168.56.1 and not for scanme,nmap.org ... odd behaviour

**Comment by dmiller-nmap** [comment]
The error, "dnet: Failed to open device" is a symptom of an issue with Npcap. Please install [the latest Npcap](https://npcap.com/#download) and try again. If the issue persists, please [open a bug report for Npcap](https://issues.npcap.org/).
