### ISSUE TITLE
Support for target list with IP:PORT format

### ISSUE THREAD

**Issue by maurosoria** [nmap/nmap#1815]
Hey guys, 

I would like to have support for an input list with IP:PORT format. I usually need to scan a list of hosts but each one with different ports. Now, it is no possible, nmap would scan the same ports for every host. I've made a wrapper script for this task, but wouldn't be great that nmap supports this? With randomization and all that stuff.

Thanks guys !

**Comment by nnposter** [comment]
Please peruse discussion in #1217. Any additional comments should be made there.
