### ISSUE TITLE
Passing --iflist only prints interfaces, does not scan

### ISSUE THREAD

**Issue by drws** [nmap/nmap#1835]
I'm running Nmap 7.80 on Arch Linux. If the --iflist output option is passed, Nmap accepts all input arguments, but does not scan anything - it just outputs the interface and route list. As far as I understand the manpage this debugging output should be printed in addition to scan results. Or if current behavior is the desired one, it could be mentioned in the manpage.

**Comment by nnposter** [comment]
Can you elaborate on the use case where you need the list of interfaces and the scan results *at the same time*?

Normally you would use `--iflist` to understand what network connectivity is available to Nmap, either to troubleshoot a previous scan or to force a specific interface in a new scan. If you simply need to know which interface was used during the scan then you can use option `-d`.

**Comment by dmiller-nmap** [comment]
@drws Nmap has several diagnostic output options that do not permit a scan to take place at the same time:
* --iflist
* --version or -V
* --route-dst
* --script-help
* --help or -h

If you have a use case for including interface or route information in the course of a scan, please help us understand what information you need and how it is useful. We may be able to consider extending Nmap's output to include this information, but it will not involve changing the behavior `--iflist`, so we would need it to be filed in a new enhancement request.

**Comment by drws** [comment]
Just an answer to finish the debate: I see your point. I also cannot say much else except that info `--iflist` outputs seems useful to me to be included in certain scan reports (debugging remote LANs for example) and could provide universal interface to obtain interface/route report as well. This information can be easily obtained with system commands, but that requires multiple commands to be run and there are multiple interface managers in use.
