### ISSUE TITLE
Npcap Driver Installation Failure - Error 0x1

### ISSUE THREAD

**Issue by blueck** [nmap/nmap#1842]
Hello, I tried installing npcap 0.991 with loopback_support=no & winpcap_mode=no and seeing the following error on Windows Server 2012 R2: 
![image](https://user-images.githubusercontent.com/4887301/70029752-fd5f1000-1564-11ea-96d1-22ea06a773a2.png)
![image](https://user-images.githubusercontent.com/4887301/70028507-10241580-1562-11ea-93d5-0545912072cb.png)

Here is the NPFInstall.log, it fails with:
```
Error 0x1: Couldn't the get notify object interface.

Possible cause:

Incorrect function.
```

[NPFInstall.log](https://github.com/nmap/nmap/files/3915217/NPFInstall.log)

Any help would be appreciated, thank you.

**Comment by blueck** [comment]
We were able to finally install the driver.  We are still not 100% clear on the connection, but we noticed when we attempted to manually install the driver inf via the network device properties we got a "some controls disabled" error because they were already open (attached). 
![image](https://user-images.githubusercontent.com/4887301/70196020-948ea980-16c4-11ea-8dba-f1c40c232470.png)
When checking logged in users, we saw one that had a COM Surrogate process running.  Once that user was kicked off, the property sheet controls error was gone and the Npcap install was successful.

**Comment by dmiller-nmap** [comment]
Thanks for the report. I'm glad you were able to find a cause and solution, because it had me stumped. The function `HrGetINetCfg` was failing, which is Microsoft-provided code intended to get a reference or handle to the INetCfg registry. It was failing, presumably because something else already had a reference to it and had not released it.
