### ISSUE TITLE
nmap/zenmap cannot find nmap-payloads, nmap-mac-prefixes 

### ISSUE THREAD

**Issue by lukinalutuna** [nmap/nmap#1843]
Hello,

I'm having trouble in scanning with nmap -sP 192.168.178.1/24. 

setup_target: failed to determine route datalink offset failed for type 127

Before, I had trouble with the same scanning with error message: "setup_target: failed to determine route datalink offset failed for type 127". I got this error message since the last update/upgrade on 2nd of Dec.

So I uninstalled nmap/zenmap and other dependencies. 

Afterwards, I reinstalled the dependencies kali-linux-default, msfpc, commix, unicorn-magic, sparta. Lastly, I reinstalled metasploit-framework with nmap/zenmap as its package.

And then, I've scanned the network and got the error messages.

It said: "cannot find nmap-payloads. UDP payloads are disabled." and "cannot find nmap-mac-prefixes: Ethernet vendor correlation will not be performed."

Did I miss something at the reinstallation?

I'm using Kali Linux Kali-Rolling 2019.4

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Are you using Windows Subsystem for Linux (WSL), or are you using Kali on a Linux kernel? Please provide output of `nmap --version` and `uname -a`.

The value 127 is usually LINKTYPE_IEEE802_11_RADIOTAP, which may indicate that the WiFi interface is in monitor mode. Try setting the interface to managed mode (normal operations) to avoid the `datalink_offset` error.

To diagnose the "cannot find file" errors, please provide output with the `-d2` option included. This will give us information about where Nmap may be looking for files.

**Comment by outlaw12321** [comment]
zenmap is no longer supported on the new kali Linux  and are you having a issue with wifi after apt upgrade with 2019.4 mine works great until i upgrade then my wifi changed from wlan0 to some wlx42a937929 (example) and no wifi can airmon-ng see the wifi but cant get on even my wifi

**Comment by dmiller-nmap** [comment]
Since there was no further information provided, we are closing this issue. Please reopen if the problem persists.
