### ISSUE TITLE
Help！ NETGEAR A6210 CAN'T CAPTRUE ANY 802.11 RAW FRAMES ON Win10！

### ISSUE THREAD

**Issue by andersling** [nmap/nmap#1848]
HI,all！
I can't not make A6210 work on windows 10! does anyone has some advice? Thanks a lot !
![image](https://user-images.githubusercontent.com/3992929/70309838-5cfd3a00-1849-11ea-9af0-0da9a6520966.png)

![image](https://user-images.githubusercontent.com/3992929/70309867-70100a00-1849-11ea-8dac-b08bb81dd980.png)

![image](https://user-images.githubusercontent.com/3992929/70309994-a9e11080-1849-11ea-890e-ab0f5ce164fa.png)

![image](https://user-images.githubusercontent.com/3992929/70310027-b6fdff80-1849-11ea-8f86-e0bc8983b65e.png)

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. Sadly, Microsoft has deprecated the API that Npcap uses for raw WiFi frame capture (MicrosoftDocs/windows-driver-docs#1476), so most device drivers do not provide it on Windows 10. Some users have reported success obtaining Windows 8.1 device drivers and using those in compatibility mode on Windows 10. We will be evaluating whether we need to deprecate this functionality in Npcap or at least warn that it may not work on Windows 10.
