### ISSUE TITLE
install npcap failed. Error code 8007007e

### ISSUE THREAD

**Issue by q465271765** [nmap/nmap#1850]
install npcap error
Npcap LWF driver has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10
Finish setting system restore point: Before installation of Npcap 0.99-r2
[NPFInstall.log](https://github.com/nmap/nmap/files/3937587/NPFInstall.log)

**Comment by dmiller-nmap** [comment]
Thank you for reporting this. We have made 18 releases since Npcap 0.99-r2, so we are not accepting issue reports for that version. Please try Npcap 0.9984 and let us know if you still have problems.

**Comment by guyharris** [comment]
See also #1401.
