### ISSUE TITLE
No monitor checkboxes for wireshark windows 10

### ISSUE THREAD

**Issue by archmogician** [nmap/nmap#1851]
[screenshot](https://user-images.githubusercontent.com/55859343/70420749-38f25200-1a1d-11ea-913d-f18850a23179.png)

[DiagReport-20191209-002340.txt](https://github.com/nmap/nmap/files/3938607/DiagReport-20191209-002340.txt)

**Comment by dmiller-nmap** [comment]
Sadly, Microsoft has deprecated the API that Npcap uses for raw WiFi frame capture (MicrosoftDocs/windows-driver-docs#1476), so most device drivers do not provide it on Windows 10. Some users have reported success obtaining Windows 8.1 device drivers and using those in compatibility mode on Windows 10. We will be evaluating whether we need to deprecate this functionality in Npcap or at least warn that it may not work on Windows 10.

**Comment by archmogician** [comment]
So most of the USB Wi-Fi antennas won't either on Windows 10 ?

**Comment by andersling** [comment]
@dmiller-nmap  Thanks dmiler for your reply!!
  and by the way,you said [Some users have reported success obtaining Windows 8.1 device drivers and using those in compatibility mode on Windows 10]， it's it means that I find the device's win8 drvier and install on my win10 OS ,then try? 
 thanks !
