### ISSUE TITLE
nfs-ls.nse script not showing anything

### ISSUE THREAD

**Issue by chris9797** [nmap/nmap#1853]
I am using Nmap 7.80 and the nfs-ls script gives me the same output as the normal nmap scan.
The remote directory which I want to find using nfs-ls is present in the target machine as I can mount it from my host machine kali. I am referring 

> [Penetration testing-A hands on introduction to hacking, book by Georgia Weidman page 145](https://books.google.co.in/books/about/Penetration_Testing.html?id=DUMyDwAAQBAJ&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q&f=false).

Normal o/p:
```
root@kali:/# nmap 192.168.1.4
Starting Nmap 7.80 ( https://nmap.org ) at 2019-12-12 00:45 EST
Nmap scan report for 192.168.1.4
Host is up (0.013s latency).
Not shown: 993 closed ports
PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
80/tcp   open  http
111/tcp  open  rpcbind
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
2049/tcp open  nfs
MAC Address: 00:0C:29:13:27:11 (VMware)

Nmap done: 1 IP address (1 host up) scanned in 0.31 seconds

```
o/p with nfs-ls script:
```
root@kali:/# nmap --script nfs-ls 192.168.1.4
Starting Nmap 7.80 ( https://nmap.org ) at 2019-12-12 00:45 EST
Nmap scan report for 192.168.1.4
Host is up (0.013s latency).
Not shown: 993 closed ports
PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
80/tcp   open  http
111/tcp  open  rpcbind
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
2049/tcp open  nfs
MAC Address: 00:0C:29:13:27:11 (VMware)

Nmap done: 1 IP address (1 host up) scanned in 0.59 seconds
```

**Comment by nnposter** [comment]
Please try the following patch:
```diff
--- a/nselib/rpc.lua	2019-12-14 15:16:33.978756100 -0700
+++ b/nselib/rpc.lua	2019-12-19 19:36:27.569007400 -0700
@@ -719,6 +719,7 @@
         local len
         len, pos = string.unpack(">I4", data, pos)
         pos, protocol = Util.unmarshall_vopaque(len, data, pos)
+        protocol = protocol:match("[^\0]*")
         len, pos = string.unpack(">I4", data, pos)
         pos, addr = Util.unmarshall_vopaque(len, data, pos)
         len, pos = string.unpack(">I4", data, pos)
```

**Comment by cnotin** [comment]
May be related to #1469

**Comment by nnposter** [comment]
Definitely. I have run into it as well. The OP provides no info to go by.
The patch above is addressing one specific NFS implementation quirk observed in real world.

**Comment by chris9797** [comment]
> Please try the following patch:
did not work

**Comment by chris9797** [comment]
> Please try the following patch:
> 
> ```diff
> --- a/nselib/rpc.lua	2019-12-14 15:16:33.978756100 -0700
> +++ b/nselib/rpc.lua	2019-12-19 19:36:27.569007400 -0700
> @@ -719,6 +719,7 @@
>          local len
>          len, pos = string.unpack(">I4", data, pos)
>          pos, protocol = Util.unmarshall_vopaque(len, data, pos)
> +        protocol = protocol:match("[^\0]*")
>          len, pos = string.unpack(">I4", data, pos)
>          pos, addr = Util.unmarshall_vopaque(len, data, pos)
>          len, pos = string.unpack(">I4", data, pos)
> ```

did not work

**Comment by nnposter** [comment]
There is another patch for a different issue:
```diff
--- a/nselib/rpc.lua
+++ b/nselib/rpc.lua
@@ -2797,8 +2797,6 @@
   RpcInfo = function( host, port )
     local status, result
     local portmap = Portmap:new()
-    local pversion = 4
-    local comm = Comm:new('rpcbind', pversion)
 
     mutex "lock"
 
@@ -2812,7 +2810,9 @@
       return true, nmap.registry[host.ip]['portmapper']
     end
 
+    local pversion = 4
     while pversion >= 2 do
+      local comm = Comm:new('rpcbind', pversion)
       status, result = comm:Connect(host, port)
       if (not(status)) then
         mutex "done"
```
If this one does not help either then please provide nmap output with debug level 4.

**Comment by WallK** [comment]
> There is another patch for a different issue:
> 
> ```diff
> --- a/nselib/rpc.lua
> +++ b/nselib/rpc.lua
> @@ -2797,8 +2797,6 @@
>    RpcInfo = function( host, port )
>      local status, result
>      local portmap = Portmap:new()
> -    local pversion = 4
> -    local comm = Comm:new('rpcbind', pversion)
>  
>      mutex "lock"
>  
> @@ -2812,7 +2810,9 @@
>        return true, nmap.registry[host.ip]['portmapper']
>      end
>  
> +    local pversion = 4
>      while pversion >= 2 do
> +      local comm = Comm:new('rpcbind', pversion)
>        status, result = comm:Connect(host, port)
>        if (not(status)) then
>          mutex "done"
> ```
> 
> If this one does not help either then please provide nmap output with debug level 4.

Had same issue, patch helped, thank you!

**Comment by nnposter** [comment]
The two patches have been committed as r37861 (c4f7153c226f0eeea1ff9116dc95d38aa885e048) and r37862 (922199296cc34bce7ec5657e6fad75d4edc7fa95).

**Comment by nnposter** [comment]
No follow-up data provided; issue apparently resolved/abandoned.
