### ISSUE TITLE
dnet: Failed to open device eth3

### ISSUE THREAD

**Issue by DBZandr01d** [nmap/nmap#1854]
Hi im a newbie, I reinstalled npcap and and when i launch nmap even if im root it still show: dnet: Failed to open device eth3. (when i try to nmap a website). any idea ? Im on windows 10 using ubuntu...

**Comment by dmiller-nmap** [comment]
On Windows, please use the [Windows build of Nmap](https://nmap.org/download.html#windows). We do not support the Linux build on Windows Subsystem for Linux (WSL).

**Comment by fyodor** [comment]
I've created an official tracking issue for (future) potential Nmap WSL support: https://github.com/nmap/nmap/issues/1864

**Comment by AmyLawler** [comment]
I downloaded the Latest **Npcap release self-installer: npcap-0.9990.exe** from [https://nmap.org/download.html](url)
Completely FIXED the ** #dnet: Failed to open device eth3** issue.
