### ISSUE TITLE
Check redis.lua and rsync.lua use of receive_buf

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#1855]
David Fifield found a problem in stun.lua based on a usage of receive_buf with the second argument of false.  He documented the problem and his fix at https://seclists.org/nmap-dev/2019/q4/8.  He also noted that rsync and redis NSE libraries may ahve the same issue:

        nselib/redis.lua:      status, data = self.socket:receive_buf(match.numbytes(len), false)
        nselib/rsync.lua:    status, data = self.socket:receive_buf(match.numbytes(4), false)
        nselib/rsync.lua:    status, data = self.socket:receive_buf(match.numbytes(len), false)

We should check and (if needed) fix those too.

**Comment by dmiller-nmap** [comment]
I checked and these look straightforward; David's assessment is correct and these would be buggy. The rsync function containing those calls is not actually used anywhere currently, so no scripts are affected, but the redis one probably is causing bad output from some scripts (none in default category). Fix incoming.
