### ISSUE TITLE
rtsp-methods.nse error: Script execution failed

### ISSUE THREAD

**Issue by lukinalutuna** [nmap/nmap#1871]
Ho ho ho,
merry Christmas to all!
did anyone experience error on running the script rtsp-methods? I've downloaded nmap 7.80 from svn for my Kali 2019.4 and from homebrew cellar for my MacOS.

Can anyone help?

Thanks.

**Comment by nnposter** [comment]
Please double-check that your version of `nselib/rtsp.lua` is newer than November 6 so it includes commit 08a6d8db4b15599c4ec5f8e49bcfc811decfe161. Otherwise please provide nmap output with debug level 3.

**Comment by nnposter** [comment]
No follow-up data provided; issue apparently resolved/abandoned.
