### ISSUE TITLE
Nmap script ssl-cert does not report modulus and exponent

### ISSUE THREAD

**Issue by p-l-** [nmap/nmap#1876]
The (structured) output of the Nmap script "ssl-cert" reports a "representation" of some integers (at least, the exponent and modulus of RSA keys), rather than their actual values:
```
$ nmap -n -PS443 -p 443 --script=ssl-cert -oX - www.nmap.org | \
>    grep -E '^<elem key="(modulus|exponent)">'
<elem key="exponent">BIGNUM: 0xXXXXXXXXXXXX</elem>
<elem key="modulus">BIGNUM: 0xXXXXXXXXXXXX</elem>
```

**Comment by nnposter** [comment]
Thank you for reporting the issue. A fix has been committed as r37846.
