### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by apc300** [nmap/nmap#1878]
windows nmap-7.80-setup.exe
installing silently via /S
unable to find any documentation that actually helps disable all the optional features

it looks like there are no command line option to NOT install the loopback adapter? i tried everything i could

**Comment by dmiller-nmap** [comment]
This is intended behavior: installing Npcap along with Nmap in silent mode does not support additional installation options. It is recommended to install the latest Npcap first, with whatever installation options you want, then install Nmap with the `/NPCAP=NO` option to skip Npcap installation. A full list of supported options is available in [the Nmap installer source code](https://github.com/nmap/nmap/blob/86f80305a1c0d7cef6b95369fe4bdb590211b612/mswin32/nsis/Nmap.nsi.in#L4-L21).

Note that silent installation is only available with Npcap OEM. If you need to install Npcap silently, you can check out https://npcap.org/oem/ for information about licensing.
