### ISSUE TITLE
segmentation fault  on sslv2-drown

### ISSUE THREAD

**Issue by gsahbi** [nmap/nmap#1879]
Nmap 7.80

nmap -d -vv -sT -sC -sV -A -T4 -p- -O -A -Pn --script vuln -oA full 10.10.10.10
...
NSE: sslv2-drown against 10.10.10.10:5900 threw an error!
/usr/bin/../share/nmap/nselib/vnc.lua:251: bad argument #2 to 'insert' (position out of bounds)
stack traceback:
	[C]: in function 'table.insert'
	/usr/bin/../share/nmap/nselib/vnc.lua:251: in method 'handshake'
	/usr/bin/../share/nmap/nselib/sslcert.lua:614: in upvalue 'special'
	/usr/bin/../share/nmap/nselib/sslcert.lua:813: in local 'starttls'
	/usr/bin/../share/nmap/nselib/sslv2.lua:320: in function 'sslv2.test_sslv2'
	/usr/bin/../share/nmap/scripts/sslv2-drown.nse:286: in function </usr/bin/../share/nmap/scripts/sslv2-drown.nse:225>
	(...tail calls...)

**Comment by nnposter** [comment]
Apparently the same error was only present in nmap version 7.70. Please double-check that file `nselib/vnc.lua` is really from nmap 7.80.

Separately, I assume that you are really reporting this Lua error and not some segmentation fault, correct?

**Comment by nnposter** [comment]
Issue presumably resolved
