### ISSUE TITLE
npcap uninstall minor flaw

### ISSUE THREAD

**Issue by fifteenblade** [nmap/nmap#1884]
Hello,

there's a minor flaw during the npcap uninstall routine.

npcap version: 0.9986
OS: Windows 10 1909

The uninstall routine tries to delete temporary files it generated.
This failed because the uninstall routine has them still in use.
Because of this they are marked for deletion during the next reboot.

![Screenshot_1](https://user-images.githubusercontent.com/8506026/71925929-7835cf00-3192-11ea-9e12-45c776b20b80.png)

![Screenshot_2](https://user-images.githubusercontent.com/8506026/71926017-ae734e80-3192-11ea-87ff-e2688b237a58.png)
![Screenshot_3](https://user-images.githubusercontent.com/8506026/71926035-b8954d00-3192-11ea-8f48-6736e510a510.png)

Solution:
Ajust uninstall routine

**Comment by dmiller-nmap** [comment]
These files are artifacts of the NSIS installer/uninstaller system that Npcap uses. There is no problem, since the files are in an appropriate temporary location and will be deleted at next reboot.
