### ISSUE TITLE
Attempting to index a nil value in http.get_url() when no options parameter is provided

### ISSUE THREAD

**Issue by noglue** [nmap/nmap#1885]
nmap  7.80 on Kali linux.

When using "get_url (u, options)" from "http" class without providing the optional "options" parameter the function call fails with this error:
`/usr/bin/../share/nmap/nselib/http.lua:1798: attempt to index a nil value (local 'options')`

This is caused by the following line in "http":
`options.scheme = options.scheme or parsed.scheme`

I propose the following fix: 
`if (options ~= nil) then`
`options.scheme = options.scheme or parsed.scheme`
`end`

**Comment by nnposter** [comment]
Thank you for reporting the issue. A slightly different fix has been committed as r37865.
