### ISSUE TITLE
Smb-os-discovery script still does not work.

### ISSUE THREAD

**Issue by SleepyLctl** [nmap/nmap#1888]
Hello, even though the issue was reported and fixed, it seems that it's still not working. I just update&upgraded and seems that the problem with os-discovery persists. Previous this was reported as " Nmap 7.80 can no longer run smb-os-discovery script #1808 "

nmap --script=smb-os-discovery -d 10.10.10.3 -p 445
Starting Nmap 7.80 ( https://nmap.org ) at 2020-01-12 11:02 CET
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 11:02
Completed NSE at 11:02, 0.00s elapsed
Initiating Ping Scan at 11:02
Scanning 10.10.10.3 [4 ports]
Packet capture filter (device tun0): dst host 10.10.14.6 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.10.10.3)))
We got a ping packet back from 10.10.10.3: id = 8634 seq = 0 checksum = 56901
Completed Ping Scan at 11:02, 0.12s elapsed (1 total hosts)
Overall sending rates: 33.62 packets / s, 1277.43 bytes / s.
mass_rdns: Using DNS server 192.168.1.1
Initiating Parallel DNS resolution of 1 host. at 11:02
mass_rdns: 0.01s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
Completed Parallel DNS resolution of 1 host. at 11:02, 0.01s elapsed
DNS resolution of 1 IPs took 0.01s. Mode: Async [#: 1, OK: 0, NX: 1, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating SYN Stealth Scan at 11:02
Scanning 10.10.10.3 [1 port]
Packet capture filter (device tun0): dst host 10.10.14.6 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.10.10.3)))
Discovered open port 445/tcp on 10.10.10.3
Completed SYN Stealth Scan at 11:02, 0.11s elapsed (1 total ports)
Overall sending rates: 9.43 packets / s, 414.94 bytes / s.
NSE: Script scanning 10.10.10.3.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 11:02
NSE: Starting smb-os-discovery against 10.10.10.3.
NSE: [smb-os-discovery 10.10.10.3] SMB: Added account '' to account list
NSE: [smb-os-discovery 10.10.10.3] SMB: Added account 'guest' to account list
NSE: [smb-os-discovery 10.10.10.3] SMB: Login as \guest failed (NT_STATUS_LOGON_FAILURE)
NSE: [smb-os-discovery 10.10.10.3] SMB: WARNING: the server appears to be Unix; your mileage may vary.
NSE: [smb-os-discovery 10.10.10.3] SMB: Login as WORKGROUP\<blank> failed, but was given guest access (username may be wrong, or system may only allow guest)
NSE: smb-os-discovery against 10.10.10.3 threw an error!
/usr/bin/../share/nmap/nselib/smb.lua:1030: bad argument #2 to 'unpack' (data string too short)
stack traceback:
        [C]: in function 'string.unpack'
        /usr/bin/../share/nmap/nselib/smb.lua:1030: in function 'smb.negotiate_v1'
        /usr/bin/../share/nmap/nselib/smb.lua:1074: in function 'smb.negotiate_protocol'
        /usr/bin/../share/nmap/nselib/smb.lua:372: in function 'smb.start_ex'
        /usr/bin/../share/nmap/nselib/smb.lua:3363: in function 'smb.get_os'
        /usr/bin/../share/nmap/scripts/smb-os-discovery.nse:152: in function </usr/bin/../share/nmap/scripts/smb-os-discovery.nse:149>
        (...tail calls...)

Completed NSE at 11:02, 2.44s elapsed
Nmap scan report for 10.10.10.3
Host is up, received echo-reply ttl 63 (0.077s latency).
Scanned at 2020-01-12 11:02:06 CET for 2s

PORT    STATE SERVICE      REASON
445/tcp open  microsoft-ds syn-ack ttl 63
Final times for host: srtt: 77297 rttvar: 58773  to: 312389

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 11:02
Completed NSE at 11:02, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 3.80 seconds
           Raw packets sent: 5 (196B) | Rcvd: 2 (72B)

**Comment by frank-leitner** [comment]
Did you apply the fix linked in #1808?
Otherwise it is to be expected to encounter the issue if you use the version that contains the issue.

I just manually applied said fix to my installation of nmap 7.80 and it works.

**Comment by SleepyLctl** [comment]
My bad then, I expected the update is already deployed; I did not manually fix it. Ty then.
