### ISSUE TITLE
Application error (crash) with script http-headers

### ISSUE THREAD

**Issue by lpesyna** [nmap/nmap#1892]
We now have a consistent error in Nmap 7.8 with one particular smart device that is causing an application crash.  We have observed in Windows server 2016 and Windows 7.

Command string as follows and error occurs when http header script is running.

nmap -v -n -PE  -PS8081 -servicedb D:\Nmap\IED-services-fast -T2 --script smb-os-discovery.nse --script-args=smbnoguest -d --script banner --script-args ports=22 --script http-headers <ip>

Revert binaries to Nmap 7.7, leaving nselib and scripts folders as-is and problem goes away.  zlibwapi.dll looks to have been introduced in Nmap 7.8

Faulting application name: nmap.exe, version: 7.0.80.0, time stamp: 0x5d43c16d
Faulting module name: zlibwapi.dll, version: 1.2.11.0, time stamp: 0x5d43c0c1
Exception code: 0xc0000005
Fault offset: 0x000100cf
Faulting process id: 0x2310
Faulting application start time: 0x01d5caf51ccd2678
Faulting application path: C:\Program Files (x86)\Nmap\nmap.exe
Faulting module path: C:\Program Files (x86)\Nmap\zlibwapi.dll
Report Id: 67f8eff2-904a-4c1c-8bb1-3d1234b1ad61
Faulting package full name: 
Faulting package-relative application ID:

**Comment by nnposter** [comment]
This appears to be an instance of issue #1723. If urgent, consider a workaround from #1883; otherwise the issue will be rectified in the next nmap release.

**Comment by lpesyna** [comment]
Thank you, the workaround appears to correct the issue.
