### ISSUE TITLE
Error in ip-geolocation-geoplugin: bad argument #2 to 'lpeg.match'

### ISSUE THREAD

**Issue by fearx135** [nmap/nmap#1894]
Hello I've try to use the ip-geolocation-geoplugin, but there is an error of bad argument 2: Here is the result of the output 
nmap -T1 -sV -p80 --script=ip-geolocation-geoplugin www.target.com
Starting Nmap 7.80 ( https://nmap.org ) at 2020-01-16 01:10 -03
RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Nmap scan report for www.serviciosempresariales.cl (XXX.XX.XXX.X)
Host is up (0.056s latency).

PORT   STATE SERVICE VERSION
80/tcp open  http    Microsoft IIS httpd 10.0
Service Info: OS: Windows; CPE: cpe:/o:microsoft:windows

Host script results:
|_ip-geolocation-geoplugin: bad argument #2 to 'lpeg.match' (string expected, got nil)

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 166.67 seconds

**Comment by nnposter** [comment]
Please re-run nmap with option `-d` and post the full output here.

**Comment by fearx135** [comment]
nmap -sV -p80 --script=ip-geolocation-geoplugin www.own.cl -d
Starting Nmap 7.80 ( https://nmap.org ) at 2020-01-16 10:30 -03
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 46 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 2) scan.
Initiating NSE at 10:30
Completed NSE at 10:30, 0.00s elapsed
NSE: Starting runlevel 2 (of 2) scan.
Initiating NSE at 10:30
Completed NSE at 10:30, 0.00s elapsed
Initiating Ping Scan at 10:30
Scanning www.own.cl (107.22.228.171) [4 ports]
Packet capture filter (device eth0): dst host 192.168.48.129 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 107.22.228.171)))
We got a TCP ping packet back from 107.22.228.171 port 80 (trynum = 0)
Completed Ping Scan at 10:30, 0.03s elapsed (1 total hosts)
Overall sending rates: 134.00 packets / s, 5092.13 bytes / s.
mass_rdns: Using DNS server 192.168.48.2
Initiating Parallel DNS resolution of 1 host. at 10:30
mass_rdns: 0.00s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
Completed Parallel DNS resolution of 1 host. at 10:30, 0.00s elapsed
DNS resolution of 1 IPs took 0.00s. Mode: Async [#: 1, OK: 1, NX: 0, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating SYN Stealth Scan at 10:30
Scanning www.own.cl (107.22.228.171) [1 port]
Packet capture filter (device eth0): dst host 192.168.48.129 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 107.22.228.171)))
Completed SYN Stealth Scan at 10:30, 0.23s elapsed (1 total ports)
Overall sending rates: 8.56 packets / s, 376.58 bytes / s.
Initiating Service scan at 10:30
NSE: Script scanning 107.22.228.171.
NSE: Starting runlevel 1 (of 2) scan.
Initiating NSE at 10:30
NSE: Starting ip-geolocation-geoplugin against www.own.cl (107.22.228.171).
NSE: [ip-geolocation-geoplugin 107.22.228.171] http.request socket error: The script encountered an error:
- ssl failed:
- Failed to connect:
- Could not connect:
- TIMEOUT
NSE: Finished ip-geolocation-geoplugin against www.own.cl (107.22.228.171).
Completed NSE at 10:30, 16.01s elapsed
NSE: Starting runlevel 2 (of 2) scan.
Initiating NSE at 10:30
Completed NSE at 10:30, 0.00s elapsed
Nmap scan report for www.own.cl (107.22.228.171)
Host is up, received reset ttl 128 (0.00053s latency).
rDNS record for 107.22.228.171: ec2-107-22-228-171.compute-1.amazonaws.com
Scanned at 2020-01-16 10:30:19 -03 for 16s

PORT   STATE    SERVICE REASON      VERSION
80/tcp filtered http    no-response

Host script results:
|_ip-geolocation-geoplugin: bad argument #2 to 'lpeg.match' (string expected, got nil)
Final times for host: srtt: 526 rttvar: 5000  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 2) scan.
Initiating NSE at 10:30
Completed NSE at 10:30, 0.00s elapsed
NSE: Starting runlevel 2 (of 2) scan.
Initiating NSE at 10:30
Completed NSE at 10:30, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-service-probes nmap-services.
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 16.79 seconds
           Raw packets sent: 6 (240B) | Rcvd: 1 (40B)

**Comment by nnposter** [comment]
Looks like you might have connectivity issues:
```
NSE: [ip-geolocation-geoplugin 107.22.228.171] http.request socket error: The script encountered an error...
```
For whatever it is worth, I have used the exact command line (with your original target before your edit) and I am getting good results:
```
Nmap scan report for <redacted> (107.22.228.171)
Host is up, received user-set.
Scanned at 2020-01-16 08:40:02 Eastern Standard Time for 3s

PORT   STATE    SERVICE REASON      VERSION
80/tcp filtered http    no-response

Host script results:
| ip-geolocation-geoplugin: coordinates: 39.0481, -77.4728
|_location: Virginia, United States
```

**Comment by fearx135** [comment]
Ok, I'll check, and thankyou!
