### ISSUE TITLE
Nmap 7.80 Bug with Included Version of NPcap on Windows 10

### ISSUE THREAD

**Issue by jandrusk** [nmap/nmap#1897]
When installing NMap 7.80 on Windows 10 and leaving the defaults after the install is complete, we are not able to communicate with our internal CA using either the MMC snap-in or using the certutil command to ping our CA. The communication uses RPC ports in the 64,000 range. 

I have been able to isolate this to the version of NPcap that is included with the NMap 7.80 installation. If NPcap is unselected the problem is not reproduced. Also, installing the standalone version of NPCap doesn't reproduce the issue. 

Uninstalling NMap 7.80 and the included version of NPcap does not return the system to the original functional state.

**Comment by dmiller-nmap** [comment]
Thanks for this bug report. Fortunately, you have already discovered that the latest version of Npcap is not subject to the same issue. We do not upgrade Nmap Windows installers to a later version of Npcap without a corresponding Nmap release, so the recommended course of action is always to update Npcap separately, ensuring the latest version with the latest bugfixes.
