### ISSUE TITLE
Debian 9  Ncat: Invalid proxy type "socks5". QUITTING.

### ISSUE THREAD

**Issue by pdarcos** [nmap/nmap#1901]
Hi all,

I'm on Debian 9 and installed Ncat via apt. (apt install nmap)
Ncat version is 7.40

When I try to create a socks proxy (have tried socks4 and socks5) with the following command I get the error mentioned in the title:
ncat -l 3128 --proxy-type socks5
Ncat: Invalid proxy type "socks5". QUITTING.

When I check ncat -h I see that it correctly lists the proxy options as http, socks4 and socks5. But only http works.

Any idea what's wrong? Do I need to install some other package on debian to get socks functionality with Ncat?

Cheers

**Comment by nnposter** [comment]
Ncat can use all three types of proxy as a client but it can only act as HTTP proxy.
