### ISSUE TITLE
nmap error execution script discovery

### ISSUE THREAD

**Issue by pokolhaboru** [nmap/nmap#1906]
Hi all,

When I put the --script=discovery on new Kali Linux, he abort with this message nmap: nse_nsock.cc:369: void callback(nsock_pool, nsock_event, void*): Assertion `lua_status(L) == LUA_YIELD' failed.

When I put like --script=smb-* it runs with no errors.

**Comment by nnposter** [comment]
Can you isolate which specific script is causing the the assertion error?

**Comment by nnposter** [comment]
Issue apparently resolved/abandoned.
