### ISSUE TITLE
Useage of broadcast-dhcp-discover script to detect rogue/foreign DHCP servers

### ISSUE THREAD

**Issue by smuellener** [nmap/nmap#1908]
Hello I would like to use the script broadcast-dhcp-discover to discover rogue DHCP servers. For this I would need to:

1) get all DHCP servers found using the script
2) remove whitelisted servers (e.g. 172.20.1.1)
3) report warning about any rogue servers

As I understand it, currently the script only returns first found DHCP response per interface (so a list of results but only one per interface). @bonsaiviking is that correct and would you agree on changing this to returning all servers found?

**Comment by dmiller-nmap** [comment]
I agree the current script is not doing what we want. I'm pushing a change now to allow receiving more than 1 response per interface, as well as fixing the problem that it was not ever returning more than 1 response, regardless of how many interfaces it tried to run on.

**Comment by smuellener** [comment]
Awesome thanks! Looking forward to testing this...
