### ISSUE TITLE
Npcap : Installation aborted

### ISSUE THREAD

**Issue by AE0n-exe** [nmap/nmap#1913]
Hi.
I have a problem with the npcap setup.
When I launch installation, I only see this message :
"Installation aborted"
"Setup was not completed successfully."
In "Show details", I only have "Stopping the npcap driver".

Can you help me ?

**Comment by dmiller-nmap** [comment]
Thanks for this report. Npcap 0.9988 fixes several issues related to broken installs and installation failures. Please let us know if this update solves your issue.
