### ISSUE TITLE
NMAP dnet: Failed to open device eth4

### ISSUE THREAD

**Issue by 2337914955** [nmap/nmap#1915]
hello，I have a problem，today，I used nmap to scan the site,But it went wrong
dnet: Failed to open device eth4
QUITTING!
Thanks for your help！
![image](https://user-images.githubusercontent.com/45325321/74099265-b5f49180-4b5c-11ea-9b4f-6397aac2efa9.png)
nmap -d --iflist.txt：[nmap -d --iflist.txt](https://github.com/nmap/nmap/files/4176632/nmap.-d.--iflist.txt)

**Comment by dmiller-nmap** [comment]
The error, "dnet: Failed to open device" is a symptom of an issue with Npcap. Please install [the latest Npcap](https://npcap.com/#download) and try again. If the issue persists, please [open a bug report for Npcap](https://issues.npcap.org/).
