### ISSUE TITLE
TTL from --reason not in gnmap output

### ISSUE THREAD

**Issue by drwetter** [nmap/nmap#1920]
Hi,

while processing a bunch of gnmap files with a script it looks to me like the information from ``--reason`` is missing in the gnmap output:

```
dirks@laptop:~|0% sudo nmap -sS  --reason -Pn -p443  insecure.org 
Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-13 11:52 CET
Nmap scan report for insecure.org (45.33.49.119)
Host is up, received user-set (0.18s latency).
Other addresses for insecure.org (not scanned): 2600:3c01::f03c:91ff:fe98:ff4e
rDNS record for 45.33.49.119: ack.nmap.org

PORT    STATE SERVICE REASON
443/tcp open  https   syn-ack ttl 41

Nmap done: 1 IP address (1 host up) scanned in 0.29 seconds
dirks@laptop:~|0% sudo nmap -sS -v --reason -Pn -p443  insecure.org  -oG -
# Nmap 7.80 scan initiated Thu Feb 13 11:54:56 2020 as: nmap -sS -v --reason -Pn -p443 -oG - insecure.org
# Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
Host: 45.33.49.119 (ack.nmap.org)       Status: Up
Host: 45.33.49.119 (ack.nmap.org)       Ports: 443/open/tcp//https///
# Nmap done at Thu Feb 13 11:54:56 2020 -- 1 IP address (1 host up) scanned in 0.29 seconds
dirks@laptop:~|0% 
```
The latter shows that none of the _reason_ fields _syn-ack ttl 41_ was transferred.

Or do I miss something?

Needless to say but from the user perspective this would be appreciated as for broader scans one  could tell better whether a device itself has a service or something which is further away.

Cheers, Dirk

PS: XML output seems fine:
```
dirks@laptop:~|0% sudo nmap -sS -v --reason -Pn -p443  insecure.org  -oX - | grep reason_ttl
<host starttime="1581591342" endtime="1581591342"><status state="up" reason="user-set" reason_ttl="0"/>
<ports><port protocol="tcp" portid="443"><state state="open" reason="syn-ack" reason_ttl="41"/><service name="https" method="table" conf="3"/></port>
dirks@laptop:~|0% 
```

**Comment by dmiller-nmap** [comment]
[Grepable output is deprecated](https://nmap.org/book/output-formats-grepable-output.html), which means that the format will not continue to be extended. This is mostly because it is not a very extensible format; changes would break many scripts that use the format. XML output has been the recommended machine-readable output format since [Nmap 2.45BETA6](https://nmap.org/changelog.html#2.54BETA6) in October 2000.

**Comment by drwetter** [comment]
Am 13. Februar 2020 21:35:39 MEZ schrieb Daniel Miller <notifications@github.com>:
>[Grepable output is
>deprecated](https://nmap.org/book/output-formats-grepable-output.html),
>which means that the format will not continue to be extended. This is
>mostly because it is not a very extensible format; changes would break
>many scripts that use the format. XML output has been the recommended
>machine-readable output format since [Nmap
>2.45BETA6](https://nmap.org/changelog.html#2.54BETA6) in October 2000.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nmap/nmap/issues/1920#issuecomment-585959399

Good to know, thanks.

Is there a *good* converter for XML to CSV? Or any planning for native CSV output?


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection
