### ISSUE TITLE
Windows 10 1909 18363.657安装npcap 版本0.9986和0.9987均导致蓝屏，安装时在加载npcap的驱动过程中蓝屏

### ISSUE THREAD

**Issue by l1TTss** [nmap/nmap#1924]
开发人员你们好，我的系统是Windows 10 1909 18363.657安装npcap 版本0.9986和0.9987均导致蓝屏，安装时在加载npcap的驱动过程中蓝屏。电脑是Dell Inspiron 灵越 15 7000系列的，网卡是Intel wireless-AC 9560，电脑有安装wireshark 3.2.1，但是，我把wireshark3.2.1卸载了，单独安装npcap也是会导致电脑蓝屏的。
该问题我的系统在Windows 10 1909 18363.476版本时安装npcap 版本0.9986都没导致电脑蓝屏，在Windows 10 1909 18363.657尝试测试安装近期各个版本的npcap均导致电脑蓝屏，同时，本人发现一个奇怪的问题，npcap 0.9986成功安装后，本人升级了Intel显卡驱动（Intel-UHD-Graphics-Driver_WXYJ9_WIN_26.20.100.7637_A03），重启系统后，发现npcap组件已失效，wireshark无法查看到任何网卡，重新卸载npcap 9.9986再重装，又导致系统蓝屏，后来我只好装历史版本0.9982才没有导致系统蓝屏了，现在的npcap兼容操作系统和网卡的能力比不上原来winpcap的，还请开发人员能仔细测试，做好兼容性适配工作，一方面积极与微软Windows 10开发人员协调帮助，一方面与各网卡生产厂商驱动开发人员协调帮助，谢谢你们的付出，真的辛苦了。

**Comment by imagebreaker** [comment]
Actually, I met the same problem with you, with the OS vesion 1909 18363.657.

**Comment by dmiller-nmap** [comment]
Thank you for this bug report. In order to diagnose a blue screen crash, we need the kernel minidump file from `C:\Windows\Minidump\`. You can send this file privately to me: dmiller@nmap.com.
