### ISSUE TITLE
100 second hard limit 10 year fatal should be removed

### ISSUE THREAD

**Issue by nickb937** [nmap/nmap#1930]
$ ncat --wait 120 193.168.1.3 554
Ncat: Since April 2010, the default unit for -w timeout is seconds, so your time of "120" is 2.0 minutes. Use "120ms" for 120 milliseconds. QUITTING.

I wanted a 2 minute wait, maybe even 5.  Software says NO.

**Comment by gvanem** [comment]
Use `ncat --wait 2m 193.168.1.3 554` instead.

**Comment by nnposter** [comment]
The abort is executed only if the the timeout value is over 100 *and the time unit is not specified*. As such, you can use Gisle's example of `2m` or simply `120s` if you want to stick with seconds.
