### ISSUE TITLE
Install of npcap-0.9987.exe on Windows 10 corrupted

### ISSUE THREAD

**Issue by Hilary-M** [nmap/nmap#1935]
[install.log](https://github.com/nmap/nmap/files/4260876/install.log)
When I started the install there was pop-up indicating that I should select yes to restart the computer so that uninstall would work.

I selected yes and the computer restart.
Then I ran the install again and got an error message that the install failed
Now the install is failed and there is no uninstaller
I will attach the install log and a screen capture
![image](https://user-images.githubusercontent.com/13766190/75433054-fc940b00-5914-11ea-952d-f7173300cafe.png)

**Comment by dmiller-nmap** [comment]
Thanks for this report. We are working on improvements to the installer so it can continue in cases like this, but we do try to warn before removing WinPcap that if it prompts for a restart, you should choose "later."

**Comment by dmiller-nmap** [comment]
Npcap 0.9988, released today, makes certain changes to how it invokes the WinPcap uninstaller that should prevent a reboot after uninstalling in the majority of cases. It also is more tolerant of partial installations resulting from past installer failures, so it should be possible to fix your installation by running the Npcap 0.9988 installer.
