### ISSUE TITLE
 wireshark can't find NPF file

### ISSUE THREAD

**Issue by yheon** [nmap/nmap#1937]
I used Wireshark until 8 days ago with no problems. but when  I opened the program today. I got this error:The capture session could not be initiated on interface '\Device\NPF_Loopback' (Error opening adapter: The system cannot find the path specified. (3)). So I googled this error code 3. But I couldn't find satisfaction solution. In addition,I couldn't find Device folder in my computer.

**Comment by yheon** [comment]
I removed it and download  again.

**Comment by guyharris** [comment]
> I removed it and download again.

"It" presumably being Npcap rather than Wireshark, right?

By the way, there *isn't* a \Device folder that you could see with, for example, File Explorer - that's an internal "symbolic link" in the NT kernel, not a name in the file system.  The error message is a little bit confusing.

**Comment by yheon** [comment]
Thank you. before seeing your answer, I tried making a folder named device in c:/Windows/. Now I can use Wireshark.!!!!  thank you for your answer.

**Comment by dmiller-nmap** [comment]
Npcap 0.9989 will no longer list the NPF_Loopback device if it is not available for capture.
