### ISSUE TITLE
Error code 433, "A device which does not exist was specified." error when opening the loopback device?

### ISSUE THREAD

**Issue by guyharris** [nmap/nmap#1948]
Some Wireshark users have been reporting an error "\Device\NPF_Loopback' (Error opening adapter: A device which does not exist was specified. (433)".  See, for example, [this question on the Wireshark Q&A site](https://ask.wireshark.org/question/12810/error-when-trying-to-start-capture/), as well as issues #1793 and #1944.

A Google search for

    "A device which does not exist was specified." 433

found a bunch of other reports of that issue *not* mentioning Wireshark or Npcap and *not* having anything to do with packet capture.

[Microsoft's page for Windows error codes from 0 to 499](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) doesn't list 433.  [This answers.microsoft.com page](https://answers.microsoft.com/en-us/windows/forum/windows_7-system/blue-screen-61760121025648/f488ea66-690a-4749-9fd2-f26601f2c9a5) shows an NT status code of 0xc000000e being associated with that error; [Microsoft's list of NT status codes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) shows 0xc000000e as `STATUS_NO_SUCH_DEVICE`.

The master branch of npcap doesn't show any code checking for, or returning, or doing anything *else* with `STATUS_NO_SUCH_DEVICE`, nor does it show any reference to 433.

Any idea what could be going on here?  The "Error opening adapter" part of the message comes from `pcap_activate_npf()` - it calls `PacketOpenAdapter()` and, if that returns NULL, if the error code is `ERROR_BAD_UNIT`, it returns `PCAP_ERROR_NO_SUCH_DEVICE`, but, for any other error code, it returns `PCAP_ERROR` and, at least in the master libpcap branch, formats an error message using `pcap_fmt_errmsg_for_win32_err()`, which uses `FormatMessageA()` to get an error message for the error code, so I *guess* Microsoft's FormatMessage code turns 433 into "A device which does not exist was specified.", even though 433 isn't documented.

**Comment by guyharris** [comment]
433 is `ERROR_NO_SUCH_DEVICE`, which is in winerror.h but is *NOT* documented on the 0-499 error code page.  Currently, nothing in the tip of the npcap master branch has `ERROR_NO_SUCH_DEVICE` in it.

**Comment by dmiller-nmap** [comment]
This particular one is probably a result of the behavior of Npcap 0.9983 - 0.9987 where the `\Device\NPF_Loopback` device will be returned from a call to `PacketGetAdapterNames()` (or `pcap_findalldevs()`) even if the `npcap` driver is not running. Npcap 0.9988 changes this so that the loopback device will only be displayed if it can successfully be opened for capture (63f7e3e8363).

I'm basing this guess on #1944, where the user determined that the driver service was not running. There may be a separate issue causing the driver to not run on those systems, so we'll see if that is reported for Npcap 0.9988.

**Comment by guyharris** [comment]
> This particular one is probably a result of the behavior of Npcap 0.9983 - 0.9987 where the `\Device\NPF_Loopback` device will be returned from a call to `PacketGetAdapterNames()` (or `pcap_findalldevs()`) even if the `npcap` driver is not running.

So is the issue here that, if you try to open an interface, Packet32.dll checks whether it knows about it, in the sense of "would `pcap_findalldevs()` return it?" and, if not, returns ` ERROR_BAD_UNIT`, but if it knows about it, it (or the helper) makes a `CreateFileA()` call on a device symbolic link, expecting it to succeed, given that it's already determined whether the interface exists, but it *doesn't* exist, so `ERROR_NO_SUCH_DEVICE` is returned by the NT kernel because it fails to find the symbolic link in question due to the Npcap driver not running?

**Comment by dmiller-nmap** [comment]
Yes, that sounds correct.

**Comment by dmiller-nmap** [comment]
Since Npcap 0.9988, the NPF_Loopback device will not be shown if it is not available for capture.
