### ISSUE TITLE
Npcap still checks _WINNT4?

### ISSUE THREAD

**Issue by guyharris** [nmap/nmap#1950]
If `_WINNT4` means what I suspect it does, the checks for it in Packet32.cpp and Packet32-Int.h are *way* out of date, especially given that you just dropped *Windows Vista* support.

The code might be slightly cleaner if it weren't trying to make sure it'd still build for NT 4.0.

**Comment by guyharris** [comment]
There's also some commented-out code in `PacketOpenAdapterNPF()` that checks for NT 4; that should probably also be removed.

**Comment by dmiller-nmap** [comment]
Thanks. We tend to leave well enough alone, so stuff that "just works" is ignored. I've got a cleanup of Packet.dll on my to-do list, so I'll add this to it.
