### ISSUE TITLE
Need help for using npcap on windows to catch multicast

### ISSUE THREAD

**Issue by zeerd** [nmap/nmap#1959]
I am using the npcap(0.9986) to catch some packages on a win10.

I could catch the normal UDP packages , so seems the basic setting is OK for my program.

But I could not catch any multicast packages.

At this moment, I start a Wireshark on the same win10 computer. My program could catch those multicast packages now, like the WireShark doing.

And Then, I close the WireShark, and my programe could not catch any multicast, again.

So, I think there must be something that the WireShark done, but my program missed.

Could any body give me some hint for this?

**Comment by guyharris** [comment]
> At this moment, I start a Wireshark on the same win10 computer. My program could catch those multicast packages now, like the WireShark doing.

Are you capturing in promiscuous mode?

If your program calls `pcap_open_live()`, the third argument must be 1.

If it calls `pcap_create()` and `pcap_activate()`, you must call `pcap_set_promisc(), with the first argument being the `pcap_t *` you got as a return value from `pcap_create()`, and the second argument being 1, after calling `pcap_create()` and before calling `pcap_activate()`.

Promiscuous mode is *not* a per-program setting, it's a per-network-interface setting, so if Wireshark puts the interface into promiscuous mode (which, by default, it does), that means that *all* programs capturing on that interface - including your program if it's capturing on that interface - will be capturing in promiscuous mode.  When Wireshark exits, the interface will no longer be in promiscuous mode.

If there's more than one program capturing in promiscuous mode on an interface, the interface is in promiscuous mode until the last such program stops capturing on the interface.

**Comment by dmiller-nmap** [comment]
> If there's more than one program capturing in promiscuous mode on an interface, the interface is in promiscuous mode until the last such program stops capturing on the interface.

I would have to test to verify, but I think we fixed this particular behavior in #1035. As soon as the promiscuous capture handle is closed, the adapter reverts to the non-promiscuous packet filter for all remaining handles.

**Comment by guyharris** [comment]
> > If there's more than one program capturing in promiscuous mode on an interface, the interface is in promiscuous mode until the last such program stops capturing on the interface.
> 
> I would have to test to verify, but I think we fixed this particular behavior in #1035. As soon as the promiscuous capture handle is closed, the adapter reverts to the non-promiscuous packet filter for all remaining handles.

Presumably meaning "a handle on which `NDIS_PACKET_TYPE_PROMISCUOUS` is the filter will receive all packets and, as long as one or more handles have `NDIS_PACKET_TYPE_PROMISCUOUS` as the filter, all other handles, whether they have `NDIS_PACKET_TYPE_PROMISCUOUS` as the filter or not, will also receive all packets; as soon as no handles have `NDIS_PACKET_TYPE_PROMISCUOUS` as the filter, all handles will receive packets according to their filter".  For programs using the pcap API, non-promiscuous handles have

    NDIS_PACKET_TYPE_ALL_LOCAL |  NDIS_PACKET_TYPE_DIRECTED |
        NDIS_PACKET_TYPE_BROADCAST | NDIS_PACKET_TYPE_MULTICAST

as their filter.

**Comment by zeerd** [comment]
Sorry！My mistake.

I found the reason. I haven't used the promisc mode from the pcap_open_live() by the right way.
When I changed this promiscuous mode from 0 to 1, the issue resolved.

Whatever, hope you could add some description into the SDK, not all the user ,like me, known what is the promisc mode. We just copy the example from internet and catch something...
