### ISSUE TITLE
Memory leak in npcap 0.9988 with data on loopback when capture another eth?

### ISSUE THREAD

**Issue by yyjdelete** [nmap/nmap#1966]
Tested with npcap 0.9988 + win10

A lot of memory leak happen on paged pools with tag `Mdl` and `NPBL`. [NPBL](https://github.com/nmap/npcap/blob/1ca9e3c382153301e2950f92c66a400093cc6cf4/packetWin7/npf/npf/Loopback.c#L292) is only used by npcap.sys, and it leak 50% of allocs, and also the same leak count for `Mdl`.

This only happen for me when a lot of data is send and recv though loopback, and an capture (can also be tested with wireshark) on another eths.
(***EVEN when loopback is not captured***, which I used to think npcap should do nothing in this case, is it another bug?)

https://github.com/nmap/npcap/blob/39b72d0f71ebd905e840f36c5fd1a59721687f7d/packetWin7/npf/npf/Loopback.c#L439-L440
Is the comments here and `NET_BUFFER_NEXT_NB` really right? Seems the above logic didn't skip the first node.

![image](https://user-images.githubusercontent.com/1819074/76632542-57b53700-657e-11ea-8afa-0a1ae10d3f8d.png)
Use https://github.com/zodiacon/AllTools/blob/master/PoolMonXv2.exe, can also get almost the same result with poolmon from Mircosoft.

**Comment by dmiller-nmap** [comment]
Thanks for this report. This is new code in this version, but I'm disappointed I didn't catch this leak. I'll take a look at the function in question. Npcap does not unregister its WFP filter when the loopback handle is closed, which is why the leaks continue even when loopback capture is stopped. We may consider doing that to limit performance impact in the future.

**Comment by dmiller-nmap** [comment]
You were right about NET_BUFFER_NEXT_NB: though we need to skip freeing the first NB, we still need to free the MDL (tag 'Mdl') and its associated buffer (tag 'NPBL'), and that is what was leaking. We'll be doing a release soon with this fix.

**Comment by dmiller-nmap** [comment]
***WORKAROUND:*** Until the next release can be made, a workaround is to disable loopback capture: Set the Registry value `HKLM\SYSTEM\CurrentControlSet\Services\npcap\Parameters\LoopbackSupport` to `0x0` and restart the npcap driver service: `net stop npcap; net start npcap`. This change will persist across reboots, but may be reset by the next installation or upgrade.
