### ISSUE TITLE
Npcap 0.9988 IntelNic with VLAN Virtual Interface Windows 7 BSOD

### ISSUE THREAD

**Issue by jodern** [nmap/nmap#1971]
Hi, I had a constant crash after updating my npcap to version 0.9988. 
My machine has Intel Nic with multiple VLAN interface attached. 

The BSOD Message is always IRQL_NOT_LESS_OR_EQUAL.
I had reverted to version 0.93 and using this version to generate my DiagReport. 
[DiagReport-20200317-175029.txt](https://github.com/nmap/nmap/files/4342708/DiagReport-20200317-175029.txt)
[minidump.zip](https://github.com/nmap/nmap/files/4342723/minidump.zip)

**Comment by dmiller-nmap** [comment]
Thanks for this report. This crash was previously reported as #1964 and will be fixed in the next release which is currently in testing.
