### ISSUE TITLE
Feature request: deduplicate lists of ips and ports to scan

### ISSUE THREAD

**Issue by Viss** [nmap/nmap#1973]
The verison I'm on is 7.70SVN, but I'm betting this hasn't been addressed in any later versions since its fairly under-the-hood

So let's say that you're gonna scan 50 domain names, and all of those domain names resolve to the same ip address - nmap will actually conduct 50 scans against the same ip and ports. 

I understand that vhosts are a thing, and largely this affects things like screenshotting websites, but if FTP is open on some shared hosting provider, nmap will do 50 scans against the same ip, on port 21, and return 50 results for the exact same ftp server.

It stands to reason that by augmenting how nmap does the accounting of  "what to scan", performance can be dramatically improved by making decisions about what ip and ports to scan based on resolving hostnames to ips and then deduplicating it all before the scan begins.

**Comment by Viss** [comment]
I can see from the perspective of running scripts, especially against webservers, that - absolutely, using the domain name to make that connection will vary from name to name on the same ip, but to "simply tell if the port is open or closed", if all 50 domain names are aimed at the same ip, there's no reason to scan that ip 50 times.

**Comment by dmiller-nmap** [comment]
This is an interesting idea. Nmap's current scan behavior can't support it,
though: there's nothing that keeps track of what IPs are in the scan queue
or have been completed in an earlier hostgroup. It would be easier to add
this after splitting out forward lookups into their own parallel scan phase
(I will link a related issue later).

For now, the best and fastest way to do this is to use a separate
purpose-built tool to do your forward lookups, then strip out duplicates
and feed the list to Nmap with -iL.

**Comment by Viss** [comment]
okiedokie! I'll tweak the stuff I'm working on to do all the deduping up front before nmap gets involved!

**Comment by dmiller-nmap** [comment]
Turns out this was much simpler than I was thinking. The new `--unique` option uses a Nmap's new-ish fast-lookup target exclusion code to prevent a target from being scanned twice. Fixed in 0de714e
