### ISSUE TITLE
npcap.sys 0.9988 memory leaks on Windows 10 x64

### ISSUE THREAD

**Issue by rampageX** [nmap/nmap#1976]
Process Hacker:
![ph](https://user-images.githubusercontent.com/994081/77050776-354f6d80-6a05-11ea-81bb-b32b9bba6c1a.png)

PoolMon:
![pm](https://user-images.githubusercontent.com/994081/77050805-400a0280-6a05-11ea-9aaa-cf63db7f6c6d.png)

Tag Search:

![npcap](https://user-images.githubusercontent.com/994081/77050833-4c8e5b00-6a05-11ea-873b-11aa1e2bbdad.png)

**Comment by rampageX** [comment]
0.9987 no problem.

**Comment by dmiller-nmap** [comment]
Thanks for this report. This has been previously reported as #1966 and will be fixed in the next release.
