### ISSUE TITLE
Shellshock Detection Script Inconsistencies

### ISSUE THREAD

**Issue by unKn0wnUser453** [nmap/nmap#1983]
NSE: http-shellshock.nse

Edits Requested:
Line 89: cmd = '() { :;}; echo; /bin/bash -c '..cmd
Line 99: Comment out line 99

Different results with/without line 99
Suggest either take it out or do 2 request with/without.

For line 89, adding the echo before the command would ensure the response has a blank line after the header.

**Comment by nnposter** [comment]
Could you please elaborate on the rationale for the additional bash wrapper?

@cldrn Is there a case for using the payload as a header *name*? It seems to me that doing so might result in HTTP 400 while the chance of executing is limited, especially since the payload contains a colon so whatever primitive parsing might try to accept the header is bound to trim or split the payload.

**Comment by cldrn** [comment]
The example vulnerable application we used to write that script was vulnerable via header injection. I think at that time there were a couple of products affected by the injection via headers but i can't recall which ones. 

The VM is still available here:
https://drive.google.com/file/d/0BzPR8exG0kt6eUtBZ1NjekRNblE/view?usp=sharing

**Comment by nnposter** [comment]
Thank you for the quick response. I have run the VM and it appears *not* vulnerable when the payload is used as a header *name*. (It is vulnerable when the same payload is used as a value for a regular header.)

Considering this observed test, combined with my earlier rationale, do you see a reason why we should keep populating a header name with the payload?

**Comment by cldrn** [comment]
Hi,

It makes sense to remove it if it does not work as expected. I thought we included there for a reason (that VM) but it could be that it never worked as intended so feel free to remove the payload from the header.

**Comment by nnposter** [comment]
The header name payload has been removed in r37990.
