### ISSUE TITLE
http-default-accounts

### ISSUE THREAD

**Issue by jilani97** [nmap/nmap#1984]
Im trying to use the default accounts script to check for default password on my router, which I know is admin:admin, I also added that in the fingreprints lua file to the Cisco router. But I get an ssl error in the debug. 

Command used: nmap -d2 -sV --script=http-default-accounts 192.168.0.1

**Comment by nnposter** [comment]
Please provide output from the following scan:
```
nmap -n -Pn --script http-default-accounts --script-args name=cisco -T2 -d3 -pXXX 192.168.0.1
```
where `XXX` is whatever port you use for the router admin interface.

**Comment by jilani97** [comment]
Hi,

I am not sure if it is port 8080 or 80 (tcpwrapped), but Ill provide the
output from 80:
PS C:\WINDOWS\system32> nmap -n -Pn --script http-default-accounts
--script-args name=cisco -T2 -d3 -p80 192.168.0.1
Trying to initialize Windows pcap engine
npcap service is already running.
wpcap.dll present, library version: Npcap version 0.9986, based on libpcap
version 1.9.1
Starting Nmap 7.80 ( https://nmap.org ) at 2020-03-31 20:53 W. Europe
Daylight Time
Fetchfile found C:\Program Files (x86)\Nmap/nmap-services
Fetchfile found C:\Program Files (x86)\Nmap/nmap.xsl
The max # of sockets we are using is: 1
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 1
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
Fetchfile found C:\Program Files (x86)\Nmap/nse_main.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/lpeg-utility.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/stdnse.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/strict.lua
Fetchfile found C:\Program Files (x86)\Nmap/scripts\script.db
Fetchfile found C:\Program Files (x86)\Nmap/nselib/tableaux.lua
NSE: Arguments from CLI: name=cisco
NSE: Arguments parsed: name=cisco
NSE: {
        ["name"] = "cisco",
}
Fetchfile found C:\Program Files
(x86)\Nmap/scripts\http-default-accounts.nse
NSE: Script http-default-accounts.nse was selected by name.
Fetchfile found C:\Program Files (x86)\Nmap/nselib/creds.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/ipOps.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/stringaux.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/unittest.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/nsedebug.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/listop.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/http.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/base64.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/comm.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/oops.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/sasl.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/smbauth.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/unicode.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/shortport.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/slaxml.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/url.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/idna.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/punycode.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/data/idnaMappings.lua
NSE: Loaded 1 scripts for scanning.
NSE: Loaded 'C:\Program Files (x86)\Nmap/scripts\http-default-accounts.nse'.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 20:53
Completed NSE at 20:53, 0.00s elapsed
Fetchfile found C:\Program Files (x86)\Nmap/nmap-payloads
Initiating ARP Ping Scan at 20:53
Scanning 192.168.0.1 [1 port]
Packet capture filter (device eth4): arp and arp[18:4] = 0x8C705A9D and
arp[22:2] = 0xA964
**TIMING STATS** (1.8560s): IP, probes
active/freshportsleft/retry_stack/outstanding/retranwait/onbench,
cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 0/*/*/*/*/* 1.00/75/* 200000/-1/-1
Current sending rates: 0.00 packets / s.
Overall sending rates: 0.00 packets / s.
Ultrascan timeout init for 192.168.0.1 at 1585680837.508000
SENT (1.9460s) ARP who-has 192.168.0.1 tell 192.168.0.37
**TIMING STATS** (1.9610s): IP, probes
active/freshportsleft/retry_stack/outstanding/retranwait/onbench,
cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 1/*/*/*/*/* 1.00/75/* 200000/-1/-1
Current sending rates: 2.39 packets / s, 100.48 bytes / s.
Overall sending rates: 2.39 packets / s, 100.48 bytes / s.
RCVD (1.9620s) ARP reply 192.168.0.1 is-at 08:80:39:DF:FB:2F
Found 192.168.0.1 in incomplete hosts list.
ultrascan_host_probe_update called for machine 192.168.0.1 state UNKNOWN ->
HOST_UP (trynum 0 time: 17000)
Changing ping technique for 192.168.0.1 to ARP
Moving 192.168.0.1 to completed hosts list with 0 outstanding probes.
Changing global ping host to 192.168.0.1.
Completed ARP Ping Scan at 20:53, 0.42s elapsed (1 total hosts)
Overall sending rates: 2.38 packets / s, 100.00 bytes / s.
pcap stats: 4 packets received by filter, 0 dropped by kernel.
Initiating SYN Stealth Scan at 20:53
192.168.0.1 pingprobe type ARP is inappropriate for this scan type;
resetting.
Scanning 192.168.0.1 [1 port]
Packet capture filter (device eth4): dst host 192.168.0.37 and (icmp or
icmp6 or ((tcp or udp or sctp) and (src host 192.168.0.1)))
**TIMING STATS** (1.9640s): IP, probes
active/freshportsleft/retry_stack/outstanding/retranwait/onbench,
cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 0/*/*/*/*/* 1.00/75/* 1000000/-1/-1
Current sending rates: 0.00 packets / s.
Overall sending rates: 0.00 packets / s.
Ultrascan timeout init for 192.168.0.1 at 1585680837.927000
SENT (2.3700s) TCP [192.168.0.37:64653 > 192.168.0.1:80 S seq=354869565
ack=0 off=6 res=0 win=1024 csum=0x1F6E urp=0 <mss 1460>] IP [ver=4 ihl=5
tos=0x00 iplen=44 id=39188 foff=0 ttl=40 proto=6 csum=0x7841]
**TIMING STATS** (2.3700s): IP, probes
active/freshportsleft/retry_stack/outstanding/retranwait/onbench,
cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 1/*/*/*/*/* 1.00/75/* 1000000/-1/-1
Current sending rates: 2.46 packets / s, 108.11 bytes / s.
Overall sending rates: 2.46 packets / s, 108.11 bytes / s.
RCVD (2.3710s) TCP [192.168.0.1:80 > 192.168.0.37:64653 SA seq=1083151140
ack=354869566 off=6 res=0 win=16384 csum=0x135D urp=0 <mss 512>] IP [ver=4
ihl=5 tos=0x00 iplen=44 id=63273 foff=0 ttl=64 proto=6 csum=0x022c]
Found 192.168.0.1 in incomplete hosts list.
Discovered open port 80/tcp on 192.168.0.1
Changing ping technique for 192.168.0.1 to tcp to port 80; flags: S
Moving 192.168.0.1 to completed hosts list with 0 outstanding probes.
Changing global ping host to 192.168.0.1.
Completed SYN Stealth Scan at 20:53, 0.41s elapsed (1 total ports)
Overall sending rates: 2.44 packets / s, 107.58 bytes / s.
pcap stats: 6 packets received by filter, 0 dropped by kernel.
NSE: Script scanning 192.168.0.1.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 20:53
NSE: Starting http-default-accounts M:44FD974 against 192.168.0.1:80.
NSOCK INFO [1.2200s] nsock_iod_new2(): nsock_iod_new (IOD #1)
NSOCK INFO [2.3740s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #1) EID 8
NSOCK INFO [2.3760s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 8 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51932 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51932 > 192.168.0.1:80 | 00000000: 16 03 00 00 69 01
00 00 65 03 03 55 1c a7 e4 72     i   e  U   r
00000010: 61 6e 64 6f 6d 31 72 61 6e 64 6f 6d 32 72 61 6e andom1random2ran
00000020: 64 6f 6d 33 72 61 6e 64 6f 6d 34 00 00 0c 00 2f dom3random4    /
00000030: 00 0a 00 13 00 39 00 04 00 ff 01 00 00 30 00 0d      9       0
00000040: 00 2c 00 2a 00 01 00 03 00 02 06 01 06 03 06 02  , *
00000050: 02 01 02 03 02 02 03 01 03 03 03 02 04 01 04 03
00000060: 04 02 01 01 01 03 01 02 05 01 05 03 05 02

NSOCK INFO [2.3760s] nsock_write(): Write request for 110 bytes to IOD #1
EID 19 [192.168.0.1:80]
NSOCK INFO [2.3760s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 19 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51932 > 192.168.0.1:80 | SEND
NSOCK INFO [2.3770s] nsock_read(): Read request from IOD #1 [192.168.0.1:80]
(timeout: 7000ms) EID 26
NSOCK INFO [9.3780s] nsock_trace_handler_callback(): Callback: READ TIMEOUT
for EID 26 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51932 > 192.168.0.1:80 | CLOSE
NSOCK INFO [9.3780s] nsock_iod_delete(): nsock_iod_delete (IOD #1)
NSOCK INFO [9.3780s] nsock_iod_new2(): nsock_iod_new (IOD #2)
NSOCK INFO [9.3830s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #2) EID 32
NSOCK INFO [9.4600s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 32 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51933 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51933 > 192.168.0.1:80 | 00000000: 16 03 00 00 53 01
00 00 4f 03 00 3f 47 d7 f7 ba     S   O  ?G
00000010: 2c ee ea b2 60 7e f3 00 fd 82 7b b9 d5 96 c8 77 ,   `~    {    w
00000020: 9b e6 c4 db 3c 3d db 6f ef 10 6e 00 00 28 00 16     <= o  n  (
00000030: 00 13 00 0a 00 66 00 05 00 04 00 65 00 64 00 63      f     e d c
00000040: 00 62 00 61 00 60 00 15 00 12 00 09 00 14 00 11  b a `
00000050: 00 08 00 06 00 03 01 00

NSOCK INFO [9.4660s] nsock_write(): Write request for 88 bytes to IOD #2
EID 43 [192.168.0.1:80]
NSOCK INFO [9.4670s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 43 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51933 > 192.168.0.1:80 | SEND
NSOCK INFO [9.4680s] nsock_read(): Read request from IOD #2 [192.168.0.1:80]
(timeout: 7000ms) EID 50
NSOCK INFO [16.4690s] nsock_trace_handler_callback(): Callback: READ
TIMEOUT for EID 50 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51933 > 192.168.0.1:80 | CLOSE
NSOCK INFO [16.4690s] nsock_iod_delete(): nsock_iod_delete (IOD #2)
NSOCK INFO [16.4690s] nsock_iod_new2(): nsock_iod_new (IOD #3)
NSOCK INFO [16.4730s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #3) EID 56
NSOCK INFO [16.4800s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 56 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51934 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51934 > 192.168.0.1:80 | 00000000: 47 45 54 20 2f 6e
6d 61 70 6c 6f 77 65 72 63 68 GET /nmaplowerch
00000010: 65 63 6b 31 35 38 35 36 38 30 38 33 37 20 48 54 eck1585680837 HT
00000020: 54 50 2f 31 2e 31 0d 0a 48 6f 73 74 3a 20 31 39 TP/1.1  Host: 19
00000030: 32 2e 31 36 38 2e 30 2e 31 0d 0a 43 6f 6e 6e 65 2.168.0.1  Conne
00000040: 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 55 73 ction: close  Us
00000050: 65 72 2d 41 67 65 6e 74 3a 20 4d 6f 7a 69 6c 6c er-Agent: Mozill
00000060: 61 2f 35 2e 30 20 28 63 6f 6d 70 61 74 69 62 6c a/5.0 (compatibl
00000070: 65 3b 20 4e 6d 61 70 20 53 63 72 69 70 74 69 6e e; Nmap Scriptin
00000080: 67 20 45 6e 67 69 6e 65 3b 20 68 74 74 70 73 3a g Engine; https:
00000090: 2f 2f 6e 6d 61 70 2e 6f 72 67 2f 62 6f 6f 6b 2f //nmap.org/book/
000000a0: 6e 73 65 2e 68 74 6d 6c 29 0d 0a 0d 0a          nse.html)

NSOCK INFO [16.4920s] nsock_write(): Write request for 173 bytes to IOD #3
EID 67 [192.168.0.1:80]
NSOCK INFO [16.4920s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 67 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51934 > 192.168.0.1:80 | SEND
NSOCK INFO [16.4930s] nsock_read(): Read request from IOD #3 [192.168.0.1:80]
(timeout: 7000ms) EID 74
NSOCK INFO [16.7770s] nsock_trace_handler_callback(): Callback: READ ERROR
[An existing connection was forcibly closed by the remote host.  (10054)]
for EID 74 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51934 > 192.168.0.1:80 | CLOSE
NSOCK INFO [16.7770s] nsock_iod_delete(): nsock_iod_delete (IOD #3)
NSOCK INFO [16.7770s] nsock_iod_new2(): nsock_iod_new (IOD #4)
NSOCK INFO [16.7830s] nsock_connect_ssl(): SSL connection requested to
192.168.0.1:80/tcp (IOD #4) EID 81
NSOCK INFO [17.7840s] nsock_trace_handler_callback(): Callback: SSL-CONNECT
TIMEOUT for EID 81 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51935 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51935 > 192.168.0.1:80 | CLOSE
NSOCK INFO [17.7870s] nsock_iod_delete(): nsock_iod_delete (IOD #4)
NSOCK INFO [17.7870s] nsock_iod_delete(): nsock_iod_delete: SSL shutdown
failed ((null)) on NSI 4
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] http.request socket
error: The script encountered an error:
- ssl failed:
- Failed to connect:
- Could not connect:
- TIMEOUT
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] HTTP response error:
Error creating socket.
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Unexpected response
returned for 404 check: creating socket.
Fetchfile found C:\Program Files
(x86)\Nmap/nselib/data/http-default-accounts-fingerprints.lua
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Loading fingerprints:
C:\Program Files
(x86)\Nmap/nselib/data/http-default-accounts-fingerprints.lua
Fetchfile found C:\Program Files (x86)\Nmap/nselib/json.lua
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] 3 fingerprints were
loaded
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Trying known
locations under path '' (change with 'http-default-accounts.basepath'
argument)
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] HTTP pipeline: Total
number of requests: 1
NSOCK INFO [17.7870s] nsock_iod_new2(): nsock_iod_new (IOD #5)
NSOCK INFO [17.8200s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #5) EID 88
NSOCK INFO [17.8350s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 88 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51936 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51936 > 192.168.0.1:80 | 00000000: 47 45 54 20 2f 20
48 54 54 50 2f 31 2e 31 0d 0a GET / HTTP/1.1
00000010: 48 6f 73 74 3a 20 31 39 32 2e 31 36 38 2e 30 2e Host: 192.168.0.
00000020: 31 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 6b 1  Connection: k
00000030: 65 65 70 2d 61 6c 69 76 65 0d 0a 55 73 65 72 2d eep-alive  User-
00000040: 41 67 65 6e 74 3a 20 4d 6f 7a 69 6c 6c 61 2f 35 Agent: Mozilla/5
00000050: 2e 30 20 28 63 6f 6d 70 61 74 69 62 6c 65 3b 20 .0 (compatible;
00000060: 4e 6d 61 70 20 53 63 72 69 70 74 69 6e 67 20 45 Nmap Scripting E
00000070: 6e 67 69 6e 65 3b 20 68 74 74 70 73 3a 2f 2f 6e ngine; https://n
00000080: 6d 61 70 2e 6f 72 67 2f 62 6f 6f 6b 2f 6e 73 65 map.org/book/nse
00000090: 2e 68 74 6d 6c 29 0d 0a 0d 0a                   .html)

NSOCK INFO [17.8360s] nsock_write(): Write request for 154 bytes to IOD #5
EID 99 [192.168.0.1:80]
NSOCK INFO [17.8360s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 99 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51936 > 192.168.0.1:80 | SEND
NSOCK INFO [17.8370s] nsock_read(): Read request from IOD #5 [192.168.0.1:80]
(timeout: 11000ms) EID 106
NSOCK INFO [18.1150s] nsock_trace_handler_callback(): Callback: READ
SUCCESS for EID 106 [192.168.0.1:80] (1706 bytes)
NSE: TCP 192.168.0.37:51936 < 192.168.0.1:80 | HTTP/1.1 200 OK
Content-type: text/html
Expires: Thu, 3 Oct 1968 12:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, must-revalidate
Connection: close
Set-Cookie: Lang=en
Set-Cookie: SessionID=33893090
Content-Length: 1469

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html lang="en">
<head>
<title>Setup</title>
<meta http-equiv="x-ua-compatible" content="IE=EmulateIE8" >
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<META http-equiv="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
<meta HTTP-EQUIV="Expires" CONTENT="Mon, 06 Jan 1990 00:00:01 GMT">
<script language="javascript" type="text/javascript" src="lang.js"></script>
<script language="javascript" type="text/javascript"
src="linux.js"></script>
<script language="javascript" type="text/javascript">
function loadnext()
{
    window.location.href = "Docsis_system.asp";
}

</script>
</head>
<body bgcolor="#ffffff" text="#666666" onLoad="loadnext()">
<form name="login" method="POST" action="">
<div ID="maintext"
STYLE="position:absolute;left:50px;top:40px;font-family:Arial,Helvetica">
<h4>Checking JavaScript Support </h4>
<p>To provide an enhanced user interface, this Router uses JavaScript
extensively.
<P>If this page is not quickly replaced, your Browser does NOT support
JavaScript.
<P>Please enable JavaScript in your Browser, or use a different Browser.
</p>
</div>

<div ID="NStext"
STYLE="position:absolute;left:50px;top:220px;font-family:Arial,Helvetica;">
Netscape 4.x Browsers are NOT supported.
<p>Please use a later browser, such as IE 5.5 or later, or the current
version of Mozilla or Netscape.</p>
</div>
</form>
</body>
</html>



NSE: [http-default-accounts M:44FD974 192.168.0.1:80] HTTP pipeline:
connlimit=1, batchlimit=1
NSE: TCP 192.168.0.37:51936 > 192.168.0.1:80 | CLOSE
NSOCK INFO [18.1180s] nsock_iod_delete(): nsock_iod_delete (IOD #5)
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] HTTP pipeline: Number
of received responses: 1
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Processing Cisco IOS
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Processing Cisco
Linksys
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Processing Cisco
EPC3925
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Trying login combo ->
<blank>:<blank>
NSOCK INFO [18.1180s] nsock_iod_new2(): nsock_iod_new (IOD #6)
NSOCK INFO [18.1220s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #6) EID 112
NSOCK INFO [18.1880s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 112 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51937 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51937 > 192.168.0.1:80 | POST /goform/Docsis_system
HTTP/1.1
Content-Length: 82
Host: 192.168.0.1
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (compatible; Nmap Scripting Engine;
https://nmap.org/book/nse.html)

login=Log%20In&password_login=&Language_Submit=0&LanguageSelect=en&username_login=
NSOCK INFO [18.1920s] nsock_write(): Write request for 321 bytes to IOD #6
EID 123 [192.168.0.1:80]
NSOCK INFO [18.1920s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 123 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51937 > 192.168.0.1:80 | SEND
NSOCK INFO [18.1930s] nsock_read(): Read request from IOD #6 [192.168.0.1:80]
(timeout: 7000ms) EID 130
NSOCK INFO [18.2700s] nsock_trace_handler_callback(): Callback: READ
SUCCESS for EID 130 [192.168.0.1:80] (141 bytes)
NSE: TCP 192.168.0.37:51937 < 192.168.0.1:80 | 00000000: 48 54 54 50 2f 31
2e 30 20 33 30 32 20 52 65 64 HTTP/1.0 302 Red
00000010: 69 72 65 63 74 0d 0a 53 65 72 76 65 72 3a 20 50 irect  Server: P
00000020: 53 20 48 54 54 50 20 53 65 72 76 65 72 0d 0a 4c S HTTP Server  L
00000030: 6f 63 61 74 69 6f 6e 3a 20 68 74 74 70 3a 2f 2f ocation: http://
00000040: 31 39 32 2e 31 36 38 2e 30 2e 31 2f 44 6f 63 73 192.168.0.1/Docs
00000050: 69 73 5f 73 79 73 74 65 6d 2e 61 73 70 0d 0a 43 is_system.asp  C
00000060: 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65 78 ontent-type: tex
00000070: 74 2f 68 74 6d 6c 0d 0a 43 6f 6e 6e 65 63 74 69 t/html  Connecti
00000080: 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 0d 0a          on: close

NSOCK INFO [18.2740s] nsock_read(): Read request from IOD #6 [192.168.0.1:80]
(timeout: 7000ms) EID 138
NSOCK INFO [18.2880s] nsock_trace_handler_callback(): Callback: READ EOF
for EID 138 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51937 > 192.168.0.1:80 | CLOSE
NSOCK INFO [18.2890s] nsock_iod_delete(): nsock_iod_delete (IOD #6)
NSE: [http-default-accounts M:44FD974 192.168.0.1:80] Trying login combo ->
admin:admin
NSOCK INFO [18.2890s] nsock_iod_new2(): nsock_iod_new (IOD #7)
NSOCK INFO [18.2900s] nsock_connect_tcp(): TCP connection requested to
192.168.0.1:80 (IOD #7) EID 144
NSOCK INFO [18.3630s] nsock_trace_handler_callback(): Callback: CONNECT
SUCCESS for EID 144 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51938 > 192.168.0.1:80 | CONNECT
NSE: TCP 192.168.0.37:51938 > 192.168.0.1:80 | POST /goform/Docsis_system
HTTP/1.1
Content-Length: 92
Host: 192.168.0.1
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (compatible; Nmap Scripting Engine;
https://nmap.org/book/nse.html)

login=Log%20In&password_login=admin&Language_Submit=0&LanguageSelect=en&username_login=admin
NSOCK INFO [18.3780s] nsock_write(): Write request for 331 bytes to IOD #7
EID 155 [192.168.0.1:80]
NSOCK INFO [18.3780s] nsock_trace_handler_callback(): Callback: WRITE
SUCCESS for EID 155 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51938 > 192.168.0.1:80 | SEND
NSOCK INFO [18.3780s] nsock_read(): Read request from IOD #7 [192.168.0.1:80]
(timeout: 7000ms) EID 162
NSOCK INFO [18.4310s] nsock_trace_handler_callback(): Callback: READ
SUCCESS for EID 162 [192.168.0.1:80] (142 bytes)
NSE: TCP 192.168.0.37:51938 < 192.168.0.1:80 | 00000000: 48 54 54 50 2f 31
2e 30 20 33 30 32 20 52 65 64 HTTP/1.0 302 Red
00000010: 69 72 65 63 74 0d 0a 53 65 72 76 65 72 3a 20 50 irect  Server: P
00000020: 53 20 48 54 54 50 20 53 65 72 76 65 72 0d 0a 4c S HTTP Server  L
00000030: 6f 63 61 74 69 6f 6e 3a 20 68 74 74 70 3a 2f 2f ocation: http://
00000040: 31 39 32 2e 31 36 38 2e 30 2e 31 2f 41 64 6d 69 192.168.0.1/Admi
00000050: 6e 69 73 74 72 61 74 69 6f 6e 2e 61 73 70 0d 0a nistration.asp
00000060: 43 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65 Content-type: te
00000070: 78 74 2f 68 74 6d 6c 0d 0a 43 6f 6e 6e 65 63 74 xt/html  Connect
00000080: 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 0d 0a       ion: close

NSOCK INFO [18.4350s] nsock_read(): Read request from IOD #7 [192.168.0.1:80]
(timeout: 7000ms) EID 170
NSOCK INFO [18.4930s] nsock_trace_handler_callback(): Callback: READ EOF
for EID 170 [192.168.0.1:80]
NSE: TCP 192.168.0.37:51938 > 192.168.0.1:80 | CLOSE
NSOCK INFO [18.4940s] nsock_iod_delete(): nsock_iod_delete (IOD #7)
NSE: Finished http-default-accounts M:44FD974 against 192.168.0.1:80.
Completed NSE at 20:54, 16.12s elapsed
Nmap scan report for 192.168.0.1
Fetchfile found C:\Program Files (x86)\Nmap/nmap-mac-prefixes
MAC prefix 0001C8 is duplicated in C:\Program Files
(x86)\Nmap/nmap-mac-prefixes; ignoring duplicates.
MAC prefix 080030 is duplicated in C:\Program Files
(x86)\Nmap/nmap-mac-prefixes; ignoring duplicates.
MAC prefix 080030 is duplicated in C:\Program Files
(x86)\Nmap/nmap-mac-prefixes; ignoring duplicates.
Host is up, received arp-response (0.015s latency).
Scanned at 2020-03-31 20:53:57 W. Europe Daylight Time for 17s

PORT   STATE SERVICE REASON
80/tcp open  http    syn-ack ttl 64
MAC Address: 08:80:39:DF:FB:2F (Cisco Spvtg)
Final times for host: srtt: 14750 rttvar: 14500  to: 400000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 20:54
Completed NSE at 20:54, 0.00s elapsed
Read from C:\Program Files (x86)\Nmap: nmap-mac-prefixes nmap-payloads
nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 18.54 seconds
           Raw packets sent: 2 (72B) | Rcvd: 2 (72B)
PS C:\WINDOWS\system32>

*All the best,*

Ilham Jilani

**Comment by nnposter** [comment]
This looks like a device variant that the current script does not fully recognize. To collect all the necessary information for developing an update, could you please review instructions posted [here](https://github.com/nnposter/nndefaccts#fingerprint-contributions) and send in the session file?

**Comment by jilani97** [comment]
Ok, sent to nndefacts /at/ shared-files.de
All the best,

Ilham Jilani

**Comment by nnposter** [comment]
The session file looks good and the fix should be straightforward. Please apply the following patch and report back whether the only reported credential combo is `admin:admin`. Also please share the firmware version of the device.
```diff
--- a/nselib/data/http-default-accounts-fingerprints.lua	2020-03-31 21:26:51.890992300 -0600
+++ b/nselib/data/http-default-accounts-fingerprints.lua	2020-03-31 21:40:15.240724900 -0600
@@ -677,9 +677,8 @@
 })
 
 table.insert(fingerprints, {
-  -- Version ESIP-12-v302r125573-131230c_upc
-  name = "Cisco EPC3925",
-  cpe = "cpe:/h:cisco:epc3925",
+  name = "Cisco EPC392x",
+  cpe = "cpe:/h:cisco:epc392*",
   category = "routers",
   paths = {
     {path = "/"}
@@ -691,7 +690,10 @@
            and response.body:find("window%.location%.href%s*=%s*(['\"])Docsis_system%.asp%1")
   end,
   login_combos = {
-    {username = "", password = ""}
+    {username = "", password = ""},
+    {username = "baduser", password = "admin"},
+    {username = "admin", password = "badpassword"},
+    {username = "admin", password = "admin"}
   },
   login_check = function (host, port, path, user, pass)
     local form = {username_login=user,
@@ -702,8 +704,9 @@
     local resp = http_post_simple(host, port,
                                  url.absolute(path, "goform/Docsis_system"),
                                  nil, form)
+    local loc = resp.header["location"] or ""
     return resp.status == 302
-           and (resp.header["location"] or ""):find("/Quick_setup%.asp$")
+           and (loc:find("/Quick_setup%.asp$") or loc:find("/Administration%.asp$"))
   end
 })
 
```

**Comment by jilani97** [comment]
![Screenshot from 2020-04-01 10-06-22](https://user-images.githubusercontent.com/21960925/78113832-9cefba80-7400-11ea-8117-27db6fc8e64a.png)

Firmware Name: 

e3928A-ES-16-E138-c3220r55103-150810.bin
--


Thanks for the help

**Comment by nnposter** [comment]
The update has been committed as r37919. Thank you for working with us and providing the login traces!
