### ISSUE TITLE
Add SSL probe with TLS_EMPTY_RENEGOTIATION_INFO_SCSV

### ISSUE THREAD

**Issue by mattfoster** [nmap/nmap#199]
Recently, I've come across some devices which don't respond to nmap's standard SSL probes, and after some experimentation I've determined that they only respond to SSL ClientHellos which contain `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` in their cipher lists.

I'm afraid I don't have a Probe line to share with you, but we've been using:

    pack("H*", "160301005f0100005b030155bb3d2c4188e00a88c3ca8c8c7194a9977fa090ae784816f9c37254b900269500002e00390038003500160013000a00330032002f009a00990096000500040015001200090014001100080006000300ff0100000400230000"),

I also don't yet know which devices exhibit this behaviour, but I'll update this issue if I find out.

**Comment by nnposter** [comment]
Out of curiosity, do these targets specifically require the SCSV or do they just want to see support for secure renegotiation in general and the corresponding TLS extension is therefore sufficient?

**Comment by dmiller-nmap** [comment]
We recently added TLSSessionReq probe to strictly handle detecting modern TLS servers that don't like our older SSLSessionReq probes. I just added TLS_EMPTY_RENEGOTIATION_SCSV to the cipher list of this probe, which should solve the issue.
