### ISSUE TITLE
Can't find PACKET_ENABLE_LOOPBACK

### ISSUE THREAD

**Issue by j3nks** [nmap/nmap#1992]
What header do I need to include to enable PACKET_ENABLE_LOOPBACK for PacketSetLoopbackBehavior(PACKET_ENABLE_LOOPBACK);

I searched through the entire code base and couldn't find it.

Oh and this is for NPCAP .9990

**Comment by mmueller-projektantrieb** [comment]
It is called NPF_ENABLE_LOOPBACK instead, if you want to enable loopback with that function.

**Comment by dmiller-nmap** [comment]
This was a typo in a comment on another issue (#1929) as well as in the CHANGELOG and in a comment in the code. I've corrected all 3 places.
