### ISSUE TITLE
ssl-cert not working

### ISSUE THREAD

**Issue by vigneshkaladharan** [nmap/nmap#2001]
i am using nmap 6.4 
i run the below command 
nmap -sT --open -p5100 -v -Pn -sV --script +ssl-cert 127.0.01 got the response as 

5100/tcp open  admd?**
but i have a valid SSL cert bind to this port

**Comment by dmiller-nmap** [comment]
Nmap 6.40 is nearly 7 years old. Please upgrade to Nmap 7.80 and try again. Note that there have been several fixes to Nmap 7.80's ssl-cert that have not yet been released. If you wish, you can build directly from the development source (`master` branch of this repository) to get these improvements.

**Comment by vigneshkaladharan** [comment]
@dmiller-nmap Thank you very much for your help dmiller-nmap

**Comment by vigneshkaladharan** [comment]
> Nmap 6.40 is nearly 7 years old. Please upgrade to Nmap 7.80 and try again. Note that there have been several fixes to Nmap 7.80's ssl-cert that have not yet been released. If you wish, you can build directly from the development source (`master` branch of this repository) to get these improvements.

what options do we need to provide in nmap for client certificate authentication
