### ISSUE TITLE
Npcap - no raw 802.11 packets captured on Win10

### ISSUE THREAD

**Issue by pr0mixe** [nmap/nmap#2002]
This is a repost of #1877 because there was no response. 
I have no 802.11 packets captured on ALL of my Windows 10 machines. ALL versions of npcap and Wireshark. Npcap installs fine, the services run, I can capture regular data packets with it. I can enter monitor mode on all of my wifi interfaces but no packets received in monitor mode. Same with Wireshark and with Winpcap-compatible API mode in 3rd party apps. It has been doing this since last year on at least 5 different Windows 10 machines, some with clean OS installs. Where do I begin to troubleshoot? Thanks!

PS: The only reliable working combination I was able to come up with on several Win10 x64 machines is: Win 10 x64 1803, npcap 0.995, Wireshark 3.0.3.  Same version of npcap does not capture 802.11 packets on Win10 1903 or newer. Any other versions of npcap on Win10 1903+ do not work either...

**Comment by fyodor** [comment]
Thanks for the updates, but please don't do "reposts".  You can post updates as comments to the original issue instead.  Cheers!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
