### ISSUE TITLE
nmap service probe - "Juniper SA2000 or SA4000 VPN gateway http config"

### ISSUE THREAD

**Issue by fabianlagos** [nmap/nmap#2007]
Hi !

Do you have documentation or information on this "match" in the "nmap service probe"?

![image](https://user-images.githubusercontent.com/25568255/79313721-c6afe380-7ece-11ea-9244-0c370c46917a.png)

I need to understand this relationship of the Juniper HTTP content and version. I can't find anything, any information would be appreciated

**Comment by fyodor** [comment]
The documentation is [here](https://nmap.org/book/vscan-fileformat.html). Cheers!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
