### ISSUE TITLE
How do I use npcap under python?

### ISSUE THREAD

**Issue by jkjbhk** [nmap/nmap#2008]
Is there any related tutorial or basis?

**Comment by jkjbhk** [comment]
On Windows10

**Comment by gvanem** [comment]
How about Impacket?  https://github.com/SecureAuthCorp/impacket

**Comment by guyharris** [comment]
[The pcap Wikipedia page](https://en.wikipedia.org/wiki/Pcap) lists, in the ["Wrapper libraries for libpcap" section](https://en.wikipedia.org/wiki/Pcap#Wrapper_libraries_for_libpcap), several wrapper libraries, including some for Python.

**Comment by dmiller-nmap** [comment]
Thanks for your interest. Any pcap library wrapper for Python that has Windows integration should work with Npcap. Several have already been suggested. Scapy is also reported to work with Npcap.
