### ISSUE TITLE
Bruteforce. Oracle database. The service seems to have failed or is heavily firewalled

### ISSUE THREAD

**Issue by kemanik** [nmap/nmap#2010]
nmap -sT -p 1521 -d -Pn -e eth4 --script oracle-brute --script-args "unpwdb.timelimit=3h,oracle-brute.sid=UPGR,userdb=C:\\Users\\rag\\Downloads\\usernames.lst,passdb=C:\\Users\\rag\\Downloads\\passwords.lst" 192.168.1.102

In oracle password brute force scanning there are a lot of errors like this:

NSE: oracle-brute against 192.168.1.102:1521 threw an error!
C:\Program Files (x86)\Nmap/nselib/tns.lua:1278: attempt to call a nil value (method 'len')
stack traceback:
	C:\Program Files (x86)\Nmap/nselib/tns.lua:1278: in field 'unmarshalKvpComponent'
	C:\Program Files (x86)\Nmap/nselib/tns.lua:1202: in field 'unmarshalKvp'
	C:\Program Files (x86)\Nmap/nselib/tns.lua:498: in method 'parseResponse'
	C:\Program Files (x86)\Nmap/nselib/tns.lua:1427: in method 'exchTNSPacket'
	C:\Program Files (x86)\Nmap/nselib/tns.lua:1726: in method 'Login'
	C:\Program Files (x86)\Nmap/scripts\oracle-brute.nse:140: in method 'login'
	C:\Program Files (x86)\Nmap/nselib/brute.lua:768: in method 'doAuthenticate'
	C:\Program Files (x86)\Nmap/nselib/brute.lua:821: in function <C:\Program Files (x86)\Nmap/nselib/brute.lua:797>

[nmap_output_oracle.txt](https://github.com/nmap/nmap/files/4493079/nmap_output_oracle.txt)

**Comment by nnposter** [comment]
There is a bug in the code. Unfortunately I have no access to an environment where I can test. Could you please apply the following patch and report back?

https://gist.github.com/nnposter/dcf21b9cdf0e17fe7f88b4763db2e4ba

**Comment by kemanik** [comment]
Now it works!

**Comment by nnposter** [comment]
A mildly updated patch has been committed as r37932. Thank you for reporting the issue!
