### ISSUE TITLE
Npcap OEM 0.9990: Silent reinstall still prompts the user, hangs when run in system session

### ISSUE THREAD

**Issue by akontsevoy** [nmap/nmap#2014]
When reinstalling Npcap OEM over an existing same version, the following prompt pops up, even in silent mode. When the installation is run unattended, this hangs the installer indefinitely.

![image](https://user-images.githubusercontent.com/1968357/79630183-11d42b80-8147-11ea-8b1b-8d2d1240e5df.png)

Expected behavior: Silent installation should never ever ask the user anything, and assume "yes" on all prompts (unless the command line parameters specify otherwise).

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! A `goto` got deleted in the Silent control flow. This dialog should have been skipped.

**Comment by dmiller-nmap** [comment]
For documentation, this was fixed in Npcap 0.9991.
