### ISSUE TITLE
Nmap 7.80 Windows bug when scanning two ports

### ISSUE THREAD

**Issue by rambo691** [nmap/nmap#2026]
There is a bug in the new version of Nmap 7.80 on Windows when you are going to scan two ports.

The screenshots are self-explanatory.

Nmap 7.70 version
![image](https://user-images.githubusercontent.com/16231048/80366723-07720a00-888a-11ea-9465-d03119f93ba3.png)

Nmap 7.80 version

![image](https://user-images.githubusercontent.com/16231048/80366771-1ce73400-888a-11ea-8b12-d464664dec94.png)

I've done a downgrade to version 7.70 and this problem didn't appear.

**Comment by nnposter** [comment]
The comma in `-p 139,445` is being interpreted by PowerShell as an argument separator. Please repeat the scan outside of PowerShell or enclose the port list in quotes.

**Comment by rambo691** [comment]
You're right, it's the Powershell version. More specifically, the version of powershell that gives problems is version 4.0 but in version 5 (which I have used so far) it works perfectly. Thank you very much for your help!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
