### ISSUE TITLE
make && make install

### ISSUE THREAD

**Issue by sfdota** [nmap/nmap#2028]
make[1]: Entering directory '/home/tools/nmap/nping'
cd . && autoconf
/bin/sh: 1: autoconf: not found
make[1]: *** [Makefile:146: configure] Error 127
make[1]: Leaving directory '/home/tools/nmap/nping'
make: *** [Makefile:394: build-nping] Error 2

**Comment by dmiller-nmap** [comment]
There should be no reason to need autoconf, but Make may think the `configure` scripts need to be rebuilt based on file timestamps. Run the following command in the to update the last-modified time for each `configure` file: `find . -name 'configure' -exec touch {} \;`

**Comment by calito** [comment]
use:
apt-get install autoconf

**Comment by goarblt** [comment]
hello
https://www.evil.com/
