### ISSUE TITLE
Docker Compose Issue

### ISSUE THREAD

**Issue by charlesomer** [nmap/nmap#2039]
I can't seem to get nmap to work in a docker container. For some reason, Nmap seems to think every IP address is on the network (when it's not). No issues when running outside of the docker container.

This is what I've got so far. https://github.com/charlesomer/network-devices-scanner

I've set `network_mode: host` in the compose file so I'm not sure. I may have missed something obvious?

When doing `nmap -F 192.168.0.0/24` on my local network, I receive a list of all the devices which are present on the network (as expected).
However, when doing the same from a docker container, I get a list of every single IP address in the subnet, even ones which have no devices assigned to them.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
