### ISSUE TITLE
Npcap 0.9991: (Windows 10 version 2004) no network on cold boot for 10-15 second

### ISSUE THREAD

**Issue by xsm1997** [nmap/nmap#2046]
Hello, I am using Windows 10 version 2004. 
After installing Npcap, my computer keeps no network connection on cold boot (reboot, not shutdown) for 10-15 second. In this period, my auto-starting programs can not connect to the Internet, resulting errors and failing.
When uninstalled Npcap, the things get normal. I can get network connection as soons as my computer boots into login screen.
Note that on Windows 10 version 1909 and earlier, this will not happen. At least it works normally on Windows 10 1909.
Is that a known bug of Npcap? Hope this could be solved soon.
Thanks!

**Comment by xsm1997** [comment]
It is a problem related to slow DHCP response. Sorry. Closing this issue.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
