### ISSUE TITLE
a lot of port open for no reason

### ISSUE THREAD

**Issue by Morophine** [nmap/nmap#2047]
nmap (my ip)
Starting Nmap 7.80 ( https://nmap.org ) at 2020-05-16 15:45 EDT
Nmap scan report for sagembox (my ip)
Host is up (0.024s latency).
Not shown: 991 closed ports
PORT     STATE SERVICE
23/tcp   open  telnet
80/tcp   open  http
139/tcp  open  netbios-ssn
443/tcp  open  https
992/tcp  open  telnets
8080/tcp open  http-proxy
8443/tcp open  https-alt
8888/tcp open  sun-answerbook
9100/tcp open  jetdirect

Nmap done: 1 IP address (1 host up) scanned in 2.60 seconds
I dont know why all these ports are open and i dont know how to shut them down am on linux, Please help

**Comment by dmiller-nmap** [comment]
Thanks for your interest in Nmap. Unfortunately, we cannot provide support for things other than Nmap and its associated software.
