### ISSUE TITLE
Tighten Nmap Data File Replacement Rules and  Security Permissions

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2051]
We received a report from a company using Nmap that was concerned about reducing that risk that an attacker could replace Nmap's data files, since that could potentially allow code execution.  The data file replacement behavior is all documented at https://nmap.org/book/data-files-replacing-data-files.html, but we think this could be tightened up without substantially reducing usability.  So our current plans are:

1) Remove C:\Nmap from the Windows search path.  Even though it is documented, I doubt many people use it.  And it does introduce security concerns since Windows (at least sometimes) ships with insecure C: root filesystem permissions, probably for legacy app compatibility reasons.  On Linux/UNIX/Mac platforms, all of the data directories are places that should only be writable by privileged users (or the user running Nmap themselves).

2) Remove the "updates" directory searches since those relate to a feature that we never really introduced.

3) We will make sure the current working directly isn't searched when specifying NSE scripts by category (though keep it for running scripts).  Also, there is a feature where you can specify a directory and have all NSE scripts in that directory automatically run.  We are thinking about requiring a forward slash at the end of the directory name for that feature so that it doesn't happen accidentally.

**Comment by dmiller-nmap** [comment]
Changes incoming. Status on the above items:

1. Windows will no longer search NMAPDATADIR, which was hard-coded as `c:\nmap` previously.
2. `nmap-update` has been entirely removed, including the additional search paths for fetching data files and scripts.
3. If a user runs `nmap --script name-of-directory`, it will result in an error if the directory exists. The error message is `directory 'name-of-directory' found, but will not match without '/'`. If the directory does not exist, the error is `'name-of-directory' did not match a category, filename, or directory`. To get the old behavior, it must be specified as `nmap --script name-of-directory/`

**Comment by goarblt** [comment]
hello
https://www.evil.com/
