### ISSUE TITLE
Notably faster fromhex()

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#2055]
Function `stdnse.fromhex()` is used extensively throughout the NSE codebase, which makes it worth optimizing. The following drop-in replacement performs about 43% faster[1] and creates only a quarter of temporary Lua strings than the current implementation:
```lua
function fromhex (hex)
  local p = hex:find("[^%x%s]")
  if p then
    return nil, "Invalid hexadecimal digits at position " .. p
  end
  hex = hex:gsub("%s+", "")
  if #hex % 2 ~= 0 then
    return nil, "Odd number of hexadecimal digits"
  end
  return hex:gsub("..", function (h) return string.char(tonumber(h, 16)) end)
end
```
I will commit the change in a few weeks unless concerns are raised.

[1] https://gist.github.com/nnposter/b9e4e1a9b9d2637f8c8c6b2948866640

**Comment by dmiller-nmap** [comment]
I like it! Thanks for taking the time to work it out. I don't see any issues.

**Comment by nnposter** [comment]
Committed as r37938 (f5b4d98153f8c794ea7892208dc39e1f22a299ed)
