### ISSUE TITLE
An error in MS SQL password brute forcing

### ISSUE THREAD

**Issue by kemanik** [nmap/nmap#2056]
Correct logins and passwords are in files and result should be successful.
nmap -p 1433 -d2 -Pn --script ms-sql-brute --script-args "unpwdb.timelimit=3h,mssql.instance-port=1433,userdb=D:\\logins.txt,passdb=D:\\passwords.txt" 192.168.100.154 --disable-arp-ping -sT

Logins file contain cyrillic symbols in first line and correct login in second line, password file contains only correct password. Result has an error:
Host script results:
| ms-sql-brute: 
|   [192.168.100.154:1433]
|     No credentials found
|     Errors:
|_      Network error. Skipping instance. Error: EOF
[nmap_error.txt](https://github.com/nmap/nmap/files/4696212/nmap_error.txt)
[logins.txt](https://github.com/nmap/nmap/files/4700041/logins.txt)
[passwords.txt](https://github.com/nmap/nmap/files/4700042/passwords.txt)

**Comment by kemanik** [comment]
@nnposter What do you think about it?

**Comment by dmiller-nmap** [comment]
Thanks for the report. This looks like an encoding mixup, most likely. The logins.txt seems to be UTF-8, but I think it's being interpreted some other way. I'll start looking into it.

**Comment by dmiller-nmap** [comment]
Yes, it's a problem with determining the length of a string in characters, not bytes. The TDS login packet has offsets in bytes and lengths in characters. Your username and password contain characters that take more than 1 byte in UTF-8 (the input character set for all NSE scripts), but the script is assuming all characters take only 1 byte. Even though they are correctly transcoded to UTF-16LE, the packet ends up being malformed. I'm pushing a change that seems to work here, but I can't be sure the password encoding works; it may be I've broken that, but it would be a different problem.

If you try the fixed version and get a different result than you expect, please let me know and provide debug output with `-d2 --script-trace`

**Comment by dmiller-nmap** [comment]
Assuming since we haven't heard back that this issue is resolved.
