### ISSUE TITLE
Cups-Info NMAP Error

### ISSUE THREAD

**Issue by neonxdhd** [nmap/nmap#2063]
nmap --script cups-info 192.168.130.23
![image](https://user-images.githubusercontent.com/48869362/84499152-e46caf80-aca9-11ea-9a9c-934bd9d326c4.png)
![image](https://user-images.githubusercontent.com/48869362/84499251-23026a00-acaa-11ea-802e-897f0ca2f1ad.png)
![image](https://user-images.githubusercontent.com/48869362/84499313-44635600-acaa-11ea-8f88-cbcd365e3105.png)
![image](https://user-images.githubusercontent.com/48869362/84499409-707ed700-acaa-11ea-8492-49780da897b7.png)
![image](https://user-images.githubusercontent.com/48869362/84499432-7b396c00-acaa-11ea-96da-facc1198193b.png)
![image](https://user-images.githubusercontent.com/48869362/84499466-8c827880-acaa-11ea-89ad-d876a609ab13.png)
What am i doing wrong? :/

**Comment by nnposter** [comment]
Thank you for reporting the issue. A fix has been committed as r37939. Please refresh file `nselib/ipp.lua` from [SVN](https://svn.nmap.org/nmap/nselib/ipp.lua) or [GitHub](https://raw.githubusercontent.com/nmap/nmap/master/nselib/ipp.lua).

**Comment by neonxdhd** [comment]
Duplicate of #
![image](https://user-images.githubusercontent.com/48869362/84562266-0bc78900-ad4b-11ea-90a8-aadc417862d3.png)
I change the file and now appears that :/

**Comment by neonxdhd** [comment]
> Thank you for reporting the issue. A fix has been committed as r37939. Please refresh file `nselib/ipp.lua` from [SVN](https://svn.nmap.org/nmap/nselib/ipp.lua) or [GitHub](https://raw.githubusercontent.com/nmap/nmap/master/nselib/ipp.lua).
Thank you :D.
But i change the file and now appears that
![image](https://user-images.githubusercontent.com/48869362/84562305-74166a80-ad4b-11ea-8963-bda9c70de43d.png)

**Comment by nnposter** [comment]
The second issue has been resolved in r37940. There was also yet another issue, this time in the script itself, now resolved in r37941. Please refresh both `nselib/ipp.lua` and `scripts/cups-info.nse`.

If you run into more problems please open new GitHub issues as needed; do not reuse this one.
