### ISSUE TITLE
NMAP Cups-Info Don't appear printers

### ISSUE THREAD

**Issue by neonxdhd** [nmap/nmap#2064]
![image](https://user-images.githubusercontent.com/48869362/84639020-b2e52580-aeef-11ea-9be5-843ee2dcf16f.png)
![image](https://user-images.githubusercontent.com/48869362/84639128-dc05b600-aeef-11ea-9284-b4e7467a1970.png)
![image](https://user-images.githubusercontent.com/48869362/84639155-e758e180-aeef-11ea-9bec-35f0c9c33227.png)
![image](https://user-images.githubusercontent.com/48869362/84639219-fdff3880-aeef-11ea-9bfe-345a537cb131.png)
![image](https://user-images.githubusercontent.com/48869362/84639270-0c4d5480-aef0-11ea-827a-eff430048d29.png)
![image](https://user-images.githubusercontent.com/48869362/84639347-29822300-aef0-11ea-8ec7-54d30b9f22a2.png)

I made the changes in ipp.lua and cups-info.nse and there is no longer an error but no printers( https://github.com/nmap/nmap/commit/e761d3e355ecedfd24308ee5490419294ef31576 ; https://github.com/nmap/nmap/commit/838ec193e3031763ccf3ed05370480652a37a336 ; https://github.com/nmap/nmap/commit/7ff536c8a10517a667284ab2ac79658bb8861c7c)

**Comment by nnposter** [comment]
Please re-run the script with `-ddd` to see if the output provides any clues.

**Comment by neonxdhd** [comment]
> Please re-run the script with `-ddd` to see if the output provides any clues.
![image](https://user-images.githubusercontent.com/48869362/84667064-c4dbbe00-af19-11ea-9503-339fac98feae.png)
![image](https://user-images.githubusercontent.com/48869362/84667177-e8066d80-af19-11ea-9fc9-f787849de514.png)
![image](https://user-images.githubusercontent.com/48869362/84667338-1d12c000-af1a-11ea-83c8-13c8a7d80d42.png)
![image](https://user-images.githubusercontent.com/48869362/84667426-416e9c80-af1a-11ea-9e72-88330f50b137.png)
Appears that :/

**Comment by nnposter** [comment]
Please save the *full* output to a text file, instead of these partial screenshosts

**Comment by neonxdhd** [comment]
> Please save the _full_ output to a text file, instead of these partial screenshosts

[output.txt](https://github.com/nmap/nmap/files/4781238/output.txt)

**Comment by neonxdhd** [comment]
> Please save the _full_ output to a text file, instead of these partial screenshosts

[output.txt](https://github.com/nmap/nmap/files/4781254/output.txt)

**Comment by nnposter** [comment]
The output definitely helps. That said, IPP request `CUPS-Get-Printers`, issued by the script, seems to work just fine and the target server is returning status `successful-ok`, but not listing any printers. In other words, there are no client- or server-side errors.

To make sure that your version of CUPS, 2.3.1, does not behave in some unique way, I have tested the script against several different instances of CUPS 2.3.1 and the script worked correctly with all of them. Here is one example:
```
PORT    STATE SERVICE REASON
631/tcp open  ipp     syn-ack
| cups-info: 
|   Brother_HL_L3230CDW_series
|     DNS-SD Name: Brother Colour @ 926BEH3
|     Location: Reception
|     Model: HL-L3230CDW series - IPP Everywhere
|     State: Idle
|     Queue: 0 print jobs
|   Samsung-ML-2525W
|     DNS-SD Name: Samsung ML-2525W @ 926BEH3
|     Location: Office
|     Model: Samsung ML-2525W Series
|     State: Idle
|_    Queue: 0 print jobs
```
At this point I can only suggest to review what restrictions or other configuration settings on the target server might be causing the printers to stay unlisted.

**Comment by neonxdhd** [comment]
Thank you for the help :D. Because the problem isn't NMAP anymore i will close the issue.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
