### ISSUE TITLE
ncat: Mixing --ssl and --proxy doesn't work

### ISSUE THREAD

**Issue by gonzzor** [nmap/nmap#2065]
Trying to connect to a TLS webserver via a HTTP proxy doesn't work, using the following
`ncat --proxy proxy.example.net:8080 --ssl tls.example.net 443`

It silently ignores the --ssl option and connects to tls.example.net 443 without doing TLS.

Tested with commit cc0661fb34a6d0ab23f41ab1ffaf4fb18b5f1489

**Comment by dmiller-nmap** [comment]
Just put in a fix for this which will show up within an hour. Possibly there are bugs, since my test setup was pretty simple. This is just a patch until #2066 can be accomplished (use Nsock's built-in proxy support in Ncat).

**Comment by goarblt** [comment]
hello
https://www.evil.com/
