### ISSUE TITLE
NMAP Don't Show Device type on Ubuntu 20.4 LTS and CentOS 8

### ISSUE THREAD

**Issue by the-m4ster-keys** [nmap/nmap#2072]
I do the command "nmap -A -T4 --osscan-guess" and the output is this:
![imagem](https://user-images.githubusercontent.com/48869362/85926243-f51a4980-b895-11ea-8509-606e6be95738.png)
I have firewall disable on the two machines and the two machines are in the same network.
This machines are in the same network with Host Only Adapter on Virtualbox
OS Machine NMAP:OpenBSD 6.6
OS Victim:Ubuntu 20.4 LTS
Version NMAP:7.80
I check with CentOS 8 to be a victim and not appears that parameter too... :/
I check using Ubuntu 20.4 LTS with NMAP and the victim is Ubuntu 20.4 LTS and that parameter not appear too :/
That parameter just appears on OpenBSD 6.6, Ubuntu 18.04 LTS and my router. 
Output when I do "nmap -A -T4 --osscan-guess -ddd"
[Output_debug.txt](https://github.com/nmap/nmap/files/4840862/Output_debug.txt)
Is anything i can do for show the  device type parameter? :/
Thanks for your attention

**Comment by fyodor** [comment]
The device type if there are too many possible matches.  Your best bet would be to submit the fingerprint at the URL it gives to you in the screenshot.  Because if this was an exact match, the device type of that match would be printed.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
