### ISSUE TITLE
A program on 8081 is incorrectly identified to be blackice-icecap

### ISSUE THREAD

**Issue by tronster** [nmap/nmap#2075]
**Describe the bug**
Running netstat on a RaspberryPi (RPI) using an OS install such as MotionEye returns "8081/tcp open blackice-icecap" but this service is not installed.

**To Reproduce**
1. Install MotionEye OS (https://github.com/ccrisan/motioneyeos/wiki) on an RPI. (I used an RPI 0w).  
2. Make sure the RPI is running on the network and perform a nmap of the network from it or another computer. 
    e.g., nmap 192.168.1.0/24
3. Notice the results from the RPI running MotionEyeOS shows:
    8081/tcp open  blackice-icecap
4. Log onto the RPI and perform: sudo netstat -tulpn
5. Look for the entry on port 8081 which should show something like:
    tcp        0      0 0.0.0.0:8081            0.0.0.0:*                LISTEN       1258/motion
6. Notice the "Program name" after the slash ("/") in the last column is called "motion" not "blackice-icecap"

**Expected behavior**
The nmap result should show the program name running to be "motion" and not "blackice-icecap"

**Version info (please complete the following information):**
-  OS: Motion version 4.2.2
- Output of `nmap --version`:
Apple LLVM version 11.0.3 (clang-1103.0.32.62)
  Optimized build.
  Default target: x86_64_apple-darwin19.5.0
  Host CPU: skylake

**Additional context**
This apparently has tripped up other users for other linux distributions; see: https://www.raspberrypi.org/forums/viewtopic.php?p=792640

**Comment by nnposter** [comment]
What command line options have you used?

If you have only executed `nmap 192.168.1.0/24`, as you hint, then this outcome is to be expected because nmap will only detect open ports and report back their IANA assignments (or most common use).

**Comment by tronster** [comment]
No command line options.  If "blackice" as mentioned the article posted above, is a service by IBM that in 2007 was declared end-of-lifecycle, then perhaps the "fix" is just to update the IANA assignment/most common use string.

**Comment by nnposter** [comment]
Please feel free to pursue an update to the IANA registry. In the meantime you might try to rerun the scan with `-sV` to see if you get different results.

**Comment by tronster** [comment]
Thank you for the suggestion of trying `-sV`, alas it only returned port 80 as to being open.
 
Most of this (e.g., IANA registry,etc...) is outside of my wheelhouse; this bug report is the deepest I plan to pursue it.  Hopefully someone with more knowledge of nmap and the systems that support it can pursue a course of action (if any) that makes sense.

**Comment by nnposter** [comment]
Seeing port 8081 open without `-sV` but not with `-sV` is not commonly observed. Please make sure that the port is still actually open, such as by running `netstat -ntl`.

If you do not wish to pursue this further then please close the issue.

**Comment by tronster** [comment]
Yes it's still open with netstat -ntl

As for pursuing, I mean not to pursue beyond a bug report here.  I believe it's still wrong unless "blackice-icecap" is still the most popular/common item run on the port.  If that is the case then yes I will close this.

**Comment by dmiller-nmap** [comment]
We stick to using IANA-supplied name assignments unless there is some overwhelmingly popular common service which uses the port. In this case, [Shodan shows](https://www.shodan.io/search?query=port%3A8081) the vast majority of services here to be HTTP, so there is not a good reason to change this.
