### ISSUE TITLE
Certificate error while installing npcap-0.9995

### ISSUE THREAD

**Issue by Gundares** [nmap/nmap#2083]
I am getting an error while installing npcap-0.9995 (the latest available for download on the NMAP website). In particular, the error happens when the installer tries to install the service; please, see the setupapi.dev.log extract. OS windows server 2012R2.
`>>>  [SetupCopyOEMInf - C:\Program Files\Npcap\NPCAP.inf]
>>>  Section start 2020/07/16 18:31:17.466
      cmd: "C:\Program Files\Npcap\NPFInstall.exe" -n -i
     sto: {Setup Import Driver Package: C:\Program Files\Npcap\NPCAP.inf} 18:31:17.466
     inf:      Provider: Nmap Project
     inf:      Class GUID: {4D36E974-E325-11CE-BFC1-08002BE10318}
     inf:      Driver Version: 07/09/2020,17.23.10.830
     inf:      Catalog File: npcap.cat
     sto:      {Copy Driver Package: C:\Program Files\Npcap\NPCAP.inf} 18:31:17.466
     sto:           Driver Package = C:\Program Files\Npcap\NPCAP.inf
     sto:           Flags          = 0x00000007
     sto:           Destination    = C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}
     sto:           Copying driver package files to 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}'.
     flq:           Copying 'C:\Program Files\Npcap\npcap.cat' to 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\npcap.cat'.
     flq:           Copying 'C:\Program Files\Npcap\NPCAP.inf' to 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\NPCAP.inf'.
     flq:           Copying 'C:\Program Files\Npcap\npcap.sys' to 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\npcap.sys'.
     sto:      {Copy Driver Package: exit(0x00000000)} 18:31:17.482
     pol:      {Driver package policy check} 18:31:17.497
     pol:      {Driver package policy check - exit(0x00000000)} 18:31:17.497
     sto:      {Stage Driver Package: C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\NPCAP.inf} 18:31:17.497
     inf:           {Query Configurability: C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\NPCAP.inf} 18:31:17.513
     inf:                Driver package 'NPCAP.inf' is configurable.
     inf:           {Query Configurability: exit(0x00000000)} 18:31:17.513
     flq:           Copying 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\npcap.cat' to 'C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\npcap.cat'.
     flq:           Copying 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\NPCAP.inf' to 'C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\NPCAP.inf'.
     flq:           Copying 'C:\Users\KMSAdmin\AppData\Local\Temp\2\{76ff007b-f8df-4c48-9854-da3879fb0969}\npcap.sys' to 'C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\npcap.sys'.
     sto:           {DRIVERSTORE IMPORT VALIDATE} 18:31:17.529
     sig:                {_VERIFY_FILE_SIGNATURE} 18:31:17.544
     sig:                     Key      = NPCAP.inf
     sig:                     FilePath = C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\NPCAP.inf
     sig:                     Catalog  = C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\npcap.cat
!    sig:                     Verifying file against specific (valid) catalog failed! (0x800b0109)
!    sig:                     Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
     sig:                {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 18:31:17.575
     sig:                {_VERIFY_FILE_SIGNATURE} 18:31:17.575
     sig:                     Key      = NPCAP.inf
     sig:                     FilePath = C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\NPCAP.inf
     sig:                     Catalog  = C:\Windows\System32\DriverStore\Temp\{2882ed06-10ba-5a40-a80a-8b4c57d11d47}\npcap.cat
!    sig:                     Verifying file against specific Authenticode(tm) catalog failed! (0x800b010a)
!    sig:                     Error 0x800b010a: A certificate chain could not be built to a trusted root authority.
     sig:                {_VERIFY_FILE_SIGNATURE exit(0x800b010a)} 18:31:17.575
!!!  sig:                Driver package catalog file certificate does not chain to a root, and Code Integrity is enforced.
!!!  sig:                Driver package failed signature validation. Error = 0xE0000247
     sto:           {DRIVERSTORE IMPORT VALIDATE: exit(0xe0000247)} 18:31:17.575
!!!  sig:           Driver package failed signature verification. Error = 0xE0000247
!!!  sto:           Failed to import driver package into Driver Store. Error = 0xE0000247
     sto:      {Stage Driver Package: exit(0xe0000247)} 18:31:17.575
     sto: {Setup Import Driver Package - exit (0xe0000247)} 18:31:17.591
!!!  inf: Failed to import driver package into driver store
!!!  inf: Error 0xe0000247: A problem was encountered while attempting to add the driver to the store.
<<<  Section end 2020/07/16 18:31:17.653
<<<  [Exit status: FAILURE(0xe0000247)]`

**Comment by Gundares** [comment]
Found an issue in my machine's cert store. Closing it now.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
