### ISSUE TITLE
Add option to report the result of all the host discovery techniques

### ISSUE THREAD

**Issue by bendikro** [nmap/nmap#2090]
nmap supports providing multiple host discovery options, however, only the result of one of the techniques is returned.

### Example with only `ICMP Ping echo` option
`$ nmap -sn -PE 74.207.244.221`
```
 <host starttime="1315618421" endtime="1315618434">
  <status state="up" reason="echo-reply"/>
  <address addr="74.207.244.221" addrtype="ipv4"/>
 </host>
```

Result `state="up" reason="echo-reply"`

### Example with `ICMP Ping echo` option as well as `TCP ACK Ping` option
`$ nmap -sn -PE -PA 74.207.244.221`
```
 <host starttime="1315618421" endtime="1315618434">
  <status state="up" reason="reset"/>
  <address addr="74.207.244.221" addrtype="ipv4"/>
 </host>
```
Result `state="up" reason="reset"`

The reason this example has `reason="reset"` is due to a firewall configured to respond with a TCP packet with the RST flag in response to an unexpected TCP ACK (as described in [PR1616](https://github.com/nmap/nmap/pull/1616))

### The problem
So when nmap sends a TCP ACK ping (-PA) as well as ICMP ping (-PE), the resulting value of `reason` simply depends on which technique got a response first, which in my case usually is the TCP RST packet from the firewall. However, sometimes it's the ICMP echo reply from the host that comes first, in which case the result will be `reason="echo-reply"`.

Therefore there are two issues when a firewall is configured to respond with a TCP RST on TCP ACK packets (TCP ACK ping):
1. The result of a host discovery (`reason`) for a valid host may vary depending on which response packet arrives first.
2. There is no way to distinguish between a host that exists (where an `ICMP echo reply` packet was actually received, but came last) and a host that doesn't exist. In both cases the result will be `state="up" reason="reset"`.

### Suggested solution
Have a cmd option to include the result of all the host discovery techniques being used.

**Comment by fyodor** [comment]
Thanks for your suggestion.  If we always had all the results, I agree it would be worth printing them.  But in general, as soon as Nmap's host discovery engine gets the first response, it marks the host as up and moves on to the next stage and/or other hosts.  It would be less efficient to wait around for more responses once Nmap already knows what it needs for host discovery purposes.  So if you want to know whether the host responds to ping and also whether it responds to a TCP ack, you would be better off running Nmap twice (possibly at the same time).  Cheers!
