### ISSUE TITLE
Speed improvement for script afp-ls 

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#2098]
Script `afp-ls` spends an exorbitant amount of time on collecting file details because files on a volume are first enumerated but then individual file parameters, such as size, permissions, and modification time, are queried one request at a time. In the end, roughly 3*N+1 requests are sent for a volume with N files.

It appears possible to utilize the initial enumeration (which uses `FPEnumerateExt2` at the protocol level) to receive all the necessary file details as well, so only one request is needed per volume, even though somewhat larger.

The performance improvement is rather dramatic, typically between 5x to 20x for real-life volumes.

The [patch](https://gist.github.com/nnposter/9d45542b811d620dc615d5fca796cee2) will be committed in a few weeks if no concerns are raised.

**Comment by nnposter** [comment]
The patch has been committed as r37992.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
