### ISSUE TITLE
Document the new issue/bug tracker

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#21]
We should document this shiny new issue tracker in the Nmap book and man page, e.g.:

http://nmap.org/book/man-bugs.html

If it's not more than a page or so, we can probably just put it all there.  But if there's more that warrants documentation in helping users use this properly, we should probably put it into Ch1 or 2 and then just include a reference in this man page and a very short summary.

For stuff only needed by admins of the issue tracker (tagging, etc.) we should probably create a secwiki page for best practices, tag meanings, etc.

**Comment by dmiller-nmap** [comment]
This is done in the man page and on the website. We get far more issue reports here than on the mailing list, so I'd say it's a success.
