### ISSUE TITLE
nmap [-PU][-PA] disabled?

### ISSUE THREAD

**Issue by Largehare** [nmap/nmap#2102]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
i type **nmap -sn -PU53 192.168.0.1/24** to use udp scan to find living host(no port scan). then i found nmap had its own thoughts still sent arp to recon from wireshark. (so did -PA) i am a noob. is there any changes when nmap updating that i dont know?

**To Reproduce**
wireshark
nmap -sn -PU53 192.168.0.1/24

**Expected behavior**
sending udp or tcp to scan 

**Version info (please complete the following information):**
 - OS: [kali linux2020]
 - Output of `nmap --version`:

Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d libssh2-1.8.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

 - Output of `nmap --iflist`

Starting Nmap 7.80 ( https://nmap.org ) at 2020-08-13 00:03 EDT
************************INTERFACES
DEV  (SHORT) IP/MASK                     TYPE     UP MTU   MAC
lo   (lo)    127.0.0.1/8                 loopback up 65536
lo   (lo)    ::1/128                     loopback up 65536
eth0 (eth0)  192.168.0.111/24            ethernet up 1500  00:0C:29:A9:B3:61
eth0 (eth0)  fe80::20c:29ff:fea9:b361/64 ethernet up 1500  00:0C:29:A9:B3:61

**************************ROUTES
DST/MASK                     DEV  METRIC GATEWAY
192.168.0.0/24               eth0 100
0.0.0.0/0                    eth0 100    192.168.0.1
::1/128                      lo   0
fe80::20c:29ff:fea9:b361/128 eth0 0
::1/128                      lo   256
fe80::/64                    eth0 100
ff00::/8                     eth0 256

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by nnposter** [comment]
From the Nmap man page:

> Also note that ARP/Neighbor Discovery is done by default against targets on a local Ethernet network even if you specify other -P* options, because it is almost always faster and more effective.

**Comment by Largehare** [comment]
> From the Nmap man page:
> 
> > Also note that ARP/Neighbor Discovery is done by default against targets on a local Ethernet network even if you specify other -P* options, because it is almost always faster and more effective.

i see. interesting option

**Comment by nnposter** [comment]
Consider what needs to happen on the wire when you want to use the other options, such as your `-PU53`. The system still needs to perform ARP resolution before it can send the UDP packet. If the scanner receives the ARP response then in almost all circumstances this L2 packet alone is already a reliable signal that the host is up. There is no point to send the actual UDP packet.

Please close the issue if this sufficiently explains the observed behavior.
