### ISSUE TITLE
nmap-services: port 27350 is MATLAB Job Scheduler server's default

### ISSUE THREAD

**Issue by martinwguy** [nmap/nmap#2103]
Not a *bug*, but a standard port that's not included in nmap-services.

Reference: https://www.mathworks.com/help/matlab-parallel-server/troubleshoot-common-problems.html

About half way down, 7th heading:

Verify Network Communications for Cluster Discovery / DNS SRV Record
[...]
 * MJS_PORT is the port on which you connect to the MATLAB Job Scheduler server. The default is 27350, but if you change it for the server you must change it here accordingly.

Blessings!

    M

**Comment by goarblt** [comment]
hello
https://www.evil.com/
