### ISSUE TITLE
SYN scan broken since r37979

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#2107]
SYN scan no longer detects open ports. All come back as "filtered". (Regular connect scan works fine.) Bisection of the commits identified r37979 (cfff367aa641fb1fceec8bbb290e249d0892edd4) as the culprit.

Observed on Ubuntu 18.04 x86-64 with kernel 4.15.0-112-generic

**Comment by dmiller-nmap** [comment]
Thanks for catching this; that's embarrassing! I'll try to sort it out.

**Comment by dmiller-nmap** [comment]
Got it. I had relocated the pointer increment to outside the switch statement, but the switch condition was supposed to use the previous value of the pointer. I'm working also  on handling the case of `optlen == 1` at the beginning of the loop, which might cause us to read off the end of the options by 1 byte.

**Comment by nnposter** [comment]
I can confirm that the fix resolves the issue. Thank you!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
