### ISSUE TITLE
Zenmap fails to start in MacOS Catalina v10.15.6

### ISSUE THREAD

**Issue by jjdsantos** [nmap/nmap#2108]
The installation of Zenmap on MacOS Catalina was successfully and completed without errors.
However, when I started Zenmap, and after entered my "admin" credentials, the Zenmap suddently closes without any error.

On Console/system.log , I saw the following errors:

Aug 26 12:35:39 iMac Zenmap[2081]: /Applications/Zenmap.app/Contents/MacOS/zenmap.bin
Aug 26 12:35:49 iMac Zenmap[2081]: Failed to execute applescript with admin privileges, trying without.
Aug 26 12:35:49 iMac Zenmap[2081]: Failed to execute applescript at all.

Note: This occurred in several versions of MacOS Catalina v 10.x.x

 - OS: MacOS Catalina v10.15.6 and older minor versions of Catalina v10
 - Current version of Zenmap

Please, someone can help me?
Thanks in advance
Regards
Julio

**Comment by avenged110** [comment]
I, too, have this issue, but on OS X 10.9.5. Nmap 7.80 (Zenmap) installs and works without issue. 7.90-7.92 experience the same situation noted above. This occurs on a fresh install of 10.9.5 as well.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
