### ISSUE TITLE
smb.lua:816: Invalid reuse of a socket from one thread to another

### ISSUE THREAD

**Issue by phomchick** [nmap/nmap#2111]
nmap fails when running --script discovery

Command invocation:
kali@kali:~$ sudo nmap -d --script discovery 192.168.1.0/24 -oX report.xml >./debug.txt

DEBUG output:
NSE: [smb-ls 192.168.1.149] Share name:\\192.168.1.149\IPC$
NSE: smb-ls against 192.168.1.149 threw an error!
/usr/bin/../share/nmap/scripts/smb-ls.nse:134: /usr/bin/../share/nmap/nselib/smb.lua:816: Invalid reuse of a socket from one thread to another.
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nse_main.lua:207: in function </usr/bin/../share/nmap/nse_main.lua:205>
        (...tail calls...)
        /usr/bin/../share/nmap/scripts/smb-ls.nse:134: in upvalue 'list_files'
        /usr/bin/../share/nmap/scripts/smb-ls.nse:205: in function </usr/bin/../share/nmap/scripts/smb-ls.nse:170>
        (...tail calls...)
nmap: nse_nsock.cc:369: void callback(nsock_pool, nsock_event, void*): Assertion `lua_status(L) == LUA_YIELD' failed.
Aborted

Environment:
Hardware: Raspberry Pi 4

kali@kali:~$ lsb_release -a                                                                                                      
No LSB modules are available.                                                                                                    
Distributor ID: Kali                                                                                                             
Description:    Kali GNU/Linux Rolling                                                                                           
Release:        2020.3                                                                                                           
Codename:       kali-rolling

Nmap version 7.80 ( https://nmap.org )
Platform: arm-unknown-linux-gnueabihf
Compiled with: liblua-5.3.3 openssl-1.1.1g libssh2-1.8.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Comment by nnposter** [comment]
This appears to be a known bug. Please see https://github.com/nmap/nmap/issues/1837#issuecomment-567647708 and report back.

**Comment by phomchick** [comment]
It appears to be the same bug. On a guess that the Kali distribution does not have the current version of nmap, I downloaded https://nmap.org/dist/nmap-7.80.tar.bz2 and used that to compile and install a new version, but I get the same error. I tried to use svn to make sure I had the latest source code, but "svn co https://svn.nmap.org/nmap fails with "svn E170013: Unable to connect to a repository at URL 'https://svn.nmap.org/nmap'; svn E000110: Error running context: Connection timed out.

**Comment by phomchick** [comment]
SVN works in Ubuntu, so I think there are problems with Kali that I need to understand. Let's close this report for now.

**Comment by nnposter** [comment]
Yes, the patch was committed after the release of 7.80 so it is to be expected that https://nmap.org/dist/nmap-7.80.tar.bz2 is still broken.

I see no issues with accessing https://svn.nmap.org/nmap .

**Comment by goarblt** [comment]
hello
https://www.evil.com/
