### ISSUE TITLE
can't find interface "rmnet_data1" 

### ISSUE THREAD

**Issue by vishal-chaudhary30** [nmap/nmap#2124]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nmap --version`:
 - Output of `nmap --iflist`

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by fyodor** [comment]
I'm closing this since I don't see any actual report text -- just our empty template.  There is a title, but that's not enough to go on.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
