### ISSUE TITLE
Nsock: Poll engine uses excessive CPU on Windows when only PCAP sockets are used

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#2127]
Most of Nsock's engines have a workaround for PCAP handles on systems where those cannot be used with `select()` or whatever system function the engine is built on. The workaround is to just try a nonblocking PCAP read at the start of the loop and return immediately if there's something there, otherwise execute the main part of the loop. With the Poll engine, this basically means there's nothing to do and we busy-loop until a packet arrives.

Long-term fix would probably be to shim in some sort of event wait using `pcap_get_event()` for Windows, but maybe there's a better way to structure all these engines in this case. At least we need to be sure of the behavior of Poll() in the case of no sockets as input.

To reproduce: `nping google.com -c 10 --delay 2 --nsock-engine poll`

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by dmiller-nmap** [comment]
We discussed this issue today as a performance improvement, apart from the excessive CPU usage. A solution to this issue with Nsock would also be good to apply to the Nmap scan engine.

**Comment by dmiller-nmap** [comment]
This does not occur with the select Nsock engine because the select call essentially becomes a sleep. This is even true on Windows because we're using nbase's `fselect()` function, which detects the no-fds-set condition that would fail with WSASelect and instead just calls `usleep()`. The simple solution, therefore, is to add 'no-fds-set-check-and-sleep' to the relevant engines. This can be guarded by `#ifndef PCAP_CAN_DO_SELECT`, since there's already a check for no events that is sufficient on platforms and engines where pcap handles can be used as input to poll (or whatever synchronization function is being used).

**Comment by dmiller-nmap** [comment]
Fixed in b94ae785ba05cc8690d25c43c802931e799452ed
