### ISSUE TITLE
Using nmap version 7.80 on Windows 10 causes a BSOD every time

### ISSUE THREAD

**Issue by StewAlexander-com** [nmap/nmap#2134]
Hi all

I have the following system:
```
OS Name:                   Microsoft Windows 10 Enterprise 2016 LTSB
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

On a Dell Optiplex, with nmap 7.80 installed via Chocolatey 

Whenever I try to execute an nmap scan it creates a BSOD, looks like the root cause is with the tcp.sys driver

This just started happening, I believe the instigator when I attempted to run ```nmap -aV''' against itself

Any ideas as to the cause, and possible fixes?

**Comment by StewAlexander-com** [comment]
Reinstalling nmap via Chocolatey had no effect

**Comment by dmiller-nmap** [comment]
We do not distribute Nmap through Chocolatey. Try downloading Npcap 1.00 from https://npcap.org/#download and installing that, then installing  Nmap from https://nmap.org/download.html. If you still have problems, please provide output of `nmap --version`.

**Comment by StewAlexander-com** [comment]
Someone does

**Comment by StewAlexander-com** [comment]
Installed npcap via Wireshark, re-installed nmap issue fixed

Ok to close

**Comment by goarblt** [comment]
hello
https://www.evil.com/
