### ISSUE TITLE
Ncat isn't built with make (all)

### ISSUE THREAD

**Issue by boite** [nmap/nmap#214]
There is a make target to build Ncat, but it's not a dependency of the "all" target.  Thus, make install fails:-

    $ ./configure && make
    # make install
    ...
    make: *** No rule to make target `ncat/ncat', needed by `install-ncat'. Stop.

**Comment by nnposter** [comment]
I can confirm that the issue has been around for a while (also noted by Robin Wood in http://seclists.org/nmap-dev/2015/q3/271) and that the patch offered in http://seclists.org/nmap-dev/2015/q3/337 addresses the issue.

That said, a permanent resolution might first standardize the naming convention used in the make files.

**Comment by mubix** [comment]
Confirmed, and it causes issues in build scripts unfortunately :/

**Comment by asdfljdasflkjwfd** [comment]
I am still getting 'make: *** No rule to make target `ncat/ncat', needed by `install-ncat'.  Stop.' with current master
