### ISSUE TITLE
Kali linux 2020.3 Zenmap not working 

### ISSUE THREAD

**Issue by Zanzaux** [nmap/nmap#2151]
Hi I have installed zenmap but I cannot start it, the icon is created in the kali menu, but the program does not start.

 apt install alien
 alien zenmap-7.91-2.noarch.rpm

dpkg -i zenmap_7.91-2_all.deb

from the terminal I get the following error
zenmap
Could not import the zenmapGUI.App module: 'No module named gtk'.
I checked in these directories:
    /usr/bin
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-x86_64-linux-gnu
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /usr/local/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.6/site-packages
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.

**Comment by dmiller-nmap** [comment]
Zenmap requires the pygtk library. This is a package dependency issue, which you should bring up with the Kali Linux maintainers: https://www.kali.org/docs/community/submitting-issues-kali-bug-tracker/

**Comment by Zanzaux** [comment]
Ok Thanks, pygtk 2 has been removed from kali as it is obsolete.

**Comment by Zanzaux** [comment]
Ok Thanks, pygtk 2 has been removed from kali as it is obsolete , io hope updated with python 3  spero be able to use Zenmap again soon.

**Comment by Seferovic8** [comment]
Unstable works
Try this:
nix run -f channel:nixos-unstable nmap_graphical

**Comment by crazyskills** [comment]
Thanks, Seferovic8. Worked for me on 2021.1.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
