### ISSUE TITLE
Feature request: Add docker-discovery script.

### ISSUE THREAD

**Issue by jigordev** [nmap/nmap#2172]
The docker-containers script is able to retrieve informations about docker containers present on the machine through the Docker API.

Github repository: https://github.com/jigordev/nmap-scripts/blob/main/docker-containers.nse

**Comment by jigordev** [comment]
The docker-discovery script is able to retrieve informations about docker containers, images, networks, volumes and plugins present on the machine through the Docker API.

Github repository: https://github.com/jigordev/nmap-scripts/blob/main/docker-discovery.nse

**Comment by goarblt** [comment]
hello
https://www.evil.com/
