### ISSUE TITLE
Ncat question about passing client ip and port to external programs stdin

### ISSUE THREAD

**Issue by CanadianJeff** [nmap/nmap#2189]
I am coding a C++ program which I am using on top of Ncat
ncat -lv4Ck 10001 -e /usr/local/bin/myprogram
how can I get ncat to pass along the clients ip and port into myprograms stdin?

**Comment by nnposter** [comment]
Ncat is not passing this info via `stdin`. You should query environment variables `NCAT_REMOTE_ADDR` and `NCAT_REMOTE_PORT` instead.

You can try it with this trivial utility:
```c
#include <stdlib.h>
#include <stdio.h>
#define ADDR "NCAT_REMOTE_ADDR"
#define PORT "NCAT_REMOTE_PORT"
int main (int argc, char **argv)
{
fprintf(stderr,"%s=%s\n%s=%s\n",ADDR,getenv(ADDR),PORT,getenv(PORT));
return 0;
}
```
Running client `ncat -v 192.168.100.37 10001` resulted in the following:
```
$ ncat -lv4Ck 10001 -e ./envtest
Ncat: Version 7.80SVN ( https://nmap.org/ncat )
Ncat: Listening on 0.0.0.0:10001
Ncat: Connection from 192.168.100.29.
Ncat: Connection from 192.168.100.29:50211.
NCAT_REMOTE_ADDR=192.168.100.29
NCAT_REMOTE_PORT=50211
```

**Comment by CanadianJeff** [comment]
thank you so much I really appreciate the help
