### ISSUE TITLE
http-passwd gets "attempt to get length of a nil value (local 'buf')" error

### ISSUE THREAD

**Issue by tatulea** [nmap/nmap#2191]
**Describe the bug**
I am trying to run a scan using `http-passwd` script, but the `unicode.lua` module fails to decode the response.

```
NSE: http-passwd against 34.102.136.180:8080 threw an error!
/usr/local/bin/../share/nmap/nselib/unicode.lua:35: attempt to get length of a nil value (local 'buf')
stack traceback:
	/usr/local/bin/../share/nmap/nselib/unicode.lua:35: in function 'unicode.decode'
	/usr/local/bin/../share/nmap/nselib/url.lua:226: in function 'url.parse'
	/usr/local/bin/../share/nmap/nselib/url.lua:281: in function 'url.absolute'
	/usr/local/bin/../share/nmap/nselib/http.lua:1700: in function 'http.parse_redirect'
	/usr/local/bin/../share/nmap/nselib/http.lua:1766: in function 'http.get'
	/usr/src/app/nmap_scripts/http-passwd.nse:161: in function </usr/src/app/nmap_scripts/http-passwd.nse:121>
	(...tail calls...)
```

Same error is returned for `https-redirect` for some hosts as well.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Output of `nmap --version`: 7.80

**Comment by nnposter** [comment]
This issue has been likely resolved by commit 8515e83671adda522959807e785ce415cfad54b5, Please attempt to reproduce the error with Nmap 7.91. If the issue does persist then please provide the value of the problematic `Location` header returned by the target.

**Comment by nnposter** [comment]
Issue presumably resolved

**Comment by goarblt** [comment]
hello
https://www.evil.com/
