### ISSUE TITLE
citrix-enum-servers-xml can return error

### ISSUE THREAD

**Issue by tatulea** [nmap/nmap#2192]
**Describe the bug**
I have run the following scan:

```
NSE: citrix-enum-servers-xml against wordpress.com (192.0.78.9:443) threw an error!
/usr/local/bin/../share/nmap/nselib/citrixxml.lua:50: bad argument #1 to 'char' (value out of range)
stack traceback:
	[C]: in function 'string.char'
	/usr/local/bin/../share/nmap/nselib/citrixxml.lua:50: in function 'citrixxml.decode_xml_document'
	(...tail calls...)
	...al/bin/../share/nmap/scripts/citrix-enum-servers-xml.nse:37: in function <...al/bin/../share/nmap/scripts/citrix-enum-servers-xml.nse:35>
	(...tail calls...)
```

It seems like the `citrixxml.lua` has an error. For the scan run above the value of `escaped_val` is `&#8212;` and the value of `hexval` is `8212`, which can not to converted to char using `string.char`.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Output of `nmap --version`: 7.80

**Comment by nnposter** [comment]
Thank you for reporting the issue. A fix has been committed as r38146. The implemented change will leave character references with codepoints higher than 255 untouched.
