### ISSUE TITLE
Upgrade Nmap Windows Builds to use Visual Studio 2019 instead of 2013

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2198]
Even though we build Npcap with Visual Studio 2019, we're still using VS 2013 for Nmap because we use (and want to continue using) a different build system for that.  First we need to upgrade the Nmap Windows build system because it's currently an under-resourced Windows 8.1 VM.  So we will probably want to buy new hardware and then set up a new VM.  Or maybe we'll set up an Azure cloud instance.

**Comment by dmiller-nmap** [comment]
This was done for Nmap 7.92 in 5707fb14c5c7af3aa867e733d883c6300acf5e74 and b7687223c15593f12ee3f34a4fa8763586410e45
