### ISSUE TITLE
Add virtualhost option to http-default-accounts

### ISSUE THREAD

**Issue by l0nedigit** [nmap/nmap#2207]
**Describe the bug**
In the case where a DNS name is discovered (e.g. in SSL certificate, vhost brute forcing, etc.) and the name does not resolve via DNS server (potentially removed previously and virtual host not removed) it is not possible (unless you modify hosts file).  If an option to specify a vhost in the command and specify ip:port as usual for the target would overcome this.  If target is ip:port and vhost is specified in Host header option, DNS resolution can be avoided all together.

**To Reproduce**
1. Create a virtual host with a name that does not resolve via DNS on web application of choice with a default login account already present inside of http-default-accounts script
2. Run http-default-accounts on the host specifying target as <ip>:<port>

**Expected behavior**
The expected result is to display that the login page has default account

**Comment by nnposter** [comment]
Please use command-line option `--script-args http.host=your_target_vhost`

More at https://nmap.org/nsedoc/lib/http.html#script-args

**Comment by l0nedigit** [comment]
Ah perfect, didn't realize that was an option. Thanks for letting me know.
