### ISSUE TITLE
Blue screen on install

### ISSUE THREAD

**Issue by Jarod997** [nmap/nmap#2210]
**Describe the bug**
Ran "nmap-7.91-setup.exe" - setup causes blue screen. This has happened with the direct nmap install, and while trying to install WireShark.

**To Reproduce**
Double click "nmap-7.91-setup.exe" from (my) downloads folder.

**Expected behavior**
Install with no blue screen.

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
>Windows 10 Pro: 10.0.1904

 - Output of `nmap --version`:
>WARNING: Could not import all necessary Npcap functions. You may need to upgrade to the latest version from https://npcap.org. Resorting to connect() mode -- Nmap may not function completely
>Nmap version 7.91 ( https://nmap.org )
>Platform: i686-pc-windows-windows
>Compiled with: nmap-liblua-5.3.5 openssl-1.1.1h nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 nmap-libdnet-1.12 ipv6
>Compiled without:
>Available nsock engines: iocp poll select

 - Output of `nmap --iflist`
>WARNING: Could not import all necessary Npcap functions. You may need to upgrade to the latest version from https://npcap.org. Resorting to connect() mode -- Nmap may not function completely
>Starting Nmap 7.91 ( https://nmap.org ) at 2020-12-17 08:33 Eastern Standard Time
>************************INTERFACES************************
>DEV  (SHORT) IP/MASK                      TYPE     UP MTU  MAC
>eth0 (eth0)  fe80::d0b6:8fdb:3d54:1887/64 ethernet up 1500 00:D8:61:5D:53:3B
>eth0 (eth0)  10.0.0.197/24                ethernet up 1500 00:D8:61:5D:53:3B
>lo0  (lo0)   ::1/128                      loopback up -1
>lo0  (lo0)   127.0.0.1/8                  loopback up -1

**Additional context**
Not sure if I have any special circumstances which would contribute to a Blue Screen.

**Comment by Spessmen14** [comment]
Also getting a BSOD with same conditions. Run npcap install, get BSOD. Every time. 

Can't upload my minidumps since this POS website rejects...a zip file...like it says to upload.

**Comment by Spessmen14** [comment]
[Minidump.zip.txt](https://github.com/nmap/nmap/files/5732965/Minidump.zip.txt)

Added .txt at the end so it uploads.

**Comment by dmiller-nmap** [comment]
Thanks for these reports. This is a known issue with Npcap, resulting from a bad interaction between an existing Npcap installation and the Npcap version bundled with Nmap. The solution is to not install Npcap from the Nmap installer but instead download the latest Npcap (version 1.10 at the moment) from https://npcap.org/#download and install that.

**Comment by Spessmen14** [comment]
IT STILL HAPPENS.

Same bsod code.

**Comment by dmiller-nmap** [comment]
@Spessmen14 Does this crash happen if you run the Npcap 1.10 installer? I think I might have an idea what has happened: the 1.00 installer replaced the earlier Uninstall.exe with the one that triggers the crash in the existing Npcap installation. The new installer doesn't do this, but the damage is already done. Workaround: as Administrator, run `net stop npcap` then run the Npcap 1.10 installer.

**Comment by Spessmen14** [comment]
Yes, that's what happens, every time.

**Comment by Spessmen14** [comment]
Annnd it worked.

For the LUVVA GAWD, please put this potential problem-solving info where it
might help others.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by goarblt** [comment]
hello
https://www.evil.com/
