### ISSUE TITLE
Script ip-geolocation-map-bing produces invalid XML output 

### ISSUE THREAD

**Issue by f-froehlich** [nmap/nmap#2214]
**Describe the bug**
Script ip-geolocation-map-bing produces invalid XML output like:

```
<script id="ip-geolocation-map-bing">
    <elem>Script argument problem</elem>
    <elem>Need to specify an API key, get one at https://www.bingmapsportal.com/.</elem>
</script>
```

so attribute "output" is missing

**To Reproduce**
Execute the script and take a look on its XML output.

**Expected behavior**
The script should output XML, which is valid with your DTD.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04 (but I think it doesn't matter)
 - Output of `nmap --version`:
 `
Nmap version 7.91SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1f nmap-libssh2-1.9.0 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
`

**Comment by AnonymousWebHacker** [comment]
@f-froehlich 
This is momentary, in case you need it
`curl -s http://ip-api.com/json/$(curl -s https://ipinfo.io/ip) | jq '.query, .country, .city, .org, .isp'`
The value, [curl -s https://ipinfo.io/ip] you can change it for a specific ip

**Comment by f-froehlich** [comment]
Thank you for the hint but even it is so, the script-tag should have an "output" attribute like the following to be conform with the DTD.
```
<script id="ip-geolocation-map-bing" output="Script argument problem">
    <elem>Script argument problem</elem>
    <elem>Need to specify an API key, get one at https://www.bingmapsportal.com/.</elem>
</script>
```

**Comment by dmiller-nmap** [comment]
Duplicate #2216

**Comment by AnonymousWebHacker** [comment]
@f-froehlich In the command output I can't help you, I'm not from the nmap developer team, I just put a variant that you could use

**Comment by goarblt** [comment]
hello
https://www.evil.com/
