### ISSUE TITLE
Script ip-geolocation-map-google produces invalid XML

### ISSUE THREAD

**Issue by f-froehlich** [nmap/nmap#2215]
**Describe the bug**
Script ip-geolocation-map-google produces invalid XML output like:

```
<script id="ip-geolocation-map-google">
    <elem>Script argument problem</elem>
    <elem>Need to specify an API key, get one at
        https://developers.google.com/maps/documentation/static-maps/.
    </elem>
</script>
```

so attribute "output" is missing

**To Reproduce**
Execute the script and take a look on its XML output.

**Expected behavior**
The script should output XML, which is valid with your DTD.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04 (but I think it doesn't matter)
 - Output of `nmap --version`:
 `
Nmap version 7.91SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1f nmap-libssh2-1.9.0 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
`

**Comment by dmiller-nmap** [comment]
Duplicate #2216

**Comment by goarblt** [comment]
hello
https://www.evil.com/
