### ISSUE TITLE
Hosthint produces invalid XML output

### ISSUE THREAD

**Issue by f-froehlich** [nmap/nmap#2217]
**Describe the bug**
hosthint produces invalid XML output like:

```
<hosthint>
    <status state="up" reason="arp-response" reason_ttl="0"/>
    <address addr="[[ADDR]]" addrtype="ipv4"/>
    <address addr="[[ADDR]]" addrtype="mac" vendor="[[VENDOR]]"/>
    <hostnames>
    </hostnames>
</hosthint>
```
Note: [[ADDR]] and [[VENDOR]] are replaced by me and valid addresses in the real XML output.

**To Reproduce**
Execute a scan with XML output and parse it against your DTD. You will got the following error:

```
VALID:DTD_CONTENT_MODEL: Element hosthint content does not follow the DTD, expecting (status , address , hostnames)*, got (status address address hostnames )
```

**Expected behavior**
Nmap should output XML, which is valid with your DTD.

**Solution**
Update your DTD as followed:
```
- <!ELEMENT hosthint (status,address,hostnames)* >
+ <!ELEMENT hosthint (status,address*,hostnames)* >
```

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04 (but I think it doesn't matter)
 - Output of `nmap --version`:
 `
Nmap version 7.91SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1f nmap-libssh2-1.9.0 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
`

**Update:**
I just have seen, that you DTD allows also multiple hostnames so may it should change to
```
- <!ELEMENT hosthint (status,address,hostnames)* >
+ <!ELEMENT hosthint (status, address*, hostnames*) >
```
This also exclude multiple staus-elements, which not exist

**Comment by goarblt** [comment]
hello
https://www.evil.com/
