### ISSUE TITLE
Work under vpn

### ISSUE THREAD

**Issue by hastalamuerte** [nmap/nmap#2220]
.

**Comment by hastalamuerte** [comment]
help plllzzz
https://prnt.sc/wf2w27 i got nordlynx tunnel with 0.0.0.0.0 ip (nordvpn). For example core impact succefuly see 2 adapters and let me choose one for work - i set nordlynx when on = ok, and another if... 

Can you plz add that function to nmap , and (switch gui) especially to Zenmap . 
Npcap driver succefuly install on both connections (on real, and nord tunnel)

Thx

**Comment by hastalamuerte** [comment]
Reserach with core impact by nmap net recon - with vpn no results . Without too - why? Because url under restrict in my country ))))))

**Comment by BitesizedLion** [comment]
can confirm issue.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
