### ISSUE TITLE
Support Lua 5.4

### ISSUE THREAD

**Issue by tuxmaster5000** [nmap/nmap#2223]
The nmap source code will only work with lua 5.3.
To use 5.4 only an few lines must changed and the test will pass.
Because nmap comes with an bundled one an PR will change to much, so I have attached the needed diffs as an patch.
The background for it, was to use the native lua on Fedora 33, which was changed to 5.4
[lua5.4.patch.zip](https://github.com/nmap/nmap/files/5791465/lua5.4.patch.zip)

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by great944** [comment]
I am curious if there are any known issues that prevents LUA 5.4.4 in main? I am updating locally on windows, any input on the subject is appreciated. 
Thank you.
