### ISSUE TITLE
linux nmap script iax2-brute command

### ISSUE THREAD

**Issue by mohamadtay** [nmap/nmap#2224]
on i try to register iax2 with iax2-brute script
i use this commad  but 
nmap -sU -p 4569  --script iax2-brute 192.168.1.42
i have this output 
Host is up (0.026s latency).
PORT     STATE         SERVICE
4569/udp open|filtered unknown
| iax2-brute:
|   Accounts
|     No valid accounts found
|   Statistics
|_    Performed 0 guesses in 1 seconds, average tps: 0

now i try to set username and passwords list
using this commadn

nmap -sU -p 4569  --script iax2-brute 192.168.1.42  --script-args userdb=users.lst,passdb=dpass.lst

Host is up (0.026s latency).
PORT     STATE         SERVICE
4569/udp open|filtered unknown
|_iax2-brute: Invalid usernames iterator
users.lst
and 
dpass.lst
i set it in root folder
i have result 
Invalid usernames iterator

My result must be a valid registration

**Comment by nnposter** [comment]
If you call nmap with `--script-args userdb=users.lst,passdb=dpass.lst` then both these files are expected to be in the current working directory, not in the root directory or any of nmap directories.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
