### ISSUE TITLE
Ncat doesn't write response to file before closing

### ISSUE THREAD

**Issue by Maratk1n** [nmap/nmap#2225]
Hello,
I use latest ncat
`Ncat: Version 7.91 ( https://nmap.org/ncat )`
and trying to send UDP package. But I have problem with writing to file while using the command
`cat ./tests/invite_x_rc_failover.sip | /usr/bin/nc -w 1 -u -C --no-shutdown -o /tmp/nc_output.txt 127.0.0.1 5060`
or
`/usr/bin/nc -w 1 -u -C --no-shutdown -o /tmp/nc_output.txt 127.0.0.1 5060 < ./tests/invite_x_rc_failover.sip`
I expect the file to contain both a request and a response, but it only contains a request.

Is it possible to catch response while using UDP mode?

**Comment by nnposter** [comment]
The obvious issue with UDP is that there is no way to tell when ncat should stop listening for inbound packets so your experience is not surprising. Options `-w 1` and `--no-shutdown` do not apply here.

In your case I would consider the following trick to keep `stdin` open long enough for the response to arrive:
```
(cat ./tests/invite_x_rc_failover.sip; sleep 3) | ncat -u -C -o /tmp/nc_output.txt 127.0.0.1 5060
```

**Comment by Maratk1n** [comment]
@nnposter thank you for your reply.
I found this solution but I was hoping there are some other tricks like in the `netcat-openbsd`.
I mean the following option
```
-q      after EOF on stdin, wait the specified number of seconds and then quit.
        If seconds is negative, wait forever.
```
but I'm not really sure if it would help me.

However, I should try the `sleep` with subshell.
