### ISSUE TITLE
Error al instalar ncap 0x8007007e

### ISSUE THREAD

**Issue by alexrivaxx** [nmap/nmap#2233]
A la hora de instalar ncap se desinstala, me salta ese error. Como hago para solucionarlo.
![error ncap](https://user-images.githubusercontent.com/77743356/105205361-7a708e80-5b45-11eb-9fde-40b2fa2e8a1f.PNG)

**Comment by fyodor** [comment]
Thanks for opening the issue, but it should have been opened in the Npcap tracker rather than Nmap.  And I think this has probably already been fixed.  If you are still encountering this with Npcap 1.31, please open an issue on that tracker.  Thanks!
