### ISSUE TITLE
Chrome is marking nmap-7.91-setup.exe as dangerous

### ISSUE THREAD

**Issue by kdawg14** [nmap/nmap#2234]
This isn't a bug with the software, rather a concern with downloading from the website.

**Describe the bug**
When trying to download the latest nmap installer by clicking https://nmap.org/dist/nmap-7.91-setup.exe from the download page, Chrome displays a warning indicating that it's unsafe.

The site ahead contains harmful programs
Attackers on nmap.org might attempt to trick you into installing programs that harm your browsing experience (for example, by changing your homepage or showing extra ads on sites you visit). Learn more

transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fnmap.org%2Fdist%2Fnmap-7.91-setup.exe&hl=en-US

**To Reproduce:**
Using Version 88.0.4324.96 (Official Build) (64-bit) of Chrome on Windows 10 Enterprise (don't know if other versions are also affected but would assume so), go to https://nmap.org/dist/nmap-7.91-setup.exe.

**Expected behavior**
Should be able to download without error

**Version info (please complete the following information):**

- OS: Windows 10 Enterprise
- Browser: Chrome Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by kdawg14** [comment]
It looks like Chrome is no longer blocking it and the transparencyreport.google.com link referenced in the original issue is no longer showing unsafe content found.

**Comment by fyodor** [comment]
Thanks for the report, @kdawg14.  Google's system wrongfully flagged a 10-year-old Windows version of Ncat as malware and they then blocked the entire download directory of roughly 500 files.  That meant Nmap releases (which were also in that directory) were blocked by Chrome from download for some unfortunate hours before Google fixed it :/.

**Comment by kdawg14** [comment]
Thanks, @fyodor. Frustrating to be sure, but I'm glad to hear that's all it was :)

**Comment by goarblt** [comment]
hello
https://www.evil.com/
