### ISSUE TITLE
Integrate IPv6 OS classification engine changes from Summer 2015

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#224]
@alegen did some great work to improve IPv6 OS fingerprinting, and we want this to be included in our next release.

**Comment by fyodor** [comment]
We think we have integrated all the "easy" improvements which were clear wins.  The imputation still remains but even though that sounds like a great benefit, we had mixed empirical results when testing it against our database and so we may need more work on that before it can be integrated. So closing this for now.
