### ISSUE TITLE
How to contribute to the Japanese documentation?

### ISSUE THREAD

**Issue by tkmru** [nmap/nmap#2243]
The Japanese documentation for nmap is available at https://nmap.org/man/ja/index.html, but it has not been maintained for a long time and is far from up-to-date.

For example, the latest documentation says [`--host-timeout <time>`](https://nmap.org/book/man-performance.html), but the Japanese documentation says
[`--host-timeout <milliseconds>`](https://nmap.org/man/ja/man-performance.html) is still the same.

I would like to fix these old descriptions. How can I contribute?

**Comment by dmiller-nmap** [comment]
Thanks for your interest! Our documentation translations are unfortunately stuck describing the version of Nmap that was current when they were made. We would love to keep them current, and that depends on users like you submitting corrections and improvements. The general guidelines are [here on nmap.org](https://nmap.org/xlate-faq.html). The Japanese translation refers to Nmap 4.50. The commit 0012ee3deead26e646eaef45e4fee1901159f8dc is around that time, so you can compare the current `docs/refguide.xml` with that one to see what has changed in the English version. You can make smaller changes and updates if you would prefer, but we'll need some way to mark those, at least in the XML source, as having been addressed already. Maybe a simple `<!-- XML comment -->` would work.

**Comment by tkmru** [comment]
Thanks for answering my question!
I was surprised that the Japanese documentation was older than I imagined.
Now that I know how to contribute, I'll try to contribute in my spare time. Thanks.

**Comment by tkmru** [comment]
@dmiller-nmap I emailed you from Google Workspace 9 days ago, did you receive it?
Is there any problem with email address of Google Workspace?
