### ISSUE TITLE
Upgrade Nmap's PCRE library (libpcre)

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2250]
We currently bundle LibPCRE 7.6 and use it for our Linux, Windows, and Mac binary packages.  Since 7.X is no longer officially supported, we should upgrade to the latest stable version.  As of 2021-02-13, the latest PCRE release is 8.44.  There is also a new PCRE2 library which is up to version 10.36.  New features are only added to PCRE2.  The upgrade to latest PCRE should be fairly straighforward since Linux distributions already link Nmap to newer PCRE with no issues.  We could also consider upgrading to PCRE2.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by fyodor** [comment]
OK, libpcre (one) is now officially end-of-life with the current 8.45 release expected to be the last one.  I'm not sure there's much value upgrading to that instead of just jumping to the current version (libpcre2) as proposed in #1335.  Unless we identify some major problem/difficulty with the generational upgrade. So I'm closing this issue and replacing it with #1335 on our roadmap.
