### ISSUE TITLE
'http-enum' NSE Script and script argument 'http-fingerprints.nikto-db-path'

### ISSUE THREAD

**Issue by TW-D** [nmap/nmap#2251]
**Describe the bug**
The 'http-fingerprints.nikto-db-path' argument of the nse 'http-enum' script doesn't work

**To Reproduce**
```bash
nmap -p 80 --script="http-enum" --script-args="http-enum.displayall,http-fingerprints.nikto-db-path='/var/lib/nikto/databases/db_dictionary'" testphp.vulnweb.com
```

**Expected behavior**
I'm waiting for the script to use the specified Nikto database and not the default one.

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
```
5.4.0-65-generic 
#73-Ubuntu
```
 - Output of `nmap --version`:
 ```
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d nmap-libssh2-1.8.2 libz-1.2.11 libpcre-8.39 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
 - Output of `nmap --iflist`
 ```
not necessary
```
**Additional context**
```
:~$ cat /var/lib/nikto/databases/db_dictionary | grep "wp"
showpost
wp
wp-content
wp-dbmanager
wp-includes
wp-login
wp-syntax
```
```
:~$ curl -i "http://<HOST>/wp"
HTTP/1.1 301 Moved Permanently
```
```
:~$ nmap -p 80 --script="http-enum" --script-args="http-enum.displayall,http-fingerprints.nikto-db-path='/var/lib/nikto/databases/db_dictionary'" <SAME-HOST>
Nothing :(
```

**Comment by nnposter** [comment]
The issue you are running into is that the Nmap fingerprint code is designed to load a file formatted as Nikto `db_tests` database, such as:
```
"000006","0","1234576890ab","@CGIDIRSflexform.cgi","GET","200","","","","","Check Phrack 55 for info by RFP, allows to append info to writable files.","",""
"000007","0","1234576890ab","@CGIDIRSflexform","GET","200","","","","","Check Phrack 55 for info by RFP, allows to append info to writable files.","",""
```
while you are trying to load `db_dictionary`.

**Comment by TW-D** [comment]
Thanks **nnposter** for your help. you are right this to work. But if I only want to discover directories by example then I have to use the argument 'http-enum.fingerprintfile' ? But the value 'db_dictionary' won't work because Nmap is waiting for a LUA file, how can I do that?

**Comment by SKYSAW144** [comment]
Pass it a LUA file then?

**Comment by TW-D** [comment]
Yes **SKYSAW144**, but I'm sorry, I wasn't specific enough. Is there a guide of good practice for this?

**Comment by nnposter** [comment]
You can use the following impromptu fingerprint file to load `db_dictionary` from Nikto:
```lua
local io = require "io"
local string = require "string"
local table = require "table"
local stdnse = require "stdnse"
local nmap = require "nmap"

fingerprints = {};

local nikto_db_path = stdnse.get_script_args("http-fingerprints.nikto-db-path") or "db_dictionary"
nikto_db_path = nmap.fetchfile(nikto_db_path) or nikto_db_path
local f = io.open(nikto_db_path, "r")

if f then
  f:close()
  stdnse.debug1("Found nikto db.")
  local probes = {}
  for l in io.lines(nikto_db_path) do
    local path = l:match("^%s*([^#%s].-)%s*$")
    if path then
      table.insert(probes, {path = "/" .. path, method = "HEAD"})
    end
  end
  table.insert(fingerprints, {
    category = "nikto",
    probes = probes,
    matches = {{match = "", output = "Nikto db_dictionary match"}},
  })
end
```
Use it as follows:
```
nmap .... --script-args fingerprintfile=<thisfile>,nikto-db-path=db_dictionary ...
```
... getting output such as:
```
PORT   STATE SERVICE
80/tcp open  http
| http-enum: 
|_  /SiteScope: Nikto db_dictionary match
```

**Comment by TW-D** [comment]
Thanks **nnposter** for your script, by writing it line by line. The structure of a raw Nikto file should be 
```
stdnse.pretty_printer(fingerprints)

{
    [1] = {
        ["matches"] = {
            [1] = {
                ["match"] = "",
                ["output"] = "Nikto db_dictionary match",
            },
        },
        ["probes"] = {
            [1] = {
                ["method"] = "HEAD",
                ["path"] = "/test1",
            },
            [2] = {
                ["method"] = "HEAD",
                ["path"] = "/test2",
            },
            [...]
        },
        ["category"] = "nikto"
    }
}
```

it's understood, again all my thanks for your help

**Comment by nnposter** [comment]
Yes, that's one way: having statically defined fingerprints. However, keep in mind that the fingerprint file is very powerful because it is just executed Lua code. As long as it populates the `fingerprints` table, it can do whatever you need, such as parsing another source on the fly or use the HTTP library to pull data directly from the web.
