### ISSUE TITLE
Force probe detection

### ISSUE THREAD

**Issue by tatulea** [nmap/nmap#2259]
Hi,

From what i've seen, nmap uses two types of detection: table and probe.
Is there a possibility to force nmap to use probe for all the scans? If it cannot decide that service is running based on the probe, I would prefer it to return tcpwrapped.

Also, there is a confidence level from what i've seen. What is the link between the type (table or probe) and confidence level? Is it something like "for the table detection the maximum confidence level is 5 and for probe the minimum is 6", or can it be that there is a table detection with a high confidence level like 8?

**Comment by fyodor** [comment]
The issues DB is more for Nmap bugs than for questions about how Nmap works.  I'd suggest mailing the nmap dev list instead.  Also, see https://nmap.org/book/man-version-detection.html for more details on this probing.  Cheers.
