### ISSUE TITLE
-Pn says scan times will be slower, will they?

### ISSUE THREAD

**Issue by digininja** [nmap/nmap#2261]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
Scanning with -Pn gives this message:

> Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.

**Expected behavior**
I've already done host discovery scans and know that all the hosts I'm scanning are up and are responding well, so will the scan times really be slower?

Or is this just a warning that it could be slower as it could be trying to access hosts that don't exist?

If it is just that they could be slower, the warning should say may, not will.

**Comment by fyodor** [comment]
Scan times will generally be slower but I guess for some scans it may not make much difference.  I just changed it to "may be slower" in #38196.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
