### ISSUE TITLE
Nmap bug: malformed nmap-payloads packets sent

### ISSUE THREAD

**Issue by mzet-** [nmap/nmap#2268]
**Description**
While working on [PR #2266](https://github.com/nmap/nmap/pull/2266) I've noticed that UDP scan: `nmap -n -sU -p427 <target>` does not correctly detects OpenSLP service:

```
PORT    STATE         SERVICE
427/udp open|filtered svrloc
```
While service detection scan: `nmap -n -sU -p427 <target> -sV` detects it as expected:

```
PORT    STATE SERVICE VERSION
427/udp open  svrloc  Service Location Protocol 2
```

Even though payload in `nmap-payloads` is correct and equivalent to probe in`nmap-service-probe`, specifically `nmap-payloads` payload:

```
# svrloc
udp 427
  "\x02\x01\x00\x006 \x00\x00\x00\x00\x00\x01\x00\x02en\x00\x00\x00\x15"
  "service:service-agent\x00\x07default\x00\x00\x00\x00"
```

`nmap-service-probe` probe:

```
# svrloc
Probe UDP svrloc q|\x02\x01\x00\x006 \x00\x00\x00\x00\x00\x01\x00\x02en\x00\x00\x00\x15service:service-agent\x00\x07default\x00\x00\x00\x00|
```
After observing the `nmap-payloads` packet that is acutally sent (under wireshark) it can be indeed observed that it is malformed and different than the one that is in `nmap-payloads` file:

![image](https://user-images.githubusercontent.com/4785347/111035174-7b24f300-8419-11eb-94fe-b4ab3317d95f.png)

Whereas service detection probe (`-sV`) sends correct packet:

![image](https://user-images.githubusercontent.com/4785347/111035305-23d35280-841a-11eb-9746-54ebec0c1ecf.png)

**Root cause**

After spending some time in the debugger I found subtle issue that caused corrupting the packets. The issue was introduced in commit [9c83be38331adff3d23b154eadace9263edfab48](https://github.com/nmap/nmap/commit/9c83be38331adff3d23b154eadace9263edfab48).

At https://github.com/nmap/nmap/blob/master/payload.cc#L318 we can see std::vector declared locally (on the stack); at https://github.com/nmap/nmap/blob/master/payload.cc#L332 iterator is created for this vector; finally at https://github.com/nmap/nmap/blob/master/payload.cc#L343 the pointer to the data of locally declared vector is returned.

**Comment by mzet-** [comment]
@bonsaiviking, can you look at this and merge associated [fix](https://github.com/nmap/nmap/pull/2269) at your earliest convenience? This issue makes whole `payloads.cc` subsystem dysfunctional since Sep 2020. Thanks.

**Comment by mzet-** [comment]
@fyodor, @dmiller-nmap, @nnposter are you really not interested in this? UDP scanning (`-sU`) is broken for Nmap in versions `7.90` and `7.91`. Please just compare results of UDP scanning between Nmap `7.80` and `7.91` and you will notice that the latter one does not correctly detects opened ports (I've already verified it for following UDP ports: `53, 123, 161, 389, 427`).

Distros like Kali and Arch (and probably other) are already shipped with Nmap in version 7.91 so many pen testers and admins out there are severely impacted by this issue. I believe we should address this issue promptly - [the patch](https://github.com/nmap/nmap/pull/2269) is pending.

**Comment by cldrn** [comment]
Didn't see inconsistent results against OpenVPN UDP but it should be tested for other UDP services that does return an exact match. 

```
Starting Nmap 7.91SVN ( https://nmap.org ) at 2021-04-20 15:46 PDT
Nmap scan report for 10.0.4.152
Host is up (0.00036s latency).

PORT     STATE         SERVICE VERSION
1194/udp open|filtered openvpn

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 104.53 seconds
```



```
Starting Nmap 7.80 ( https://nmap.org ) at 2021-04-20 15:49 PDT
Nmap scan report for 10.0.4.152
Host is up (0.00045s latency).

PORT     STATE         SERVICE VERSION
1194/udp open|filtered openvpn

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 104.22 seconds

```

**Comment by mzet-** [comment]
But why did you choose for checking the service that is not correctly detected by the version `7.80` (probably due to not ideal packet payload (from `nmap-payloads`)? We're dealing with the regression (caused by the [9c83be38331adff3d23b154eadace9263edfab48](https://github.com/nmap/nmap/commit/9c83be38331adff3d23b154eadace9263edfab48) commit) here so please verify a service that is correctly detected by the version `7.80` and is not detected by the version `7.91`.

See below (version `7.80`):

```
nmap -sU -n -p123,389 10.0.140.10
Starting Nmap 7.80 ( https://nmap.org ) at 2021-04-22 05:00 EDT
Nmap scan report for 10.0.140.10
Host is up (0.012s latency).

PORT    STATE SERVICE
123/udp open  ntp
389/udp open  ldap
```
Version `7.91`:

```
nmap -sU -n -p123,389 10.0.140.10
Starting Nmap 7.91 ( https://nmap.org ) at 2021-04-22 05:02 EDT
Nmap scan report for 10.0.140.10
Host is up (0.012s latency).

PORT    STATE         SERVICE
123/udp open|filtered ntp
389/udp open|filtered ldap
```

And the fixed (`master`):

```
~/nmap-master# git diff
diff --git a/payload.cc b/payload.cc
index c7bfe8fb6..d45af7940 100644
--- a/payload.cc
+++ b/payload.cc
@@ -315,7 +315,6 @@ int init_payloads(void) {
 const char *udp_port2payload(u16 dport, size_t *length, u8 tryno) {
   static const char *payload_null = "";
   std::map<struct proto_dport, std::vector<struct payload> >::iterator portPayloadIterator;
-  std::vector<struct payload> portPayloadVector;
   std::vector<struct payload>::iterator portPayloadVectorIterator;
   proto_dport key(IPPROTO_UDP, dport);
   int portPayloadVectorSize;
@@ -323,7 +322,7 @@ const char *udp_port2payload(u16 dport, size_t *length, u8 tryno) {
   portPayloadIterator = portPayloads.find(key);
 
   if (portPayloadIterator != portPayloads.end()) {
-    portPayloadVector = portPayloads.find(key)->second;
+    std::vector<struct payload>& portPayloadVector = portPayloads.find(key)->second;
     portPayloadVectorSize = portPayloadVector.size();
 
     tryno %= portPayloadVectorSize;

~/nmap-master# ./nmap -sU -n -p123,389 10.0.140.10
Starting Nmap 7.91SVN ( https://nmap.org ) at 2021-04-22 05:08 EDT
Nmap scan report for 10.0.140.10
Host is up (0.012s latency).

PORT    STATE SERVICE
123/udp open  ntp
389/udp open  ldap
```

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by ymgh96** [comment]
I have still malformed packet for OpenVPN on a non-default port in nmap v7.93. And get open|filtered status.
nmap with -sU  just send two udp packets (doesn't send multiple UDP payloads!)
