### ISSUE TITLE
Assertion failed: p != NULL (netutil.cc: route_dst_netlink: 3190)

### ISSUE THREAD

**Issue by Phone-Metal** [nmap/nmap#2285]
**Describe the bug**
![Screenshot_20210412_104815.jpg](https://user-images.githubusercontent.com/74254069/114341905-a3b91d80-9b7c-11eb-9c7c-3fc7564c8189.jpg)

**To Reproduce**
`nmap` `target`

**Expected behavior**
A Normal Nmap Scan 

**Version info:**

 - OS: Alpine Linux v3 

 - Output of nmap --version : 
`Nmap version 7.91 
Platform: aarch64-alpine-linux-musl
Compiled with: liblua-5.3.6 openssl-1.1.1h libssh2-1.9.0 libz-1.2.11 libpcre-8.44 libpcap-1.10.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select` 

 - Output of nmap --iflist: `INTERFACES: NONE FOUND(!)
ROUTES: NONE FOUND(!)`

**Comment by goarblt** [comment]
hello
https://www.evil.com/
