### ISSUE TITLE
Why do I only get three script output?

### ISSUE THREAD

**Issue by benjiamin911** [nmap/nmap#2292]
I using the nmap for smb vuln scan. The command just like: nmap-- smb-vuln* -p 135,139,445 10.11.1.5. However it seem like I only get three script output. 
![image](https://user-images.githubusercontent.com/30366193/115506288-45431c00-a2ad-11eb-8fa7-07b13dbff690.png)
But it really run for all script according to the -dd option, showing for the debug information
![image](https://user-images.githubusercontent.com/30366193/115506192-2d6b9800-a2ad-11eb-81c9-f9ae89825a9f.png)
What can I do if I really want all script output?

**Comment by nnposter** [comment]
Scripts are generally designed to produce output only if there are findings to report. They typically do not output messages like "*Nothing found*". Otherwise the real findings would get potentially drowned in the sea of non-actionable noise.

It is not a rule but some scripts do produce "negative" debug messages so you should try to run Nmap with option `-d`.

**Comment by cldrn** [comment]
Hi,
Most of those scripts use the library vulns. You can include the output of those scripts by adding the library arguments `vulns.showall`. This will make Nmap generate output reports even for non vulnerable hosts.

[NSE vulns](https://nmap.org/nsedoc/lib/vulns.html)

**Comment by benjiamin911** [comment]
> Hi,
> Most of those scripts use the library vulns. You can include the output of those scripts by adding the library arguments `vulns.showall`. This will make Nmap generate output reports even for non vulnerable hosts.
> 
> [NSE vulns](https://nmap.org/nsedoc/lib/vulns.html)

It works!!! Thank you

**Comment by benjiamin911** [comment]
您好，来函已至，我会尽快查阅您的邮件的！       
 
   This is an automatic reply, confirming that your e-mail was received.Thank you
