### ISSUE TITLE
Assertion failed: probe->tryno == maxtries

### ISSUE THREAD

**Issue by kost** [nmap/nmap#2293]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
Scanning with following flags: 
```nmap -PE -PS21,22,23,25,53,79,80,111,135,139,161,443,445,497,515,548,993,1025,1028,1029,1917,2869,5000,6000,8080,9001,9100,49000 -PA80 -PP -PU53,67,68,69,80,123,136,139,161,162,40125 -sT -sV -T4 -p0-65535 -v -iL targets -oA output```

```
Starting Nmap 7.91SVN ( https://nmap.org ) at 2021-04-21 10:58 IST
NSE: Loaded 155 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 10:58
Completed NSE at 10:58, 0.00s elapsed
Initiating NSE at 10:58
Completed NSE at 10:58, 0.00s elapsed
Initiating NSE at 10:58
Completed NSE at 10:58, 0.00s elapsed
Initiating Ping Scan at 10:58
Scanning 2318 hosts [42 ports/host]
Ping Scan Timing: About 0.31% done
Ping Scan Timing: About 0.62% done
Ping Scan Timing: About 0.92% done
Ping Scan Timing: About 1.23% done; ETC: 13:42 (2:41:32 remaining)
Assertion failed: probe->tryno == maxtries (scan_engine.cc: processData: 2656)
```

**To Reproduce**
You can take static binaries from here:
https://github.com/ernw/static-toolbox/releases/tag/nmap-v7.91SVN

And run scan 

**Expected behavior**

**Version info (please complete the following information):**

Linux host 4.1.12-124.46.4.1.el7uek.x86_64 #2 SMP Wed Jan 6 13:08:02 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

/opt/nmap/nmap --version
Nmap version 7.91SVN ( https://nmap.org )
Platform: x86_64-pc-linux-musl
Compiled with: nmap-liblua-5.3.5 openssl-1.0.2-chacha nmap-libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without: libssh2
Available nsock engines: epoll poll select

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by LizardBlizzard** [comment]
Experiencing the same issue as @kost 

**Version info**:
**nmap --version**
`Nmap version 7.91SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1f nmap-libssh2-1.9.0 libz-1.2.11 libpcre-8.39 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select`
**uname -a**
`Linux ubuntu20 5.4.0-1036-azure #38-Ubuntu SMP Wed Jan 6 18:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by gMemiy** [comment]
The same issue.

nmap -v -sUV -T4 -F -sV -O

Nmap version 7.91SVN ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1h nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-1.00 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Comment by dmiller-nmap** [comment]
This is a bad interaction between the new multiple-payloads code for UDP (#1859) and the fact that `-T4` sets the equivalent of `--max-retries=6`. Probably related commit: 6310b7d9e3cbf8c82d97308f277a073d3b239d41

**Comment by RaduNico** [comment]
I've tried playing a bit around with the max retries counter, but with no success. I've managed to bypass this issue by using the commit just before  6310b7d and the issue does not appear to happen anymore. Cheers dmiller-nmap!

`git checkout 58617a79f7e157d5c8a097926c979ee8670f201a`

**Comment by goarblt** [comment]
hello
https://www.evil.com/
