### ISSUE TITLE
About support python version

### ISSUE THREAD

**Issue by sandy-lcq** [nmap/nmap#2294]
Hi,

I noticed that python file under this project using shebang like : #!/usr/bin/env python
As we know,  python2 already EOL since Jan 2020.  So I suppose we will also only support python3, right?

if yes,  the best shebang should be #!/usr/bin/env python3.  Since python maybe not exist on some distro.
refer https://www.python.org/dev/peps/pep-0394/.

What is your opinion about this? 

Thanks.

**Comment by fyodor** [comment]
Thanks for your suggestion.  Zenmap does not currently support Python3.  But yeah, once we do move to Python3, it is likely that we won't worry much about Python2 support.
