### ISSUE TITLE
Nmap 7.70 executed as privileged (by sudo) with torsocks produces the error: route_dst_netlink: can't find interface "eth0"

### ISSUE THREAD

**Issue by D3vil0per** [nmap/nmap#2302]
**Describe the bug**
I'm testing nmap in Stealth Scan mode over Tor to check the effect and see if on my test machine what I can see in term of logs.
For doing this, I use torsocks (2.3.0 version) since, if I enable tor on my system and I don't use torsocks, I get all scanned ports as "opened" (False Positive).

In this test, let's guess we have:
- A: 1 VM that works as a Gateway that routes the traffic over Tor. OS: Debian GNU/Linux 10 (buster); Kernel: Linux 4.19.0-16-amd64
- B: 1 VM that use the first VM as gateway and that executes nmap over Tor. OS: Debian GNU/Linux 10 (buster); Kernel: Linux 4.19.0-16-amd64
- C: 1 VM that is the target of the port scan (let's guess it is scanme.nmap.org)

All the VMs work properly and Tor is enabled. The B VM surfs correctly on Internet.
On B VM, I execute the following command:

`torsocks nmap -sT -Pn -F -A -vvv scanme.nmap.org --system-dns`

It works properly since it returns open port: 80/tcp, 22/tcp (despite to adjust_timeout2 with rrt of 20557374 microseconds but ok for now).

Then, let's guess I need to perform a Stealth Scan, or for any reason, we want to perform the command as privileged mode by "sudo":

`sudo torsocks nmap -sS -Pn -F -A -vvv scanme.nmap.org --system-dns`

I will get the following output:

> Starting Nmap 7.70 ( https://nmap.org ) at 2021-05-07 02:46 UTC
> NSE: Loaded 148 scripts for scanning.
> NSE: Script Pre-scanning.
> NSE: Starting runlevel 1 (of 2) scan.
> Initiating NSE at 02:46
> Completed NSE at 02:46, 0.00s elapsed
> NSE: Starting runlevel 2 (of 2) scan.
> Initiating NSE at 02:46
> Completed NSE at 02:46, 0.00s elapsed
> route_dst_netlink: can't find interface "eth0"

I get the error "**route_dst_netlink: can't find interface "eth0"** " only when I run as sudo.

**To Reproduce**
`sudo torsocks nmap -sS -Pn -F -A -vvv scanme.nmap.org --system-dns`

**Expected behavior**
The expected behavior is a successful port scan on scanme.nmap.org (the target).

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 -- Debian GNU/Linux 10 (buster); Kernel: Linux 4.19.0-16-amd64
 - Output of `nmap --version`:
 -- Nmap version 7.70 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d libssh2-1.8.0 libz-1.2.11 libpcre-8.39 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
 - Output of `nmap --iflist`
> Starting Nmap 7.70 ( https://nmap.org ) at 2021-05-07 02:47 UTC
> ************************INTERFACES************************
> DEV  (SHORT) IP/MASK                    TYPE     UP MTU   MAC
> lo   (lo)    127.0.0.1/8                loopback up 65536
> lo   (lo)    ::1/128                    loopback up 65536
> eth0 (eth0)  10.152.152.11/18           ethernet up 1500  08:00:27:6D:0B:DA
> eth0 (eth0)  fe80::a00:27ff:fe6d:bda/64 ethernet up 1500  08:00:27:6D:0B:DA
> 
> **************************ROUTES**************************
> DST/MASK                    DEV  METRIC GATEWAY
> 10.152.128.0/18             eth0 0
> 0.0.0.0/0                   eth0 0      10.152.152.10
> ::1/128                     lo   0
> fe80::a00:27ff:fe6d:bda/128 eth0 0
> ::1/128                     lo   256
> fe80::/64                   eth0 256
> ff00::/8                    eth0 256 

**Additional context**
Even if I execute "ip addr show" I get:

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>     link/ether 08:00:27:6d:0b:da brd ff:ff:ff:ff:ff:ff
>     inet 10.152.152.11/18 brd 10.152.191.255 scope global eth0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::a00:27ff:fe6d:bda/64 scope link
>        valid_lft forever preferred_lft forever

In the /etc/network/interfaces file, the content is:

> ## Loopback interface.
> auto lo
> iface lo inet loopback
> 
> auto eth0
> iface eth0 inet static
>    
> address 10.152.152.11
> netmask 255.255.192.0
> gateway 10.152.152.10
> ##

The "route_dst_netlink: can't find interface "eth0" " should be produced by Nmap and not by torsocks. Why if I run "torsocks nmap" it is able to find eth0 interface while if I run it as "sudo torsocks nmap" it is not able to find eth0 and produces the route_dst_netlink: can't find interface "eth0" error?

Thank you for your support

**Comment by nnposter** [comment]
Here is my guess of what is going on:

From Nmap man page:

> By default, Nmap performs a SYN Scan, though it substitutes a connect scan if the user does not have proper privileges to send raw packets (requires root access on Unix). .... TCP connect scan is the default TCP scan type when SYN scan is not an option. This is the case when a user does not have raw packet privileges. Instead of writing raw packets as most other scan types do, Nmap asks the underlying operating system to establish a connection with the target machine and port by issuing the connect system call.

From Torsockets man page:

> torsocks is a library to allow transparent SOCKS proxying. It wraps the normal connect() function.

To put the two together:

1. Running SYN scan without sudo (or granting Nmap certain POSIX capabilities explicitly) is not possible, as it needs the ability craft its own packets and perform packet capture.
2. Running SYN scan over torsockets is not possible because the library is only intercepting regular connection requests, not injections of custom-crafted packets.

**Comment by D3vil0per** [comment]
Thank you for the answer @nnposter 

Your answer is true about SYN Scan. The only doubt that I have is:
for testing purpose, let's try to focus on the TCP connect scan instead of SYN scan.

If I execute `torsocks nmap -F -sT scanme.nmap.org -vvv --system-dns` it works properly:

> Starting Nmap 7.70 ( https://nmap.org ) at 2021-05-10 06:33 UTC
> Initiating Ping Scan at 06:33
> Scanning scanme.nmap.org (45.33.32.156) [2 ports]
> Completed Ping Scan at 06:33, 0.23s elapsed (1 total hosts)
> Initiating System DNS resolution of 1 host. at 06:33
> Completed System DNS resolution of 1 host. at 06:33, 0.00s elapsed
> DNS resolution of 1 IPs took 0.00s. Mode: System [OK: 0, ??: 1]
> Initiating Connect Scan at 06:33
> Scanning scanme.nmap.org (45.33.32.156) [100 ports]
> Discovered open port 22/tcp on 45.33.32.156
> Discovered open port 80/tcp on 45.33.32.156
> Completed Connect Scan at 06:33, 32.92s elapsed (100 total ports)
> Nmap scan report for scanme.nmap.org (45.33.32.156)
> Host is up, received syn-ack (0.33s latency).
> Scanned at 2021-05-10 06:33:23 UTC for 33s
> Not shown: 98 closed ports
> Reason: 98 conn-refused
> PORT   STATE SERVICE REASON
> 22/tcp open  ssh     syn-ack
> 80/tcp open  http    syn-ack
> 
> Read data files from: /usr/bin/../share/nmap
> Nmap done: 1 IP address (1 host up) scanned in 33.49 seconds

If I execute the same sudoed command as `sudo torsocks nmap -F -sT scanme.nmap.org -vvv --system-dns` we get the error specified in the main post issue:

> Starting Nmap 7.70 ( https://nmap.org ) at 2021-05-10 06:35 UTC
> route_dst_netlink: can't find interface "eth0"

In this case I expected that by sudo should be work, but we continue to get the **route_dst_netlink: can't find interface "eth0"** error

**Comment by D3vil0per** [comment]
Thank you @nnposter 
You're right. Without -Pn I'm still trying to use host discovery. If I follow your suggestion:

`sudo torsocks nmap -Pn -F -sT scanme.nmap.org -vvv --system-dns`

or

`torsocks nmap -Pn -F -sT scanme.nmap.org -vvv --system-dns`

It works well. It works also if I use -sV scan method but without "sudo":

`torsocks nmap -Pn -F -sV scanme.nmap.org -vvv --system-dns`

If I use "sudo" I continue to get "**route_dst_netlink: can't find interface "eth0"**  "(I don't know why at this point I get this error as sudo e no error with no sudo).

Also --scanflags with all the flags works well, for example:

torsocks nmap -Pn -F --scanflags URGACKPSHRSTSYNFIN -T4 scanme.nmap.org -vvv --system-dns

Even if, in this case, if I select --scanflags ACK, I don't know why I get open/closed ports instead of filtered/unfiltered.
If I use "sudo" I continue to get "route_dst_netlink: can't find interface "eth0" (I don't know why at this point I get this error as sudo e no error with no sudo).

Then, I tried also the remanent scanning techniques: -sS (TCP SYN scan), -sU (UDP scans), -sY (SCTP INIT scan), -sN; -sF; -sX (TCP NULL, FIN, and Xmas scans), -sA (TCP ACK scan), -sW (TCP Window scan), -sM (TCP Maimon scan), -sZ (SCTP COOKIE ECHO scan), -sI <zombie host>[:<probeport>] (idle scan), -sO (IP protocol scan).

All these scan techniques require to be executed by sudo. And if I use sudo, of course I continue to get the "**route_dst_netlink: can't find interface "eth0"**  " error in all these scanning techniques.

It means that is there no way to use all the remanent scanning techniques shown above by using torsocks?
Why with --scanflags ACK I get open/closed labels instead of filtered/unfiltered?

**Comment by nnposter** [comment]
SOCKS proxies are based on standard application-level connections so they do not support any scanning technique that requires custom packets. As an example, `-sA` sends a TCP ACK packet that is not part of any existing connection. Furthermore, SOCKS proxies, depending on the SOCKS version, support TCP and UDP at most. Furthermore, Tor (not just torproxy) does not support UDP.

**Comment by mdavids** [comment]
For what it is worth; the same error appears on an IPv6-only system (Ubuntu 20.04.3 LTS, Nmap 7.80), where even the loopback interface has been stripped from `127.0.0.1` and only has `::1`. Once that is added again, the error disappears.

**Comment by nnposter** [comment]
@mdavids This is not related. I have created issue #2416 to capture it.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by Dyln01** [comment]
us the command nmap --proxy http://127.0.0.1:9050 to use tor not torsocks that will work

**Comment by LatekVo** [comment]
This is old but i would like to point out that the result of this command:
`nmap --iflist` is 
```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-08-13 17:49 CEST
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                                    TYPE     UP   MTU   MAC
lo      (lo)      127.0.0.1/8                                loXXX
lo      (lo)      ::1/128                                    loXXX
eth0    (eth0)    19XXX                           etXXX
eth0    (eth0)    fdXXX etXXX
eth0    (eth0)    feXXX               etXXX
wlan0   (wlan0)   (none)/0                                   etXXX
docker0 (docker0) 172.XXX                             etXXX

**************************ROUTES**************************
DST/MASK                                    DEV     METRIC GATEWAY
192.XXX                              eth0    100
172.XXX                              docker0 0
0.0.0.0/0                                   eth0    100    192.XXX
::1/128                                     lo      0
fdXXX eth0    0
feXXX               eth0    0
fdXXX                    eth0    100
feXXX                                   eth0    1024
ff0XXX                                    eth0    256
``` (of course, i replaced addresses with XXX)
While the command: `torify nmap --iflist`
Returns: ```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-08-13 17:50 CEST
INTERFACES: NONE FOUND(!)
ROUTES: NONE FOUND(!)
```
I would suggest using what Dyln01 recommended in this thread, but the core issue with torify in my case is that it doesn't forward any interfaces to the supplied command.
