### ISSUE TITLE
nmap missing data on the last device

### ISSUE THREAD

**Issue by fceledon** [nmap/nmap#2310]
Doing:

`nmap nmap -v -sn 192.168.1.0/24`

the response is fine, except on the last device missing the MAC address:

```
Initiating ARP Ping Scan at 12:14
Scanning 255 hosts [1 port/host]
Completed ARP Ping Scan at 12:14, 7.66s elapsed (255 total hosts)
Initiating Parallel DNS resolution of 255 hosts. at 12:14
Completed Parallel DNS resolution of 255 hosts. at 12:14, 2.53s elapsed
Nmap scan report for 192.168.1.0 [host down]
....
Nmap scan report for 192.168.1.251 [host down]
Nmap scan report for 192.168.1.252 [host down]
Nmap scan report for 192.168.1.253 [host down]
Nmap scan report for dsldevice.attlocal.net (192.168.1.254)
MAC Address: F8:2D:C0:A7:F3:80 (Unknown)
Nmap scan report for 192.168.1.255 [host down]
Initiating Parallel DNS resolution of 1 host. at 12:14
Completed Parallel DNS resolution of 1 host. at 12:14, 0.00s elapsed
Nmap scan report for zm.attlocal.net (192.168.1.245)
Read data files from: /usr/bin/../share/nmap
           Raw packets sent: 494 (13.832KB) | Rcvd: 66 (1.848KB)

```
In this case, the device 'zm.attlocal.net' does not report the MAC address. (also the ip address is not the last, out of order).

Looks like there is no information about the host running **nmap** (in this case ZM)..

**Comment by dmiller-nmap** [comment]
MAC address is only available for targets which can be contacted via a link layer protocol. Loopback connections, which are used for contacting the scanning system itself, do not have link-layer addresses. You can verify this by running `ifconfig lo` and confirming that the `lo` device does not have a `HWaddr`, or by running `arp -an` and confirming that there is no MAC address for your own IP address in the ARP table.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
