### ISSUE TITLE
Missing git version tags.

### ISSUE THREAD

**Issue by kloczek** [nmap/nmap#2311]
In https://github.com/nmap/nmap/tags there is no even single version tag.
It would be good to add at least last version tag (just `<version>` with dots and numbers).

**Comment by tamiradari** [comment]
I vote up for this.
Tags will allow a convenient way to compare between NMAP versions.
I have no idea how to it today.

**Comment by fyodor** [comment]
This is a good idea, but might not work so well with our current processes.  Right now we branch releases off our SVN repo, often way in advance (for major releases).  Then we may pick and choose just very safe/stable improvements from the trunk to add to that major release branch.  So at the time of release, it may be quite a bit different from any moment in time from the Github (or SVN) trunk.  So there's no exact tag which would recreate it.  I don't think the SVN release branches are currently public (mostly from a desire to save certain exciting features as surprises for major releases), but of course we release all the source code in a tarball when we do the release.

Note that we do keep a [log of the changes and dates of each release](https://nmap.org/changelog).

We are leaning toward moving from SVN (with this Github mirror) to full-Github in the future.  At that point we might want to revisit our release branching procedures, how we use the tag features, etc.  So for now I'm closing this, but folks are still welcome to comment and we may re-open when it is more feasible to create an accurate tag for each release.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
