### ISSUE TITLE
[Feature Request] Support sending request data as an argument to an executable (ncat)

### ISSUE THREAD

**Issue by hwittenborn** [nmap/nmap#2318]
I'm in the middle of creating a basic file checker for a program I use (Drone CI), and it needs to check data (from an HTTP request) and verify that the data in it is valid, and return a status code if it is or isn't.

My current approach to doing this is running `ncat -lp 80 -e /path/to/program -o /tmp/output-file.txt`, and having the program read from the temp file, and deleting it upon completion.

The problem comes when I need to accept multiple requests at once. In theory, this is possible with `ncat -lkp 80 -e /path/to/program -o /tmp/output-file.txt`, but it becomes an issue real quick when multiple requests are yet to be responded to, as it results in the output of multiple requests in `/tmp/output-file.txt`, making it a lot harder to properly tell which request came from who.

Drone CI is **supposed** to be the only thing sending requests, which does result in some kind of conformity to the data being sent in, but it's also possible for outside forces to send in requests, which is what makes it more challenging to properly parse requests.

My proposed solution is based off the `-o`/`--output` option. I would like to send the output of `ncat` as an argument to any given program, here being `/path/to/program`. This would avoid having to write to a file at all, and would only require the program to read its list of passed arguments, avoiding any potential mixed requests issues, as requests aren't even put with each other in the first place.

**Comment by nnposter** [comment]
I am perhaps missing something, but why are you passing data from `ncat` to `program` via file, instead of `stdin`?

**Comment by hwittenborn** [comment]
@nnposter As of my current knowledge, I can't pass things like HTTP headers and data to a program.

That approach has led me to storing `ncat`'s output in a file so it can be retrieved by my program.

*Is* it possible to pass such data to my program from `ncat`?

**Comment by hwittenborn** [comment]
@nnposter I'm attempting to use the `/dev/stdin` method, but it keeps hanging when running `cat` on it. Any ideas?

**Comment by hwittenborn** [comment]
@nnposter I've gotten all the above stuff working, but now I have a new issue:

Any time I use redirects (i.e. `> /dev/null`), the script just hangs, and I can't figure out why.

I'm needing to store the value of `/dev/stdin` inside of a variable (in a bash script), in which the following is hanging after the `tee` command on the first line:

```sh
#!/bin/bash
cat /dev/stdin | tee "/tmp/$$.txt" &> /dev/null

export input="$(cat "/tmp/$$.txt")"
```

**Comment by hwittenborn** [comment]
More testing:

The same issue is appearing to happen whenever I'm "attempting to hide" output(??):

```sh
#!/bin/bash
echo 'HTTP/1.1 200 OK'
echo
cat /dev/stdin | dd status=none of="/tmp/$$.txt"
```

**Comment by hwittenborn** [comment]
Moved issue to https://github.com/nmap/nmap/issues/2319.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
