### ISSUE TITLE
How to control CPU utilization under 100%

### ISSUE THREAD

**Issue by minofmax** [nmap/nmap#2328]
when I use the cmd which is 'nmap --nsock-engine=epoll -Pn XXX -p1-65535 -sT --open --script=banner --min-rtt-timeout 1ms --max-rtt-timeout 500ms --defeat-rst-ratelimit --max-retries 0 --max-scan-delay 0 --min-rate 3000 --max-parallelism 100 --min-parallelism 100'. The cpu utilization will increase to 100%, and when the cpu undef full occupied, the result is not exactly right, some open port will not in result.

so, how can I control cpu utilization under 100%?

**Comment by goarblt** [comment]
hello
https://www.evil.com/
