### ISSUE TITLE
Unable disable scripts from arguments

### ISSUE THREAD

**Issue by WHK102** [nmap/nmap#2329]
By example, when need use all basic scripts but exclude one, for me need scann a host using `-A` over multiple ports but prevent send http request, when waf dettect a intrusion the IPS bans me, can not disable only the nmap http requests.

By example: `nmap -A --exclude-script "http-*" addr`

**Comment by cldrn** [comment]
You could use the expression `"and not(http-*)"` when selecting scripts.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
