### ISSUE TITLE
False positives in enumerated ciphers reported by ssl-enum-ciphers.nse

### ISSUE THREAD

**Issue by agritik89** [nmap/nmap#2332]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
nmap sometimes shows a cipher as a supported cipher for an SSL endpoint. But probing using `openssl s_client` seems to imply that the endpoint does not actually support the said cipher. 

**To Reproduce**

```
$ nmap --script ssl-enum-ciphers.nse -p12770 localhost
Starting Nmap 7.60 ( https://nmap.org ) at 2021-07-04 08:38 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000056s latency).
PORT   STATE SERVICE
/tcp open unknown
| ssl-enum-ciphers: 
|  TLSv1.2: 
|   ciphers: 
|    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (prime256v1) - A
|   compressors: 
|    NULL
|   cipher preference: client
|_ least strength: A
Nmap done: 1 IP address (1 host up) scanned in 0.54 seconds

```
**Notice below that using a different address causes more ciphers to be enumerated**

```
$ nmap --script ssl-enum-ciphers.nse -p12770 127.0.0.1
Starting Nmap 7.60 ( https://nmap.org ) at 2021-07-04 08:38 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000057s latency).
PORT   STATE SERVICE
/tcp open unknown
| ssl-enum-ciphers: 
|  TLSv1.2: 
|   ciphers: 
|    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (prime256v1) - A
|    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (prime256v1) - A
|    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 2048) - A
|    TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|    TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|    TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|    TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|    TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|   compressors: 
|    NULL
|   cipher preference: client
|   warnings: 
|    64-bit block cipher 3DES vulnerable to SWEET32 attack
|_ least strength: C
Nmap done: 1 IP address (1 host up) scanned in 0.56 seconds

```

**Trying to use one of the "extra" reported ciphers fails. This happens irrespective of what particular address is used as the parameter for connect and whether the cipher is insecure etc.**

```

$ openssl s_client -connect localhost:12770 -tls1_2 -cipher ECDHE-RSA-DES-CBC3-SHA
CONNECTED(00000005)
139769949999552:error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available:../ssl/statem/statem_clnt.c:3786:No ciphers enabled for max supported SSL/TLS version
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
  Protocol : TLSv1.2
  Cipher  : 0000
  Session-ID: 
  Session-ID-ctx: 
  Master-Key: 
  PSK identity: None
  PSK identity hint: None
  SRP username: None
  Start Time: 1625387495
  Timeout  : 7200 (sec)
  Verify return code: 0 (ok)
  Extended master secret: no
---

$ openssl s_client -connect 127.0.0.1:12770 -tls1_2 -cipher ECDHE-RSA-DES-CBC3-SHA
CONNECTED(00000005)
140131877401024:error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available:../ssl/statem/statem_clnt.c:3786:No ciphers enabled for max supported SSL/TLS version
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
  Protocol : TLSv1.2
  Cipher  : 0000
  Session-ID: 
  Session-ID-ctx: 
  Master-Key: 
  PSK identity: None
  PSK identity hint: None
  SRP username: None
  Start Time: 1625387512
  Timeout  : 7200 (sec)
  Verify return code: 0 (ok)
  Extended master secret: no
---


```

**Expected behavior**

It should be possible to use enumerated ciphers with the scanned endpoint or at least the endpoint should not report that the said cipher is unsupported.

**Version info (please complete the following information):**

 - OS: Ubuntu 18.04.5 LTS; Linux 5.4.0-1038-aws x86_64

 - Output of `nmap --version`:

Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.0g nmap-libssh2-1.8.0 libz-1.2.8 libpcre-8.39 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

 - Output of `nmap --iflist`

Starting Nmap 7.60 ( https://nmap.org ) at 2021-07-04 09:06 UTC
************************INTERFACES************************
DEV             (SHORT)           IP/MASK                      TYPE     UP   MTU   MAC
veth4965c04     (veth4965c04)     (none)/0                     ethernet up   1500  EA:C4:0B:31:37:94
veth4965c04     (veth4965c04)     fe80::e8c4:bff:fe31:3794/64  ethernet up   1500  EA:C4:0B:31:37:94
vethc3ae6c1     (vethc3ae6c1)     (none)/0                     ethernet up   1500  D2:B3:18:E4:E9:51
vethc3ae6c1     (vethc3ae6c1)     fe80::d0b3:18ff:fee4:e951/64 ethernet up   1500  D2:B3:18:E4:E9:51
cali3d0f42edbea (cali3d0f42edbea) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
cali3d0f42edbea (cali3d0f42edbea) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
docker_gwbridge (docker_gwbridge) 172.18.0.1/16                ethernet up   1500  02:42:0E:CD:C9:33
docker_gwbridge (docker_gwbridge) fe80::42:eff:fecd:c933/64    ethernet up   1500  02:42:0E:CD:C9:33
vetha0f332a     (vetha0f332a)     (none)/0                     ethernet up   1500  8A:B9:28:F4:64:6B
vetha0f332a     (vetha0f332a)     fe80::88b9:28ff:fef4:646b/64 ethernet up   1500  8A:B9:28:F4:64:6B
calie855833632f (calie855833632f) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
calie855833632f (calie855833632f) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
vethfe5720b     (vethfe5720b)     (none)/0                     ethernet up   1500  02:CA:CC:5F:83:6D
vethfe5720b     (vethfe5720b)     fe80::ca:ccff:fe5f:836d/64   ethernet up   1500  02:CA:CC:5F:83:6D
docker0         (docker0)         172.17.0.1/16                ethernet up   1500  02:42:01:2E:2F:99
docker0         (docker0)         fe80::42:1ff:fe2e:2f99/64    ethernet up   1500  02:42:01:2E:2F:99
vethefc9746     (vethefc9746)     (none)/0                     ethernet up   1500  32:76:E2:EF:61:AE
vethefc9746     (vethefc9746)     fe80::3076:e2ff:feef:61ae/64 ethernet up   1500  32:76:E2:EF:61:AE
cali1396305583c (cali1396305583c) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
cali1396305583c (cali1396305583c) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
veth9626c7e     (veth9626c7e)     (none)/0                     ethernet up   1500  0A:88:9C:81:78:9D
veth9626c7e     (veth9626c7e)     fe80::888:9cff:fe81:789d/64  ethernet up   1500  0A:88:9C:81:78:9D
lo              (lo)              127.0.0.1/8                  loopback up   65536
lo              (lo)              ::1/128                      loopback up   65536
vethafc8fc2     (vethafc8fc2)     (none)/0                     ethernet up   1500  9E:99:D1:E4:B2:DC
vethafc8fc2     (vethafc8fc2)     fe80::9c99:d1ff:fee4:b2dc/64 ethernet up   1500  9E:99:D1:E4:B2:DC
ens3            (ens3)            172.31.15.187/20             ethernet up   9001  0A:60:62:DF:3A:0B
ens3            (ens3)            fe80::860:62ff:fedf:3a0b/64  ethernet up   9001  0A:60:62:DF:3A:0B
calib2dd9241459 (calib2dd9241459) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
calib2dd9241459 (calib2dd9241459) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
veth467cfae     (veth467cfae)     (none)/0                     ethernet up   1500  F6:CB:4F:BC:42:84
veth467cfae     (veth467cfae)     fe80::f4cb:4fff:febc:4284/64 ethernet up   1500  F6:CB:4F:BC:42:84
br-d6380bce30b0 (br-d6380bce30b0) 172.19.0.1/16                ethernet up   1500  02:42:20:B2:09:29
br-d6380bce30b0 (br-d6380bce30b0) fe80::42:20ff:feb2:929/64    ethernet up   1500  02:42:20:B2:09:29
cali1e66a931053 (cali1e66a931053) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
cali1e66a931053 (cali1e66a931053) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
vethbd8bcde     (vethbd8bcde)     (none)/0                     ethernet up   1500  EA:CD:69:82:9A:4B
vethbd8bcde     (vethbd8bcde)     fe80::e8cd:69ff:fe82:9a4b/64 ethernet up   1500  EA:CD:69:82:9A:4B
veth7b012cf     (veth7b012cf)     (none)/0                     ethernet up   1500  FE:E8:C3:08:2C:CC
veth7b012cf     (veth7b012cf)     fe80::fce8:c3ff:fe08:2ccc/64 ethernet up   1500  FE:E8:C3:08:2C:CC
cali06d556950bb (cali06d556950bb) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
cali06d556950bb (cali06d556950bb) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
vetheda3a76     (vetheda3a76)     (none)/0                     ethernet up   1500  3A:79:E8:A3:14:D1
vetheda3a76     (vetheda3a76)     fe80::3879:e8ff:fea3:14d1/64 ethernet up   1500  3A:79:E8:A3:14:D1
veth2bca35c     (veth2bca35c)     (none)/0                     ethernet up   1500  AE:10:90:A2:B8:48
veth2bca35c     (veth2bca35c)     fe80::ac10:90ff:fea2:b848/64 ethernet up   1500  AE:10:90:A2:B8:48
veth69a6db6     (veth69a6db6)     (none)/0                     ethernet up   1500  66:0C:E5:F9:92:25
veth69a6db6     (veth69a6db6)     fe80::640c:e5ff:fef9:9225/64 ethernet up   1500  66:0C:E5:F9:92:25
vxlan.calico    (vxlan.calico)    192.168.217.64/32            ethernet up   1450  66:82:A7:07:A9:1B
vxlan.calico    (vxlan.calico)    fe80::6482:a7ff:fe07:a91b/64 ethernet up   1450  66:82:A7:07:A9:1B
caliadec7b0f933 (caliadec7b0f933) (none)/0                     ethernet up   1450  EE:EE:EE:EE:EE:EE
caliadec7b0f933 (caliadec7b0f933) fe80::ecee:eeff:feee:eeee/64 ethernet up   1450  EE:EE:EE:EE:EE:EE
vethe101fb4     (vethe101fb4)     (none)/0                     ethernet up   1500  16:FA:12:A6:62:65
vethe101fb4     (vethe101fb4)     fe80::14fa:12ff:fea6:6265/64 ethernet up   1500  16:FA:12:A6:62:65
vethcd0492c     (vethcd0492c)     (none)/0                     ethernet up   1500  96:03:7B:10:B1:32
vethcd0492c     (vethcd0492c)     fe80::9403:7bff:fe10:b132/64 ethernet up   1500  96:03:7B:10:B1:32
kube-ipvs0      (kube-ipvs0)      10.96.0.1/32                 other    down 1500
kube-ipvs0      (kube-ipvs0)      10.96.0.10/32                other    down 1500
kube-ipvs0      (kube-ipvs0)      10.96.4.160/32               other    down 1500
kube-ipvs0      (kube-ipvs0)      10.96.145.192/32             other    down 1500
kube-ipvs0      (kube-ipvs0)      10.96.168.127/32             other    down 1500
veth5df0976     (veth5df0976)     (none)/0                     ethernet up   1500  F2:99:EA:ED:D1:CB
veth5df0976     (veth5df0976)     fe80::f099:eaff:feed:d1cb/64 ethernet up   1500  F2:99:EA:ED:D1:CB

**************************ROUTES**************************
DST/MASK                      DEV             METRIC GATEWAY
192.168.217.65/32             ens3            0
192.168.217.66/32             ens3            0
192.168.217.67/32             ens3            0
192.168.217.68/32             ens3            0
192.168.217.69/32             ens3            0
192.168.217.70/32             ens3            0
192.168.217.71/32             ens3            0
172.31.0.1/32                 ens3            100
172.31.0.0/20                 ens3            0
172.17.0.0/16                 docker0         0
172.18.0.0/16                 docker_gwbridge 0
172.19.0.0/16                 br-d6380bce30b0 0
0.0.0.0/0                     ens3            100    172.31.0.1
::1/128                       lo              0
fe80::42:1ff:fe2e:2f99/128    docker0         0
fe80::42:eff:fecd:c933/128    docker_gwbridge 0
fe80::42:20ff:feb2:929/128    br-d6380bce30b0 0
fe80::ca:ccff:fe5f:836d/128   vethfe5720b     0
fe80::860:62ff:fedf:3a0b/128  ens3            0
fe80::888:9cff:fe81:789d/128  veth9626c7e     0
fe80::14fa:12ff:fea6:6265/128 vethe101fb4     0
fe80::3076:e2ff:feef:61ae/128 vethefc9746     0
fe80::3879:e8ff:fea3:14d1/128 vetheda3a76     0
fe80::640c:e5ff:fef9:9225/128 veth69a6db6     0
fe80::6482:a7ff:fe07:a91b/128 vxlan.calico    0
fe80::88b9:28ff:fef4:646b/128 vetha0f332a     0
fe80::9403:7bff:fe10:b132/128 vethcd0492c     0
fe80::9c99:d1ff:fee4:b2dc/128 vethafc8fc2     0
fe80::ac10:90ff:fea2:b848/128 veth2bca35c     0
fe80::d0b3:18ff:fee4:e951/128 vethc3ae6c1     0
fe80::e8c4:bff:fe31:3794/128  veth4965c04     0
fe80::e8cd:69ff:fe82:9a4b/128 vethbd8bcde     0
fe80::ecee:eeff:feee:eeee/128 caliadec7b0f933 0
fe80::ecee:eeff:feee:eeee/128 cali06d556950bb 0
fe80::ecee:eeff:feee:eeee/128 calie855833632f 0
fe80::ecee:eeff:feee:eeee/128 calib2dd9241459 0
fe80::ecee:eeff:feee:eeee/128 cali1e66a931053 0
fe80::ecee:eeff:feee:eeee/128 cali3d0f42edbea 0
fe80::ecee:eeff:feee:eeee/128 cali1396305583c 0
fe80::f099:eaff:feed:d1cb/128 veth5df0976     0
fe80::f4cb:4fff:febc:4284/128 veth467cfae     0
fe80::fce8:c3ff:fe08:2ccc/128 veth7b012cf     0
::1/128                       lo              256
fe80::/64                     ens3            256
fe80::/64                     docker0         256
fe80::/64                     docker_gwbridge 256
fe80::/64                     veth69a6db6     256
fe80::/64                     vetha0f332a     256
fe80::/64                     br-d6380bce30b0 256
fe80::/64                     vethefc9746     256
fe80::/64                     veth5df0976     256
fe80::/64                     vethc3ae6c1     256
fe80::/64                     vethe101fb4     256
fe80::/64                     vethcd0492c     256
fe80::/64                     veth2bca35c     256
fe80::/64                     veth9626c7e     256
fe80::/64                     veth4965c04     256
fe80::/64                     vethfe5720b     256
fe80::/64                     vethbd8bcde     256
fe80::/64                     vxlan.calico    256
fe80::/64                     caliadec7b0f933 256
fe80::/64                     cali06d556950bb 256
fe80::/64                     cali1e66a931053 256
fe80::/64                     calib2dd9241459 256
fe80::/64                     calie855833632f 256
fe80::/64                     veth467cfae     256
fe80::/64                     veth7b012cf     256
fe80::/64                     cali3d0f42edbea 256
fe80::/64                     vetheda3a76     256
fe80::/64                     vethafc8fc2     256
fe80::/64                     cali1396305583c 256
ff00::/8                      ens3            256
ff00::/8                      docker0         256
ff00::/8                      docker_gwbridge 256
ff00::/8                      veth69a6db6     256
ff00::/8                      vetha0f332a     256
ff00::/8                      br-d6380bce30b0 256
ff00::/8                      vethefc9746     256
ff00::/8                      veth5df0976     256
ff00::/8                      vethc3ae6c1     256
ff00::/8                      vethe101fb4     256
ff00::/8                      vethcd0492c     256
ff00::/8                      veth2bca35c     256
ff00::/8                      veth9626c7e     256
ff00::/8                      veth4965c04     256
ff00::/8                      vethfe5720b     256
ff00::/8                      vethbd8bcde     256
ff00::/8                      vxlan.calico    256
ff00::/8                      caliadec7b0f933 256
ff00::/8                      cali06d556950bb 256
ff00::/8                      cali1e66a931053 256
ff00::/8                      calib2dd9241459 256
ff00::/8                      calie855833632f 256
ff00::/8                      veth467cfae     256
ff00::/8                      veth7b012cf     256
ff00::/8                      cali3d0f42edbea 256
ff00::/8                      vetheda3a76     256
ff00::/8                      vethafc8fc2     256
ff00::/8                      cali1396305583c 256

**Additional context**

1. Issue is currently not reproducible at will but only encountered in the field and has only been seen with kube-apiserver being the service implicated. Not sure if that is by chance or if there is some relevance to it. 
2. Invariably every time this happens; I notice that the enumerated list differs based on whether I use localhost or 127.0.0.1 as the argument for the connect parameter. Using `127.0.0.1` shows more ciphers in the enumerated list and each of these "extra" ciphers is a false positive. I verified that the same serving certificate is used irrespective of whether localhost or 127.0.0.1 is used for the connection - this was to rule out that the serving certificate may be different for localhost and 127.0.0.1. 
3. Latest nmap: I tried `nmap 7.91` as well and failed to notice any difference in this behavior.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. There are a few different things that are probably going on here:

1. Your `openssl` command does not support the triple-DES cipher. You can test this with `openssl ciphers 3DES`, which will show a list of matching ciphers if your version of OpenSSL *does* include these.
2. `ssl-enum-ciphers` uses the targetname (the name provided to Nmap for the target, e.g. "localhost") for the Server Name Indication (SNI) extension. TLS services such as Apache with mod_ssl can have different configurations on the same IP and port using the SNI name just like HTTP uses the Host header for virtual hosts. This is the reason for the difference between Nmap scans.

You can always verify what Nmap is doing by adding the `--script-trace` option to see a hex dump of all traffic. You could edit `tls.lua` to reduce the `CIPHERS` table down to only the ones you are interested in, if you really feel you want to debug it.

If you check into these possibilities and still feel that the script is incorrect, feel free to reopen this issue.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
