### ISSUE TITLE
How to make the linux Ncat command not attempt to read from stdin?

### ISSUE THREAD

**Issue by Doronbs11** [nmap/nmap#2333]
The old nc command used to have a "-d" flag to not attempt to read from stdin. The new Ncat does not. Is there a workaround that has the same effect on the Ncat command?

**Comment by nnposter** [comment]
I am not familiar with how exactly `-d` behaved in the legacy netcat, but is perhaps `--recv-only` what you need?

**Comment by Doronbs11** [comment]
> I am not familiar with how exactly `-d` behaved in the legacy netcat, but is perhaps `--recv-only` what you need?

Can you Expand on what that means? I read the man page and from what I understand it just means the instance will not send anything but only receive. Why will it give the same effect as not attempting to read from stdin?

**Comment by nnposter** [comment]
What Ncat reads from stdin is sent to the other endpoint. With `--recv-only`, nothing is sent so there is no need for reading from stdin.

**Comment by dmiller-nmap** [comment]
@nnposter is correct: the equivalent command for Ncat is `ncat --recv-only`. The `-d` option is only present on OpenBSD's netcat implementation, not in the traditional/Hobbit utility. Implications of these options on EOF handling are documented here: https://secwiki.org/w/Ncat/EOF_behavior

**Comment by dmiller-nmap** [comment]
I just created this additional resource for navigating compatibility with the most popular netcat implementations: https://secwiki.org/w/Ncat/Compatibility

Note that for full compatibility with OpenBSD's `-d` option, you must also give the `--no-shutdown` option to Ncat.

**Comment by Doronbs11** [comment]
> I just created this additional resource for navigating compatibility with the most popular netcat implementations: https://secwiki.org/w/Ncat/Compatibility
> 
> Note that for full compatibility with OpenBSD's `-d` option, you must also give the `--no-shutdown` option to Ncat.

I am using version 7.50 on my VM, so no --no-shutdown. Is there an alternative for the --no-shutdown flag? maybe -k on the transmit side?

**Comment by goarblt** [comment]
hello
https://www.evil.com/
