### ISSUE TITLE
nmap -p- 192.168.1.3 doesn't work until -p- option is moved, then it works normally! 

### ISSUE THREAD

**Issue by Martyn575** [nmap/nmap#2335]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**

"nmap -p- 192.168.1.3" doesn't work correctly first time (or any number of times), it reports an error and only scans 1000 ports, until the user runs: 

nmap 192.168.1.3 -p-

Once the user does this the command:

nmap -p- 192.168.1.3 

Now works correctly with no error, and scans all 65535 ports! 

**To Reproduce**

```
root@Atlas:/home/xxxx# nmap -p- 192.168.1.3
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-12 21:14 BST
Failed to resolve "-p-".
Nmap scan report for 192.168.1.3
Host is up (0.000010s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 1.67 seconds
```

Note that we see the error: "Failed to resolve "-p-"." 
Note also that we are only scanning 1000 ports. 

I run it a second time with the same options: 

```
root@Atlas:/home/xxxx# nmap –p– 192.168.1.3
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-12 21:14 BST
Failed to resolve "–p–".
Nmap scan report for 192.168.1.3
Host is up (0.000010s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 1.67 seconds
```

Same behaviour. I now change the order of the command line parameters, moving "-p-" to the end: 

```
root@Atlas:/home/xxxx# nmap 192.168.1.3 -p-
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-12 21:14 BST
Nmap scan report for 192.168.1.3
Host is up (0.0000050s latency).
Not shown: 65534 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 6.12 seconds
```

I get the expected behaviour, 65535 ports scanned. 

Now, I change the command line parameters back to the original:

```
root@Atlas:/home/xxxx# nmap -p- 192.168.1.3 
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-12 23:19 BST
Nmap scan report for 192.168.1.3
Host is up (0.000010s latency).
Not shown: 65534 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 6.10 seconds
```

The behaviour is now correct and different from the first and second time i ran nmap with the "-p-" options, and it now works correctly. Somehow moving the "-p-" to the end of the command line parameters has changed the behaviour of nmap - at least for parameter parsing. 

**Expected behavior**

nmap -p- 192.168.1.3 

should work the first times without error, and it should work in the same way as if the user had run nmap 192.168.1.3 -p- first!

**Version info (please complete the following information):**

 - OS: [e.g. Linux 4.15, Windows 10 1909]

```
root@Atlas:/home/xxxx# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

 - Output of `nmap --version`:

```
root@Atlas:/home/xxxx# nmap --version
Nmap version 7.70 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d libssh2-1.8.0 libz-1.2.11 libpcre-8.39 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

 - Output of `nmap --iflist`

```
root@Atlas:/home/xxxx# nmap --iflist
Starting Nmap 7.70 ( https://nmap.org ) at 2021-07-12 23:53 BST
************************INTERFACES************************
DEV    (SHORT)  IP/MASK                      TYPE     UP MTU   MAC
enp7s0 (enp7s0) 192.168.1.3/24               ethernet up 1500  60:45:CB:9B:47:26
enp7s0 (enp7s0) fe80::6245:cbff:fe9b:4726/64 ethernet up 1500  60:45:CB:9B:47:26
lo     (lo)     127.0.0.1/8                  loopback up 65536
lo     (lo)     ::1/128                      loopback up 65536

**************************ROUTES**************************
DST/MASK                      DEV    METRIC GATEWAY
192.168.1.0/24                enp7s0 0
0.0.0.0/0                     enp7s0 0      192.168.1.1
::1/128                       lo     0
fe80::6245:cbff:fe9b:4726/128 enp7s0 0
::1/128                       lo     256
fe80::/64                     enp7s0 256
ff00::/8                      enp7s0 256
::/0                          enp7s0 1024   fe80::f268:65ff:fe01:cdd7
```

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by Martyn575** [comment]
Nope, i am sorry, actually this is not a bug - it's because when pasting '-p-' some systems change it to the other '-'... which isn't recognised by nmap.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
