### ISSUE TITLE
Ncat 7.91 Stable crashes connecting to a socket (-U)

### ISSUE THREAD

**Issue by katzurki** [nmap/nmap#2336]
**Describe the bug**
The latest ncat version 7.91 crashes when trying to connect to a socket.

**To Reproduce**
Using the binary from https://nmap.org/dist/ncat-7.91-1.x86_64.rpm, execute:
ncat -U /run/docker.sock

The output is: Segmentation fault

**Expected behavior**
Connects and awaits HTTP headers.

**Version info (please complete the following information):**
 - OS: Linux 5.10.0 amd64
 - Output of `ncat --version`: Ncat: Version 7.91 ( https://nmap.org/ncat )

**Additional context**
This problem is only present in Ncat 7.91, and a slightly earlier ncat, say version 7.80, works flawlessly.

**Comment by nnposter** [comment]
This is likely a known bug, #2154, already remediated last October in r38121 (f6b40614e4a8131394792d590965f8af3c635323). If you can, please recompile ncat from source and try again.

I am tentatively closing the issue but please reopen if you can reproduce the segfault in recompiled ncat.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
