### ISSUE TITLE
ncap-oem.exe is missing in 7.9x Windows installers

### ISSUE THREAD

**Issue by minonl** [nmap/nmap#2346]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

I have been trying to install nmap with scoop on Windows, which utilize a ncap-oem.exe to (silent) install from command line.

There are some GitHub issues referring to a missing `npcap.oem.exe`
https://github.com/lukesampson/scoop-extras/issues/4862
https://github.com/ScoopInstaller/Main/issues/1465

I noticed the file name is still defined in Makefile here:
https://github.com/nmap/nmap/blob/e93109ef886a4da8b6e0686718bad829edd41fff/mswin32/Makefile

I wonder if it is removed by purpose.

**Expected behavior**
Describe what you would like to happen instead.

ncap-oem.exe exists in installers to make silent install possible

**Comment by fyodor** [comment]
Yes, the silent install feature was removed from the Windows installer last year as documented in the [Changelog](https://nmap.org/changelog) (search for "Removed the silent-install command-line option (/S) from the Windows installer").  It was widely abused by companies who were redistributing Nmap as part of their products in violation of it's license.  Those companies should license [Nmap OEM](https://nmap.org/changelog) instead, which does include a silent Windows installer.  For normal end users we recommend just downloading Nmap and installing it manually (only takes a few clicks).  We are also looking at ways for end users to ease large deployments and such where manual install is more difficult.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
