### ISSUE TITLE
Zenmap closes immediately upon entering password nmap 7.0

### ISSUE THREAD

**Issue by mozzer74** [nmap/nmap#235]
Just installed 7.0 in Yosemite,  no previous versions of nmap or zenmap were on this system.  

I launch zenmap, put in my password, and it immediately closes.

Thoughts?

**Comment by mozzer74** [comment]
I forgot, here's the command output:

Traceback (most recent call last):
  File "./zenmap_wrapper.py", line 173, in <module>
    substitute_key_file(in_file_name, out_file_name, REPLACEMENTS)
  File "./zenmap_wrapper.py", line 63, in substitute_key_file
    in_file = open(in_file_name, "r")
IOError: [Errno 2] No such file or directory: '/Applications/Zenmap.app/Contents/Resources/etc/pango/pangorc.in'

**Comment by yshh** [comment]
I have encountered this issue on OSX 10.10.5.

Log output in /var/log/system.log:
```
Nov 20 12:01:50 ***s-MacBook-Pro.local authexec[38604]: executing /Applications/Zenmap.app/Contents/MacOS/zenmap_wrapper.py
Nov 20 12:01:50 ***s-MacBook-Pro com.apple.xpc.launchd[1] (org.insecure.Zenmap.143736[38592]): FairPlay decryption failed on binary.
```

**Comment by dmiller-nmap** [comment]
http://www.gtk.org/download/macos.php saving this here.

**Comment by functio** [comment]
Quick hack: Just create the missing file:

sudo mkdir mkdir -p /Applications/Zenmap.app/Contents/Resources/etc/pango && touch /Applications/Zenmap.app/Contents/Resources/etc/pango/pangorc.in

**Comment by dmiller-nmap** [comment]
@functio Thanks for this workaround!

**Comment by stonky** [comment]
@functio ditto workaround!

**Comment by levelksk** [comment]
@functio thank you very much！it work！

**Comment by dmiller-nmap** [comment]
I believe this bug should be resolved with the 7.01 release. Please try the new .dmg installer at https://nmap.org/download.html#macosx and let us know if it solves this issue for you.

**Comment by levelksk** [comment]
@dmiller-nmap 7.01 is good! i can use it in OSX 10.11.2

**Comment by stonky** [comment]
@dmiller-nmap 

*I believe this bug should be resolved with the 7.01 release.*

Yep; sorted thank you.

**Comment by dmiller-nmap** [comment]
Thanks all! Keep scanning and reporting bugs.

**Comment by vinnytroia** [comment]
I hate to re-has old issues, but this is happening on a fresh install of 10.11.3 with NMAP 7.0.1 installer. Anything i should be looking for? The workaround listed above also does not work.

**Comment by vinnytroia** [comment]
FYI -- im getting a different command line error 
./zenmap.bin: line 67: ./Contents/MacOS/python: No such file or directory

But the file is there...

**Comment by cybernorris** [comment]
Ditto on failing to closing after entering password.

NMap 7.01
OSX 10.11.4 and 10.10.5

```
May  6 20:49:23 cardenphoto.local authexec[50772]: executing /Applications/Zenmap.app/Contents/MacOS/zenmap.bin
May  6 20:49:35 cardenphoto com.apple.xpc.launchd[1] (org.insecure.Zenmap.101988[50764]): FairPlay decryption failed on binary.
```

**Comment by dmiller-nmap** [comment]
@vinnytroia Please upgrade to Nmap 7.12, which should solve this issue. As @cybernorris points out, you may need to delete the `Zenmap.app` directory before proceeding. Also, you may encounter a crash in Zenmap that has [a known simple workaround](http://seclists.org/nmap-dev/2016/q2/18).

**Comment by TheMaskedMan101100** [comment]
All you have to do to open Zenmap if this happens is to open terminal and put this in `open -a Zenmap` type in your password and it should open!

**Comment by beck1888** [comment]
> All you have to do to open Zenmap if this happens is to open terminal and put this in `open -a Zenmap` type in your password and it should open!

`open -a Zenmap` this fixed it, thank you!
