### ISSUE TITLE
[7.92] source code signature missing

### ISSUE THREAD

**Issue by tuxmaster5000** [nmap/nmap#2351]
For the last version the asc file with the source code signature is missing.

**Comment by fyodor** [comment]
Hm, I see them here for both the .tar.bz2 and .tgz source code tarballs: https://nmap.org/dist/sigs/?C=M;O=D

I'm closing this, but please comment with more details if I'm missing something.

**Comment by tuxmaster5000** [comment]
Sorry my mistake, I have forgotten the sigs sub dir :(

**Comment by goarblt** [comment]
hello
https://www.evil.com/
