### ISSUE TITLE
rdp-vuln-ms12-020 throws (initial position out of string)

### ISSUE THREAD

**Issue by umar98** [nmap/nmap#2355]
NSE: rdp-vuln-ms12-020 against threw an error!
C:\Program Files (x86)\Nmap/scripts\rdp-vuln-ms12-020.nse:195: bad argument #3 to 'unpack' (initial position out of string)
stack traceback:
        [C]: in function 'string.unpack'
        C:\Program Files (x86)\Nmap/scripts\rdp-vuln-ms12-020.nse:195: in function <C:\Program Files (x86)\Nmap/scripts\rdp-vuln-ms12-020.nse:74>
        (...tail calls...)

**Comment by garthoid** [comment]
me too

**Comment by dmiller-nmap** [comment]
Most likely this is a not-vulnerable service. I have added some exception handling to the script, as well as changed the socket receive calls to try to receive enough bytes for the unpack operations. Fix incoming.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
