### ISSUE TITLE
rtsp-urls.txt contains password information

### ISSUE THREAD

**Issue by qingzi310** [nmap/nmap#2357]
Hello, 

nmap/nselib/data/rtsp-urls.txt contains `/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream` as the last line, and it contains password information that cannot pass our policy check. Is that ok we remove this line ourselves? 

And do you consider remove it in the official updates? 

Thanks in advance.

**Comment by nnposter** [comment]
Yes, you can edit file `nselib/data/rtsp-urls.txt` as you see fit (for your internal use).

Alternatively, you can force script `rtsp-url-brute`, which is the only script using the file, to use a different URL list by specifying script argument `rtsp-url-brute.urlfile`.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
