### ISSUE TITLE
stdout for some reason went to stderr

### ISSUE THREAD

**Issue by Areso** [nmap/nmap#2361]
**Describe the bug**
nc always throw output to stderr

**To Reproduce**
Steps to reproduce the behavior, including command-line options.
```
$ nc -z -v -w 1 ya.ru 443 > log.log 2> error.log  
$ cat log.log  
""
$ cat error.log   
Connection to ya.ru 443 port [tcp/https] succeeded!
  
$ nc -z -v -w 1 ya.ru 883 > log.log 2> error.log  
$ cat log.log  
""
$ cat error.log   
nc: connect to ya.ru port 883 (tcp) timed out: Operation now in progress
nc: connect to ya.ru port 883 (tcp) failed: Network is unreachable
```
**Expected behavior**
```
$ nc -z -v -w 1 ya.ru 443 > log.log 2> error.log  
$ cat log.log  
Connection to ya.ru 443 port [tcp/https] succeeded!
$ cat error.log   
""  
$ nc -z -v -w 1 ya.ru 883 > log.log 2> error.log  
$ cat log.log  
""
$ cat error.log   
nc: connect to ya.ru port 883 (tcp) timed out: Operation now in progress
nc: connect to ya.ru port 883 (tcp) failed: Network is unreachable
```

**Version info (please complete the following information):**
 - OS: RHEL 8.4
 - Output of `ncat --version`: 7.70

**Additional context**
Successfull connect shouldn't produce STDERR.

**Comment by nnposter** [comment]
This is by design, namely to separate session data (i.e., data exchanged with the target) from locally generated messages, such as errors or verbose information. In other words, writing to `stderr` is used as a logging facility.
```
ncat example.org 80 >http-response.data 2>http-response.log
```
Whether the transaction worked is determined by the exit code, not by absence of `stderr` output.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
