### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [nmap/nmap#2368]
**Describe the current behavior**
Looks like in git repo there is no at all git version tags.

**Expected behavior**
Each version should be tagged. With lat version tag for exwmple it would be easier see and asses what has been changed from lat release.

**Comment by fyodor** [comment]
Thanks for the suggestion.  This is actually a duplicate of #2311 .

**Comment by kloczek** [comment]
And .. still no tags :(
I would suggest to move away from svn and embrace power of git.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
