### ISSUE TITLE
Nmap aggressive scan is flooding Windows Server 2012 with error logs event with EvenID 36888 and 36874

### ISSUE THREAD

**Issue by Grizzly2000** [nmap/nmap#2372]
**Describe the bug**
Nmap aggressive scan is flooding Windows 2012 Server with error logs event with EvenID 36888 and 36874. Scan is running from Debian.

**To Reproduce**
Run nmap scan on Windows 2012 Server from Debian with the following command :
sudo nmap -A 172.17.2.52 --version-trace -vvvvvvvvvvvvv

Windows version :
Microsoft Windows Server 2012 R2 Standard
6.3.9600 N/A Build 9600

Windows Event Log information : 
Level : Error
Source : Schannel
Event ID : 36888/36874

**Expected behavior**
Which NSE scripts are responsible of this behavior ?
Is it possible to stop log flooding in Windows event log by providing a specific nmap parameter? 

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 `Linux laptop10 5.10.0-0.bpo.8-amd64 #1 SMP Debian 5.10.46-4~bpo10+1 (2021-08-07) x86_64 GNU/Linux`

 - Output of `nmap --version`:
 `Nmap version 7.70 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d libssh2-1.8.0 libz-1.2.11 libpcre-8.39 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select`

 - Output of `nmap --iflist` : 

************************INTERFACES************************
DEV    (SHORT)  IP/MASK        TYPE        UP MTU   MAC
lo     (lo)     127.0.0.1/8    loopback    up 65536
wlp2s0 (wlp2s0) 172.17.0.69/24 ethernet    up 1500  78:2B:46:7C:A2:A9
tun0   (tun0)   172.16.1.22/32 point2point up 1500

**************************ROUTES**************************
DST/MASK          DEV    METRIC GATEWAY
172.16.1.1/32     tun0   50     172.16.1.21
172.16.1.21/32    tun0   50
91.121.229.225/32 wlp2s0 600    172.17.0.200
172.17.0.200/32   wlp2s0 600
172.17.0.0/24     wlp2s0 600
172.17.0.0/16     wlp2s0 600    172.17.0.200
169.254.0.0/16    wlp2s0 1000
0.0.0.0/0         tun0   50     172.16.1.21
0.0.0.0/0         wlp2s0 600    172.17.0.200

**Additional context**
On Windows2012Server, set 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\EventLogging' to '0' is not a valid solution. In fact, other 'Schannel' Event Log error should not be hidden and interesting to monitor such as remote access.

Screenshots of Windows Event Log : 

![nmap_windows_log1](https://user-images.githubusercontent.com/14803338/134375902-2174b6ca-036d-4d1f-85f4-3fcce78006f7.png)

![nmap_windows_log2](https://user-images.githubusercontent.com/14803338/134375936-904c90f5-bdd1-4c82-8bed-b48962fbda92.png)

**Comment by nnposter** [comment]
Script `ssl-enum-ciphers` is likely the culprit here.
If you are concerned about logged events on the scanned target then you should be more selective in what scripts are used (option `--script`), as opposed to launching the entire default set (by using option `-A`)

**Comment by goarblt** [comment]
hello
https://www.evil.com/
