### ISSUE TITLE
Nmap is not sending ICMP timestamp requests when -PP flag is set

### ISSUE THREAD

**Issue by ml16685** [nmap/nmap#2377]
**Describe the bug**
I'd like nmap to send ICMP timestamp requests to the host. To achieve this I use the command:

`nmap -PP "ip addr"`

But among requests generated by nmap there are no ICMP requests, only TCP SYN packets.

The host is actually in my subnet. If I set "ip addr" to some non existing host from other subnet I observe ICMP timestamp requests.

So seems nmap sends ICMP timestamp requests only under special conditions.

What are these conditions? And is it possible to force nmap to send ICMP timestamp requests to any host, maybe via some additional flag?

As I know, there are other utils which can be used, like nping, but I'd like to first clarify the option with nmap.

Thank you.

**To Reproduce**
Run the following command:

`nmap -PP "ip addr"`

**Expected behavior**
nmap is expected to forcibly send ICMP timestamp requests for any host

**Version info (please complete the following information):**
 - OS: Ubuntu 16.04
 - Output of `nmap --version`:

> Nmap version 7.01 ( https://nmap.org )
> Platform: x86_64-pc-linux-gnu
> Compiled with: liblua-5.2.4 openssl-1.0.2g libpcre-8.38 libpcap-1.7.4 nmap-libdnet-1.12 ipv6
> Compiled without:
> Available nsock engines: epoll poll select

 - Output of `nmap --iflist`:

> Starting Nmap 7.01 ( https://nmap.org ) at 2021-10-09 14:58 MSK
> ************************INTERFACES************************
> DEV    (SHORT)  IP/MASK                      TYPE     UP MTU   MAC
> lo     (lo)     127.0.0.1/8                  loopback up 65536
> lo     (lo)     ::1/128                      loopback up 65536
> enp0s3 (enp0s3) 192.168.2.104/24             ethernet up 1500  08:00:27:FF:A8:1B
> enp0s3 (enp0s3) fe80::4f79:6531:1f05:8f1e/64 ethernet up 1500  08:00:27:FF:A8:1B
> 
> **************************ROUTES**************************
> DST/MASK                      DEV    METRIC GATEWAY
> 192.168.2.0/24                enp0s3 100
> 169.254.0.0/16                enp0s3 1000
> 0.0.0.0/0                     enp0s3 100    192.168.2.1
> ::1/128                       lo     0
> fe80::4f79:6531:1f05:8f1e/128 enp0s3 0
> fe80::/64                     enp0s3 256
> ff00::/8                      enp0s3 256

**Comment by goarblt** [comment]
hello
https://www.evil.com/
