### ISSUE TITLE
How to hide this message: "unrecognized despite returning data. If you know the service/version"

### ISSUE THREAD

**Issue by gMan1990** [nmap/nmap#2380]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

**Expected behavior**
Describe what you would like to happen instead.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by AuroraHaaash** [comment]
> **NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**
> 
> **NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**
> 
> **Describe the current behavior** A clear and concise description of what the bug or current behavior is.
> 
> **Expected behavior** Describe what you would like to happen instead.

Hi, I'm facing the same problem. Have you solved ?

**Comment by amahlaka** [comment]
I would also like to know if this is possible, as it pollutes the output sometimes

**Comment by dmiller-nmap** [comment]
Thanks for your input. This is a core feature of Nmap: if a service is not recognized, the output contains a fingerprint to recognize the service in the future. If you need to filter Nmap's output, you can use a text editor to post-process the results.
