### ISSUE TITLE
nmap license URL in payloads file/disclaimer is broken

### ISSUE THREAD

**Issue by 003random** [nmap/nmap#2389]
**Describe the current behavior**
line 13 on https://github.com/nmap/nmap/blob/master/nmap-payloads contains a link to the license but gives a 404 instead.

**Expected behavior**
expected that the reference on line 13 in https://github.com/nmap/nmap/blob/master/nmap-payloads would lead me to the license page.

**Comment by 003random** [comment]
https://github.com/nmap/nmap/search?q=https%3A%2F%2Fnmap.org%2Fdata%2FLICENSE for the other places where this URL is referenced

**Comment by fyodor** [comment]
Thanks @003random .  I've fixed all of these in SVN and the changes should be reflected on Github shortly.
