### ISSUE TITLE
No open ports found when the scan size is large

### ISSUE THREAD

**Issue by qingzi310** [nmap/nmap#2396]
**Describe the bug**
When scanning 32768 IPs on 65535/4 ports on each scan, we could see the stdout that has a lot of open ports but there is no open ports found in the result xml file.

We used to run 32768/4 on 65535/16 ports on each scan(1/16 in terms of the scan size) and that worked fine. We would like to know if there is limitation on the scan size or this is a bug.

**Version info (please complete the following information):**
Version 7.91

**Comment by qingzi310** [comment]
Will re-open with more data.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
