### ISSUE TITLE
Fix sectools.org http redirects

### ISSUE THREAD

**Issue by nmapster** [nmap/nmap#24]
We have a .htaccess file on sectools but it the redirects listed in there don't seem to be working.  I think it might be we just need to make sure .htaccess reading or redirecting is enabled in the web server config for this site or maybe it is the permissions of the .htaccess file itself

**Comment by dmiller-nmap** [comment]
The Sectools application handles these urls, so .htaccess isn't consulted. Made appropriate changes in the application to handle the specific redirections properly.
