### ISSUE TITLE
Deprecated CPEs for Microsoft IIS

### ISSUE THREAD

**Issue by oh2fih** [nmap/nmap#2401]
Nmap detects Microsoft IIS as `cpe:/a:microsoft:internet_information_server`.

This has been deprecated and replaced with `cpe:/a:microsoft:internet_information_services` with the correct name of the product.

Sources include:
- IIS - https://nvd.nist.gov/products/cpe/detail/834795
- IIS 1.0 https://nvd.nist.gov/products/cpe/detail/834796
- ...
- IIS 7.0 https://nvd.nist.gov/products/cpe/detail/834802
- IIS 7.5 https://nvd.nist.gov/products/cpe/detail/126703
- IIS 8.0 https://nvd.nist.gov/products/cpe/detail/834804
- IIS 8.5 https://nvd.nist.gov/products/cpe/detail/393414
- IIS 10.0 https://nvd.nist.gov/products/cpe/detail/367120

**Comment by goarblt** [comment]
hello
https://www.evil.com/
