### ISSUE TITLE
Wrong hostname reported

### ISSUE THREAD

**Issue by Ricky-Tigg** [nmap/nmap#2403]
**nmap:** 7.91; **NetworkManager:** 1.32.12; **OS:** Fedora; ’`hostname-mode=none`’ added into section `[main]` of /etc/NetworkManager/NetworkManager.conf.

```
[yk@fedora ~]$ hostnamectl status | sed -n '1p;3p'
   Static hostname: n/a
Transient hostname: fedora
```
_Description_: I had previously addressed the cause that had allowed _NetworkManager_ to interfere with the host-name, while that last had been set – by using `hostnamectl --transient set-hostname <name>`, for instance by applying back the old transient host-name. nmap though faulty reports the **old** host-name, then obsolete, as the current one.

```
[root@fedora yk]# nmap -sS -p 1-1024 -T 5 `ifconfig wlp2s0 | sed -n 2p | awk '{print $2}'`
Starting Nmap 7.91 ( https://nmap.org ) at 2021-11-27 16:09 EET
Nmap scan report for DESKTOP-JAQA2JI (192.168.100.152)
Host is up (0.000022s latency).
All 1024 scanned ports on DESKTOP-JAQA2JI (192.168.100.152) are closed
```

**Comment by dmiller-nmap** [comment]
Nmap gets the hostname for an IP address by sending DNS PTR requests to the nameservers in `/etc/resolv.conf`. If it can't find any nameservers, or if the response is truncated or a CNAME record, it uses `getnameinfo()` to ask the OS what name should be used. That is usually done by checking `/etc/hosts` first, then by querying any name services configured on the system (DNS, NIS+, LDAP, AD, etc.).

All this to say, Nmap is just reporting what these nameservers have told it. The name is most likely cached somewhere like your DHCP server (home routers often act as a caching DNS resolver and populate local records with info from DHCP reservations).

**Comment by goarblt** [comment]
hello
https://www.evil.com/
