### ISSUE TITLE
can ncat close the connection after operation is done

### ISSUE THREAD

**Issue by xkarosx** [nmap/nmap#2404]
hi
im trying to connect to a server using ncat
```
ncat localhost 2399
```
for example localhost:2399
and when im done i want ncat to disconnect
if possible to disconnect after X seconds
is that possible?
i've tried the `-w` switch but it doesn't work if i put `-w 1` it would wait forever
can anyone help?
thanks!

**Comment by nnposter** [comment]
Take a look at `--idle-timeout`
```
$ ncat -v -i5 localhost 9099
Ncat: Version 7.92SVN ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:9099.
aaabbbccc
dddeeefff
Ncat: Idle timeout expired (5000 ms).
$ 
```

**Comment by xkarosx** [comment]
Idle timeout is how long its connected?
I mean the server does sent data packets
So it doesnt timeout becuase the data packets are getting recieved

**Comment by xkarosx** [comment]
Or can we use `--send-only` ?
So it does only send the data and doesnt recieve 
So it timesout?
Is that possible?

**Comment by nnposter** [comment]
> and when im done i want ncat to disconnect

Please clearly describe how exactly you are interacting with the server and at what exact point of this interaction you want to disconnect.

**Comment by xkarosx** [comment]
So after im done sending a file from me(the client)
To the server. i want ncat to disconnect

**Comment by nnposter** [comment]
If you do not want to see any data back from the server at all then option `--send-only` will do the trick. Just be aware that some data might be sent back by the server, just not read by Ncat, before the connection gets truly aborted.

**Comment by xkarosx** [comment]
So `--send-only` and `--idle-timeout`
Will do the trick?
```
Ncat localhost 2399 --idle-timeout 3 --send-only
```
 so this well be the full command for connecting to a server then disconnect after 3s?

**Comment by nnposter** [comment]
If you do not care for any of the server data then there is no need for `--idle-timeout`

**Comment by xkarosx** [comment]
I actually do so the command will be:
```
Ncat localhost 2399 --idle-timeout 3 --send-only
```

**Comment by nnposter** [comment]
If you want to receive some server data then you cannot use `--send-only`.

Please note that you are contradicting yourself in what you are trying to accomplish:

>> Please clearly describe how exactly you are interacting with the server and at what exact point of this interaction you want to disconnect.

> So after im done sending a file from me(the client) To the server. i want ncat to disconnect

and then

>> If you do not care for any of the server data then ...

> I actually do

You cannot disconnect once you send the data yet still want to receive a response.

**Comment by xkarosx** [comment]
Ok so i misunderstood that part 😂.
So if i want some of that response data i will use:
```
Ncat localhost 2399 --idle-timeout 3
```
And it will disconnect after 3 seconds
Is this still incorrect?

**Comment by nnposter** [comment]
Idle timeout will tear down the connection if the connection was idle for that long, presumably after the server sent its response. On the other hand, if the server keeps sending data back, while you want to receive only some portion of it, you can use the pipe or options `--exec`, `--sh-exec` or `--lua-exec` to read only the desired amount.

**Comment by xkarosx** [comment]
So when i use pipe and get fractions of the data back does ncat detect that as idle?

**Comment by xkarosx** [comment]
So while i use pipe to get some of the data back
Does ncat detect that as idle?

**Comment by nnposter** [comment]
No. Idle means no packets are flowing. You would use the reading process to exit after reading the data you want, which in turn breaks the connection.

**Comment by xkarosx** [comment]
So the command well be...?

**Comment by nnposter** [comment]
Here is an example, that will read only first 3 lines of the response and save them to file `foo`:
```
ncat -v -c 'sed -re 3q >foo' sometarget 80
```

**Comment by xkarosx** [comment]
Ok but does it disconnect after X seconds?

**Comment by nnposter** [comment]
No. As I said, this will disconnect after 3 lines. You can come up with other examples how to disconnect after a certain number of seconds instead. Ncat does not have such ability natively, other than the idle timeout.

**Comment by xkarosx** [comment]
```
ncat -v -c 'sed -re 5q >test' localhost 2399
```
It will disconnect after 5 lines of the server response are written to the file named 'test' 
Am i correct?

**Comment by nnposter** [comment]
yes

**Comment by xkarosx** [comment]
This helped me alot man 
Appreciate it.

**Comment by xkarosx** [comment]
Have a good day! 👍

**Comment by goarblt** [comment]
hello
https://www.evil.com/
