### ISSUE TITLE
Always get no reply when sending broadcast packets

### ISSUE THREAD

**Issue by yyy33** [nmap/nmap#2405]
**Describe the bug**
In fact, I received a reply package.

````
❯ sudo nping --icmp --dest-mac 50:04:b8:5b:b5:47 --dest-ip 255.255.255.255 -c 1

Starting Nping 0.7.92 ( https://nmap.org/nping ) at 2021-11-29 20:00 CST
SENT (0.8932s) ICMP [10.10.10.42 > 255.255.255.255 Echo request (type=8/code=0) id=25074 seq=1] IP [ttl=64 id=34390 iplen=28 ]

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
Raw packets sent: 1 (42B) | Rcvd: 0 (0B) | Lost: 1 (100.00%)
Nping done: 1 IP address pinged in 1.93 seconds
````
![2021-11-29_20-04](https://user-images.githubusercontent.com/51548147/143865221-213a7149-c29f-484b-811e-73e14058f351.png)

**To Reproduce**
Steps to reproduce the behavior, including command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nping --version`:
 - Output of `nmap --version`:
 - Output of `nmap --iflist`:

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by gvanem** [comment]
From `man nping`: *Nping uses the same syntax for target specifications that Nmap does.*

Does Nmap support an address like this? I guess, no.

**Comment by yyy33** [comment]
> From `man nping`: _Nping uses the same syntax for target specifications that Nmap does._
> 
> Does Nmap support an address like this? I guess, no.

You mean I have problems with the syntax I use?

**Comment by gvanem** [comment]
No. Just that Nping does not support Broadcast pings.

**Comment by nnposter** [comment]
The issue is that Nping generally expects the response to come from the target IP address.

You can leverage Nping ability to include arbitrary payload via option `--data` to trick it into accepting the responses:
```
$ nping --icmp --dest-mac yourtargetmac -c 1 --data 45FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 255.255.255.255

Starting Nping 0.7.92SVN ( https://nmap.org/nping ) at 2021-11-29 18:38 MST
SENT (0.9026s) ICMP [192.168.66.133 > 255.255.255.255 Echo request (type=8/code=0) id=51076 seq=1] IP [ttl=64 id=49186 iplen=48 ]
RCVD (0.9034s) ICMP [192.168.66.2 > 192.168.66.133 Echo reply (type=0/code=0) id=51076 seq=1] IP [ttl=128 id=24620 iplen=48 ]
 
Max rtt: 0.128ms | Min rtt: 0.128ms | Avg rtt: 0.128ms
Raw packets sent: 1 (62B) | Rcvd: 1 (48B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 1.94 seconds
```
Specifically, I am faking an embedded IPv4 header with a destination of 255.255.255.255, taking advantage of an ICMP fallback mechanism where Nping first inspects the *source* IP address of the ICMP response against the target list and if this fails then it also checks the *destination* IP address of an IPv4 packet that *might* be embedded in the ICMP response. Unfortunately ICMP Echo Reply packets do not embed Echo Request packets so this fallback does not come into effect by default.

**Comment by yyy33** [comment]
> The issue is that Nping generally expects the response to come from the target IP address.
> 
> You can leverage Nping ability to include arbitrary payload via option `--data` to trick it into accepting the responses:
> 
> ```
> $ nping --icmp --dest-mac yourtargetmac -c 1 --data 45FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 255.255.255.255
> 
> Starting Nping 0.7.92SVN ( https://nmap.org/nping ) at 2021-11-29 18:38 MST
> SENT (0.9026s) ICMP [192.168.66.133 > 255.255.255.255 Echo request (type=8/code=0) id=51076 seq=1] IP [ttl=64 id=49186 iplen=48 ]
> RCVD (0.9034s) ICMP [192.168.66.2 > 192.168.66.133 Echo reply (type=0/code=0) id=51076 seq=1] IP [ttl=128 id=24620 iplen=48 ]
>  
> Max rtt: 0.128ms | Min rtt: 0.128ms | Avg rtt: 0.128ms
> Raw packets sent: 1 (62B) | Rcvd: 1 (48B) | Lost: 0 (0.00%)
> Nping done: 1 IP address pinged in 1.94 seconds
> ```
> 
> Specifically, I am faking an embedded IPv4 header with a destination of 255.255.255.255, taking advantage of an ICMP fallback mechanism where Nping first inspects the _source_ IP address of the ICMP response against the target list and if this fails then it also checks the _destination_ IP address of an IPv4 packet that _might_ be embedded in the ICMP response. Unfortunately ICMP Echo Reply packets do not embed Echo Request packets so this fallback does not come into effect by default.

Thanks, this is a good way

**Comment by yyy33** [comment]
Thanks to everyone for the reply

**Comment by fyodor** [comment]
Wow, @nnposter .  That's some clever packet-fu!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
