### ISSUE TITLE
Termux nmap error


### ISSUE THREAD

**Issue by tharunjuturu** [nmap/nmap#2411]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

**Expected behavior**
Describe what you would like to happen instead.![Screenshot_2021-12-16-08-31-16-866_com.termux.jpg](https://user-images.githubusercontent.com/88937101/146300683-11016dcd-bb51-40c3-ad4a-56ff091d6031.jpg)

**Comment by fyodor** [comment]
Thanks for the report, but we would need more details than just a screenshot to work on this.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
