### ISSUE TITLE
 error:02001002:system library:fopen:No such file or directory

### ISSUE THREAD

**Issue by acauatunari** [nmap/nmap#2419]
## when I try to start the server, I get this error as a return

![image](https://user-images.githubusercontent.com/68363358/147909638-93aae4a2-5fbb-4542-8fc6-4255b973dc08.png)

**Comment by nnposter** [comment]
As far as I know, there is nothing wrong with this functionality:
```
root@kali:~/Desktop# ncat --listen --ssl --ssl-cert test-cert.pem --ssl-key test-key.pem -v
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Listening on :::31337
Ncat: Listening on 0.0.0.0:31337
```
Make sure that the two files are present, in the right directory, and with correct file permissions.

If you believe that there is truly a bug in Ncat then please reopen this issue and provide supporting information from the issue template and output of commands `id` and `ls -l test-*.pem`.
