### ISSUE TITLE
ncat: netcat -q secs option not supported

### ISSUE THREAD

**Issue by pothos** [nmap/nmap#2422]
**Describe the bug**
Both nc.traditional and nc.openbsd have a `-q secs			quit after EOF on stdin and delay of secs` parameter which `ncat` does not support. This fails the command invocation when `ncat` is used as symlinked drop-in for `nc`.

**To Reproduce**
`echo | ncat -q 1 1.1.1.1 53` results in `ncat: invalid option -- 'q'` `Ncat: Try '--help' or man(1) ncat for more information, usage options and help. QUITTING.`

**Expected behavior**
Same as `echo|nc.traditional -q 1 1.1.1.1 53` would lead to exiting after one second without failure and nothing printed.
The `-q 1` timeout kicks in becase stdin is closed after `echo` printed its single empty line.

**Version info (please complete the following information):**
 - OS: Linux 5.16rc8
 - Output of `ncat --version`: 7.80

**Additional context**
This is a compatibilty problem occuring on systems that try to stop shipping traditional or OpenBSD netcat, .e.g, on Flatcar Container Linux where `nc` is a symlink to `ncat`.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by dmiller-nmap** [comment]
Thanks for requesting this feature. The `-q` option is indeed unimplemented, as documented in our [Ncat/netcat compatibility](https://secwiki.org/w/Ncat/Compatibility) guide. I will label this issue as a feature request so we can prioritize it accordingly. Pull requests are also welcome.

**Comment by dmiller-nmap** [comment]
Fixed in 1db532209edbb24c8620f6ece22338496f6cba52. The commit with the docs for the -q option will close this issue.
