### ISSUE TITLE
How to list all devices on LAN (in C)

### ISSUE THREAD

**Issue by fmichaut-dev** [nmap/nmap#2423]
I don't really have an issue. I am just looking for some information.

I would like to detect all devices connected to LAN with their IP (and maybe MAC) addresses in a portable manner (windows/linux at least). This is to implement LAN discovery in my network application.

I know nmap is capable of doing so (for instance, the output of `nmap -sn 192.168.1.0/24` is exactly what I am looking for). I tried looking in the source code, but I couldn't find it.

Can I have a simple example on how to do so ?

**Comment by fyodor** [comment]
Hi.  The issues DB isn't really for Nmap usage questions.  I'd suggest emailing the Nmap development list (dev@nmap.org) instead or asking on the Nmap subreddit or on a site like StackExchange.  If you have an [Nmap OEM](https://nmap.org/oem/) license to redistribute Nmap within your application then you best bet is to contact our support group for help.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
