### ISSUE TITLE
--disable-arp-ping doesn't prevent arp pinging from occurring

### ISSUE THREAD

**Issue by michaelmelnick** [nmap/nmap#2424]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
Running packet captures while performing a wide variety of nmap scans shows that hundreds of ARPs are going out even when the `--disable-arp-ping` flag is set. While this is expected default behavior it should be alterable by the flag, and is not. 

**To Reproduce**
Example:

`sudo nmap -sn 192.168.*.1-255 --disable-arp-ping`

**Expected behavior**
I would expect to see just the specified protocol packets (-sn so ICMP), not parallel production of braodcast ARP entries for every address in the requested range. 

**Version info (please complete the following information):**
 - OS: Yocto / Ubuntu 20.04.2 LTS and MacOS 11.6
 - Output of `nmap --version`:
Yocto / Ubuntu:
Nmap version 7.92 ( https://nmap.org )
Platform: aarch64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1f nmap-libssh2-1.9.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

OSX:
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-apple-darwin19.6.0
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1m nmap-libssh2-1.9.0 libz-1.2.11 nmap-libpcre-7.6 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select
 - Output of `nmap --iflist`

Yocto / Ubuntu:

Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-11 18:40 UTC
************************INTERFACES************************
DEV             (SHORT)           IP/MASK                                 TYPE        UP MTU   MAC
resin-vpn       (resin-vpn)       10.240.74.249/32                        point2point up 1500
resin-vpn       (resin-vpn)       fe80::14f5:5a40:bc7f:f584/64            point2point up 1500
balena0         (balena0)         10.114.101.1/24                         ethernet    up 1500  02:42:8E:0D:B2:C4
br-9ff6f35066c7 (br-9ff6f35066c7) 172.18.0.1/16                           ethernet    up 1500  02:42:76:71:ED:CC
supervisor0     (supervisor0)     10.114.104.1/25                         ethernet    up 1500  02:42:D8:49:41:42
lo              (lo)              127.0.0.1/8                             loopback    up 65536
lo              (lo)              ::1/128                                 loopback    up 65536
resin-dns       (resin-dns)       10.114.102.1/24                         ethernet    up 1500  62:CD:51:32:E6:2F
wlan0           (wlan0)           (none)/0                                ethernet    up 1500  FE:78:CE:8F:AF:A1
eth0            (eth0)            192.168.4.24/22                         ethernet    up 1500  B8:27:EB:AC:B0:0E
eth0            (eth0)            fe80::a83f:6cb6:b26:cacc/64             ethernet    up 1500  B8:27:EB:AC:B0:0E
eth0            (eth0)            fd42:8a0d:2df2:1:ba27:ebff:feac:b00e/64 ethernet    up 1500  B8:27:EB:AC:B0:0E
eth0            (eth0)            fd42:8a0d:2df2:1:372f:29cc:31d:4796/64  ethernet    up 1500  B8:27:EB:AC:B0:0E

**************************ROUTES**************************
DST/MASK                                 DEV             METRIC GATEWAY
52.4.252.97/32                           resin-vpn       0
10.114.104.0/25                          supervisor0     0
10.114.101.0/24                          balena0         0
10.114.102.0/24                          resin-dns       0
192.168.4.0/22                           eth0            100
172.18.0.0/16                            br-9ff6f35066c7 0
0.0.0.0/0                                eth0            100    192.168.4.1
::1/128                                  lo              0
fd42:8a0d:2df2:1:372f:29cc:31d:4796/128  eth0            0
fd42:8a0d:2df2:1:ba27:ebff:feac:b00e/128 eth0            0
fe80::14f5:5a40:bc7f:f584/128            resin-vpn       0
fe80::a83f:6cb6:b26:cacc/128             eth0            0
::1/128                                  lo              256
fd42:8a0d:2df2:1::/64                    eth0            100
fe80::/64                                eth0            100
fd42:8a0d:2df2:1::/64                    eth0            256
fe80::/64                                resin-vpn       256
ff00::/8                                 eth0            256
ff00::/8                                 resin-vpn       256
::/0                                     eth0            1024   fe80::9aed:7eff:fe6d:b3f2
::/0                                     eth0            20100  fe80::9aed:7eff:fe6d:b3f2

OSX:

Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-11 18:40 GMT
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                                  TYPE        UP   MTU   MAC
lo0     (lo0)     127.0.0.1/8                              loopback    up   16384
lo0     (lo0)     ::1/128                                  loopback    up   16384
lo0     (lo0)     fe80::1/128                              loopback    up   16384
gif0    (gif0)    (none)/0                                 point2point down 1280
stf0    (stf0)    (none)/0                                 other       down 1280
en5     (en5)     (none)/0                                 ethernet    up   1500  AC:DE:48:00:11:22
en5     (en5)     fe80::aede:48ff:fe00:1122/128            ethernet    up   1500  AC:DE:48:00:11:22
ap1     (ap1)     (none)/0                                 ethernet    up   1500  F2:18:98:14:2A:51
en0     (en0)     192.168.4.22/22                          ethernet    up   1500  F0:18:98:14:2A:51
en0     (en0)     fe80::62:ec4e:b9e8:a010/128              ethernet    up   1500  F0:18:98:14:2A:51
en0     (en0)     fd42:8a0d:2df2:1:148f:78f3:7678:de0e/128 ethernet    up   1500  F0:18:98:14:2A:51
awdl0   (awdl0)   (none)/0                                 ethernet    up   1500  2E:8A:8D:F5:56:4F
awdl0   (awdl0)   fe80::2c8a:8dff:fef5:564f/128            ethernet    up   1500  2E:8A:8D:F5:56:4F
llw0    (llw0)    (none)/0                                 ethernet    up   1500  2E:8A:8D:F5:56:4F
llw0    (llw0)    fe80::2c8a:8dff:fef5:564f/128            ethernet    up   1500  2E:8A:8D:F5:56:4F
en3     (en3)     (none)/0                                 ethernet    up   1500  82:FC:FA:88:CC:05
en4     (en4)     (none)/0                                 ethernet    up   1500  82:FC:FA:88:CC:04
en1     (en1)     (none)/0                                 ethernet    up   1500  82:FC:FA:88:CC:01
en2     (en2)     (none)/0                                 ethernet    up   1500  82:FC:FA:88:CC:00
bridge0 (bridge0) (none)/0                                 ethernet    up   1500  82:FC:FA:88:CC:01
utun0   (utun0)   (none)/0                                 point2point up   1380
utun0   (utun0)   fe80::2840:9a9:ac24:9819/128             point2point up   1380
utun1   (utun1)   (none)/0                                 point2point up   2000
utun1   (utun1)   fe80::afbb:14f6:c34e:9ebe/128            point2point up   2000

**************************ROUTES**************************
DST/MASK                        DEV   METRIC GATEWAY
172.217.16.131/32               en0   0      192.168.4.1
192.168.1.254/32                en0   0      192.168.4.1
172.217.169.2/32                en0   0      192.168.4.1
17.57.146.153/32                en0   0      192.168.4.1
172.217.169.3/32                en0   0      192.168.4.1
18.168.175.133/32               en0   0      192.168.4.1
172.217.169.14/32               en0   0      192.168.4.1
34.238.13.177/32                en0   0      192.168.4.1
172.217.169.35/32               en0   0      192.168.4.1
35.213.86.143/32                en0   0      192.168.4.1
44.231.33.233/32                en0   0      192.168.4.1
52.5.230.162/32                 en0   0      192.168.4.1
52.40.207.36/32                 en0   0      192.168.4.1
52.97.133.178/32                en0   0      192.168.4.1
52.97.133.226/32                en0   0      192.168.4.1
52.97.179.226/32                en0   0      192.168.4.1
52.215.192.133/32               en0   0      192.168.4.1
54.190.100.195/32               en0   0      192.168.4.1
54.224.92.216/32                en0   0      192.168.4.1
76.223.31.44/32                 en0   0      192.168.4.1
87.248.100.168/32               en0   0      192.168.4.1
92.247.181.40/32                en0   0      192.168.4.1
99.86.116.141/32                en0   0      192.168.4.1
104.18.89.237/32                en0   0      192.168.4.1
104.21.55.208/32                en0   0      192.168.4.1
104.244.42.2/32                 en0   0      192.168.4.1
104.244.42.68/32                en0   0      192.168.4.1
104.244.42.129/32               en0   0      192.168.4.1
104.244.42.130/32               en0   0      192.168.4.1
104.244.42.132/32               en0   0      192.168.4.1
104.244.42.196/32               en0   0      192.168.4.1
108.177.15.157/32               en0   0      192.168.4.1
127.0.0.1/32                    lo0   0      127.0.0.1
140.82.112.26/32                en0   0      192.168.4.1
140.82.114.26/32                en0   0      192.168.4.1
140.82.121.4/32                 en0   0      192.168.4.1
140.82.121.6/32                 en0   0      192.168.4.1
142.250.110.188/32              en0   0      192.168.4.1
142.250.178.2/32                en0   0      192.168.4.1
142.250.178.10/32               en0   0      192.168.4.1
142.250.178.14/32               en0   0      192.168.4.1
142.250.179.226/32              en0   0      192.168.4.1
142.250.179.227/32              en0   0      192.168.4.1
142.250.179.234/32              en0   0      192.168.4.1
142.250.180.2/32                en0   0      192.168.4.1
142.250.180.14/32               en0   0      192.168.4.1
142.250.187.206/32              en0   0      192.168.4.1
142.250.187.225/32              en0   0      192.168.4.1
142.250.187.238/32              en0   0      192.168.4.1
142.250.200.1/32                en0   0      192.168.4.1
142.250.200.10/32               en0   0      192.168.4.1
142.250.200.37/32               en0   0      192.168.4.1
151.101.16.201/32               en0   0      192.168.4.1
151.101.18.167/32               en0   0      192.168.4.1
162.125.19.130/32               en0   0      192.168.4.1
162.125.19.131/32               en0   0      192.168.4.1
162.159.134.234/32              en0   0      192.168.4.1
172.66.40.203/32                en0   0      192.168.4.1
172.217.16.226/32               en0   0      192.168.4.1
172.217.16.228/32               en0   0      192.168.4.1
172.217.16.238/32               en0   0      192.168.4.1
18.135.227.37/32                en0   0      192.168.4.1
34.234.127.156/32               en0   0      192.168.4.1
35.174.127.31/32                en0   0      192.168.4.1
35.174.225.168/32               en0   0      192.168.4.1
172.217.169.37/32               en0   0      192.168.4.1
172.217.169.42/32               en0   0      192.168.4.1
172.217.169.65/32               en0   0      192.168.4.1
172.217.169.66/32               en0   0      192.168.4.1
172.217.169.74/32               en0   0      192.168.4.1
185.199.110.133/32              en0   0      192.168.4.1
13.107.246.64/32                en0   0      192.168.4.1
192.168.4.1/32                  en0   0
192.168.4.1/32                  en0   0
192.168.4.22/32                 en0   0
216.58.212.195/32               en0   0      192.168.4.1
216.58.212.234/32               en0   0      192.168.4.1
216.58.212.238/32               en0   0      192.168.4.1
216.58.213.2/32                 en0   0      192.168.4.1
216.58.213.3/32                 en0   0      192.168.4.1
216.58.213.6/32                 en0   0      192.168.4.1
216.58.213.22/32                en0   0      192.168.4.1
216.239.32.116/32               en0   0      192.168.4.1
216.239.36.54/32                en0   0      192.168.4.1
255.255.255.255/32              en0   0
192.168.4.0/22                  en0   0
169.254.0.0/16                  en0   0
127.0.0.0/8                     lo0   0      127.0.0.1
224.0.0.0/4                     en0   0
0.0.0.0/0                       en0   0      192.168.4.1
::1/128                         lo0   0      ::1
2001:4860:4860::8888/128        en0   0      fe80:6::9aed:7eff:fe6d:b3f2
2a00:1450:4009:80a::2003/128    en0   0      fe80:6::9aed:7eff:fe6d:b3f2
fe80:1::1/128                   lo0   0
fe80:e::2840:9a9:ac24:9819/128  lo0   0
fe80:f::afbb:14f6:c34e:9ebe/128 lo0   0
fd42:8a0d:2df2:1::/64           en0   0
fe80:1::/64                     lo0   0      fe80:1::1
fe80:4::/64                     en5   0
fe80:6::/64                     en0   0
fe80:7::/64                     awdl0 0
fe80:8::/64                     llw0  0
ff01:1::/32                     lo0   0      ::1
ff01:4::/32                     en5   0
ff01:6::/32                     en0   0
ff01:7::/32                     awdl0 0
ff01:8::/32                     llw0  0
ff02:1::/32                     lo0   0      ::1
ff02:4::/32                     en5   0
ff02:6::/32                     en0   0
ff02:7::/32                     awdl0 0
ff02:8::/32                     llw0  0
ff00::/8                        lo0   0      ::1
ff00::/8                        en5   0
ff00::/8                        en0   0
ff00::/8                        awdl0 0
ff00::/8                        llw0  0
::/0                            en0   0      fe80:6::9aed:7eff:fe6d:b3f2
::/0                            utun0 0      fe80:e::
::/0                            utun1 0      fe80:f::

**Comment by nnposter** [comment]
I might be missing something in the description of your issue. How do you expect the layer-3 host discovery packets (ICMP or other) to be send to the targets without obtaining their MAC addresses first?

**Comment by michaelmelnick** [comment]
Hi, I'm sure I could missing something here too, but:

- Does that mean this option shouldn't exist at all?
- Nmap could check the internal arp table for existing entries which would reduce the number of hosts that need to be discovered
- I figure this may interact in some way with the `--send-ip` options which should presumably not require layer-3 packets to get linked to layer-2 addresses first

**Comment by fyodor** [comment]
Hi @michaelmelnick.  Thanks for your post.  Nmap normally does an "ARP scan" where it sweeps the directly-connected (same ethernet segment) addresses to find the responsive hosts.  All the hosts which don't respond are marked as down and not scanned further.  The ones which respond are marked up and Nmap skips higher level ping sweeps (such as ICMP echo request).  When you disable ARP scan as you did, Nmap skips the preliminary ARP sweep and tries to do higher level discovery (such as sending ICMP echo request) to each address.   This is usually slower and less reliable, so --disable-arp-ping is only recommended for fairly obscure special cases, such as the [proxy arp example in the man page](https://nmap.org/book/man-host-discovery.html).  Even if you disable ARP ping, you will still see some ARP messages sent out for the reason described by @nnposter.  When Nmap asks the system to send an ICMP echo request to an individual target, for example, the system has to do ARP resolution to determine that target's MAC address if the system is not already in the ARP cache.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
