### ISSUE TITLE
[Question] How to select an interface in Windows?

### ISSUE THREAD

**Issue by PinkDev1** [nmap/nmap#2425]
- Nmap version 7.90 ( https://nmap.org )
- Platform: i686-pc-windows-windows
- Compiled with: nmap-liblua-5.3.5 openssl-1.1.1h nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-1.55 nmap-libdnet-1.12 ipv6
- Compiled without:
- Available nsock engines: iocp poll select

I've tried selecting an interface with the same name that `netsh wlan show interfaces` returns, but it always throws the same error:
```
> nmap --source-port 80 -O -sV -p 3000 -T4 -iL weird_http.txt -e Wi-Fi
Starting Nmap 7.90 ( https://nmap.org ) at 2022-01-14 21:11 Argentina Standard Time
I cannot figure out what source address to use for device Wi-Fi, does it even exist?
QUITTING!
```

What name should I use to select an interface in the windows version?

**Comment by fyodor** [comment]
Keep in mind that Nmap should select the appropriate interface itself in most cases.  But if you want/need to select an interface, check "nmap --iflist" for the options. If that doesn't work, and you try with Nmap version 7.92 and it still doesn't work, please let us know the details and we can re-open.

**Comment by PinkDev1** [comment]
That worked, thanks :)
