### ISSUE TITLE
Nmap runtime error in AWS lambda

### ISSUE THREAD

**Issue by Abdullah-alfadhel** [nmap/nmap#2433]
**Describe the bug**
This is the error : "2022-01-28T15:01:11.602Z	402fbdb2-2edd-45f3-838e-ecf3f3c55407	INFO	Can't parse port list "53," at line 43 of nmap-payloads."

Nmap gives an error when parsing the payload when I run it in AWS lambda. At first, I thought it would be the same issue that got fixed 2 months ago in version 7.92 but it's not! As I copied the nmap-payload file from the Nmap repo just to make sure. And still got the same error.

**To Reproduce**
Steps to reproduce the behavior, including command-line options.
I'm launching Nmap through the node child_processes and exeFile methods.
Create the index.js file and copy the code bellow,

My index. file is as follow:

**this serves as a blueprint to execute any file you want.

```

const BINARY = "nmap"; // binary to be run (needs to be uploaded with your Lambda function!)

var path = require("path");
var childProcess = require("child_process");

exports.handler = function (event, context, callback) {
  var text = event && event.text ? event.text : false;

  if (!text) {
    callback("Missing input params or invalid ip or url.");
    return;
  }

  // set env path, as per https://aws.amazon.com/blogs/compute/running-executables-in-aws-lambda/
  process.env["PATH"] =
    process.env["PATH"] + ":" + process.env["LAMBDA_TASK_ROOT"];

  var target = text.split(" "); // consider doing a .split(' ') and passing the resulting array in as processArgs for more command line options ;)
  var binaryPath = path.join(__dirname, "/tmp/bin", BINARY);
  var processArgs = [target];

  // run the binary, passing in arguments
  childProcess.execFile(
    binaryPath,
    processArgs,
    { maxBuffer: 1024 * 5000 },
    function (error, stdout, stderr) {
      // unable to run the binary:
      if (error) {
        console.log("Error running binary:", error);
        callback(error, null);
        return;
      }

      // binary returns an error:
      if (stderr) {
        console.log(stderr);
        callback(error, null);
        return;
      }

      // binary succeeds:
      var response = {
        response_type: "in_channel",
        text: "Response from Lambda: \n```" + stdout + "```",
      };

      callback(error, response);
      return;
    }
  );
};


```
As i ran it, it showed that it need the extra files, so i copied all the nmap repo as I don't know what to take and what to leave.
Then I created a "/tmp/bin" and "/tmp/share" files so it can be used by nmap binary and the file structure became as follows:

```

├── index.js
├── node_modules
├── nodejs
│   └── node14
│       └── node_modules
├── package-lock.json
├── package.json
└── tmp
    ├── bin
    │   ├── BSDmakefile
    │   ├── CHANGELOG
    │   ├── CONTRIBUTING.md
    │   ├── FPEngine.cc
    │   ├── FPEngine.h
    │   ├── FPModel.cc
    │   ├── FPModel.h
    │   ├── FingerPrintResults.cc
    │   ├── FingerPrintResults.h
    │   ├── HACKING
    │   ├── INSTALL
    │   ├── LICENSE
    │   ├── MACLookup.cc
    │   ├── MACLookup.h
    │   ├── Makefile.in
    │   ├── NewTargets.cc
    │   ├── NewTargets.h
    │   ├── NmapOps.cc
    │   ├── NmapOps.h
    │   ├── NmapOutputTable.cc
    │   ├── NmapOutputTable.h
    │   ├── README-WIN32
    │   ├── README.md
    │   ├── Target.cc
    │   ├── Target.h
    │   ├── TargetGroup.cc
    │   ├── TargetGroup.h
    │   ├── acinclude.m4
    │   ├── aclocal.m4
    │   ├── charpool.cc
    │   ├── charpool.h
    │   ├── checklibs.sh
    │   ├── config.guess
    │   ├── config.sub
    │   ├── configure
    │   ├── configure.ac
    │   ├── depcomp
    │   ├── idle_scan.cc
    │   ├── idle_scan.h
    │   ├── libdnet-stripped
    │   ├── liblinear
    │   ├── liblua
    │   ├── libnetutil
    │   ├── libpcap
    │   ├── libpcre
    │   ├── libssh2
    │   ├── libz
    │   ├── lpeg.c
    │   ├── ltmain.sh
    │   ├── macosx
    │   ├── main.cc
    │   ├── missing
    │   ├── mswin32
    │   ├── nbase
    │   ├── ncat
    │   ├── ndiff
    │   ├── nmap
    │   ├── nmap-header-template.cc
    │   ├── nmap-mac-prefixes
    │   ├── nmap-os-db
    │   ├── nmap-payloads
    │   ├── nmap-protocols
    │   ├── nmap-rpc
    │   ├── nmap-service-probes
    │   ├── nmap-services
    │   ├── nmap.cc
    │   ├── nmap.h
    │   ├── nmap.spec.in
    │   ├── nmap_amigaos.h
    │   ├── nmap_config.h.in
    │   ├── nmap_dns.cc
    │   ├── nmap_dns.h
    │   ├── nmap_error.cc
    │   ├── nmap_error.h
    │   ├── nmap_ftp.cc
    │   ├── nmap_ftp.h
    │   ├── nmap_tty.cc
    │   ├── nmap_tty.h
    │   ├── nmap_winconfig.h
    │   ├── nping
    │   ├── nse_debug.cc
    │   ├── nse_debug.h
    │   ├── nse_dnet.cc
    │   ├── nse_dnet.h
    │   ├── nse_fs.cc
    │   ├── nse_fs.h
    │   ├── nse_libssh2.cc
    │   ├── nse_libssh2.h
    │   ├── nse_lpeg.cc
    │   ├── nse_lpeg.h
    │   ├── nse_lua.h
    │   ├── nse_main.cc
    │   ├── nse_main.h
    │   ├── nse_main.lua
    │   ├── nse_nmaplib.cc
    │   ├── nse_nmaplib.h
    │   ├── nse_nsock.cc
    │   ├── nse_nsock.h
    │   ├── nse_openssl.cc
    │   ├── nse_openssl.h
    │   ├── nse_pcrelib.cc
    │   ├── nse_pcrelib.h
    │   ├── nse_ssl_cert.cc
    │   ├── nse_ssl_cert.h
    │   ├── nse_utility.cc
    │   ├── nse_utility.h
    │   ├── nse_zlib.cc
    │   ├── nse_zlib.h
    │   ├── nselib
    │   ├── nsock
    │   ├── osscan.cc
    │   ├── osscan.h
    │   ├── osscan2.cc
    │   ├── osscan2.h
    │   ├── output.cc
    │   ├── output.h
    │   ├── payload.cc
    │   ├── payload.h
    │   ├── portlist.cc
    │   ├── portlist.h
    │   ├── portreasons.cc
    │   ├── portreasons.h
    │   ├── probespec.h
    │   ├── protocols.cc
    │   ├── protocols.h
    │   ├── scan_engine.cc
    │   ├── scan_engine.h
    │   ├── scan_engine_connect.cc
    │   ├── scan_engine_connect.h
    │   ├── scan_engine_raw.cc
    │   ├── scan_engine_raw.h
    │   ├── scan_lists.cc
    │   ├── scan_lists.h
    │   ├── scripts
    │   ├── service_scan.cc
    │   ├── service_scan.h
    │   ├── services.cc
    │   ├── services.h
    │   ├── shtool
    │   ├── string_pool.cc
    │   ├── string_pool.h
    │   ├── struct_ip.h
    │   ├── targets.cc
    │   ├── targets.h
    │   ├── tcpip.cc
    │   ├── tcpip.h
    │   ├── tests
    │   ├── timing.cc
    │   ├── timing.h
    │   ├── todo
    │   ├── traceroute.cc
    │   ├── traceroute.h
    │   ├── utils.cc
    │   ├── utils.h
    │   ├── xml.cc
    │   ├── xml.h
    │   ├── zenmap
    │   └── zenmap.spec.in
    └── share

27 directories, 141 files

```
After that just zip the tmp and index in one zip file and upload it to lambda with node 14.x runtime.
and use the target as : www.google.com

**Expected behavior**
The expected behavior is to have the nmap normal return

**Version info (please complete the following information):**
 - OS: Amazon linux 2
 - Output of `nmap --version`: 
 nNmap version 6.49BETA1 ( http://nmap.org )\nPlatform: x86_64-unknown-linux-gnu\nCompiled with: nmap-liblua-5.2.3 openssl-1.0.2c nmap-libpcre-7.6 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6\nCompiled without:\nAvailable nsock engines: epoll poll select\n
 
 - Output of `nmap --iflist`:
 nStarting Nmap 6.49BETA1 ( http://nmap.org ) at 2022-01-28 15:25 UTC\n************************INTERFACES************************\nDEV           (SHORT)         IP/MASK           TYPE     UP MTU   MAC\nvtarget_1     (vtarget_1)     169.254.79.1/32   ethernet up 1500  8E:8E:63:97:A5:6B\ntelemetry1_sb (telemetry1_sb) 169.254.79.130/30 ethernet up 1500  3E:30:71:A9:A3:43\nlo            (lo)            127.0.0.1/8       loopback up 65536\nvinternal_1   (vinternal_1)   169.254.76.1/23   ethernet up 1500  E2:02:16:80:7C:4F\n\n**************************ROUTES**************************\nDST/MASK          DEV           METRIC GATEWAY\n169.254.76.2/32   vinternal_1   0\n169.254.79.2/32   vtarget_1     0\n169.254.79.128/30 telemetry1_sb 0\n169.254.76.0/23   vinternal_1   0\n0.0.0.0/0         vinternal_1   0      169.254.76.2\n\n

**Additional context**
Thank you for your time and please tell me if a need to edit any thing to make the issue clearer.

**Comment by nnposter** [comment]
Recent `nmap-payloads` file is not likely going to work with Nmap 6.49BETA1. As an example, port ranges were not supported back then.

**Comment by Abdullah-alfadhel** [comment]
ok, and I discovered something else, you can't run Nmap in AWS lambda because we don't have root privileges in our Faas.

But as a side note. do new releases of Nmap have executable binary just like the one I'm using?

**Comment by nnposter** [comment]
> you can't run Nmap in AWS lambda because we don't have root privileges in our Faas

While you lose some functionality, you can still accomplish quite a bit without root privileges. Take a look at option `--unprivileged`. You can still perform port scans (via `-sT`), albeit not as efficiently, do version scans, and run most of the scripts.

> do new releases of Nmap have executable binary just like the one I'm using?

It is preferred to use binaries provided by your Linux distribution or compile your own to match the architecture and libraries. https://nmap.org/dist/?C=M&O=D has generic RPMs for Intel.

**Comment by Abdullah-alfadhel** [comment]
Thank you for your knowledge, but AWS lambda is using amazon Linux 2. How do I compile Nmap for it?

**Comment by nnposter** [comment]
I have no personal experience with Amazon Linux but you should be able to install and run standard GNU development tools, such as gcc, and compile your own Nmap binaries.

You can also try installing Nmap RPMs directly:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-software.html

**Comment by goarblt** [comment]
hello
https://www.evil.com/
