### ISSUE TITLE
Problems encountered when running multiple nping processes simultaneously

### ISSUE THREAD

**Issue by yyy33** [nmap/nmap#2435]
**Describe the bug**
When multiple processes are running simultaneously, the same reply packets are grabbed between processes

**To Reproduce**
````
#!/usr/bin/env zsh

MAC_LIST=('50:04:b8:5b:b5:47'
        'b8:27:eb:74:f2:60 b8:27:eb:74:f2:61'
        '94:be:46:41:42:d5'
        '74:5b:b5:8b:40:05 10:c3:7b:56:a7:a3 9c:d2:1e:2c:f5:52')

for MAC in ${MAC_LIST}; do
        sudo nping --icmp \
            --icmp-type echo-request \
            --dest-mac $MAC \
            --dest-ip 255.255.255.255 \
            --data 45FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF \
            -c 3 \
            --delay 100ms \
        | grep RCVD | grep -Pom1 '(?<=\[).*(?= >)' 2>/dev/null &
done
````
Only the device `50:04:b8:5b:b5:47` can respond to broadcast icmp packets in `MAC_LIST`, and the IP address of the device `50:04:b8:5b:b5:47` is `10.10.10.116`.
Normally the script should only print one line of text: 10.10.10.116, but after I run it, it prints 7 lines of text: 10.10.10.116

**Expected behavior**
See above
 
**Version info (please complete the following information):**
 - OS: Linux x550vc-yyy 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux
 - Output of `nping --version`:Nping version 0.7.92 ( https://nmap.org/nping )
 - Output of `nmap --version`:
 ```
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-1.1.1m libssh2-1.9.0 libz-1.2.11 libpcre-8.45 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
 - Output of `nmap --iflist`:
 ```
Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-30 09:59 CST
************************INTERFACES************************
DEV   (SHORT) IP/MASK                      TYPE     UP MTU   MAC
lo    (lo)    127.0.0.1/8                  loopback up 65536
lo    (lo)    ::1/128                      loopback up 65536
lan0  (lan0)  (none)/0                     ethernet up 1500  10:C3:7B:56:A7:A3
wlan0 (wlan0) 10.10.10.41/24               ethernet up 1500  9C:D2:1E:2C:F5:52
wlan0 (wlan0) fe80::9ed2:1eff:fe2c:f552/64 ethernet up 1500  9C:D2:1E:2C:F5:52

**************************ROUTES**************************
DST/MASK                      DEV   METRIC GATEWAY
10.10.10.0/24                 wlan0 3003
0.0.0.0/0                     wlan0 3003   10.10.10.1
::1/128                       lo    0
fe80::9ed2:1eff:fe2c:f552/128 wlan0 0
::1/128                       lo    256

```

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by nnposter** [comment]
This is to be expected. Nping is a layer-3 ping tool, so by default it is not making assumption about the MAC address the responses might come from. It would not be appropriate to filter received responses based on the value of `--dest-mac`.

That said, you should be able to accomplish your goal by adding option `--bpf-filter "ether src host $MAC"` or some variation of this, depending on your environment.

**Comment by yyy33** [comment]
> This is to be expected. Nping is a layer-3 ping tool, so by default it is not making assumption about the MAC address the responses might come from. It would not be appropriate to filter received responses based on the value of `--dest-mac`.
> 
> That said, you should be able to accomplish your goal by adding option `--bpf-filter "ether src host $MAC"` or some variation of this, depending on your environment.

Thanks for the answer, I added that option and it works fine
` --bpf-filter "ether src $MAC" `

**Comment by goarblt** [comment]
hello
https://www.evil.com/
