### ISSUE TITLE
How can I ask nmap to detect https protocol first?

### ISSUE THREAD

**Issue by CaledoniaProject** [nmap/nmap#2437]
**Describe the bug**
This nginx website accepts both https and http protocol on port 443: 

* hxxp://t.open-xchange.com:443/
* hxxps://t.open-xchange.com:443/

And I want nmap to detect it as https port instead.

How can I ask nmap to send the https payload first?

**Comment by fyodor** [comment]
Thanks for posting.  I'm closing this since it is a question rather than a clear bug report or feature request, but anyone is still welcome to respond.  You also might try other forums like the Nmap dev list, Nmap subreddit, Stackexchange, Quora, etc.

**Comment by CaledoniaProject** [comment]
Understood, I'll post the question elsewhere.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
