### ISSUE TITLE
unrecognized option '--discovery-ignore-rst'

### ISSUE THREAD

**Issue by tomsuzans** [nmap/nmap#2438]
**Describe the bug**
After upgrading CentOS8 to Alma Linux 8.5 nmap is not recognising command '--discovery-ignore-rst'
![image](https://user-images.githubusercontent.com/73278234/152416083-e4dbf97e-f988-41be-8492-af9112ec8275.png)

**To Reproduce**
nmap 192.168.88.1 --discovery-ignore-rst

**Expected behavior**
Expected to run scan

**Version info (please complete the following information):**
 - OS: Alma Linux 8.5
 - Output of `nmap --version`: 7.70

**Comment by nnposter** [comment]
Version 7.70 predates implementation of this option by about two years.

**Comment by tomsuzans** [comment]
Ok. Alma/C8 repo has old version. Have to compile manually

**Comment by goarblt** [comment]
hello
https://www.evil.com/
