### ISSUE TITLE
Upgrade Nmap to the Universal CRT

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#2448]
We should use the Universal CRT to avoid needing to install a VC runtime on Windows 10 and later. We may already have done this, but need to confirm that we're doing so.

https://docs.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt?view=msvc-170

**Comment by fyodor** [comment]
I'm closing this after discussion with @dmiller-nmap.  We think we probably got UCRT by default back when we upgraded to (and beyond) VS2015.  And it looks like we do still need to install the VC runtime.
