### ISSUE TITLE
xml report with --webxml stylesheet is missing the stylesheet

### ISSUE THREAD

**Issue by andreaskern** [nmap/nmap#245]
# Steps to reproduce
* Generate report with `nmap -oX test.xml --webxml 192.168.0.0./28`
* open xml file with `firefox test.xml`

# Expected
* Firefox shows contents of the xml file

# Actually
* Firefox shows "Error loading stylesheet: An unknown error has occurred (805303f4)"
  * Firefox console says  "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://svn.nmap.org/nmap/docs/nmap.xsl. (Reason: CORS header 'Access-Control-Allow-Origin' missing)."

# Additional information
embedding the stylesheet does not work because the server does not support Cross-Origin Request
`wget http://nmap.org/svn/docs/nmap.xsl` and `--stylesheet ./nmap.xsl` works as expected

**Comment by dmiller-nmap** [comment]
Thanks for this report. We were aware this was broken because of security restrictions, but did not know there was a fix we could implement server-side. This should work now on Firefox, but Chrome will still not allow loading of remote XSLT stylesheets for local files, giving this error:

    'file:' URLs are treated as unique security origins.
