### ISSUE TITLE
NSE constructing bad DHCP message with IP

### ISSUE THREAD

**Issue by leshow** [nmap/nmap#2454]
**Describe the bug**
I modified the `dhcp-discover` script to add a requested IP address parameter so that you can construct a DHCPREQUEST where option 50 is set to an IP of your choosing. `nmap` seems to construct a bad dhcp message when you set `options` on `dhcp.make_request` see:

![shark](https://user-images.githubusercontent.com/1128302/158202626-36da2793-7de3-4dfc-b049-e8b88fc7d5c8.png)

**To Reproduce**

```
 sudo nmap -sU -p 67 --script /home/leshow/dev/scripts/dhcp-discover --script-args dhcptype=DHCPREQUEST,req_addr=192.168.0.149,mac=DEADC0DECAFE -vvv 192.168.0.1 -d1
```

I added the `req_addr` field, with the following modifications to the script:
```

  local opts = {}
  if (stdnse.get_script_args(SCRIPT_NAME .. ".req_addr") or nil) then
    stdnse.debug1("Inserting request ip address %s", req_addr);
    table.insert(opts, {number = 50, type = "ip", value = req_addr})
  end

... when the request is made, I pass through opts
   local status, result = dhcp.make_request(host.ip, dhcptypeid, iface.address, macaddr, opts, nil, overrides)
```

**Expected behavior**
I expect the IP to be put in the DHCP message with a length of 4

**Version info (please complete the following information):**
 - OS: Linux 5.16.14
 - Output of `nmap --version`:
 ```
❯ nmap --version
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-1.1.1m libssh2-1.9.0 libz-1.2.11 libpcre-8.45 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
 ```

**Additional context**
The docs for `make_request` say that the `type` field should be `string` | `ip` but I found that neither worked, additionally running `ipOps.str_to_ip(req_addr)` threw an exception, although the output of the IP in debug logs looked correct:

```
NSE: [dhcp-discover 192.168.0.1:67] Inserting request ip address 192.168.0.149
```

**Comment by leshow** [comment]
Blah, you need to call `ipOps.ip_to_str(req_addr)`. I thought because the IP value was already a string that `make_request` would do this for me.

Sorry for wasting your time, closing.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
