### ISSUE TITLE
Zenmap fails to run commands that nmap can run

### ISSUE THREAD

**Issue by sql-sith** [nmap/nmap#2455]
**Describe the bug**

**To Reproduce**
Start Zenmap as root and run any of the predefined scan profiles as root. This causes the following message to appear: 

```
dnet: Failed to open device wlp3s0
QUITTING! 
```

**Expected behavior**
Scans run as root perform as expected.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS, 5.13.0-35-generic x86_64
 - Zenmap version from 7.92 (installed and run with flatpak)
 - Output of `nmap --version`:
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1k nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Additional context**
Since Zenmap requires Python 2.x, flatpak is the only way I could find to install and run Zenmap. Please let me know if there is a better way. When running as root, no Zenmap scans succeed but if I copy the nmap commands from Zenmap and paste them into a root terminal, they run successfully there. Zenmap run as a normal user succeeds when it should. For example, "Quick scan" succeeds but "Quick scan plus" causes this message to appear:

```
TCP/IP fingerprinting (for OS scan) requires root privileges.
QUITTING!
```

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by dmiller-nmap** [comment]
Zenmap has been upgraded to Python 3: #1176 

The issue reported here is due to flatpak sandboxing. If you want to use Zenmap or Nmap within any sandbox, you will have to configure the sandbox to grant the necessary permissions or capabilities. This is not something we can do from our code. Thanks for reporting this issue.

**Comment by mmiller7** [comment]
> Zenmap has been upgraded to Python 3: #1176
> 
> The issue reported here is due to flatpak sandboxing. If you want to use Zenmap or Nmap within any sandbox, you will have to configure the sandbox to grant the necessary permissions or capabilities. This is not something we can do from our code. Thanks for reporting this issue.

What permissions should be enabled so it can run nmap/ping/etc as root?  I don't see any that are obviously labeled "allow root"
