### ISSUE TITLE
Issue with NSE 'sh: 1:' 

### ISSUE THREAD

**Issue by aretsmarvin** [nmap/nmap#2457]
**Info:**
I am working on a scanner with Nmap. I am expanding this scanner with NSE scripts.

**Issue:**
I have a script that runs '[Nuclei](https://github.com/projectdiscovery/nuclei)', using Nmap. This script is made and used by someone else, and it has worked before. However, when I run it now, I get the error: `sh: 1: nuclei: not found`. Nuclei is (of course) installed on the system, and it works as root and normal user. It looks like Nmap doesn't have access to Nuclei, but how to fix?

The NSE script:
```
local shortport = require "shortport"
local stdnse = require "stdnse" 

portrule = function(host,port) 
	return true
end 

action = function(host,port) 
	local handle = ""
        local always = stdnse.get_script_args("nuclei.always")
	local hostname = stdnse.get_hostname(host)
	
	if     port.number == 80 then
		handle = io.popen("nuclei -u http://" .. hostname .. " -nc -silent -etags intrusive -rl 30 -rlm 1000 -bs 8 -c 8")
	elseif port.number == 443 then 
		handle = io.popen("nuclei -u https://" .. hostname .. " -nc -silent -etags intrusive -rl 30 -rlm 1000 -bs 8 -c 8")
	elseif always == "yes" then      
		handle = io.popen("nuclei -u " .. hostname .. " -nc -silent -etags intrusive -rl 30 -rlm 1000 -bs 8 -c 8")
	end 
	local result = handle:read("*a") 
	handle:close()
	return result
end 
```
I've also tried the full path (/usr/local/bin/nuclei) to Nuclei, but same result

The Nmap command:
`nmap -script=nuclei.nse -p80,443 -T2 IPADDRESS`

**Version info:**
Ubuntu 20.04.4 LTS focal

Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1 libssh2-1.8.0 libz-1.2.11 libpcre-8.39 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Comment by goarblt** [comment]
hello
https://www.evil.com/
