### ISSUE TITLE
-o option not as expected

### ISSUE THREAD

**Issue by PhilZ-cwm6** [nmap/nmap#2458]
**Describe the bug**
`nmap -oSomefile` will output to `Somefile`

**To Reproduce**
Always

**Expected behavior**
Only `-oN Somefile`, `-oX Somefile`... should output to `Somefile`

**Version info (please complete the following information):**
 - OS: FreeBSD 12
 - Output of `nmap --version`:
 
```
Nmap version 7.91 ( https://nmap.org )
Platform: amd64-portbld-freebsd12.3
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1l-freebsd nmap-libssh2-1.9.0 libz-1.2.11 libpcre-8.45 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select
```

**Additional context**
none

**Comment by nnposter** [comment]
I cannot quite reproduce your case:
```
./nmap -oSomefile 192.168.1.1
You are using a deprecated option in a dangerous way. Did you mean: -oS omefile
QUITTING!
```
I am guessing that you have really used a different filename than `Somefile`. More specifically, the filename likely did not start with N, A, X, G or S. If you were to use let's say:
```
./nmap -oOtherfile 192.168.1.1
```
then the output will be indeed written to `Otherfile`. The reason is that option `-oN` used to be just `-o` and Nmap maintains this backward compatibility. If you were to run the same command with `-d`, you would get:
```
Warning: The -o option is deprecated. Please use -oN
```

**Comment by PhilZ-cwm6** [comment]
> I cannot quite reproduce your case:
> 
> ```
> ./nmap -oSomefile 192.168.1.1
> You are using a deprecated option in a dangerous way. Did you mean: -oS omefile
> QUITTING!
> ```
> 
> I am guessing that you have really used a different filename than `Somefile`. More specifically, the filename likely did not start with N, A, X, G or S. If you were to use let's say:
> 
> ```
> ./nmap -oOtherfile 192.168.1.1
> ```
> 
> then the output will be indeed written to `Otherfile`. The reason is that option `-oN` used to be just `-o` and Nmap maintains this backward compatibility. If you were to run the same command with `-d`, you would get:
> 
> ```
> Warning: The -o option is deprecated. Please use -oN
> ```

Thank you, in fact, I used `-ojN` for internal testing on a white listing script that excluded pattern `-o. ` to avoid code injection

I will try `-d` in addition and give a feedback before closing the issue

**Comment by PhilZ-cwm6** [comment]
thank you, `-d` fixed the issue
Best regards

**Comment by goarblt** [comment]
hello
https://www.evil.com/
