### ISSUE TITLE
Add 'dhcp-client-identifier' argument option to dhcp-discover/broadcast-dhcp-discover script

### ISSUE THREAD

**Issue by ascheucher** [nmap/nmap#2462]
I am trying to test a DHCP server to see if a specific _dhcp-client-identifier_ receives the correct IP address assignment.

Would it be possible to add a command line argument option to allow a _dhcp-client-identifier_ to be specified?

e.g. `nmap -sU -p 67 --script=dhcp-discover --script-args dhcp-discover.dhcp-client-identifier=host-type-a-232`

P.S.: This is a shameless copy of this request for a related enhancement: https://github.com/nmap/nmap/issues/1838 implemented by [nnposter](https://github.com/nnposter)
         I hope I and other interest users are as lucky. :)

Thanks in advance.

Regards,
Andreas

**Comment by nnposter** [comment]
This looks fairly straightforward.

Have you given any thought how the value should be specified? As an example, for FQDNs, the actual value in the option should be prepended with \x00, which in turn makes it unfriendly for passing the actual value via `--script-args`. This could be of course resolved by adding the hardware type prefix automatically. On the other hand, a different user might desire to have full control over the value, including the hardware type.

I am thinking of having *two* parameters, one for a simple case, where the hardware type of 0 is assumed, and one in hex, which is used without further decoration. In other words, `clientid=abc` would be equivalent to `clientid-hex=00:61:62:63`.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by nnposter** [comment]
Please provide feedback on the proposal above and also your specific use case, including the type of client identifier you would be using.

**Comment by ascheucher** [comment]
Hi, sorry for the late answer. Too much going on...

I am far from a specialist in the area and your suggestion sounds like your knowledge is much deeper. 

Your suggestion with the simple `clientid` and the `clientid-hex` sounds great to me! I just guess, it will need it documented the way you describe it here, as I didn't even know about hardware types at all, till I googled further to figure out what you are talking about. :) I guess I am not alone here...

Thanks for considering to implement the feature!

**Comment by nnposter** [comment]
Can you elaborate on your specific use case? Also, would you be in a position to test the code?

**Comment by ascheucher** [comment]
Of course: we have some Mac book pros in our network. For wired network we use USB to Ethernet  adapters. As the adapters all look the same, it’s easy to accidentally use a wrong one. Hence, I would prefer to set a client identifier for them and avoid to use the MAC address, as this would Link to the adapter and not to the computer.

I can test the code for sure. I two MBPs and 5 adapters at hand.

**Comment by nnposter** [comment]
Please grab the two updated scripts from PR #2468 and report back.

**Comment by ascheucher** [comment]
I will test it in the the coming days... thanks so far.

**Comment by nnposter** [comment]
Issue abandoned
