### ISSUE TITLE
Disable certain features through config / at build time?

### ISSUE THREAD

**Issue by 33Fraise33** [nmap/nmap#2467]
**Describe the current behavior**
We are providing certain users from our company with a jumphost with limited priviliges (ping, traceroute, nmap,..) They are able to escape the /bin/rbash shell to /bin/bash through the provided option to download and execute lua scripts. 
![image](https://user-images.githubusercontent.com/6802744/164646748-13acb597-9053-46f0-8f84-8a669ae92dbc.png)

**Expected behavior**
Is it possible to disable certain features or only allow certain options? We only want to have the port scan functionality. Is there a specific way this is possible or are there any plans for this?

**Comment by nnposter** [comment]
Please use `./configure --without-liblua`
