### ISSUE TITLE
NMAP 7.92 with npcap-1.50 installation (instead of 1.60)

### ISSUE THREAD

**Issue by luistorres21es** [nmap/nmap#2469]
Hello Team

I installed Nmap Win32 latest version (7.92) which still includes npcap-1.50 for installation.

After installed both, then I installed npcap 1.60 separately. When I run a nmap scan, the following issue appears:

**Error compiling our pcap filter: expression rejects all packets**

I need npcap 1.60 because it fixed some issues with Ndismedia interfaces (in npcap 1.50 version)

Nmap version 7.92 should include npcap 1.60 version embedded for installation. 

Your support is required, thanks in advance

**Comment by fyodor** [comment]
Hi.  We will include the then-latest version of Npcap with the next version of Nmap.  But you are welcome and encouraged to upgrade to Npcap 1.60 along with Nmap.  The most efficient method is to install Npcap 1.60 first so Nmap 1.50 is never installed in the first place.  But you can install Npcap later too.

**Comment by luistorres21es** [comment]
Thanks for your reply

As stated before, I installed npcap 1.60 and nmap 7.92. When trying to perform a scan, the following issue appears:

**Error compiling our pcap filter: expression rejects all packets**

What should I do to fix this error?

Thanks in advance
