### ISSUE TITLE
No NSE status reports, and taking many hours.

### ISSUE THREAD

**Issue by GlitchTime** [nmap/nmap#2472]
**Describe the bug**
I'm not sure if this is a bug, but I'm scanning 64 hosts and it has gotten to the NSE stage and it has been on the same screen for over 3 hours now and there have been no status reports from the program which I know has been a problem in the past because of issue #701 and I know that this's in the [FAQ](https://secwiki.org/w/FAQ_long_running) but it was quite vague.
**To Reproduce**
I'm scanning a VERY BIG RANGE I used the command `nmap -p 1-65535 -T4 -A -v ***.**.0.0/16` the stars are because I don't want to tell you what range I'm scanning.
**Expected behavior**
The expected behavior is that it gives status reports or has finished by now.
**Version info (please complete the following information):**
 - OS: Windows 10
 - Output of `nmap --version`: 
 
Nmap version 7.92 ( https://nmap.org )

Platform: i686-pc-windows-windows

Compiled with: nmap-liblua-5.3.5 openssl-1.1.1k nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-1.50 nmap-libdnet-1.12 ipv6

Compiled without:

Available nsock engines: iocp poll select

 - Output of `nmap --iflist`:

Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-30 14:48 Eastern Daylight Time

************************INTERFACES************************

DEV  (SHORT) IP/MASK                      TYPE     UP   MTU  MAC

eth0 (eth0)  fe80::65ab:212b:b8b9:b319/64 ethernet up   1500 18:C0:4D:42:25:CC

eth0 (eth0)  192.168.1.153/24             ethernet up   1500 18:C0:4D:42:25:CC

eth1 (eth1)  fe80::e1f2:b05b:efc3:49c5/64 ethernet down 1500 F8:AC:65:AB:BD:1A

eth1 (eth1)  169.254.73.197/16            ethernet down 1500 F8:AC:65:AB:BD:1A

eth2 (eth2)  fe80::580:8f55:c47f:4ede/64  ethernet down 1500 FA:AC:65:AB:BD:19

eth2 (eth2)  169.254.78.222/16            ethernet down 1500 FA:AC:65:AB:BD:19

eth3 (eth3)  fe80::c8fa:e010:6148:de88/64 ethernet down 1500 F8:AC:65:AB:BD:1D

eth3 (eth3)  169.254.222.136/16           ethernet down 1500 F8:AC:65:AB:BD:1D

eth4 (eth4)  fe80::6824:4600:2b03:777/64  ethernet down 1500 F8:AC:65:AB:BD:19

eth4 (eth4)  169.254.7.119/16             ethernet down 1500 F8:AC:65:AB:BD:19

lo0  (lo0)   ::1/128                      loopback up   -1

lo0  (lo0)   127.0.0.1/8                  loopback up   -1

DEV    WINDEVICE

eth0   \Device\NPF_{40A761B8-D9AA-4BF3-97E4-62E9D6BE8771}

eth0   \Device\NPF_{40A761B8-D9AA-4BF3-97E4-62E9D6BE8771}

eth1   \Device\NPF_{A5A6AE69-2F56-4D7B-AB12-0A35E7889363}

eth1   \Device\NPF_{A5A6AE69-2F56-4D7B-AB12-0A35E7889363}

eth2   \Device\NPF_{D9CEBD8B-3304-496A-99CF-424E62954FB5}

eth2   \Device\NPF_{D9CEBD8B-3304-496A-99CF-424E62954FB5}

eth3   \Device\NPF_{5D9141C3-6800-4067-B264-6E3653880E47}

eth3   \Device\NPF_{5D9141C3-6800-4067-B264-6E3653880E47}

eth4   \Device\NPF_{0B6743FF-A3CB-48E3-8200-0751AE0BAD76}

eth4   \Device\NPF_{0B6743FF-A3CB-48E3-8200-0751AE0BAD76}

lo0    \Device\NPF_Loopback

lo0    \Device\NPF_Loopback

<none> \Device\NPF_{F60281D5-4A3E-4D9E-9837-8D8706C1844A}

<none> \Device\NPF_{FA678782-6DE6-4B82-954D-D551E15406E0}

<none> \Device\NPF_{73D95E48-85FE-4F90-B8F8-2C939582BF69}

**************************ROUTES**************************

DST/MASK                      DEV  METRIC GATEWAY

255.255.255.255/32            eth2 281

255.255.255.255/32            eth1 281

192.168.1.153/32              eth0 281

255.255.255.255/32            eth0 281

192.168.1.255/32              eth0 281

255.255.255.255/32            eth3 321

255.255.255.255/32            eth4 326

127.0.0.1/32                  lo0  331

127.255.255.255/32            lo0  331

255.255.255.255/32            lo0  331

192.168.1.0/24                eth0 281

127.0.0.0/8                   lo0  331

224.0.0.0/4                   eth2 281

224.0.0.0/4                   eth1 281

224.0.0.0/4                   eth0 281

224.0.0.0/4                   eth3 321

224.0.0.0/4                   eth4 326

224.0.0.0/4                   lo0  331

0.0.0.0/0                     eth0 25     192.168.1.1

fe80::65ab:212b:b8b9:b319/128 eth0 281

fe80::e1f2:b05b:efc3:49c5/128 eth1 281

fe80::580:8f55:c47f:4ede/128  eth2 281

fe80::c8fa:e010:6148:de88/128 eth3 321

fe80::6824:4600:2b03:777/128  eth4 326

::1/128                       lo0  331

fe80::/64                     eth0 281

fe80::/64                     eth2 281

fe80::/64                     eth1 281

fe80::/64                     eth3 321

fe80::/64                     eth4 326

ff00::/8                      eth2 281

ff00::/8                      eth0 281

ff00::/8                      eth1 281

ff00::/8                      eth3 321

ff00::/8                      eth4 326

ff00::/8                      lo0  331

**Comment by GlitchTime** [comment]
Update, after 5 hours it finished, but for some reason some reason there was no status reports throughout the full 5 hours.

**Comment by dmiller-nmap** [comment]
Since the scan did eventually finish, this is not a bug as such. We do have feature requests in for improved timing estimates, as you noted. I can also suggest that if you want regular status updates, you can use the `--stats-every` option, e.g. `--stats-every 1m` to get a status line at least once per minute. Additionally, your scan is requesting a lot of work to be done: 65K ports on 65K target IP addresses, plus OS detection and traceroute for all discovered targets, and version scan and NSE scripts run against all open ports. Consider reducing the scan scope or using other timing options to improve scan speed.
