### ISSUE TITLE
smb NSE scripts with password using special characters

### ISSUE THREAD

**Issue by crlsgms** [nmap/nmap#2474]
Hello Everyone
First I made a [Question on the mail listing first](https://seclists.org/nmap-dev/2021/q4/1), but didn't found a safe solution yet for this issue. Using NMAP scans with smb NSE scripts, and with some special characters being used that could be interpreted as breaks, the scan will not run.

**To Reproduce**
For example, this scan:
```
nmap -PE -PS80,69,443,3389,8080 -PP -PA21 -PU161,137-139,123 -sS -sU -sV -O
-d2 -vv -pT:0-65535,U:137,161 --script
nbstat,snmp-interfaces,snmp-processes,smb-enum-shares,smb-os-discovery,smb2-vuln-uptime,broadcast-ping,snmp-sysdescr
--open --stats-every 5s --max-retries 1 --script-args
smbtype='v2',smbdomain='WORKGROUP',smbbasic='true',smbsign='ignore',smbpassword=\""'1'1'1'#RC|WNa,#fW/z1@dd'1'1''"\",smbusername='user',smb2-vuln-uptime.skip-os=true,creds.snmp=public
--disable-arp-ping --min-rate=600 --max-rate=10000 -oX
report_labwin7_password_escapes_d2x.xml 10.10.5.5
```

where the correct password will be: "'1'1'1'#RC|WNa,#fW/z1@dd'1'1''"

chosen on purpose to have lots of quotes and shell break characters to
validate the scan itself.

**Expected behavior**
The scan would ran with whatever password being used, with all cases and complexities, charecters and so on, without breaking the full command being used

**Version info**
 - OS: Ubuntu Linux, whatever version, tried with some versions of nmap including the latest version 7.92
 - Output of `nmap --version`:
   - Nmap version 7.92 ( https://nmap.org )
  Platform: x86_64-unknown-linux-gnu
  Compiled with: nmap-liblua-5.3.5 openssl-1.1.1 libssh2-1.8.0 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
  Compiled without:
  Available nsock engines: epoll poll select
 - Output of `nmap --iflist`
 ```
- Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-06 16:02 UTC
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                     TYPE     UP MTU   MAC
lo      (lo)      127.0.0.1/8                 loopback up 65536
lo      (lo)      ::1/128                     loopback up 65536
docker0 (docker0) 192.168.3.9/24             ethernet up 1500  02:47:C2:BF:77:70
eth0    (eth0)    10.10.29.6/24              ethernet up 1500  07:50:56:FA:55:E1

**************************ROUTES**************************
DST/MASK                     DEV     METRIC GATEWAY
10.10.10.99/32               eth1    0      10.10.19.1
10.10.10.0/24                eth1    0
10.10.20.0/24                eth0    0
192.168.35.0/24              docker0 0
169.254.0.0/16               eth1    1000
0.0.0.0/0                    eth0    0      10.10.29.1
::1/128                      lo      0
fe80::250:56ff:fefa:56e1/128 eth0    0
::1/128                      lo      256
fe80::/64                    eth0    256
ff00::/8                     eth0    256
```

**Additional context**
Most of the ips and mac address were changed for security purposes

Some information I found on the lists are quite old:

https://dev.nmap.narkive.com/mbZVDb1B/special-characters-in-script-args
https://seclists.org/nmap-dev/2009/q2/393

that using both \"pasword\" or "'password'" would be parsed correctly to
lua/nse script, but considering a wide range of passwords with special
characters I wanted to know if there is a "silver bullet" to have this
content passed correctly to the scripts, or even a more smart way to send
this info, using a script-args file, joining arguments into a vector...

At some point I will send all the smb parameters to the scan coming from a
.php application, where I store the user / credentials / workgroup / domain
and send them to the parameters all with the same "escape" character, I
tried with " ", ' ' and \"  \", and with -d3 on the scan I can see that the
parameters with quotes are parsed on lua to get only the content, but in
same cases inside quotes are discarded on the password field.

**Comment by nnposter** [comment]
The following works for Bash:
`smbpassword=$'\'"\\\'1\\\'1\\\'1\\\'#RC|WNa,#fW/z1@dd\\\'1\\\'1\\\'\\\'"\''`

The idea behind this is:
1. The password is wrapped in single quotes, to tell Nmap parser where the password ends.
2. All existing single quotes need to be escaped with a backslash.
3. The result is wrapped in single quotes so that Bash preserves the existing single quotes.
4. All existing single quotes and backslashes need to be escaped with a backslash, again.
5. The leading `$'` construct facilitates the escaping of single quotes in Bash.

You can save yourself most of the chore by using `--script-args-file`, removing the need to deal with Bash quotes.

Here is an example:
```
$ nmap -p445 --script smb-enum-shares --script-args smbusername=user,smbpassword=$'\'"\\\'1\\\'1\\\'1\\\'#RC|WNa,#fW/z1@dd\\\'1\\\'1\\\'\\\'"\'' 10.10.10.10
Starting Nmap 7.92SVN ( https://nmap.org ) at 2022-05-06 15:07 MDT
Nmap scan report for 10.10.10.10
Host is up (0.00051s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds
MAC Address: 00:0C:29:04:7E:5F (VMware)

Host script results:
| smb-enum-shares: 
|   account_used: user
|   \\10.10.10.10\ADMIN$: 
|     Type: STYPE_DISKTREE_HIDDEN
|     Comment: Remote Admin
|     Anonymous access: <none>
|     Current user access: <none>
|   \\10.10.10.10\Alice: 
|     Type: STYPE_DISKTREE
|     Comment: Alice's squirrel stash
|     Anonymous access: <none>
|     Current user access: READ
|   \\10.10.10.10\Bob: 
|     Type: STYPE_DISKTREE
|     Comment: Bob's tobacco pouch
|     Anonymous access: <none>
|     Current user access: READ
|   \\10.10.10.10\C$: 
|     Type: STYPE_DISKTREE_HIDDEN
|     Comment: Default share
|     Anonymous access: <none>
|     Current user access: <none>
|   \\10.10.10.10\IPC$: 
|     Type: STYPE_IPC_HIDDEN
|     Comment: Remote IPC
|     Anonymous access: READ
|     Current user access: READ/WRITE
|   \\10.10.10.10\Users: 
|     Type: STYPE_DISKTREE
|     Comment: 
|     Anonymous access: <none>
|_    Current user access: READ

Nmap done: 1 IP address (1 host up) scanned in 0.82 seconds
```

**Comment by crlsgms** [comment]
Thank you @nnposter for the info, will simulate here if it suits our purpose, was trying only to use files as the last resources so we would not need more overhead on our project to protect / encrypt / remove the files since the passwords are not always the same. 

After the simulation and tests will come back to post the results, so anyone with similar problems can use as reference
