### ISSUE TITLE
-u didn't work

### ISSUE THREAD

**Issue by walkerxk** [nmap/nmap#2481]
**Describe the bug**
-u didn't work
**To Reproduce**
Steps to reproduce the behavior, including command-line options.
/usr/local/bin/ncat -i1 -vw1 1.1.1.1 53 #sent a tcp packet
/usr/local/bin/ncat -i1 -vw1 1.1.1.1 53 -u #didn't sent a udp packet
**Expected behavior**
A clear and concise description of what you expected to happen. For issues related to EOF handling (socket disconnect), see [our document on EOF behavior in Ncat](https://secwiki.org/w/Ncat/EOF_behavior).
-u sent a udp packet
**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `ncat --version`:
ubuntu
Ncat: Version 7.92SVN ( https://nmap.org/ncat ) build from newest source in git
**Additional context**
Add any other context about the problem here, such as software version of the service you are connecting Ncat to.
![image](https://user-images.githubusercontent.com/3411710/170404715-f496562b-75ce-4eb5-a4e5-9c38ea31edae.png)
![image](https://user-images.githubusercontent.com/3411710/170404757-15b69dfb-030b-4a5e-9c2a-cea0cf42b258.png)
dig +short www.nmap.org @1.1.1.1 sent udp packet

**Comment by nnposter** [comment]
Your screenshots do not show that you are feeding Ncat with any data for sending. UDP does not perform any initial handshake so Ncat will not generate any traffic unless you give it some payload.

**Comment by nnposter** [comment]
Yes, of course:
```
echo -n X | ncat -u 1.1.1.1 53
```

**Comment by walkerxk** [comment]
I mean if i didn't feed Ncat with any data for sending, Ncat sent any char like netcat-openbsd did?
Most people (like me) didn't realize you should feed Ncat when you use udp protocol.

**Comment by walkerxk** [comment]
ok, thanks.
