### ISSUE TITLE
Nmap segfaults with Openssl 3 legacy provider enabled

### ISSUE THREAD

**Issue by kulikjak** [nmap/nmap#2482]
**Describe the bug**
When Nmap is compiled with OpenSSL 3, there are several tests that fail with
`./nselib/smbauth.lua:377: OpenSSL error 50856204 in digital envelope routines: function (null): unsupported`.
This is expected considering that in OpenSSL 3 some cyphers (like **md5** used in this case) are part of the legacy provider that is not enabled by default. What is not expected is that when I enable the legacy provider in the openssl global configuration (via openssl.cnf), all tests pass and nmap segfaults during cleanup.

It's not just the test suite, the same thing happens e.g. with:
`nmap -A scanme.nmap.org`

The core contains the following stack:
```gdb
nmap:core> ::stack
libc.so.1`rw_write_held+0x23()
libc.so.1`rw_rdlock_impl+0xfe()
libc.so.1`pthread_rwlock_rdlock+0xc()
libcrypto.so.3`CRYPTO_THREAD_read_lock+9()
libcrypto.so.3`ossl_lib_ctx_get_data+0x2c()
libcrypto.so.3`ossl_provider_deregister_child_cb+0x29()
libcrypto.so.3`OSSL_LIB_CTX_free+0x50()
legacy.so`legacy_teardown+0x1a()
libcrypto.so.3`ossl_provider_free+0xbd()
libcrypto.so.3`evp_cipher_free_int+0x2d()
libssl.so.3`SSL_CTX_free+0x21c()
nsock_pool_delete+0x584()
_ZL7gc_poolP9lua_State+0x23()
luaD_precall+0x375()
luaD_callnoyield+0x42()
luaD_rawrunprotected+0x51()
luaD_pcall+0x43()
GCTM+0xfd()
luaC_freeallobjects+0x82()
close_state+0x25()
_Z9close_nsev+0x15()
_ZN7NmapOpsD1Ev+0x25c()
libc.so.1`_exithandle+0x74()
libc.so.1`exit+0x11()
_start+0x4e()
```
I was not able to reproduce this outside of Nmap with something simpler. I just know that the same command with legacy provider disabled works as expected.

**To Reproduce**
Compile Nmap with the OpenSSL 3 and than run e.g. this:
`nmap -A scanme.nmap.org`

**Version info (please complete the following information):**
 - OS: Oracle Solaris 11.4
    - I didn't test this on other OSes as I don't have access to anything that ships OpenSSL 3...
 - Output of `nmap --version`:

Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-solaris2.11
Compiled with: nmap-liblua-5.3.5 openssl-3.0.2 libssh2-1.10.0 libz-1.2.12 libpcre-8.45 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: poll select

**Additional context**

I am not 100% sure that this is Nmap issue, but so far I didn't see similar crash in other programs compiled with OpenSSL 3 when legacy provider is enabled.

**Comment by kulikjak** [comment]
So I tried looking into this again with the latest OpenSSL 3.0.5, and while the call stack changed a little bit, the same issue is still there.
```gdb
> ::stack
libc.so.1`rw_write_held+0x10()
libc.so.1`rw_rdlock_impl+0xf0()
libcrypto.so.3`CRYPTO_THREAD_read_lock+4()
libcrypto.so.3`ossl_lib_ctx_get_data+0x20()
libcrypto.so.3`ossl_provider_deregister_child_cb+0x20()
libcrypto.so.3`ossl_provider_deinit_child+0x34()
libcrypto.so.3`OSSL_LIB_CTX_free+0x58()
legacy.so`legacy_teardown+0xc()
libcrypto.so.3`ossl_provider_teardown+0x20()
libcrypto.so.3`ossl_provider_free+0xd8()
libcrypto.so.3`evp_cipher_free_int+0x30()
libssl.so.3`SSL_CTX_free+0x1b8()
nsock_pool_delete+0x4ac()
_ZL7gc_poolP9lua_State+0x2c()
luaD_precall+0x200()
luaD_callnoyield+0x44()
luaD_rawrunprotected+0x48()
luaD_pcall+0x30()
GCTM+0x10c()
luaC_freeallobjects+0x64()
close_state+0x14()
_Z9close_nsev+0x28()
_ZN7NmapOpsD1Ev+0x3d0()
libc.so.1`_exithandle+0x7c()
libc.so.1`exit+4()
_start+0x6c()
```
Temporary workaround I found is to remove the `SSL_CTX_free(nsp->sslctx);` in qnsock_pool.c`. This leaks memory, but it's in the cleanup that is called when Nmap is ending, so IMHO not really that big of a deal. But still no fix :disappointed:.

I see that Fedora already delivers the latest Nmap with OpenSSL 3, so unless they are hitting this themselves (which I doubt), this seems like it doesn't affect everybody.

Should you have an idea how to investigate this further, please let me know. I will most likely ask on OpenSSL github as well.

**Comment by kulikjak** [comment]
I have an update regarding this (and big thanks for helping goes to @mattcaswell (in the OpenSSL issue)).

The problem is that the `NmapOps::~NmapOps()` called from exit handler (that eventually calls `SSL_CTX_free` and segfaults) runs after OpenSSL was already cleaned up with it's own exit handler.

This is not Solaris specific after all as exit handlers are called in the LIFO order on both Solaris and Linux. To verify that I tested the same thing on Fedora VM and it indeed segfaults as well.

The OpenSSL issue mentions two potential solutions:
1. Nmap arranges its code such that `SSL_CTX_free()` is called earlier (outside of the exit handler).
2. Nmap calls `OPENSSL_init_crypto` explicitly using the `OPENSSL_INIT_NO_ATEXIT` option (_must_ be the first call to any OpenSSL function). This means that `OPENSSL_cleanup` will not automatically be invoked on process exit. Instead Nmap must call it explicitly (and _after_ `SSL_CTX_free` has been called).

I tried adding `OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);` at the beginning of `ssl_init_helper` (`nsock_ssl.c`)   and `OPENSSL_cleanup();` to `nsock_pool_delete()` (right after the problematic `SSL_CTX_free()` call) and the issue is gone, though I am not sure whether this is the best way to do that as there might be other places where the program exits, there are other places where SSL is being initialized as well and automatic cleanup in the exit handler seems like a nice thing. That said, `NmapOps` is initialized before main even starts, so I don't think that forcing the OpenSSL exit handler before it is possible without bigger changes.

**Comment by dmiller-nmap** [comment]
Please check out the latest Nmap code and see if the issue still presents. The approach I took was to register an atexit handler with `OPENSSL_atexit()` that will set a global (static) state variable. Our cleanup code (`nsock_pool_delete()` calling a new function, `nsock_ssl_cleanup()`) will check this state variable to determine if it should call `SSL_CTX_free()`, which it will only do if the atexit handler has not been called. We've also added code to enable the legacy provider by default (tested with OpenSSL 3.0.5 no-deprecated).

**Comment by mattcaswell** [comment]
> which it will only do if the atexit handler has not been called.

This will presumably lead to mem leaks if OpenSSL library is already cleaned up by the time nmap's cleanup code is called. This is not necessarily a problem since we're exiting anyway and the OS will reclaim any allocated resources. But it does mean that tools like asan/valgrind etc will report leaks.

**Comment by kulikjak** [comment]
Thanks for the update, I will try it the first thing tomorrow morning.

I am just wondering; since the OpenSSL exit handler is AFAICT always called before the Nmap one (making the SSL context always leak), whether just removing the `SSL_CTX_free` would not do the same thing?

**Comment by kulikjak** [comment]
So I just tested it with the latest master ([1f50e82](https://github.com/nmap/nmap/commit/1f50e82dd2bd89b6d25d0421d5022e1a5983a7ef)) and it doesn't segfault anymore (with context never being cleared).

**Comment by dmiller-nmap** [comment]
@kulikjak Thanks for the confirmation. Closing this as resolved.
