### ISSUE TITLE
nmap is not listing the correct cipher suites

### ISSUE THREAD

**Issue by madhavanjayaram** [nmap/nmap#2483]
I am using nmap 7.92

nmap -p 443 --unprivileged --script ssl-enum-ciphers <FQDN of server>

I have configured the following ciphers in the server (windows 2012 R2 standard) via gpedit.msc

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

But, the nmap scan on port 443 of the server lists only the below ciphers

  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
  TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
  TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
  TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
  TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A

How can this be resolved?

**Comment by nnposter** [comment]
Script `ssl-enum-ciphers` is able to recognize `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`. You might want to validate your configuration with other tools, such as OpenSSL:
```
openssl s_client -connect yourserver:443 -cipher ECDHE-RSA-AES256-GCM-SHA384
```
and make sure that you are not suffering from congested network or other packet loss.

**Comment by nnposter** [comment]
Apparently resolved
