### ISSUE TITLE
Feature Request: variable tcp window size

### ISSUE THREAD

**Issue by dksslq** [nmap/nmap#2491]
People who care will care about [such](https://github.com/nmap/nmap/blob/master/tcpip.cc#L665) below toys, and something interesting will happen.

``` c
  if (window)
    tcp->th_win = htons(window);
  else
    tcp->th_win = htons(1024); /* Who cares */
```

I propose adding some command line options to allow users to control TCP window size.

**Comment by dksslq** [comment]
# bug

**Comment by fyodor** [comment]
Well the function you're pointing to already has an option for setting the window size.  It only uses 1024 if that option isn't specified.  Regarding Nmap as a whole, can you describe more of your use cases for wanting to set the window size while scanning?  If you only want to send individual packets with arbitrary window sizes for testing purposes, our Nping program (included with Nmap) supports the --win option for this.

I'm closing this for now, but we can re-open if some compelling reasons for adding this to Nmap can be found.

**Comment by dksslq** [comment]
For flexibility of the nmap port scanner.

Using fixed 1024 win while scanning is more detectable and its look like hardcoded and not so good.
Consider move the `nping --win` function to the nmap or add a random window size switch?

**Comment by dksslq** [comment]
> For flexibility of the nmap port scanner.
> 
> Using fixed 1024 win while scanning is more detectable and its look like hardcoded and not so good. Consider move the `nping --win` function to the nmap or add a random window size switch?

For flexibility of the nmap port scanner.

Using fixed 1024 win while scanning is more detectable and its look like hardcoded and not so good.
Consider move the `nping --win` function to the nmap or add a random window size switch?

**Comment by dksslq** [comment]
> Well the function you're pointing to already has an option for setting the window size. It only uses 1024 if that option isn't specified. Regarding Nmap as a whole, can you describe more of your use cases for wanting to set the window size while scanning? If you only want to send individual packets with arbitrary window sizes for testing purposes, our Nping program (included with Nmap) supports the --win option for this.
> 
> I'm closing this for now, but we can re-open if some compelling reasons for adding this to Nmap can be found.

For flexibility of the nmap port scanner.

Using fixed 1024 win while scanning is more detectable and its look like hardcoded and not so good.
Consider move the nping --win function to the nmap or add a random window size switch?
