### ISSUE TITLE
lastest nmap installed bug

### ISSUE THREAD

**Issue by bettswang** [nmap/nmap#2493]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
I want to install the lastest nmap rpm package on linux ( include fedora35\Centos8), but it's failed. 

**To Reproduce**
 wget https://nmap.org/dist/nmap-7.92-1.x86_64.rpm
 rpm -ivh nmap-7.92-1.x86_64.rpm

**Expected behavior**
installed sucessfully

**Version info (please complete the following information):**
 - OS: centos8 \ fedora35
 - Output of `nmap --version`: 7.92
 - Output of `nmap --iflist`

**Additional context**
Add any other context about the problem here, such as special network type.

```
[root@fedora35 ~]# ls
anaconda-ks.cfg  nmap-7.92-1.x86_64.rpm
[root@fedora35 ~]# rpm -ivh nmap-7.92-1.x86_64.rpm
error: Failed dependencies:
        python >= 2.4 is needed by nmap-2:7.92-1.x86_64
[root@fedora35 ~]# python2 --version
Python 2.7.18
[root@fedora35 ~]# python3 --version
Python 3.10.0
```

**Comment by leleobhz** [comment]
I confirm the issue when installing via DNF (using URL):

```
[root@doca01 ~]# LANG=C dnf install https://nmap.org/dist/nmap-7.92-1.x86_64.rpm --skip-broken
Updating Subscription Management repositories.
Last metadata expiration check: 3:19:39 ago on Mon Jun 20 06:07:52 2022.
nmap-7.92-1.x86_64.rpm                                                                                                                   1.6 MB/s | 7.1 MB     00:04    
Dependencies resolved.
Nothing to do.
Complete!
[root@doca01 ~]# 
```

**Comment by bettswang** [comment]
what's problem? "--skip-broken" ignores the mistakes ? Are there any wrong with offical install guide ?

**Comment by loneicewolf** [comment]
tried and still problematic; will see if I can test different things and come back

**Comment by luminous706** [comment]
Any update on this? I have the same problem... the nmap package on Alma Linux 8 is old, I wish I could get the RPM provided, but here's what I get:

```
dnf localinstall https://nmap.org/dist/nmap-7.80-1.x86_64.rpm
Last metadata expiration check: 1:38:03 ago on Thu 03 Nov 2022 05:28:58 PM EDT.
nmap-7.80-1.x86_64.rpm                                                                                                                                                          1.7 MB/s | 6.8 MB     00:03
Error:
 Problem: conflicting requests
  - nothing provides python >= 2.4 needed by nmap-2:7.80-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by dmiller-nmap** [comment]
This is because Zenmap 7.93 and earlier requires Python 2. Future releases will require Python 3, which will ensure the package dependencies can be met on current systems. See #1176.

**Comment by thomastt123** [comment]
Is this issue resolved?

Here python 2.7.18 is installed and still getting the error message on a kali vm:

└─$ rpm -vhU https://nmap.org/dist/nmap-7.80-1.x86_64.rpm                                                               
rpm: RPM should not be used directly install RPM packages, use Alien instead!                                           
rpm: However assuming you know what you are doing...                                                                    
Retrieving https://nmap.org/dist/nmap-7.80-1.x86_64.rpm                                                                 
error: Failed dependencies:                                                                                                     
python >= 2.4 is needed by nmap-2:7.80-1.x86_64

**Comment by fyodor** [comment]
Thanks for the update, @thomastt123 .  We're planning a new Nmap release for this month which will use Python3 instead.  That should resolve this issue.
