### ISSUE TITLE
 `--exclude-ports` option doesn't work properly

### ISSUE THREAD

**Issue by simonedimaria** [nmap/nmap#2495]
**Describe the bug**
The `--exclude-ports` option doesn't work properly: sometimes it ignores the N port but doesn't discover the other open ports too.

**Steps To Reproduce**
Example excluding port 80:
First scan: `nmap xxx.xxx.xxx.0/24 --open -oN output.txt`
Second scan: `nmap xxx.xxx.xxx.0/24 --open --exclude-ports 80 -oN output.txt`

**Expected behaviour**
Find all the open ports for each device in the network, excluding port 80.
But as you can see in this foto:
![nmap](https://user-images.githubusercontent.com/12881861/175380227-4d65a878-a2d7-45bc-9b79-710a91ab77b1.png)
On the left the first scan.
On the right the second scan. In the second scan output, the device xxx.xxx.xxx.38 didn't get scanned at all.

**Version info (please complete the following information):**
 - OS: Linux 5.17.0-kali3-amd64 #1 SMP PREEMPT Debian 5.17.11-1kali1 (2022-05-30) x86_64 GNU/Linux
 - Nmap version 7.92

**Comment by nnposter** [comment]
There could be a rational explanation for these results. A host will not get port-scanned if it is not detected as up during the initial host discovery phase, which consists of the following:

* ARP ping (obviously applies only for hosts reachable via layer 2)
* ICMP timestamp request
* TCP ports 80 and 443

In your case, it is clear that port 443 is not open and 80 you administratively prohibited. That leaves you with the first two bullets. If ARP does not apply and ICMP is blocked then the host will not get scanned.

Try adding `-PSx` to the command line, where "x" is a port likely open on the target machine, such as -PS8080. Alternatively, use `-Pn` to suppress host discovery together (at the risk of wasting time trying to scan hosts that might not be up or reachable at all).

**Comment by nnposter** [comment]
You are welcome
