### ISSUE TITLE
Arguments are not passed to NSE scripts correctly for Nmap 7.92, Windows platform

### ISSUE THREAD

**Issue by anat0li** [nmap/nmap#2497]
When I try to pass arguments to NSE scripts using the --script-args option, those arguments are inaccessible from the script code, as they should be according to the description in  [https://nmap.org/book/nse-usage.html#nse-args.](url)

Actually whole content of the --script-args option can be seen as a string value at nmap.registry.args[1]. It does not look as if they had been properly parsed to the table with name/value entries, as expected.

**To Reproduce** the issue we can run `mysql-query.nse` script from Nmap\scripts that uses the following arguments:
```
--
-- @args mysql-query.query the query for which to return the results
-- @args mysql-query.username (optional) the username used to authenticate to the database server
-- @args mysql-query.password (optional) the password used to authenticate to the database server
-- @args mysql-query.noheaders do not display column headers (default: false)
--
...
local arg_username  = stdnse.get_script_args(SCRIPT_NAME .. ".username")
local arg_password  = stdnse.get_script_args(SCRIPT_NAME .. ".password") or ""
local arg_query     = stdnse.get_script_args(SCRIPT_NAME .. ".query")
local arg_noheaders = stdnse.get_script_args(SCRIPT_NAME .. ".noheaders") or false
```
The following command can be used to run the script against some MySQL server:

**nmap -dd -sS -p3306 target.com -script mysql-query.nse -script-args='username=user,password=password,query="select version()"'**

The following is a quote from the debug output from the command executed:

```
NSE: Starting mysql-query M:314CBAC against target.com (10.29.39.189:3306).
NSE: [mysql-query M:314CBAC 10.29.39.189:3306] No query was given, aborting ...
NSE: Finished mysql-query M:314CBAC against target.com (10.29.39.189:3306).
```
The script is aborting because the query argument is empty despite the fact it has been passed using the --script-args option.

**Expected behavior**
The same command was executed against the same target with Nmap 7.92 on the Linux platform; and it outputs the expected query result, which is the MySQL server version as below:
```
| mysql-query:
|   version()
|   10.5.2-MariaDB
|
|   Query: select version()
|_  User: user
```

**Version info (please complete the following information):**
 - OS: Windows 10 Enterprise, version 21H2, build 19044.1706
 - Output of `nmap --version`:
 
```
Nmap version 7.92 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1k nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-1.55 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select
```

 - Output of `nmap --iflist`
It does not seem to be relevant to the issue.

**Additional context**
I asked one of my colleagues to test the issue on some VMs available for him, and he got a similar result: Nmap 7.92 fails to pass  arguments to NSE scripts under the Windows platform, but works correctly under the Linux platform, such as `x86_64-redhat-linux-gnu
`

**Comment by nnposter** [comment]
This is expected. Please understand that quoting on Windows works differently than on Linux, so you need to modify your command line accordingly.

Here is a demo of what is wrong with your command line:
```
c:\args>args -dd -sS -p3306 target.com --script mysql-query.nse --script-args='username=user,password=password,query="select version()"'
[0] >args<
[1] >-dd<
[2] >-sS<
[3] >-p3306<
[4] >target.com<
[5] >--script<
[6] >mysql-query.nse<
[7] >--script-args='username=user,password=password,query=select version()'<
```
You see that:

* The single quotes were not processed by the CLI
* The double quotes got stripped off

Now with the single and double quotes swapped:
```
c:\args>args -dd -sS -p3306 target.com --script mysql-query.nse --script-args="username=user,password=password,query='select version()'"
[0] >args<
[1] >-dd<
[2] >-sS<
[3] >-p3306<
[4] >target.com<
[5] >--script<
[6] >mysql-query.nse<
[7] >--script-args=username=user,password=password,query='select version()'<
```
You see that:

* The outer quotes got processed by the CLI
* The inner quotes were preserved, so Nmap knows that the `query` parameter is set to `select version()`
