### ISSUE TITLE
About The Result of a Single Scan

### ISSUE THREAD

**Issue by AuroraHaaash** [nmap/nmap#2501]
Hello, I'm trying to use the "-sV", but it output things like "x services unrecognized despite returning data. If you know the service/version, please submit the following fingerprints at https://nmap.org/cgi-bin/submit.cgi?new-service :"
Actually, I dont want to get these information cuz I want to parse the result in a easy way.
So, is there any way to simply drop these message?

**Comment by bka-dev** [comment]
To parse results, using stdout output might not be the best idea. Check -oA <filename> instead and try to parse either the XML , GNMAP or NMAP files.

Regarding stdout, I'm not aware of any switch that would drop this single message.

**Comment by AuroraHaaash** [comment]
OK, GOT it. My work maybe a Little…WEIRD, and I've already find my way out.But still THANKS A LOT for Reply, it gives me a rather clear idea and can be of much use for my future work.REALLY THANKS.发自我的手机-------- 原始邮件 --------发件人： Bastian Kanbach ***@***.***>日期： 2022年8月26日周五 04:41收件人： nmap/nmap ***@***.***>抄送： AuroraHaaash ***@***.***>, Author ***@***.***>主    题： Re: [nmap/nmap] About The Result of a Single Scan (Issue #2501)
To parse results, using stdout output might not be the best idea. Check -oA  instead and try to parse either the XML , GNMAP or NMAP files.
Regarding stdout, I'm not aware of any switch that would drop this single message.

**Comment by AuroraHaaash** [comment]
OK, GOT it. My work maybe a Little…WEIRD, and somehow I've already find my way out.
But still THANKS A LOT for Your Reply,  gives me another idea and can be of much use for my future work. I'll try it
REALLY THANKS.

**Comment by fyodor** [comment]
It sounds like this issue is resolved. Thanks everyone.
