### ISSUE TITLE
Is there any other way other than e-mail to send the translated document?

### ISSUE THREAD

**Issue by tkmru** [nmap/nmap#2507]
I am trying to improve the Japanese documentation of Nmap. The Japanese documentation has been left as it was at the time of version 5.
I have followed the [guidelines](https://nmap.org/xlate-faq.html) and have tried to email(fyodor@nmap.org) but have not received a reply. Is there a better way to contact them? 
The guidelines state the following:

> Send me the translated XML file. An email attachment or linking to a web page or CVS repository is OK. I'll use my scripts to convert it to a web page to post to Insecure.Org and an Nroff man page.

**Comment by dmiller-nmap** [comment]
Thanks for contributing this! You can also send to dmiller@nmap.com and I can make the necessary conversion as well.

**Comment by tkmru** [comment]
Thank you very much. I just sent you an email with attachments.

**Comment by tkmru** [comment]
@dmiller-nmap I emailed you from Google Workspace 15 days ago, did you receive it?
Is there any problem with email address of Google Workspace?

**Comment by dmiller-nmap** [comment]
Your translation will be committed to SVN and mirrored here shortly. For future reference, pull requests for translation updates can also be made. Only the XML needs to be updated; the `.1` roff files are auto-generated.

**Comment by tkmru** [comment]
@dmiller-nmap Looking at this [link](https://nmap.org/man/ja/man-performance.html), it seems that the HTML does not reflect the XML changes. You can see that the argument is still `<milliseconds>` and has not been changed. Could you please reflect the latest version of XML?
