### ISSUE TITLE
Report every x seconds

### ISSUE THREAD

**Issue by tjt263** [nmap/nmap#252]
There used to be an option to automatically write a brief scan report (percentage complete) to the standard output every so often, at specified intervals. Has this option been removed? It seems so. If so, please bring it back. Cheers.

**Comment by dmiller-nmap** [comment]
The option is [`--stats-every`](https://nmap.org/book/man-output.html#idm246880457920), and it has not been removed.

**Comment by tjt263** [comment]
Okay, cheers. Looks like it's just been removed from the help screen. FYI.
<pre>
------------------------------------------------------------------------------------------------
tjt263@MacBook-Pro:~$ nmap -h |grep -- --stats-every
------------------------------------------------------------------------------------------------
tjt263@MacBook-Pro:~$ nmap -V
Nmap version 7.00 ( https://nmap.org )
Platform: x86_64-apple-darwin14.5.0
Compiled with: liblua-5.2.3 openssl-1.0.2d nmap-libpcre-7.6 libpcap-1.5.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select
------------------------------------------------------------------------------------------------
tjt263@MacBook-Pro:~$ nmap -h |grep -- --stats-every
------------------------------------------------------------------------------------------------
</pre>
