### ISSUE TITLE
Set an username in ldap-brute

### ISSUE THREAD

**Issue by ymgh96** [nmap/nmap#2524]
In ldap-brute.nse script I just find the feature for setting a list (file) of usernames with "userdb" switch.
I have a feature request (!) mean argument to set just one username (string, not a list). I search and don't find this argument even in source code. Please guide me if there is this feature and I mistake!

**Describe the current behavior**
nmap 192.168.1.1 -p 389 --script ldap-brute --script-args ldap.base='"cn=users,dc=test,dc=local"',passdb=password.txt,userdb=username.txt

**Expected behavior**
nmap 192.168.1.1 -p 389 --script ldap-brute --script-args ldap.base='"cn=users,dc=test,dc=local"',passdb=password.txt,_ldap.username_="my_username"

**Comment by dmiller-nmap** [comment]
The way to accomplish this currently would be to create a file with only one line containing the username of your choice, then use that with the `userdb` argument:

```
echo "my_username" > my_user.txt
nmap --script-args "ldap.base='cn=users,dc=test,dc=local',passdb=password.txt,userdb=my_user.txt" [other options as needed]
```
