### ISSUE TITLE
NSOCK ERROR openssl legacy provider failed to load

### ISSUE THREAD

**Issue by emardee** [nmap/nmap#2532]
**Describe the bug**
When running a scan using NMAP Gui v7.93 on Windows 11, I get the following error:
 - NSOCK ERROR... openssl legacy provider failed to load

Reading on various forums, the solution appears to be remove v7.93 and install v7.92. Was surprised I couldn't find this bug with v7.93 reported here. (Apologies if this bug is already listed, but I just failed to find it).

**To Reproduce**
Run v7.93 from the GUI and select Scan from the interface.  

**Expected behavior**
Would expect it to run the scan without errors

**Version info (please complete the following information):**
 - OS: Windows 11  21H2 (Build: 22000.1042)
 - NMAP v7.93 (apologies can't run the version command requested, as I already removed v7.93. Sorry).

**Comment by dmiller-nmap** [comment]
This is not a true error in the sense that Nmap cannot work. However, having the legacy OpenSSL provider installed will allow the use of legacy crypto that may be needed to fully probe some outdated services and devices. In our Windows builds, the legacy provider is built-in, so the load fails because it is unnecessary. I've added some checks to ensure we only print this warning when the -d option is used (debugging).

**Comment by Ma1Dong** [comment]
I also encountered this problem, does it not affect scanning? thank you
![image](https://user-images.githubusercontent.com/52943794/196432737-2f098315-d3b4-4cf3-95d6-a452c4d424ea.png)

**Comment by UniqueUsernam** [comment]
I have also experienced this error when running Zenmap GUI 7.93. This is the output of nmap --version on the command line:

> Nmap version 7.93 ( https://nmap.org )
> Platform: x86_64-apple-darwin17.7.0
> Compiled with: nmap-liblua-5.3.6 openssl-3.0.5 nmap-libssh2-1.10.0 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.10.1 > > nmap-libdnet-1.12 ipv6
> Compiled without:
> Available nsock engines: kqueue poll select

I am receiving this error whenever I run an Intense scan in Zenmap.
![IMAGE](https://user-images.githubusercontent.com/73913201/222429032-9133baa4-98a0-403f-8e50-e458b716098a.jpg)

I don't use -d for debugging, and I still see this error. The scan still runs, but this error always occurs when I run Intense scan. I've tried removing -v to disable verbose output, but I still see the error.

**Comment by Nephilimi** [comment]
I saw this error today using a copy of zenmap for windows installed today. The command I ran was; nmap -sU -p 47800-47810 --script bacnet-info 192.168.0.4

**Comment by pich4ya** [comment]
Solution for macOS.

1. uninstall nmap 7.93

For homebrew nmap
```
brew uninstall nmap
```
For dmg nmap
```
sudo rm -r /Applications/Zenmap.app
sudo rm /usr/local/bin/{ncat,ndiff,nmap,nmap-update,nping}
sudo rm /usr/local/share/man/*/man1/nmap.1
sudo rm /usr/local/share/man/man1/{ncat,ndiff,nping,nmap-update}.1
sudo rm -r /usr/local/share/{nmap,ncat}
```
2. Install nmap 7.92
https://nmap.org/dist/nmap-7.92.dmg
