### ISSUE TITLE
Zenmap 7.00 not build in FreeBSD

### ISSUE THREAD

**Issue by nemysis** [nmap/nmap#255]
Hello I'm FreeBSD Maintainer for Zenmap

https://www.freshports.org/security/zenmap/

```\n
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 349
    mode = ((os.stat(uninstaller_filename)[ST_MODE]) | 0555) & 07777
                                                          ^
SyntaxError: invalid token
*** Error code 1

Stop.
make[1]: stopped in /usr/local/ports/local/In-Review/security/zenmap
*** Error code 1

Stop.
make: stopped in /usr/local/ports/local/In-Review/security/zenmap
```

Please correct this.

**Comment by dmiller-nmap** [comment]
Thanks for the report. Unfortunately, I can't see what's wrong with the syntax there. What version of Python are you using? Do you get a `SyntaxError` with the command: `python -c 'print chr(0x40 | 0001)'`? Can you check that the setup.py file is not corrupted? I get a sha1sum of "7dbd0bca3f98875fb13bfe4d551eda1ad709b98f" for that file.

**Comment by elad** [comment]
@dmiller-nmap that looks like a Python 3 error.

@nemysis try forcing a 2.6-2.7 Python version per https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/using-python.html.

**Comment by dmiller-nmap** [comment]
Verified, this is a Python 3 syntax error: 

> Octal literals are no longer of the form 0720; use 0o720 instead.

Until Python 3 is supported (which would require a move to GTK+ 3 via PyGObject), we will not fix this. Instead, we'll put a hard version check for Python 2 into setup.py.

**Comment by nemysis** [comment]
I use now python2.7  but got this

```\n
  File "setup.py", line 315
    ,
    ^
SyntaxError: invalid syntax
*** Error code 1

Stop
```
