### ISSUE TITLE
Memory leak in nse_openssl.cc when OPENSSL_VERSION_NUMBER >= 0x10100000L

### ISSUE THREAD

**Issue by linholmes** [nmap/nmap#2550]
#define FUNC_EVP_CIPHER_CTX_cleanup EVP_CIPHER_CTX_reset
It should be 
#define FUNC_EVP_CIPHER_CTX_cleanup EVP_CIPHER_CTX_free 

leak code in nse_openssl.cc:
l_encrypt and l_decrypt function:
```
EVP_CIPHER_CTX *cipher_ctx = EVP_CIPHER_CTX_new()
...
FUNC_EVP_CIPHER_CTX_cleanup( PASS_EVP_CTX(cipher_ctx))
```

EVP_CIPHER_CTX_new should use  EVP_CIPHER_CTX_free

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! I cleaned up the use of macros for this and hopefully made it easier to read, as well as fixing several other similar issues in Ncat and Nping plus some error paths that could lead to a leak. Fix incoming.
