### ISSUE TITLE
Path Traversal

### ISSUE THREAD

**Issue by SleepTheGod** [nmap/nmap#2552]
**Summary**
A google dork that leads to a critical path traversal

**To Reproduce**
1. Go to the following link [Here](https://www.google.com/search?q=%22%2Flibdnet-stripped%2F)
2. We can also go to google.com and in the search bar type this "/libdnet-stripped/"
3. The following results will lead us [here](https://svn.nmap.org/nmap/libdnet-stripped/) 

**Expected behavior**
https://svn.nmap.org/nmap/libdnet-stripped
https://github.com/nmap/nmap/blob/master/libdnet-stripped/libdnet-stripped.vcxproj
https://ftp.software.ibm.com/aix/freeSoftware/aixtoolbox/PATCHES/nmap-7.60-aix.patch
https://marc.info/?l=nmap-dev&m=151629423302977&w=2
And many many more

 - OS Tested: [Windows 11 Home Current]
 
**Additional context**
Found by Taylor Christian Newsome Twitter.com/ClumsyLulz

**Comment by dmiller-nmap** [comment]
That is our public Subversion repository. There is no path traversal involved.
