### ISSUE TITLE
Nmap install error: "install: nmap-payloads: No such file or directory"

### ISSUE THREAD

**Issue by benpratt** [nmap/nmap#2553]
On FreeBSD 13.1 running "sudo gmake install" fails to install with the following error:

install: nmap-payloads: No such file or directory
gmake: *** [Makefile:325: install-nmap] Error 71

The install succeeds with svn revision 38541 and fails after updating to svn revision 38542.

Steps to reproduce on FreeBSD 13.1:

In nmap directory run:
1. 'gmake distclean'
2. 'svn up -r38542'
3. './configure --with-openssl=/usr/local"
4. 'gmake'
5. 'sudo gmake install'

**Comment by ad0nis** [comment]
Can confirm that this same issue is happening in ubuntu 20.04 when building from source.

**Comment by jopamo** [comment]
Looks like the reference in [Makefile.in](https://github.com/nmap/nmap/blob/master/Makefile.in) just needs to be removed? It was merged into [nmap-service-probes](https://github.com/nmap/nmap/commit/2fcfac93292f65a7ca67294d48061fc45e1b323f#diff-38f19b3e0ac7fac55a9dab2cb0ecad2166e45db60b34def3f6c410d82f28680b)

**Comment by benpratt** [comment]
It looks like this commit resolved the install issue: https://github.com/nmap/nmap/commit/70dc5434f41109cd0e9000f9082cbe3b5a6a9d31
