### ISSUE TITLE
Unable to find nmap-protocols!

### ISSUE THREAD

**Issue by Redfern89** [nmap/nmap#2558]
Hello, dear developer! i build nmap from github.. 

┌── root😈fuck [ 📂/home/fck/dev ]
└─> nmap 192.168.1.10 -sV
Starting Nmap 7.93SVN ( https://nmap.org ) at 2022-11-02 11:10 MSK
Unable to find nmap-protocols!  Resorting to /etc/protocols
Parse error in protocols file /etc/protocols line 8
nmap: protocols.cc:142: int nmap_protocols_init(): Assertion `!protocol_table[protno]' failed.
Aborted

**Comment by WorldisEnd** [comment]
I ran into the same problem, while archlinux was trying to compile.

**Comment by normalmf666** [comment]
same here
