### ISSUE TITLE
The results of DES-CBC and DES of openssl encrypt are exactly the same

### ISSUE THREAD

**Issue by chushuai** [nmap/nmap#2563]
out1 = openssl.encrypt( "DES-CBC", pw_hash, nil, cli_sesskey )
out2 = openssl.encrypt( "DES", pw_hash, nil, cli_sesskey )

**Comment by dmiller-nmap** [comment]
NSE is simply returning the result of the EVP cipher returned by `EVP_get_cipherbyname()` using the name provided. OpenSSL uses CBC mode for DES if no other mode is provided, meaning that "DES" and "DES-CBC" are the same cipher. You can verify this by comparing the output of the following commands and seeing that they are equal:

echo "hello" | openssl enc -e -des -a -k 0 -S 0
echo "hello" | openssl enc -e -des-cbc -a -k 0 -S 0
