### ISSUE TITLE
padding  should be int not bool 

### ISSUE THREAD

**Issue by chushuai** [nmap/nmap#2566]
https://github.com/nmap/nmap/blob/master/nse_openssl.cc#L380
/** decrypt( string algorithm, string key, string iv, string data, bool padding = false ) */

int padding = lua_toboolean( L, 5 );

You can see the code in openssl
https://github.com/openssl/openssl/blob/79c8dcf3985a7b75eac8e53eb8652728af6c5d3d/crypto/evp/evp_enc.c#L1046

**Comment by nnposter** [comment]
The OpenSSL C code is using the `pad` parameter in a typical Boolean fashion: A non-zero `int` value turns on PKCS#5 padding; there are no logical values other than true/false. As a result, it makes sense that in Lua, which has a distinct Boolean type, the parameter is using this type and not an integer.

Please feel free to reopen the issue if you have a counterargument that Lua should be also using the integer type for this purpose..
