### ISSUE TITLE
Zenmap: Legend for topology page

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#258]
Along with the Hosts Viewer, Fisheye, Controls button group, put a Legend button that pops up the [topology legend](https://nmap.org/book/zenmap-topology.html#zenmap-topology-legend) so that users don't have to go all the way to the website for that.

**Comment by surajhande555** [comment]
I will work on this

**Comment by dmiller-nmap** [comment]
Further requirements:
* Text must be displayed as text, not an image.
* Images should be actual renders of the radialnet pixmaps and shapes so that they will update with any changes we may make to those files and settings.
* Text descriptions may be shorter than the full descriptions on the [Surfing the Network Topology](https://nmap.org/book/zenmap-topology.html#zenmap-topology-legend) page. E.g. the green circle could be described as "Host with fewer than 3 open ports," and the blue line as "Traceroute connection. Thicker line means higher RTT."
