### ISSUE TITLE
Possible bug with hidden files?

### ISSUE THREAD

**Issue by altjx** [nmap/nmap#2588]
**Describe the bug**
When trying to use a hidden file (starting with a period (".")), I am getting a `Permission Denieddenied (13)` error message. When renaming the file to exclude the period, it works perfectly fine.

**To Reproduce**

```
root@vm:~# nmap -sS -Pn -n -iL /root/.host_discovery_ips.txt --top-ports 50 -vvv
Failed to open input file /root/.host_discovery_ips.txt for reading: Permission denied (13)
```

The above command fails for me; however, renaming the discovery file works fine:

```
root@vm:~# cp /root/.host_discovery_ips.txt /root/host_discovery_ips.txt
root@vm:~# nmap -sS -Pn -n -iL /root/host_discovery_ips.txt --top-ports 50 -vvv
Starting Nmap 7.93 ( https://nmap.org ) at 2022-12-21 12:37 CST
Initiating ARP Ping Scan at 12:37
Scanning 1022 hosts [1 port/host
```

According to the ls output below, they are exactly the same files with the exception of the file names:

```
root@vm:~# ls -la .host_discovery_ips.txt host_discovery_ips.txt
-rw-r--r-- 1 root root 12873 Dec 21 12:29 .host_discovery_ips.txt
-rw-r--r-- 1 root root 12873 Dec 21 12:37 host_discovery_ips.txt
```

**Expected behavior**
Nmap should be able to interpret hidden files the same way as it does with non-hidden files.

**Version info (please complete the following information):**

OS:

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
```

 Output of `nmap --version`:

```
Nmap version 7.93 ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.2 libssh2-1.10.0 libz-1.2.11 libpcre-8.39 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

Output of `nmap --iflist`:

```
root@vm:~# nmap --iflist
Starting Nmap 7.93 ( https://nmap.org ) at 2022-12-21 12:39 CST
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                      TYPE     UP MTU   MAC
lo      (lo)      127.0.0.1/8                  loopback up 65536
lo      (lo)      ::1/128                      loopback up 65536
ens18   (ens18)   10.2.224.18/22               ethernet up 1500  92:5D:3B:C0:17:F0
ens18   (ens18)   fe80::77e6:5219:ee43:8bbe/64 ethernet up 1500  92:5D:3B:C0:17:F0
docker0 (docker0) 172.17.0.1/16                ethernet up 1500  02:42:87:00:BA:4A

**************************ROUTES**************************
DST/MASK                      DEV     METRIC GATEWAY
10.2.224.0/22                 ens18   100
172.17.0.0/16                 docker0 0
169.254.0.0/16                ens18   1000
0.0.0.0/0                     ens18   100    10.2.224.109
::1/128                       lo      0
fe80::77e6:5219:ee43:8bbe/128 ens18   0
::1/128                       lo      256
fe80::/64                     ens18   1024
ff00::/8                      ens18   256
```

**Additional context**
Nothing special to my knowledge -- just a standard Ubuntu OS. I did have to install Nmap version 7.93 using Snap because `apt install nmap -y` resulted in Nmap version 7.80, which had other issues that were fixed in later versions of Nmap.

**Comment by nnposter** [comment]
I was unable to reproduce the issue in 7.92 or 7.93:
```
root@kali:~# echo 172.12.5.5>.host_discovery_ips.txt
nmap -sS -Pn -n -iL /root/.host_discovery_ips.txt --top-ports 50 -vvv
Starting Nmap 7.93 ( https://nmap.org ) at 2022-12-21 19:46 MST
Initiating SYN Stealth Scan at 19:46
Scanning 172.12.5.5 [50 ports]
Discovered open port 22/tcp on 172.12.5.5
...
```
Furthermore, the code is doing straightforward `fopen()` on the filename so there is no internal globbing or other opportunities to interfere with accessing the file.

This really looks like an environmental issue on your end and, if I were to guess, snap [home interface](https://snapcraft.io/docs/home-interface) is likely your culprit:

> The home [interface](https://snapcraft.io/docs/interface-management) allows access to **non-hidden** files owned by the user in the user’s home ($HOME) directory where a user normally stores their personal files and documents.

**Comment by dmiller-nmap** [comment]
As @nnposter noted, Nmap is not doing any different handling of files based on filename. The permission denied error 13 is simply reporting what the OS has returned when it tried to open the file. If you can show that the file is otherwise accessible (e.g. `stat` shows the file characteristics are accessible and `cat` or `grep` can be used on the file), you may reopen this issue and provide that information.
