### ISSUE TITLE
Check Lua version at configure time

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#259]
Nmap is only compatible with Lua 5.2 at the moment (and if we change to 5.3 then we will not be compatible with older versions either), so we should use autoconf macros to detect the *correct* version, not just any version.

See http://seclists.org/nmap-dev/2015/q4/236

**Comment by palashahuja** [comment]
@dmiller-nmap  Can we simply add the dependency for lua 5.3 methods rather than fixating on lua being 5.2?
