### ISSUE TITLE
NSE: failed to initialize the script engine

### ISSUE THREAD

**Issue by Aviril7** [nmap/nmap#2596]
Am trying to brute force a test lab (https://smikta.info/index.php) with the following command

nmap -p 443 --script http-form-brute --script-args "brute.firstonly=true,http-form-brute.path=/?method=login,http-form-brute.method=POST,userdb=user.txt,http-form-brute.uservar=user_name,http-form-brute.passvar=user_pass,http-form-brute.onfailure=Wrong,http.useragent=Mozilla/5.0 (X11; Linux aarch64; rv:102.0) Gecko/20100101 Firefox/102.0" smikta.info

But it keep's giving me the following error 

Starting Nmap 7.93 ( https://nmap.org ) at 2023-01-04 08:04 UTC
NSE: args = brute.firstonly=true,http-form-brute.path=/?method=login,http-form-brute.method=POST,userdb=user.txt,http-form-brute.uservar=user_name,http-form-brute.passvar=user_pass,http-form-brute.onfailure=Wrong,http.useragent=Mozilla/5.0 (X11; Linux aarch64; rv:102.0) Gecko/20100101 Firefox/102.0
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:1298: arguments did not parse!
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nse_main.lua:1298: in main chunk
        [C]: in ?

QUITTING!

**Comment by dksslq** [comment]
`=' in `method=login' needs to be escape

**Comment by Aviril7** [comment]
Just for me to get a better understanding can please just edit the command for

**Comment by dksslq** [comment]
And UserAgent, you should escape the special chars.

**Comment by Aviril7** [comment]
Can you please edit the command

**Comment by Aviril7** [comment]
> `=` in `method=login` needs to be escape

With a back slash

**Comment by dksslq** [comment]
```
'useragent="a b c d",url="/?m=login"'
```

**Comment by Aviril7** [comment]
I tried it and got below error

zsh: parse error near `)'

**Comment by Aviril7** [comment]
> ```
> 'useragent="a b c d",url="/?m=login"'
> ```

This the command and got below error

zsh: parse error near `)'

**Comment by Aviril7** [comment]
Same error

**Comment by dmiller-nmap** [comment]
The script arguments have failed to be parsed because of unescaped or unquoted strings. In a /bin/sh-style shell, you can use double-quotes to surround strings and use single-quotes around the entire argument to `--script-args`. When you have this many script arguments, it may be better to use `--script-args-file` to pass a file containing a single argument per line. Commas and quotes are not needed in that case.

**Comment by Aviril7** [comment]
So you're saying the command should look something like this
 `nmap -p 443 --script http-form-brute --script-args "brute.firstonly=true,http-form-brute.path=""/?method=login"",http-form-brute.method=POST,userdb=user.txt,http-form-brute.uservar=user_name,http-form-brute.passvar=user_pass,http-form-brute.onfailure=Wrong,http.useragent=""Mozilla/5.0 (X11; Linux aarch64; rv:102.0) Gecko/20100101 Firefox/102.0"" smikta.info`
