### ISSUE TITLE
Http-form-brute 

### ISSUE THREAD

**Issue by Aviril7** [nmap/nmap#2597]
Am trying to brute force a test lab (http://smikta.info) with nmap following command
~$ `nmap --script http-form-brute -p 80 smikta.info`

@output

`Starting Nmap 7.92 ( https://nmap.org ) at 2023-01-05 18:48 WAT Nmap scan report for http://smikta.info (192.124.249.69) Host is up (0.28s latency). rDNS record for 192.124.249.69: http://cloudproxy10069.sucuri.net`

`PORT   STATE SERVICE`
`80/tcp open  http`

`Nmap done: 1 IP address (1 host up) scanned in 1.89 seconds`

Expected @output

`-- PORT     STATE SERVICE REASON`
`-- 80/tcp   open  http    syn-ack`
`-- | http-form-brute:`
`-- |   Accounts`
`-- | Patrik Karlsson:secret - Valid credentials`
`-- |   Statistics`
`-- |_ Perfomed 60023 guesses in 467 seconds average tps: 138`

please what am I doing wrong

**Comment by cldrn** [comment]
You need to set the parameters to the field names used in the HTTP form.

**Comment by Aviril7** [comment]
Thank's it worked
