### ISSUE TITLE
Is ncap required by nmap

### ISSUE THREAD

**Issue by paulcsiki** [nmap/nmap#2605]
We're seeing AV detections of ncat and would like to prevent that by removing ncat from the nmap package that we redistribute. Is ncat used internally by nmap? Can we safely remove ncat from the nmap package?

**Comment by fyodor** [comment]
Just as an update, I corresponded with Paul last week about this.  Apparently Bitdefender Advanced Threat Security is wrongfully flagging our Windows ncat.exe Version 7.90 binary.  It apparently classifies it as "potentially unwanted software".  When we do the upcoming Nmap release, hopefully we'll get a chance to check against VirusTotal to make sure everything shows up as clean.  We've had good results in the past by contacting A/V companies about their false positives, although it's admittedly annoying to deal with.
