### ISSUE TITLE
Zenmap python3

### ISSUE THREAD

**Issue by KrizalidTheRed** [nmap/nmap#2607]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

**Expected behavior**
Describe what you would like to happen instead.

I've tried to install zenmap, but requires python2-gtk, when i try to install i've got errors, and python2 is deprecated, when we get a new version?

**Comment by dmiller-nmap** [comment]
Python 3 port was begun in #2088. Next release will have all parts complete.
