### ISSUE TITLE
Potential memory leak in nsock/src/nsock_pcap.c

### ISSUE THREAD

**Issue by icy17** [nmap/nmap#2609]
Potential memory leak in [nsock_pcap.c](https://github.com/nmap/nmap/blob/master/nsock/src/nsock_pcap.c#L114) line 114. Calling pcap_compile() without calling pcap_freecode() to free the memory will cause a memory leak.
[Doc](https://www.tcpdump.org/manpages/pcap_freecode.3pcap.html) says "pcap_freecode() is used to free up allocated memory pointed to by a bpf_program struct generated by [pcap_compile](https://www.tcpdump.org/manpages/pcap_compile.3pcap.html)(3PCAP) when that BPF program is no longer needed, for example after it has been made the filter program for a pcap structure by a call to [pcap_setfilter](https://www.tcpdump.org/manpages/pcap_setfilter.3pcap.html)(3PCAP)."

![image](https://user-images.githubusercontent.com/39425646/216514764-ae4298b2-0090-434a-b9ff-1c9cf9afd7ed.png)

**Comment by dksslq** [comment]
Shit bro,
