### ISSUE TITLE
Nmap 7.94 does not print service as 'unknown' instead skips the service tag in XML report.

### ISSUE THREAD

**Issue by adityatelange** [nmap/nmap#2656]
**Describe the bug**
Nmap 7.94 does not print service as 'unknown' instead skips the service tag in XML report.

**To Reproduce**
1. Install Nmap `7.93`
2. Run a nmap scan: `nmap -oX nmap7.93.xml <IP>` having few filtered ports.
3. Observe the output.
4. Install Nmap `7.94`
5. Run a nmap scan: `nmap -oX nmap7.94.xml <IP>` having few filtered ports.
6. Observe the xml output/report.

![image](https://github.com/nmap/nmap/assets/21258296/ac891bba-40c8-4fa3-8f63-5782240b45da)

**Expected behavior**
Nmap should display service as `Unknown` like in earlier versions.

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909] Windows 10 22H2.
 - Output of `nmap --version`: Nmap version 7.94 ( https://nmap.org )
 - Output of `nmap --iflist`: -

**Additional context**
N/A

**Comment by adityatelange** [comment]
Hi @dmiller-nmap is commit c13ce4536e09be371977f72d32a565662acad736 related to this issue?

**Comment by dmiller-nmap** [comment]
For future reference, this is allowed by the DTD:

https://github.com/nmap/nmap/blob/38c113f82043ddb382b3308bd9c493e928d6975c/docs/nmap.dtd#L202

The service element is not required. The semantic meaning of the "unknown" service name is that there is no known name associated with this port, though the port number has been found open frequently enough to be included in the `nmap-services` file. For this reason, including the "unknown" service tag does not convey any additional information. Earlier versions of Nmap also leave out the service tag when scanning ports that do not appear in the `nmap-services` file, e.g. 65533, though the screen output also shows "unknown" for these services.
