### ISSUE TITLE
Multiple nmap processes running with `--exclude`, memory overflow

### ISSUE THREAD

**Issue by fsxchen** [nmap/nmap#2669]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
When I run multiple nmap processes with the parameters `--exclude`, then the memory overflow。

**To Reproduce**
```
/ # uname -a
Linux centos105_117 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 Linux
nmap: 7.94
```
the command is 
```
nmap -T4 --max-rate 1000 --max-retries 2 -sS -pT:22-23,80,135,137,139,443,445,8080,8083  --exclude 192.168.100.232,192.168.100.102,192.168.100.30,192.168.100.240,192.168.100.232,192.168.100.102,192.168.100.30,192.168.100.240,192.168.103.200,192.168.103.201,192.168.103.203,192.168.103.205,192.168.103.32,192.168.103.34,192.168.103.153,192.168.103.147,192.168.103.149,192.168.103.127,192.168.103.180,192.168.103.181,192.168.103.135,192.168.103.202,192.168.103.106,192.168.103.191,192.168.103.121,192.168.103.213,192.168.103.166,192.168.103.173,192.168.103.229,192.168.103.154,192.168.104.151,192.168.104.156 -oX -  192.168.105.101-201 &
```

**Expected behavior**
If I run this command multiple times, there will be multiple processes running at the same time at this point, then the memory overflow. I find that if I reduce the number of `--exclude` arguments, the memory footprint is better.

**Version info (please complete the following information):**
```
/usr/bin # cat /etc/issue
Welcome to Alpine Linux 3.17
Kernel \r on an \m (\l)

```

nmap:7.94

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by co60ca** [comment]
Hey @fsxchen if you remove the duplicates in your --exclude arguments this may not happen.

--exclude **192.168.100.232**,192.168.100.102,192.168.100.30,192.168.100.240,**192.168.100.232**,192.168.100.102

I've bolded a duplicate as above.

https://github.com/nmap/nmap/issues/2731

**Comment by dmiller-nmap** [comment]
Duplicate #2731
