### ISSUE TITLE
Nmap with -sT parameter hangs on 7.94

### ISSUE THREAD

**Issue by randybock** [nmap/nmap#2672]
**Describe the bug**
When running nmap with the -sT parameter, the scan never completes.  Keeps just saying 0.00% done.  Have let it run for more than an hour.

**To Reproduce**
Run nmap with -sT parameter. Runs fine when the parameter is removed

**Expected behavior**
I expect it to run within a few seconds.  The same command worked perfectly in 7.93.

**Version info (please complete the following information):**
 - OS: Windows server 2012
 - Output of `nmap --version`:  
 - Nmap version 7.94 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.4 openssl-3.0.8 nmap-libssh2-1.10.0 nmap-libz-1.2.13 nmap-libpcre-7.6 Npcap-1.75 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select
 - Output of `nmap --iflist`
Starting Nmap 7.94 ( https://nmap.org ) at 2023-06-23 16:31 Central Daylight Time
************************INTERFACES************************
DEV  (SHORT) IP/MASK                      TYPE     UP   MTU  MAC
eth0 (eth0)  fe80::5b7f:b21:7155:7e30/64  ethernet down 1500 3C:EC:EF:B2:54:42
eth1 (eth1)  fe80::7561:3224:ade4:5230/64 ethernet up   1500 AC:1F:6B:87:66:D3
eth1 (eth1)  10.2.1.52/24                 ethernet up   1500 AC:1F:6B:87:66:D3
lo0  (lo0)   ::1/128                      loopback up   -1
lo0  (lo0)   127.0.0.1/8                  loopback up   -1

DEV    WINDEVICE
eth0   \Device\NPF_{6BCFDEC4-A31F-4CE4-82B1-56C4B1C2F3D5}
eth1   \Device\NPF_{E645965B-E8A9-46EF-BE19-82BAB3D8EBC7}
eth1   \Device\NPF_{E645965B-E8A9-46EF-BE19-82BAB3D8EBC7}
lo0    \Device\NPF_Loopback
lo0    \Device\NPF_Loopback
<none> \Device\NPF_{984DE894-CEB8-4667-A0A9-02CD6637677A}
<none> \Device\NPF_{9E8736B7-6794-496A-98B2-1F20B959622A}
<none> \Device\NPF_{09D6E3C2-A2FB-44A4-A46B-F3F614AF90BE}

**************************ROUTES**************************
DST/MASK                      DEV  METRIC GATEWAY
255.255.255.255/32            eth1 261
255.255.255.255/32            eth1 281
10.2.1.52/32                  eth1 281
10.2.1.255/32                 eth1 281
127.255.255.255/32            lo0  331
127.0.0.1/32                  lo0  331
255.255.255.255/32            lo0  331
10.2.1.0/24                   eth1 281
127.0.0.0/8                   lo0  331
224.0.0.0/4                   eth1 261
224.0.0.0/4                   eth1 281
224.0.0.0/4                   lo0  331
0.0.0.0/0                     eth1 281    10.2.1.31
fe80::5b7f:b21:7155:7e30/128  eth0 261
fe80::7561:3224:ade4:5230/128 eth1 281
::1/128                       lo0  331
fe80::/64                     eth0 261
fe80::/64                     eth1 281
ff00::/8                      eth0 261
ff00::/8                      eth1 281
ff00::/8                      lo0  331
**Additional context**
None

**Comment by TheProdigyLeague** [comment]
Not a Lua expert, but IME; When executing scripts, instead of running they kind of just hang. The interpreter (ANTLR or whatever...) Is trying to throw a compiler error (But, bot go "hm???") and just runs an infinite loop rather than throwing error...ANYWAYS, hope this helps. And, ITC it could just be The Version, or The Interpreter...

**Comment by dksslq** [comment]
Default parallelism is 0, using ```--max-parallelism``` or ```nmap -sT xx``` hangs. its a bug specific to windows. check: https://github.com/nmap/nmap/blob/d131a096a869195be36ef7d4fa36739373346cb2/scan_engine_connect.cc#L119

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is a known issue with Nmap 7.94 on Windows which has been fixed in preparation for the next release. The fix is in commit 0890822b0945000a0f7058331b171d26eeb74d00
