### ISSUE TITLE
Is there a mistake in nmap-services

### ISSUE THREAD

**Issue by dksslq** [nmap/nmap#2675]
vunknown	13882/tcp	0.000000
[nmap-services](https://github.com/nmap/nmap/blob/master/nmap-services#L13759)
![image](https://github.com/nmap/nmap/assets/21374813/013a5c70-4a14-4c13-bdcd-2201244fa4de)

**Comment by iasdeoupxe** [comment]
Looks like. I would create a PR but the file itself has the text below:

```
# THIS FILE IS GENERATED AUTOMATICALLY FROM A MASTER - DO NOT EDIT.
# EDIT /nmap-private-dev/nmap-services-all IN SVN INSTEAD.
```

**Comment by dmiller-nmap** [comment]
Yes, thanks for pointing this out. This was a typo introduced in 2013!
