### ISSUE TITLE
Error #487: Your port specifications are illegal.

### ISSUE THREAD

**Issue by Pation1** [nmap/nmap#2676]
When I write: sudo nmap -sT -p (host), or sudo nmap -sS -p (host), the results are: Starting Nmap 7.94 (https://nmap.org) at 2023-07-04 23:24 EDT
Error #487: Your port specifications are illegal. Example of proper form: "-100,200-1024,T:3000-4000,U:6000-"
QUITTING!

I use Kali Linux
Nmap version 7.94

**Comment by kml0212** [comment]
-p stands **specific ports** you want to scan . the you provided clearly has the answer you need to specify the ports properly 

Example :
_$ sudo nmap -sS -p 22,80  18.0.0.1_
this scans the tcp ports 22 , 80  

If you want to default ports leave it with out mentioning  "-p " option  
Example :
_$ nmap scanme.nmap.org_

need to _scan all ports_ use  -p- 
_range of ports_ -p-<range>   ex : _`nmap -p-100 <host>`_

**Comment by talier00t** [comment]
You have to indicate the port specifications and its pretty buggy. Can you try single scanning first? Then you can troubleshoot it if it still fails.

**Comment by dmiller-nmap** [comment]
@kml0212 is correct. The `-p` option requires a set of ports as an argument. See https://nmap.org/book/man-port-specification.html
