### ISSUE TITLE
Segmentation fault with 7.94 and -p http (or any string)

### ISSUE THREAD

**Issue by tacocat31415** [nmap/nmap#2678]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
"Ports can also be specified by name according to what the port is referred to in the nmap-services." from https://nmap.org/book/man-port-specification.html

But using any string for `-p`, such as `-p http` causes a segmentation fault.

**To Reproduce**
nmap -p http 8.8.8.8

**Expected behavior**
You should get nmap output for any http related ports, such as:

Starting Nmap 7.94 ( https://nmap.org ) at 2023-07-09 19:33 EDT
Nmap scan report for dns.google (8.8.8.8)
Host is up (0.0024s latency).

PORT     STATE    SERVICE
80/tcp   filtered http
443/tcp  open     https
8080/tcp filtered http-proxy

**Version info (please complete the following information):**

└─$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.2"
VERSION="2023.2"
VERSION_CODENAME=kali-rolling

Nmap version 7.94 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.4.4 openssl-3.0.9 libssh2-1.10.0 libz-1.2.13 libpcre-8.39 libpcap-1.10.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Comment by TheProdigyLeague** [comment]
~
+ FIX: a segmentation fault in Ncat when scanned with the SSL NSE scripts. 
    I was able to reproduce this on 2013-09-27 with latest SVN by running:
        Ncat: ncat -v -k --ssl -l localhost
        Nmap: ./nmap --script-trace --script '+ssl*' localhost -p 31337
+ This was initially reported by Timo Juhani Lindfors on the Debian bug tracker: 
|_
    $ http://bugs.debian.org/cgi-bin/bugreport.cgi bug=724580
user Henri notes: "I traced the latter back to openssl and opened a ticket there, which never got any reply... https://rt.openssl.org/Ticket/Display.html?id=2885&user=guest&pass=guest"

<screen>
g++: internal compiler error: Segmentation fault (program as)
Please submit a full bug report,
with preprocessed source if appropriate.
See &lt;http://gcc.gnu.org/bugs.html&gt; for instructions.
</screen>
break;
-- @usage
-- nmap -p <port> --script http-security-headers <target>
--
-- @output
-- 80/tcp open  http    syn-ack
-- | http-security-headers:
-- |   Strict_Transport_Security:
-- |     Header: Strict-Transport-Security: max-age=15552000; preload
-- |   Public_Key_Pins_Report_Only:
-- |     Header: Public-Key-Pins-Report-Only: max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
-- |   X_Frame_Options:
-- |     Header: X-Frame-Options: DENY
-- |     Description: The browser must not display this content in any frame.
-- |   X_XSS_Protection:
-- |     Header: X-XSS-Protection: 0
-- |     Description: The XSS filter is disabled.
-- |   X_Content_Type_Options:
-- |     Header: X-Content-Type-Options: nosniff
-- |     Will prevent the browser from MIME-sniffing a response away from the declared content-type.
-- |   Content-Security-Policy:
-- |     Header: Content-Security-Policy: script-src 'self'
-- |     Description: Loading policy for all resources type in case of a resource type dedicated directive is not defined (fallback).
-- |   X-Permitted-Cross-Domain-Policies:
-- |     Header: X-Permitted-Cross-Domain-Policies: none
-- |     Description : No policy files are allowed anywhere on the target server, including this master policy file.
-- |   Cache_Control:
-- |     Header: Cache-Control: private, no-cache, no-store, must-revalidate
-- |   Pragma:
-- |     Header: Pragma: no-cache
-- |   Expires:
-- |_    Header: Expires: Sat, 01 Jan 2000 00:00:00 GMT

**Comment by dmiller-nmap** [comment]
Thanks for this report. This was previously reported and fixed: Duplicate #2658
