### ISSUE TITLE
How does SYN scan work in nmap? Why is it necessary to get its route first?

### ISSUE THREAD

**Issue by CaledoniaProject** [nmap/nmap#2689]
I'm running latest nmap on a hacky CentOS 7 kernel with no /proc/net/route available. In that case SYN scan fails here: https://github.com/nmap/nmap/blob/3be01efb1c11dc9c3d0b53e2a72ae340a48df764/targets.cc#L382

Can you explain on that? I want to know why is it necessary to validate the route first.

**Comment by fyodor** [comment]
Nmap needs to know which interface to send the packet through.
