### ISSUE TITLE
Print getopt warnings *after* options summary before exiting

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#269]
Options summary is so long that users have to scroll up to see what went wrong if they mess up the options. Either don't print it or print it *before* the getopt warning so the warning is clearly visible.

**Comment by notul-atul** [comment]
I am beginner here and I wants to start by implementing above enhancement.
First I want to show warning message to user and then ask user to Press Enter to simply exit or Press any other key to see options summary. Is this fine or should I stick to directions mentioned here?
