### ISSUE TITLE
Nmap Permission Denied

### ISSUE THREAD

**Issue by Meljhon** [nmap/nmap#2694]
(i use the nmap command nmap -sP 127.0.0.1 and it said) Starting Nmap 7.94 (https://nmap.org) at 2023-08-06 09:37 UTC
route_dst_netlink: if_indextoname(1) failed: 13 (Permission denied) i dont know what cause this i also try running this on sudo but it doesn't work too im using kali linux armf. i install kali linux using anlinux and termux

PLS HELP

**Comment by romanovj** [comment]
you don't have rights, build static nmap and execute from adb shell

**Comment by Meljhon** [comment]
> you don't have rights, build static nmap and execute from adb shell or add "-unprivileged"
how do i do it?

**Comment by D1X0N2782** [comment]
The same happen to me and I don't have permisions to arp-scan neither, This should be because of Termux but I can't find a way to fix it

**Comment by romanovj** [comment]
@D1X0N2782 root your device or run from adb

**Comment by dmiller-nmap** [comment]
Nmap requires root privileges for most operations. You can use the `--unprivileged` option to tell Nmap that it does not have root privileges in order to use the features that are allowed in that case: -sT, -sV, and NSE scripts.

**Comment by Linkxee-Tech** [comment]
──(kali㉿localhost)-[~]
└─$ whoami
kali                                                       
┌──(kali㉿localhost)-[~]
└─$ nmap kali.org
Starting Nmap 7.94 ( https://nmap.org ) at 2023-11-03 07:59 UTC
Failed to resolve "kali.org".
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.17 seconds

Is not working what should I do

**Comment by anksingh1212121** [comment]
Same problem with me what to do

**Comment by itsyo2f** [comment]
> Same problem with me what to do

I used that method :
sudo nmap -sn 192.168.1.1/24 --unprivilege
Results : 
Starting Nmap 7.94SVN ( https://nmap.org ) at 2024-03-11 21:23 UTC
Nmap scan report for 192.168.1.1
Host is up (0.012s latency).
Nmap scan report for 192.168.1.52
Host is up (0.030s latency).
Nmap scan report for 192.168.1.63
Host is up (0.047s latency).
Nmap scan report for 192.168.1.79
Host is up (0.040s latency).
Nmap scan report for 192.168.1.97
Host is up (0.056s latency).
Nmap scan report for 192.168.1.99
Host is up (0.0019s latency).
Nmap scan report for 192.168.1.106
Host is up (0.091s latency).
Nmap scan report for 192.168.1.107
Host is up (0.090s latency).
Nmap done: 256 IP addresses (8 hosts up) scanned in 3.27 seconds

**Comment by Khali144** [comment]
> ──(kali㉿localhost)-[~] └─$ whoami kali ┌──(kali㉿localhost)-[~] └─$ nmap kali.org Starting Nmap 7.94 ( https://nmap.org ) at 2023-11-03 07:59 UTC Failed to resolve "kali.org". WARNING: No targets were specified, so 0 hosts scanned. Nmap done: 0 IP addresses (0 hosts up) scanned in 0.17 seconds
> 
> Is not working what should I do

check your dns client settings:
if you write the ip address of your local dns server correct, then it maybe your dns server is the problem.
you can added additional dns servers addresses using netwrok manager GUI then reactivate your associated network interface to reload it's configurations.
