### ISSUE TITLE
Bug in http-security-headers: no string output.

### ISSUE THREAD

**Issue by javelineou** [nmap/nmap#2704]
**Describe the bug**
Couldn't run http-security-headers script on some IPs.

**To Reproduce**
C:\Users\Users>nmap --script http-security-headers 10.100.1.1
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-11 11:14 SE Asia Standard Time
Nmap scan report for 10.100.1.1
Host is up (0.0099s latency).
Not shown: 995 closed tcp ports (reset)
Bug in http-security-headers: no string output.
Bug in http-security-headers: no string output.
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
2000/tcp open  cisco-sccp
5060/tcp open  sip
8008/tcp open  http

**Expected behavior**
Im expecting for HTTP response just like in: https://nmap.org/nsedoc/scripts/http-security-headers.html

**Version info (please complete the following information):**
 - OS: Windows 10 22H2
 - Output of `nmap --version`:
 Nmap version 7.94 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.4 openssl-3.0.8 nmap-libssh2-1.10.0 nmap-libz-1.2.13 nmap-libpcre-7.6 Npcap-1.75 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Comment by nnposter** [comment]
Can you provide any of the following?
* A publicly reachable IP address to reproduce the issue
* A Burp, Zap or Fiddler trace or pcap of the HTTP request/response
* A dump of Nmap output, running in detailed debug mode `-ddd`

**Comment by nnposter** [comment]
Please feel free to reopen if you have additional details.
