### ISSUE TITLE
the spec file used for building the RPM of the nmap is incorrect

### ISSUE THREAD

**Issue by UhichaKubernetes** [nmap/nmap#2706]
The following configuration defined in the spec file used for building the RPM of the nmap source code is incorrect：
Requires: python >= 3.0

The correct configuration should be:
Requires: python3 >= 3.0

Because in RPM package-based Linux distributions, version 3 of Python is named python3 instead of python.

**Comment by Siddhesh-Agarwal** [comment]
@UhichaKubernetes I faced the same problem. is there any workaround for this problem? I went ahead and tried this [solution](https://stackoverflow.com/a/58386644).
