### ISSUE TITLE
Critical: Nmap fails when using OS-detection

### ISSUE THREAD

**Issue by jsherwood0** [nmap/nmap#2710]
**Describe the bug**
When running nmap with OS-detection, the command fails with the following assertion error:
```
nmap: osscan.cc:681: bool FingerTest::str2AVal(const char*, const char*): Assertion `AVs[0] == NULL || 0 == strcmp("Y", AVs[0])' failed.
```
This appears to have been introduced in commit [15a93e7](https://github.com/nmap/nmap/commit/15a93e7b34b3f3dd187242c08d236bd38e1c584b) "Deal with missing 'R' test in fingerprints/observations"

**To Reproduce**
Run nmap with OS-detection enabled.  For example:
`nmap -O 192.168.1.1`

**Expected behavior**
The scan should proceed and results should display.

**Version info (please complete the following information):**
 - OS: Linux 6.4.0-kali3-amd64 Debian 6.4.11-1kali1 (2023-08-21) x86_64 GNU/Linux
 - Output of `nmap --version`:

```
Nmap version 7.94 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.4.4 openssl-3.0.10 libssh2-1.10.0 libz-1.2.13 libpcre-8.39 libpcap-1.10.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

 - Output of `nmap --iflist`:
```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-09-20 18:12 EDT
************************INTERFACES************************
DEV  (SHORT) IP/MASK                      TYPE     UP MTU   MAC
lo   (lo)    127.0.0.1/8                  loopback up 65536
lo   (lo)    ::1/128                      loopback up 65536
eth0 (eth0)  xxx.xxx.xxx.xxx/24            ethernet up 1500  xx:xx:xx:xx:xx:xx
eth0 (eth0)  xxxx::xxxx:xxxx:xxxx:xxxx/64 ethernet up 1500  xx:xx:xx:xx:xx:xx
eth1 (eth1)  (none)/0                     ethernet up 1500  xx:xx:xx:xx:xx:xx

**************************ROUTES**************************
DST/MASK                      DEV  METRIC GATEWAY
xxx.xxx.xxx.xxx/24               eth0 100
0.0.0.0/0                     eth0 100    xxx.xxx.xxx.xxx
::1/128                       lo   0
xxxx::xxxx:xxxx:xxxx:xxxx/128 eth0 0
fe80::/64                     eth0 1024
ff00::/8                      eth0 256
```

**Additional context**
(none)

**Comment by dmiller-nmap** [comment]
Thanks for this report. The nmap-os-db that shipped with Nmap 7.94 should not trigger this assertion, but I pushed a fix that should sync shortly.
