### ISSUE TITLE
[Npcap] Error during starting npcap service in wpcap api-INCOMPATIBLE mode

### ISSUE THREAD

**Issue by Komosa** [nmap/nmap#273]
I'm trying to install npcap with _Install Npcap in WinPcap API-compatible Mode_ switch **OFF**. (Admin only is ON).
I'm disabling service autostart on last screen of installer.

After successful installation I'm trying to start service: `net start npcap` as admin. But I get following error:

    System error 2 has occured.
    
    The system cannot find the file specified.

(npcap service is recognized, eg. `net stop npcap` says that it is stopped)

What is expected instead: service should be successfully started.

I'm able to reproduce it again after deinstallation.
I'm using [prebuild insaller](https://svn.nmap.org/nmap-exp/yang/NPcap-LWF/npcap-nmap-0.05-r3.exe), v 0.05-r3.
In on Windows 8.1 Enterprise N.

(There is no possibility to enter issue on npcap' github page and there is label Npcap here in nmap repo, so I'm reporting this issue here).

**Comment by Komosa** [comment]
I was not able to reproduce issue on other machine. Similary, after restoring windows from previous snapshot, problem stops reproducing.

Sorry for disturbing you.

**Comment by hsluoyz** [comment]
@Komosa Try to use the instructions here: https://github.com/nmap/npcap/releases/tag/v0.05-r8
, despite that 0.05-r8 is not the latest release. The final act is to disabling the ``Driver Signature Enforcement``:
https://support.hidemyass.com/hc/en-us/articles/202723596-How-to-disable-Driver-Signing-check-on-Windows
