### ISSUE TITLE
hash of nmap has changed

### ISSUE THREAD

**Issue by microlaser** [nmap/nmap#2736]
I use MacOS Sonoma and MacPorts and Little Snitch and Little Snitch reported that the hash of my binary for nmap is changed.  I just wanted to make sure the hash is correct and this is just a bug.  
sh-3.2# which nmap
/opt/local/bin/nmap
sh-3.2# shasum -a /opt/local/bin/nmap
Value "/opt/local/bin/nmap" invalid for option a (number expected)
Type shasum -h for help
sh-3.2# shasum -a 256 /opt/local/bin/nmap
f7febf226427f0a527506e61d07decead3b0b62cf4f70f10527f7ebb2af1a03d  /opt/local/bin/nmap

This is what I see.  Is this hash valid?  

Thank you,

Michael Lazin

**Comment by fyodor** [comment]
I don't know what version of Nmap you have or how it was obtained (either compiled yourself, from us, or from a third party) and so we really can't confirm whether whatever checksum you have is correct.  I suggest downloading the latest version for your platform directly from nmap.org.  Cheers.
