### ISSUE TITLE
Can i scan scanme.nmap.org with these tools?

### ISSUE THREAD

**Issue by Mettthew** [nmap/nmap#2738]
**Hello, everyone**,

I am new to the world of scanning and I am studying different vulnerability scanners for my thesis and I also stumbled upon **Nmap**!

`My graduate project is to take several scanners, run the scans on the same target and finally combine the returned outputs. `

`Initially I have using a Metasploitable machine that I downloaded and ran locally, but the next step is to scan a public Ip address because precisely it has to work mainly for the purpose of doing these kinds of scans.`

`I know you can't scan Ip addresses randomly because it's illegal and you need the consent of the owner, so I wanted to look for Ip addresses that were specifically created to be scanned and have vulnerabilities for the sole purpose of testing what I'm studying.`

Searching the net I came across "**scanme.nmap.org**" and reading its description it is just what I was looking for, although the permission to scan is specified for **NMAP** and other similar port scanners.

So I wanted to ask if among these port scanners, can **OpenVas** and **Shodan InternetDB API** be used to scan the site? 
I specify regarding **OpenVas** that I have the free version and in case I would run the standard **Full and Fast scan**.

> I also wanted to ask if you happen to know of any other similar Ip Addresses that I can scan (assuming with the consent of the owner of that address) with these tools?

Thank you in advance for your help :)

**Comment by fyodor** [comment]
Just try not to hammer the server too had. A few scans in a day is fine, but don't scan 100 times a day or use this site to test your ssh brute-force password cracking tool.

**Comment by Mettthew** [comment]
certainly, **thank you very much**! 💯
