### ISSUE TITLE
Error while installing nmap

### ISSUE THREAD

**Issue by prachipalaskar23** [nmap/nmap#2742]
I am trying to install nmap using source code. It is failing with error

libpcap/libpcap.a(pcap-rdmasniff.o): In function `__ibv_reg_mr':
/usr/include/infiniband/verbs.h:2532: undefined reference to `ibv_reg_mr'
libpcap/libpcap.a(pcap-rdmasniff.o): In function `rdmasniff_activate':
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:322: undefined reference to `ibv_dereg_mr'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:330: undefined reference to `ibv_destroy_qp'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:334: undefined reference to `ibv_destroy_cq'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:338: undefined reference to `ibv_destroy_comp_channel'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:342: undefined reference to `ibv_dealloc_pd'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:346: undefined reference to `ibv_close_device'
libpcap/libpcap.a(pcap-rdmasniff.o): In function `___ibv_query_port':
/usr/include/infiniband/verbs.h:2356: undefined reference to `ibv_query_port'
libpcap/libpcap.a(pcap-rdmasniff.o): In function `rdmasniff_cleanup':
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:82: undefined reference to `ibv_dereg_mr'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:84: undefined reference to `ibv_destroy_qp'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:85: undefined reference to `ibv_destroy_cq'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:86: undefined reference to `ibv_dealloc_pd'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:87: undefined reference to `ibv_destroy_comp_channel'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:88: undefined reference to `ibv_close_device'
libpcap/libpcap.a(pcap-rdmasniff.o): In function `rdmasniff_create':
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:370: undefined reference to `ibv_get_device_list'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:405: undefined reference to `ibv_free_device_list'
libpcap/libpcap.a(pcap-rdmasniff.o): In function `rdmasniff_findalldevs':
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:417: undefined reference to `ibv_get_device_list'
/scratch/nmap/nmap-7.92/libpcap/./pcap-rdmasniff.c:434: undefined reference to `ibv_free_device_list'
collect2: error: ld returned 1 exit status

my OpenSSL version is

 openssl version is
OpenSSL 1.1.1k

**Comment by fyodor** [comment]
I'd suggest trying with Nmap Version 7.94 or the current SVN release.  If you still have a problem, please create a new issue with all relevant details such as the platform and distribution you're trying to compile on.  Cheers.
