### ISSUE TITLE
OpenBSD patch: time_t is not long int

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#275]
From the OpenBSD ports maintainer: http://seclists.org/nmap-dev/2016/q1/35

This may not be the best way to handle this: what format string directive should be used for time_t on all platforms? Should we use a macro to cast these? Are these the only places where this conversion is necessary, implied, or assumed?

```diff
Index: nmap_ftp.cc
===================================================================
--- nmap_ftp.cc	(revision 35571)
+++ nmap_ftp.cc	(working copy)
@@ -378,6 +378,6 @@
 
   if (o.debugging || o.verbose)
     log_write(LOG_STDOUT, "Scanned %d ports in %ld seconds via the Bounce scan.\n",
-              numports, (long) time(NULL) - starttime);
+              numports, (long) time(NULL) - (long int)starttime);
   return;
 }
Index: osscan2.cc
===================================================================
--- osscan2.cc	(revision 35571)
+++ osscan2.cc	(working copy)
@@ -2583,7 +2583,7 @@
       /* Up 2 years?  Perhaps, but they're probably lying. */
       if (o.debugging) {
         log_write(LOG_STDOUT, "Ignoring claimed %s uptime of %lu days\n",
-        hss->target->targetipstr(), (hss->seq_send_times[0].tv_sec - hss->si.lastboot) / 86400);
+        hss->target->targetipstr(), (long int)(hss->seq_send_times[0].tv_sec - hss->si.lastboot) / 86400);
       }
       lastboot = 0;
     }
Index: output.cc
===================================================================
--- output.cc	(revision 35571)
+++ output.cc	(working copy)
@@ -1999,7 +1999,7 @@
                 (double) (tv.tv_sec - currenths->seq.lastboot) / 86400,
                 tmbuf);
     xml_open_start_tag("uptime");
-    xml_attribute("seconds", "%li", tv.tv_sec - currenths->seq.lastboot);
+    xml_attribute("seconds", "%li", (long int)(tv.tv_sec - currenths->seq.lastboot));
     xml_attribute("lastboot", "%s", tmbuf);
     xml_close_empty_tag();
     xml_newline();
```

**Comment by devnexen** [comment]
The thing is about time_t it is mainly a long int (Linux, FreeBSD ...) but OpenBSD decides to update it to a long long int since 5.5 release so in order to "cope" with other platforms hence the explicit cast.

**Comment by gvanem** [comment]
I see some problems beyond the year 2036 :smile:.

**Comment by devnexen** [comment]
True sure. That s a solution until other platforms move to 64 bits type :-) or I could provide a version with macros ...

**Comment by gvanem** [comment]
> That s a solution until other platforms move to 64 bits type 

64-bit `time_t` type you mean? MSVC has had that for ~10 years.

A 64-bit value - a 32-bit value doesn't give correct values regardless of a 64-bit `time_t` value AFAICS.
Check  the info for [LLP64/IL32P64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) platforms. What is special with OpenBSD vs. FreeBSD in this regard?

Use a macro IMHO; not fester the Nmap code more than it's already is.
