### ISSUE TITLE
only a portion of HostKeyAlgorithms be detected by ssh2-enum-algos.nse

### ISSUE THREAD

**Issue by aes256ctr** [nmap/nmap#2750]
### centos7.9 server：/etc/ssh/sshd_config
```
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com
```
**sshd has been restarted and takes effect.**

### Why can only a portion of HostKeyAlgorithms be detected by ssh2-enum-algos.nse？
Here are the scan results：
```
|   server_host_key_algorithms: (2)
|       ecdsa-sha2-nistp256
|       ssh-ed25519
```

**Comment by nnposter** [comment]
Have you validated with a packet sniffer or by inspecting debug output from SSH client that the server is in fact offering those other algorithms? Have you generated the corresponding host keys?

**Comment by nnposter** [comment]
Please feel free to reopen if the issue persists.

**Comment by aes256ctr** [comment]
![Snipaste_2024-11-08_09-58-44](https://github.com/user-attachments/assets/c963f8e8-6978-477e-b2c9-807953e635c4)

Thank you for your guidance and comments.
The packet capture showed that only 2 HostKeyAlgorithms algorithms were returned, although I haven't fully figured it out yet, it must be my own problem (I guess it's related to the fact that there are only three types of `ssh-host_ * _key. pub` in the `/etc/ssh` directory)
