### ISSUE TITLE
Update unpwdb NSE library to handle DOS/Windows line breaks for username & pass input files

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2770]
A customer reported that the [ssh-brute script](https://nmap.org/nsedoc/scripts/ssh-brute.html) username and password input files don't only work with UNIX/Linux-style line breaks (\n) and not DOS/Windows style (\r\n).  The issue is probably in the [unpwdb library](https://nmap.org/nsedoc/lib/unpwdb.html) and so should hopefully be an easy fix that should help many scripts.

**Comment by dmiller-nmap** [comment]
Fixed in 66f43184f6c25e7dbc07f0599a74bbbf31b7a490
