### ISSUE TITLE
Not reviewed / merged NSE / Service Probe PRs?

### ISSUE THREAD

**Issue by iasdeoupxe** [nmap/nmap#2810]
Sorry for creating a separate issue but is there any reason / rationale why various open PRs haven't received a single remark from a project member or similar?

Just scratching the surface here and there might be more:
- #2632
- #1425
- #2184
- #2637
- #2557

**Comment by iasdeoupxe** [comment]
For me the most important question which should be answered is:

Does it worth to contribute to this project?

If i'm seeing that a quite simple PR which i had created 5 years ago is not merged in all these years and seeing the same for other PRs (at least one which also pinged the contributors via the mailing lists) as well the simple answer would be:

No

But i would also really understand the reasons for this. If it is a simple "not enough resources / people available for reviews" then it would be great to either get a short note in the remaining open PRs about that (to at least not leaving the authors in the dark) or to update the readme of this project so that people are not wasting their time creating PRs which will be never merged.

**Comment by fyodor** [comment]
Thanks for your contributions and comments.  It's frustrating for us too that we haven't been able to get to all these yet.  We've managed to close 586 PR's but there are 248 still open.  Including 3 new ones from the last week.  And with Issues we've closed 1,065, but 578 are still open.  Sometimes they fall through the cracks, or we're so focused on the "bigger" issues that we neglect some of the smaller ones.  We're working on a new Nmap release for this week in which we've integrated thousands of user-contributed OS and service fingerprints), but we'll try to integrate more PR's for the following release.  So thanks for the reminder.  I'm closing this ticket to avoid clogging the DB further, but you can still leave notes/comments here.

**Comment by iasdeoupxe** [comment]
Nearly one year passed now and none of the initially linked PRs received any action / review so far (one was even closed by the creator, probably due to being stale so long).

This is indeed really getting frustrating, could you please try to find a solution for the current situation?

And if you can't or don't want to review / receive external Pull Requests maybe also just disable these?

**Comment by iasdeoupxe** [comment]
@fyodor FYI, initial mentioned #1425 is now 7 years old and hasn't seen any reaction since i created this issue here (probably all other mentioned PRs as well, all except one seems to be still open...)
