### ISSUE TITLE
Nmap no longer finds PCRE headers in `pcre` directory

### ISSUE THREAD

**Issue by kulikjak** [nmap/nmap#2851]
Hi, the change that migrated Nmap from PCRE to PCRE2 in https://github.com/nmap/nmap/commit/828ab48764b82d0226e860c73c5dac5b11f77385 removed the `HAVE_PCRE_PCRE_H` macro and thus the ability to find `pcre2.h` inside `pcre` directory.

Was this intended or just an oversight?

Since we have the libs in a standard location (`/usr/lib/`) and only headers in the additional `pcre` directory (`/usr/include/pcre`), I cannot solve it by using `--with-pcre2=DIR`. I had to patch the include on several places to build it. Before the change, the configure script solved this seamlessly.

**Comment by dmiller-nmap** [comment]
Thanks for this report. What distro or source package are you using to provide the PCRE2 development headers? I would want to be sure we're not supposed to be looking in pcre2/pcre2.h, for instance.

**Comment by kulikjak** [comment]
Hi, we are building pcre2 from source with `--includedir=/usr/include/pcre`:
https://github.com/oracle/solaris-userland/blob/master/components/pcre2/Makefile#L80

So the https://github.com/nmap/nmap/commit/c6ffdbf7ae35e397b663f787fc4934f01458f945 doesn't help us specifically, although I do realize that this is not necessarily common (maybe it was more common with original pcre), but that is where the header file lives on Oracle Solaris.

**Comment by jospezial** [comment]
@thesamesam
Since https://github.com/nmap/nmap/commit/c6ffdbf7ae35e397b663f787fc4934f01458f945 the build of https://github.com/gentoo/gentoo/blob/master/net-analyzer/nmap/nmap-9999.ebuild is broken.



```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --datarootdir=/usr/share --docdir=/usr/share/doc/nmap-9999 --htmldir=/usr/share/doc/nmap-9999/html --libdir=/usr/lib64 --enable-ipv6 --enable-nls --with-libssh2 --with-ncat --without-ndiff --with-nping --with-liblua --with-openssl --without-zenmap --with-zlib --with-zlib --cache-file=/var/tmp/portage/net-analyzer/nmap-9999/work/nmap-9999/config.cache --with-libdnet=included --with-pcre=/usr --without-dpdk
...
checking for pcre2.h... no
checking for pcre2/pcre2.h... no
...
make: *** No rule to make target 'libpcre/Makefile', needed by 'build-pcre'.  Stop.

```

https://github.com/gentoo/gentoo/tree/master/dev-libs/libpcre2
```
 * Contents of dev-libs/libpcre2-10.44-r1:
/usr
/usr/bin
/usr/bin/i686-pc-linux-gnu-pcre2-config
/usr/bin/pcre2-config -> x86_64-pc-linux-gnu-pcre2-config
/usr/bin/pcre2grep
/usr/bin/pcre2test
/usr/bin/x86_64-pc-linux-gnu-pcre2-config
/usr/include
/usr/include/pcre2.h
/usr/include/pcre2posix.h
/usr/lib
/usr/lib/libpcre2-16.so -> libpcre2-16.so.0.13.0
/usr/lib/libpcre2-16.so.0 -> libpcre2-16.so.0.13.0
/usr/lib/libpcre2-16.so.0.13.0
/usr/lib/libpcre2-32.so -> libpcre2-32.so.0.13.0
/usr/lib/libpcre2-32.so.0 -> libpcre2-32.so.0.13.0
/usr/lib/libpcre2-32.so.0.13.0
/usr/lib/libpcre2-8.so -> libpcre2-8.so.0.13.0
/usr/lib/libpcre2-8.so.0 -> libpcre2-8.so.0.13.0
/usr/lib/libpcre2-8.so.0.13.0
/usr/lib/libpcre2-posix.so -> libpcre2-posix.so.3.0.5
/usr/lib/libpcre2-posix.so.3 -> libpcre2-posix.so.3.0.5
/usr/lib/libpcre2-posix.so.3.0.5
/usr/lib/pkgconfig
/usr/lib/pkgconfig/libpcre2-16.pc
/usr/lib/pkgconfig/libpcre2-32.pc
/usr/lib/pkgconfig/libpcre2-8.pc
/usr/lib/pkgconfig/libpcre2-posix.pc
/usr/lib64
/usr/lib64/libpcre2-16.so -> libpcre2-16.so.0.13.0
/usr/lib64/libpcre2-16.so.0 -> libpcre2-16.so.0.13.0
/usr/lib64/libpcre2-16.so.0.13.0
/usr/lib64/libpcre2-32.so -> libpcre2-32.so.0.13.0
/usr/lib64/libpcre2-32.so.0 -> libpcre2-32.so.0.13.0
/usr/lib64/libpcre2-32.so.0.13.0
/usr/lib64/libpcre2-8.so -> libpcre2-8.so.0.13.0
/usr/lib64/libpcre2-8.so.0 -> libpcre2-8.so.0.13.0
/usr/lib64/libpcre2-8.so.0.13.0
/usr/lib64/libpcre2-posix.so -> libpcre2-posix.so.3.0.5
/usr/lib64/libpcre2-posix.so.3 -> libpcre2-posix.so.3.0.5
/usr/lib64/libpcre2-posix.so.3.0.5
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/libpcre2-16.pc
/usr/lib64/pkgconfig/libpcre2-32.pc
/usr/lib64/pkgconfig/libpcre2-8.pc
/usr/lib64/pkgconfig/libpcre2-posix.pc
/usr/share
/usr/share/doc
...
```

**Comment by jospezial** [comment]
[build.log](https://github.com/user-attachments/files/16575589/build.log)

**Comment by jospezial** [comment]
@bonsaiviking @dmiller-nmap @thesamesam Do we need to change something in Gentoo or does https://github.com/nmap/nmap/commit/c6ffdbf7ae35e397b663f787fc4934f01458f945 something wrong?

**Comment by nnposter** [comment]
This seems to me like a combination of a mistake on your end and a known bug:

First, your logs indicate that you might be running `configure` with `--with-pcre=/usr`, while the correct option is `--with-libpcre=/usr`. So, to `configure`, it looks like you did not specify any location explicitly.

It will try to find it, and it likely succeeded in the past, but https://github.com/nmap/nmap/commit/c6ffdbf7ae35e397b663f787fc4934f01458f945 introduced a bug, causing the header test not to work correctly. The fix for this defect has been already developed and it will be converted into a PR in the next few days. If you are anxious to look at it now, grab it from my private branch at https://github.com/nnposter/nmap/commit/1f2e0b9e89eade0150d68e09705cc3c2ab5bf641.

Then again, you likely want to fix how you invoke `configure` regardless. If you do that, you do not need to wait for the fix to get committed.

**Comment by nnposter** [comment]
@jospezial Feel free to give #2907 a spin and report back

**Comment by nnposter** [comment]
PR #2907 has been committed as r38963 (bef25962e7931b903d56b277f61ab3a0de9c00f5).
