### ISSUE TITLE
npcap.com and nmap.org are down

### ISSUE THREAD

**Issue by seladb** [nmap/nmap#2855]
**Describe the current behavior**
I'm not sure where is the right place to report this issue, but I couldn't find any other place. Both web-sites and all of their resources are down and not available. Are you aware of this issue? Any estimation of when they'll be up again?

**Expected behavior**
N/A

**Comment by fyodor** [comment]
We're sorry for the disruption.  Everything should be up and running now, but please let us know if you still see anything amiss.
