### ISSUE TITLE
VirusTotal detections in docs/Nmap-Third-Party-Open-Source.pdf

### ISSUE THREAD

**Issue by rdegraaf-ncc3** [nmap/nmap#2856]
VirusTotal thinks that [docs/Nmap-Third-Party-Open-Source.pdf](https://github.com/nmap/nmap/blob/master/docs/Nmap-Third-Party-Open-Source.pdf) contains malware: https://www.virustotal.com/gui/file/6846c8e862e812c1180750aea63509bb71dee80a51c6bcd8085900e02a23be46.  

Can you please check the file and its provenance? If you confirm it to be a false positive, please report your findings in this issue so that I have something to show corporate IT. I presume that it was generated from https://github.com/nmap/nmap/blob/master/docs/Nmap-Third-Party-Open-Source.fodt but I wasn't able to determine what tool or options you used.

**Comment by fyodor** [comment]
Thanks for the report. I generated the PDF myself using Libreoffice export from the fodt file so I'm sure it's a false positive. But I just regenerated with a newer Libreoffice and it doesn't get flagged, so I think that's the easiest way to solve this.  I just checked in a new copy to svn and it will sync to github shortly.  [Here's the clean VirusTotal report for the new version](https://www.virustotal.com/gui/file/ff463824f8145fb7f59ed2a26375d95b8c68566abf717d44d6e5219f1ed2b576).
