### ISSUE TITLE
ndiff: 'module' object has no attribute 'excepthook

### ISSUE THREAD

**Issue by malmoe** [nmap/nmap#286]
The installation of ndiff shipped with debian seems to be broken. A fresh installation did not solve this issue.

root@host:/usr/bin# ndiff Traceback (most recent call last): File "/usr/bin/ndiff", line 84, in sys.excepthook = ndiff.excepthook AttributeError: 'module' object has no attribute 'excepthook'

Running on a linux machine: root@host:/usr/bin# uname -a Linux hineta 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt17-1 (2015-09-26) x86_64 GNU/Linux

root@host:/usr/bin# /usr/bin/nmap --version

Nmap version 6.47 ( http://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.3 openssl-1.0.1k libpcre-8.35 libpcap-1.6.2 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

root@host:/usr/bin# python -c "import ndiff; print dir(ndiff); print ndiff.__file__"
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', 'difflib', 'fail', 'fcompare', 'fopen', 'main', 'restore', 'sys']
/usr/lib/python2.7/dist-packages/ndiff.pyc

**Comment by dmiller-nmap** [comment]
@malmoe This looks like a problem with the Debian package for Ndiff. I installed it and got a different error, because they didn't include the `ndiff` Python module that contains the actual code. It seems this is a known issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804193

**Comment by dmiller-nmap** [comment]
I'm closing this issue since Debian has marked theirs as resolved. It does not appear to be our problem.
