### ISSUE TITLE
nmap connecting to port 80 and port 443 with TCP on a udp scan

### ISSUE THREAD

**Issue by nathaniel-security** [nmap/nmap#2866]
**Describe the bug**
- when i tun a UDP scan NMAP also tries to connect on port 80 and port 443 with TCP 
**To Reproduce**
- open and start wireshark to capture the packets
- in the command line 
`sudo nmap -sU 142.250.193.174`
- IP address can be anything 
- in wireshark you will notice after the ping scan it tries to connect on port 80 and port 443 with TCP

![image](https://github.com/nmap/nmap/assets/48921869/b34fe62b-72db-4c0a-9ec0-551b9d0c3465)

**Expected behavior**

**Version info (please complete the following information):**
 - OS: Linux version 6.1.0-1parrot1-amd64 , Debian 10.2.1-6) 10.2.1 20210110
 - Output of `nmap --version`:
     - Nmap version 7.93

**Additional context**
- nothing

**Comment by nnposter** [comment]
Please review the host discovery section in the man page. Use option `-Pn` to disable host discovery.

**Comment by Zetdanur** [comment]
nmap -p 443
