### ISSUE TITLE
Inappropriate association of a Port Number with an Application

### ISSUE THREAD

**Issue by ullix** [nmap/nmap#2869]
**Describe the bug**
In this file https://github.com/nmap/nmap/blob/master/nmap-services I see this line:

`pumpkindb	9981/tcp	0.000000	# Event sourcing database engine with a built-in programming language`

This is very unfortunate and hopefully unintended by the pumpkindb community, as the port number is used for much longer (well over 10 years) by tvheadend .
Tvheadend is: "Tvheadend is the leading TV streaming server and recorder for Linux "
https://tvheadend.org/

In fact, tvheadend is using these 2 ports:
`9981
9982`

This inappropriate association of a port results in significant confusion of users like myself.

**To Reproduce**
running:  nmap server -p1-65000

**Expected behavior**
It should list the 2 ports given as primarily owned by tvheadend

**Version info (please complete the following information):**
$ nmap -V
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.2 nmap-libssh2-1.8.2 libz-1.2.11 libpcre-8.39 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.2
Release:	21.2
Codename:	victoria

**Comment by xmehulx** [comment]
Hey there! Would it be fine if both are added as both default to the same port?

**Comment by ullix** [comment]
@xmehulx that looks like a compromise. Over time, I believe we will see more of such problems.

**Comment by xmehulx** [comment]
And what if the port is really running pumpkindb and not tvheadend? As pumpkindb also defaults to 9981 as mentioned in their [documentation](http://pumpkindb.org/doc/) Why tvheadend should own the port?

**Comment by nnposter** [comment]
The association of port 9981 with `pumpkindb` is taken directly from [IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=9981), so this is what Nmap is going to report by default, unless overridden when performing version detection. See [RFC 6335](https://www.rfc-editor.org/rfc/rfc6335.html) on how the port association is established.
