### ISSUE TITLE
Discrepancy of target order between IPv6 and IPv4 scans

### ISSUE THREAD

**Issue by hugohue** [nmap/nmap#2878]
**Describe the bug**
- When setting `--min-rate` that is higher than `--max-hostgroup`, the order of targets is not randomized nor following the input list with `-iL`. The order for IPv4 addresses seems to be sorted by the least significant bit while the IPv6 addresses are sorted by the most significant bit.  

**To Reproduce**
- Run `sudo tcpdump -n -w <scan6.pcap>`
- Run `sudo nmap -6 -n -v -p80 --min-rate 11 --max-rate 11 --min-hostgroup 10 --max-hostgroup 10 --max-retries 0 -sS -Pn -iL <ipv6_addr_file>`
- Run `sudo tcpdump -n -w <scan4.pcap>`
- Run `sudo nmap -n -v -p80 --min-rate 11 --max-rate 11 --min-hostgroup 10 --max-hostgroup 10 --max-retries 0 -sS -Pn -iL <ipv4_addr_file>`
- Compare the scan order of two.

**Expected behavior**
- The target scan order is expected to follow the input address file or to be randomized.

**Version info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Output of `nmap --version`: 
 `Nmap version 7.95SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.4.6 openssl-1.1.1f nmap-libssh2-1.11.0 libz-1.2.11 nmap-libpcre2-10.43 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select`

**Additional context**
- Sorting the targets by the least significant bit could be a separate feature.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. What you are seeing is not any deliberate sorting, but rather a harmonic oscillation effect from instructing Nmap to send packets at a certain rate, while the scan engine itself attempts to spread the scan load equally across the systems being scanned.  On my system (with different performance characteristics), the targets appear to be randomized, even though I did not request randomization. Nmap's documentation does not make any claims about the order in which targets are scanned, though they tend to be scanned in sequence as they appear on the command line or in the input file. The `--randomize-hosts` option is offered as a stronger assurance that no such sequential ordering will happen during the scan, but that does not imply a strict ordering in its absence.
