### ISSUE TITLE
all IANA cipher suites

### ISSUE THREAD

**Issue by kylak** [nmap/nmap#2886]
Hello, does nmap uses all IANA cipher suites when using ssl-enum-ciphers ?

Thanks.

**Comment by xmehulx** [comment]
Hello, I noticed that interestingly some ciphers are extra, and not in IANA list, but these were the ones I found missing from TLS Cipher suites in Nmap:
- `0x00,0xFF   TLS_EMPTY_RENEGOTIATION_INFO_SCSV`
- `0x13,0x06   TLS_AEGIS_256_SHA512 [draft-irtf-cfrg-aegis-aead-08]`
- `0x13,0x07   TLS_AEGIS_128L_SHA256[draft-irtf-cfrg-aegis-aead-08]`
- `0x56,0x00   TLS_FALLBACK_SCSV `
I am not sure why they are missing, but if useful and needed (do let me know why), I can add them.

**Comment by nnposter** [comment]
Note that `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` and `TLS_FALLBACK_SCSV` are not cipher suites, but merely signaling that piggy-backs on the cipher suite negotiation mechanism.
