### ISSUE TITLE
nmap -sO parameter crash

### ISSUE THREAD

**Issue by termenti** [nmap/nmap#2908]
I get a crash - coredump with -sO parameter like this:
nmap -sO 127.0.0.1
nmap -sO -p- 127.0.0.1
nmap -sO -p 0-255 127.0.0.1

What nmap returns is:
nmap -sO -p- 127.0.0.1
Starting Nmap 7.95 ( https://nmap.org ) at 2024-08-12 14:07 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000016s latency).
Not shown: 249 closed n/a protocols (proto-unreach)
nmap: protocols.cc:194: const nprotoent* nmap_getprotbynum(int): Assertion `num >= 0 && num < UCHAR_MAX' failed.
Interrupted (coredump)

Command with is working is:
nmap -sO -p 0-254 127.0.0.1

**Comment by nnposter** [comment]
This is a known bug that has been already fixed in r38951 (efa0dc36f2ecade6ba8d2ed25dd4d5fbffdea308).
