### ISSUE TITLE
Nmap/nse_main.lua:829: 'ssl-crime' did not match a category, filename, or directory stack traceback:

### ISSUE THREAD

**Issue by jones11joseph** [nmap/nmap#2918]
nmap --script ssl-crime -p 443 XXXXXCCC.COM
Starting Nmap 7.95 ( https://nmap.org ) at 2024-08-22 10:14 ZZZZZ Standard Time
NSE: failed to initialize the script engine:
C:\Program Files (x86)\Nmap/nse_main.lua:829: 'ssl-crime' did not match a category, filename, or directory
stack traceback:
        [C]: in function 'error'
        C:\Program Files (x86)\Nmap/nse_main.lua:829: in local 'get_chosen_scripts'
        C:\Program Files (x86)\Nmap/nse_main.lua:1364: in main chunk
        [C]: in ?

QUITTING!

**Comment by nnposter** [comment]
Considering that script `ssl-crime` is not part of the Nmap distribution, what exactly is your issue?
