### ISSUE TITLE
Inconsistency when using "-sC" vs "--script default"

### ISSUE THREAD

**Issue by RaduNico** [nmap/nmap#2940]
**Bug Description**
When using `nmap -sV -sC --script ssh-auth-methods google.com` several scripts which are expected to run do not get executed (ssl-date, http-server-header, tls-alpn). When running nmap with `nmap -sV --script default --script ssh-auth-methods google.com` the before mentioned scripts do get executed.

This issue was observed in a larger context as well. When using `nmap -sV -sC --script ssh-auth-methods -iL scope`, several  scripts which are usually executed got completely skipped (rdp-ntlm-info, ms-sql-ntlm-info, smb2-security-mode). The same issue would not occur if `--script default` was used instead of `-sC`.

**To Reproduce**
The following commands can be used in order to reproduce the issue
```
# Baseline for which scripts should run
nmap -p443 -sV -sC -vvv -oN baseline.txt -oX baseline.xml google.com    

# It can be observed that multiple NSE scripts do not get executed when compared with the baseline
nmap -p443 -sV -sC --script ssh-auth-methods -vvv -oN short_default.txt -oX short_default.xml google.com

# The same behavior is not present. Most scripts do get executed
nmap -p443 -sV --script default --script ssh-auth-methods -vvv -oN long_default.txt -oX long_default.xml google.com
```
Steps to reproduce the behavior, including command-line options.

**Expected behavior**
There should not be any difference when using either -sC or --script default, since the man page specifies `-sC: equivalent to --script=default `. In a larger sense, the expected behavior when using the flag "-sC" with other scripts is that both default and the specified scripts should get executed

**Version info**
The version of nmap is the one compiled from this repository at the time of writing:
```
$ nmap --version
Nmap version 7.95SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.4.6 openssl-1.1.1f nmap-libssh2-1.11.0 libz-1.2.11 libpcre2-10.34 libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
$ uname -a
Linux hostname 5.4.0-196-generic #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

I've added the files which resulted from the commands for reference:
* Baseline `-sC`
[baseline.txt](https://github.com/user-attachments/files/17046913/baseline.txt)
[baseline_xml.txt](https://github.com/user-attachments/files/17046954/baseline_xml.txt)
* Short default `-sC --script ssh-auth-methods`
[short_default.txt](https://github.com/user-attachments/files/17046914/short_default.txt)
[short_default_xml.txt](https://github.com/user-attachments/files/17046966/short_default_xml.txt)
* Long default `--script default --script ssh-auth-methods`
[long_default.txt](https://github.com/user-attachments/files/17046912/long_default.txt)
[long_default_xml.txt](https://github.com/user-attachments/files/17046957/long_default_xml.txt)

Edit: Accidentally posted the thread before finishing to write it.

**Comment by nnposter** [comment]
Roughly speaking, executed scripts are determined by a union of all instances the `--script` argument. Total absence of the `--script` argument triggers a default value of `default` (as long as script scanning is requested via `-sC` in the first place). Furthermore, if version scan is prescribed, `-sV`, then all the scripts in the `version` category are also added.

Specifically, `-sC` behaves just like `--script default`, as long as not overridden by an explicit `--script`.

In your case:

> `nmap -p443 -sV -sC -vvv -oN baseline.txt -oX baseline.xml google.com`

All scripts categorized as `default` and/or `version` are executed.

> `nmap -p443 -sV -sC --script ssh-auth-methods -vvv -oN short_default.txt -oX short_default.xml google.com`

Script `ssh-auth-methods` and all scripts categorized as `version` are executed. Argument `-sC` serves no purpose here; it is implied by `--script`.

> `nmap -p443 -sV --script default --script ssh-auth-methods -vvv -oN long_default.txt -oX long_default.xml google.com`

Script `ssh-auth-methods` and all scripts categorized as `default` and/or `version` are executed. Argument `-sC` serves no purpose here; it is implied by `--script`.

**Comment by RaduNico** [comment]
Then I believe the manual page should reflect that using the flag "-sC" is not equivalent to using "--script default" and that behavior can change depending on what scripts are selected. Currently the manual page states:
"Performs a script scan using the default set of scripts. **It is equivalent to --script=default.**" . This is obviously not the case if using "-sV -sC --script ssh-auth-methods" does not in fact run the scripts categorized as `default`.
