### ISSUE TITLE
nmap --script vuln won't include vulners scan.

### ISSUE THREAD

**Issue by gobiursus** [nmap/nmap#2946]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
When you execute `nmap --script vuln $hostname` vulners will not be used although vulners is a part of category vuln. It was usable during 2022 on Kali Linux

**To Reproduce**
Steps to reproduce the behavior, including command-line options.
`nmap --script vuln $hostname`

**Expected behavior**
Trigger scripts under category `vuln` include vulners.nse

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nmap --version`:
```
Nmap version 7.94SVN ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.4.6 openssl-3.3.2 libssh2-1.11.0 libz-1.3.1 libpcre2-10.42 libpcap-1.10.5 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
 - Output of `nmap --iflist`:
 

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by nnposter** [comment]
Script `vulners` works by inferring vulnerabilities from collected version numbers on scanned ports. This dependency is *not* automatically triggering a version scan. As a result, adding version scan (option `-sV`) should take care of the issue.

Put differently, category `vuln` indeed *does* include script `vulners` but the script disqualifies itself if it does not find version info for a given port.
