### ISSUE TITLE
npcap install should uninstall prior version when installing new version

### ISSUE THREAD

**Issue by markpizz** [nmap/nmap#295]
Historically when a version of WinPcap was installed, the prior version is explicitly uninstalled.

Today I tried to install npcap-nmap-0.05-r10 on a system which already had npcap-nmap-0.05-r7 already installed I was prompted with a message box that says:

"Npcap version 0.5.0.912 already exists on this system.  Reinstall this version?"  Yes/No

What actually happened after seeing this message and clicking Yes was the right thing (uninstall followed by an install), but the message itself is at least confusing.  The wording should be changed.

**Comment by hsluoyz** [comment]
Hi. After you choose ``Yes`` for ``Npcap version 0.5.0.912 already exists on this system. Reinstall this version?``. Npcap will first uninstall the old version, then prompt a new window to install the current version. "Reinstall" actually means both "Uninstall" and "Install" I think?

**Comment by markpizz** [comment]
Hi Yang,

If you read my entire message, your response confirmed exactly what i described which was correct and reasonable behavior.  

The point of the message is that "The wording should be changed".  It should say something like: "Uninstall the currently installed Npcap and install version xxxx?"

**Comment by hsluoyz** [comment]
Hi. There may be a misunderstanding here. There's two wordings in Npcap:
1. When you install a different version Npcap with one already installed, the wording is ``Npcap version 0.5.0.912 exists on this system. Replace with version 0.X.X.XXX?``
2. When you install the same version, the wording is ``Npcap version 0.5.0.912 already exists on this system. Reinstall this version?``

So "Reinstall" in condition 2 actually means uninstall 0.5.0.912 and install 0.5.0.912 again.  I just think I don't need to write the same version string twice.

And it's notable that revision in Npcap is not recognized in installer. This means Npcap 0.05-r9 and Npcap 0.05-r10 are both recognized as 0.5.0.912 in the installer. So the installer will think you are reinstalling the same version which is apparently not true.
