### ISSUE TITLE
/usr/bin/../share/nmap/scripts/broadcast-dhcp-discover.nse:170: attempt to index a boolean value

### ISSUE THREAD

**Issue by e-Gyi-qO** [nmap/nmap#2961]
**Describe the bug**
/usr/bin/../share/nmap/scripts/broadcast-dhcp-discover.nse:170: attempt to index a boolean value

**To Reproduce**
nmap -d --script broadcast-dhcp-discover

**Expected behavior**
Does an attempt to index a boolean value is a problem by itself, no matter what the other circumstances are?
Eventually I hope to get the offer of the dhcp server. I am not sure there are no other issues. Possibly I am doing something wrong.

**Additional context**
```
Starting Nmap 7.95 ( https://nmap.org ) at 2024-11-09 22:58 UTC
PORTS: Using ports open on 0% or more average hosts (TCP:1000, UDP:0, SCTP:0)
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.4.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 22:58
NSE: Starting broadcast-dhcp-discover.
NSE: broadcast-dhcp-discover threw an error!
/usr/bin/../share/nmap/scripts/broadcast-dhcp-discover.nse:170: attempt to index a boolean value
stack traceback:
	/usr/bin/../share/nmap/scripts/broadcast-dhcp-discover.nse:170: in function </usr/bin/../share/nmap/scripts/broadcast-dhcp-discover.nse:131>

NSE: Finished broadcast-dhcp-discover.
Completed NSE at 22:58, 0.05s elapsed
NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 22:58
Completed NSE at 22:58, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-protocols nmap-services.
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.20 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)
```
As an aside, additional context for me is [most popular answer](https://serverfault.com/a/875791) at [command-line-program-to-test-dhcp-service](https://serverfault.com/questions/171744/command-line-program-to-test-dhcp-service)

**Comment by nnposter** [comment]
This script went through some changes since the last official release. Please replace all files in folder `nselib` and this script with the latest versions from SVN or GitHub and try again.

**Comment by e-Gyi-qO** [comment]
> This script went through some changes since the last official release. Please replace all files in folder `nselib` and this script with the latest versions from SVN or GitHub and try again.

I am sorry. I can not find the time for doing that. Not abandoned but low priority on my side.
