### ISSUE TITLE
Fingerprint and actual packet byte are different

### ISSUE THREAD

**Issue by xiaoyuer11223344** [nmap/nmap#2963]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**

`nmap -sV 117.160.128.60 -p 1251 -Pn --packet-trace -vvv`

The situation is like this, because I am https://github.com/nmap/nmap/blob/master/nmap-service-probes I saw that the probe corresponding to Oracle TNS is as follows, but I found that the actual packet sending situation will be converted from \ x04 to \ x34. What is the reason for this?

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/46322a01-eb76-46f7-a311-6061d55960d1">

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/71845204-7653-4e38-83df-85ddae5cc432">

**To Reproduce**
Steps to reproduce the behavior, including command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nmap --version`:
 - Output of `nmap --iflist`

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by liquidpele** [comment]
Because that's the hex for the character 4.   Try it out.  https://onlinestringtools.com/convert-string-to-hexadecimal
