### ISSUE TITLE
Allow user to force traceroute to closed ports

### ISSUE THREAD

**Issue by elipsion** [nmap/nmap#2975]
**Describe the current behavior**
When doing a traceroute, nmap requires the target port to be responding.

**Expected behavior**
When troubleshooting firewalls, I would like to be able to force a traceroute to closed ports, to see where along the path that the packet is dropped.

**Comment by nnposter** [comment]
Do you truly mean "closed" ports, where you receive either TCP RST or ICMP type 3 response, or "filtered" ports, where packets are silently getting dropped without any indication?

If the former, what exactly would you want? TCP RST will come with your target IP address as the source, even if spoofed, so there is no useful information there. ICMP type 3 is more useful but typically seen only with UDP or old-fashioned router ACLs.

If the latter, you can use the `firewalk` script, as long as you can traceroute the target somehow, either through ICMP or another open or closed port. Here is an example, where 443/tcp is reachable but 445/tcp is not:

```
$ nmap -Pn -p443,445 --script=firewalk --traceroute 192.168.0.9
Starting Nmap 7.95SVN ( https://nmap.org ) at 2024-12-01 16:07 PST
Nmap scan report for 192.168.0.9
Host is up (0.00056s latency).

PORT    STATE    SERVICE
443/tcp closed   https
445/tcp filtered microsoft-ds

Host script results:
| firewalk:
| HOP  HOST           PROTOCOL  BLOCKED PORTS
|_2    192.168.333.1  tcp       445

TRACEROUTE (using port 443/tcp)
HOP RTT     ADDRESS
1   0.56 ms 192.168.222.1
2   0.51 ms 192.168.333.1
3   0.16 ms 192.168.444.1
4   0.48 ms 192.168.0.9

Nmap done: 1 IP address (1 host up) scanned in 9.53 seconds
```

**Comment by nnposter** [comment]
This is how you can do it with Nping by hand.

TTL 3 is one hop past the firewall. 443/tcp is open so we get ICMP type 11.
```
$ nping -c1 --tcp -p443 --ttl 3 192.168.0.9

Starting Nping 0.7.95SVN ( https://nmap.org/nping ) at 2024-12-01 17:06 PST
SENT (0.0217s) TCP A.B.C.D:2950 > 192.168.0.9:443 S ttl=3 id=33844 iplen=40  seq=3652725308 win=1480
RCVD (0.0219s) ICMP [192.168.444.1 > A.B.C.D TTL=0 during transit (type=11/code=0) ] IP [ttl=253 id=19311 iplen=68 ]

Max rtt: 0.154ms | Min rtt: 0.154ms | Avg rtt: 0.154ms
Raw packets sent: 1 (40B) | Rcvd: 1 (68B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 1.06 seconds
```
In contrast, 445/tcp is blocked, so we get no response:
```
$ nping -c1 --tcp -p445 --ttl 3 192.168.0.9

Starting Nping 0.7.95SVN ( https://nmap.org/nping ) at 2024-12-01 17:04 PST
SENT (0.0291s) TCP A.B.C.D:58204 > 192.168.0.9:445 S ttl=3 id=42928 iplen=40  seq=830369512 win=1480

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
Raw packets sent: 1 (40B) | Rcvd: 0 (0B) | Lost: 1 (100.00%)
Nping done: 1 IP address pinged in 1.06 seconds
```
Now we confirm the hop where the probe is dying by decrementing TTL and receiving a response:
```
$ nping -c1 --tcp -p445 --ttl 2 192.168.0.9

Starting Nping 0.7.95SVN ( https://nmap.org/nping ) at 2024-12-01 17:03 PST
SENT (0.0193s) TCP A.B.C.D:36167 > 192.168.0.9:445 S ttl=2 id=36036 iplen=40  seq=143548808 win=1480
RCVD (0.0200s) ICMP [192.168.444.1 > A.B.C.D TTL=0 during transit (type=11/code=0) ] IP [ttl=254 id=36036 iplen=56 ]

Max rtt: 0.627ms | Min rtt: 0.627ms | Avg rtt: 0.627ms
Raw packets sent: 1 (40B) | Rcvd: 1 (56B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 1.05 seconds

```
