### ISSUE TITLE
Word Misspelling

### ISSUE THREAD

**Issue by webdevyan** [nmap/nmap#2999]
Hi there! Thank's for doing a great job with nmap (I love this tool)

I just want you to let you know guys about a misspelling (word: "Man" instead of "Main") on the welcome page of nmap from the terminal, I will attach a screenshot, So you know what I mean.

hope this is useful for you guys, thank's again!
![Screenshot_2024-12-22_18_06_41](https://github.com/user-attachments/assets/23c7d2ce-4134-427f-bc22-0f549a2bd14e)

**Comment by 2tokui** [comment]
It is correct, "man page" means manual page.

**Comment by webdevyan** [comment]
Oh ok! Nice! I got it now! Thanks
