### ISSUE TITLE
Make Ncat warn about certificate trust issues even without --ssl-verify

### ISSUE THREAD

**Issue by bonsaiviking** [nmap/nmap#30]
From [the Nmap TODO file](../tree/master/todo/nmap.txt):
>Change Ncat so that it does SSL certificate trust checking by 
  default (even without --ssl-verify) and provides a warning and the key
  fingerprint if there is no valid trusted chain or the cert is
  expired, etc.  The warning should happen (to STDERR) even if -v is
  not specified.

This is also in the TODO file, but the design decision is not firm:
> We should add a new option to force Ncat to quit if
  cert not valid, and --ssl-verify should become an undocumented alias
  for that.

**Comment by nmapster** [comment]
I don't think the 2nd part is needed since Ncat already does quit with --ssl-verify if cert is invalid.  We might have thought it only gave a warning in that case or something.
