### ISSUE TITLE
NMap Syn Scan Crashes VMs on Mac OSX

### ISSUE THREAD

**Issue by ChrisTruncer** [nmap/nmap#303]
Hi there,

I realize this is a bit of an odd bug report, but I thought it was worth submitting.  I believe there must have been some updates to nmap, and possibly how it performs Syn scans.  I typically run NMap within a VM on Debian, Kali, or some other linux distro.  When using the latest version of NMap that's on the website (7.01 as of now), I've been trying to perform a top 1000 port scan against a class C (/24) network.

Once it gets about halfway through, the entire VM crashes.  This is reproducible across multiple different VMs, but all within VMWare Fusion on Mac OSX.  This has been tested on Kali, Debian, and Ubuntu, and any syn scan of a /24 network with top 1000 ports completely crashes the box.

It's not tied to just the top 1000 ports, it also happens once it hits a certain limit on a top 100.

Some research online (thanks to @g0tmilk) returned this:
https://twitter.com/DavidJBianco/status/692865313637998592

and this:
https://twitter.com/DavidJBianco/status/692884879080443904

So, I know this is kind of a hard bug to fix, look into, but right now NMap is essentially unusable on a Mac when virtualized.  Any possibility this might be looked into?

**Comment by dmiller-nmap** [comment]
My initial take is that this is not our bug: it's a resource exhaustion problem with VMware, as evidenced by the second status you linked referring to hitting an open-file/socket limit in the *host* OS. But we'd need more info to determine either way. Open questions:

1. Does this happen with older versions of Nmap, too, or only recent ones? If only recent versions, what version is the first to show the problem?
2. What network settings are used for the VM? Bridged, NAT, Host-only, etc. There are often problems with NAT slowing down scans. Bridged adapters are the least likely to cause problems like this.
3. Have you filed a bug report with VMware for this issue? It seems like a VM crash like this would be something they'd want to deal with. More so if it affects any other running VMs.

Some possible suggestions:

1. Have you tried installing VMware Tools on your guest? I don't know of any directly applicable changes this would help with, but it might help.
2. Can you check or increase the maximum number of open files and sockets in your host OS? Here's a [guide to doing so on OS X](http://b.oldhu.com/2012/07/19/increase-tcp-max-connections-on-mac-os-x/) that I have not vetted at all. Similarly, check if there's an artificial limit on the hypervisor process responsible for network stuff.
3. Does reducing parallelism with `--max-parallelism` help? Setting it to something well below the maximum files limit would be necessary.

**Comment by ChrisTruncer** [comment]
I think for the time being you are correct.  I was just finally able to replicate the issue with another tool other than NMap (I wasn't able to do that previously).  This leads me to believe, like you suggested, that it is more oriented to VMWare vs. any recent change to nmap.

Thanks for taking the time to respond, I appreciate it.

**Comment by leebaird** [comment]
Running an nmap scan with the Network Adapter set to NAT, crashes my VM in about 30 sec.
Switching it to Bridged seems to work.
