### ISSUE TITLE
Npcap does not see vmware vmnet8 adapter

### ISSUE THREAD

**Issue by zdm** [nmap/nmap#338]
Hi.

Npcap 0.06-r71 is installed in winpcap compatible mode.
I don't see VmWare network interface in wireshark, but it appears, if I am using winpcap.

![screenshot 2016-03-16 07 04 15](https://cloud.githubusercontent.com/assets/1025608/13802560/ca9b1c4c-eb45-11e5-8aad-bec91a4119f8.png)

![screenshot 2016-03-16 07 04 41](https://cloud.githubusercontent.com/assets/1025608/13802564/d2a8e4b4-eb45-11e5-9b9f-6fc5656914aa.png)

**Comment by hsluoyz** [comment]
Hi,

Please use the lastest Npcap 0.06-r72:
https://github.com/nmap/npcap/releases

**Comment by zdm** [comment]
Thank you!
