### ISSUE TITLE
[Npcap] pcap_snaplen() isn't working well

### ISSUE THREAD

**Issue by Komosa** [nmap/nmap#339]
Hi all,
there is commonly known bug, that pcap_snaplen doesn't work with winpcap, and there is commonly known workaround for this: set empty filter for sniffing after call to activate.

This setting-empty-filter trick stopped to work with npcap.
More detailed info:
since npcap 0.05 (r1) some packets are snapped, but not all of them;
this behavior continues to be observable up to npcap 0.06 (r1) (inclusive).

Since npcap 0.06 r2 behavior is better, way more packets is being snapped (but still not all).
This is being observable also for 0.06 r3 and r4. (observable caplens: 134, 276, 342, 1392, 1484, 1486, 1490, 1514).

Since npcap 0.06 r5 (also in r6, I could not test r7) problem is even worse - some packets are not snapped, resulting in ~1500bytes packets, but most of them are snapped at really short level (most commonly 16 (!) bytes).

Scenario: set snaplen to 123.
Procedure is: create() set_promisc(0) set_timeout(250) set_snaplen(123) activate() set_nonblock(1) filter("") dispatch() - I will publish examplary tool and comment.

I ran those tests also with libpcap on linux, it works (although snapping at 122).

**Comment by Komosa** [comment]
https://github.com/Komosa/use-pcap - code for reproduction.

**Comment by hsluoyz** [comment]
Hi Komosa,

> Since npcap 0.06 r5 (also in r6, I could not test r7) problem is even worse - some packets are not snapped, resulting in ~1500bytes packets, but most of them are snapped at really short level (most commonly 16 (!) bytes).

DO NOT USE 0.06 R5, R6 and the original R7. They have a severe bug that causes captured malformed packets. Please use the latest R7.2 for testing.

**Comment by hsluoyz** [comment]
Hi @Komosa ,

I have fixed the ``pcap_snaplen() isn't working for outgoing packets`` issue in Npcap 0.06 R9, please try the lastest installer at:
https://github.com/nmap/npcap/releases
