### ISSUE TITLE
redis-brute script maybe error

### ISSUE THREAD

**Issue by sechacking** [nmap/nmap#358]
login = function( self, username, password )
    local status, response = self.helper:reqCmd("AUTH", password)

    -- some error occurred, attempt to retry
    if ( status and response.type == redis.Response.Type.ERROR and
      "-ERR invalid password" == response.data ) then
      return false, brute.Error:new( "Incorrect password" )
    elseif ( status and response.type == redis.Response.Type.STATUS and
      "+OK" ) then
      return true, creds.Account:new( "", password, creds.State.VALID)
    else
      local err = brute.Error:new( response.data )
      err:setRetry( true )
      return false, err
    end

  end,

username has no used.and nmap can not work it.

**Comment by tremblerz** [comment]
[Here](https://github.com/nmap/nmap/blob/master/scripts/redis-brute.nse#L108) it is set to use password only and hence we don't username anywhere. Correct me if I am missing something.

**Comment by cldrn** [comment]
Yes, redis auth system is only password based. No username is required/available. This ticket can be closed now.  cc @bonsaiviking
