### ISSUE TITLE
[NSE] rpcinfo breaks when encountering TCP protocol 0

### ISSUE THREAD

**Issue by TomSellers** [nmap/nmap#363]
The **rpcinfo.nse** script crashes when gathering information from certain IPv6 enabled installations even if the target is scanned via its IPv4 address.  This is due to the script trying to process an unexpected protocol type: 0.  IP protocol ID 0 is HOPOPT / IPv6 Hop-by-Hop Option. Information on this can be found at the links at the bottom of this Issue.  The code that is crashing performs actions that can be skipped for protocol 0 so working around it for this script is trivial.  My concern is that this needs to be reviewed to ensure broader changes are implemented if required.

Simplest command to reproduce

`nmap -n -d --script=rpcinfo.nse  -p 111 <target>`

Error Message

```
NSE: rpcinfo M:434AE38 against 192.168.270.10:111 threw an error!
C:\Users\Test\Documents\nmap-7.12/scripts\rpcinfo.nse:97: port 'protocol' field must be "udp", "sctp" or "tcp"
stack traceback:
        [C]: in function 'get_port_state'
        C:\Users\Test\Documents\nmap-7.12/scripts\rpcinfo.nse:97: in function <C:\Users\Test\Documents\nmap-7.12/scripts\rpcinfo.nse:84>
        (...tail calls...)
```

The relevant code is line 97 in **rpcinfo.nse**: 

```
96    for proto, v2 in pairs(v) do
97      local nmapport = nmap.get_port_state(host, {number=v2.port, protocol=proto})
98      if nmapport and (nmapport.state == "open" or nmapport.state == "open|filtered") then
```
Direct link:  https://github.com/nmap/nmap/blob/0ac6e525237300792f12b74c35e75c171b5ce3ea/scripts/rpcinfo.nse#L96-L98

Here is an example of the variable **v** that the code is iterating over:

```
udp:
  version:
    1: 2
    2: 3
    3: 4
  port: 111
tcp:
  version:
    1: 2
    2: 3
    3: 4
  port: 111
0:
  version:
    1: 2
    2: 3
    3: 4
  port: 111
```

When `nmap.get_port_state` gets called with protocol 0 from variable **'v'** above it triggers this section of code in **nse_utility.cc**:

```
196 protocol = strcmp(lua_tostring(L, -1), "tcp") == 0 ? IPPROTO_TCP :
197            strcmp(lua_tostring(L, -1), "udp") == 0 ? IPPROTO_UDP :
198            strcmp(lua_tostring(L, -1), "sctp") == 0 ? IPPROTO_SCTP :
199            luaL_error(L, "port 'protocol' field must be \"udp\", \"sctp\" or \"tcp\"");
```

Direct link:  https://github.com/nmap/nmap/blob/0ac6e525237300792f12b74c35e75c171b5ce3ea/nse_utility.cc#L196-L199

This code is unable to account for a protocol name of **'0'** and so generates the error.

As I said at the start, it's trivial to work around this in **rcpinfo.nse**. My concern is that other sections of code may need to be adjusted as well.  

Thoughts?

Reference:
 1. IP Protocol number list
    https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers

 2. Assigned Internet Protocol Numbers
    http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

 3. IP Protocol 0, Hop by Hop Options
   https://en.wikipedia.org/wiki/IPv6_packet#Hop-by-hop_options_and_destination_options

 4. RCF 2460, Page 11, Section 4.3 - Hop-by-Hop Options Header
    http://tools.ietf.org/html/rfc2460#page-11

**Comment by TomSellers** [comment]
Per request by @bonsaiviking on the dev mailing list, here is an example of using **rpcinfo** against one of these hosts:

```
rpcinfo -p 
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100000    4     0    111  portmapper
    100000    3     0    111  portmapper
    100000    2     0    111  portmapper


rpcinfo -s 
   program version(s) netid(s)                         service     owner
    100000  2,3,4     local,udp6,tcp6,udp,tcp          portmapper  superuser
```

**Comment by dmiller-nmap** [comment]
Looks like various implementations use different numeric mappings for "local" protocols/netids. Linux shows `0` as @TomSellers shows, and output of rpcinfo (using version 3 or 4) is:

    100000    4    local     /v                     portmapper superuser
    100000    3    local     /v                     portmapper superuser
    100000    2    local     /v                     portmapper superuser

Whereas a FreeBSD system uses `7` for portmapper version 2, but version 3 or 4 gives:

    100000    4    local     /var/run/rpcbind.sock  portmapper superuser
    100000    3    local     /var/run/rpcbind.sock  portmapper superuser
    100000    2    local     /var/run/rpcbind.sock  portmapper superuser

I've chosen to just report the protocol numerically, as `rpcinfo -p` does. It'd be nice if we could gather version 3 info if available, too/instead.
