### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by davidsilveiro** [nmap/nmap#374]
Within src/file.c:229 **fp** contributes to a resource leak. Consider using fclose() earlier in the function.

**Comment by dmiller-nmap** [comment]
@davidsilveiro Can you clarify what source file you are referring to? Nmap does not have a file named `file.c`

**Comment by davidsilveiro** [comment]
@dmiller-nmap So sorry buddy, I had been looking for bugs within nmap, and a few others projects. I mistakenly got jumbled up >_< 

This was a mistake on my end, there's no resource leak.

Sorry for the trouble
