### ISSUE TITLE
Support decimal-IP notation for destination in Ncat

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#375]
Both traditional (Hobbit) and OpenBSD netcat support using IPv4 address in decimal notation as a destination address. Example:

```
$ host nmap.org
nmap.org has address 45.33.49.119
$ nc.openbsd $((45 * 256**3 + 33 * 256**2 + 49 * 256 + 119)) 22
SSH-2.0-OpenSSH_6.6.1
```

At least one user has complained of this on IRC. Ncat gives this error instead:

```
Ncat: You must specify a host to connect to. QUITTING.
```

**Comment by bensherman** [comment]
The specific use case for me is using 0 in place of 0.0.0.0.

**Comment by fyodor** [comment]
I'm not totally against this, but I'm also not sure we really need to support an obsolete syntax just because some other ancient tools do.  Then again, I just tested the Chrome web browser and it allowed me to reach nmap.org at https://757150071/.  If "0" is the only specific use case anyone has, maybe we could just special case that?  Is there anyone who might use this in other situations than "0"?

**Comment by dmiller-nmap** [comment]
Further testing reveals only decimal numbers are failing to work: converting to hex works just fine:

```
$ ./ncat/ncat 0x2d213177 22
SSH-2.0-OpenSSH_6.6.1
```

We're actually specifically checking for a non-digit character to distinguish hostname from port number in ncat_main.c:

```c
        /* Resolve hostname if we're given one */
        if (strspn(argv[optind], "0123456789") != strlen(argv[optind])) {
/*<snip>*/
        } else {
            if (!o.listen)
                bye("You must specify a host to connect to.");
        }
```

This is to avoid ambiguity: `ncat -l 22`; does this mean "listen on all addresses on port 22" or "listen on 0.0.0.22 on port `DEFAULT_NCAT_PORT`"? If the former, then there is no way to use decimal address for listen address. If the latter, then we break compatibility with other netcats. A better solution would be to always treat a digits-only *last* argument as a port number.

**Comment by Varunram** [comment]
Yeah but that'd mean people can not exchange arguments right? For e.g. 
```
ncat -l 8001
ncat 8001 -l
```
Might cause a few more problems while specifying ports since some might be accustomed to specifying the port in-between.

**Comment by Varunram** [comment]
But that might break the command flexibility for some right?

**Comment by bensherman** [comment]
robots are going to end us all
