### ISSUE TITLE
DEBUG message shown in -vv mode?

### ISSUE THREAD

**Issue by fschwarzer** [nmap/nmap#384]
Hi,

I am not sure if this is an issue, just noticed this as odd.

When I am using the -vv (two v's) option, I get a DEBUG message. Since other DEBUG messages only join the game with -vvv (three v's), I wondered ...

Here's the output with one connection happening:

$ while true; do while true; do echo "$(fortune)"; sleep 1; done | ncat -vv -l 9999; done
Ncat: Version 7.12 ( https://nmap.org/ncat )
Ncat: Listening on :::9999
Ncat: Listening on 0.0.0.0:9999
Ncat: Connection from ::1.
Ncat: Connection from ::1:33746.
NCAT DEBUG: Closing connection.   # <== See? Seems needlessly lonely here. :)
Ncat: Version 7.12 ( https://nmap.org/ncat )
Ncat: Listening on :::9999
Ncat: Listening on 0.0.0.0:9999

**Comment by dmiller-nmap** [comment]
I checked, and this call to `logdebug` is properly guarded with a check of `o.debug`. Ncat considers 1 `-v` to be "verbose," and each additional `-v` increases the debug level by one. Most debug statements are guarded with `if (o.debug > 1)` which means `-vvv` or higher, but not all.
