### ISSUE TITLE
Npcap Loopback Adapter  Windows 10 wireshark 不能抓取 127.0.0.1的数据包

### ISSUE THREAD

**Issue by rinetd** [nmap/nmap#388]

**Comment by hsluoyz** [comment]
你好，

你用的Npcap是什么版本？安装时是否勾选了``Support loopback traffic ("Npcap Loopback Adapter" will be created)``选项？在Wireshark里是否看到了Npcap Loopback Adapter？如果没有，那不能抓取的现象是什么呢？

**Comment by hsluoyz** [comment]
As there's no further feedback on this post for 5 days, I'd like to close it for now.

**Comment by rinetd** [comment]
谢谢 ！不好意思

 问题解决了，步骤如下：
1.卸载原来的winpcap
2.安装的时候 **最后一项**一定要勾选
 【install Npcap in Winpcap API-Compatible Mode 】
 当然
【Support loopback traffic ("Npcap Loopback Adapter" will be created)】
也是必须要勾选的
最后再次谢谢@hsluoyz 做出这么优秀的软件

**Comment by LuckeX** [comment]
我安装的npcap是0.99-r5，为什么不能选择【Support loopback traffic ("Npcap Loopback Adapter" will be created)】 这个选项

**Comment by hsluoyz** [comment]
@LuckeX please in English.

**Comment by dmiller-nmap** [comment]
Duplicate of #1244
