### ISSUE TITLE
Disable ethernet while using npcap cause system freeze

### ISSUE THREAD

**Issue by ekkolord** [nmap/nmap#391]
Windows 10 10586.164 64-bit 
Npcap 0.07 r6

Reproduce: 
Method 1: Use wireshark, then go to Network Connections, right-click Ethernet, disable, system freeze.
Method 2: Use wireshark, then connect to a VPN, system freeze.

Winpcap dont have this problem.

**Comment by hsluoyz** [comment]
Hi @ekkolord ,

Thanks for the report! I have fixed this issue in Npcap 0.07 r8. See:
https://github.com/nmap/npcap/releases
