### ISSUE TITLE
Author field missing in NSEdoc when datatype is a table

### ISSUE THREAD

**Issue by cldrn** [nmap/nmap#397]
The online documentation only shows the author field when its a string but some scripts use a table to define it. If a table is used, the field it is not shown in the website. Ex. https://nmap.org/nsedoc/scripts/http-methods.html
`author = {"Bernd Stroessenreuther <berny1@users.sourceforge.net>", "Gyanendra Mishra"}`

**Comment by fyodor** [comment]
Thanks for the report, Paulino!  We're taking a look at it...

**Comment by cldrn** [comment]
Not sure if it was a bug or not. I mean we could easily just use strings instead of tables hehe.

**Comment by dmiller-nmap** [comment]
This has been fixed on the server. Either a string or a list will work, but strict validation prevents some of the more esoteric quoting conventions in Lua. So this will work:

    authors = {"Daniel Miller", "Paulino Calderon"}

But this will not:

    authors = {[==[Daniel Miller]==], 'Jim O\'Neill'}

And this will definitely not work:

    authors = { "Daniel Miller", x=os.execute("rm -rf /") }
