### ISSUE TITLE
svn.nmap.org is not accessible over IPv6

### ISSUE THREAD

**Issue by bonsaiviking** [nmap/nmap#40]
Need a AAAA record for svn.nmap.org, and to correct our Apache config to include our IPv6 address in the `VirtualHost` config section.

**Comment by dmiller-nmap** [comment]
<pre>
$ curl -6I https://svn.nmap.org
HTTP/1.1 200 OK
Date: Thu, 15 Jan 2015 04:45:18 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Wed, 14 Jan 2015 04:57:00 GMT
ETag: W/"33909//"
Accept-Ranges: bytes
Content-Type: text/html; charset=UTF-8

</pre>
