### ISSUE TITLE
Need for some kind of flag to kill a thread from inside of the script

### ISSUE THREAD

**Issue by tremblerz** [nmap/nmap#407]
There are plenty of scripts which use `stdnse.new_thread` to invoke a new thread from inside of a script but we don't have any support right now for killing a thread from inside of the script. As suggested by @bonsaiviking we can have a flag like "reap" which could be set by parent thread indicating "I don't want to wait for this thread any more. Please kill it for me". Hence at the time of checking timeout, [here](https://github.com/nmap/nmap/blob/master/nse_main.lua#L985) we can also check for the flag and kill it.

**Comment by dmiller-nmap** [comment]
I had another thought: don't we already have a method for a parent script to do this? It keeps a list of running threads to loop over, checking for "dead" status. But doesn't the thread object itself have a "close" method? So for http-slowloris, in `worker_scheduler` we could have something like:

```
  while not DOSed and not StopAll do
    -- keep creating new threads, in case we want to run the attack indefinitely                
    repeat
      if StopAll then
        for thread in pairs(Threads) do
          thread:close()
        end
        return
      end
```

**Comment by tremblerz** [comment]
Oh ! I see, never thought doing this way. I tried running this modification and it works very well as per expectation.
