### ISSUE TITLE
Npcap (0.07-r11) - installation fails on Server 2008 R2 SP1

### ISSUE THREAD

**Issue by simgar** [nmap/nmap#409]
I'm trying to install Npcap 0.07-r11 on a Server 2008 R2 SP1 machine which had Wireshark-win64-2.0.3 with WinPcap 4.1.3 installed.  I've made several attempts with the same results, uninstalling each time.  I can't find an installation log file to post here so I've attempted the installation again.  This is everything I did and saw.  Current situation is WinPcap 4.1.3 is not installed.

- I double-click the .exe and UAC is invoked.  I enter my creds and click Yes to start the installation.
- I accept the licence agreement.
- I select 'Support lookback traffic' and 'Install Npcap in WinPcap API-compatible mode' and click Install.
- I see a couple of cmd.exe-style windows appear and disappear.
- The installation stops with the main 'Npcap 0.07 (beta) Setup' window still visible, progress bar about 3/4 across to the right, with the heading 'Failed to create the npcap service for Vista, Win7, Win8 and Win10'.  A smaller window has appeared on top of it,  entitled 'Npcap 0.07 (beta) Setup', which reads 'Failed to create the npcap service for Vista, Win7, Win8 and Win10. Please try installing Npcap again, or use the official Npcap installer from https://github.com/nmap/npcap/releases'. I click OK on this window.
- Another window flashes up and is gone.
- A smaller window appears on top of the main 'Npcap 0.07 (beta) Setup' window (which is in the same state as before), again entitled 'Npcap 0.07 (beta) Setup', and now reading 'Failed to create the npcap2 service for Vista, Win7, Win8 and Win10. Please try installing Npcap again, or use the official Npcap installer from https://github.com/nmap/npcap/releases'. I click OK on this window.
- More cmd.exe-style windows open and close.
- The main 'Npcap 0.07 (beta) Setup' window now reads 'Installation Complete, Setup was completed successfully' in the white header and 'Completed' with a full progress bar in the body.
- I click on Show details.  It reads (I copied and pasted each line.)
```
Execute: net stop npf
Execute: net stop npcap
Start setting system restore point: Before installation of Npcap 0.07
Error occured when starting setting system restore point, return value=|2147942526|
Windows CurrentVersion: 6.1 (win7)
Output folder: C:\Program Files\Npcap
Extract: LICENSE
Extract: NPFInstall2.exe
Extract: NPFInstall.exe
Output folder: C:\Program Files\Npcap
Extract: npf.sys
Extract: npf.inf
Extract: npf_wfp.inf
Extract: npf_wifi.inf
Extract: npf.cat
Extract: npcap.sys
Extract: npcap.inf
Extract: npcap_wfp.inf
Extract: npcap_wifi.inf
Extract: npcap.cat
Created uninstaller: C:\Program Files\Npcap\uninstall.exe
Installing NDIS6.x x64 driver for Vista, Win7, Win8 and Win10
Output folder: C:\Windows\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NPcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Windows\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NPcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Windows\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NPcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Windows\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NPcapHelper.exe
Extract: WlanHelper.exe
Execute: "C:\Program Files\Npcap\NPFInstall.exe" -n -il
Execute: "C:\Program Files\Npcap\NPFInstall.exe" -n -c
The cache in driver store was cleared
Execute: "C:\Program Files\Npcap\NPFInstall.exe" -n -iw
Execute: "C:\Program Files\Npcap\NPFInstall.exe" -n -i
Failed to create the npcap service for Vista, Win7, Win8 and Win10
Execute: "C:\Program Files\Npcap\NPFInstall2.exe" -n -iw
Execute: "C:\Program Files\Npcap\NPFInstall2.exe" -n -i
Failed to create the npcap2 service for Vista, Win7, Win8 and Win10
Adding DLL folder: "C:\Windows\system32\Npcap" to PATH environment variable
Target was appended to PATH
Execute: net start npf
Execute: net start npcap
Completed
```
- I click Next.
- I am offered the option to 'Automatically start the Npcap driver at boot time'.  I uncheck the box and click Next.
- The header changes to 'Finished - Thanks you for installing Npcap' and the body to 'Npcap has been installed on your computer.' and 'Click Finish to close this wizard.' so I click Finish.

To aid diagnostics, from a Command Prompt as Administrator, I tried running
```
cd C:\Program Files\Npcap
NPFInstall.exe -?
```
and saw a window entitled 'NPFInsdtall.exe - System Error' - 'The program can't start because wlanapi.ddl is missing from your computer.  Try reinstalling the program to fix this problem.'

Programs and Features now contains Npcap 0.07.

**Comment by hsluoyz** [comment]
Hi @simgar ,

Thanks for the report!

The bug is supposed to be fixed on the latest Npcap 0.07 r12 version, please try it at:
https://github.com/nmap/npcap/releases

Please feedback to this issue after trying:)

**Comment by simgar** [comment]
What a quick response!  

It does now install without error but Wireshark fails to start with the error: 

'Wireshark.exe - System Error' - 'The program can't start because wlanapi.ddl is missing from your computer. Try reinstalling the program to fix this problem.'

I OK that and it appears again.  I okay that and Wireshark opens its main window and starts loading modules and then I get a similar window:

'dumppcap.exe - System Error' - 'The program can't start because wlanapi.ddl is missing from your computer. Try reinstalling the program to fix this problem.'

OKing this causes it to appear again.  And again.  After 16 times, I gave up and closed the main Wireshark window.

I did try uninstalling and reinstalling Wireshark (v2.0.3) but the problem remains.

**Comment by hsluoyz** [comment]
> 'Wireshark.exe - System Error' - 'The program can't start because wlanapi.ddl is missing from your computer. Try reinstalling the program to fix this problem.'

By ``wlanapi.ddl``, do you really mean ``wlanapi.dll``? the dynamically-linked library?

> I did try uninstalling and reinstalling Wireshark (v2.0.3) but the problem remains.

Do you still have this issue when installing WinPcap instead of Npcap?

**Comment by hsluoyz** [comment]
Hi @simgar .

> I OK that and it appears again. I okay that and Wireshark opens its main window and starts loading modules and then I get a similar window:

> 'dumppcap.exe - System Error' - 'The program can't start because wlanapi.ddl is missing from your computer. Try reinstalling the program to fix this problem.'

The bug is supposed to be fixed on the latest Npcap 0.07 r13 version, please try it at:
https://github.com/nmap/npcap/releases

Please feedback to this issue after trying:)

**Comment by hsluoyz** [comment]
I will assume that this issue has been fixed. If it hasn't, please reopen it again.

**Comment by simgar** [comment]
Now fixed.  Thanks for the prompt response.
