### ISSUE TITLE
allow nmap/liblua build with clang (do not overwrite CC)

### ISSUE THREAD

**Issue by ohauer** [nmap/nmap#41]
liblua builds fine with clang, but setting CC=clang will be overwritten in the liblua/Makefile

Index: liblua/Makefile
===================================================================
--- liblua/Makefile     (revision 33903)
+++ liblua/Makefile     (working copy)
@@ -6,7 +6,7 @@
 # Your platform. See PLATS for possible values.
 PLAT= none

-CC= gcc
+CC?= gcc
 CFLAGS= -O2 -Wall -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)
 LDFLAGS= $(SYSLDFLAGS) $(MYLDFLAGS)
 LIBS= -lm $(SYSLIBS) $(MYLIBS)

**Comment by dmiller-nmap** [comment]
I agree with the spirit of this, but I'm pretty sure this works anyway. Nmap's Makefile invokes `make CC=$(CC)`, and [this complete build from Travis](https://s3.amazonaws.com/archive.travis-ci.org/jobs/46400097/log.txt) shows that clang is being used to build liblua. After all, the liblua Makefile itself invokes Make the same way for various platforms that have different native C compilers.

I'm open to more discussion, but I need to be convinced this is actually broken.

**Comment by ohauer** [comment]
Hi Daniel,
you are right, the build will stuck with clang.
I suspect it spotted in my eyes because I'm reading mostly BSD Makefiles
