### ISSUE TITLE
nmap -sn displays non-existing hosts up in different subnet

### ISSUE THREAD

**Issue by nielsk** [nmap/nmap#413]
Let's say I am in 192.168.11.0/24 and scan 192.168.21.0/24 then `nmap -sn 192.168.21.0/24` displays that all hosts are up in the subnet, even though most are non-existent.
I would expect only to the see the live hosts and no "ghosts" like when I scan in the same subnet as my computer is.

I did a `nmap -sn -d -n --packet-trace` for one of the non-existing hosts and get the following:

    Starting Nmap 6.46 ( http://nmap.org ) at 2016-06-09 16:18 Mitteleuropäische Sommerzeit
    
    Winpcap present, dynamic linked to: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
    --------------- Timing report ---------------
      hostgroups: min 1, max 100000
      rtt-timeouts: init 1000, min 100, max 10000
      max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
      parallelism: min 0, max 0
      max-retries: 10, host-timeout: 0
      min-rate: 0, max-rate: 0
    ---------------------------------------------
    Initiating Ping Scan at 16:18
    Scanning 192.168.21.247 [4 ports]
    Packet capture filter (device eth1): dst host 192.168.11.12 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 192.168.21.247)))
    SENT (0.2510s) ICMP [192.168.11.12 > 192.168.21.247 Echo request (type=8/code=0) id=45775 seq=0] IP [ttl=54 id=8332 iplen=28 ]
    SENT (0.2530s) TCP 192.168.11.12:45397 > 192.168.21.247:443 S ttl=46 id=31025 iplen=44  seq=736434284 win=1024 <mss 1460>
    SENT (0.2530s) TCP 192.168.11.12:45397 > 192.168.21.247:80 A ttl=49 id=7593 iplen=40  seq=0 win=1024 
    SENT (0.2530s) ICMP [192.168.11.12 > 192.168.21.247 Timestamp request (type=13/code=0) id=26582 seq=0 orig=0 recv=0 trans=0] IP [ttl=52 id=12976 iplen=40 ]
    RCVD (0.2530s) TCP 192.168.21.247:80 > 192.168.11.12:45397 RA ttl=254 id=60975 iplen=40  seq=736434284 win=1024 
    We got a TCP ping packet back from 192.168.21.247 port 80 (trynum = 0)
    Completed Ping Scan at 16:18, 0.18s elapsed (1 total hosts)
    Overall sending rates: 22.22 packets / s, 844.44 bytes / s.
    Nmap scan report for 192.168.21.247
    Host is up, received reset (0.00s latency).
    Final times for host: srtt: 0 rttvar: 5000  to: 100000
    Read from C:\Program Files (x86)\Nmap: nmap-payloads.
    Nmap done: 1 IP address (1 host up) scanned in 0.25 seconds
               Raw packets sent: 4 (152B) | Rcvd: 1 (40B)

**Comment by dmiller-nmap** [comment]
This is due to something on your network answering on the "nonexistent" hosts's behalf. This line:

    RCVD (0.2530s) TCP 192.168.21.247:80 > 192.168.11.12:45397 RA ttl=254 id=60975 iplen=40  seq=736434284 win=1024

means that we received a TCP RST/ACK packet indicating a closed port 80 from 192.168.21.247. That's sufficient evidence to indicate that something on that address is willing to speak TCP.

How is your network set up? If the gateway to the 192.168.21 network is a NAT router or a firewall configured to reject connections, this could be expected behavior. You can use the `--reason` option to also see why Nmap makes certain host-up or port state decisions.
