### ISSUE TITLE
XML to Nroff man page conversion problem

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#417]
There seems to be a problem with the current conversion of our man page (docs/refguide.xml) into the Nroff man page (docs/nmap.1).  The man page when rendered with "man" contains:

`"Key among that information is the “interesting ports table”..  That table lists the port number and protocol, service name, and state. The state is either open, filtered, closed, or unfiltered.  Open.  means that an application on the target machine is listening"`

Note the two periods after "interesting ports table" and then later comes "Open. means".  The relevant XML source code is:

```
"Key among that information is the <quote>interesting ports table</quote>.<indexterm><primary>ports</primary><secondary sortas="interesting">&ldquo;interesting&rdquo;</secondary></indexterm> That table lists the port number and protocol, service name, and state.  The state is either <literal>open</literal>, <literal>filtered</literal>, <literal>closed</literal>, or <literal>unfiltered</literal>.
<literal>Open</literal><indexterm><primary><literal>open</literal> port state</primary></indexterm> means that an application on the target machine is listening"
```

So it seems like the indexterm element is having the problem.  Note that this problem doesn't manifest in the HTML rendering: https://nmap.org/book/man.html#man-description

**Comment by dmiller-nmap** [comment]
Same issue as #114. indexterm is converted to a comment, but without a newline preceding it.
