### ISSUE TITLE
auth-owners.nse repeating error

### ISSUE THREAD

**Issue by cclements** [nmap/nmap#43]
An script run on a single host throws this error repeatedly in in a debug=1

NSE: auth-owners against 10.x.xxx.xx:5356 threw an error!
ERROR
stack traceback:
        [C]: in function 'try'
        /usr/bin/../share/nmap/scripts/auth-owners.nse:57: in function </usr/bin/../share/nmap/scripts/auth-owners.nse:44>
        (...tail calls...)

**Comment by dmiller-nmap** [comment]
Whenever you see an error thrown "in function 'try'", it's a handled failure. It would be nice if we could find some other way to return up the stack from the middle of a script, but throwing an error is the best we can do.

In your particular case, you've scanned a system and found 113/tcp open, triggering the auth-owners script. Unfortunately, when the script subsequently tries to connect to 113/tcp, it fails. It's possible that some adaptive behavior like a firewall on the target has turned off access to port 113 after the initial scan succeeded.
