### ISSUE TITLE
BSOD when install, and could not reinstall or uninstall.

### ISSUE THREAD

**Issue by crysehillmes** [nmap/nmap#430]
When I install Npcap on my Windows 10, I got BSOD with error DRIVER_IRQL_LESS_OR_NOT_EQUAL(nwifi.sys).
After reboot, when i try to reinstall or uninstall npcap, in detail log:

```
Start setting system restore point: Before installation of Npcap 0.07
Error occured when uninstalling WinPcap, Npcap installation quits
Finish setting system restore point: Before installation of Npcap 0.07
Completed
```

How can I solve these problems? Thanks.

**Comment by hsluoyz** [comment]
Hi @crysehillmes ,

Please do the following two steps:
1) Uninstall WinPcap manually first, then reboot. Then install Npcap again.
2) Send your BSoD dump file to: hsluoyz@gmail.com. It should be in ``C:\Windows\Minidump``.


Cheers,
Yang

**Comment by hsluoyz** [comment]
Hi @crysehillmes ,

I analyzed your dump, it seems that a software called ``Killer Network Manager`` has compatible issues with Npcap. Please uninstall it or update to the latest driver, then try installing Npcap again.

**Comment by crysehillmes** [comment]
Hi @hsluoyz ,

Thank you for your help. `Killer Network Manager` is part of my Killer Wireless and Ethernet adapter driver suite. I find the manufacturer(Qualcomm) also provider standalone drivers without the Bandwidth Control (bwcW10x64), so I install the standalone drivers. Npcap is working now.
Thank you very much.
