### ISSUE TITLE
Not able to "make" ncat with lua 5.3

### ISSUE THREAD

**Issue by tremblerz** [nmap/nmap#431]
Here is the few lines of [error](http://pastebin.com/jcE7ZZuT) which I am getting while doing `./configure && make`. I am not sure but most probably it is due to lua 5.3 because recently I updated my lua version to 5.3 from 5.2

**Comment by dmiller-nmap** [comment]
Upgrading Lua versions involves a lot of code changes to fix incompatibilities. Patrick has recently done this in a branch he intends to commit soon: http://seclists.org/nmap-dev/2016/q2/186
