### ISSUE TITLE
Can not uninstall..

### ISSUE THREAD

**Issue by DynConcepts** [nmap/nmap#438]
Attempted to install...it failed (removing pcap)...now I cant get out...

All I want to do is use Wireshark with local packets..... <sigh>

**Comment by hsluoyz** [comment]
Hi @DynConcepts ,

You can manually uninstall WinPcap first, then install Npcap.

**Comment by DynConcepts** [comment]
I have tried that.... Even though the install of Npcap failed, attempting to do anything with WinPcap fails because "there is a newer version"..so I want to completely uninstall NpCap - but the EXE does not have a way to do it, and the program does not show up under "Add Remove"....

**Comment by hsluoyz** [comment]
Can you post all the Npcap installation logs here?

**Comment by DynConcepts** [comment]
Point me to them, and I will post them...

**Comment by DynConcepts** [comment]
![image](https://cloud.githubusercontent.com/assets/9969889/16341689/6e8d685a-39fc-11e6-95d3-46f7c35f8c93.png)

**Comment by hsluoyz** [comment]
![image](https://cloud.githubusercontent.com/assets/3787410/16341735/3de70e76-3a61-11e6-9e69-a414362d6465.png)

**Comment by DynConcepts** [comment]
That is not "logs"....that is a screen shot.. system will not allow me to upload (get a "something went really wrong..." message).

**Comment by hsluoyz** [comment]
Then can you post a screen shot?

**Comment by DynConcepts** [comment]
See my previous comment...When I try to post a screenshot (or any file) I get a message "something when really wrong" in the comment box!

**Comment by hsluoyz** [comment]
In fact I only need the text inside the red circle in my screen shot, can you write them down in the comment?

**Comment by DynConcepts** [comment]
Are telling me the program does not create and maintain proper text log files?

Just tell me how to completely and utterly install the thing, PLEASE.

**Comment by hsluoyz** [comment]
Unfortunately, The NSIS packing system we used doesn't provide a convenient log file thing, so you have to write it down or take a screenshot of it, if you want me to know your errors.

**Comment by DynConcepts** [comment]
Just tell me how to completely and utterly install the thing, PLEASE.  - Or is uninstall not supported either?

**Comment by hsluoyz** [comment]
What shows you that makes you think Npcap fails the installation?

**Comment by DynConcepts** [comment]
I am pretty much past that, but the key message is: "nCAP Installation Quits".

What I really want t5o know now is how to get it OFF my machine, ENTIRELY, every file, every setting, ALL of it....

I will be pretty upset if the only answer is "wipe the machine and restore from backup".

**Comment by hsluoyz** [comment]
Please remove any ``wpcap.dll`` files in your file system, then try Npcap installer again.

**Comment by DynConcepts** [comment]
Final comment... I asked for REMOVAL. You were unable or unwilling to provide that. That meant I spent the better part of the day restoring my machine from backups to completely and utterly remove all traces. There is ZERO chance of me ever installing this again.
