### ISSUE TITLE
Merging scripts http-wordpress-plugins and http-wordpress-themes

### ISSUE THREAD

**Issue by cldrn** [nmap/nmap#44]
What does everybody think about merging the NSE scripts http-wordpress-plugins and http-wordpress-themes into a single script to avoid code repetition?

Nmap-dev thread:
http://seclists.org/nmap-dev/2014/q4/229

**Comment by nmapster** [comment]
On Tue, Jan 13, 2015 at 5:59 PM, Paulino Calderon <notifications@github.com>
wrote:

> What does everybody think about merging the NSE scripts
> http-wordpress-plugins and http-wordpress-themes into a single script to
> avoid code repetition?
>
Sounds like a good idea to me!  Alternatively, the common code could be
placed in a library.  I'm not sure how often people want to enumerate
plugins but not themes or vice versa.  Of course the combined script could
have a script arg for specifying that you only want to check one of the two.

I'm testing the "reply to bug" feature of the new issues system.  Hopefully
this gets through!

-Fyodor

**Comment by peter-hackertarget** [comment]
My two cents from someone with a non-dev background and just starting with lua.

The scripts are not overly complicated so even though there is an argument for removing code re-use a combined script will be slightly more involved simply due to the number of script-args required / handling multiple input files etc.

As they stand, there is potential for them to modified (http://seclists.org/nmap-dev/2015/q1/56) or cloned and re-purposed for Joomla or Drupal modules without much work. From the point of view of a non-developer a simple standalone script is easier to perform these changes without breaking things.

From a purely end user point of view, I like the fact that the title of the two scripts (plugins and themes) clearly indicates what testing will be performed.

**Comment by h4ck3rk3y** [comment]
Hi,
I am new to nmap,lua and network programming.
This is my first contribution ,an attempt to merge the two.
https://github.com/h4ck3rk3y/nmap/blob/master/scripts/http-wordpress-combined.nse
I don't have a host to run a test.I tried running this and the http-wordpress-plugins.nse as a test on a random blog it didn't work very well.Please criticize my work and help me develop better.
Regards,
Gyanendra Mishra

**Comment by h4ck3rk3y** [comment]
Hi,
Sorry for all the noise.
I was finally able to test my script properly.I made some changes and added proper documentation.
Here is the final file : 
https://github.com/h4ck3rk3y/nmap/blob/master/scripts/http-wordpress-combo.nse
I have made a post regarding the same in the mailing list too.
Regargs,
Gyanendra Mishra

**Comment by peter-hackertarget** [comment]
Nice work on combining the two scripts.

I have made additional changes to my previously submitted scripts (both themes and plugins), the changes are introducing more differences between the two scripts.

The most recent update to the http-wordpress-plugins.nse script includes getting both the version of the plugin in use and latest version from the wordpress.org API (this can be disabled with a script-arg).

Sample output:
```
Interesting ports on my.woot.blog (123.123.123.123):
PORT   STATE SERVICE REASON
80/tcp open  http    syn-ack
| http-wordpress-plugins:
| search amongst the 500 most popular plugins
|   akismet 3.0.4 (latest version: 3.0.4)
|   wordpress-seo 1.7 (latest version: 1.7.1)
|   disqus-comment-system 2.83 (latest version: 2.84)
|_  wp-to-twitter 1.2 (latest version: 1.45)
```

If someone wants to combine these changes into a single script then by all means, or they could be left as standalone scripts.

My latest updates to plugins and themes are here -> https://github.com/peter-hackertarget/nmap-nse-scripts/

**Comment by h4ck3rk3y** [comment]
Thanks Peter.
I was looking for a source to get the latest versions of the themes couldn't find anything.
What I could do is make a get_version() and a get_latest_plugin_version() ,the first function tells the version being used of the theme/plugn while the second function accesses the api and returns the current latest.

**Comment by h4ck3rk3y** [comment]
Hi,
I have posted the same here.
http://seclists.org/nmap-dev/2015/q1/97

**Comment by cldrn** [comment]
Hey,

I have committed an updated version of your script in rev 33988. The most common usage escenario is users trying to detect possibly outdated themes and plugins so combining them was the best way to go (and avoid code duplication in the process )

Thanks for your contributions! You can find more details of the changes I made in the nmap-dev thread.

Nmap-dev thread: http://seclists.org/nmap-dev/2015/q1/155

**Comment by h4ck3rk3y** [comment]
Thanks Paulino!
I am very happy as this is my first patch to be committed. :)
