### ISSUE TITLE
Zenmap crashes with Permission Denied on zenmap.conf

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#449]
This is reported too often to be a simple file permissions issue. It is probably a concurrency problem with opening, reading, and writing the config file. It started happening after we merged #247 and then fixed some other concurrency issues (r35718, r35721, r35726, r35727, r35744, specifically 97b5aa2c).

Example reports:
* http://seclists.org/nmap-dev/2016/q2/70 (saving in Program Files on Windows)
* http://seclists.org/nmap-dev/2016/q2/244 (saving in %userprofile% on Windows)
* http://seclists.org/nmap-dev/2016/q2/197 (saving in $HOME on OS X)

**Comment by RajithaRama** [comment]
@dmiller-nmap Is this issue fixed..?

**Comment by dmiller-nmap** [comment]
Fixed in 4c1ef965 and e4fcf23

**Comment by dmiller-nmap** [comment]
For some reason, the user's zenmap.conf is being changed to read-only. I can't figure out where it's happening, so we'll just have to catch the appropriate error and suggest that the user go and fix it. I think it's not going to happen again, but I guess we'll see.
