### ISSUE TITLE
High parallelism and the Nsock Select Engine on Windows

### ISSUE THREAD

**Issue by Tudor-Coman** [nmap/nmap#455]
On Windows there is no safeguard to prevent adding more that FD_SETSIZE (typically this value is 64) file descriptors inside a fd_set. Having a min-parallelism greater than 64 may have unexpected consequences and in some situations reduce the accuracy of the scan.

**Comment by Tudor-Coman** [comment]
File descriptors are added to a fd_set using a function in nbase.h called checked_fd_set().
On Linux there is an actual check performed like:
`if (fd >= FD_SETSIZE)` but it isn't portable to Windows and I'm not sure this is how it should even be used.
Shouldn't the number of file descriptors actually be checked using the set itself like:
`if (fds->fd_count >= FD_SETSIZE)`. 
This solution would be actually more portable.

**Comment by dmiller-nmap** [comment]
I'm tempted to mark this `wontfix` because we now have the much faster and more reliable Poll and IOCP engines for Nsock, but I'm leaving it open in the hopes that we can fix the code in a portable, fast, and correct manner.
