### ISSUE TITLE
Rendering of "The six port states" definition list in man.1

### ISSUE THREAD

**Issue by timhughes** [nmap/nmap#463]
The section "The six port states recognized by Nmap" under "Port Scanning Basics" should be a definition list but the things being defined don't show up.

On http://linux.die.net/man/1/nmap it just becomes a single paragraph. In the console each definition is a separate paragraph but what they are defining isn't showing up.

**Comment by dmiller-nmap** [comment]
Thanks so much for reporting this! Turns out this was caused by a misplaced `<indexterm>` element in our docbook XML (`docs/refguide.xml`). I made the change there and regenerated the manpage and it seems to be fixed.
