### ISSUE TITLE
Superfluous OpenService error message

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#465]
Some time ago file `mswin32/winfix.cc` has been updated to accommodate NPCAP, including the following logic in `win_init()`:
```
if (start_service("npcap"))
	pcap_driver = PCAP_DRIVER_NPCAP;
else if (start_service("npf"))
	pcap_driver = PCAP_DRIVER_WINPCAP;
else
	pcap_driver = PCAP_DRIVER_NONE;
```
There is a purely cosmetic but annoying issue in `start_service()` in that it always generates a console error message when a requested service is not found, namely "*Error in OpenService*":
```
  npf = OpenService(scm, svcname, SC_MANAGER_CONNECT | SERVICE_QUERY_STATUS);
  if (npf == NULL) {
    error("Error in OpenService");
    goto quit_error;
  }
```

In case the user relies on `npf`, instead of `npcap`, he is always greeted with this error message as a result of nmap invoking `start_service("npcap")` first.

IMHO forced error messages should be limited to situations where something went wrong, as opposed to when the code is simply probing for system capabilities. I am proposing to update the code as follows:
```
--- mswin32/winfix.cc.orig      2016-06-27 09:32:59.000000000 -0600
+++ mswin32/winfix.cc   2016-07-20 19:51:19.751480100 -0600
@@ -187,7 +187,8 @@
   }
   npf = OpenService(scm, svcname, SC_MANAGER_CONNECT | SERVICE_QUERY_STATUS);
   if (npf == NULL) {
-    error("Error in OpenService");
+    if (o.debugging > 1)
+      log_write(LOG_PLAIN, "%s service not found.\n", svcname);
     goto quit_error;
   }
   if (!QueryServiceStatus(npf, &service)) {
```
This results in clean console output under normal circumstances and consistent output when debugging:
```
Starting Nmap 7.12SVN ( https://nmap.org ) at 2016-07-20 19:54 Mountain Daylight Time
...
PORTS: Using top 1000 ports found open (TCP:1000, UDP:0, SCTP:0)
npcap service not found.
npf service is already running.
Winpcap present, dynamic linked to: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
```
The same issue is present in nping:
```
--- nping/winfix.cc.orig        2016-06-27 09:33:12.000000000 -0600
+++ nping/winfix.cc     2016-07-20 20:04:30.489707800 -0600
@@ -187,7 +187,8 @@
   }
   npf = OpenService(scm, svcname, SC_MANAGER_CONNECT | SERVICE_QUERY_STATUS);
   if (npf == NULL) {
-    error("Error in OpenService");
+    if (o.getDebugging() > DBG_1)
+      printf("%s service not found.\n", svcname);
     goto quit_error;
   }
   if (!QueryServiceStatus(npf, &service)) {
```

**Comment by hsluoyz** [comment]
I also think this message needs to be fixed. But turning it into debug-level info may be not a good choice. Because if both ``npcap`` and ``npf`` services fail, nmap's scan will fail too. But no service related message is displayed.

I think a better solution is only displaying ``Error in OpenService`` when the 2nd check fails. In this context, it only shows in the ``npf`` service checking routine. So only the message in ``npcap`` service checking routine should be removed.

**Comment by nnposter** [comment]
I respectfully disagree. Having more detailed, debug-level trace is useful as the code performs the probing. Also, implementing a condition when to print this error message in `start_service()`, as I understand your position, would seem unnecessarily polluting the code.

If you want to keep this message then perhaps the best spot would be to put it after the probing logic, i.e. only after determining that `pcap_driver == PCAP_DRIVER_NONE`. I would also recommend to use more descriptive language for the text of the message, something like "*Neither NPCAP nor NPF service found*".

**Comment by hsluoyz** [comment]
> I respectfully disagree. Having more detailed, debug-level trace is useful as the code performs the probing. Also, implementing a condition when to print this error message in start_service(), as I understand your position, would seem unnecessarily polluting the code.

I'm OK with adding debug-level info, as a normal user won't see the log.

> If you want to keep this message then perhaps the best spot would be to put it after the probing logic, i.e. only after determining that pcap_driver == PCAP_DRIVER_NONE. I would also recommend to use more descriptive language for the text of the message, something like "Neither NPCAP nor NPF service found".

This solution seems to be better than adding to the second checking code.

**Comment by hsluoyz** [comment]
@bonsaiviking , Dan, what's your opinion about this issue?

**Comment by nnposter** [comment]
@bonsaiviking: The issue has not been fixed in `nping/winfix.cc`. Re-opening as #485.
