### ISSUE TITLE
Better debugging/status output for NSE

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#47]
Currently, the only feedback a user has (beyond full stack traces for every running script when a key is pressed at `-d2`) is a timing line like this:

    NSE Timing: About 96.08% done; ETC: 20:46 (0:00:50 remaining)

It seems like this could be enhanced at higher debug levels with information about

* number of running scripts
* Number of scripts in each status (waiting, running, etc.)
* Names of scripts once they drop below a certain number (5?)
* Maybe even a backtrace of 1 or 2 remaining scripts at a high debug level.

**Comment by cldrn** [comment]
It would be nice if NSE scripts can also report their progress. We will need to add an interface to allow programmers to set/update the completion level of a script.

**Comment by gordonlyon** [comment]
Yes, this would be a nice feature for sure.

**Comment by dmiller-nmap** [comment]
Ok, so I was mostly ignorant. NSE already does this when the user presses a key:

* If verbosity (or debugging) is 1 or more, prints `Active NSE Script Threads: %d (%d waiting)`
* If debugging is 2 or more, prints backtrace of running threads.

So my first 2 points are already addressed. Names of scripts below 5? Just turn up the debugging to 2 and you get names *and* backtraces. I'm closing this, though @cldrn's point is still valid and should be added as a separate issue.
