### ISSUE TITLE
Nmap fails to run with Npcap 0.08 and later (which has added support of libpcap 1.8.0)

### ISSUE THREAD

**Issue by hsluoyz** [nmap/nmap#498]
I have found out why Nmap crashes with Npcap with libpcap 1.8.0. Nmap includes a internal header of libpcap: ``pcap-int.h`` (details in: https://github.com/nmap/nmap/issues/426). And when this file updates from old 1.0.0 to the latest 1.8.0, it has changed the offset of the ``adapter`` member in the ``pcap`` struct:

- In the [old 1.0.0 pcap-int.h](https://github.com/nmap/nmap/blob/master/mswin32/pcap-include/pcap-int.h#L263): the offset is 0. See this code:
```c
struct pcap {
#ifdef WIN32
	ADAPTER *adapter;
	LPPACKET Packet;
	int nonblock;
#else
	int fd;
	int selectable_fd;
	int send_fd;
#endif /* WIN32 */
```
- In the [new 1.8.0 pcap-int.h](https://github.com/nmap/libpcap/blob/npcap/pcap-int.h#L163), the offset is 8 bytes. There are two new function pointers before the ``adapter`` member. See this code:
```c
struct pcap {
	/*
	 * Method to call to read packets on a live capture.
	 */
	read_op_t read_op;

	/*
	 * Method to call to read packets from a savefile.
	 */
	int (*next_packet_op)(pcap_t *, struct pcap_pkthdr *, u_char **);

#ifdef _WIN32
	ADAPTER *adapter;
#else
	int fd;
	int selectable_fd;
#endif /* _WIN32 */
```

So Nmap got the wrong adapter value when linking with the new Npcap. The solutions are:
**Solution 1**. Update Nmap repo's ``pcap-int.h`` to the latest 1.8.0 version.
**Solution 2**. Remove the dependence on ``pcap-int.h``.

Regarding **Solution 1**, I noticed that Nmap has included a lot of Npcap and libpcap headers here in [\mswin32\pcap-include](https://github.com/nmap/nmap/tree/master/mswin32/pcap-include). And some of those are still old 1.0.0 files, including the faulty ``pcap-int.h``. So given that Npcap has updated to use latest libpcap 1.8.0, it's reasonable to update Nmap to use latest libpcap 1.8.0 as well. Those headers are in the ``mswin32`` path, so they are only used by Windows. We don't need to worry that this change will breach Nmap's build on other platforms. So this solution is definitely what we should do.

Regarding **Solution 2**, it is also what we need to do. It has been proposed and discussed quite a lot in another issue: https://github.com/nmap/nmap/issues/426. So I think this issue would only focus on the **Solution 1**.

**Comment by nnposter** [comment]
IMHO, whatever change gets implemented, nmap should not break compatibility with WinPcap for the time being. Would not solution 1 cause that?

**Comment by hsluoyz** [comment]
Very good question. IMHO, given that Nmap installer will ship Npcap, this should not be a big issue.

And if anyone could solve the problem along the **Solution 2** path. It would be definitely great. But since it's a 2010 year remaining issue. I think there's no easy way now. And what I proposed for **Solution 2** (https://github.com/nmap/npcap/commit/b400111b365dd6397329f01c6b9086fb215f7210) also breaks the compatibility with WinPcap.

I believe following **Solution 2** would be a tough way and needs quite a lot of time and discussion before it can be solved. But this issue needs to be solved ASAP because some users are already complaining about it.

So I will do **Solution 1** for now, even it breaks the compatibility with WinPcap. If one day issue https://github.com/nmap/nmap/issues/426 is fixed, Nmap will still re-gain the WinPcap's compatibility.

**Comment by nnposter** [comment]
Maybe there should be a larger discussion in the community whether this is the best time to introduce incompatibility with WinPcap or, put differently, whether Npcap has reached sufficient maturity to become the only option going forward. (Do not take me wrong, I do appreciate your work and the advantages of Npcap.)

**Comment by hsluoyz** [comment]
I get it:)

This is currently only a workaround for now. So I can let some complaining users use this bug-fixed Nmap to test latest Npcap. This issue will be discussed in our next group meeting.

**Comment by hsluoyz** [comment]
This issue has been fixed in: https://github.com/nmap/nmap/commit/af13cef717d237d26a4b9cbee314e137e1783954
