### ISSUE TITLE
Can't select Monitor mode while installing npcap 0.08

### ISSUE THREAD

**Issue by rkoornstra** [nmap/nmap#509]
Trying to install npcap, but support raw 802.11 traffic (monitor mode) is greyed out.
I actually need this mode. Why is it greyed out?
What can be done to enable this option upon install?

Call: 62
IfFileExists: file "C:\npcap_install_options.txt" does not exist, jumping 76
Call: 77
Jump: 94
Jump: 111
Call: 115
Jump: 205
Call: 115
Call: 115
Call: 115
Call: 115
Call: 115
Call: 115
IfFileExists: file "C:\Program Files\Npcap\NPFInstall.exe" does not exist, jumping 400
Call: 1092
File: overwriteflag=0, allowskipfilesflag=2, name="C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\modern-header.bmp"
File: wrote 70976 to "C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\modern-header.bmp"
WriteINIStr: wrote [Field 1] State=1 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 414
WriteINIStr: wrote [Field 2] State=1 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 427
WriteINIStr: wrote [Field 3] State=1 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
WriteINIStr: wrote [Field 3] Flags=DISABLED in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 444
WriteINIStr: wrote [Field 4] State=0 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 457
WriteINIStr: wrote [Field 5] State=0 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
WriteINIStr: wrote [Field 5] Flags=DISABLED in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 470
WriteINIStr: wrote [Field 6] State=0 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 483
WriteINIStr: wrote [Field 7] State=0 in C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\options.ini
Jump: 500
IfFileExists: file "C:\windows\system32\wpcap.dll" does not exist, jumping 508
Call: 1092
File: overwriteflag=1, allowskipfilesflag=2, name="C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\InstallOptions.dll"
File: wrote 14848 to "C:\Users\koorstra\AppData\Local\Temp\nsu6558.tmp\InstallOptions.dll"

**Comment by hsluoyz** [comment]
Hi,

We disabled the raw 802.11 option on purpose because it's not mature enough. e.g., Nmap still doesn't support it.

However, you can still enable the option following this guide:
https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-redistribution-options-gui

**Comment by rkoornstra** [comment]
I was wondering whether this would help for wireshark as well so I can sniff 802.11 traffic?

**Comment by hsluoyz** [comment]
Yeah. Npcap supports Wireshark to sniff raw 802.11 traffic in monitor mode. Remember to use Wireshark latest development version instead of the stable version for better support.
