### ISSUE TITLE
Extend nmap_mass_rdns to support IPv6

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#51]
`nmap_mass_rdns` in `nmap_dns.cc` has this little disappointment:

<pre>
  // mass_dns only supports IPv4.
  if (o.mass_dns && o.af() == AF_INET)
    nmap_mass_rdns_core(targets, num_targets);
  else
    nmap_system_rdns_core(targets, num_targets);
</pre>

I don't see any technical reason why IPv6 couldn't also be supported, which would give a big speed boost to IPv6 scans, especially `-sL` list scans, which can be a cheap, stealthy way of doing target discovery.

**Comment by G10h4ck** [comment]
I am working on it https://gitlab.com/g10h4ck/nmap-gsoc2015/commits/hotfix/51

**Comment by ryanchou1991** [comment]
It looks cool !
