### ISSUE TITLE
NPcap 0.08+(Compatible Mode) doesn't keep extra the same logic as <=0.07-r17 and WinPcap for pcap_open_live?

### ISSUE THREAD

**Issue by yyjdelete** [nmap/nmap#512]
In old version, pcap_open_live also accept name in `pcap_findalldevs_ex` style (`rpcap://\Device\NPF_{AD3C70B4-453E-4D67-AC84-D7976DAD5503}`).
But in new version, only `pcap_findalldevs` style like `\Device\NPF_{AD3C70B4-453E-4D67-AC84-D7976DAD5503}` is accepted.

---

I found this due to [an issue of SharpPcap](https://github.com/chmorgan/sharppcap/pull/11), an WinPcap wrapper for dotNet.

I know the doc says that `pcap_findalldevs/pcap_open_live` and `pcap_findalldevs_ex/pcap_open` should be used in pair. But is the new behavior by design or mistake?

---

Sorry for my poor English.

**Comment by hsluoyz** [comment]
@guyharris, do you know this issue?

**Comment by chmorgan** [comment]
@hsluoyz does this look like something that will be fixed in npcap? I'd hate to work around it in Sharppcap given that it worked in the past with WinPcap's version of pcap_open_live(). What do you think?

**Comment by hsluoyz** [comment]
Hi @chmorgan , please try the attached Npcap 0.08 r6.1. Does it fix your issue? If yes, I will make public release.

[npcap-0.08-r6.1.zip](https://github.com/nmap/nmap/files/422946/npcap-0.08-r6.1.zip)

**Comment by chmorgan** [comment]
I'll have to defer to @yyjdelete on testing. I'm a Linux guy and haven't used the remote capture feature before. @yyjdelete can you test with that updated release to see if it fixes the rpcap issue without the sharppcap work around?

**Comment by yyjdelete** [comment]
@hsluoyz It works for me.

**Comment by hsluoyz** [comment]
OK. This issue has been fixed in latest Npcap 0.08 r7:
https://github.com/nmap/npcap/releases
