### ISSUE TITLE
Cant capture on Loopback Adapter Windows 7

### ISSUE THREAD

**Issue by Thilo1** [nmap/nmap#520]
I am using Windows 7 and installed npcap using the installer. Wireshark cant see the Npcap Loopback Adapter altough it is there in the SystemControls. Adapter is active.
The NL Adapter disabled initially all other adapters which is not good.

**Comment by hsluoyz** [comment]
Please submit your driver log following [this doc](https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-issues-driver-log).

In your report, please provide AT LEAST your OS (Vista | Win7 | Win8 | Win10, x86 | x64), Npcap version and installation options, user software version (e.g. Nmap, Wireshark), reproduce steps and other information you think necessary. If your issue occurs only on a special OS version (e.g. Win10 1511, 1607), please mention it in the report.

**Comment by Thilo1** [comment]
I think driver log is not available because its version 0.08 of npcap. OS is Win 7. 

Install.log:
CreateDirectory: "C:\Program Files\Npcap" created
File: overwriteflag=0, allowskipfilesflag=2, name="LICENSE"
File: wrote 1164 to "C:\Program Files\Npcap\LICENSE"
File: overwriteflag=0, allowskipfilesflag=2, name="NPFInstall.exe"
File: wrote 243008 to "C:\Program Files\Npcap\NPFInstall.exe"
Call: 781
CreateDirectory: "C:\Program Files\Npcap" (1)
Jump: 808
File: overwriteflag=0, allowskipfilesflag=2, name="npcap.sys"
File: wrote 60200 to "C:\Program Files\Npcap\npcap.sys"
File: overwriteflag=0, allowskipfilesflag=2, name="npcap.inf"
File: wrote 5161 to "C:\Program Files\Npcap\npcap.inf"
File: overwriteflag=0, allowskipfilesflag=2, name="npcap_wfp.inf"
File: wrote 2400 to "C:\Program Files\Npcap\npcap_wfp.inf"
File: overwriteflag=0, allowskipfilesflag=2, name="npcap_wifi.inf"
File: wrote 5174 to "C:\Program Files\Npcap\npcap_wifi.inf"
File: overwriteflag=0, allowskipfilesflag=2, name="npcap.cat"
File: wrote 10624 to "C:\Program Files\Npcap\npcap.cat"
Jump: 827
created uninstaller: 27001, "C:\Program Files\Npcap\uninstall.exe"
detailprint: Installing NDIS6.x x64 driver for Vista, Win7, Win8 and Win10
Call: 701
Jump: 713
CreateDirectory: "C:\Windows\system32\Npcap" (1)
CreateDirectory: "C:\Windows\system32\Npcap" created
File: overwriteflag=0, allowskipfilesflag=2, name="wpcap.dll"
File: wrote 329536 to "C:\Windows\system32\Npcap\wpcap.dll"
File: overwriteflag=0, allowskipfilesflag=2, name="Packet.dll"
File: wrote 159040 to "C:\Windows\system32\Npcap\Packet.dll"
File: overwriteflag=0, allowskipfilesflag=2, name="NpcapHelper.exe"
File: wrote 106304 to "C:\Windows\system32\Npcap\NpcapHelper.exe"
File: overwriteflag=0, allowskipfilesflag=2, name="WlanHelper.exe"
File: wrote 50496 to "C:\Windows\system32\Npcap\WlanHelper.exe"
Call: 1092
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\System.dll"
File: skipped: "C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\System.dll" (overwriteflag=1)
Call: 718
Jump: 730
CreateDirectory: "C:\Windows\system32\Npcap" (1)
CreateDirectory: "C:\Windows\system32\Npcap" created
File: overwriteflag=0, allowskipfilesflag=2, name="wpcap.dll"
File: wrote 374080 to "C:\Windows\system32\Npcap\wpcap.dll"
File: overwriteflag=0, allowskipfilesflag=2, name="Packet.dll"
File: wrote 182592 to "C:\Windows\system32\Npcap\Packet.dll"
File: overwriteflag=0, allowskipfilesflag=2, name="NpcapHelper.exe"
File: wrote 118592 to "C:\Windows\system32\Npcap\NpcapHelper.exe"
File: overwriteflag=0, allowskipfilesflag=2, name="WlanHelper.exe"
File: wrote 59712 to "C:\Windows\system32\Npcap\WlanHelper.exe"
Call: 856
WriteRegDWORD: "HKEY_LOCAL_MACHINE\Software\Npcap" "AdminOnly"="0x00000000"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\Software\Npcap" "WinPcapCompatible"="0x00000000"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Npcap" ""="C:\Program Files\Npcap"
Call: 1092
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\System.dll"
File: skipped: "C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\System.dll" (overwriteflag=1)
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "UninstallString"=""C:\Program Files\Npcap\uninstall.exe""
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "QuietUninstallString"=""C:\Program Files\Npcap\uninstall.exe" /S"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "DisplayIcon"="C:\Program Files\Npcap\uninstall.exe"
Exec: command=""C:\Program Files\Npcap\NPFInstall.exe" -n -il"
Exec: success (""C:\Program Files\Npcap\NPFInstall.exe" -n -il")
detailprint: Writting service options to registry
Call: 899
Jump: 908
Call: 867
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "Start"="0x00000001"
WriteRegStr: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "LoopbackAdapter"="\Device\{EE73B926-C14C-4DA3-A753-27E67058D9B8}"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "LoopbackSupport"="0x00000001"
Jump: 875
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "DltNull"="0x00000001"
Jump: 879
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "AdminOnly"="0x00000000"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "Dot11Support"="0x00000000"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "VlanSupport"="0x00000000"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "WinPcapCompatible"="0x00000000"
Call: 630
Call: 827
CreateDirectory: "C:\Users\FUEHRM~1\AppData\Local\Temp" (1)
File: overwriteflag=0, allowskipfilesflag=2, name="Insecure.cer"
File: wrote 1329 to "C:\Users\FUEHRM~1\AppData\Local\Temp\Insecure.cer"
Exec: command="certutil -addstore "TrustedPublisher" "C:\Users\FUEHRM~1\AppData\Local\Temp\Insecure.cer""
Exec: success ("certutil -addstore "TrustedPublisher" "C:\Users\FUEHRM~1\AppData\Local\Temp\Insecure.cer"")
Exec: command=""C:\Program Files\Npcap\NPFInstall.exe" -n -c"
Exec: success (""C:\Program Files\Npcap\NPFInstall.exe" -n -c")
detailprint: The cache in driver store was cleared
Exec: command=""C:\Program Files\Npcap\NPFInstall.exe" -n -iw"
Exec: success (""C:\Program Files\Npcap\NPFInstall.exe" -n -iw")
Exec: command=""C:\Program Files\Npcap\NPFInstall.exe" -n -i"
Exec: success (""C:\Program Files\Npcap\NPFInstall.exe" -n -i")
detailprint: The npcap service for Vista, Win7, Win8 and Win10 was successfully created
Jump: 844
Jump: 1067
Call: 948
Jump: 956
WriteRegDWORD: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap" "Start"="0x00000001"
Call: 910
Jump: 923
detailprint: Starting the npcap driver
Call: 1092
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\nsExec.dll"
File: skipped: "C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\nsExec.dll" (overwriteflag=1)
Jump: 1072
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "DisplayName"="Npcap 0.08"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "DisplayVersion"="0.08"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "Publisher"="Nmap Project"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "URLInfoAbout"="http://www.npcap.org"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "URLUpdateInfo"="http://www.npcap.org"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "VersionMajor"="0"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "VersionMinor"="1"
WriteRegStr: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "InstalledBy"="Nmap"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "NoModify"="0x00000001"
WriteRegDWORD: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "NoRepair"="0x00000001"
DeleteRegKey: "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\npcap-nmap"
detailprint: Finish setting system restore point: Before installation of Npcap 0.08
Call: 1092
File: overwriteflag=1, allowskipfilesflag=2, name="C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\SysRestore.dll"
File: skipped: "C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\SysRestore.dll" (overwriteflag=1)
Jump: 38
Call: 1092
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\InstallOptions.dll"
File: skipped: "C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\InstallOptions.dll" (overwriteflag=1)
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\final.ini")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\InstallOptions.dll")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\modern-header.bmp")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\nsExec.dll")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\options.ini")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\SysRestore.dll")
Delete: DeleteFile("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\System.dll")
RMDir: RemoveDirectory("C:\Users\FUEHRM~1\AppData\Local\Temp\nscD80E.tmp\")

**Comment by Thilo1** [comment]
SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>net start npcap
Der angeforderte Dienst wurde bereits gestartet.

Sie erhalten weitere Hilfe, wenn Sie NET HELPMSG 2182 eingeben.


C:\Windows\system32>NET HELPMSG 2182

Der angeforderte Dienst wurde bereits gestartet.

**Comment by hsluoyz** [comment]
> I think driver log is not available because its version 0.08 of npcap. OS is Win 7.

I have updated the driver debug version to 0.08 r7. See: https://github.com/nmap/npcap/releases/tag/v0.08-r7

**Comment by Thilo1** [comment]
Ah thank you very much. I got i working when i closed all instances of wireshark then ran "sc stop npf" and then "sc start npf" then the interface was available in wireshark.
