### ISSUE TITLE
Wish-list item: NSE gzip support

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#532]
A basic NSE library would be nice; support in HTTP requests would be great. It is also already mentioned in `todo/dmiller.txt`. Perhaps a candidate for GSoC?

My tactical need is to deal with a web server that insists on gzip-encoded responses even though the requests do not contain `Accept-Encoding: gzip`.

**Comment by dmiller-nmap** [comment]
Claudiu Perta did an integration of zlib in GSoC 2015: https://codereview.appspot.com/176420043

I think this is an important thing to include, I just haven't reviewed the code itself.
