### ISSUE TITLE
Npcap installer: Allow setting destination directory with /D

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#536]
c80198c877025 changed the NSIS installer to no longer obey the `/D` option which sets `$INSTDIR` directly. Users have requested this feature in the past: #311 for instance.

**Comment by hsluoyz** [comment]
Which is ``c80198c877025``?

And in fact, Npcap is a very small software which size is less than 1MB. It doesn't occupy much disk space. Why would somebody want to change its install location? One won't gain anything from this as far as I see.

**Comment by dmiller-nmap** [comment]
Oh, I forgot it won't link properly. This works: nmap/npcap@c80198c877025

I don't know what they want to accomplish by this, but I don't see why we can't re-add the check. If `$INSTDIR` is not empty, skip over the setting of Program Files vs Program Files (x86).

**Comment by hsluoyz** [comment]
OK.

**Comment by hsluoyz** [comment]
Hi @dmiller-nmap ,

Npcap can be installed to a specified folder starting from Npcap ``0.09 r2`` now. Please try it at: https://github.com/nmap/npcap/releases/
