### ISSUE TITLE
npcap-0.09.exe doesn't start after installation - no NPFInstall.exe

### ISSUE THREAD

**Issue by techtonik** [nmap/nmap#539]
`npcap-0.09.exe` fails to unpack `NPFInstall.exe`, so installation becomes broken. See errors in `install.log`

[install.log.txt](https://github.com/nmap/nmap/files/454415/install.log.txt)

**Comment by hsluoyz** [comment]
This is because we have dropped Vista's support since Npcap ``0.08 r9``. Before we discuss about the Vista support, you have two ways:

1. use Npcap ``0.08 r8``, this is the last version that supports Vista.
2. upgrate to Win7, doesn't Windows support a free update?

**Comment by hsluoyz** [comment]
Vista's support has been added back in Npcap ``0.09 r3``. Please try it at: https://github.com/nmap/npcap/releases/

**Comment by techtonik** [comment]
Many big thanks! Testing.. )

**Comment by techtonik** [comment]
Do I need to enable WinPcap compatibility mode to make it work with Wireshark?

**Comment by hsluoyz** [comment]
No. Wireshark starts to support Npcap native mode since its 2.1.0 version. So if you are using latest Wireshark 2.2.0, you don't need to enable ``WinPcap compatibility mode`` to work with Wireshark.

**Comment by techtonik** [comment]
Do I need to reboot or start service somehow? Because Wireshark 2.2.0 doesn't see it.

**Comment by hsluoyz** [comment]
Doesn't see what? Please describe what you saw in details. And together provide your **DiagReport* output.

**Comment by techtonik** [comment]
Well, Wireshark starts with admin privileges and there are no capture interfaces:

![image](https://cloud.githubusercontent.com/assets/515889/18341682/cda47be2-75b3-11e6-960b-3f5a5da3217c.png)

```
>"C:\Program Files\Npcap\DiagReport.bat"
'powershell' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by hsluoyz** [comment]
Currently, DiagReport still doesn't work on Vista. I will fix it first.

**Comment by hsluoyz** [comment]
DiagReport relies on Windows's PowerShell. You need to install PowerShell 2.0 (KB968930) on your OS.
For x86 systems: https://www.microsoft.com/en-hk/download/details.aspx?id=9864
For x64 systems: https://www.microsoft.com/en-us/download/details.aspx?id=9239

**Comment by techtonik** [comment]
I can't reboot right now. Too much unfinished work. Python or something that can be unzipped and run without reboots or installs would be fine.

**Comment by hsluoyz** [comment]
Python is not bad, but it means that the Npcap users have to install Python interpreter. I chose PowerShell because it's built-in for nearly all Windows systems (except the Vista). So I still think it's the best solution for all the good.

**Comment by hsluoyz** [comment]
You don't have to reboot or provide DiagReport output for now. I have fixed the issue of Vista's support in latest Npcap ``0.09 r4``. Please try it at: https://github.com/nmap/npcap/releases

**Comment by techtonik** [comment]
Eventually got bluescreen with cryptic error, so had to reboot anyway. I'll skip `r4` and will try `r5` shortly.
