### ISSUE TITLE
NPcap BSOD

### ISSUE THREAD

**Issue by sindy39** [nmap/nmap#558]
Hello,

I have just loaded NPcap 0.10 r2, started (without rebooting first if that may matter) a Wireshark capture on Intel wireless interface in STA mode, and after a while I got the blue screen of death with explanation `IRQL NOT LESS OR EQUAL`.

Windows 10 Anniversary update 64 bit. What else can I do to help investigate the issue?

**Comment by hsluoyz** [comment]
Hi @sindy39 ,

Can you provide these (documented [here](https://github.com/nmap/npcap)):
1. DiagReport
2. install.log
3. BSoD dump (better full dump, at least minidump).

to hsluoyz@gmail.com, thanks!

**Comment by hsluoyz** [comment]
@sindy39 ,

This bug should have been fixed. Please try latest Npcap 0.10 r4 here:
https://github.com/nmap/npcap/releases
