### ISSUE TITLE
Problems with npcap and Intel(R) Ethernet Connection I218-LM

### ISSUE THREAD

**Issue by Hobo2k** [nmap/nmap#567]
After installation of npcap 10 r7 I could capture on different devices with Wireshark 2.2.1 but not on LAN or NPCAP Loopback. This devices told a Link-Layer Header of "DLT -1" not like the other "Ethernet".
After reboot the LAN Interface say driver error and won't connect to LAN. The status Interface was empty.
A remove fixed this.

On my system there is a Windows 7 x64  Version	6.1.7601 Service Pack 1 Build 7601 installed.

**Comment by hsluoyz** [comment]
@Hobo2k , please install Npcap 0.10-r7 debug version, and provide your **DiagReport** and **Packet.log** together, thanks!

**Comment by hsluoyz** [comment]
Since we didn't receive feedback in nearly a week, this will be temporarily closed.

**Comment by Hobo2k** [comment]
Hi,

Sorry, I was offline a few days.
Attached the DiagReport.
[DiagReport-20161018-092945.txt](https://github.com/nmap/nmap/files/535495/DiagReport-20161018-092945.txt)

Where do I find the Paket.log?
This are my install options.
![screenshot_2016-10-18_-_09-25-28](https://cloud.githubusercontent.com/assets/5597327/19468297/e088d2e0-9515-11e6-9ca9-a030c4d5588d.jpg)

![screenshot_2016-10-18_-_09-29-07](https://cloud.githubusercontent.com/assets/5597327/19468298/e0892a88-9515-11e6-8984-1847d9865226.jpg)
I can't capture on the Interface. 
![screenshot_2016-10-18_-_09-33-57](https://cloud.githubusercontent.com/assets/5597327/19468376/3e875b1e-9516-11e6-99ba-9dd0d07c1e4e.jpg)

Thanks

**Comment by hsluoyz** [comment]
Hi @Hobo2k ,

You must install a debug version Npcap to generate ``Paket.log``. I have uploaded the Npcap 0.10 r9 debug version here: https://github.com/nmap/npcap/releases

Please install it and send me the ``Packet.log`` after you perfrom your action to see DLT-1.

**Comment by Hobo2k** [comment]
Hi, how wrote, I can't start any capturing on LAN nor Loopback Interface, see pictures above. It's the same with Npcap 0.10 r9 debug whether Npcap 0.10 r7 debug version.

This is the output of tshark.
```
C:\>tshark -i \Device\NPF_{4245ACD7-1B29-404E-A3D5-1B2FFA180F39}
Capturing on 'LAN'
tshark: The capture session could not be initiated on interface '\Device\NPF_{4245ACD7-1B29-404E-A3D5-1B2FFA180F39}' (failed to set hardware filter to promiscuous mode).

Please check that "\Device\NPF_{4245ACD7-1B29-404E-A3D5-1B2FFA180F39}" is the proper interface.

Help can be found at:

       https://wiki.wireshark.org/WinPcap
       https://wiki.wireshark.org/CaptureSetup

0 packets captured
```

The new DIagReport:
[DiagReport-20161018-103623.txt](https://github.com/nmap/nmap/files/535671/DiagReport-20161018-103623.txt)

**Comment by hsluoyz** [comment]
Was ``Paket.log`` generated after you ran ``tshark -i \Device\NPF_{4245ACD7-1B29-404E-A3D5-1B2FFA180F39}``? If yes, please send it to me.

**Comment by Hobo2k** [comment]
No it isn't generated.

**Comment by hsluoyz** [comment]
Packet.dll in Npcap debug version will generate its log to: ``C:\Program Files\Npcap\Packet.log``. Please make sure you are using Npcap's Packet.dll instead of another version from other software.

**Comment by Hobo2k** [comment]
Okay now installed again without compatibility mode and without Loopback interface:
now it seems working...

[DiagReport-20161018-110141.txt](https://github.com/nmap/nmap/files/535711/DiagReport-20161018-110141.txt)
Also a packet.log is generated, it wasn't before:
[Packet.log.txt](https://github.com/nmap/nmap/files/535737/Packet.log.txt)

I'll try if it's the loopback interface or the compatibility mode.

**Comment by hsluoyz** [comment]
> Okay now installed again without compatibility mode and without Loopback interface:
> now it seems working...

I think you can still choose the Loopback interface option.

> DiagReport-20161018-110141.txt
> Also a packet.log is generated, it wasn't before:
> Packet.log.txt

Since the issue is fixed, I think you don't need to generate ``Packet.log`` anymore. Don't forget to use a non-debug version for better performance.

**Comment by Hobo2k** [comment]
Okay the Error is generated because of the WinPCap API Compatibility Mode.
By using tshark as admin, the packet.log is also generated ;-)
Here the packet log with the error:
[Packet_error.log.txt](https://github.com/nmap/nmap/files/535760/Packet_error.log.txt)

**Comment by Hobo2k** [comment]
Okay it's not all.

After reboot, There's no IP Stack on the nic:
![screenshot_2016-10-19_-_08-55-41](https://cloud.githubusercontent.com/assets/5597327/19512334/a923d512-95eb-11e6-9ce1-98e50c4ba159.jpg)

After diabling the NPF Service on the nic, the connection is possible again.
![screenshot_2016-10-19_-_08-57-49](https://cloud.githubusercontent.com/assets/5597327/19512352/ca24b592-95eb-11e6-8fc0-ea62dc615835.jpg)

**Comment by hsluoyz** [comment]
I noticed that you installed: ``Steelhead, VirtualBox, Sniffer Filter Driver, McAfee``. They are possibly conflicting with Npcap and causing your no IP problem. Please uninstall one software and try again to see if the issue is fixed.

We have maintained an incompatible list [here](https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-incompatible). Let me know the result and I'll put it onto the list too:)

**Comment by Hobo2k** [comment]
Okay, it's a company notebook, so I can't uninstall the McAffee.
Steelhead I don't know which software this should be.
Sniffer Filter Driver is for the Netscout Sniffer Portable. I deinstalled it from the network devices.
Virtual Box is needed for, but I try to deactivate it...

I'll let you know.

**Comment by hsluoyz** [comment]
@Hobo2k , can you try this command ``netsh int ip reset`` to see if the problem is solved?

**Comment by Hobo2k** [comment]
Okay
After deinstalling the `Sniffer Filter Driver` from Network Interfaces, it seems working all fine.
I got an IP by DHCP and sniffering is also working.

Thanks for your support.

**Comment by hsluoyz** [comment]
Good! I will add ``Netscout Sniffer Portable`` to Npcap's incompatible list in the docs.
