### ISSUE TITLE
Added built-in patterns,multiple pattern search and uniqueness of results to http-grep

### ISSUE THREAD

**Issue by h4ck3rk3y** [nmap/nmap#57]
Hi,
I have added support for built-in patterns like email,phone etc and multiple pattern search (more than one pattern/built-in per search)  to http-grep.nse. I have also added unique results as an option. If something falls under one url it won't be shown under any other url if uniqueness(http-grep.unique) is set to true. Apart from uniqueness rest all is the same as here. 
http://seclists.org/nmap-dev/2015/q1/166
The script with uniqueness feature is here :
https://github.com/h4ck3rk3y/nmap/blob/master/test_scripts/http-grep.nse
This also eliminates the need of http-email-harvest.
TODO :
 add richer patterns
 better formatted output

Gyanendra
irc - gyani

**Comment by dmiller-nmap** [comment]
@h4ck3rk3y completed this script in GSOC 2015.
