### ISSUE TITLE
Npcap causing BSOD: PAGE_FAULT_IN_NONPAGED_AREA

### ISSUE THREAD

**Issue by jediminer543** [nmap/nmap#570]
[DiagReport-20161014-194307.txt](https://github.com/nmap/nmap/files/530355/DiagReport-20161014-194307.txt)

[101416-14359-01.zip](https://github.com/nmap/nmap/files/530371/101416-14359-01.zip)

By computer BSODs either when putting my adapter into monitor mode, or taking it out of it. I belive it is a driver issue, but thought I should report it. Attached are the diagnostic reports and the zipped DMP file.

**Comment by hsluoyz** [comment]
Hi @jediminer543 ,

Your uploaded DMP seems to be invalid. It can't be analyzed.

```
************* Symbol Loading Error Summary **************
Module name            Error
ntoskrnl               The system cannot find the file specified
				The SYMSRV client failed to find a file in the UNC store, or there
				is an invalid UNC store (an invalid path or the pingme.txt file is
				not present in the root directory), or the file is present in the
				symbol server exclusion list.
```

So would you please provide a full dump (``MEMORY.DMP``)?

**Comment by hsluoyz** [comment]
I noticed that you have installed ``WinpkFilter, Kaspersky Anti-Virus, SoftEther VPN, VirtualBox``, they can be compatible with Npcap driver. I suggest that you uninstall ``WinpkFilter`` and ``SoftEther VPN`` first, then use Npcap again to see if it has been fixed. If that doesn't work, then uninstall ``Kaspersky`` and ``VirtualBox`` as well, although they are less likely to trigger this issue.

**Comment by hsluoyz** [comment]
Since we didn't receive feedbacks after a week, I would like to close it for now.

**Comment by jediminer543** [comment]
Sorry for lack of update; bug was fixed by driver update

**Comment by hsluoyz** [comment]
@jediminer543 Npcap driver update? That's good!

**Comment by jediminer543** [comment]
For future reference, not the Npcap driver, it was the wireless device's driver
