### ISSUE TITLE
Windows cannot connect to any wifi network

### ISSUE THREAD

**Issue by silk42** [nmap/nmap#571]
Hello there.
Since I've installed nmap+npcap (latest version for Windows) I'm unable to connect to ANY wifi network.
I also tried with an additional usb wifi dongle with no success.
Win 7 Ent 64bit English
Disinstalling nmap+npcap won't work, neither would disabling the protocol driver fro the network.
I've also already checked for restore points with no luck.
I'm stuck.

PS:connection to wifi happens to work in Safe Mode so it's definetly something extra that I cannot find.

Any hints?

**Comment by hsluoyz** [comment]
Please provide the ``DiagReport, install.log, NPFInstall.log`` to me in this session or to my mail: hsluoyz@gmail.com. Thanks!

**Comment by hsluoyz** [comment]
The conclusion is: 
```
It seems that uninstalling the Junos Pulse software for VPN connection did the trick.
I've subsequently reinstalled nmap+npcap and the wifi connection is still working.
```

I will put ``Junos Pulse`` onto the Npcap incompatible list.

**Comment by silk42** [comment]
Here you go.

Let me know if you need anything else.

Regards,
SC

2016-10-17 13:31 GMT+02:00 Yang Luo <notifications@github.com>:
