### ISSUE TITLE
Win7: Npcap LWF driver has failed to be installed

### ISSUE THREAD

**Issue by serious-cnam** [nmap/nmap#572]
[DiagReport-20161019-154912.txt](https://github.com/nmap/nmap/files/539198/DiagReport-20161019-154912.txt)

[install.log.txt](https://github.com/nmap/nmap/files/539204/install.log.txt)

Hi,

When I try to install npcap library, the service installation failed with the output below:

```
NIPO@TFR1NIPO C:\Program Files\Npcap
$ NPFInstall.exe -n -c
Npcap driver cache in Driver Store has been successfully cleaned up!

NIPO@TFR1NIPO C:\Program Files\Npcap
$ NPFInstall.exe -n -iw
Npcap WFP callout driver has been successfully installed!

NIPO@TFR1NIPO C:\Program Files\Npcap
$ NPFInstall.exe -n -i2
Npcap LWF driver (with Wi-Fi support) has failed to be installed.
```

Please can you assist me with the installation?

Thanks for your support.

**Comment by hsluoyz** [comment]
Hi @serious-cnam , please provide the ``NPFInstall.log`` file as well, thanks!

**Comment by serious-cnam** [comment]
[NPFInstall.log.txt](https://github.com/nmap/nmap/files/539634/NPFInstall.log.txt)
Here it is!

**Comment by hsluoyz** [comment]
Hi @serious-cnam 

The ``INetCfgClassSetup::Install`` method fails with 0x8004a029 (``NETCFG_E_MAX_FILTER_LIMIT``), which in [MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff559083(v=vs.85).aspx) means:
```
Indicates that the application is trying to install a filter device, but the maximum number of filter devices that the system supports has already been reached.
```

**Comment by serious-cnam** [comment]
Thank you so much!

Npcap is now up and running :)
In fact the MaxNumFilters was set to 8 so i had just set it to the max number 14.

All the entries listed in the lwf section weren't really LWF but only 8 of them.

`PS C:\Users\nipo\Desktop> .\display-lwf.ps1


MaxNumFilters : 8



Filter Count: 8
Filter List:


Description : Virtual WiFi Filter Driver
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{5CBF81BF-5055-47CD-9055-A76B2B4E3698}

Description : Microsoft Network Monitor 3 Driver
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{6E022F38-AB31-44C5-8206-2EB023EFF145}

Description : Symantec Endpoint Protection Firewall
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{72891E7B-0A3D-4541-BDCB-3DA62E25B6A8}

Description : Zone Alarm Firewall Driver
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{AC30BFB5-834B-46D2-B912-6CE71684EB2D}

Description : QoS Packet Scheduler
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{B5F4D659-7DAA-4565-8E41-BE220ED60542}

Description : WFP Lightweight Filter
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{B70D6460-3635-4D42-B866-B8AB1A24454C}

Description : NativeWiFi Filter
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{E475CF9A-60CD-4439-A75F-0079CE0E18A1}

Description : NDIS Capture LightWeight Filter
PSPath      : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\system\currentcontrolset\control\network\{4d36e974-e325-11ce-bfc1-08002be10318}\{EA24CD6C-D17A-4348-9190-09F0D5BE83DD}`

Once again, thank you for your help pointing me in the good direction.
