### ISSUE TITLE
Weblogic 12c Administration Console fingerprint for http-default-accounts

### ISSUE THREAD

**Issue by cldrn** [nmap/nmap#576]
Anyone with access to a Weblogic 12c Administration Console? I wrote a signature during a pentest engagement but I forgot to write the target_check function so I can't include it in http-default-accounts yet.

This signature is useful as access to the administration console means code execution on the machine. Unfortunately, due to time constraints I made the target_check function always return true and now I need a simple function to check the target is indeed a Weblogic Administration Console. 

`table.insert(fingerprints, {
--Version 12c
  name = "Weblogic Administration Console",
  category = "web",
  paths = {
    {path = "/console/"}
  },
  target_check = function (host, port, path, response)
    return true
  end,
  login_combos = {
    {username = "weblogic", password = "weblogic1"}
  },
  login_check = function (host, port, path, user, pass)
   return try_http_post_login(host, port, path, "j_security_check",
                              "loginFailed",
                              {j_character_encoding="UTF-8", j_username=user, j_password=pass}, true)
  end
})
`
Any help?

**Comment by cldrn** [comment]
Just realized the new target_check function is optional =). Will commit this signature later then.

**Comment by nnposter** [comment]
How about:
```
  target_check = function (host, port, path, response)
    return response.status == 200
           and response.body
           and response.body:find("/console/j_security_check", 1, true)
           and response.body:lower():find("<title>[^<]-weblogic server ")
  end,
```

**Comment by nnposter** [comment]
I have looked around and I see a slightly different failed-login response from 10.3.6 and yet different response from an original BEA version (9.2). The login request itself is the same as yours and the two could share the same `target_check`:
```
  target_check = function (host, port, path, response)
    local loc = response.header["location"] or ""
    return response.status == 302
           and (loc:find("/console/login/LoginForm%.jsp$")
             or loc:find("/console/login/LoginForm%.jsp;"))
  end,
```
I think that either you should make the fingerprint version-specific or we could try to come up with a single generic fingerprint, which would cover several versions and, as a side benefit, application-specific console credentials.

We would need to forego `try_http_post_login()`, hand-rolling the response validation. Something along the following lines:
```
table.insert(fingerprints, {
  -- Version 9.2, 10.3.6
  name = "WebLogic Server Console",
  category = "webtest",
  paths = {
    {path = "/console/"}
  },
  target_check = function (host, port, path, response)
    local loc = response.header["location"] or ""
    return response.status == 302
           and (loc:find("/console/login/LoginForm%.jsp$")
             or loc:find("/console/login/LoginForm%.jsp;"))
  end,
  login_combos = {
    -- WebLogic 9.x
    {username = "weblogic", password = "weblogic"},
    -- WebLogic 10.x
    {username = "weblogic", password = "weblogic1"},
    -- WebLogic 12.x
    {username = "weblogic", password = "welcome1"},
    -- Adobe LiveCycle ES
    {username = "weblogic", password = "password"},
    -- PeopleSoft
    {username = "system", password = "passw0rd"}
  },
  login_check = function (host, port, path, user, pass)
    local req = http_post_simple(host, port,
                                url.absolute(path, "j_security_check"), nil,
                                {j_username=user,j_password=pass,j_character_encoding="UTF-8"})
    local loc = req.header["location"] or ""
    -- WebLogic 9.x
    if req.status == 403 then return false end
    -- WebLogic 10.x
    if req.status == 302 and loc:find("/console/login/LoginForm%.jsp$") then return false end
    return true
  end
})
```
P.S. I have just committed a fingerprint for WebLogic 9.x, which we can yank out if we manage to come up with a unified fingerprint.

**Comment by nnposter** [comment]
Finally I got my hands on 12c. The login flow seems to be the same as for 10.x so there are three options:

1. A fingerprint specific to 10.x/12.x, which can use `target_check` from above and
 1. your `login_check` with `try_http_post_login` *(costing 2 requests)*
 1. a custom `login_check` that looks for the 302-redirect, as outlined above *(costing 1 request)*
1. A unified fingerprint as outlined above (and the latest incarnation below).

It is your call. I am fine with any of them.

The unified fingerprint follows:
```
table.insert(fingerprints, {
  -- Version 8.1, 9.2, 10.3.4, 10.3.6, 12.1.2
  name = "WebLogic Server Console",
  category = "web",
  paths = {
    {path = "/console/"}
  },
  target_check = function (host, port, path, response)
    local loc = response.header["location"] or ""
    return response.status == 302
           and loc:find("/console/login/LoginForm%.jsp%f[;\0]")
  end,
  login_combos = {
    -- WebLogic 9.x
    {username = "weblogic", password = "weblogic"},
    -- WebLogic 10.x, 12.x
    {username = "weblogic", password = "weblogic1"},
    {username = "weblogic", password = "welcome1"},
    -- Adobe LiveCycle ES
    {username = "weblogic", password = "password"},
    -- PeopleSoft
    {username = "system", password = "Passw0rd"}
  },
  login_check = function (host, port, path, user, pass)
    local req = http_post_simple(host, port,
                                url.absolute(path, "j_security_check"), nil,
                                {j_username=user,j_password=pass,j_character_encoding="UTF-8"})
    local loc = req.header["location"] or ""
    -- WebLogic 8.x, 9.x
    if req.status == 403 then return false end
    -- WebLogic 10.x, 12.x
    if req.status == 302 and loc:find("/console/login/LoginForm%.jsp$") then return false end
    return true
  end
})
```

**Comment by cldrn** [comment]
You rock nnposter! One fp for all weblogic console works better. I'm going to let you commit this.

Sorry for the delay, I just started 'unwatching' projects, too much noise is making me miss messages!

**Comment by nnposter** [comment]
Committed in r36461.
Please feel free to close the issue. I do not have sufficient rights.
