### ISSUE TITLE
[npcap] npcap loopback adapter visibility

### ISSUE THREAD

**Issue by Gl0** [nmap/nmap#580]
Current version of this adapter works strange:
It's either seen by wireshark or by sharppcap based program, once you opened device you can't use second program until you restart services:
```
net stop npf
net stop npcap
net start npcap
```
(for wireshark - npf is enough, for sharppcap based programs - npcap is enough, so stopping both)

Checked on fresh install windows 10.0.14393 x64 in hyperv, latest wireshark and sharppcap
[logs.zip](https://github.com/nmap/nmap/files/566677/logs.zip)
In log:
1. install npcap
2. run wireshark (seen loopback there), close wireshark
3. run my program based on sharppcap, not seen loopback, close program
4. restart services
5. run program again, seen loopback there, close program
6. run wireshark again, not seen loopback there

**Comment by hsluoyz** [comment]
Hi @Gl0 , thanks for reporting this! This issue has been fixed in latest ``Npcap 0.10 r14``. Please try it at: https://github.com/nmap/npcap/releases
