### ISSUE TITLE
Windows_10 Blue Screen with NPCap

### ISSUE THREAD

**Issue by liujingliangPacs** [nmap/nmap#582]
[DiagReport-20161104-133837.txt](https://github.com/nmap/nmap/files/570680/DiagReport-20161104-133837.txt)
The following is the problem that I has encountered now:
I was using Winpcap to receive and send packet normally.
Everying is good.

But I want to try the Npcap.

Here is my practice steps:
1. Uninstall the Winpcap from my windows 10.
2. Install the Npcap with the Winpcap compatible mode.
3. Run the application WireShark, the result is OK.
4. Run my application.
   4.1 The moudle of receiving packet run normally.
   4.2 The moudle of sending one packet run normally; ( call api : pcap_sendpacket )
   4.3 The moudle of sending multiple packet run abnormally; ( call api : pcap_sendqueue_transmit )
       The windows blue screen occur.

The dump file is too big, so I can not update here.
Please download it from the following URL:
http://pan.baidu.com/s/1dFBQxmp

best regards.

My Email Address:
liujingliang@163.com

**Comment by hsluoyz** [comment]
Hi @liujingliangPacs ,

Can you provide the DiagReport too? (https://github.com/nmap/npcap/#diagnostic-report) You need to run ``C:\Program Files\Npcap\DiagReport.bat``, then a txt file named ``C:\Program Files\Npcap\DiagReport-<TIME>.txt`` will be generated. Thanks!

**Comment by liujingliangPacs** [comment]
I added the content of diagReport.

**Comment by hsluoyz** [comment]
Hi @liujingliangPacs , your BSoD is mainly caused by a driver named ``rt640x64.sys``, which is the driver of your ``Realtek PCIe GBE Family Controller`` adapter.

1. Can you try Npcap on other adapters (like ``Intel(R) Dual Band Wireless-AC 3165`` in your computer) to see if the BSoD still happens?
2. Can you update your Realtek adapter's driver to the latest release to see if it's fixed?

Thanks!

**Comment by liujingliangPacs** [comment]
1. I try other three adapters in my computer.
    My application runs normally.
    The BSoD doesn't happen.
2. I update the Realtek adapter's driver,  but the BSoD still happen.

So the problem should be the Realtek adapter's driver.

Thank you very much.
