### ISSUE TITLE
Failed to start npcap2 service on Win 7 x86 SP1

### ISSUE THREAD

**Issue by zandr14** [nmap/nmap#584]
Tried to run npcap-0.10-r16.exe on Win 7 x86 SP1. It ends up with the error "Failed to start npcap2 service...". How is it to troubleshoot that?

**Comment by hsluoyz** [comment]
Hi @zandr14 , please provide 3 files based on [docs here](https://github.com/nmap/npcap#bug-report):
1. Diagnostic report (DiagReport)
2. install.log
3. NPFInstall.log

You can upload them to this GitHub conversation.

**Comment by Nokim** [comment]
I can confirm same for npcap-0.10-r18.exe on Win 7 x64 SP1
After install Wi-Fi totally broken until reboot after uninstall.
[logs.zip](https://github.com/nmap/nmap/files/586802/logs.zip)

**Comment by hsluoyz** [comment]
Hi @Nokim , from your log, you encountered the error:
```
Error 0x8004a029: Couldn't install the network component.
```
This error and its solution has been described in: https://github.com/nmap/nmap/issues/572. If you have any further questions, please let me know.

**Comment by Nokim** [comment]
Hi @hsluoyz , yes, that solution allowed me to install drivers and services (i removed some other filters) but all works only until reboot. Then all network connections fail to get IP address via DHCP or send any packet. Removing npcap and rebooting solves that but...

Well, now this looks like another issue.

**Comment by hsluoyz** [comment]
@Nokim ,

Npcap has a few of conflicting software as listed [here in the docs](https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-incompatible). ``No IP under DHCP`` is one of the conflicts listed there. Although you didn't install ``Trend Micro OfficeScan Anti-virus``, the same symptom can be caused by similar software.

I notice you have installed uncommon software like ``COMODO Internet Security Firewall, AppEx Networks Accelerator``. You should try to uninstall them one by one and test if Npcap starts to work after uninstalling them.

**Comment by Nokim** [comment]
@hsluoyz ,
yes, you are right about conflicting software but removing COMODO Internet Security Firewall and AppEx Networks Accelerator didn't help. So didn't help removing OpenVPN and Wireshark. But disabling driver from VirtualBox solved problem. So does disabling npcap driver. But enabling both in same time brake network.

Problem is that i require working networking in VirtualBox.

**Comment by Nokim** [comment]
@hsluoyz ,
yes, you are right about conflicting software but removing COMODO Internet Security Firewall and AppEx Networks Accelerator didn't help. So didn't help removing OpenVPN and Wireshark. But disabling driver from VirtualBox (installed 5.1.8 r111374) solved problem. So does disabling npcap driver. But enabling both in same time brake network.

Problem is that i require working networking in VirtualBox.

**Comment by hsluoyz** [comment]
> fail to get IP address via DHCP or send any packet

What does it mean? Can you receive any packets? Can you set a static IP manually to make the network connected?
