### ISSUE TITLE
Npcap's automatically created hotspot affect other devices' connection speed.

### ISSUE THREAD

**Issue by legendtang** [nmap/nmap#587]
When using latest npcap (e.g. the 0.10 r17), I found an AP created by my computer whose SSID starts with `DIRECT-MF` + `hostname`. The problem is, most wireless card will create the same channel of which AP you connected to therefore other devices' (like your phone) connection speed would be hugely affected by this AP.

I've got no idea why it would create this (maybe to catch wireless traffic?). But could you please stop do this by default.

**Comment by legendtang** [comment]
Also, I am pretty sure I didn't check `Support raw 802.11 traffic (and monitor mode) for wireless adapters`.

**Comment by hsluoyz** [comment]
Hi @legendtang , please provide 3 files based on [docs here](https://github.com/nmap/npcap#bug-report):
1. Diagnostic report (DiagReport)
2. install.log
3. NPFInstall.log

You can upload them to this GitHub conversation.

**Comment by legendtang** [comment]
@hsluoyz Thanks to point out. I've uploaded these three files. Please have a look at them.

[install.txt](https://github.com/nmap/nmap/files/586099/install.txt)
[NPFInstall.txt](https://github.com/nmap/nmap/files/586101/NPFInstall.txt)
[DiagReport-20161111-232622.txt](https://github.com/nmap/nmap/files/586100/DiagReport-20161111-232622.txt)

**Comment by hsluoyz** [comment]
@legendtang ,

Npcap doesn't create any hotspot even if installed with ``Support raw 802.11 traffic`` option selected. So it must be something else.

I noticed that you have installed several possible conflicting software: ``SoftEther VPN, Sangfor SSL VPN, Cisco AnyConnect VPN``. These software may cause your creating hotspot issue.

Can you uninstall them one by one and see whether it's any one of them causing this issue?

**Comment by legendtang** [comment]
@hsluoyz It's quite weird that removing those software nothing was changed, but once npcap was removed the hotspot won't be created automatically. However, I managed to disable the hotspot auto-creation after typing `netsh wlan set hostednetwork mode=disallow`. Anyway, thanks for the investigation. Once someone reproduced this issue can be open again.

**Comment by legendtang** [comment]
@hsluoyz I still encounter this problem when I cleared all the drivers you've mentioned. Could you help me diagnose with the log?
[install.txt](https://github.com/nmap/nmap/files/661333/install.txt)
[NPFInstall.txt](https://github.com/nmap/nmap/files/661334/NPFInstall.txt)
[DiagReport-20161219-225157.txt](https://github.com/nmap/nmap/files/661335/DiagReport-20161219-225157.txt)

**Comment by hsluoyz** [comment]
I also noticed you installed ``Hyper-V`` (and the ``vSwitch driver`` with it) in your log. That can possibly mess with Npcap driver. Please uninstall the ``Hyper-V`` feature entirely and reboot your system. Then re-install Npcap again to try if it's fixed.

And about the SSID, can you capture a screenshot for your `DIRECT-MF` + `hostname` SSID? I can't find many info about this strange SSID name except: http://www.tomshardware.com/answers/id-2227523/direct-viziotv-network.html. It said that it shows when the computer connects to something like a remote control or a remote TV. Did you connect your computer to such a thing? Please disconnect them and uninstall related drivers. Then re-install Npcap again to try if it's fixed.

If the above advice doesn't help, please contact me via QQ: 515964173, say ``Npcap help`` in your add friend message.

**Comment by legendtang** [comment]
@hsluoyz Thank you for your advice. But I've tried remove all `Hyper-V` stuffs before and due to my working requirement I just installed them back. There is no difference. About the weird SSID, I've found nothing but your link.

I cannot bear such WiFi interference so I've reinstalled my OS and most of my current softwares back then it went away. And I believe this issue has little to do with `Npcap`. Please mark this issue with `invalid` tag and, please let me have personal contact with you if I reproduce the same issue in your convenience.

**Comment by mattjreynolds** [comment]
Apologies for posting on an old thread (especially as this is not related to nmap/npcap at all. I'm leaving this here for anyone else with the same issue as this thread is one of the few search results.

The mentions of Hyper-V networking helped me track down the issue. I resolved the problem by going to Network Connections in Control panel. (Hit Win+R and enter ncpa.cpl - or see here: [open-network-connections-in-windows-10](https://www.top-password.com/blog/open-network-connections-in-windows-10/) )
In there I had a couple of hyper-v virtual wifi adapters showing as enabled.
After disabling those, the SSID `DIRECT-MF` + `hostname` + `????` went away. 
Note: once disabled, the virtual wifi adapters are no longer visible, I've not looked into how you'd restore/recreate them again if you decided you wanted them back.
