### ISSUE TITLE
Problem with Sonicwall Global VPN Client

### ISSUE THREAD

**Issue by romariohornburg** [nmap/nmap#600]
Sonicwall Global VPN Client does not work with npcap driver.

**Comment by Varunram** [comment]
@romariohornburg  Winpcap sometimes does not work well with VPNs. Since npcap is based on winpcap, I guess it *might* have the same issue. See http://www.winpcap.org/misc/faq.htm#Q-5 for details on the issue.

**Comment by hsluoyz** [comment]
@romariohornburg , how does ``Sonicwall Global VPN`` conflict with Npcap driver? Like no connection or no IP or something else?

**Comment by hsluoyz** [comment]
Since there's no reply for more than a week, I will close it for now.
