### ISSUE TITLE
Npcap's DiagReport uses Windows 10-only cmdlets

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#611]
`Get-NetAdapter` does not work on Windows 7, for instance, resulting in output like:

```
*************************************************
Network Adapter(s) Info:
*************************************************
Get-NetAdapter : The term 'Get-NetAdapter' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\Npcap\DiagReport.ps1:111 char:1
+ Get-NetAdapter
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetAdapter:String) [], Comm 
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Varunram** [comment]
@dmiller-nmap Get-NetAdapter is not available in Windows 7. 
Source :- https://blogs.technet.microsoft.com/heyscriptingguy/2014/01/15/using-powershell-to-find-connected-network-adapters/
It states that this cmdlet is available only in Windows 8 and above.

**Comment by Varunram** [comment]
I don't think there is any *easy* way to get the network adapter properties without using Net-Adapter. We could write a custom cmdlet and configure it to work with Npcap though.
