### ISSUE TITLE
Installing nmap-7.31-setup.exe on my machine causes all Wi-Fi access to be limited connectivity.

### ISSUE THREAD

**Issue by kumarnipun** [nmap/nmap#613]
Installing nmap-7.31-setup.exe on my machine ( windows 7 professional 64 bit) causes all Wi-Fi access to be limited connectivity.
 I have to uninstall Nmap  and than restart my PC to get it working again.

Please help.

**Comment by hsluoyz** [comment]
Please download latest Npcap here: https://github.com/nmap/npcap/releases and try again.

**Comment by dmiller-nmap** [comment]
Duplicate of #373
