### ISSUE TITLE
I could not capture any packets when using wireshark with npcap in Monitor Mode

### ISSUE THREAD

**Issue by w1nst0nwU** [nmap/nmap#628]
Dear Doctor Luo：
I could not capture any packets when using Wireshark with npcap over my WLAN Adapter。I tried to toggle Monitor Mode in Wireshark and WlanHelper both。

My Adapter is INTEL adv N6205。

**Comment by hsluoyz** [comment]
Please upload your ``DiagReport`` and ``NPFInstall.log`` here based on: https://github.com/nmap/npcap#bug-report

**Comment by wInstonwU** [comment]
[install.log.txt](https://github.com/nmap/nmap/files/681691/install.log.txt)
[NPFInstall.log.txt](https://github.com/nmap/nmap/files/681692/NPFInstall.log.txt)
[DiagReport-20170103-110936.txt](https://github.com/nmap/nmap/files/681693/DiagReport-20170103-110936.txt)


hi,dear Doctor  LUO:  @hsluoyz 

I am appreciate for your reply.
Attachment is the file provided what you metioned.
As the supportion of file format, i changed the name of "install.log" to "install.log.txt“ and  "NPFInstall.log" to "NPFInstall.log.txt“

Thanks again. 罗博士。

**Comment by hsluoyz** [comment]
I noticed you are using a ``Intel(R) Centrino(R) Advanced-N 6205`` wireless adapter. Please verify that adapter actually supports monitor mode. You can run: ``WlanHelper.exe 03987483-2570-4B56-A230-9B082D6AD3AB modes`` to get the supported modes.

**Comment by wInstonwU** [comment]
I have run it as your advice, like the screenshot below
![image](https://cloud.githubusercontent.com/assets/5894033/21599929/49e14b34-d1af-11e6-8b29-ad5c72bb344e.png)

**Comment by hsluoyz** [comment]
Well. It seems that your adapter supports monitor mode. You can run: ``WlanHelper.exe 03987483-2570-4B56-A230-9B082D6AD3AB mode monitor`` to set it to monitor mode and print its output here.

**Comment by wInstonwU** [comment]
I think my Apdater went to Monitor Mode success like the screenshot below.
![image](https://cloud.githubusercontent.com/assets/5894033/21599959/fe9141a6-d1af-11e6-95b1-fda57ea3f181.png)
Thanks again.

**Comment by hsluoyz** [comment]
Don't switch on monitor mode via ``WlanHelper.exe`` if you are capturing with Wireshark. Here're the steps:

1. Make sure your adapter is in Managed Mode (like turning off monitor mode via WlanHelper).
2. Launch WireShark GUI. Then check the monitor mode option in its GUI (QT GUI and GTK GUI is slightly different for this option's location) and then start capturing.
3. Confirm whether you start receiving the wireless packets.

**Comment by wInstonwU** [comment]
I think I had performed like that  which you metioned 1,2,3 when i saw your relay in other issues yestorday.
For  insurance that i performed it again:

> 1.Make sure your adapter is in Managed Mode (like turning off monitor mode via WlanHelper).
I toggled it to Managed Mode and I can run scanning as normal like below
![image](https://cloud.githubusercontent.com/assets/5894033/21600141/ae57be74-d1b2-11e6-86b4-545e8fd5983c.png)

> 2.Launch WireShark GUI. Then check the monitor mode option in its GUI (QT GUI and GTK GUI is slightly different for this option's location) and then start capturing.
I check on the checkbox in Wireshark and click "开始" like below
![image](https://cloud.githubusercontent.com/assets/5894033/21600177/25aa028e-d1b3-11e6-889b-fb8b37ec5c9f.png)

> 3.Confirm whether you start receiving the wireless packets.
I still could not capture any raw 802.11 packets in Monitor Mode like below
![image](https://cloud.githubusercontent.com/assets/5894033/21600197/66938400-d1b3-11e6-85d4-9fbe21c95e78.png)

By the way,I can capture fake Ehthernet packets with that apdater out of Monitor Mode,like below

**Comment by hsluoyz** [comment]
Right now I can't think of other reasons than the wireless adapter itself. Maybe your adapter has poor support for monitor mode/Npcap.

Can you afford to purchase a USB adapter like [NetGear A6200 adapter](http://item.jd.com/1258468.html)? I can assure you it will work because that's the adapter I use to develop Npcap.

**Comment by wInstonwU** [comment]
hi,doctor Luo: @hsluoyz 
I have test in several situations,I found that all INTEL adapter(aha,just two) in my hand could not work on Monitor Mode. look at sreenshot below
![image](https://cloud.githubusercontent.com/assets/5894033/21602592/7874a240-d1d0-11e6-8d32-181a70fa710a.png)
![image](https://cloud.githubusercontent.com/assets/5894033/21602597/8cf48bea-d1d0-11e6-84b9-31fea122fc84.png)


The advice you gived  me upon  to purchase a adapter remained me that I have a NETGEAR WNDA3100v2
adapter. it is success working on Monitor Mode
I have tried to test with other adapter(Realtek RTL8188CU) in my hand and it is success working on Monitor Mode too.

Could you do some analysis with INTEL adapter  if you are willing to.

You are my beacon.
THANKS ALL THE TIME.

**Comment by hsluoyz** [comment]
The on-board wireless adapter in my laptop is ``Intel(R) Dual Band Wireless-AC 3165``: 

And it even doesn't support mode (by running WlanHelper). So I bought the NETGEAR USB adapter. It seems that most of on-board Intel adapters just don't support monitor mode.

I'm willing to do some analysis on more Intel adapters, the problem is I don't have any others. It's even on-board, so it means I need to get a laptop with it to test, which is even difficult for me to do it.

**Comment by wInstonwU** [comment]
You could just bollow or purchase（i think it is cheap，just 30-50rmb） a INTEL on-board adapter instead of buy a laptop.

Now I am sorry to bother you again. I have a new problem:
the `Realtek RTL8188CU adapter` i mentioned (it is a USB adapter),it **could not** working on my laptop which on-board apdater is INTEL N6205,but it **is working** on the laptop which on-board apdater is INTEL N7260(metioned in sreenshot above ).also the INTEL N7260 is always **not** working.
Now i am confused

**Comment by alagoutte** [comment]
@hsluoyz with old release of npcap (0.08), it is possible to capture (with wlanhelper) but with last release don't work (no possible to set monitor mode for me in Qt)

**Comment by wInstonwU** [comment]
hi,@alagoutte
what is the meaning of 

> (no possible to set monitor mode for me in Qt)

I will have a try in release of npcap(0.08)

**Comment by alagoutte** [comment]
With last release, i have no option to set to monitor mode on Wireshark

**Comment by dmiller-nmap** [comment]
I am also having trouble capturing in monitor mode. My adapter is the Alfa AC1200, which is a USB adapter with the Realtek 8812au chipset. The driver that came with it did not support monitor mode, but after I updated the driver, WlanHelper reports that it does, and so does Wireshark. But I can't capture any frames, either using Wireshark to enable monitor mode or by using WlanHelper to enable it.

One thing I found with Wireshark: if you have WinPcap installed, it will prefer that and so will not be able to see the monitor mode stuff that Npcap lets it see. So it only works when Npcap is installed on its own, and not with WinPcap or Win10Pcap.

**Comment by dmiller-nmap** [comment]
We are now tracking compatibility with various WiFi adapters on SecWiki at the [Npcap/WiFi adapters](https://secwiki.org/w/Npcap/WiFi_adapters) page. Please ensure you are using the latest Npcap and follow the directions there for determining level of WiFi capture support. You may update this issue, edit the SecWiki page, or email us directly at dev@nmap.org with adapter info.

**Comment by omax83** [comment]
In the Linux (like airdump-ng and so on get raw dump utilites) works good for Intel N6205 internal wireless card. But in windows wireshark, commview both not work with that card. I think the problem in the Intel driver. Maybe need to find special old version, that support working good in monitor mode and with wireshark (npcap, winpcap tools).
