### ISSUE TITLE
ISCSI scripts do not work

### ISSUE THREAD

**Issue by elitest** [nmap/nmap#631]
I wasn't sure if I should reopen #206 or not so I'm just creating a new issue.  Seems like the issue persists.  When I run nmap 7.40(compiled from source):
```
nmap -sC -sV -d -p 3260 10.10.10.142
```
I get:
```
/usr/local/bin/../share/nmap/nselib/iscsi.lua:592: attempt to index a nil value (local 'auth_method')
stack traceback:
	/usr/local/bin/../share/nmap/nselib/iscsi.lua:592: in method 'discoverTargets'
	/usr/local/bin/../share/nmap/scripts/iscsi-info.nse:81: in function </usr/local/bin/../share/nmap/scripts/iscsi-info.nse:70>
	(...tail calls...)
```
I'm not a lua expert but it seems like the code [here](https://github.com/nmap/nmap/blob/0bb1dc6dc23fdcabd5bbfa0ddc3a8b68bf84d5b1/nselib/iscsi.lua#L584-L594) is the problem?  Does LUA have an issue with the key value pair being set to "None" and then initialized with that value in "local auth_method".  Why does that part of the code even care about auth?  It seems like it addressed better elsewhere possibly?  I am testing against openfiler as in the docs.  I also can do further testing on anything we come up with as it is persistently running in my lab.

BTW if I remove the following lines
```
    p.kvp:add( "AuthMethod", "None" )
```
```
    local auth_method = resp.kvp:get("AuthMethod")[1]
    if ( auth_method:upper() ~= "NONE" ) then
      return false, "ERROR: iscsi.Helper.discoverTargets: Unsupported authentication method"
    end
```
the script doesn't fail, but outputs:
```
Nmap scan report for 10.10.10.142
Host is up, received conn-refused (0.00052s latency).
Scanned at 2017-01-05 20:33:56 CST for 95s
PORT     STATE SERVICE REASON  VERSION
3260/tcp open  iscsi?  syn-ack
|_iscsi-info: 
Final times for host: srtt: 516 rttvar: 3803  to: 100000
```

I know I am running a valid ISCSI target as I have connected to it from Proxmox and written data to it.

**Comment by Varunram** [comment]
@elitest In its current state, I think discoverTargets only scans for those targets which have authentication set to None.  Instead of removing 
```
    p.kvp:add( "AuthMethod", "None" )
    local auth_method = resp.kvp:get("AuthMethod")[1]
    if ( auth_method:upper() ~= "NONE" ) then
      return false, "ERROR: iscsi.Helper.discoverTargets: Unsupported authentication method"
    end
```
try removing only 
```
    if ( auth_method:upper() ~= "NONE" ) then
      return false, "ERROR: iscsi.Helper.discoverTargets: Unsupported authentication method"
    end
```
because if we remove the local variable auth_method, other parts of discoverTargets would be affected. 

For a permanent fix, we would have to tweak the conditional statement a bit I suppose. 
Since I don't have an iSCSI target, could you check if this works?

**Comment by elitest** [comment]
I just pulled from master and it seems that the errors no longer happen, so this has been "fixed" since 7.4.0, however it still outputs no info about the iscsi target.
```
Nmap scan report for 10.10.10.142
Host is up, received conn-refused (0.0029s latency).
Scanned at 2017-01-07 09:53:07 CST for 95s
PORT     STATE SERVICE REASON  VERSION
3260/tcp open  iscsi?  syn-ack
|_iscsi-info: 
Final times for host: srtt: 2930 rttvar: 4457  to: 100000
```
I dug into it a bit, but am out of time for now.  Based on the commit history of iscsi.lua and iscsi-info.nse, it doesn't seem like there is anything obvious that broke this, but there have been some upgrades between lua versions and a bunch of formatting.  Any recommendations for figuring out what may have broken externally or if it was the change from different lua versions?

**Comment by Varunram** [comment]
@elitest I agree with you that there is nothing obvious in iscsi.lua or iscsi-info.nse to break the code like this. I did go through the past commits on both and there was nothing there too. But based on the script output, I think the host might be refusing connections from the NSE script. Is there some script on the target side preventing remote detection/connection?

**Comment by elitest** [comment]
This is a network completely under my control, no IPS or anything else should be interfering.  I installed FreeNAS in a completely different VM and what do you know that worked...
```
Nmap scan report for 10.10.10.178
Host is up, received syn-ack (0.0010s latency).
Scanned at 2017-01-08 21:07:19 CST for 85s
PORT     STATE SERVICE REASON  VERSION
3260/tcp open  iscsi?  syn-ack
| iscsi-info: 
|   iqn.2005-10.org.freenas.ctl:iscsi: 
|     Address: 10.10.10.178:3260,257
|_    Authentication: NOT required
Final times for host: srtt: 1030 rttvar: 3938  to: 100000
```
I'm going to try and fire up wireshark at some point and compare the two, see what is diff.  I still feel that there must be something up with the script.  Openfiler is a working iscsi target.  Seems weird to me.

**Comment by bcoles** [comment]
I ran into the same issue. The cause is a hard-coded IQN in the NSE iSCSI library. Issue #1313 has been created to track this issue.
