### ISSUE TITLE
OS detection 

### ISSUE THREAD

**Issue by capt2101akash** [nmap/nmap#636]
The -O parameter doesn't works for centos 6.x it gives fingerprints for all centos systems which are protected by firewall and to bypass that I have used UDP scan and also did decoy method. It works fine for ubuntu and windows distributors which are also protected by firewall. The output says sometimes too many fingerprints so for that we not even can submit those fingerprint.

**Comment by Varunram** [comment]
@capt2101akash Could you give the output of the script by running it in debug mode?

**Comment by capt2101akash** [comment]
@Varunram  here is the output. 

Starting Nmap 7.40 ( https://nmap.org ) at 2017-01-09 21:28 IST
PORTS: Using top 1000 ports found open (TCP:1000, UDP:0, SCTP:0)
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
mass_rdns: Using DNS server 192.168.1.1
Initiating Parallel DNS resolution of 1 host. at 21:28
mass_rdns: 0.40s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
Completed Parallel DNS resolution of 1 host. at 21:28, 0.40s elapsed
DNS resolution of 1 IPs took 0.40s. Mode: Async [#: 1, OK: 0, NX: 1, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating SYN Stealth Scan at 21:28
Scanning 10.0.3.21 [1000 ports]
Packet capture filter (device wlan0): dst host 192.168.1.30 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.0.3.21)))
Discovered open port 25/tcp on 10.0.3.21
Discovered open port 53/tcp on 10.0.3.21
Discovered open port 22/tcp on 10.0.3.21
Increased max_successful_tryno for 10.0.3.21 to 1 (packet drop)
Discovered open port 80/tcp on 10.0.3.21
Completed SYN Stealth Scan at 21:28, 4.24s elapsed (1000 total ports)
Overall sending rates: 238.68 packets / s, 10502.06 bytes / s.
Packet capture filter (device wlan0): dst host 192.168.1.30 and (icmp or (tcp and (src host 10.0.3.21)))
Initiating OS detection (try #1) against 10.0.3.21
OS detection timingRatio() == (1483977488.597 - 1483977488.096) * 1000 / 500 == 1.002
Retrying OS detection (try #2) against 10.0.3.21
OS detection timingRatio() == (1483977490.963 - 1483977490.462) * 1000 / 500 == 1.002
Retrying OS detection (try #3) against 10.0.3.21
OS detection timingRatio() == (1483977493.321 - 1483977492.820) * 1000 / 500 == 1.004
Retrying OS detection (try #4) against 10.0.3.21
OS detection timingRatio() == (1483977497.577 - 1483977497.077) * 1000 / 500 == 1.000
Retrying OS detection (try #5) against 10.0.3.21
OS detection timingRatio() == (1483977499.939 - 1483977499.438) * 1000 / 500 == 1.000
Nmap scan report for 10.0.3.21
Host is up, received user-set (0.0040s latency).
Scanned at 2017-01-09 21:28:03 IST for 17s
Not shown: 996 closed ports
Reason: 996 resets
PORT   STATE SERVICE REASON
22/tcp open  ssh     syn-ack ttl 63
25/tcp open  smtp    syn-ack ttl 63
53/tcp open  domain  syn-ack ttl 63
80/tcp open  http    syn-ack ttl 63
No exact OS matches for host (If you know what OS is running on it, see https://nmap.org/submit/ ).
TCP/IP fingerprint:
OS:SCAN(V=7.40%E=4%D=1/9%OT=22%CT=1%CU=40367%PV=Y%DS=2%DC=I%G=Y%TM=5873B31C
OS:%P=i686-pc-linux-gnu)SEQ(SP=105%GCD=1%ISR=10A%TI=Z%II=I%TS=A)SEQ(SP=105%
OS:GCD=1%ISR=10A%TI=Z%TS=A)OPS(O1=M5B4ST11NW7%O2=M5B4ST11NW7%O3=M5B4NNT11NW
OS:7%O4=M5B4ST11NW7%O5=M5B4ST11NW7%O6=M5B4ST11)WIN(W1=3890%W2=3890%W3=3890%
OS:W4=3890%W5=3890%W6=3890)ECN(R=Y%DF=Y%T=40%W=3908%O=M5B4NNSNW7%CC=Y%Q=)T1
OS:(R=Y%DF=Y%T=40%S=O%A=S+%F=AS%RD=0%Q=)T2(R=N)T3(R=N)T4(R=N)T5(R=Y%DF=Y%T=
OS:40%W=0%S=Z%A=S+%F=AR%O=%RD=0%Q=)T6(R=N)T7(R=N)U1(R=Y%DF=N%T=40%IPL=164%U
OS:N=0%RIPL=G%RID=G%RIPCK=G%RUCK=346B%RUD=G)IE(R=Y%DFI=N%T=40%CD=S)

Uptime guess: 0.216 days (since Mon Jan  9 16:17:51 2017)
Network Distance: 2 hops
TCP Sequence Prediction: Difficulty=261 (Good luck!)
IP ID Sequence Generation: All zeros
Final times for host: srtt: 3965 rttvar: 2814  to: 100000

Read from /usr/local/bin/../share/nmap: nmap-os-db nmap-payloads nmap-services.
OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 18.86 seconds
           Raw packets sent: 1169 (56.340KB) | Rcvd: 1061 (45.906KB)

**Comment by Varunram** [comment]
@capt2101akash Are you using CentOS v6.3/6.4/6.5/6.6?

**Comment by capt2101akash** [comment]
@Varunram  No I amusing ubuntu 14.04 but I am doing the scan on a centos system and that is what my issue is, for centos system it is not able to detect the OS version but for other operating systems it is able to do that.

**Comment by Varunram** [comment]
I mean do you know the OS of the target machine? Because if the version is not in those specified above, then its fingerprint does not exist in the database and you'll have to submit the same.

**Comment by capt2101akash** [comment]
Yeah I know and I had already submitted the fingerprints on nmap.org/submit but the problem is for all the centos systems I guess. So I think the -o parameter should be modified more to get the inner details of the centos machine.

**Comment by dmiller-nmap** [comment]
@capt2101akash The problem is in the `U1.RUCK` (UDP probe 1, Received UDP Checksum) test, which is showing a value of 0x346B instead of the expected "G" value, which would mean a Good (correct) checksum. Something (either your scanning system or a router or firewall) between you and the target is altering packets or spoofing replies. This makes it impossible for Nmap to get a 100% match with its database, since CentOS (any version) does not generate responses with bad checksums.

You can work around this problem by using the `--osscan-guess` option, which should show a 96% match for "Linux 2.6.32" and a 95% match for "Linux 2.6.32 or 3.10", etc. You are welcome to submit this fingerprint via https://nmap.org/submit/ but we will likely not be able to use it since it contains destructive interference in the UDP checksum.
