### ISSUE TITLE
Zenmap "Easy" mode to get nmap $25k from FTC?

### ISSUE THREAD

**Issue by BryanQuigley** [nmap/nmap#637]
The FTC is having a contest: https://www.ftc.gov/node/1010523 and I think nmap is the best item out there for fulfilling it.

From my point of view the key items would make it better would be an "easy" mode (choice on first run) that would:
1. be preset to do the local subnet only (with warning if it's more than 256).
2. preset scan to run
3. hide most technical details during run (mostly just display a progress bar / time left)
4. report just the relevant details for a non-techy from the script.

Other issues:
IPv6?  Allow them to copy list of addresses from their router?

Thoughts on if you would accept patches adding this to zenmap?

**Comment by dmiller-nmap** [comment]
@BryanQuigley Thanks for the interesting idea! I do think that Nmap could be a key component in a winning solution, but I don't think that Zenmap would be the best starting point. Here's what I think Nmap has to offer:

* Recognizing IoT devices. Nmap's OS and service detection capabilities are second to none, and expanding them to cover any device is as simple as sending the scan of that device to us via https://nmap.org/submit/
* Determining software version. Same argument.
* Scalability. Nmap can scan and report on just about any device that exists.

Where Zenmap would fall short:

* Ease of use. Admittedly, this is what your proposal seeks to remedy, but Zenmap is still a general-purpose scanning tool for experts, and the FTC is seeking a special-purpose tool for homeowners.
* Determining version of software that **should** be on the devices and assisting with firmware updates. This is really outside the scope of Nmap/Zenmap, so it would require a new tool to be written. Possibly this could be a NSE script, or at least some component would be, but that's separate from a patch to Zenmap.

I will point out 2 things from your proposal that we would be very interested in implementing for Nmap in general:

* Local subnet detection. We already do detection of local subnet for the purpose of routing and ARP vs raw-IP host discovery, but we don't have an easy "scan my LAN" option or syntax; you have to look up your IP and netmask and translate them to an address range in order for Nmap to scan.
* Progress bar/time left display for Zenmap. Nmap produces output suitable for this purpose, but Zenmap doesn't parse it.

**Comment by dmiller-nmap** [comment]
The contest is over. Closing this issue.
