### ISSUE TITLE
How to capture on monitor mode using the Npcap SDK?

### ISSUE THREAD

**Issue by yohannest** [nmap/nmap#646]
npcap sdk question.

After setting the card to monitor mode, I can capture 802.11 frames using wireshark but I could not capture any frames using the npcap sdk. The existing samples included in the sdk also don't capture any frames.

What do i need to do to be able to capture the 802.11 frames using the sdk?

**Comment by Varunram** [comment]
@YohannesT  May I know what adapter you are using? If you're using an Intel adapter,  I don't think it will work as answered by Dr.Luo @hsluoyz in #628

**Comment by hsluoyz** [comment]
@YohannesT  Please provide your DiagReport, which will describe your physical adapters. I personally develop Npcap under ``NetGear A6200``, a USB adapter. This can be guaranteed to work.

**Comment by hsluoyz** [comment]
Hi @YohannesT , I misunderstood your question. So you want to know how to capture on monitor mode with Npcap SDK.

1. Update to latest Npcap SDK, the previous SDK has some change issues.
2. Did you call ``pcap_set_rfmon`` to set the monitor mode in your code?
