### ISSUE TITLE
Update/Do tests for zenmap and nmap

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#662]
At the moment, we do not have any up to date tests for nmap and zenmap. Similar utilities (eg. Metasploit) have extensive (and sort of up to date) tests to cover the wide range of the scripts'  capabilities. Once we add more tests, it'd be simpler to migrate (and obviously test) code when future updates of python arrive.

**Comment by fgeek** [comment]
It is always good to have more test cases, but I am not sure if this issue tracker is the best way to keep track of this kind of improvement. Does Nmap project have continuous integration system (e.g. Jenkins or similar) at the moment?

**Comment by Varunram** [comment]
Nmap does have Travis CI at the moment. What I meant was there are a bunch of files that haven't been updated in five years or so, and I don't think they are all that useful now. So we could consider updating them or removing them altogether.

**Comment by fyodor** [comment]
Thanks.  We're closing this issue since it's sort of subsumed by our new CI/testing issue: #2768 .
