### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mikhoul** [nmap/nmap#663]
Hi,

I tried to install Npcap 0.80 from Github https://github.com/nmap/npcap/releases under Win 7/64 pro and the installation abort.
The installer say that he is not able to create the services.

I join the installation log to help you to find what happen and how correct it.

[Log.zip](https://github.com/nmap/nmap/files/721343/Log.zip)

:octocat:

**Comment by Varunram** [comment]
@mikhoul I'll look into the issue, Seems like there is a problem with the Packet Install Driver installing. Did previous versions of Npcap work fine with your system?

**Comment by Varunram** [comment]
@mikhoul Could you run NPFInstall.exe -iw and provide the output here?

**Comment by hsluoyz** [comment]
@mikhoul  Your error code is ``0x8004a029``. This is a commonly happened issue. Please refer to: https://github.com/nmap/nmap/issues/572

**Comment by dmiller-nmap** [comment]
I think perhaps we should check for this condition in the installer (either NPFInstall.exe or the NSIS installer). It should be as simple as checking the registry value for the max number of filters and then checking the number of installed filters and seeing if there's room to install Npcap or not.

**Comment by hsluoyz** [comment]
Different OS have different limitations. So checking the registry value can be tricky, not even mention you have to check the number of installed filters. A better way seems to be just capturing the error code ``0x8004a029`` and showing a message box about it.

**Comment by dmiller-nmap** [comment]
Thanks @hsluoyz I'll try that method. Looks like Windows 8 and later removed the limit, but still reads the registry key, so upgrade installs may have an artificial limit, too. https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/9ac148ba-390f-410f-ba74-c8e992369632/is-maxnumfilters-max-ndis-filters-registry-value-on-windows-8-removed?forum=wdk

**Comment by dmiller-nmap** [comment]
See nmap/npcap@695a871
