### ISSUE TITLE
NSE verbosity

### ISSUE THREAD

**Issue by aress31** [nmap/nmap#674]
The nmap scripts are very powerfull! Hence, I rely extensively on them, however, I think that improvements could be done to the output. 

Indeed, when setting no verbosity we hardly see if the script were properly running during the scan (we can only see the results from successfull scripts). Even when setting verbosity we do not even get the name of the current NSE script running. See the following output:

Completed NSE at 15:17, 0.00s elapsed
Initiating NSE at 15:17
Completed NSE at 15:17, 0.00s elapsed
Initiating NSE at 15:17
Completed NSE at 15:17, 0.00s elapsed
Initiating Ping Scan at 15:17

My request is to improve the verbosity of the scripts to be able to troubleshot and follow the scan activity even when no verbosity is set.

Thanks.

**Comment by Varunram** [comment]
@AresS31 Good suggestion, but I think there are various levels of verbosity already and it would be a bit complicated and unnecessary to add more verbosity. For troubleshooting, we do have -d and -d2 which provide a good follow up of what happens in the scan. For less output, -v and -vv provide a good range of output. In addition to this, we have -v0 too. So depending upon the user's discretion, nmap prints the output accordingly. Here's a small table with the stats

1. -d2     1083 lines
2. -d          66 lines
3. -vv         51 lines
5. -v0          0 lines

**Comment by dmiller-nmap** [comment]
Related #280

**Comment by dmiller-nmap** [comment]
Verbose output (`-v`) will print the number of active and waiting NSE script threads when stats are printed (press any key or use `--stats-every`). The status of individual NSE scripts is printed with debug output (`-d`), and the debug level can be adjusted while running by using the [runtime interaction](https://nmap.org/book/man-runtime-interaction.html) feature. Currently, at debug level 1, the name and number of threads of each running script is printed if there are 5 or fewer scripts running. At debug level 2, a full stack trace of each running thread is printed. We do not have plans to improve this level of detail. Specific suggestions can be made in a new issue. We also are tracking ideas for improving time-remaining estimates at #701.
