### ISSUE TITLE
[npcap] Windump crashing on start

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#697]
Hello,
I cannot use windump.exe, which is provided with npcap...

When i start it, i get the error (in french):
http://imgur.com/a/GNFBG

Which means:
> The entry point method getservent does not exist in the dynamic links library
> C:\Windows\System32\Npcap\windump.exe

I'm working with Npcap 0.81  installed with default options, on a x64 windows 10 (latest insider) computer.
wpcap.dll is working perfectly

I would really like to have it working...

Side note: I used to have Winpcap, which I uninstalled with the GUI, 
then removed manually `C:\Windows\System32\Packet.dll` and `C:\Windows\System32\wpcap.dll`.

**Comment by dmiller-nmap** [comment]
Thanks for the report. WinDump is not provided with Npcap, so it's possible that the version you have installed was built for an earlier version of Npcap. If you install Npcap in WinPcap-compatibility mode, it should work, but I believe @hsluoyz has a Npcap-compatible WinDump repository, if you are able to compile it yourself. Please let us know if you believe the situation is different.

**Comment by hsluoyz** [comment]
Just as Dan said, the original WinDump can't be used with Npcap, because the latest Libpcap interface has removed some deprecated functions which are imported by it. Please use the WinDump here: https://github.com/hsluoyz/WinDump

**Comment by gpotter2** [comment]
Very right, sorry for bothering

**Comment by gpotter2** [comment]
Ok, so i've tried using the provided version. I got a problem related to Windump, so i will post it in the WinDump repo.

**Comment by gpotter2** [comment]
Here is the issue
https://github.com/hsluoyz/WinDump/issues/1
