### ISSUE TITLE
NSE script. Find open ports,services and detect OS

### ISSUE THREAD

**Issue by MAXXAMMAX** [nmap/nmap#698]
Hello all! Help me please.
There is a task: Scan a scope of IP's. Find open ports and services. Try to detect OS. Do not check 45001, 45002, 45003 ports if detected that OS==Windows. Write results to txt file so:

> IP adress 1 /host name/ mac-adress/ OS
> port number/ service name
> port number/ service name
> port number/ service name
> 
> IP adress 2 /host name/ mac-adress/ OS
> port number/ service name
> port number/ service name
> port number/ service name

I tried what i understood in NSE:
```
portrule = function(host, port)
    return port.protocol == "tcp"
            and port.state == "open"
end

-- The Action Section --
action = function(host, port)

    local host_ip=host.ip
    local host_name=host.name
    if (host_name==nil)then
    host_name="unknown"
    end
    local host_mac_addr=host.mac_addr
    if (host_mac_addr==nil)then
    host_mac_addr="unknown"
    end
    local port_protocol=port.protocol
    if (port_protocol==nil)then
    port_protocol="unknown"
    end
    local port_service=port.service
    if (port_service==nil)then
    port_service="unknown"
    end
    local port_reason=port.reason
    if (port_reason==nil)then
    port_reason="unknown"
    end
    local port_state=port.state
    if (port_state==nil)then
    port_state="unknown"
    end
    local port_number=port.number
    if (port_number==nil)then
    port_number="unknown"
    end
    local port_version_name=port.version.name
    if (port_version_name==nil)then
    port_version_name="unknown"
    end

    file = io.open ("scanresult.txt","a+")
    file:write (host_ip..""..host_name.." "..host_mac_addr.." "..port_number.." "..port_version_name.." "..port_state.." "..port_protocol.."\n")
    file:flush()
    file:close()

    local result=host_ip..""..host_name.." "..host_mac_addr.." "..port_number.." "..port_version_name.." "..port_state.." "..port_protocol

    return result
end
```
But i have next troubles:
1. I dont know how try to detect OS (i saw code in smb-system-info.nse and smb-os-discovery.nse, but cant apply its for my script)
2.  And cause i use "portrule" each time appears record in txt file when Nmap finds ports. I think for my task will be better to use "hostrule", but i dont know how in "action" make port searching?

P.S. Sorry, my English is not so good. In my native language there are not so many FAQ about NSE.

**Comment by dmiller-nmap** [comment]
NSE is probably not a good solution for this. Instead, you could use a shell script to set Nmap options to do what you want. Check out the Nmap book sections on output formats to get ideas for how to parse the output and put it in the format you want: https://nmap.org/book/output.html
