### ISSUE TITLE
Issues with smb-enum-shares and smb-enum-users

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#704]
smb-enum-shares seems to work, but has a few issues (one of which seems to be fixed in #266 through 2db52ae951dc1c6ea854b198d16144af622d065b). smb-enum-users however doesn't seem to return any output. 

Related: #238, #266

**Comment by tnaami** [comment]
I updated to the latest NMAP (7.40) and still no users.  I ran with the -d debug and it appears to fail logging in as guest from what I see.  Guest is disabled by group policy on all of our computers.

Ideas? Suggestions?

**Comment by cldrn** [comment]
Ok I have found the issue and fixed it. I'll post the patch soon, just need to clean up the code a bit.
