### ISSUE TITLE
Issues with broadcast-dhcp-discover

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#714]
Reported earlier in http://seclists.org/nmap-dev/2017/q1/87, but more reports regarding the same have been coming in, so it doesn't seem like an one-off issue. The log is at https://bpaste.net/show/129e402a688f

**Comment by rewanth1997** [comment]
The script is working fine in the latest version. You can close this issue.

**Comment by nnposter** [comment]
Apparently resolved
