### ISSUE TITLE
Npcap prevent computer to sleep

### ISSUE THREAD

**Issue by lkytal** [nmap/nmap#721]
I wonder why there is not issue section for npcap itself...

After switch from winpcap to npcap, my system can't sleep correctly. It used to sleep after 15min, however, after installed npcap, my system will automatically power off after 15min instead of go sleep. My system is windows 10 1607 x64, npcap version 0.82 (newest for now).

**Comment by Varunram** [comment]
Good catch! I don't know about the computer shutting down, but I did notice that when I installed Npcap, it seems to change the sleep settings. Thing to note here is that it changes the sleep settings only if they are changed after Npcap is uninstalled. If we change the settings when Npcap is installed and don't touch it thereafter even after uninstalling, it doesn't seem to do anything.

**Comment by dmiller-nmap** [comment]
Can either of you report exactly what the sleep settings were and whether they were changed? Or are the settings the same, but the behavior is different?

@lkytal was there a crash? Is there a .dmp file in `C:\Windows\minidump\` that you could send to dmiller@nmap.com?

**Comment by Varunram** [comment]
Steps to reproduce:
1. Set timer to 1 minute 
2. Install Npcap
3. Wait for 1 minute (to test whether the computer sleeps)
4. Go to settings and find out that the sleep timer has changed.

**Comment by lkytal** [comment]
@dmiller-nmap I've emailed dump file to you. The change of system sleep timer may not allway happend.

**Comment by dmiller-nmap** [comment]
Thanks, I now have 2 different dump files for this crash. Hope to have it
resolved soon.

**Comment by dmiller-nmap** [comment]
@lkytal Please try Npcap 0.83, released yesterday, which has this fix. Let us know if it solves your problem!

**Comment by lkytal** [comment]
During the last day it works perfectly, thanks. @dmiller-nmap
