### ISSUE TITLE
nmap TLS scan not matching openssl scan

### ISSUE THREAD

**Issue by YTKme** [nmap/nmap#730]
I am trying to scan an endpoint to see what TLS version it is running and I am seeing some discrepancy between the nmap scan and the openssl scan. Scanning the same host I see only TLSv1.0 from nmap (7.40) and I can see TLSv1.2 with openssl (1.0.1e). I also scan the same host with Qualys SSL Labs and it seem to be getting TLSv1.2 also. So I was wondering why nmap is only showing TLSv1.0? (result of scan below)

**nmap scan:**
```
localhost:~ user$ nmap -sV --script ssl-enum-ciphers -p 443 <example.com>
 
Starting Nmap 7.40 ( https://nmap.org ) at 2017-02-11 13:13 PST
Nmap scan report for <example.com> (xxx.xxx.xxx.xxx)
Host is up (0.016s latency).
PORT    STATE SERVICE  VERSION
443/tcp open  ssl/http Apache Tomcat/Coyote JSP engine 1.1
|_http-server-header: Apache-Coyote/1.1
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (secp192r1) - D
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp192r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp192r1) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Key exchange (secp192r1) of lower strength than certificate key
|_  least strength: D
 
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 24.51 seconds
localhost:~ user$
```

**openssl scan:**
```
SSL handshake has read 8589 bytes and written 453 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: XXX
    Session-ID-ctx:
    Master-Key: XXX
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1486848462
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by dmiller-nmap** [comment]
Thanks for the report. I think you reported this [on ServerFault](https://serverfault.com/questions/832207/tls-version-scan-discrepancy-between-nmap-openssl-ssllab), and I introduced a change in 6f8ec3906 that should have fixed it. Have you downloaded the latest [ssl-enum-ciphers](https://nmap.org/nsedoc/scripts/ssl-enum-ciphers.html) to see if that solves the problem?

**Comment by dmiller-nmap** [comment]
@YTKme I am closing this issue, since I believe it has been fixed. If you still have a problem, please reopen or comment here.

**Comment by tok7886** [comment]
@dmiller-nmap I'm having a similar issue with the latest version of the ssl-enum-ciphers script. I'm scanning a host that supports SSLv3, TLSv1.0, TLSv1.1 and  TLSv1.2. The ssl-enum-ciphers script detects the other ciphers, but it does not detect that TLSv1.2 is available on that server. If I scan it with:

`openssl s_client -connect servername:port -tls1_2`

I see that openssl successfully connects using TLSv1.2:

```
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
---
```

I've attached the debug output, if that can help in identifying the problem.
[output.zip](https://github.com/nmap/nmap/files/2094000/output.zip)
