### ISSUE TITLE
Flag -n is not always working as expected

### ISSUE THREAD

**Issue by fgeek** [nmap/nmap#734]
When running 7.40 with params: `nmap -n -sL -iL list` and list contains `fe80::3432:64ff:fu64:3666/64` I can see following network traffic:

> 11:04:14.044701 IP 10.0.0.51.49736 > 10.0.0.254.53: 42251+ A? fe80::3432:64ff:fu64:3666. (43)
> 11:04:14.051234 IP 10.0.0.51.49736 > 10.0.0.254.53: 19319+ AAAA? fe80::3432:64ff:fu64:3666. (43)
> 11:04:14.061676 IP 10.0.0.51.37506 > 10.0.0.254.53: 42251+ A? fe80::3432:64ff:fu64:3666. (43)
> 11:04:14.074976 IP 10.0.0.51.37506 > 10.0.0.254.53: 19319+ AAAA? fe80::3432:64ff:fu64:3666. (43)

Shouldn't -n flag block all DNS queries?

**Comment by dmiller-nmap** [comment]
`-n` blocks *reverse* DNS, so you will not send any `PTR` queries to determine the name associated with a numeric IP.  Forward lookups to resolve names to numeric IPs will still happen. In your case, you provided "fe80::3432:64ff:f**u**64:3666/64", which at first looks like an IPv6 address. But "u" is not a hexadecimal character, so Nmap treats the whole thing as a hostname and tries to resolve it (`A` or `AAAA` query).

**Comment by fgeek** [comment]
Thank you for fast reply.
