### ISSUE TITLE
ndiff documentation is referring to html-title

### ISSUE THREAD

**Issue by fgeek** [nmap/nmap#746]
Documentation of ndiff is refering to html-title. How do I generate .1 file from the XML? I can populate the documentation from http-title.

**Comment by Varunram** [comment]
The tool is provided in the doc ```Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>```. I, however, manually edited the pages (since the differences are minimal).

**Comment by fgeek** [comment]
Great thanks.
