### ISSUE TITLE
bad TCP package

### ISSUE THREAD

**Issue by YJJ690386995** [nmap/nmap#771]
Hello, I have installed Npcap, and then use Wireshark to capture traffic of locallhost. However, the packages are bad TCP in black background and red words. Then I check the npcap loopback adapter, it shows "Not recognized network".
![image](https://cloud.githubusercontent.com/assets/5127691/24046099/56c92024-0b5c-11e7-8b71-f3742089c936.png)
[locallhost.ZIP](https://github.com/nmap/nmap/files/850704/locallhost.ZIP)

**Comment by Varunram** [comment]
Hi there, could you tell us a little more regarding what operating system you use and other details? The attachment fails to decompress so it'd be great if you could upload it again. Thanks!

**Comment by YJJ690386995** [comment]
I use Window 10. I want to use Wireshark to capture the traffic of an instant messaging system running in the localhost:3000.  Since this is  traffic from a my computer to  my computer, I installed Npcap and capture on loopback interfaces. However, there are so many bad TCP packages captured in the attached file.

[pcap.zip](https://github.com/nmap/nmap/files/850741/pcap.zip)

**Comment by hsluoyz** [comment]
Hi @YJJ690386995 , what you see is the warning of Wireshark. It shows that your programs are re-using the TCP sequence number for multiple packets, which are regarded as abnormal by Wireshark. For example, in your locallhost.ZIP, No. 1 and No. 3 packets are both from TCP port 50312, and they use the same TCP sequence number: 40 70 ff 1c. This is why No. 3 packet is warned with black color. The same reason applies to No. 2 and No. 4 packets of port 28434, and so on.

So you should figure out why your programs use the same TCP sequence numbers for all the packets. This should be avoided. You can usually use Socket API for TCP communication, and socket will handle the TCP sequence numbers for you automatically.

**Comment by YJJ690386995** [comment]
Thank you for your help!
