### ISSUE TITLE
nmap not able to match nginx reverse proxy on HTTPS port

### ISSUE THREAD

**Issue by kiran-dp** [nmap/nmap#787]
I've nginx server with https/443 open, port 80 is not open. HSTS is enabled on 443.

When I try to detect the service running on port 443, getting ''400 The plain HTTP request was sent to HTTPS port' error. Closest issue I found was #168, explicitly adding "--script ssl-enum-ciphers" didn't help in my case. Post at http://seclists.org/nmap-dev/2015/q2/312 indicate SSLSessionReq probe would be ran first in case of standard SSL port, but it doesn't seem to be doing this.

Added ncat and nmap output below. Appreciate any help in this regard.

Thanks,
-Kiran
--------------------------------------------------------
```
nmap-7.40# (echo -e 'GET / HTTP/1.0\r\n\r\n'; sleep 3) | ncat 172.28.46.137 443
HTTP/1.1 400 Bad Request
Date: Mon, 20 Mar 2017 11:52:03 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 264
Connection: close
Cache-Control: no-store
Pragma: no-cache
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubdomains;

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

```
-----------------------------------------------------
```
nmap-7.40# ./nmap -sV --version-intensity 1 -p 443  172.28.46.137

Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-20 19:27 UTC
Nmap scan report for 172.28.46.137
Host is up (0.00089s latency).
PORT    STATE SERVICE    VERSION
443/tcp open  ssl/https?
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port443-TCP:V=7.40%T=SSL%I=1%D=3/20%Time=58D02D4B%P=x86_64-unknown-linu
SF:x-gnu%r(vmware-esx,212,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nDate:\x20
SF:Mon,\x2020\x20Mar\x202017\x2012:27:58\x20GMT\r\nContent-Type:\x20text/h
SF:tml;\x20charset=utf-8\r\nContent-Length:\x20166\r\nConnection:\x20close
SF:\r\nCache-Control:\x20no-store\r\nPragma:\x20no-cache\r\nContent-Securi
SF:ty-Policy:\x20default-src\x20'self'\r\nX-Content-Type-Options:\x20nosni
SF:ff\r\nX-XSS-Protection:\x201;\x20mode=block\r\nStrict-Transport-Securit
SF:y:\x20max-age=31536000;\x20includeSubdomains;\r\n\r\n<html>\r\n<head><t
SF:itle>400\x20Bad\x20Request</title></head>\r\n<body\x20bgcolor=\"white\"
SF:>\r\n<center><h1>400\x20Bad\x20Request</h1></center>\r\n<hr><center>ngi
SF:nx</center>\r\n</body>\r\n</html>\r\n")%r(tor-versions,212,"HTTP/1\.1\x
SF:20400\x20Bad\x20Request\r\nDate:\x20Mon,\x2020\x20Mar\x202017\x2012:27:
SF:58\x20GMT\r\nContent-Type:\x20text/html;\x20charset=utf-8\r\nContent-Le
SF:ngth:\x20166\r\nConnection:\x20close\r\nCache-Control:\x20no-store\r\nP
SF:ragma:\x20no-cache\r\nContent-Security-Policy:\x20default-src\x20'self'
SF:\r\nX-Content-Type-Options:\x20nosniff\r\nX-XSS-Protection:\x201;\x20mo
SF:de=block\r\nStrict-Transport-Security:\x20max-age=31536000;\x20includeS
SF:ubdomains;\r\n\r\n<html>\r\n<head><title>400\x20Bad\x20Request</title><
SF:/head>\r\n<body\x20bgcolor=\"white\">\r\n<center><h1>400\x20Bad\x20Requ
SF:est</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r
SF:\n")%r(SSLSessionReq,212,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nDate:\x
SF:20Mon,\x2020\x20Mar\x202017\x2012:28:03\x20GMT\r\nContent-Type:\x20text
SF:/html;\x20charset=utf-8\r\nContent-Length:\x20166\r\nConnection:\x20clo
SF:se\r\nCache-Control:\x20no-store\r\nPragma:\x20no-cache\r\nContent-Secu
SF:rity-Policy:\x20default-src\x20'self'\r\nX-Content-Type-Options:\x20nos
SF:niff\r\nX-XSS-Protection:\x201;\x20mode=block\r\nStrict-Transport-Secur
SF:ity:\x20max-age=31536000;\x20includeSubdomains;\r\n\r\n<html>\r\n<head>
SF:<title>400\x20Bad\x20Request</title></head>\r\n<body\x20bgcolor=\"white
SF:\">\r\n<center><h1>400\x20Bad\x20Request</h1></center>\r\n<hr><center>n
SF:ginx</center>\r\n</body>\r\n</html>\r\n");

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 17.60 seconds

```

**Comment by Varunram** [comment]
@kiran-dp I think the issue has to do more with your vhosts' configuration than with nmap itself. Do check you have ```listen 443 ssl; ``` instead of ```listen 443; ssl on``` in your config file. This is with the assumption that you don't make the mistake of serving both http and https on the same port.

**Comment by dmiller-nmap** [comment]
Nmap is correctly detecting SSL, most likely based on the error message. You can see this in the service fingerprint where it has `T=SSL`. That means that all the probes listed and their responses came from within an SSL tunnel. The odd thing to me is that the `GetRequest` probe did not produce any response. Could you run the Nmap command again with the addition of `--version-trace` to see the probes that are sent in order? There might be an issue there.

**Comment by kiran-dp** [comment]
Thanks for responses Varun, Daneil.
I missed that 'T=SSL' in output as I was comparing nmap 6.40 (we are using today) vs nmap 7.40 output, just kept looking at 'Bad Request..' part. I just re-tried with latest version and getting expected result. 

Here is output with --version-trace. As I'm getting expected result, go ahead and close the issue if no issues with below output.
`# nmap -sV --version-light --version-trace -oX tt.xml -p 443 172.28.46.137

Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-23 16:44 UTC
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI:
NSE: Loaded 40 scripts for scanning.
Packet capture filter (device eth0): dst host 172.17.0.3 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 172.28.46.137)))
We got a ping packet back from 172.28.46.137: id = 42187 seq = 0 checksum = 23348
Overall sending rates: 1663.20 packets / s, 63201.66 bytes / s.
mass_rdns: Using DNS server 171.70.168.183
mass_rdns: 0.00s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
DNS resolution of 1 IPs took 0.00s. Mode: Async [#: 1, OK: 0, NX: 1, DR: 0, SF: 0, TR: 1, CN: 0]
Packet capture filter (device eth0): dst host 172.17.0.3 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 172.28.46.137)))
Overall sending rates: 812.35 packets / s, 35743.30 bytes / s.
NSOCK INFO [0.3000s] nsock_iod_new2(): nsock_iod_new (IOD #1)
NSOCK INFO [0.3010s] nsock_connect_tcp(): TCP connection requested to 172.28.46.137:443 (IOD #1) EID 8
NSOCK INFO [0.3020s] nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 8 [172.28.46.137:443]
Service scan sending probe NULL to 172.28.46.137:443 (tcp)
NSOCK INFO [0.3020s] nsock_read(): Read request from IOD #1 [172.28.46.137:443] (timeout: 6000ms) EID 18
NSOCK INFO [6.3080s] nsock_trace_handler_callback(): Callback: READ TIMEOUT for EID 18 [172.28.46.137:443]
Service scan sending probe SSLSessionReq to 172.28.46.137:443 (tcp)
NSOCK INFO [6.3080s] nsock_write(): Write request for 88 bytes to IOD #1 EID 27 [172.28.46.137:443]
NSOCK INFO [6.3080s] nsock_read(): Read request from IOD #1 [172.28.46.137:443] (timeout: 5000ms) EID 34
NSOCK INFO [6.3080s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 27 [172.28.46.137:443]
NSOCK INFO [6.3100s] nsock_trace_handler_callback(): Callback: READ ERROR [Connection reset by peer (104)] for EID 34 [172.28.46.137:443]
NSOCK INFO [6.3100s] nsock_iod_delete(): nsock_iod_delete (IOD #1)
NSOCK INFO [6.3100s] nsock_iod_new2(): nsock_iod_new (IOD #2)
NSOCK INFO [6.3100s] nsock_connect_tcp(): TCP connection requested to 172.28.46.137:443 (IOD #2) EID 40
NSOCK INFO [6.3100s] nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 40 [172.28.46.137:443]
Service scan sending probe TLSSessionReq to 172.28.46.137:443 (tcp)
NSOCK INFO [6.3100s] nsock_write(): Write request for 110 bytes to IOD #2 EID 51 [172.28.46.137:443]
NSOCK INFO [6.3100s] nsock_read(): Read request from IOD #2 [172.28.46.137:443] (timeout: 5000ms) EID 58
NSOCK INFO [6.3100s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 51 [172.28.46.137:443]
NSOCK INFO [6.3110s] nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 58 [172.28.46.137:443] (7 bytes): ......(
Service scan hard match (Probe TLSSessionReq matched with TLSSessionReq line 12854): 172.28.46.137:443 is ssl
NSOCK INFO [6.3110s] nsock_iod_delete(): nsock_iod_delete (IOD #2)
NSOCK INFO [6.3110s] nsock_iod_new2(): nsock_iod_new (IOD #3)
NSOCK INFO [6.3110s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #3) EID 65
NSOCK INFO [6.3220s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 65 [172.28.46.137:443]
Service scan sending probe NULL to 172.28.46.137:443 (tcp)
NSOCK INFO [6.3220s] nsock_read(): Read request from IOD #3 [172.28.46.137:443] (timeout: 6000ms) EID 74
NSOCK INFO [12.3280s] nsock_trace_handler_callback(): Callback: READ TIMEOUT for EID 74 [172.28.46.137:443]
Service scan sending probe GetRequest to 172.28.46.137:443 (tcp)
NSOCK INFO [12.3280s] nsock_write(): Write request for 18 bytes to IOD #3 EID 83 [172.28.46.137:443]
NSOCK INFO [12.3280s] nsock_read(): Read request from IOD #3 [172.28.46.137:443] (timeout: 5000ms) EID 90
NSOCK INFO [12.3280s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 83 [172.28.46.137:443]
NSOCK INFO [12.3300s] nsock_trace_handler_callback(): Callback: READ EOF for EID 90 [172.28.46.137:443]
NSOCK INFO [12.3300s] nsock_iod_delete(): nsock_iod_delete (IOD #3)
NSOCK INFO [12.3300s] nsock_iod_new2(): nsock_iod_new (IOD #4)
NSOCK INFO [12.3300s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #4) EID 97
NSOCK INFO [12.3320s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 97 [172.28.46.137:443]
Service scan sending probe HTTPOptions to 172.28.46.137:443 (tcp)
NSOCK INFO [12.3320s] nsock_write(): Write request for 22 bytes to IOD #4 EID 107 [172.28.46.137:443]
NSOCK INFO [12.3320s] nsock_read(): Read request from IOD #4 [172.28.46.137:443] (timeout: 5000ms) EID 114
NSOCK INFO [12.3320s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 107 [172.28.46.137:443]
NSOCK INFO [12.3730s] nsock_trace_handler_callback(): Callback: READ EOF for EID 114 [172.28.46.137:443]
NSOCK INFO [12.3730s] nsock_iod_delete(): nsock_iod_delete (IOD #4)
NSOCK INFO [12.3730s] nsock_iod_new2(): nsock_iod_new (IOD #5)
NSOCK INFO [12.3730s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #5) EID 121
NSOCK INFO [12.3750s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 121 [172.28.46.137:443]
Service scan sending probe FourOhFourRequest to 172.28.46.137:443 (tcp)
NSOCK INFO [12.3750s] nsock_write(): Write request for 53 bytes to IOD #5 EID 131 [172.28.46.137:443]
NSOCK INFO [12.3750s] nsock_read(): Read request from IOD #5 [172.28.46.137:443] (timeout: 5000ms) EID 138
NSOCK INFO [12.3750s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 131 [172.28.46.137:443]
NSOCK INFO [12.4160s] nsock_trace_handler_callback(): Callback: READ EOF for EID 138 [172.28.46.137:443]
NSOCK INFO [12.4160s] nsock_iod_delete(): nsock_iod_delete (IOD #5)
NSOCK INFO [12.4160s] nsock_iod_new2(): nsock_iod_new (IOD #6)
NSOCK INFO [12.4160s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #6) EID 145
NSOCK INFO [12.4180s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 145 [172.28.46.137:443]
Service scan sending probe vmware-esx to 172.28.46.137:443 (tcp)
NSOCK INFO [12.4180s] nsock_write(): Write request for 441 bytes to IOD #6 EID 155 [172.28.46.137:443]
NSOCK INFO [12.4180s] nsock_read(): Read request from IOD #6 [172.28.46.137:443] (timeout: 5000ms) EID 162
NSOCK INFO [12.4180s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 155 [172.28.46.137:443]
NSOCK INFO [12.4590s] nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 162 [172.28.46.137:443] [EOF](530 bytes)
NSOCK INFO [12.4600s] nsock_read(): Read request from IOD #6 [172.28.46.137:443] (timeout: 4959ms) EID 170
NSOCK INFO [12.4600s] nsock_trace_handler_callback(): Callback: READ EOF for EID 170 [172.28.46.137:443]
NSOCK INFO [12.4600s] nsock_iod_delete(): nsock_iod_delete (IOD #6)
NSOCK INFO [12.4600s] nsock_iod_new2(): nsock_iod_new (IOD #7)
NSOCK INFO [12.4600s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #7) EID 177
NSOCK INFO [12.4620s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 177 [172.28.46.137:443]
Service scan sending probe tor-versions to 172.28.46.137:443 (tcp)
NSOCK INFO [12.4620s] nsock_write(): Write request for 13 bytes to IOD #7 EID 187 [172.28.46.137:443]
NSOCK INFO [12.4620s] nsock_read(): Read request from IOD #7 [172.28.46.137:443] (timeout: 5000ms) EID 194
NSOCK INFO [12.4620s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 187 [172.28.46.137:443]
NSOCK INFO [12.5030s] nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 194 [172.28.46.137:443] [EOF](530 bytes)
NSOCK INFO [12.5040s] nsock_read(): Read request from IOD #7 [172.28.46.137:443] (timeout: 4958ms) EID 202
NSOCK INFO [12.5040s] nsock_trace_handler_callback(): Callback: READ EOF for EID 202 [172.28.46.137:443]
NSOCK INFO [12.5040s] nsock_iod_delete(): nsock_iod_delete (IOD #7)
NSOCK INFO [12.5040s] nsock_iod_new2(): nsock_iod_new (IOD #8)
NSOCK INFO [12.5050s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #8) EID 209
NSOCK INFO [12.5070s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 209 [172.28.46.137:443]
Service scan sending probe GenericLines to 172.28.46.137:443 (tcp)
NSOCK INFO [12.5070s] nsock_write(): Write request for 4 bytes to IOD #8 EID 219 [172.28.46.137:443]
NSOCK INFO [12.5070s] nsock_read(): Read request from IOD #8 [172.28.46.137:443] (timeout: 5000ms) EID 226
NSOCK INFO [12.5080s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 219 [172.28.46.137:443]
NSOCK INFO [17.5130s] nsock_trace_handler_callback(): Callback: READ TIMEOUT for EID 226 [172.28.46.137:443]
NSOCK INFO [17.5130s] nsock_iod_delete(): nsock_iod_delete (IOD #8)
NSOCK INFO [17.5130s] nsock_iod_new2(): nsock_iod_new (IOD #9)
NSOCK INFO [17.5130s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #9) EID 233
NSOCK INFO [17.5150s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 233 [172.28.46.137:443]
Service scan sending probe SSLSessionReq to 172.28.46.137:443 (tcp)
NSOCK INFO [17.5160s] nsock_write(): Write request for 88 bytes to IOD #9 EID 243 [172.28.46.137:443]
NSOCK INFO [17.5160s] nsock_read(): Read request from IOD #9 [172.28.46.137:443] (timeout: 5000ms) EID 250
NSOCK INFO [17.5160s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 243 [172.28.46.137:443]
NSOCK INFO [17.5570s] nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 250 [172.28.46.137:443] [EOF](530 bytes)
NSOCK INFO [17.5660s] nsock_read(): Read request from IOD #9 [172.28.46.137:443] (timeout: 4949ms) EID 258
NSOCK INFO [17.5670s] nsock_trace_handler_callback(): Callback: READ EOF for EID 258 [172.28.46.137:443]
NSOCK INFO [17.5670s] nsock_iod_delete(): nsock_iod_delete (IOD #9)
NSOCK INFO [17.5670s] nsock_iod_new2(): nsock_iod_new (IOD #10)
NSOCK INFO [17.5680s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #10) EID 265
NSOCK INFO [17.5700s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 265 [172.28.46.137:443]
Service scan sending probe TLSSessionReq to 172.28.46.137:443 (tcp)
NSOCK INFO [17.5700s] nsock_write(): Write request for 110 bytes to IOD #10 EID 275 [172.28.46.137:443]
NSOCK INFO [17.5700s] nsock_read(): Read request from IOD #10 [172.28.46.137:443] (timeout: 5000ms) EID 282
NSOCK INFO [17.5700s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 275 [172.28.46.137:443]
NSOCK INFO [17.6110s] nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 282 [172.28.46.137:443] [EOF](530 bytes)
NSOCK INFO [17.6200s] nsock_read(): Read request from IOD #10 [172.28.46.137:443] (timeout: 4950ms) EID 290
NSOCK INFO [17.6210s] nsock_trace_handler_callback(): Callback: READ EOF for EID 290 [172.28.46.137:443]
NSOCK INFO [17.6210s] nsock_iod_delete(): nsock_iod_delete (IOD #10)
NSE: Script scanning 172.28.46.137.
NSE: Starting runlevel 1 (of 2) scan.
NSE: Starting fingerprint-strings against 172.28.46.137:443.
NSE: [fingerprint-strings 172.28.46.137:443] SSLSessionReq:>>>HTTP/1.1 400 Bad Request
    Date: Thu, 23 Mar 2017 09:44:31 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 166
    Connection: close
    Cache-Control: no-store
    Pragma: no-cache
    Content-Security-Policy: default-src 'self'
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000; includeSubdomains;
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    <<<
NSE: [fingerprint-strings 172.28.46.137:443] TLSSessionReq:>>>HTTP/1.1 400 Bad Request
    Date: Thu, 23 Mar 2017 09:44:31 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 166
    Connection: close
    Cache-Control: no-store
    Pragma: no-cache
    Content-Security-Policy: default-src 'self'
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000; includeSubdomains;
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    <<<
NSE: [fingerprint-strings 172.28.46.137:443] tor-versions:>>>HTTP/1.1 400 Bad Request
    Date: Thu, 23 Mar 2017 09:44:26 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 166
    Connection: close
    Cache-Control: no-store
    Pragma: no-cache
    Content-Security-Policy: default-src 'self'
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000; includeSubdomains;
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    <<<
NSE: [fingerprint-strings 172.28.46.137:443] vmware-esx:>>>HTTP/1.1 400 Bad Request
    Date: Thu, 23 Mar 2017 09:44:26 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 166
    Connection: close
    Cache-Control: no-store
    Pragma: no-cache
    Content-Security-Policy: default-src 'self'
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000; includeSubdomains;
    <html>
    <head><title>400 Bad Request</title></head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
    <<<
NSE: Finished fingerprint-strings against 172.28.46.137:443.
NSE: Starting runlevel 2 (of 2) scan.
Nmap scan report for 172.28.46.137
Host is up (0.00068s latency).
Scanned at 2017-03-23 16:44:27 UTC for 17s
PORT    STATE SERVICE    VERSION
443/tcp open  ssl/https?
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port443-TCP:V=7.40%T=SSL%I=2%D=3/23%Time=58D3FB77%P=x86_64-unknown-linu
SF:x-gnu%r(vmware-esx,212,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nDate:\x20
SF:Thu,\x2023\x20Mar\x202017\x2009:44:26\x20GMT\r\nContent-Type:\x20text/h
SF:tml;\x20charset=utf-8\r\nContent-Length:\x20166\r\nConnection:\x20close
SF:\r\nCache-Control:\x20no-store\r\nPragma:\x20no-cache\r\nContent-Securi
SF:ty-Policy:\x20default-src\x20'self'\r\nX-Content-Type-Options:\x20nosni
SF:ff\r\nX-XSS-Protection:\x201;\x20mode=block\r\nStrict-Transport-Securit
SF:y:\x20max-age=31536000;\x20includeSubdomains;\r\n\r\n<html>\r\n<head><t
SF:itle>400\x20Bad\x20Request</title></head>\r\n<body\x20bgcolor=\"white\"
SF:>\r\n<center><h1>400\x20Bad\x20Request</h1></center>\r\n<hr><center>ngi
SF:nx</center>\r\n</body>\r\n</html>\r\n")%r(tor-versions,212,"HTTP/1\.1\x
SF:20400\x20Bad\x20Request\r\nDate:\x20Thu,\x2023\x20Mar\x202017\x2009:44:
SF:26\x20GMT\r\nContent-Type:\x20text/html;\x20charset=utf-8\r\nContent-Le
SF:ngth:\x20166\r\nConnection:\x20close\r\nCache-Control:\x20no-store\r\nP
SF:ragma:\x20no-cache\r\nContent-Security-Policy:\x20default-src\x20'self'
SF:\r\nX-Content-Type-Options:\x20nosniff\r\nX-XSS-Protection:\x201;\x20mo
SF:de=block\r\nStrict-Transport-Security:\x20max-age=31536000;\x20includeS
SF:ubdomains;\r\n\r\n<html>\r\n<head><title>400\x20Bad\x20Request</title><
SF:/head>\r\n<body\x20bgcolor=\"white\">\r\n<center><h1>400\x20Bad\x20Requ
SF:est</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r
SF:\n")%r(SSLSessionReq,212,"HTTP/1\.1\x20400\x20Bad\x20Request\r\nDate:\x
SF:20Thu,\x2023\x20Mar\x202017\x2009:44:31\x20GMT\r\nContent-Type:\x20text
SF:/html;\x20charset=utf-8\r\nContent-Length:\x20166\r\nConnection:\x20clo
SF:se\r\nCache-Control:\x20no-store\r\nPragma:\x20no-cache\r\nContent-Secu
SF:rity-Policy:\x20default-src\x20'self'\r\nX-Content-Type-Options:\x20nos
SF:niff\r\nX-XSS-Protection:\x201;\x20mode=block\r\nStrict-Transport-Secur
SF:ity:\x20max-age=31536000;\x20includeSubdomains;\r\n\r\n<html>\r\n<head>
SF:<title>400\x20Bad\x20Request</title></head>\r\n<body\x20bgcolor=\"white
SF:\">\r\n<center><h1>400\x20Bad\x20Request</h1></center>\r\n<hr><center>n
SF:ginx</center>\r\n</body>\r\n</html>\r\n")%r(TLSSessionReq,212,"HTTP/1\.
SF:1\x20400\x20Bad\x20Request\r\nDate:\x20Thu,\x2023\x20Mar\x202017\x2009:
SF:44:31\x20GMT\r\nContent-Type:\x20text/html;\x20charset=utf-8\r\nContent
SF:-Length:\x20166\r\nConnection:\x20close\r\nCache-Control:\x20no-store\r
SF:\nPragma:\x20no-cache\r\nContent-Security-Policy:\x20default-src\x20'se
SF:lf'\r\nX-Content-Type-Options:\x20nosniff\r\nX-XSS-Protection:\x201;\x2
SF:0mode=block\r\nStrict-Transport-Security:\x20max-age=31536000;\x20inclu
SF:deSubdomains;\r\n\r\n<html>\r\n<head><title>400\x20Bad\x20Request</titl
SF:e></head>\r\n<body\x20bgcolor=\"white\">\r\n<center><h1>400\x20Bad\x20R
SF:equest</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html
SF:>\r\n");
Final times for host: srtt: 680 rttvar: 3761  to: 100000

Read from .: nmap-payloads nmap-service-probes nmap-services.
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 17.66 seconds
`

Thanks,

**Comment by kiran-dp** [comment]
For nginx config, we have 'listen 443 ssl; ssl on;'.

**Comment by dmiller-nmap** [comment]
Ok, so it looks like we detect the SSL tunnel with the `TLSSessionReq` probe:

    Service scan hard match (Probe TLSSessionReq matched with TLSSessionReq line 12854): 172.28.46.137:443 is ssl

And then we start the service probing process over from within the SSL tunnel:

```
NSOCK INFO [6.3110s] nsock_connect_ssl(): SSL connection requested to 172.28.46.137:443/tcp (IOD #3) EID 65
NSOCK INFO [6.3220s] nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 65 [172.28.46.137:443]
Service scan sending probe NULL to 172.28.46.137:443 (tcp)
NSOCK INFO [6.3220s] nsock_read(): Read request from IOD #3 [172.28.46.137:443] (timeout: 6000ms) EID 74
NSOCK INFO [12.3280s] nsock_trace_handler_callback(): Callback: READ TIMEOUT for EID 74 [172.28.46.137:443]
Service scan sending probe GetRequest to 172.28.46.137:443 (tcp)
NSOCK INFO [12.3280s] nsock_write(): Write request for 18 bytes to IOD #3 EID 83 [172.28.46.137:443]
NSOCK INFO [12.3280s] nsock_read(): Read request from IOD #3 [172.28.46.137:443] (timeout: 5000ms) EID 90
NSOCK INFO [12.3280s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 83 [172.28.46.137:443]
NSOCK INFO [12.3300s] nsock_trace_handler_callback(): Callback: READ EOF for EID 90 [172.28.46.137:443]
```

Here you can see that we try the `NULL` probe (just connect and see if we get a banner), then try to send the `GetRequest` probe on the same socket after the 6 seconds are up. That request gets an immediate disconnect (`READ EOF`). So do all the other typical HTTP probes like `HTTPOptions`, `FourOhFourRequest`, etc.

Does this service work in a browser? Is there a WAF or IPS in the way that is dropping these connections? Nmap is acting as expected; the service seems strange, though.

Aside: we can add some match lines for the 400 error to some of the more unusual probes to catch this service, but that's not the real cause of the problem here.

**Comment by patche81** [comment]
We are experiencing the same issue, tested with nmap 7.40 and nmap current build.

The website we are testing have no WAF but is published through a reverse-proxy. There HSTS header is also configured (not sure if this might be related)
