### ISSUE TITLE
[Npcap] Service cannot start

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#804]
@hsluoyz 
Hello,

I recently updated my windows version 
`Microsoft Windows [version 10.0.15063]`

I've also updated to npcap 0.83

The Npcap service is not started, and the entire npcap installation does not work...
```
C:\Users\gpotter>sc query npcap

SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 2  (0x2)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

```
C:\WINDOWS\system32>net start npcap
System error 2 has occured.

The system cannot find the file specified.
```

My problem may have something to do with https://github.com/nmap/nmap/issues/792 as i can see:

> 在注册表里确实出现了npf这个键，但是服务名还是找不到：
> 
> C:\Users\Administrator\Downloads>net start npcap
> The requested service has already been started.

But please speak english on github....

What I tried:
- uninstall npcap/reinstall npcap, did not work
- reboot my computer several times: did not work
- uninstall npcap/reinstall npcap with Winpcap compatible mode: **it worked**
- Uninstall npcap, install winpcap: **worked**

**Comment by hsluoyz** [comment]
I don't have a Win 10.0.15063. So I can't test it by myself for a while. Can you upgrade Npcap to 0.84 to see if it is fixed?

BTW, I don't think this is related to https://github.com/nmap/nmap/issues/792

**Comment by gpotter2** [comment]
I've updated both windows and Npcpa... Seems to be working
