### ISSUE TITLE
NTLM Information disclosure scripts

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#81]
[These scripts](https://github.com/GDSSecurity/Nmap-Scripts/tree/master/NTLM-Info-Disclosure) are safe and effective, and have been [submitted on the dev list for a long time](http://seclists.org/nmap-dev/2015/q1/18). We just need to review and get them merged in.

**Comment by s0h3ck** [comment]
What do you mean by review those scripts? Is it to verify if the script do what the description says and to check if there is no bug? Thanks for letting me know. (If you give me the signal. I'm ready to analyse them carefully =))

**Comment by dmiller-nmap** [comment]
Committed in:

* 70798c246888a3bea883d2bb419eb26ee042989c
* 1f74fc25500e84d282431ac009382be8551cf66a
* 82be9b48ee5c682008d5cf34ade4d07b4148ec79
* 5a1e018803c17b4ddee7ee2df07b5251f0722de0
* 1accb103d13e16dcd48cef12d93041756b1bcd29
* cdb5e5b9d8eba0346b6cb6f4478228bb032b6879
