### ISSUE TITLE
Port in httpspider should be return as table

### ISSUE THREAD

**Issue by Wolodija** [nmap/nmap#817]
`URL.parse` returns port as `number`, not a `table` type:

https://github.com/nmap/nmap/blob/master/nselib/httpspider.lua#L426

```lua
parse = function(self)
    self.proto, self.host, self.port, self.file = self.raw:match("^(http[s]?)://([^:/]*)[:]?(%d*)")
    if ( self.proto and self.host ) then
      self.file = self.raw:match("^http[s]?://[^:/]*[:]?%d*(/[^#]*)") or '/'
      self.port = tonumber(self.port)
      if ( not(self.port) ) then
        if ( self.proto:match("https") ) then
          self.port = 443
        elseif ( self.proto:match("http")) then
          self.port = 80
        end
      end
```

I propose to change it to:

```lua
    self.proto, self.host, self._port, self.file = self.raw:match("^(http[s]?)://([^:/]*)[:]?(%d*)")
    if ( self.proto and self.host ) then
      self.file = self.raw:match("^http[s]?://[^:/]*[:]?%d*(/[^#]*)") or '/'
      self.port = {}
      self.port.number = tonumber(self._port)
      if ( not(self.port.number) ) then
        if ( self.proto:match("https") ) then
          self.port.number = 443
        elseif ( self.proto:match("http")) then
          self.port.number = 80
        end
      end
```
or something similar.

---

This changes requires also check in which way getPort is used by other functions, eg.:
https://github.com/nmap/nmap/blob/master/nselib/httpspider.lua#L255
```lua
return ("%s://%s:%d%s%s"):format(base_url:getProto(), base_url:getHost(), base_href or base_url:getPort(), base_url:getDir(), rel_url)
```
requires port number not table type.

---

The reason of changes is:

https://github.com/nmap/nmap/blob/master/nselib/httpspider.lua#L830

```lua
response = http.get(url:getHost(), url:getPort(), url:getFile(), { timeout = self.options.timeout, redirect_ok = self.options.redirect_ok, no_cache = self.options.no_cache } )
```

`http.get` expect port as table type.

---

Are these changes reasonable? If yes, I will prepare patch and pull request for this issue.

**Comment by nnposter** [comment]
Could you please check if accommodating numerical ports in the recently updated `get_host_field()` in `http.lua` by #766 is sufficient to remediate your issue?
```lua
local function get_host_field(host, port)
  if not host then return nil end
  if type(port) == "number" then
    port = {number=port, protocol="tcp", state="open", version={}}
  end
  local scheme = shortport.ssl(host, port) and "https" or "http"
  if port.number == get_default_port(scheme) then
    return stdnse.get_hostname(host)
  else
    return stdnse.get_hostname(host) .. ":" .. port.number
  end
end
```
Note the newly added `if type(port) == "number" then ...`

**Comment by nnposter** [comment]
I got too much ahead of myself here. The update above depends on another patch that has not yet been committed. Just grab the latest [http.lua](https://github.com/nmap/nmap/blob/master/nselib/http.lua#L162) from the trunk.

**Comment by Wolodija** [comment]
@nnposter, It works fine except one thing.
Port can be also a `"string"`:

Could you change:
```lua
if type(port) == "number"
```
to:
```lua
if type(port) == "number" or type(port) == "string" then
```
?

Additionally I think it is more like workaround than proper solution (in case of httpspider).

**Comment by rewanth1997** [comment]
@Wolodija  Port will be taken as a number only not as a string.

**Comment by Wolodija** [comment]
@rewanth1997, Httpspider pass port as string. It takes it from parser:
```lua
self.proto, self.host, self.port, self.file = self.raw:match("^(http[s]?)://([^:/]*)[:]?(%d*)")
```

**Comment by rewanth1997** [comment]
@Wolodija You are right but in line number 430 it is being converted into a number in the same function.

**Comment by Wolodija** [comment]
@rewanth1997, Yeah, You are right. I found where is the problem:
https://github.com/nmap/nmap/blob/master/nselib/url.lua#L186

```lua
  authority = string.gsub(authority, ":([0-9]*)$",
                function(p) if p ~= "" then parsed.port = p end; return "" end)
```
`parsed.port` is `string` so I propose to change it to:

```lua
  authority = string.gsub(authority, ":([0-9]*)$",
                function(p) if p ~= "" then parsed.port = tostring(p) end; return "" end)
```

**Comment by nnposter** [comment]
The proposal to change the port return type from `url.parse()` indeed makes sense but there might be code that depends on the port being of type `string`. Here is one [example](https://github.com/nmap/nmap/blob/master/nselib/data/http-default-accounts-fingerprints.lua#L177).

**Comment by Wolodija** [comment]
@nnposter , So, the only reasonable solution is:
```lua
if type(port) == "number" or type(port) == "string" then
```
?

+ complex refactor of code

**Comment by nnposter** [comment]
Could you please test a patch at https://gist.github.com/nnposter/a4d2640cd475cddc68d970329a88dc60 and report any issues?

**Comment by Wolodija** [comment]
Works fine for me

**Comment by rewanth1997** [comment]
@nnposter Looks good to me.

**Comment by nnposter** [comment]
I have [announced](http://seclists.org/nmap-dev/2017/q2/18) the return type patch on the mailing list and documented it as #833. I will let it sit for a few weeks and then commit it unless concerns are raised. Let's keep this issue open until then.
