### ISSUE TITLE
Buildng Installer - Cannot find deploy.bay

### ISSUE THREAD

**Issue by datkins47** [nmap/nmap#823]
Hi,

Trying to test some ideas out using the great npcap but cannot locate the files referenced for deployment, guide says to use installer\Deploy.bat after building, building is fine but the deploy.bat and the installer folder are not present in files pulled from github.

Did I miss something?

David

**Comment by Varunram** [comment]
You must generate an installer using NDIS 2.51 with the advanced logging special build and SysRestore plug-in (as specified in the guide) and then, you must sign the same. On the other hand, if you want the installer right away, feel free to download it from <a href ="https://nmap.org/npcap/"> here </a>.

**Comment by datkins47** [comment]
Hi,

 

I would try that but my clone of the git hub does not have an “installer” sub directory so the build.bat and deploy.bat mentioned in the GitHub page are not present, 

 

David

**Comment by Varunram** [comment]
Od, I forgot to mention that, the installer subdirectory has now been moved to a private repo with <a href ="https://github.com/nmap/npcap/commit/a889ccb4747f2fa985b900b2e6c67931712313fb">this</a>  commit. Once its made public again, you could build npcap from scratch.

**Comment by datkins47** [comment]
So if I save the version of the files before that commit then I should be able to proceed? Will give it a go.

 

David

**Comment by dmiller-nmap** [comment]
Thanks for letting us know. We have restored `Build.bat`, `DiagReport.ps1`, and `DiagReport.bat`, but the deployment scripts and installer code will remain private. We are in the process of updating the documentation to reflect this. You are welcome to deploy Npcap in any way that is permitted by [its license](http://npcap.org/#License).
