### ISSUE TITLE
Remove -allow-undefined flag in ltmain.sh

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#834]
At line 4419 of ltmain.sh, there's a comment for removing the flag ```-allow-undefined```. There seem to be no other instances of the same in the file. An ideal fix would be 
```diff 
--- a/ltmain.sh
+++ b/ltmain.sh
@@ -4415,11 +4415,6 @@ func_mode_link ()
        continue
        ;;

-      -allow-undefined)
-       # FIXME: remove this flag sometime in the future.
-       func_fatal_error "\`-allow-undefined' must not be used because it is the default"
-       ;;
-
       -avoid-version)
        avoid_version=yes
        continue
```

What are your thoughts on this?

**Comment by dmiller-nmap** [comment]
This is a generated file that is part of GNU libtool. We will not be changing it except to upgrade to a newer libtool.

**Comment by Varunram** [comment]
@dmiller-nmap Thanks! Forgot to close it after your reply over at dev
