### ISSUE TITLE
Bug: Install omits expected registry settings (Win-7)

### ISSUE THREAD

**Issue by netpog** [nmap/nmap#837]
**PROBLEM:** The DiagReport.bat script looks for registry entries in 'HKLM:\SOFTWARE\WOW6432Node\WinPcap', which does not exist, and is not created by the Windows installer.

**NOTE:** Searching the two install logs (install.log & NPFInstall.log), there is no instance of "WOW6432"

**REPRO:**

1) Installed npcap-0.84.exe on Win7 Pro x64.  
2) Ran DiagReport.bat
3) The resulting DiagReport-etc.txt, included this section (copied here, in entirety):
*************************************************
WinPcap Info:
*************************************************
HKLM:\SOFTWARE\WOW6432Node\WinPcap:
Get-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\WOW6432Node\WinPcap' because it does not exist.
At C:\Program Files\Npcap\DiagReport.ps1:176 char:6
+     (Get-ItemProperty HKLM:\SOFTWARE\WOW6432Node\WinPcap | out-string -stream |  ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\WOW6432Node\WinPcap:String) [Get-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
**PERHAPS RELATED?**
There was also this error-report in the DiagReport log:
*************************************************
Network Adapter(s) Info:
*************************************************
Get-NetAdapter : The term 'Get-NetAdapter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\Npcap\DiagReport.ps1:111 char:1
+ Get-NetAdapter
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetAdapter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**ENTIRELY TOO MUCH SYSTEM INFO from the DiagReport log:**
(the remainder of this post)
*************************************************
DiagReport for Npcap ( http://npcap.org )
*************************************************
Script Architecture:		64-bit
Script Path:			C:\Program Files\Npcap\DiagReport.ps1
Current Time:			04/10/2017 14:54:36
Npcap install path:		C:\Program Files\Npcap
Npcap Version:			0.84
PowerShell Version:		4.0

*************************************************
OS Info:
*************************************************

Caption                 : Microsoft Windows 7 Professional 
BuildNumber             : 7601
Locale                  : 0409
MUILanguages            : {en-US}
OSArchitecture          : 64-bit
ServicePackMajorVersion : 1
ServicePackMinorVersion : 0
SystemDirectory         : C:\windows\system32
Version                 : 6.1.7601

*************************************************
CPU Info:
*************************************************

Name                      : Intel(R) Core(TM) i3-4340 CPU @ 3.60GHz
Manufacturer              : GenuineIntel
DeviceID                  : CPU0
NumberOfCores             : 2
NumberOfLogicalProcessors : 4
Addresswidth              : 64

**Comment by Varunram** [comment]
@netpog Thanks for the report! Regarding the Get-NetAdapter issue that you mentioned, that is a known bug over at #611. As far as I know, WOW6432Node simply indicates that you're running a 64 bit Machine and it seems to be related to WinPcap. @hsluoyz

**Comment by hsluoyz** [comment]
Please paste your entire DiagReport file as plain text. It is still unclear as the way you describe it

**Comment by netpog** [comment]
Okay, thanks for asking. Here's the entire DiagReport, via the file-attach feature. 

You can see the missing-registry-path problem by searching "cannot find".  
And the Get-NetAdapter issue by searching "not recognized".

I just searched my registry; there is no instance of "winpcap".

[DiagReport-20170411-140754.txt](https://github.com/nmap/nmap/files/914283/DiagReport-20170411-140754.txt)

**Comment by dmiller-nmap** [comment]
This portion of the diagnostic is intended to show us whether you have an older version of WinPcap installed in addition to Npcap, since this could be a source of errors. We could possibly hide the key-not-found error to make this clearer, but the idea would be the same.

**Comment by hsluoyz** [comment]
Won't fix.
