### ISSUE TITLE
Improve error message when `--resume` is used with other options.

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#84]
The `--resume` option is handled in `main.cc` and only when `argc == 3`. This means that if it is used in conjunction with any other option, the user gets:

```
./nmap: unrecognized option '--resume'
Nmap 6.47SVN ( http://nmap.org )
Usage: nmap [Scan Type(s)] [Options] {target specification}
<snip entire 115-line usage page>
```

We should add a getopt option for `--resume` in nmap.cc which results in a call to `fatal()` with a more user-friendly error message like, "It is an error to use --resume with any other options."

**Comment by cldrn** [comment]
I think I found other issues with the --resume option while testing this. I searched through the list's archives and didn't really see anything there so I'll start looking into this problem and post an update soon.

**Comment by dmiller-nmap** [comment]
The initial fix has a bug which causes a segfault when running nmap, due to uninitialized use of `resume` and `myargc` variables. Reverted this.

Suggestions for a cleaner implementation are here: http://seclists.org/nmap-dev/2015/q2/42
