### ISSUE TITLE
where to get the old version NPCAP，such as 0.83,0.82...

### ISSUE THREAD

**Issue by w1nst0nwU** [nmap/nmap#842]
i Could not capture 802.11 Data frame (which Frame Control Type=0x10) in 0.86，i think i could capture it in old verison NPCAP which i used to，i wonder to know if it is my WLAN-adapter-driver's mistake.

so i want to get the old version NPCAP  windows installer package,but i could not find the old version ,

Please help me .Thank you very much

**Comment by dmiller-nmap** [comment]
You can download older versions from https://nmap.org/npcap/dist/ . Do let us know what you find out. If there is a regression, we would very much like to fix it.

**Comment by w1nst0nwU** [comment]
thank you very much @dmiller-nmap 

I have tried the 0.78-r2 and 0.86,it is all the same in capturing 802.11 Data frame (which Frame Control Type=0x10) 

i think it is my personal mistake which i had not captured the 802.11 Data Frame Yesterday.

thanks again for your help.
