### ISSUE TITLE
Make `configure` detect Python 2 and not Python 3

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#86]
Right now, our build system will "build" and install Zenmap even if there's not a Python 2 interpreter. Since Zenmap is not written for Python 3, stuff breaks. It shouldn't be tough to put a check into the configure script for this.

A better solution would be to fully support Python 3, but that would be a larger task.

**Comment by ank337** [comment]
I'd like to work on this project for GSoC . I have already submitted my proposal for this. Can you please guide me  through on how to proceed with it .

**Comment by dmiller-nmap** [comment]
@ank337 We would have to modify `configure.ac` with appropriate macros to detect this. Automake provides `AM_PATH_PYTHON`, but that will always prefer higher versions (including version 3). A discussion of this problem can be found [on the GNU bug report mailing list](http://debbugs.gnu.org/db/13/13170.html) with a potential workaround involving `AC_PROG_PYTHON` from [Pyconfigure](https://www.gnu.org/software/pyconfigure/). Essentially, we need to handle these cases:

1. No python interpreter present: Do not build Zenmap.
2. Python `2.6 <= version < 3` available: Build Zenmap.
3. Python 2 and 3 available: Build Zenmap with Python 2
3. Only Python 3 available: Do not build Zenmap

**Comment by G10h4ck** [comment]
May you test this https://github.com/G10h4ck/nmap-gsoc2015/commit/9f22c32f1cfb65bd63e8d2f2ad163e2967d5ddea and see it work for you too ?

**Comment by G10h4ck** [comment]
Fix commited in r34541 = 702c5bf7cb81847baecd50e60510f7ac0093f9ea
