### ISSUE TITLE
snmp-ios-config --script-args not working

### ISSUE THREAD

**Issue by rikosintie** [nmap/nmap#861]
Hello, 
I sent an email to dev@nmap.org before I found this site.

I have a question about the snmp-ios-config script. I have been using it for a couple years with great success but I ran it today and it failed to pull the configuration.

I ran wireshark and noticed that even though I defined:
--script-args snmpcommunity=private
it passed public as the string.

If I set the switch up with a RW community of public it works.

I started up a virtual machine that had Nmap 6.47 installed and the script worked perfectly.

I have used Ubuntu 14.04 and Windows 7 with the same result.

Is there something I have to do in nmap 7.40?

Thanks for any suggestions!

Here is my command line. 

mhubbard@1S1K-SYS76:~/Dropbox/nmap-scripts/scanreport-master$ sudo nmap -sU -n -ddd -p 161 --script snmp-ios-config --script-args snmpcommunity=private 192.168.10.51
[sudo] password for mhubbard: 

Starting Nmap 7.40 ( https://nmap.org ) at 2017-04-20 23:39 PDT
Fetchfile found /usr/local/bin/../share/nmap/nmap-services
Fetchfile found /usr/local/bin/../share/nmap/nmap.xsl
The max # of sockets we are using is: 0
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
Fetchfile found /usr/local/bin/../share/nmap/nse_main.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/lpeg-utility.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/stdnse.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/strict.lua
Fetchfile found /usr/local/bin/../share/nmap/scripts/script.db
NSE: Arguments from CLI: snmpcommunity=private
NSE: Arguments parsed: snmpcommunity=private
NSE: {
	["snmpcommunity"] = "private",
}
Fetchfile found /usr/local/bin/../share/nmap/scripts/snmp-ios-config.nse
NSE: Script snmp-ios-config.nse was selected by name.
Fetchfile found /usr/local/bin/../share/nmap/nselib/shortport.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/snmp.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/asn1.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/bin.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/bit.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/creds.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/ipOps.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/unittest.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/nsedebug.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/listop.lua
Fetchfile found /usr/local/bin/../share/nmap/nselib/tftp.lua
NSE: Loaded 1 scripts for scanning.
NSE: Loaded '/usr/local/bin/../share/nmap/scripts/snmp-ios-config.nse'.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 23:39
Completed NSE at 23:39, 0.00s elapsed
Fetchfile found /usr/local/bin/../share/nmap/nmap-payloads
Initiating ARP Ping Scan at 23:39
Scanning 192.168.10.51 [1 port]
Packet capture filter (device wlan1): arp and arp[18:4] = 0x3052CB20 and arp[22:2] = 0xBDC1
SENT (0.2194s) ARP who-has 192.168.10.51 tell 192.168.10.152
**TIMING STATS** (0.2194s): IP, probes active/freshportsleft/retry_stack/outstanding/retranwait/onbench, cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 1/*/*/*/*/* 10.00/75/* 200000/-1/-1
Current sending rates: 36.77 packets / s, 1544.40 bytes / s.
Overall sending rates: 36.77 packets / s, 1544.40 bytes / s.
RCVD (0.2227s) ARP reply 192.168.10.51 is-at 64:00:F1:01:6F:C1
Found 192.168.10.51 in incomplete hosts list.
ultrascan_host_probe_update called for machine 192.168.10.51 state UNKNOWN -> HOST_UP (trynum 0 time: 3335)
Changing ping technique for 192.168.10.51 to ARP
Moving 192.168.10.51 to completed hosts list with 0 outstanding probes.
Changing global ping host to 192.168.10.51.
Completed ARP Ping Scan at 23:39, 0.03s elapsed (1 total hosts)
Overall sending rates: 32.79 packets / s, 1377.09 bytes / s.
pcap stats: 1 packets received by filter, 0 dropped by kernel.
Initiating UDP Scan at 23:39
192.168.10.51 pingprobe type ARP is inappropriate for this scan type; resetting.
Scanning 192.168.10.51 [1 port]
Packet capture filter (device wlan1): dst host 192.168.10.152 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 192.168.10.51)))
SENT (0.2958s) UDP [192.168.10.152:46504 > 192.168.10.51:161 len=68 csum=0x6B27] IP [ver=4 ihl=5 tos=0x00 iplen=88 id=40701 foff=0 ttl=47 proto=17 csum=0x567c]
**TIMING STATS** (0.2959s): IP, probes active/freshportsleft/retry_stack/outstanding/retranwait/onbench, cwnd/ssthresh/delay, timeout/srtt/rttvar/
   Groupstats (1/1 incomplete): 1/*/*/*/*/* 10.00/75/* 1000000/-1/-1
Current sending rates: 26.84 packets / s, 2361.91 bytes / s.
Overall sending rates: 26.84 packets / s, 2361.91 bytes / s.
RCVD (0.3036s) UDP [192.168.10.51:161 > 192.168.10.152:46504 len=110 csum=0xF85C] IP [ver=4 ihl=5 tos=0x00 iplen=130 id=38669 foff=0 ttl=255 proto=17 csum=0x8e41]
Found 192.168.10.51 in incomplete hosts list.
Discovered open port 161/udp on 192.168.10.51
Changing ping technique for 192.168.10.51 to udp to port 161
Moving 192.168.10.51 to completed hosts list with 0 outstanding probes.
Changing global ping host to 192.168.10.51.
Completed UDP Scan at 23:39, 0.04s elapsed (1 total ports)
Overall sending rates: 22.20 packets / s, 1953.60 bytes / s.
pcap stats: 1 packets received by filter, 0 dropped by kernel.
NSE: Script scanning 192.168.10.51.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 23:39
NSE: Starting snmp-ios-config M:11e17d8 against 192.168.10.51:161.
NSOCK INFO [0.1780s] nsock_iod_new2(): nsock_iod_new (IOD #1)
NSOCK INFO [0.3390s] nsock_connect_udp(): UDP connection requested to 192.168.10.51:161 (IOD #1) EID 8
NSOCK INFO [0.3390s] nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 8 [192.168.10.51:161]
NSE: UDP 192.168.10.152:60532 > 192.168.10.51:161 | CONNECT
NSE: UDP 192.168.10.152:60532 > 192.168.10.51:161 | 00000000: 30 30 02 01 00 04 06 70 75 62 6c 69 63 a3 23 02 00     public  # 
00000010: 03 00 b5 7d 02 01 00 02 01 00 30 16 30 14 06 0f    }      0 0   
00000020: 2b 06 01 04 01 09 09 60 01 01 01 01 02 ce 0f 02 +      `        
00000030: 01 01                                             

NSOCK INFO [0.3390s] nsock_write(): Write request for 50 bytes to IOD #1 EID 19 [192.168.10.51:161]
NSOCK INFO [0.3390s] nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 19 [192.168.10.51:161]
NSE: UDP 192.168.10.152:60532 > 192.168.10.51:161 | SEND
NSOCK INFO [0.3390s] nsock_readbytes(): Read request for 1 bytes from IOD #1 [192.168.10.51:161] EID 26
NSOCK INFO [5.3390s] nsock_trace_handler_callback(): Callback: READ TIMEOUT for EID 26 [192.168.10.51:161]
NSE: Finished snmp-ios-config M:11e17d8 against 192.168.10.51:161.
NSE: UDP 192.168.10.152:60532 > 192.168.10.51:161 | CLOSE
NSOCK INFO [5.3390s] nsock_iod_delete(): nsock_iod_delete (IOD #1)
Completed NSE at 23:39, 5.00s elapsed
Nmap scan report for 192.168.10.51
Fetchfile found /usr/local/bin/../share/nmap/nmap-mac-prefixes
MAC prefix 0001C8 is duplicated in /usr/local/bin/../share/nmap/nmap-mac-prefixes; ignoring duplicates.
MAC prefix 080030 is duplicated in /usr/local/bin/../share/nmap/nmap-mac-prefixes; ignoring duplicates.
MAC prefix 080030 is duplicated in /usr/local/bin/../share/nmap/nmap-mac-prefixes; ignoring duplicates.
Host is up, received arp-response (0.0038s latency).
Scanned at 2017-04-20 23:39:26 PDT for 5s
PORT    STATE SERVICE REASON
161/udp open  snmp    udp-response ttl 255
MAC Address: 64:00:F1:01:6F:C1 (Cisco Systems)
Final times for host: srtt: 3844 rttvar: 4899  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 23:39
Completed NSE at 23:39, 0.00s elapsed
Read from /usr/local/bin/../share/nmap: nmap-mac-prefixes nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 5.36 seconds
           Raw packets sent: 2 (116B) | Rcvd: 2 (158B)

**Comment by dmiller-nmap** [comment]
Sorry, we forgot to update a couple places in the documentation after [Nmap 6.46BETA6](https://nmap.org/changelog.html#6.46BETA6). Since that version, the proper way to pass the SNMP community string is via the `creds.snmp` or `creds.161` script arg.

**Comment by rikosintie** [comment]
Thank you!!  I appreciate all you do and the quick response for this is amazing.
