### ISSUE TITLE
openBSD:  'IPPROTO_SCTP' was not declared in this scope

### ISSUE THREAD

**Issue by jungle-boogie** [nmap/nmap#868]
Hi All,

I don't know why but nmap is failing to build on openbsd -current.

```
In file included from scan_engine.cc:139:
scan_engine.h: In member function 'u16 UltraProbe::sport() const':
scan_engine.h:289: error: 'IPPROTO_SCTP' was not declared in this scope
scan_engine.h: In member function 'u16 UltraProbe::dport() const':
scan_engine.h:303: error: 'IPPROTO_SCTP' was not declared in this scope
gmake: *** [Makefile:109: scan_engine.o] Error 1
```
A single config option: `./configure --with-libpcap=included`

[config.txt](https://github.com/nmap/nmap/files/957009/config.txt)

thanks for any pointers!

**Comment by dmiller-nmap** [comment]
Thanks for the report. I had missed that nmap.h included a definition for IPPROTO_SCTP when I removed it from scan_engine.h. I added a conditional include of netutil.h which also defines that constant, so things should work. Please open a new report if you find more errors after r36742

**Comment by jungle-boogie** [comment]
I don't see any new commits on https://github.com/nmap/nmap/commits/master

Does this sync with SVN or something?
