### ISSUE TITLE
NSE script http-vuln-cve2017-5689 error

### ISSUE THREAD

**Issue by 4D4M4N71UM** [nmap/nmap#878]
Nmap version 7.40 

Command used:
nmap -d -p 16992 -v -v -Pn --script http-vuln-cve2017-5689 {IP}

Error:
NSE: http-vuln-cve2017-5689 against {IP}:16992 threw an error!
/usr/bin/../share/nmap/scripts/http-vuln-cve2017-5689.nse:115: attempt to index a nil value (field 'params')
stack traceback:
	/usr/bin/../share/nmap/scripts/http-vuln-cve2017-5689.nse:115: in function </usr/bin/../share/nmap/scripts/http-vuln-cve2017-5689.nse:85>
	(...tail calls...)

**Comment by dmiller-nmap** [comment]
@vinamrabhatia You can close multiple issues/pulls from one commit. I tend to use "Fixes" for issues and "Closes" for pulls, so be66ffd would have been "Fixes #878. Closes #885"
