### ISSUE TITLE
[npcap] Chocolatey

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#879]
@hsluoyz
Hello,

Could you add in chocolatey a way for us to pass the installation arguments ? Like:
`choco install npcap /loopback_support=yes`
Might be as simple as adding the passed parameters to `silentArgs`...

That's currently not the case and quite annoying...

Thanks !

**Comment by hsluoyz** [comment]
Hi. The chocolatey package already supports args. Please use the [--install-arguments parameter](http://stackoverflow.com/questions/37803877/how-do-i-pass-parameters-to-the-installer-in-a-chocolatey-package) to pass the arguments to the installer, for example:

```
choco install npcap --install-arguments='/loopback_support=yes'
```

**Comment by hsluoyz** [comment]
I assume this has been solved.

**Comment by gpotter2** [comment]
Thanks a lot !
