### ISSUE TITLE
Cannot auth against Windows 10 Creators Update (v1703)

### ISSUE THREAD

**Issue by tsimmons** [nmap/nmap#883]
When running any smb script (smb-enum-shares, smb_vuln-ms17-010) that relies on smbauth.lua (using known good credentials) against a Windows 10 Creators Update computer, it errors out with:

    No accounts left to try

I don't really have any good suggestions for fixing it.

**Comment by cldrn** [comment]
Can you try the latest version of the library? I think I solved the issue.

**Comment by tsimmons** [comment]
Where would I get the latest? Looking at https://github.com/nmap/nmap/blob/master/nselib/smbauth.lua it shows the last commit was Oct. 2016.

**Comment by tsimmons** [comment]
Whoops, never mind.  found your version at https://github.com/cldrn/nmap-nse-scripts/blob/master/nselib/smb.lua and, YES, it works!
