### ISSUE TITLE
x11 timeout error

### ISSUE THREAD

**Issue by digininja** [nmap/nmap#887]
Same as the MySQL one, saw it fly past with debug enabled.

```
NSE: x11-access against 192.168.4.77:6002 threw an error!
TIMEOUT
stack traceback:
        [C]: in local 'try'
        /usr/bin/../share/nmap/scripts/x11-access.nse:67: in function </usr/bin/../share/nmap/scripts/x11-access.nse:38>
        (...tail calls...)
```

Command line:

nmap -T4 -n -sC -oA visible_scripts -iL visible_ips -d

Version info:

```
Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-24 16:55 BST
PORTS: Using top 1000 ports found open (TCP:1000, UDP:0, SCTP:0)
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
Read from /usr/bin/../share/nmap: nmap-services.
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.04 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)
```

**Comment by dmiller-nmap** [comment]
This kind of thing:

```
NSE: some-script against X.X.X.X:Y threw an error!
TIMEOUT
stack traceback:
        [C]: in local 'try'
```

...is not usually a bug. This is a side-effect of the "try-catch" NSE construct that is used to cause a script to immediately quit. It'd be nice to not have this output, but it's not a problem with the script.

One exception: if the error is really unexpected given the service and the purpose of the script, then maybe something can be improved. But if instead this is *not* X11, it's not out of the ordinary that the connection would simply time out while waiting for a response.

**Comment by digininja** [comment]
Fair enough, maybe a copy change to indicate that it is an expected error?
