### ISSUE TITLE
smb.file_read keeps returning empty data

### ISSUE THREAD

**Issue by IgLiv** [nmap/nmap#895]
I'm trying to upload and read a file using the SMB library.
I managed to upload the file to the share successfully.
When I try to file_read I get an empty file and the uploaded file size becomes zero.
Inside the smb.file_read function I see that It's always result['data_length'] == 0.
What am I doing wrong?

**Comment by cldrn** [comment]
Did you fix the problem? Was it a bug in smb.lua?
