### ISSUE TITLE
http-ntlm-info.nse script is not working properly

### ISSUE THREAD

**Issue by bransh** [nmap/nmap#922]
Hello,

I'm facing a problem with the http-ntlm-info script. It looks like it is not using the right pattern to obtain the base64 encoded response from the server to feed the decoder.

The following is the command I run to obtain the NTLM information from my target server:
`nmap -p 443 --script http-ntlm-info --script-args http-ntlm-info.root=/autodiscover/ <TARGET> -d`

The following image shows the runtime error obtained from nmap:
![image](https://user-images.githubusercontent.com/24248983/27569550-829b9986-5ace-11e7-8c90-2fe6b9a96a53.png)

Observe that the error message indicates the function base64.dec is not able to decode the input and the problem is related to the line 85 of the http-ntlm-info script. So, by inspecting the indicated line we can see the following sentence:
`local data = base64.dec(string.match(response.header["www-authenticate"], "NTLM (.*)"))`
In order to see what is being received by the decoding function, let's add a "print" to show the result of string.match(...):

The following screenshot shows the content of the string that is being sent to base64.dec function:
![image](https://user-images.githubusercontent.com/24248983/27569787-d0d525ee-5acf-11e7-9f1e-508e1ac5c658.png)

Observe that the script is sending the following pattern to the decoder:
`<base64 string>, Negotiate, Basic realm="<ip>"`
However, it should only send the `<base64 string>` portion, therefore we have to modify the code to something like this:
`local data = base64.dec(string.match(response.header["www-authenticate"], "NTLM ([a-zA-Z0-9///+=]*)"))`

The following screenshot shows the execution of the updated script after applying the suggested modification:
![image](https://user-images.githubusercontent.com/24248983/27569858-544d947e-5ad0-11e7-8d74-9986297313c0.png)

Could you please validate this?

Thanks,

Bransh

**Comment by cldrn** [comment]
Hey! I've confirmed the issue and tested your patch. Thanks for contributing!
