### ISSUE TITLE
npcap 0.92 leaves NPCAP loopback adapter present at uninstall

### ISSUE THREAD

**Issue by Geo-Ron** [nmap/nmap#923]
Hi all,

Thank you for the wifi fix in the current release. You made my day.

But, one issue remains, the NPCAP loopback adapter remains installed.
Attached is the log file.

[NPFInstall.log.txt](https://github.com/nmap/nmap/files/1108874/NPFInstall.log.txt)

My OS is Windows 7 SP1 Pro x64.

Will try in a VirtualBox VM again.

**Comment by Geo-Ron** [comment]
On a VirtualBox VM with only a LAN network adapter the uninstall works fine.

So the problem exists on my laptop with multiple network interfaces.

**Comment by hsluoyz** [comment]
The error is:

```
[00001A00] 2016-12-21 08:44:51 --> wmain
[00001A00] 2016-12-21 08:44:51     _tmain: executing, argv[0] = C:\Program Files\Npcap\NPFInstall.exe.
[00001A00] 2016-12-21 08:44:51     _tmain: executing, argv[1] = -n.
[00001A00] 2016-12-21 08:44:51     _tmain: executing, argv[2] = -ul.
[00001A00] 2016-12-21 08:44:51 --> UninstallLoopbackAdapter
[00001A00] 2016-12-21 08:44:51 --> LoadDevIDFromFile
[00001A00] 2016-12-21 08:44:51 --> GetConfigFilePath
[00001A00] 2016-12-21 08:44:51     GetModuleFileName: succeed, strConfigPath = C:\Program Files\Npcap\loopback.ini.
[00001A00] 2016-12-21 08:44:51 <-- GetConfigFilePath
[00001A00] 2016-12-21 08:44:51     _tfopen_s: error, errCode = 0x00000002.
[00001A00] 2016-12-21 08:44:51 <-- LoadDevIDFromFile
[00001A00] 2016-12-21 08:44:51     iNpcapAdapterID == -1: error.
[00001A00] 2016-12-21 08:44:51 <-- UninstallLoopbackAdapter
[00001A00] 2016-12-21 08:44:51     _tmain: error, nStatus = -1.
[00001A00] 2016-12-21 08:44:51 <-- wmain
```

``C:\Program Files\Npcap\loopback.ini`` is not found. This file is used to record the index of Npcap loopback adapter, so the uninstaller can remove it. Please check the presence of ``C:\Program Files\Npcap\loopback.ini`` after installation.

Then run: ``C:\Program Files\Npcap\NPFInstall.exe -ul`` to manually uninstall the loopback adapter.

**Comment by dmiller-nmap** [comment]
@Geo-Ron Some older versions of the Npcap uninstaller may not have removed the loopback installer properly. As @hsluoyz mentioned, without the `loopback.ini` file, `NPFInstall.exe` cannot find the number of the loopback adapter. You can find this manually: Run [DiagReport](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport) and look for something like:

```
Caption         : [00000021] Microsoft KM-TEST Loopback Adapter
GUID            : {35612D44-55EB-4450-89D2-190E415C10A2}
Index           : 21
InterfaceIndex  : 7
Manufacturer    : Microsoft
NetConnectionID : Npcap Loopback Adapter
PNPDeviceID     : ROOT\NET\0003
```

The `NetConnectionID` must be "Npcap Loopback Adapter". Copy the number from `PNPDeviceID` (in this example, "3") and use Notepad.exe to create the `C:\Program Files\Npcap\loopback.ini` file with this number in it, nothing else. Then, running `C:\Program Files\Npcap\NPFInstall.exe -ul` will remove this adapter.

**Comment by dmiller-nmap** [comment]
Loopback device installation and uninstallation has been improved in recent versions, and we do not anticipate having this problem again. If you still have leftover Loopback Adapters, follow this alternative procedure:

1. Uninstall Npcap.
2. Open Device Manager (`devmgmt.msc`) and navigate to "Network Adapters"
3. Right-click the "Npcap Loopback Adapter" device and choose "Uninstall device." There may be more than one.
4. Install the latest Npcap from https://nmap.org/npcap/#download

If the problem persists with Npcap releases after 0.99-r6, please open a new issue.

**Comment by Cloudthumper** [comment]
I installed npcap when I installed wireshark. I found that wireshark wouldn't work the way I wanted it to so I uninstalled it. After that I found that everytime I reboot my computer I get the BSOD with the following message: IRQL NOT LESS OR EQUAL. Nothing followed, just that. I found what I believe to be the problem: Device Manager > Network adapters > Npcap Loopback Adapter. My every attempt to uninstall, disable, or others remove it results in the same BSOD. I am just short of using Windows Recovery. Please help me get rid of this. Until it's gone, I can't run diagnostics, create an image, etc.

**Comment by fyodor** [comment]
Hi @Cloudthumper.  Please try this:

1. In an Administrator command window, run the command: sc.exe config npcap start=disabled
2. Reboot the system.
3. Uninstall Npcap

**Comment by Cloudthumper** [comment]
Thanks for your help. That worked! Very much appreciated!
