### ISSUE TITLE
ms-sql-info doesn't work with non-default port

### ISSUE THREAD

**Issue by djcater** [nmap/nmap#927]
I'm testing an instance of Microsoft SQL Server which is exposed remotely over TCP, but at a non-default port (33333). Even if I force ms-sql-info to run by using `--script="+ms-sql-info"` the script will only try and connect to UDP port 1434 and TCP port 1433. This happens even if Nmap's service probes have already identified the port as `ms-sql-s`.

If I hack mssql.lua to pretend that the default port is not 1433 but instead port 33333 (`local sqlDefaultPort = ...`), then the script successfully pulls back the right information:

```
Host script results:
| ms-sql-info: 
|   XXX.XXX.XXX.XXX:33333: 
|     Version: 
|       name: Microsoft SQL Server 2012 SP1+
|       number: 11.00.3156.00
|       Product: Microsoft SQL Server 2012
|       Service pack level: SP1
|       Post-SP patches applied: true
|_    TCP port: 33333
```

I'm guessing that is because the script is a host script only.

This information is needed however when the service version probes do not have a match for the specific patch version. For the case above, by running an unmodified Nmap with `-sV --version-all -sC` the results are:

```
PORT      STATE    SERVICE  REASON          VERSION
33333/tcp open     ms-sql-s syn-ack ttl 114 Microsoft SQL Server 2012
```

There is only a soft match for the version and no MS SQL script output other than ms-sql-ntml-info which is for information about the underlying Windows Server. So the detailed version information is not matched in the service / version probes, and then not extracted by the ms-sql-info script (which is in the default category).

This could be solved by adding every missing version to the `nmap-service-probes` file, but it is difficult to keep it up to date. I think it is better to rely on a script such as ms-sql-info to extract the version information. (Requiring `--version-all` is covered by issue #926).

This is using Nmap 7.50.

I hope that explains the problem. Please let me know if you need any further information.

**Comment by cldrn** [comment]
How about using the library argument mssql.instance-all? The rarity level of the mssql probe was decreased, does it solve this issue as we don't longer only have a softmatch?

**Comment by dmiller-nmap** [comment]
The previous commit ought to fix this for now, but I'd like to do a bit more work on the library to allow ms-sql scripts to run as portrules as well as hostrules, so output for TCP instances discovered during version detection will show up under the relevant port. Ideally, a script would not have to know about any of this, but could just define a function that takes a `mssql.SqlServerInstanceInfo` object as input and returns structured output. The library would take care of discovering instances and running this function as a portrule action when necessary, and a hostrule action for all others (named pipes, unscanned ports, etc.)

**Comment by dmiller-nmap** [comment]
In fact, due to that change, mssql-brute will now brute-force some instances twice, since it already used a portrule and hostrule both. Consider these scripts in an unknown state until I update here again. :/

**Comment by dmiller-nmap** [comment]
c3d54f1faca48414798ba0ebb642f7491e545046 ought to straighten everything out and make all the ms-sql NSE scripts work much better:

* All scripts wait to run until broadcast-ms-sql-discover runs, if it is eligible to run.
* Discovery of instances is done with the first non-broadcast script to run, and is not duplicated.
* MS SQL Server ports discovered via `nmap -sV` are included for script execution even if 1434/udp is not open.
* `mssql.Helper.InitScript()` turns a process-one-instance function into action, portrule, and hostrule functions so that script authors do not need to consider details like discovery, named pipes, and output location.

Please let us know if you find any issues with these scripts after these changes.
