### ISSUE TITLE
no make target rule - build-libssh2

### ISSUE THREAD

**Issue by jungle-boogie** [nmap/nmap#929]
Hi,

I see there is a new feature, #910 - Libssh2 + ssh-brute support.

Is this gmake build error expected as a result?

```
ranlib  blas.a
gmake[2]: Leaving directory '/usr/home/sean/bin/nmap/liblinear/blas'
ar rcv liblinear.a linear.o tron.o blas/*.o
a - linear.o
a - tron.o
a - blas/daxpy.o
a - blas/ddot.o
a - blas/dnrm2.o
a - blas/dscal.o
ranlib liblinear.a
gmake[1]: Leaving directory '/usr/home/sean/bin/nmap/liblinear'
gmake: *** No rule to make target 'libssh2/src/Makefile', needed by 'build-libssh2'.  Stop.
```

This is happens on FreeBSD 11-release and openBSD -current. Using `GNU Make 4.2.1` (gmake)

**Comment by jungle-boogie** [comment]
Hi Again,

It looks like `/libssh2/install-sh` doesn't have execute bit enabled and will result in this failure:
```
ar: `u' modifier ignored since `D' is the default (see `U')
gmake[2]: Leaving directory '/usr/home/sean/bin/nmap/libssh2/src'
gmake[1]: Leaving directory '/usr/home/sean/bin/nmap/libssh2/src'
cd libssh2/src && gmake prefix=/usr/home/sean/bin/nmap/libssh2 install-libLTLIBRARIES;
gmake[1]: Entering directory '/usr/home/sean/bin/nmap/libssh2/src'
 .././install-sh -c -d '/usr/home/sean/bin/nmap/libssh2/lib'
/bin/sh: .././install-sh: Permission denied
gmake[1]: *** [Makefile:497: install-libLTLIBRARIES] Error 1
gmake[1]: Leaving directory '/usr/home/sean/bin/nmap/libssh2/src'
gmake: *** [Makefile:144: build-libssh2] Error 2
```

`libpcap/install-sh` does have the execute bit:
`-rwxr-xr-x  1 sean  sean  5578 Dec 30  2016 libpcap/install-sh`

**Comment by dmiller-nmap** [comment]
@jungle-boogie Thanks for reporting this! I confirmed on FreeBSD 11-release. Unfortunately, I then get an error trying to run Nmap:

    route_dst_generic: Failed to obtain system routes: getsysroutes_dnet: route_open() failed

This sort of thing happens on the different Unix varieties when they update route APIs. Do you happen to know what may have changed in FreeBSD 11-release?

**Comment by jungle-boogie** [comment]
hi @dmiller-nmap,

Here's the release notes for 11-release:
https://www.freebsd.org/releases/11.0R/relnotes.html

11.1-release is planned by the end of this month, possibly longer if there's regressions found:
https://www.freebsd.org/releases/11.1R/schedule.html

Here's the 11-release branch of freeBSD on github:
https://github.com/freebsd/freebsd/tree/releng/11.0

I don't receive that error when attempting to run `nmap`, though.
What flags are you setting?

**Comment by dmiller-nmap** [comment]
@jungle-boogie With `nmap --iflist` I get the list of interfaces, then "ROUTES: NONE FOUND(!)", which is typical when libdnet's route retrieval stuff is messed up. It's possible that I was just missing some devel headers and so `configure` guessed wrong. Can I get a copy of your `libdnet-stripped/include/config.h` to see how it differs from mine?

**Comment by jungle-boogie** [comment]
Hi @dmiller-nmap,

Here's the contents of config.h:
https://gist.github.com/jungle-boogie/6c81f1a363693516a489b19d99611745

I'm able to run `nmap --iflist` without an issue.

**Comment by dmiller-nmap** [comment]
I don't know why it works for you, since your config.h has the same problem, namely that `HAVE_NET_ROUTE_H` is not defined, though it should be. I'm working on fixing libdnet's configure script to detect it correctly, but here are some related bugs:

* [FreeBSD 211386](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211386), Kernel build fails when TCP_RFC7413 option set
* troglobit/smcroute#5

**Comment by jungle-boogie** [comment]
Can you run:

`freebsd-version -ku`

And see what it says?

That git issue was closed two years prior to the release of FreeBSD 11.

I start a vagrant image and compile nmap and see what happens.

**Comment by jungle-boogie** [comment]
Hi @dmiller-nmap,

I was able to build `nmap` from source on a vagrant 11.1 RC1 build:

```
% ./nmap --iflist

Starting Nmap 7.50SVN ( https://nmap.org ) at 2017-07-13 06:17 UTC
************************INTERFACES************************
DEV (SHORT) IP/MASK       TYPE     UP MTU   MAC
em0 (em0)   10.0.2.15/24  ethernet up 1500  08:00:27:E8:2D:45
lo0 (lo0)   127.0.0.1/8   loopback up 16384
lo0 (lo0)   ::1/128       loopback up 16384
lo0 (lo0)   fe80:2::1/128 loopback up 16384

ROUTES: NONE FOUND(!)
```

Download the RC of 11.1 here:
https://app.vagrantup.com/freebsd/boxes/FreeBSD-11.1-RC1
Unfortunately 11.1 RC-2 is broken for vagrant.

```sudo pkg install git automake gmake```
Then you can clone, configure and compile nmap.

I do see my original issue was resolved with this commit:
https://github.com/nmap/nmap/commit/4d396c3d2a7d59aa73cac3d79d0363f9670f36d0

I can verify I don't have the error when I compiled on the 11.1 rc-1 build, too.

**Comment by roycewilliams** [comment]
FWIW, with a fresh clean latest tree, and FreeBSD 11.1, I'm no longer getting the libssh2 error.
