### ISSUE TITLE
npcap: Windows 7 BSOD

### ISSUE THREAD

**Issue by Antiever** [nmap/nmap#942]
Just get BSODs in a different situations. The last time I installed  npcap-0.92 with this options:
![npcap-0 92_2017-07-12_22-34-33](https://user-images.githubusercontent.com/9666515/28136413-521be5d2-6752-11e7-83a3-cb2752c6ef0f.png)

than start scapy to test it, during app initialization I've lost my internet connection and after click "connect"... bsod

Here is two minidumps (don't remember for sure my steps for first bsod but looks like reason is same)
`DRIVER_IRQL_NOT_LESS_OR_EQUAL | NDProxy.SYS+b47f | ntoskrnl.exe+70e40`

[Minidump.zip](https://github.com/nmap/nmap/files/1143123/Minidump.zip)

**P.S.**
Don't know for sure if it's related issue but another time I've try to use npcap when I reboot my PC I have no more internet connection with npcap installed (before reboot all works fine). I did not deal with the cause that time, just uninstall npcap and reboot again to fix it.

**Comment by dmiller-nmap** [comment]
Thanks for the bug report! There are no Npcap functions in the minidump,
since the crash was in ndproxy.sys, but it could still be Npcap's fault.
Can you please run the driver verifier that comes with Windows
(verifier.exe) and set default tests for npcap.sys? This ought to force a
bsod from Npcap directly if it does something wrong. If this doesn't work,
we will need the full MEMORY.DMP file.

**Comment by Antiever** [comment]
Install npcap one more time and right after that I've lost my PPPoE connection (as far as I understand, this is exactly what was happened every time), any attempt to connect again always failed with:

```
Opening port...
Error 813: You have attempted to establish a second broadband connection while a previous broadband connection already established using the same device or port
```

My default connection list is:

![explorer_2017-07-15_05-41-03](https://user-images.githubusercontent.com/9666515/28236017-a31e317e-6923-11e7-8d6e-1f060a061518.png)

\+ `Localhost` after npcap

Then I turn off my PC in a usual way from Start menu... bsod

This time `DRIVER_POWER_STATE_FAILURE  ntoskrnl.exe  ntoskrnl.exe+70e40` but crash adress stay the same: `ntoskrnl.exe+70e40`

[071517-18687-01.zip](https://github.com/nmap/nmap/files/1150034/071517-18687-01.zip)

Full dump will be **17**Gb btw, so it's not the most convenient option, but if it will be the only way, than maybe I can dump some parts from it with `Volatility` for you or something like that.
What about verifier, is there some way to made checks **without** PC reboot?

And since the bsods may have a negative effect on hard disks and data, I'm ready to do just one more attempt, let's do it right. Thx.

**Comment by dmiller-nmap** [comment]
Since we have had no updates on this, I am pre-emptively closing this issue. We have solved many BSoD and stability/compatibility issues since Npcap 0.92, so I am hopeful that Npcap is no longer a problem. Please re-open it (or ask us to do so) if you still experience the problem with Npcap 0.99-r6.

**Comment by minhng99** [comment]
@dmiller-nmap Hi, I'm having the exact problem with Npcap 0.9983 running on Windows 7 x64 and VMWare, uninstall the Npcap fixed it for me.

BSoD happened when I try to connect to a PPPoE connection.

![Screenshot from 2019-11-12 04-15-47](https://user-images.githubusercontent.com/14113155/68641598-3de9e180-0503-11ea-8abc-a785aa37dc05.png)

Here is the Kernel memory dump from that BSoD

https://drive.google.com/open?id=19HVpzLWN48X-Y4dGiY8d5ex4_iL0fghu
