### ISSUE TITLE
Invalid (?) fingerprints in nmap-os-db

### ISSUE THREAD

**Issue by tterranigma** [nmap/nmap#946]
I am using honeyd and I pass it the nmap-os-db to read fingerprints. Using the latest nmap-os-db from master, honeyd complained about 3 lines in the file:

1. 

`line 53868: OPS(O1==M400CST11NW1|M400CST11NW2|M400CST11NW3|M400CST11NW4|M400CST11NW5|M400CST11NW6|M400CST11NW7|M400CST11NW8|M400CST11NW9%O2=M400CST11NW1|M400CST11NW2|M400CST11NW3|M400CST11NW4|M400CST11NW5|M400CST11NW6|M400CST11NW7|M400CST11NW8|M400CST11NW9%O3=M400CNNT11NW1|M400CNNT11NW2|M400CNNT11NW3|M400CNNT11NW4|M400CNNT11NW5|M400CNNT11NW6|M400CNNT11NW7|M400CNNT11NW8|M400CNNT11NW9%O4=M400CST11NW1|M400CST11NW2|M400CST11NW3|M400CST11NW4|M400CST11NW5|M400CST11NW6|M400CST11NW7|M400CST11NW8|M400CST11NW9%O5=M400CST11NW1|M400CST11NW2|M400CST11NW3|M400CST11NW4|M400CST11NW5|M400CST11NW6|M400CST11NW7|M400CST11NW8|M400CST11NW9%O6=M400CST11)`

The problem here is the double equals in the beginning after 01.

2.

`line 87693: SEQ(SP=5A-72|87-91%GCD=1-6%ISR=94-9E|C6-D0%TI=I%CI=I%II=I|RI%SS=O|S%TS=U)`

The problem here is the OR with ranges 5A-72|87-91.

3.

`line 87734: SEQ(SP=5C-88|A5-AF%GCD=1-6%ISR=AC-DD%TI=I%CI=I%II=RI%SS=O|S%TS=U)`

The same as the previous one.

I do not know if these the above are valid fingerprint syntax but I just thought I should share my findings.

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out! The first one is an error, and we will
correct it. The other two are valid syntax:
https://nmap.org/book/osdetect-fingerprint-format.html#osdetect-tbl-testops
