### ISSUE TITLE
Nmap NSOCK error - Too many open files

### ISSUE THREAD

**Issue by Kaicastledine** [nmap/nmap#947]
Hello,

Seem to be getting a NSOCK error  as shown below,

`NSOCK ERROR [518.1170s] nsock_make_socket(): Socket Trouble: Too many open files`

Command run - previously worked 

`nmap --script smb* --script-args unsafe=1 192.168.226.20`

I've set ulimit to unlimited for testing and same issue occurs.

Running on the following machine

`Kali linux 2017-06-22 (Debain 4.9.30-2kali1  amd64)`

**Comment by fiht** [comment]
Hi:
u Just search Linux too many open files. and Goole will tell you how to solve it.

And if u just wanner solve it, follow the steps below

## edit /etc/security/limits.conf
append 
```
*         hard    nofile      500000
*         soft    nofile      500000
root      hard    nofile      500000
root      soft    nofile      500000
```
## edit /etc/sysctl.conf
append 
```
fs.file-max = 2097152
```
## fresh it
run command in  terminal
```
sysctl -p
```
## Last step
logout and relogin
## see changes
```
cat /proc/sys/fs/file-max
ulimit -Hn
ulimit -Sn
```
## Referer
https://easyengine.io/tutorials/linux/increase-open-files-limit/
Hope there is some help for you :-D

**Comment by Kaicastledine** [comment]
Still getting the same issue however I've noticed despite the changes 

ulimit -Hn * ulimit -Sn value have not changed after changing the open file confs

**Comment by Kaicastledine** [comment]
Think there is some sort of issues with the changes being ignored.

Seen A few reports of this, will have to give it  a play and see what can be done.

**Comment by sodaphish** [comment]
I've made the changes suggested by fiht and still am experiencing the nsock_make_socket() error.

if I were to guess, its not an issue with ulimit, or other user controlled limitations, but rather an issue in how nmap is creating sockets and/or leaving them open.

**Comment by JayT33** [comment]
From the testing I've done, it seems that "smb-flood.nse" is one of the scripts that causes this error to occur.
