### ISSUE TITLE
Escape or remove angle brackets in CHANGELOG

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#95]
We should probably either fix http://nmap.org/changelog.html so that angle brackets are escaped and displayed. Perhaps this could be done in Javascript or some sort of server side processing.  Or I suppose we could just reword things to keep angle brackets out of the file.  That is what we've traditionally done, though it just kicks the can forward a bit.  Recent example entries with angle brackets include:

o Added options --data <hex string> and --data-string <string> to send custom
  payloads in scan packet data. [Jay Bosamiya]

o Removed the External Entity Declaration from the DOCTYPE in Nmap's XML. This
  was added in 6.45, and resulted in trouble for Nmap XML parsers without
  network access, as well as increased traffic to Nmap's servers. The doctype
  is now:
  <!DOCTYPE nmaprun>

**Comment by fyodor** [comment]
I guess Github didn't escape the angle brackets surrounding option values you're supposed to see after the --data and --data-string option names.

**Comment by dmiller-nmap** [comment]
Fixed this by passing CHANGELOG through an HTML entity encoder before displaying.
