### ISSUE TITLE
Integer size mismatch in service_scan.cc

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#966]
GCC compiler produces the following warning on stock x86 Ubuntu 14.04:
```
service_scan.cc: In function ‘char* substvar(char*, char**, const u8*, int, int*, int)’:
service_scan.cc:874:51: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘u64 {aka long long unsigned int}’ [-Wformat=]
     buflen = Snprintf(buf, sizeof(buf), "%lu", val);
```
The issue is applicable to other platforms as well.

I am proposing the following change, which assures that the format field and the variable are always of the same size (and at least 64 bits):
```diff
--- a/service_scan.cc
+++ b/service_scan.cc
@@ -830,7 +830,7 @@
     }
   } else if (strcmp(substcommand, "I") == 0 ){
     // Parse an unsigned int
-    u64 val = 0;
+    long long unsigned val = 0;
     bool bigendian = true;
     char buf[24]; //0xffffffffffffffff = 18446744073709551615, 20 chars
     int buflen;
@@ -871,7 +871,7 @@
         val = (val<<8) + subject[i];
       }
     }
-    buflen = Snprintf(buf, sizeof(buf), "%lu", val);
+    buflen = Snprintf(buf, sizeof(buf), "%llu", val);
     if (buflen < 0 || buflen > (int) sizeof(buf)) {
       return NULL;
     }
```

I will commit the change in a few weeks unless there are any concerns.

@dmiller-nmap FYI, r36911

**Comment by dmiller-nmap** [comment]
I am worried about a few potential problems with this solution:

* Some platforms may not have `long long unsigned`.
* Some platforms may implement `long long unsigned` as less than 64 bits, but we explicitly require it to be at least 64 bits.

I am aware that some macros are defined for format strings for various types, but I don't know how widely available they are. They are defined in `inttypes.h` according to [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/inttypes.h.html). This seems like something we should be using or defining in nbase, since that's where the `u64` type is defined.

**Comment by nnposter** [comment]
I believe that the C99 standard directly takes care of both bullets. If we wish to support less current standards then of course my patch does not make sense.

**Comment by nnposter** [comment]
According to Wikipedia articles [C Data Types](https://en.wikipedia.org/wiki/C_data_types#Printf_and_scanf_format_specifiers) and [C Standard Library](https://en.wikipedia.org/wiki/C_standard_library) header file `inttypes.h` was also added in C99 so it does not appear that it would provide better backwards compatibility than sticking with `long long unsigned`.

MSVC 2010 is one example where `long long unsigned` exists but `inttypes.h` does not.

**Comment by nnposter** [comment]
@dmiller-nmap Please let me know if my responses have satisfied your concerns or if you still like to proceed the route of `inttypes.h`.

Personally I feel that if we should not rely on guaranteed minimum integer ranges, as defined in C99, then we are implicitly facing a much larger problem across the entire codebase.

**Comment by nnposter** [comment]
@dmiller-nmap I will commit my fix by the end of the week. Please let me know if you want me to hold off.
