### ISSUE TITLE
Npcap: Access violation while multi-threading

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#982]
Hi,

We're having some errors while using multithreading in our program.

We are creating a socket through `pcap_open_live`, sending packets with `pcap_sendpacket` and recieving through `pcap_next_ex`. ([code](https://github.com/secdev/scapy/blob/master/scapy/arch/pcapdnet.py#L140-L178))

Whenever we recieve and send packets at the same time on the same object (using multi-threading), we get the error:
```
  File "scapy\arch\pcapdnet.py", line 175, in send
    pcap_sendpacket(self.pcap, x, len(x))
WindowsError: exception: access violation reading 0x0000000000000170
```

I know this has been a quite common issue in Winpcap, and would like to know if there was any fix/workaround available.

Thanks for answering !

[Scapy related issue](https://github.com/secdev/scapy/pull/770)

**Comment by gpotter2** [comment]
Alright, we found out that creating an pcap_open_live object to read and an object to write would fix the problem.

**Comment by dmiller-nmap** [comment]
I don't see anything in the libpcap API docs or in Packet.dll that prohibits sending and receiving from the same pcap_t, so this is something we'd like to fix if possible. Does the problem happen even when not multithreading? In other words, can you intersperse calls to `pcap_sendpacket` and `pcap_next_ex` if you are single-threading, or does that cause an access violation, too?

Is there any way you could get us a stack trace or crash dump for the process? I don't know at what level the exception is being caught or if it's possible to do. It's not a BSOD, so it's not a driver problem; it's either in wpcap.dll or Packet.dll somewhere.

**Comment by gpotter2** [comment]
Actually, it seems that the bug was on our side :/
