### ISSUE TITLE
Npcap disables Large Send Offloading and Checksum Offloading with no option to re-enable

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#989]
Documenting an issue just before it is fixed: Npcap 0.93 and earlier forcibly disables Large Send Offloading and Checksum Offloading (and possibly TCP Chimney Offloading). This is because these features of Windows and certain NICs cause Npcap to see a different view of outgoing packets than what really passes to the network. This effect is [documented by Microsoft](https://blogs.technet.microsoft.com/onthewire/2014/01/21/tcp-offloadingchimney-rsswhat-is-it-and-should-i-disable-it/) and [elsewhere](https://serverfault.com/a/65964/112426).

The problem with this is that some users have a need to keep this feature enabled, but it is forcibly disabled on all interfaces where Npcap is enabled, even if those interfaces are not actively sniffing. We intend, therefore, to revert the commit b4ac6c5c that introduced offload disabling. We will document this in the Npcap Users' Guide and allow users to disable these features on their own network adapters as necessary.

**Comment by dmiller-nmap** [comment]
This has been fixed in Npcap 0.94. Npcap no longer disables these NIC features. Some users may experience differences between captured and on-the-wire packets, and should manually disable these features in their network card driver.

**Comment by oldium** [comment]
Just for you to know, this "feature" in pre-0.94 versions prevented my laptop from sleeping - I had Wake-on-Wlan enabled, all offloading features were enabled, but when Wifi rekeying happened, the computer woke up. After upgrading to current latest (0.95), computer slept the whole night. Finally I know the reason. Thanks for fixing this.
