### ISSUE TITLE
No monitor mode on Wireshark, Windows 10

### ISSUE THREAD

**Issue by natiya** [nmap/nmap#990]
I have the same problem as in [this issue](https://github.com/nmap/nmap/issues/757) but I did what it work there and it doesn't work for me.

These are my system details:

OS version: Windows 10
Wireshark version: Version 2.4.0 (v2.4.0-0-g9be0fa500d)
Npcap version: 0.93
WinPcap version: 5.0.93 (the one is installed with Npcap)

I also tried Npcap 0.9 as it says in the thread I mentioned about, but it didn't work either.

In addition, when using WlanHelper.exe, I get this error:

![image](https://user-images.githubusercontent.com/31421016/29793427-0e157d46-8c44-11e7-8a65-aa7f09e7e038.png)
 But when I installed Npcap, I checked the "Support raw 802.11 traffic..." option.
I attached the 2 log files that I have.

Thank you!

[install.txt](https://github.com/nmap/nmap/files/1258381/install.txt)
[NPFInstall.txt](https://github.com/nmap/nmap/files/1258382/NPFInstall.txt)

**Comment by hsluoyz** [comment]
Please do not use the names in the example (``42dfd47a-2764-43ac-b58e-3df569c447da`` or ``Wireless Network Connection``. Your actual wireless interface names are probably not the same as them.

You can get your GUIDs and interface names via: ``WlanHelper.exe -i``. Then try these names with your command again.

**Comment by huzaifazafar108** [comment]
Was this issue resolved? I'm facing the same issue.

**Comment by huzaifazafar108** [comment]
When I use Wlanhelper to change the mode, it gives me an error:

C:\Windows\System32\Npcap>WlanHelper **247aff08-3647-4ed0-b8cb-b426d056f67a mode monitor
Error: SetWlanOperationMode::SetInterface error, error code = 50 (The request is not supported)
Failure**

**Comment by huzaifazafar108** [comment]
BTW I am using Netgear A7000 instead of A6210. Is that the problem?

**Comment by dmiller-nmap** [comment]
We are now tracking compatibility with various WiFi adapters on SecWiki at the Npcap/WiFi adapters page. Please ensure you are using the latest Npcap and follow the directions there for determining level of WiFi capture support. You may update this issue, edit the SecWiki page, or email us directly at dev@nmap.org with adapter info.
