### ISSUE TITLE
Typos in online documentation

### ISSUE THREAD

**Issue by meetinthemiddle-be** [nmap/nmap#992]
On the online man page for "Timing and performance" (https://nmap.org/book/man-performance.html) I noticed a few spelling/style mistakes. I will mark my proposed adaptions with bold marks (e.g. **proposed change**):

----------------

§  --max-retries
"While this benefits accuracy, it also lengthen scan times." 

Proposal: 
"While this benefits accuracy, it **will** also lengthen scan times."
----------------

§ --script-timeout
"Some scripts take long time before they complete their execution, this can happen due to many reasons maybe some bug in script, delay in the network or nature of the script itself(example:http-slowloris). If you want to keep some limit on time for which script should run then you need to specify --script-timeout with the maximum amount of time for which script should be run. Note that all scripts will have same timeout. Once script gets timed out no output for that script will be shown. Whether a script has timed out or not, can be seen in debug output.  "

Proposal:
"Some scripts take **a** long time before they complete their execution**. This** can happen due to many reasons**. M**aybe some bug in **a** script, delay in the network or nature of the script **itself ( for example: http-slowloris)**. If you want to keep some limit on **the** time for which **a** script should **run, ** you need to specify --script-timeout with the maximum amount of time for which **any** script should be run. Note that all scripts will have **the** same timeout. Once **a** script gets timed **out, no* output for that script will be shown. Whether a script has timed out or not, can be seen in debug output. "

Also, nowhere does it say whether this value is interpreted as seconds or milliseconds or if this can be explicitly set as in "--script-timeout 100ms" or "--script-timeout 0.1s" to demand a value of one-tenth of a second.

----------------

§ -T paranoid|sneaky|polite|normal|aggressive|insane

"... than the scan you are trying to optimize. So Nmap offers a simpler approach, with six timing templates."

Proposal:
... than the scan you are trying to **optimize, so** Nmap offers a simpler approach, with six timing templates.
----------------

"... controls, and the fine-grained controls will you specify will take precedence over the timing template default for that parameter."

Proposal:
"... controls, and the fine-grained controls **that** you specify will take precedence over the timing template default for that parameter."

**Comment by fyodor** [comment]
(just as a quick update to my checkin--I did manage to get the --script-timeout option working after more testing.  I'm not sure what the problem was). Cheers.

**Comment by meetinthemiddle-be** [comment]
The problem is the text in the documentation, not the functionality of the program.

**Comment by fyodor** [comment]
@meetinthemiddle-be yes, sorry for the confusion.  I guess my previous commit text didn't make it here.  Anyway, it said: "Rewrite the --script-timeout documentation text (even though this option, which was added last year, isn't currently working for me) and also made another slight typo fix to --max-retries doc.  This was all suggested by @meetinthemiddle-be on Github."  My followup comment here was just noted that --script-timeout is working for me now.  Please note that the documentation fixes won't be reflected online until we next regenerate from the XML source.
