### ISSUE TITLE
Npcap: feature request: select function

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#993]
Hello all, @hsluoyz 

Just asking if the *famous* `select` function could be added to npcap ?
This function would wait until a packet is available to read, and return. It would be callable with a `pcap_open` object.

We would definatly need it in our program: I tried to emulate its behavior by using a `WaitForSingleObject` trick or similar, but it seems that it conflicts with Npcap itself, so I couldn't implement it on our side...

I guess that by using something like `PacketReceivePacket(p->adapter, p->Packet, TRUE)`, it wouldn't be too hard to achieve.

Would be really great to have it ! (and btw a great reason for switching to npcap)

Thanks a lot in advance !

**Comment by hsluoyz** [comment]
Hi @gpotter2 ,

The Windows alternative for ``select`` is just ``WaitForSingleObject`` you mentioned. Why it conflicts with Npcap itself? I'm not very familar with it but does libpcap have a function for it like pcap_read_packet_block()? Because you know Npcap follows latest libpcap API now. All exposed API should go through libpcap. Even if ``PacketReceivePacket`` can work out, it needs to be provided in libpcap.

**Comment by gpotter2** [comment]
For instance, I tried using (in python)
```
handlers = [pcap_getevent(s.[stuff]) for s in sockets]
# s.stuff... is a pcap_open_live object
status = ctypes.windll.kernel32.WaitForMultipleObjects(len(sockets), (ctypes.c_int*len(handlers))(*handlers), ctypes.c_bool(False), int(timeout*1000))
```
This always return WAIT_TIMEOUT (=0x00000102). Same using WaitForSingleObject  (implementation is a bit different). Using INFINITE (=0xFFFFFFFF) never returns.

The question is why.

It seems that if one do two WaitFor... calls at the same time, this kind of bug can appear...

I think https://github.com/nmap/npcap/blob/2337a918ff9299526968842c58fe2afbb9c46db5/packetWin7/Dll/Packet32.cpp#L3145 or similar, could be the reason of this :/

**Comment by gpotter2** [comment]
I also discovered that the previous example works if the buffer has many packets in it.
- when it has only a few things in it, previous example fails
- when it has many stuff, it succeeds.

Could you try to show me a working example of what the doc says:
https://www.winpcap.org/docs/docs_40_2/html/group__wpcapfunc.html#g2c415e9192c7b18a81a02300ae6f2c02
I cannot make any that works :/

**Comment by dmiller-nmap** [comment]
You can check out [Nmap's implementation of a `pcap_select` function](https://github.com/nmap/nmap/blob/6ee953a5ff05af635af762c8d7059319161e70f7/libnetutil/netutil.cc#L964) that does this in a cross-platform manner. It uses `WaitForSingleObject` on the event returned by the Npcap API function `pcap_getevent`.
