### ISSUE TITLE
Cosmetic MSVC warnings: "possible loss of data"

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#995]
MSVC produces a few cosmetic warnings "*possible loss of data*" when converting between integers and floating point numbers.

The following patch takes care of the noise by adding explicit type casting:
```diff
--- a/nmap.cc
+++ b/nmap.cc
@@ -748,7 +748,7 @@
         o.scripthelp = true;
         o.chooseScripts(optarg);
       } else if (optcmp(long_options[option_index].name, "script-timeout") == 0) {
-        l = tval2secs(optarg);
+        l = (long)tval2secs(optarg);
         if ( l < 0 )
           fatal("Bogus --script-timeout argument specified");
         delayed_options.pre_scripttimeout = l;
--- a/FPEngine.cc
+++ b/FPEngine.cc
@@ -320,7 +320,7 @@
    value of ssthresh is held constant.
  */
   int probes_outstanding = this->probes_sent - this->responses_recv - this->probes_timedout;
-  this->cc_ssthresh = MAX(probes_outstanding, OSSCAN_INITIAL_CWND);
+  this->cc_ssthresh = (float)MAX(probes_outstanding, OSSCAN_INITIAL_CWND);
   this->cc_cwnd = OSSCAN_INITIAL_CWND;
   return OP_SUCCESS;
 }
@@ -1495,8 +1495,8 @@
   *
   *  RTO <- SRTT + max (G, K*RTTVAR)
   */
-    this->rttvar = ((1.0 - 0.25) * this->rttvar) + (0.25 * ABS(this->srtt - measured_rtt_usecs));
-    this->srtt = ((1.0 - 0.125) * this->srtt) + (0.125 * measured_rtt_usecs);
+    this->rttvar = (int)(((1.0 - 0.25) * this->rttvar) + (0.25 * ABS(this->srtt - measured_rtt_usecs)));
+    this->srtt = (int)(((1.0 - 0.125) * this->srtt) + (0.125 * measured_rtt_usecs));
     this->rto = this->srtt + MAX(500000, 4*this->rttvar);
   }
 
--- a/lpeg.c
+++ b/lpeg.c
@@ -2178,7 +2178,7 @@
   int n;
   lua_rawgeti(L, -1, t->key);  /* get rule's name */
   lua_gettable(L, postable);  /* query name in position table */
-  n = lua_tonumber(L, -1);  /* get (absolute) position */
+  n = (int)lua_tonumber(L, -1);  /* get (absolute) position */
   lua_pop(L, 1);  /* remove position */
   if (n == 0) {  /* no position? */
     lua_rawgeti(L, -1, t->key);  /* get rule's name again */
```
Please let me know if you have any concerns. Otherwise I will commit the patch in a few weeks.

**Comment by dmiller-nmap** [comment]
My only concern (and the reason I didn't do anything about it previously) is that I don't know if there really is a better way to do it, or whether we should be explicitly checking for overflow. Here are my guesses for these specific instances:

* For script-timeout, we could easily add a check for LONG_MAX to be sure of it, though that's directly user-entered value, very unlikely it would ever be a problem.
* For congestion control, I don't think the threshold is in any danger of overflow, since it's got a MAX check there. And we use an `int` for it in port scanning, so `float` ought to be able to handle it no problem. As a threshold, any loss of precision is probably not significant.
* For RTT calculations, `2^31` microseconds is 35 minutes. Very unlikely we'd ever hit something like that, but it *is* currently possible. In timing.cc, we ensure the timeout is never greater than `o.maxRttTimeout()`, but in FPEngine.cc we do not. This probably should be corrected.
* For things like lpeg, it's overwhelmingly unlikely we'd ever have a pattern with that many rules. However, we could avoid the cast if we just declare `n` to be a `lua_Number`, which is a macro for whatever base type is used for Lua numbers in the build.

**Comment by nnposter** [comment]
Here is the patch for the first item. Notes:
* The conversion to `long` seems completely unnecessary. The value is later assigned to `pre_scripttimeout`, which is of type `double`. I still implemented the test against `LONG_MAX` for general sanity.
* A similar issue can be seen for `--stats-every` where the assignment is done to `stats_interval`, which is of type `float`. I implemented the same test for consistency, implicitly taking care of any overflow.
```diff
* Adds protection against dealing with excessive time specifications.
  As a side effect it silences current MSVC compiler warning about
  "possible loss of data"
  (r????, https://github.com/nmap/nmap/issues/995)
--- a/nmap.cc
+++ b/nmap.cc
@@ -748,10 +748,10 @@
         o.scripthelp = true;
         o.chooseScripts(optarg);
       } else if (optcmp(long_options[option_index].name, "script-timeout") == 0) {
-        l = tval2secs(optarg);
-        if ( l < 0 )
+        d = tval2secs(optarg);
+        if (d < 0 || d > LONG_MAX)
           fatal("Bogus --script-timeout argument specified");
-        delayed_options.pre_scripttimeout = l;
+        delayed_options.pre_scripttimeout = d;
       } else
 #endif
         if (optcmp(long_options[option_index].name, "max-os-tries") == 0) {
@@ -1053,8 +1053,8 @@
           o.adler32 = true;
         } else if (optcmp(long_options[option_index].name, "stats-every") == 0) {
           d = tval2secs(optarg);
-          if (d < 0)
-            fatal("Argument to --stats-every cannot be negative.");
+          if (d < 0 || d > LONG_MAX)
+            fatal("Bogus --stats-every argument specified");
           o.stats_interval = d;
         } else if (optcmp(long_options[option_index].name, "disable-arp-ping") == 0) {
           o.implicitARPPing = false;
```

**Comment by nnposter** [comment]
Here is the patch for the third bullet. Notes:
* The original code is relatively safe as far as overflow because the assignment to `int` represents a weighted arithmetic average of two `int` values. An edge overflow is theoretically possible due to loss of precision when dealing with floating point numbers.
* I have replaced the floating point arithmetic with pure integers, which removes both the edge case and the need for explicit type casting.
* Any concern over how these numbers should relate to `o.maxRttTimeout()` is IMHO a separate issue.
```diff
--- a/FPEngine.cc
+++ b/FPEngine.cc
@@ -1495,8 +1495,8 @@
   *
   *  RTO <- SRTT + max (G, K*RTTVAR)
   */
-    this->rttvar = ((1.0 - 0.25) * this->rttvar) + (0.25 * ABS(this->srtt - measured_rtt_usecs));
-    this->srtt = ((1.0 - 0.125) * this->srtt) + (0.125 * measured_rtt_usecs);
+    this->rttvar += (ABS(this->srtt - measured_rtt_usecs) - this->rttvar) >> 2;
+    this->srtt += (measured_rtt_usecs - this->srtt) >> 3;
     this->rto = this->srtt + MAX(500000, 4*this->rttvar);
   }
 
```

**Comment by nnposter** [comment]
Your comment on the fourth item makes sense but the surrounding code seems mildly suspect to me:
* AFAICT, `lua_Number` is currently an alias for `double` so the whole underlying issue for "*possible loss of data*" would get shifted a few lines down to `t->u.ps = n - (t - g);` because the left side of the assignment is an `int`. (For some reason MSVC does *not* complain about it though.)
* I also do not like how the `ps` assignment is commingling floating-point number `n` with pointer arithmetic `(t - g)`.
* This whole file appears to represent imported code from the [LPeg](http://www.inf.puc-rio.br/~roberto/lpeg/) project. I have looked at the most recent version, 1.0.1, but the same `int n` declaration and the assignment are still there.

I might be missing something but currently I am inclined either to minimize the code changes and go forward with the originally proposed explicit cast to `int` or to leave the code completely as is (and tolerate the MSVC warning).

**Comment by dmiller-nmap** [comment]
*`nmap.cc`*: Looks good.

* `FPEngine.cc`*: This is a nice fix. I added #1007 for the max-rtt-timeout issue, and noted that we should try to combine functions with those in timing.cc if possible.

*LPeg*: I agree with keeping changes minimal. Go ahead and add the cast, but if you can think of a better way to ensure we don't overflow, (e.g. checking vs `INT_MAX`), then that sounds good, too.
