### ISSUE TITLE
ncat documentation is not sufficiently covering SOCKS5 proxying

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#996]
The current ncat manpage-like files are not covering the SOCKS5 proxy functionality.

@dmiller-nmap Dan, I do not mind fixing the documentation but it is not clear to me which file is the master and what tools are used to produce the remaining formats. Do you have any guidance?

**Comment by dmiller-nmap** [comment]
The xml files are the source, written in DocBook XML. Any edits will be reflected in the nroff man pages when those are updated, usually around release time.

**Comment by fyodor** [comment]
@nnposter -- great catch about SOCKS5.  Yeah, if you could add that, it would be great.  The Ncat man page is generated from ncat/docs/ncat.xml.  Sometimes installing DocBook and such is a pain, so if you just update ncat.xml, we can regenerate the HTML and Nroff versions later.  Cheers!

**Comment by nnposter** [comment]
Sure. Changes are actually needed in both `ncat.xml` and `ncatguide.xml`. I have already put the patch together over the last weekend and I plan to commit it sometime next week (together with my other outstanding patches).
